Repository kubernetes/minikube, pull requests merged in 2018-04, with the labels that each got.

#2664 Bump the minikube ISO version.
  Makefile
Labels: approved, cncf-cla: yes, size/XS

#2675 Switch the docker stop command to a docker kill.
  hack/jenkins/common.sh
  pkg/drivers/none/none.go
  pkg/minikube/bootstrapper/kubeadm/kubeadm.go
  pkg/minikube/bootstrapper/kubeadm/templates.go
  pkg/minikube/constants/constants.go
Labels: approved, cncf-cla: yes, size/M

#2682 kubeadm: increase mark master timeout
  pkg/minikube/bootstrapper/kubeadm/kubeadm.go
Labels: approved, cncf-cla: yes, size/XS

#2684 Pass 2: k8s GCR vanity URL
  deploy/addons/addon-manager.yaml
  deploy/addons/efk/elasticsearch-rc.yaml
  deploy/addons/efk/fluentd-es-rc.yaml
  deploy/addons/metrics-server/metrics-server-deployment.yaml
  deploy/docker/README.md
  pkg/minikube/constants/constants.go
  pkg/minikube/machine/cache_images.go
Labels: cncf-cla: yes, size/S

#2669 Cut the 0.26.0 release.
  CHANGELOG.md
  Makefile
Labels: approved, cncf-cla: yes, size/S

#2697 Add the recent localkube releases.
  deploy/minikube/k8s_releases.json
Labels: approved, cncf-cla: yes, size/XS

#2695 Correct the returned message
  deploy/minikube/release_sanity_test.go
Labels: cncf-cla: yes, size/XS

#2710 Correction in KVM2 installation instructions
  docs/drivers.md
Labels: cncf-cla: no, size/XS

#2701 Fix inconsistent version.
  deploy/addons/registry-creds/registry-creds-rc.yaml
Labels: cncf-cla: yes, size/XS

#2714 Fix some typo in Makefile
  Makefile
Labels: cncf-cla: yes, size/XS

#2719 Update docker-machine for hyper-v fix.
  Godeps/Godeps.json
  vendor/github.com/docker/machine/drivers/hyperv/hyperv.go
  vendor/github.com/docker/machine/drivers/hyperv/powershell.go
  vendor/github.com/docker/machine/libmachine/cert/bootstrap.go
  vendor/github.com/docker/machine/libmachine/cert/cert.go
Labels: approved, cncf-cla: yes, size/L

#2721 Use --skip-preflight-checks for k8s < 1.9
  pkg/minikube/bootstrapper/kubeadm/kubeadm.go
  pkg/minikube/bootstrapper/kubeadm/templates.go
Labels: cncf-cla: yes, size/S

#2702 switch filepath.join for path.join
  pkg/minikube/bootstrapper/kubeadm/versions.go
Labels: cncf-cla: yes, size/XS

#2724 Fix gofmt.
  pkg/minikube/bootstrapper/kubeadm/kubeadm.go
Labels: approved, cncf-cla: yes, size/S

#2725 Fixed extra-config RBAC example
  docs/configuring_kubernetes.md
Labels: cncf-cla: yes, size/XS

#2723 Add the CRI preflight ignore, lost in refactoring
  pkg/minikube/bootstrapper/kubeadm/kubeadm.go
  pkg/minikube/constants/constants.go
Labels: cncf-cla: yes, size/S

#2728 Add none driver to the supported list.
  pkg/minikube/constants/constants.go
Labels: approved, cncf-cla: yes, size/XS

#2740 Cut 0.26.1 release
  CHANGELOG.md
  Makefile
Labels: approved, cncf-cla: yes, size/XS

#2745 Disable dnsmasq on minikube-net network for kvm driver
  pkg/drivers/kvm/network.go
Labels: cncf-cla: yes, size/XS

#2761 some small typo fixes
  deploy/iso/minikube-iso/package/crio-bin/crio.conf
  pkg/minikube/cluster/cluster.go
  pkg/util/kubeconfig/config.go
  third_party/go9p/srv_srv.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#2774 Typo fix: Seperated list->Separated list
  cmd/minikube/cmd/config/configure.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2759 Fix error message format for enabling/disabling addon
  cmd/minikube/cmd/config/util.go
Labels: cncf-cla: yes, size/XS
