Repository kubernetes/minikube, pull requests merged in 2018-08, with the labels that each got.

#3035 Fix typo in README
  README.md
Labels: cncf-cla: yes, size/XS

#3034 remove r2d4 from brew PR comment
  hack/jenkins/release_update_installers.sh
Labels: approved, cncf-cla: yes, size/XS

#3049 Create LICENSE
  logo/LICENSE
Labels: cncf-cla: yes, size/XS

#3050 Revert "Remove untainting logic."
  pkg/minikube/bootstrapper/kubeadm/kubeadm.go
  pkg/minikube/bootstrapper/kubeadm/util.go
Labels: cncf-cla: yes, size/M

#3047 Replace 9p mount calls to syscall.Rename with os.Rename, which is capable of renaming on top of existing files.
  third_party/go9p/ufs_darwin.go
  third_party/go9p/ufs_linux.go
  third_party/go9p/ufs_windows.go
Labels: cncf-cla: yes, size/XS

#3061 Update logo_white.svg
  logo/logo_white.svg
Labels: cncf-cla: yes, size/XS

#3073 Update CoreDNS deployment
  deploy/addons/coredns/coreDNS-controller.yaml
Labels: cncf-cla: yes, size/XS

#3081 Update persistent_volumes.md
  docs/persistent_volumes.md
Labels: cncf-cla: yes, size/XS

#3082 updated readme for Windows installation
  README.md
Labels: cncf-cla: yes, size/S

#3072 Make CoreDNS default addon
  pkg/minikube/assets/addons.go
Labels: cncf-cla: yes, size/XS

#3029 Fix vmwarefusion driver
  Godeps/Godeps.json
  vendor/github.com/docker/machine/drivers/hyperv/hyperv.go
  vendor/github.com/docker/machine/drivers/vmwarefusion/fusion_darwin.go
  vendor/github.com/docker/machine/libmachine/ssh/client.go
Labels: cncf-cla: yes, size/L

#3045 update owners
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS
