Repository kubernetes/minikube, pull requests merged in 2018-11, with the labels that each got.

#3297 Fix typo：miniube-iso -> minikube-iso
  pkg/util/downloader.go
Labels: cncf-cla: yes, size/XS

#3280 Remove newline at the start of zsh completion file
  cmd/minikube/cmd/completion.go
Labels: cncf-cla: yes, size/XS

#3261 Update README.md
  README.md
Labels: cncf-cla: yes, size/XS

#3302 Fix some typos
  docs/contributors/adding_driver.md
  pkg/minikube/registry/registry.go
  pkg/util/kubeconfig/config.go
Labels: cncf-cla: yes, size/XS

#3322 Add timeout when reading dashboard host:port from kubectl
  cmd/minikube/cmd/dashboard.go
Labels: approved, cncf-cla: yes, size/M

#3331 trivial fix: Correct some spelling errors
  docs/drivers.md
  docs/tunnel.md
Labels: cncf-cla: yes, size/XS

#3317 Modify the correct function name
  pkg/minikube/bootstrapper/fake_runner.go
Labels: cncf-cla: yes, size/XS

#3316 Update document for new drivers
  docs/contributors/adding_driver.md
Labels: cncf-cla: yes, size/XS

#3305 Added missing dependency to docs
  README.md
Labels: cncf-cla: yes, size/XS

#3313 Upgrade to crio v1.11.8
  deploy/iso/minikube-iso/package/crio-bin/crio-bin.hash
  deploy/iso/minikube-iso/package/crio-bin/crio-bin.mk
Labels: approved, cncf-cla: yes, size/S

#3315 fix logging calls
  pkg/minikube/notify/notify.go
  pkg/minikube/tunnel/tunnel_manager.go
  pkg/util/kubernetes.go
Labels: cncf-cla: yes, size/XS

#3154 Add config parameter for the cri socket path
  cmd/minikube/cmd/start.go
  docs/alternative_runtimes.md
  pkg/minikube/bootstrapper/kubeadm/kubeadm.go
  pkg/minikube/bootstrapper/kubeadm/templates.go
  pkg/minikube/config/types.go
Labels: cncf-cla: yes, size/M

#3211 Stop docker daemon, when running cri-o
  cmd/minikube/cmd/env.go
  cmd/minikube/cmd/start.go
Labels: cncf-cla: yes, size/M

#3346 Fix error formatting
  cmd/minikube/cmd/start.go
Labels: approved, cncf-cla: yes, size/XS

#3335 Remove obsoleted job types so that they no longer show as pending
  hack/jenkins/minikube_set_pending.sh
Labels: approved, cncf-cla: yes, size/XS

#3343 Restart containerd after stopping alternate runtimes
  cmd/minikube/cmd/start.go
  pkg/minikube/bootstrapper/kubeadm/kubeadm.go
  pkg/minikube/constants/constants.go
Labels: cncf-cla: yes, size/M

#3266 Fix invalid build result comparison in the cross build script
  hack/jenkins/minikube_cross_build_and_upload.sh
Labels: approved, cncf-cla: yes, size/M

#3314 Add timeout to testDashboard, skip testTunnel if sudo password is required.
  test/integration/addons_test.go
  test/integration/mount_test.go
  test/integration/tunnel_test.go
Labels: approved, cncf-cla: yes, size/M

#3349 Fix `minikube tunnel` for hyperkit
  cmd/minikube/cmd/start.go
  pkg/minikube/tunnel/cluster_inspector.go
  pkg/minikube/tunnel/reporter_test.go
  pkg/minikube/tunnel/route_darwin.go
  pkg/minikube/tunnel/route_darwin_test.go
  pkg/minikube/tunnel/route_linux.go
  pkg/minikube/tunnel/route_linux_test.go
  pkg/minikube/tunnel/route_windows.go
  pkg/minikube/tunnel/route_windows_test.go
  pkg/minikube/tunnel/tunnel.go
  pkg/minikube/tunnel/tunnel_test.go
  pkg/provision/buildroot.go
  test/integration/tunnel_test.go
  test/integration/util/util.go
Labels: approved, cncf-cla: yes, size/L

#3361 Removed '$' symbols for easier copy&paste (trivial fix)
  docs/drivers.md
Labels: cncf-cla: yes, size/S

#3363 debugging improvements and flakiness reduction
  cmd/minikube/cmd/tunnel.go
  pkg/minikube/bootstrapper/kubeadm/util.go
  pkg/minikube/bootstrapper/ssh_runner.go
  pkg/minikube/constants/constants.go
  pkg/minikube/service/service.go
  pkg/minikube/service/service_test.go
  test/integration/tunnel_test.go
Labels: approved, cncf-cla: yes, size/S

#3365 Update Ingress-NGINX to 0.21 Release
  deploy/addons/ingress/ingress-dp.yaml
Labels: cncf-cla: yes, size/XS

#3287 Implement a check to see if an ISO URL is valid
  cmd/minikube/cmd/config/config.go
  cmd/minikube/cmd/config/validations.go
  cmd/minikube/cmd/config/validations_test.go
Labels: approved, cncf-cla: yes, size/M

#3350 Restrict TestDocker commands to 10 minutes of total runtime.
  test/integration/docker_test.go
  test/integration/util/util.go
Labels: approved, cncf-cla: yes, size/M

#3368 Adding ARCH variable to download kubeadm/kubelet binaries
  pkg/minikube/constants/constants.go
Labels: cncf-cla: yes, lgtm, size/XS

#3370 even longer timeout + timeout error is retriable now
  pkg/minikube/bootstrapper/kubeadm/util.go
  pkg/minikube/constants/constants.go
  test/integration/tunnel_test.go
Labels: approved, cncf-cla: yes, size/S

#3369 removing Windows check temporarily
  hack/jenkins/minikube_set_pending.sh
Labels: approved, cncf-cla: yes, size/XS

#3303 none driver: Only require docker for the docker runtime
  README.md
  cmd/minikube/cmd/start.go
  pkg/drivers/none/none.go
  pkg/minikube/config/types.go
  pkg/minikube/drivers/none/driver.go
Labels: cncf-cla: yes, size/M

#3382 Refactor test harness to isolate test outputs
  hack/jenkins/common.sh
  hack/jenkins/print-debug-info.sh
Labels: approved, cncf-cla: yes, size/L
