Repository kubernetes/minikube, pull requests merged in 2018-05, with the labels that each got.

#2779 Typo fix: occured->occurred
  third_party/go9p/srv_file.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2784 Typo fix: priviledges->privileges
  pkg/drivers/none/none.go
Labels: cncf-cla: yes, size/XS

#2780 Update nginx ingress controller to 0.14.0
  deploy/addons/ingress/ingress-rc.yaml
Labels: cncf-cla: yes, size/XS

#2788 Switch ingress replication controller to deployment
  deploy/addons/ingress/ingress-dp.yaml
Labels: cncf-cla: yes, size/S

#2791 Fix 1.9.x versions of Kubernetes.
  pkg/minikube/bootstrapper/kubeadm/templates.go
  pkg/minikube/bootstrapper/kubeadm/versions.go
Labels: approved, cncf-cla: yes, size/XS

#2806 Start the default network for the kvm2 driver.
  pkg/drivers/kvm/network.go
Labels: approved, cncf-cla: yes, size/M

#2782 Build container for ISO uses ubuntu:18.04
  deploy/iso/minikube-iso/Dockerfile
Labels: cncf-cla: yes, size/S

#2809 Cut 0.27.0
  CHANGELOG.md
  Makefile
Labels: approved, cncf-cla: yes, size/S

#2820 Move the etc data directory to data/minikube to make cleanup safer.
  pkg/drivers/none/none.go
  pkg/minikube/bootstrapper/kubeadm/kubeadm.go
  pkg/minikube/bootstrapper/kubeadm/kubeadm_test.go
Labels: approved, cncf-cla: yes, size/S

#2812 Use correct link for available configmap options
  deploy/addons/ingress/ingress-configmap.yaml
Labels: cncf-cla: yes, size/XS

#2824 Fix cached images not loading on Windows
  pkg/minikube/machine/cache_images.go
Labels: cncf-cla: yes, size/XS

#2821 Bump the heapster to v1.5.3
  deploy/addons/heapster/heapster-rc.yaml
Labels: cncf-cla: yes, size/XS

#2823 Give certificates some NotBefore leeway for VMs clocks that lag host clocks
  pkg/util/crypto.go
Labels: cncf-cla: yes, size/XS

#2822 Update pre-cache images to correct version
  pkg/minikube/constants/constants.go
Labels: cncf-cla: yes, size/S

#2839 Add security contacts.
  SECURITY_CONTACTS
Labels: approved, size/S

#2842 make: Don't hardcode GOARCH in Makefile
  Makefile
Labels: cncf-cla: yes, size/XS

#2836 Update CoreDNS manifest
  deploy/addons/coredns/coreDNS-configmap.yaml
  deploy/addons/coredns/coreDNS-controller.yaml
  deploy/addons/coredns/coreDNS-svc.yaml
Labels: cncf-cla: yes, size/S

#2843 kubeadm: Check for GetClientset error
  pkg/minikube/bootstrapper/kubeadm/util.go
Labels: cncf-cla: yes, size/XS

#2856 Update release docs' OSX installation method
  hack/jenkins/release_github_page.sh
Labels: cncf-cla: yes, size/XS
