Repository kubernetes/minikube, pull requests merged in 2018-09, with the labels that each got.

#3065 Allow certificates to be optionally embedded in .kube/config
  cmd/minikube/cmd/config/config.go
  cmd/minikube/cmd/start.go
  pkg/minikube/bootstrapper/certs.go
  pkg/util/kubeconfig/config.go
Labels: cncf-cla: yes, size/M

#3003 Add workaround for dnsmasq and hyperkit users to drivers readme
  docs/drivers.md
Labels: cncf-cla: yes, size/XS

#2671 fix(cli): `minikube start --mount --mountsting` without write permission
  pkg/minikube/cluster/cluster.go
Labels: cncf-cla: yes, lifecycle/rotten, size/XS

#3086 Add env variable for default ES_JAVA_OPTS
  deploy/addons/efk/elasticsearch-rc.yaml
Labels: cncf-cla: yes, size/XS

#3101 Correct typo in the returned message
  pkg/drivers/kvm/gpu.go
Labels: cncf-cla: yes, size/XS

#3121 Change default docker storage driver to overlay2
  pkg/minikube/machine/client.go
Labels: cncf-cla: yes, size/XS

#3105 Stay in same line
  cmd/util/util.go
Labels: cncf-cla: yes, size/XS

#3114 fix: --format outputs any string, --https only subsitute http URL scheme
  pkg/minikube/service/service.go
  pkg/minikube/service/service_test.go
Labels: cncf-cla: yes, size/M

#3149 adding tstromberg as maintainer
  OWNERS
Labels: approved, cncf-cla: yes, size/XS

#2763 Add link to minikube repository for Void Linux
  README.md
Labels: cncf-cla: yes, lifecycle/stale, size/XS

#3159 Fix typo: suppports -> supports
  docs/gpu.md
Labels: cncf-cla: yes, size/XS

#3118 Simplifies Linux installation instructions by using install(1)
  README.md
Labels: cncf-cla: yes, size/XS

#3148 Fix issue 2513
  pkg/drivers/kvm/domain.go
  pkg/drivers/kvm/kvm.go
  pkg/drivers/kvm/network.go
Labels: cncf-cla: yes, lgtm, size/L

#3175 Cut release 0.29.0
  CHANGELOG.md
  Makefile
Labels: approved, cncf-cla: yes, size/M

#3171 make integration fixes: Install gsutil, improve GOPATH warning, fix path/exec issues.
  Makefile
  hack/jenkins/build_iso.sh
  hack/jenkins/common.sh
  hack/jenkins/linux_integration_tests_kvm.sh
  hack/jenkins/linux_integration_tests_none.sh
  hack/jenkins/linux_integration_tests_virtualbox.sh
  hack/jenkins/print-debug-info.sh
  hack/jenkins/release_update_releases_json.sh
  test/integration/cluster_status_test.go
Labels: approved, cncf-cla: yes, size/M

#3161 Add psmisc package, for pstree command
  deploy/iso/minikube-iso/configs/minikube_defconfig
Labels: cncf-cla: yes, size/XS

#3182 Specifically call out the removal of get-k8s-versions.
  CHANGELOG.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3186 waitForDNS should wait for k8s-app=kube-dns pods to be Running
  test/integration/cluster_dns_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M
