Repository kubernetes/minikube, pull requests merged in 2018-03, with the labels that each got.

#2589 Type fix "iso"->"ISO"
  docs/contributors/releasing_minikube.md
Labels: cncf-cla: yes, size/XS

#2586 Update docker-machine to fix hyper-v cmdlet collision.
  Godeps/Godeps.json
  vendor/github.com/docker/machine/drivers/hyperv/hyperv.go
  vendor/github.com/docker/machine/drivers/hyperv/powershell.go
  vendor/github.com/docker/machine/drivers/virtualbox/virtualbox_openbsd.go
  vendor/github.com/docker/machine/drivers/vmwarefusion/fusion_darwin.go
  vendor/github.com/docker/machine/libmachine/host/host.go
  vendor/github.com/docker/machine/libmachine/provision/debian.go
  vendor/github.com/docker/machine/libmachine/provision/ubuntu_systemd.go
  vendor/github.com/docker/machine/libmachine/provision/ubuntu_upstart.go
  vendor/github.com/docker/machine/libmachine/provision/utils.go
  vendor/github.com/docker/machine/libmachine/ssh/keys.go
  vendor/k8s.io/kubernetes/pkg/generated/openapi/zz_generated.openapi.go
Labels: approved, cncf-cla: yes, size/L

#2584 Bump version and update manifest CoreDNS
  deploy/addons/coredns/coreDNS-configmap.yaml
  deploy/addons/coredns/coreDNS-controller.yaml
  deploy/addons/coredns/coreDNS-svc.yaml
Labels: cncf-cla: yes, size/S

#2600 Issue #2599 Add sshfs support for minikube iso
  deploy/iso/minikube-iso/configs/minikube_defconfig
  hack/jenkins/minishift_linux_integration_tests_kvm.sh
Labels: cncf-cla: yes, size/XS

#2591 deactivated hsts by default
  deploy/addons/ingress/ingress-configmap.yaml
  docs/addons.md
Labels: cncf-cla: yes, size/XS

#2590 Add the ValidatingAdmissionWebhook controller.
  pkg/util/constants.go
Labels: approved, cncf-cla: yes, size/XS

#2597 Upgrade Docker, from 17.09 to 17.12
  deploy/iso/minikube-iso/package/docker-bin/docker-bin.hash
  deploy/iso/minikube-iso/package/docker-bin/docker-bin.mk
Labels: cncf-cla: yes, size/XS

#2603 Typo fix "file sever"->"file server"
  third_party/go9p/clnt_mount.go
Labels: cncf-cla: yes, size/XS

#2625 Cut a 0.25.1 point release.
  CHANGELOG.md
  Makefile
Labels: approved, cncf-cla: yes, size/XS

#2649 Update persistent_volumes.md
  docs/persistent_volumes.md
Labels: cncf-cla: yes, size/XS

#2645 Update reusing_the_docker_daemon.md
  docs/reusing_the_docker_daemon.md
Labels: cncf-cla: yes, size/XS

#2621 Add link to minikube copr repository for Fedora/CentOS/Red Hat
  README.md
Labels: cncf-cla: yes, size/XS

#2644 Update nginx-ingress version to 0.12.0
  deploy/addons/ingress/ingress-rc.yaml
Labels: cncf-cla: yes, size/XS

#2663 Update cri-o, to work with Kubernetes 1.10
  deploy/iso/minikube-iso/package/crio-bin/crio-bin.hash
  deploy/iso/minikube-iso/package/crio-bin/crio-bin.mk
Labels: cncf-cla: yes, size/XS
