Repository kubernetes/minikube, pull requests merged in 2018-12, with the labels that each got.

#3290 use $(CURDIR) instead of $(PWD) in Makefile
  Makefile
Labels: approved, cncf-cla: yes, size/XS

#3393 Fix incomplete ssh line, add useful debugging commands
  hack/jenkins/print-debug-info.sh
Labels: approved, cncf-cla: yes, size/S

#3396 Add NET_PRIO cgroup to iso
  deploy/iso/minikube-iso/board/coreos/minikube/linux_defconfig
Labels: cncf-cla: yes, size/XS

#3332 Remove both the CoreDNS and KubeDNS addons. Let Kubeadm install the c…
  cmd/minikube/cmd/config/config.go
  deploy/addons/coredns/coreDNS-clusterrole.yaml
  deploy/addons/coredns/coreDNS-configmap.yaml
  deploy/addons/coredns/coreDNS-controller.yaml
  deploy/addons/coredns/coreDNS-crbinding.yaml
  deploy/addons/coredns/coreDNS-sa.yaml
  deploy/addons/coredns/coreDNS-svc.yaml
  deploy/addons/kube-dns/kube-dns-cm.yaml
  deploy/addons/kube-dns/kube-dns-controller.yaml
  deploy/addons/kube-dns/kube-dns-svc.yaml
  docs/addons.md
  pkg/minikube/assets/addons.go
  pkg/minikube/bootstrapper/kubeadm/kubeadm.go
  pkg/minikube/bootstrapper/kubeadm/templates.go
Labels: approved, cncf-cla: yes, size/L

#3398 Avoid confusing log messages by moving TEST_HOME creation to after cleanup
  hack/jenkins/common.sh
Labels: approved, cncf-cla: yes, size/XS

#3410 Remove check for obsolete kube-dns label & validate kubernetes.default rather than localhost
  test/integration/cluster_dns_test.go
Labels: approved, cncf-cla: yes, size/M

#3394 Add integration test to make sure minikube starts and stops with cont…
  test/integration/functional_test.go
  test/integration/start_stop_delete_test.go
  test/integration/util/util.go
Labels: cncf-cla: yes, size/M

#3413 none cleanup: force kubeadm, clear /etc/kubernetes, and use sudo for kubectl kill
  hack/jenkins/common.sh
  hack/jenkins/linux_integration_tests_none.sh
Labels: approved, cncf-cla: yes, size/XS

#3402 Make k8s v1.12.3 the default
  Makefile
  pkg/minikube/constants/constants.go
Labels: approved, cncf-cla: yes, size/XS

#3418 kill hung test commands and improve hung process output
  hack/jenkins/common.sh
Labels: approved, cncf-cla: yes, size/S

#3415 Report and clean up stale tunnel routes
  hack/jenkins/common.sh
  hack/jenkins/print-debug-info.sh
Labels: approved, cncf-cla: yes, size/S

#3423 Revert "Make k8s v1.12.3 the default"
  Makefile
  pkg/minikube/constants/constants.go
Labels: approved, cncf-cla: yes, size/XS

#3419 Add schedutils to the guest VM for the ionice command (used by k8s 1.12)
  deploy/iso/minikube-iso/configs/minikube_defconfig
Labels: approved, cncf-cla: yes, size/XS

#3426 Only restart docker service if container runtime is docker
  cmd/minikube/cmd/start.go
  pkg/minikube/bootstrapper/kubeadm/kubeadm.go
  pkg/provision/buildroot.go
Labels: cncf-cla: yes, lgtm, size/M

#3401 Add apiserver check to "status", and block "start" until it's healthy.
  cmd/minikube/cmd/start.go
  cmd/minikube/cmd/status.go
  pkg/minikube/bootstrapper/bootstrapper.go
  pkg/minikube/bootstrapper/kubeadm/kubeadm.go
  pkg/minikube/constants/constants.go
  test/integration/util/util.go
Labels: approved, cncf-cla: yes, size/L

#3432 cut v0.31.0
  CHANGELOG.md
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/M

#3427 Fix .Info() error message
  pkg/minikube/tunnel/tunnel_manager.go
Labels: cncf-cla: yes, size/XS

#3445 Change restart policy on gvisor pod
  deploy/addons/gvisor/gvisor-pod.yaml
  test/integration/addons_test.go
  test/integration/functional_test.go
  test/integration/util/util.go
Labels: cncf-cla: yes, size/M

#3450 Save old cluster config in memory before overwriting
  cmd/minikube/cmd/start.go
  pkg/minikube/config/config.go
  pkg/minikube/tunnel/cluster_inspector.go
  pkg/minikube/tunnel/cluster_inspector_test.go
  pkg/minikube/tunnel/test_doubles.go
  pkg/minikube/tunnel/tunnel_test.go
Labels: cncf-cla: yes, size/M

#3465 Extend Jenkins integration test timeout from 30m to 50m.
  hack/jenkins/common.sh
Labels: approved, cncf-cla: yes, size/XS

#3456 First try "kubeadm reset" without -f, primarily for older versions.
  hack/jenkins/linux_integration_tests_none.sh
Labels: approved, cncf-cla: yes, size/XS

#3428 adding priyawadhwa and tstromberg as maintainers
  MAINTAINERS
  OWNERS
Labels: approved, cncf-cla: yes, size/XS

#3436 clarified some steps in release instructions
  docs/contributors/releasing_minikube.md
Labels: approved, cncf-cla: yes, size/S

#3463 Allow ServiceCIDR to be configured via 'service-cluster-ip-range' flag.
  cmd/minikube/cmd/start.go
  pkg/minikube/bootstrapper/kubeadm/kubeadm.go
Labels: cncf-cla: yes, size/XS

#3459 Hide KVM signature when using GPU passthrough to support more GPU models
  pkg/drivers/kvm/domain.go
Labels: cncf-cla: yes, size/XS

#3453 Enable host DNS resolution in virtualbox driver by default
  pkg/minikube/drivers/virtualbox/driver.go
Labels: cncf-cla: yes, size/XS

#3466 Bump dashboard version to v1.10.1
  deploy/addons/dashboard/dashboard-dp.yaml
  pkg/minikube/constants/constants.go
Labels: cncf-cla: yes, size/S

#3452 Fix CRI socket in Kubernetes >= 1.12.0 kubeadmin config
  pkg/minikube/bootstrapper/kubeadm/templates.go
Labels: cncf-cla: yes, size/XS

#3367 Document None driver docker compatibility
  README.md
Labels: cncf-cla: yes, size/XS

#3477 Decrease log noise by logging retry loops after the initial attempt
  pkg/util/utils.go
Labels: approved, cncf-cla: yes, size/XS

#3475 tee party: Stream cmd output to tests when -v is enabled, and stream SSH output to logs
  pkg/minikube/bootstrapper/ssh_runner.go
  pkg/util/utils.go
  pkg/util/utils_test.go
  test/integration/docker_test.go
  test/integration/util/util.go
Labels: approved, cncf-cla: yes, size/L

#3476 VirtualBox time cleanup: sync on boot, don't run timesyncd
  deploy/iso/minikube-iso/configs/minikube_defconfig
  deploy/iso/minikube-iso/package/vbox-guest/vboxservice.service
Labels: approved, cncf-cla: yes, size/S

#3479 Make "stop" retry on failure.
  cmd/minikube/cmd/stop.go
  pkg/minikube/cluster/cluster.go
Labels: approved, cncf-cla: yes, size/S

#3483 Update kubeadm restart commands to support v1.13.x
  pkg/minikube/bootstrapper/kubeadm/kubeadm.go
  pkg/minikube/bootstrapper/kubeadm/templates.go
Labels: cncf-cla: yes, size/M

#3482 Make Kubernetes v1.12.4 the default
  Makefile
  pkg/minikube/constants/constants.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3374 Tell user given driver has been igored if exising VM has a different …
  pkg/minikube/cluster/cluster.go
Labels: cncf-cla: yes, size/XS
