Repository kubernetes/minikube, pull requests merged in 2019-07, with the labels that each got.

#4650 making issues log output collapsable
  .github/ISSUE_TEMPLATE/__en-US.md
Labels: cncf-cla: yes

#4652 improve github issues tempalte
  .github/ISSUE_TEMPLATE/__en-US.md
Labels: cncf-cla: yes, size/XS

#4654 adding an improved foldable issue page
  .github/ISSUE_TEMPLATE/__en-US.md
  .github/ISSUE_TEMPLATE/ar.md
  .github/ISSUE_TEMPLATE/es.md
  .github/ISSUE_TEMPLATE/fa.md
  .github/ISSUE_TEMPLATE/id.md
  .github/ISSUE_TEMPLATE/ku.md
  .github/ISSUE_TEMPLATE/pt-BR.md
  .github/ISSUE_TEMPLATE/zh-CN.md
Labels: cncf-cla: yes

#4593 Add hyperkit version
  Makefile
  cmd/drivers/hyperkit/main.go
  docs/drivers.md
  pkg/drivers/hyperkit/version.go
Labels: cncf-cla: yes, needs-ok-to-test, size/M

#4644 Add kvm prefix to flags only used by kvm
  cmd/minikube/cmd/start.go
  pkg/minikube/config/types.go
  pkg/minikube/drivers/kvm2/driver.go
Labels: cncf-cla: yes, needs-ok-to-test, size/S

#4659 exit and warn if none driver is run by not-root user
  cmd/minikube/cmd/start.go
Labels: approved, cncf-cla: yes, size/S

#4663 Pass the git commit to the kvm docker build
  Makefile
Labels: approved, cncf-cla: yes, size/XS

#4645 Fix profile flag documentation indentation
  cmd/minikube/cmd/root.go
Labels: cncf-cla: yes, needs-ok-to-test, size/XS

#4683 Avoid duplicate headers in markdown (mdlint)
  docs/drivers.md
Labels: approved, cncf-cla: yes, size/XS

#4682 Fix systemd dependencies when using containerd
  pkg/minikube/bootstrapper/kubeadm/kubeadm_test.go
  pkg/minikube/bootstrapper/kubeadm/templates.go
Labels: approved, cncf-cla: yes, size/S

#4678 Delete kubeconfig context when a machine has been deleted
  cmd/minikube/cmd/delete.go
  pkg/util/kubeconfig.go
  pkg/util/kubeconfig_test.go
Labels: cncf-cla: yes, needs-ok-to-test, size/M

#4685 Make the generated files pass gofmt and golint
  Makefile
Labels: approved, cncf-cla: yes, size/XS

#4676 Add warn if kvm driver version is old
  cmd/minikube/cmd/start.go
  cmd/minikube/cmd/start_test.go
  docs/drivers.md
  pkg/minikube/constants/constants.go
Labels: cncf-cla: yes, size/L

#4687 moving command runner to its own package
  cmd/minikube/cmd/config/util.go
  cmd/minikube/cmd/start.go
  pkg/drivers/hyperkit/driver_test.go
  pkg/drivers/none/none.go
  pkg/minikube/bootstrapper/certs.go
  pkg/minikube/bootstrapper/certs_test.go
  pkg/minikube/bootstrapper/kubeadm/kubeadm.go
  pkg/minikube/command/command_runner.go
  pkg/minikube/command/exec_runner.go
  pkg/minikube/command/fake_runner.go
  pkg/minikube/command/ssh_runner.go
  pkg/minikube/cruntime/cruntime.go
  pkg/minikube/logs/logs.go
  pkg/minikube/machine/cache_binaries.go
  pkg/minikube/machine/cache_images.go
  pkg/minikube/machine/client.go
  pkg/provision/buildroot.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#4695 Reduce complexity of the delete command
  cmd/minikube/cmd/delete.go
Labels: approved, cncf-cla: yes, size/S

#4715 reducing issue template complex tags
  .github/ISSUE_TEMPLATE/__en-US.md
  .github/ISSUE_TEMPLATE/ar.md
  .github/ISSUE_TEMPLATE/es.md
  .github/ISSUE_TEMPLATE/fa.md
  .github/ISSUE_TEMPLATE/id.md
  .github/ISSUE_TEMPLATE/ku.md
  .github/ISSUE_TEMPLATE/pt-BR.md
  .github/ISSUE_TEMPLATE/zh-CN.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#4675 Fix `minikube service` to show error message if service has no node ports
  cmd/minikube/cmd/service_list.go
  pkg/minikube/service/service.go
Labels: cncf-cla: yes, size/M

#4692 Add kubectl examples
  cmd/minikube/cmd/kubectl.go
Labels: cncf-cla: yes, size/XS

#4647 Add documentation for minikube CLI commands
  docs/cli_commands.md
Labels: cncf-cla: yes, needs-ok-to-test, size/L

#4689 Fixes the issue which caused all containers to be deleted on minikube delete
  pkg/minikube/cruntime/docker.go
Labels: cncf-cla: yes, needs-ok-to-test, size/XS

#4677 Add templating for proper localization
  cmd/minikube/cmd/start.go
  pkg/minikube/console/console.go
  pkg/minikube/console/console_test.go
  pkg/minikube/console/style.go
  pkg/minikube/extract/extract.go
  pkg/minikube/translate/translate_test.go
  translations/fr-FR.json
  translations/zh-CN.json
Labels: approved, cncf-cla: yes, size/L

#4732 Update security contacts
  MAINTAINERS
  OWNERS
  SECURITY_CONTACTS
Labels: approved, cncf-cla: yes, size/S

#4545 Don't disable other container engines when --vm_driver=none
  cmd/minikube/cmd/start.go
  pkg/minikube/cruntime/containerd.go
  pkg/minikube/cruntime/crio.go
  pkg/minikube/cruntime/cruntime.go
  pkg/minikube/cruntime/cruntime_test.go
  pkg/minikube/cruntime/docker.go
Labels: cncf-cla: yes, needs-ok-to-test, size/M

#4657 Upgrade Docker, from 18.09.6 to 18.09.7
  deploy/iso/minikube-iso/package/containerd-bin/containerd-bin.hash
  deploy/iso/minikube-iso/package/containerd-bin/containerd-bin.mk
  deploy/iso/minikube-iso/package/docker-bin/docker-bin.hash
  deploy/iso/minikube-iso/package/docker-bin/docker-bin.mk
  deploy/iso/minikube-iso/package/runc-master/runc-master.hash
  deploy/iso/minikube-iso/package/runc-master/runc-master.mk
Labels: approved, cncf-cla: yes, lgtm, size/S

#4688 Add space after // comments
  cmd/minikube/cmd/config/open.go
  cmd/minikube/cmd/config/util.go
  cmd/minikube/cmd/start.go
  cmd/minikube/cmd/stop.go
  cmd/minikube/cmd/tunnel.go
  pkg/drivers/kvm/network.go
  pkg/minikube/bootstrapper/kubeadm/kubeadm.go
  pkg/minikube/cluster/cluster.go
  pkg/minikube/constants/constants.go
  pkg/minikube/drivers/hyperv/driver.go
  pkg/minikube/tunnel/loadbalancer_patcher.go
  pkg/minikube/tunnel/process.go
  pkg/minikube/tunnel/registry.go
  pkg/minikube/tunnel/reporter.go
  pkg/minikube/tunnel/reporter_test.go
  pkg/minikube/tunnel/route.go
  pkg/minikube/tunnel/route_darwin.go
  pkg/minikube/tunnel/route_linux.go
  pkg/minikube/tunnel/route_windows.go
  pkg/minikube/tunnel/test_doubles.go
  pkg/minikube/tunnel/tunnel.go
  pkg/minikube/tunnel/tunnel_manager.go
  pkg/minikube/tunnel/tunnel_manager_test.go
  pkg/util/downloader_test.go
  pkg/util/kubeconfig.go
  pkg/util/kubernetes.go
  test/integration/cluster_logs_test.go
  third_party/go9p/ufs/ufs.go
  third_party/go9p/ufs_darwin.go
  third_party/go9p/ufs_linux.go
Labels: cncf-cla: yes, needs-ok-to-test, size/L

#4686 Refactor status command
  cmd/minikube/cmd/status.go
  pkg/minikube/constants/constants.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#4740 Fix golint complaint about new OutT/ErrT functions
  pkg/minikube/console/console.go
Labels: approved, cncf-cla: yes, size/XS

#4743 Reduce kubectl restart time from 10 seconds to 600ms
  pkg/minikube/bootstrapper/kubeadm/templates.go
Labels: approved, cncf-cla: yes, size/XS

#4746 Revert "Refactor status command"
  cmd/minikube/cmd/status.go
  pkg/minikube/constants/constants.go
Labels: approved, cncf-cla: yes, size/M

#4739 Use tempfile for extract test
  pkg/minikube/extract/extract_test.go
Labels: approved, cncf-cla: yes, size/M

#4748 Add documentation of the parallels vm-driver
  README.md
  docs/drivers.md
Labels: cncf-cla: yes, needs-ok-to-test, size/S

#4610 Upgrade Podman to 1.4
  deploy/iso/minikube-iso/package/conmon-master/conmon-master.hash
  deploy/iso/minikube-iso/package/conmon-master/conmon-master.mk
  deploy/iso/minikube-iso/package/podman/podman.hash
  deploy/iso/minikube-iso/package/podman/podman.mk
Labels: approved, cncf-cla: yes, size/S

#4741 Use print() function in both Python 2 and Python 3
  hack/prow/run_tests.py
Labels: cncf-cla: yes, ok-to-test, size/S

#4761 Update crictl to v1.15.0
  deploy/iso/minikube-iso/package/crictl-bin/crictl-bin.hash
  deploy/iso/minikube-iso/package/crictl-bin/crictl-bin.mk
Labels: approved, cncf-cla: yes, size/XS

#4762 Undefined name 'test' in run_tests.py
  hack/prow/run_tests.py
Labels: cncf-cla: yes, needs-ok-to-test, size/XS

#4752 Create package index files, for apt and yum
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/S

#4703 Upgrade crio to 1.15.0
  deploy/iso/minikube-iso/package/crio-bin/conmon-config.h
  deploy/iso/minikube-iso/package/crio-bin/crio-bin.hash
  deploy/iso/minikube-iso/package/crio-bin/crio-bin.mk
  deploy/iso/minikube-iso/package/crio-bin/crio-bin.patch
  deploy/iso/minikube-iso/package/crio-bin/crio.conf
  deploy/iso/minikube-iso/package/crio-bin/crio.conf.default
Labels: approved, cncf-cla: yes, size/L

#4556 Add linux packaging for the kvm2 driver binary
  Makefile
  hack/jenkins/release_build_and_upload.sh
  installers/linux/deb/kvm2_deb_template/DEBIAN/control
  installers/linux/deb/minikube_deb_template/DEBIAN/control
  installers/linux/rpm/kvm2_rpm_template/docker-machine-driver-kvm2.spec
Labels: approved, cncf-cla: yes, size/M

#4724 Extract Advice strings for localization
  cmd/extract/extract.go
  pkg/minikube/extract/extract.go
  translations/fr-FR.json
  translations/zh-CN.json
Labels: approved, cncf-cla: yes, size/L

#4737 refactoring and simplifying start command
  cmd/minikube/cmd/cache.go
  cmd/minikube/cmd/delete.go
  cmd/minikube/cmd/logs.go
  cmd/minikube/cmd/root.go
  cmd/minikube/cmd/start.go
  cmd/minikube/cmd/status.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#4779 Makefile improvements for the kvm2 driver
  Makefile
Labels: approved, cncf-cla: yes, size/S

#4729 Show more relevant information, when using none driver
  go.mod
  go.sum
  pkg/minikube/cluster/cluster.go
Labels: approved, cncf-cla: yes, size/M

#4763 Lint Python code for syntax errors and undefined names
  .travis.yml
Labels: cncf-cla: yes, needs-ok-to-test, size/XS

#4639 Added integration tests for registry
  deploy/addons/registry/registry-proxy.yaml.tmpl
  test/integration/addons_test.go
  test/integration/functional_test.go
  test/integration/util/util.go
Labels: cncf-cla: yes, needs-ok-to-test, size/M

#4791 Fix darwin constants
  pkg/minikube/constants/constants_darwin.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4792 Add missing ErrMapFile docs, to make golint happy
  pkg/minikube/extract/extract.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4790 Update github issues URL now that we have issue templates
  pkg/minikube/exit/exit.go
Labels: approved, cncf-cla: yes, size/XS

#4793 git ignore translations.go-e
  .gitignore
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4781 Remove deprecated drivers: kvm-old and xhyve
  cmd/minikube/cmd/config/config_test.go
  cmd/minikube/cmd/config/util_test.go
  cmd/minikube/cmd/start.go
  docs/cli_commands.md
  pkg/minikube/cluster/cluster.go
  pkg/minikube/cluster/default_drivers.go
  pkg/minikube/config/config_test.go
  pkg/minikube/config/types.go
  pkg/minikube/constants/constants.go
  pkg/minikube/constants/constants_darwin.go
  pkg/minikube/constants/constants_gendocs.go
  pkg/minikube/constants/constants_linux.go
  pkg/minikube/drivers/kvm/doc.go
  pkg/minikube/drivers/kvm/driver.go
  pkg/minikube/drivers/xhyve/doc.go
  pkg/minikube/drivers/xhyve/driver.go
Labels: approved, cncf-cla: yes, size/L

#4794 Add advice if crash on hyperkit not installed
  pkg/minikube/problem/err_map.go
Labels: cncf-cla: yes, lgtm, size/XS

#4777 Add test to make sure translations files are up to date.
  Makefile
  pkg/minikube/extract/extract_test.go
  translations/fr-FR.json
  translations/zh-CN.json
Labels: approved, cncf-cla: yes, size/M

#4796 Add T versions of the console convenience functions
  cmd/minikube/cmd/delete.go
  go.mod
  go.sum
  pkg/minikube/console/console.go
  pkg/minikube/console/style.go
  pkg/minikube/exit/exit.go
  translations/fr-FR.json
  translations/zh-CN.json
Labels: approved, cncf-cla: yes, size/M

#4799 Fix OutT to accept nil arg
  pkg/minikube/console/style.go
Labels: approved, cncf-cla: yes, size/XS

#4800 Templatizing more calls to console
  cmd/minikube/cmd/config/configure.go
  cmd/minikube/cmd/config/open.go
  cmd/minikube/cmd/status.go
  cmd/minikube/cmd/update-context.go
  pkg/minikube/console/style.go
  pkg/minikube/console/style_enum.go
  pkg/minikube/exit/exit.go
  pkg/minikube/logs/logs.go
  pkg/util/utils.go
  translations/fr-FR.json
  translations/zh-CN.json
Labels: approved, cncf-cla: yes, size/L

#4744 Allow users to skip pod health checks with --wait=false
  cmd/minikube/cmd/start.go
  test/integration/addons_test.go
  test/integration/cluster_env_test.go
  test/integration/cluster_logs_test.go
  test/integration/cluster_ssh_test.go
  test/integration/docker_test.go
  test/integration/flags.go
  test/integration/iso_test.go
  test/integration/mount_test.go
  test/integration/persistence_test.go
  test/integration/proxy_test.go
  test/integration/tunnel_test.go
  test/integration/util/util.go
Labels: approved, cncf-cla: yes, size/L

#4805 Fix regression caused by registry-proxy
  deploy/addons/registry/registry-proxy.yaml.tmpl
  deploy/addons/registry/registry-rc.yaml.tmpl
  deploy/addons/registry/registry-svc.yaml.tmpl
Labels: cncf-cla: yes, needs-ok-to-test, size/XS

#4808 Remove test checking for up to date translation files
  pkg/minikube/extract/extract_test.go
Labels: approved, cncf-cla: yes, size/M

#4809 Add LowPrefix to Empty style, move to beginning of list
  pkg/minikube/console/style.go
Labels: approved, cncf-cla: yes, size/XS

#4807 Adding translating formatting
  cmd/minikube/cmd/config/disable.go
  cmd/minikube/cmd/config/profile.go
  cmd/minikube/cmd/delete.go
  cmd/minikube/cmd/ip.go
  cmd/minikube/cmd/start.go
  cmd/minikube/cmd/stop.go
  pkg/minikube/cluster/cluster.go
  pkg/minikube/service/service.go
  translations/fr-FR.json
  translations/zh-CN.json
Labels: approved, cncf-cla: yes, size/L

#4821 Refactor TestFunctional/Registry to handle new labels
  test/integration/addons_test.go
  test/integration/util/util.go
Labels: approved, cncf-cla: yes, size/M

#4818 Upgrade Docker, from 18.09.7 to 18.09.8
  deploy/iso/minikube-iso/package/docker-bin/docker-bin.hash
  deploy/iso/minikube-iso/package/docker-bin/docker-bin.mk
Labels: approved, cncf-cla: yes, size/XS

#4811 Add a new command (profile list)
  cmd/minikube/cmd/config/profile_list.go
  pkg/minikube/config/config.go
  pkg/minikube/config/profile.go
  pkg/minikube/config/profile_test.go
  pkg/minikube/config/testdata/.minikube/profiles/p1/config.json
  pkg/minikube/config/testdata/.minikube/profiles/p2/config.json
  pkg/minikube/config/testdata/.minikube/profiles/p3_empty/config.json
  pkg/minikube/config/testdata/.minikube/profiles/p4_invalid_file/config.json
  pkg/minikube/config/testdata/.minikube/profiles/p5_partial_config/config.json
  pkg/minikube/config/types.go
  pkg/minikube/constants/constants.go
  pkg/minikube/tunnel/test_doubles.go
  test/integration/functional_test.go
  test/integration/profile_test.go
Labels: approved, cncf-cla: yes, size/L

#4827 Improve usage message when there is no profile found
  cmd/minikube/cmd/config/profile_list.go
Labels: cncf-cla: yes, lgtm

#4823 Make TestNewSSHClient and ssh_mock race-proof
  pkg/minikube/cluster/cluster_test.go
  pkg/minikube/sshutil/sshutil_test.go
  pkg/minikube/tests/ssh_mock.go
Labels: approved, cncf-cla: yes, size/L

#4828 Fix profile list error handling
  cmd/minikube/cmd/config/profile_list.go
Labels: cncf-cla: yes

#4813 Make cluster_test and utils_test run in isolation
  cmd/minikube/cmd/env_test.go
  pkg/minikube/cluster/cluster.go
  pkg/minikube/cluster/cluster_test.go
  pkg/minikube/config/config.go
  pkg/minikube/constants/constants.go
  pkg/minikube/machine/client.go
  pkg/minikube/sshutil/sshutil_test.go
  pkg/minikube/tests/api_mock.go
  pkg/minikube/tests/driver_mock.go
  pkg/minikube/tests/fake_store.go
  pkg/minikube/tunnel/cluster_inspector_test.go
  pkg/util/utils.go
  pkg/util/utils_test.go
Labels: approved, cncf-cla: yes, size/L

#4825 Console output cleanup
  cmd/minikube/cmd/completion.go
  cmd/minikube/cmd/config/addons_list.go
  cmd/minikube/cmd/config/configure.go
  cmd/minikube/cmd/config/disable.go
  cmd/minikube/cmd/config/enable.go
  cmd/minikube/cmd/config/get.go
  cmd/minikube/cmd/config/open.go
  cmd/minikube/cmd/config/profile.go
  cmd/minikube/cmd/config/profile_list.go
  cmd/minikube/cmd/config/prompt.go
  cmd/minikube/cmd/config/set.go
  cmd/minikube/cmd/config/unset.go
  cmd/minikube/cmd/config/util.go
  cmd/minikube/cmd/config/validations.go
  cmd/minikube/cmd/dashboard.go
  cmd/minikube/cmd/delete.go
  cmd/minikube/cmd/env.go
  cmd/minikube/cmd/ip.go
  cmd/minikube/cmd/kubectl.go
  cmd/minikube/cmd/mount.go
  cmd/minikube/cmd/service.go
  cmd/minikube/cmd/service_list.go
  cmd/minikube/cmd/ssh-key.go
  cmd/minikube/cmd/ssh.go
  cmd/minikube/cmd/start.go
  cmd/minikube/cmd/status.go
  cmd/minikube/cmd/stop.go
  cmd/minikube/cmd/update-check.go
  cmd/minikube/cmd/update-context.go
  cmd/minikube/cmd/version.go
  cmd/minikube/main.go
  pkg/minikube/bootstrapper/kubeadm/kubeadm.go
  pkg/minikube/cluster/cluster.go
  pkg/minikube/cruntime/containerd.go
  pkg/minikube/cruntime/crio.go
  pkg/minikube/cruntime/cruntime.go
  pkg/minikube/cruntime/docker.go
  pkg/minikube/exit/exit.go
  pkg/minikube/logs/logs.go
  pkg/minikube/machine/cache_binaries.go
  pkg/minikube/machine/client.go
  pkg/minikube/notify/notify.go
  pkg/minikube/notify/notify_test.go
  pkg/minikube/out/out.go
  pkg/minikube/out/out_test.go
  pkg/minikube/out/style.go
  pkg/minikube/out/style_enum.go
  pkg/minikube/problem/problem.go
  pkg/minikube/service/service.go
  pkg/util/downloader.go
  pkg/util/utils.go
  translations/fr-FR.json
  translations/zh-CN.json
Labels: approved, cncf-cla: yes, size/XL

#4817 Upgrade libmachine to master
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, size/XS

#4691 Warn if hyperkit version is old
  cmd/minikube/cmd/start.go
  docs/drivers.md
  pkg/minikube/constants/constants.go
Labels: cncf-cla: yes, size/M

#4843 pinning go version in travis
  .travis.yml
Labels: approved, cncf-cla: yes, size/XS

#4525 Show info about the minikube linux distribution
  pkg/minikube/cluster/cluster.go
  pkg/minikube/out/style.go
  pkg/minikube/out/style_enum.go
  pkg/minikube/tests/provision_mock.go
Labels: approved, cncf-cla: yes, size/M

#4850 Limit the number of golangci-lint jobs to one
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4852 Separate make lint targets for developers vs travis
  Makefile
  test.sh
Labels: approved, cncf-cla: yes, size/M

#4719 Bump k8s.io/kubernetes to 1.15.0
  go.mod
  go.sum
  pkg/minikube/bootstrapper/kubeadm/versions_test.go
  pkg/storage/storage_provisioner.go
  pkg/util/kubernetes.go
Labels: cncf-cla: yes, size/XL

#4863 Add libvirt package to the Fedora documentation
  docs/drivers.md
Labels: approved, cncf-cla: yes, size/XS

#4720 Validate driver is supported on current OS
  cmd/minikube/cmd/start.go
Labels: cncf-cla: yes, do-not-merge/work-in-progress, size/XS

#4871 more reliable stop for none driver
  pkg/drivers/none/none.go
Labels: approved, cncf-cla: yes, size/S

#4867 Fix flag.Parse error logging
  cmd/minikube/main.go
  pkg/initflag/initflag.go
  test/integration/addons_test.go
  test/integration/cluster_dns_test.go
  test/integration/cluster_env_test.go
  test/integration/cluster_status_test.go
  test/integration/flags.go
  test/integration/functional_test.go
  test/integration/mount_test.go
  test/integration/persistence_test.go
  test/integration/proxy_test.go
  test/integration/pv_test.go
  test/integration/start_stop_delete_test.go
  test/integration/tunnel_test.go
  test/integration/version_upgrade_test.go
Labels: cncf-cla: yes, size/M

#4876 Revert "Fix flag.Parse error logging"
  cmd/minikube/main.go
  pkg/initflag/initflag.go
  test/integration/addons_test.go
  test/integration/cluster_dns_test.go
  test/integration/cluster_env_test.go
  test/integration/cluster_status_test.go
  test/integration/flags.go
  test/integration/functional_test.go
  test/integration/mount_test.go
  test/integration/persistence_test.go
  test/integration/proxy_test.go
  test/integration/pv_test.go
  test/integration/start_stop_delete_test.go
  test/integration/tunnel_test.go
  test/integration/version_upgrade_test.go
Labels: cncf-cla: yes, size/M

#4882 CI: kill hung proc with sudo and release port
  hack/jenkins/common.sh
Labels: approved, cncf-cla: yes, size/XS

#4884 Update common.sh
  hack/jenkins/common.sh
Labels: approved, cncf-cla: yes, size/XS

#4886 Update common.sh
  hack/jenkins/common.sh
Labels: cncf-cla: yes

#4785 Upgrade nginx ingress to 0.25.0
  deploy/addons/ingress/ingress-dp.yaml.tmpl
  deploy/addons/ingress/ingress-rbac.yaml.tmpl
Labels: cncf-cla: yes, do-not-merge/work-in-progress, needs-ok-to-test, size/XS

#4904 Update link to Steve Sloka's article
  docs/tunnel.md
Labels: cncf-cla: yes, needs-ok-to-test, size/XS

#4893 CI: clean up stale hyperkit and none process and stale inaccessible vbox
  hack/jenkins/common.sh
Labels: approved, cncf-cla: yes, size/M

#4758 hyperv: Run "sudo poweroff" before stopping VM
  cmd/minikube/cmd/stop.go
  pkg/minikube/cluster/cluster.go
Labels: cncf-cla: yes, needs-ok-to-test, size/S

#4885 Fix minikube start args for integration tests
  test/integration/flags.go
Labels: approved, cncf-cla: yes, size/XS

#4887 Fix glog parse error
  cmd/minikube/main.go
  go.mod
  go.sum
  pkg/initflag/initflag.go
Labels: cncf-cla: yes, size/M

#4907 Upgrade the build image from 1.12.5 to 1.12.7
  Makefile
Labels: approved, cncf-cla: yes, size/S

#4879 UI: improve minikube help output by grouping into categories
  cmd/minikube/cmd/cache.go
  cmd/minikube/cmd/completion.go
  cmd/minikube/cmd/dashboard.go
  cmd/minikube/cmd/delete.go
  cmd/minikube/cmd/env.go
  cmd/minikube/cmd/ip.go
  cmd/minikube/cmd/kubectl.go
  cmd/minikube/cmd/logs.go
  cmd/minikube/cmd/mount.go
  cmd/minikube/cmd/root.go
  cmd/minikube/cmd/service.go
  cmd/minikube/cmd/ssh-key.go
  cmd/minikube/cmd/ssh.go
  cmd/minikube/cmd/start.go
  cmd/minikube/cmd/status.go
  cmd/minikube/cmd/stop.go
  cmd/minikube/cmd/tunnel.go
  cmd/minikube/cmd/update-check.go
  cmd/minikube/cmd/update-context.go
  cmd/minikube/cmd/version.go
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, size/L

#4916 Adding cleanup CI scripts to source control
  hack/jenkins/osx_cleanup_and_reboot.sh
  hack/jenkins/windows_cleanup_and_reboot.bat
Labels: approved, cncf-cla: yes, size/M

#4918 Travis build status link should go to master
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4915 Update latest kubernetes version to v1.15.1
  pkg/minikube/constants/constants.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4922 Unset profile when it is deleted
  cmd/minikube/cmd/config/unset.go
  cmd/minikube/cmd/config/unset_test.go
  cmd/minikube/cmd/delete.go
  pkg/minikube/config/config.go
Labels: cncf-cla: yes, size/M

#4925 Add test to config.ReadConfig
  pkg/minikube/config/config.go
  pkg/minikube/config/config_test.go
  pkg/minikube/config/testdata/.minikube/config/invalid_config.json
  pkg/minikube/config/testdata/.minikube/config/valid_config.json
Labels: cncf-cla: yes, size/M

#4926 Add comment for better clarity of closures_and_goroutines documentation
  pkg/minikube/machine/cache_binaries.go
Labels: cncf-cla: yes, size/XS

#4917 Pin the go version used for kvm-build-image
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4924 Improve code readability: rename config unit tests
  pkg/minikube/config/config_test.go
Labels: cncf-cla: yes, size/XS

#4786 Remove ingress-nginx default backend
  deploy/addons/ingress/ingress-dp.yaml.tmpl
  deploy/addons/ingress/ingress-svc.yaml.tmpl
  pkg/minikube/assets/addons.go
  test/integration/addons_test.go
  test/integration/util/util.go
Labels: cncf-cla: yes, needs-ok-to-test, size/L

#4927 Update KERNEL_VERSION to match buildroot config
  Makefile
Labels: approved, cncf-cla: yes, size/XS

#4921 Use consistent method of getting kvm-build-image
  Makefile
Labels: approved, cncf-cla: yes, size/S

#4930 Revert "Travis build status link should go to master"
  README.md
Labels: approved, cncf-cla: yes, size/XS
