Repository kubernetes/minikube, pull requests merged in 2019-11, with the labels that each got.

#5799 update examples to use "kubectl create"
  site/content/en/docs/Examples/_index.md
Labels: approved, cncf-cla: yes, size/XS

#5679 Reportcard again
  cmd/minikube/cmd/delete.go
  cmd/minikube/cmd/start.go
  cmd/minikube/cmd/status.go
  pkg/minikube/cruntime/cruntime_test.go
  pkg/minikube/driver/driver.go
  pkg/minikube/driver/driver_linux.go
  pkg/minikube/registry/global_test.go
  pkg/minikube/registry/registry.go
Labels: approved, cncf-cla: yes, size/L

#5816 Fix spelling of HTML for golint on bindata
  Makefile
Labels: approved, cncf-cla: yes, size/XS

#5813 fix cron script installation
  hack/jenkins/linux_integration_tests_kvm.sh
  hack/jenkins/linux_integration_tests_virtualbox.sh
Labels: approved, cncf-cla: yes, ok-to-test, size/XS

#5805 Store kubernetes clientset when waiting for apiserver
  pkg/minikube/bootstrapper/kubeadm/kubeadm.go
Labels: cncf-cla: yes, ok-to-test, size/S

#5839 Silence virtualbox registry check
  pkg/minikube/driver/driver_windows.go
Labels: approved, cncf-cla: yes, ok-to-test, size/XS

#5243 Remove heapster addon
  cmd/minikube/cmd/config/addons.go
  cmd/minikube/cmd/config/config.go
  cmd/minikube/cmd/config/util_test.go
  deploy/addons/heapster/grafana-svc.yaml.tmpl
  deploy/addons/heapster/heapster-rc.yaml.tmpl
  deploy/addons/heapster/heapster-svc.yaml.tmpl
  deploy/addons/heapster/influx-grafana-rc.yaml.tmpl
  deploy/addons/heapster/influxdb-svc.yaml.tmpl
  pkg/minikube/assets/addons.go
  site/content/en/docs/Reference/Commands/addons.md
  site/content/en/docs/Reference/Commands/config.md
  site/content/en/docs/Reference/Configuration/minikube.md
  site/content/en/docs/Tasks/addons.md
Labels: cncf-cla: yes, do-not-merge/invalid-commit-message, needs-ok-to-test, size/L

#5542 Add instructions for including supporting documents with MEP proposal
  enhancements/README.md
  enhancements/implemented/20190925-minikube-enhancement-process/README.md
Labels: cncf-cla: yes, ok-to-test, size/XS

#5738 small travis test changes
  .travis.yml
  test.sh
Labels: approved, cncf-cla: yes, ok-to-test, size/S

#5847 Adding priyawadhwa as minikube approver
  OWNERS
Labels: approved, cncf-cla: yes, size/XS

#5749 Use faster build for the default minikube target
  Makefile
Labels: approved, cncf-cla: yes, ok-to-test, size/S

#5837 Update NewestKubernetesVersion to v1.17.0-beta.1
  go.mod
  go.sum
  pkg/minikube/bootstrapper/kubeadm/kubeadm_test.go
  pkg/minikube/bootstrapper/kubeadm/testdata/v1.17/containerd-api-port.yaml
  pkg/minikube/bootstrapper/kubeadm/testdata/v1.17/containerd-pod-network-cidr.yaml
  pkg/minikube/bootstrapper/kubeadm/testdata/v1.17/containerd.yaml
  pkg/minikube/bootstrapper/kubeadm/testdata/v1.17/crio-options-gates.yaml
  pkg/minikube/bootstrapper/kubeadm/testdata/v1.17/crio.yaml
  pkg/minikube/bootstrapper/kubeadm/testdata/v1.17/default.yaml
  pkg/minikube/bootstrapper/kubeadm/testdata/v1.17/dns.yaml
  pkg/minikube/bootstrapper/kubeadm/testdata/v1.17/image-repository.yaml
  pkg/minikube/bootstrapper/kubeadm/testdata/v1.17/options.yaml
  pkg/minikube/constants/constants.go
Labels: approved, cncf-cla: yes, ok-to-test, size/L

#5853 bump go.mod version
  go.mod
Labels: approved, cncf-cla: yes, ok-to-test, size/XS

#5851 Skip if DashboardCmd fails on Windows
  test/integration/functional_test.go
Labels: approved, cncf-cla: yes, ok-to-test, size/XS

#5613 Add help target to list all different targets
  Makefile
  go.mod
Labels: cncf-cla: yes, ok-to-test, size/L

#5866 go mod tidy
  go.mod
Labels: approved, cncf-cla: yes, size/XS

#5842 mention fix for AppArmor related permission errors
  site/content/en/docs/Tasks/docker_daemon.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#5877 Update libmachine to point to latest
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, ok-to-test, size/XS

#5452 Update roadmap & principles for 2020 (comments & discussion welcome!)
  site/content/en/docs/Concepts/principles.en.md
  site/content/en/docs/Contributing/roadmap.en.md
Labels: approved, cncf-cla: yes, size/L, triage/discuss

#5854 Improve message when selected driver is incompatible with existing cluster
  cmd/minikube/cmd/start.go
Labels: approved, cncf-cla: yes, ok-to-test, size/S

#5852 Add memory and wait longer for TestFunctional tests, include node logs
  test/integration/functional_test.go
  test/integration/helpers.go
Labels: approved, cncf-cla: yes, ok-to-test, size/M

#5840 Health check previously configured driver & exit if not installed
  cmd/minikube/cmd/start.go
  go.mod
  pkg/minikube/driver/driver.go
  pkg/minikube/driver/driver_test.go
  pkg/minikube/registry/global.go
  pkg/minikube/registry/global_test.go
  pkg/minikube/registry/registry.go
Labels: approved, cncf-cla: yes, ok-to-test, size/L

#5868 Getting rid of GetMachineName()
  cmd/minikube/cmd/config/util.go
  cmd/minikube/cmd/dashboard.go
  cmd/minikube/cmd/delete.go
  cmd/minikube/cmd/env.go
  cmd/minikube/cmd/env_test.go
  cmd/minikube/cmd/ip.go
  cmd/minikube/cmd/logs.go
  cmd/minikube/cmd/mount.go
  cmd/minikube/cmd/ssh-key.go
  cmd/minikube/cmd/ssh.go
  cmd/minikube/cmd/start.go
  cmd/minikube/cmd/status.go
  cmd/minikube/cmd/stop.go
  cmd/minikube/cmd/tunnel.go
  cmd/minikube/cmd/update-context.go
  pkg/minikube/bootstrapper/kubeadm/kubeadm.go
  pkg/minikube/cluster/cluster.go
  pkg/minikube/cluster/cluster_test.go
  pkg/minikube/config/config.go
  pkg/minikube/config/types.go
  pkg/minikube/machine/cache_images.go
  pkg/minikube/registry/drvs/hyperkit/hyperkit.go
  pkg/minikube/registry/drvs/hyperv/hyperv.go
  pkg/minikube/registry/drvs/kvm2/kvm2.go
  pkg/minikube/registry/drvs/none/none.go
  pkg/minikube/registry/drvs/parallels/parallels.go
  pkg/minikube/registry/drvs/virtualbox/virtualbox.go
  pkg/minikube/registry/drvs/vmware/vmware.go
  pkg/minikube/registry/drvs/vmwarefusion/vmwarefusion.go
  pkg/minikube/service/service.go
  pkg/minikube/service/service_test.go
  pkg/minikube/tests/api_mock.go
  site/content/en/docs/Contributing/drivers.en.md
Labels: approved, cncf-cla: yes, ok-to-test, size/L

#5889 Refactor config.Config to prepare for multinode
  cmd/minikube/cmd/config/profile.go
  cmd/minikube/cmd/config/profile_list.go
  cmd/minikube/cmd/config/util.go
  cmd/minikube/cmd/dashboard.go
  cmd/minikube/cmd/delete.go
  cmd/minikube/cmd/env.go
  cmd/minikube/cmd/ip.go
  cmd/minikube/cmd/logs.go
  cmd/minikube/cmd/mount.go
  cmd/minikube/cmd/ssh-key.go
  cmd/minikube/cmd/ssh.go
  cmd/minikube/cmd/start.go
  cmd/minikube/cmd/start_test.go
  cmd/minikube/cmd/tunnel.go
  pkg/minikube/config/config.go
  pkg/minikube/config/profile.go
  pkg/minikube/config/profile_test.go
  pkg/minikube/config/testdata/profile/.minikube/profiles/p1/config.json
  pkg/minikube/config/testdata/profile/.minikube/profiles/p2/config.json
  pkg/minikube/config/testdata/profile/.minikube/profiles/p5_partial_config/config.json
  pkg/minikube/config/types.go
  pkg/minikube/machine/cache_images.go
  pkg/minikube/tunnel/cluster_inspector.go
  pkg/minikube/tunnel/cluster_inspector_test.go
  pkg/minikube/tunnel/test_doubles.go
  pkg/minikube/tunnel/tunnel_test.go
  pkg/provision/buildroot.go
  test/integration/a_serial_test.go
Labels: approved, cncf-cla: yes, ok-to-test, size/L

#5890 CI: Retry GitHub status updates
  hack/jenkins/common.sh
  hack/jenkins/minikube_set_pending.sh
Labels: approved, cncf-cla: yes, ok-to-test, size/M

#5864 Only copy new or modified files into VM on restart
  pkg/minikube/assets/vm_assets.go
  pkg/minikube/command/ssh_runner.go
Labels: approved, cncf-cla: yes, ok-to-test, size/M

#5894 Make --wait=false non-blocking, --wait=true blocks on system pods
  cmd/minikube/cmd/start.go
  pkg/minikube/bootstrapper/bootstrapper.go
  pkg/minikube/bootstrapper/kubeadm/kubeadm.go
  pkg/minikube/bootstrapper/kubeadm/kubeadm_test.go
  pkg/minikube/out/out_test.go
  pkg/minikube/out/style.go
  test/integration/addons_test.go
  test/integration/fn_mount_cmd.go
  test/integration/fn_pvc.go
  test/integration/functional_test.go
  test/integration/gvisor_addon_test.go
Labels: approved, cncf-cla: yes, ok-to-test, size/L

#5901 Remove noisy error message
  pkg/minikube/driver/driver_windows.go
Labels: approved, cncf-cla: yes, size/XS

#5906 Remove unused glog import
  pkg/minikube/driver/driver_windows.go
Labels: cncf-cla: yes

#5909 fix up typo
  pkg/minikube/translate/translate_test.go
  pkg/minikube/vmpath/constants.go
Labels: cncf-cla: yes, ok-to-test, size/XS

#5848 Add retry to SSH connectivity check
  cmd/minikube/cmd/start.go
Labels: cncf-cla: yes, ok-to-test, size/S

#5918 Remove noisy warning message while apiserver is booting up
  pkg/minikube/bootstrapper/kubeadm/kubeadm.go
Labels: approved, cncf-cla: yes, ok-to-test, size/XS

#5916 Make it possible to recover from a previously aborted StartCluster (Ctrl-C)
  cmd/minikube/cmd/start.go
  pkg/minikube/bootstrapper/bootstrapper.go
  pkg/minikube/bootstrapper/kubeadm/kubeadm.go
Labels: approved, cncf-cla: yes, ok-to-test, size/M

#5925 Update DefaultKubernetesVersion to v1.17.0-beta.1 to prepare for betas
  pkg/minikube/bootstrapper/kubeadm/kubeadm_test.go
  pkg/minikube/constants/constants.go
Labels: approved, cncf-cla: yes, ok-to-test, size/XS

#5929 Update changelog for v1.6.0-beta.0 release
  CHANGELOG.md
Labels: approved, cncf-cla: yes, size/M

#5928 Update Makefile version to 1.6.0-beta.0 for beta release
  Makefile
Labels: approved, cncf-cla: yes, ok-to-test, size/XS

#5937 Correct link error:404
  site/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5946 Corret link error:404
  site/content/en/docs/Contributing/releasing.en.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5934 dashboard: Update to latest images (2.0.0-beta6)
  deploy/addons/dashboard/dashboard-dp.yaml
  pkg/minikube/bootstrapper/images/images.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5967 Upgrade buildroot minor version to 2019.02.7
  Makefile
  deploy/iso/minikube-iso/package/hyperv-daemons/hyperv-daemons.mk
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5917 SSHRunner: include stdout/stderr with error message
  pkg/minikube/command/exec_runner.go
  pkg/minikube/command/ssh_runner.go
Labels: approved, cncf-cla: yes, ok-to-test, size/M

#5960 Add option for virtualbox users to set nat-nic-type
  cmd/minikube/cmd/start.go
  go.mod
  pkg/minikube/config/types.go
  pkg/minikube/registry/drvs/virtualbox/virtualbox.go
Labels: cncf-cla: yes, ok-to-test, size/S

#5964 Fix validation of container-runtime config
  cmd/minikube/cmd/config/config.go
  cmd/minikube/cmd/config/validations.go
  cmd/minikube/cmd/config/validations_test.go
Labels: approved, cncf-cla: yes, ok-to-test, size/M

#5932 fixed metrics-server and added integration tests
  deploy/addons/metrics-server/metrics-server-deployment.yaml.tmpl
  test/integration/addons_test.go
Labels: cncf-cla: yes, kind/bug, ok-to-test, size/M

#5969 Create using_psp.md
  site/content/en/docs/Tutorials/using_psp.md
Labels: cncf-cla: yes, needs-ok-to-test, size/L

#5919 Double lookBackwardsCount to 400, to find usage error in new apiserver
  pkg/minikube/logs/logs.go
Labels: approved, cncf-cla: yes, ok-to-test, size/XS

#5971 Upgrade podman to 1.6.3
  deploy/iso/minikube-iso/package/podman/podman.hash
  deploy/iso/minikube-iso/package/podman/podman.mk
Labels: approved, cncf-cla: yes, ok-to-test, size/XS

#5955 Fix profile list json command output
  cmd/minikube/cmd/config/profile_list.go
Labels: cncf-cla: yes, ok-to-test, size/XS

#5914 Update docker to v19.03.5
  deploy/iso/minikube-iso/package/containerd-bin/containerd-bin.hash
  deploy/iso/minikube-iso/package/containerd-bin/containerd-bin.mk
  deploy/iso/minikube-iso/package/docker-bin/docker-bin.hash
  deploy/iso/minikube-iso/package/docker-bin/docker-bin.mk
  deploy/iso/minikube-iso/package/runc-master/runc-master.hash
  deploy/iso/minikube-iso/package/runc-master/runc-master.mk
Labels: cncf-cla: yes, ok-to-test, size/S

#5972 Update crictl to v1.16.1
  deploy/iso/minikube-iso/package/crictl-bin/crictl-bin.hash
  deploy/iso/minikube-iso/package/crictl-bin/crictl-bin.mk
Labels: approved, cncf-cla: yes, ok-to-test, size/XS

#5973 Update default k8s version to 1.17.0-rc.1
  pkg/minikube/bootstrapper/kubeadm/kubeadm_test.go
  pkg/minikube/constants/constants.go
Labels: approved, cncf-cla: yes, ok-to-test, size/S

#5970 cri-o v1.16.0
  deploy/iso/minikube-iso/package/conmon-master/conmon-master.hash
  deploy/iso/minikube-iso/package/conmon-master/conmon-master.mk
  deploy/iso/minikube-iso/package/crio-bin/crio-bin.hash
  deploy/iso/minikube-iso/package/crio-bin/crio-bin.mk
  deploy/iso/minikube-iso/package/crio-bin/crio-wipe.service
  deploy/iso/minikube-iso/package/crio-bin/crio.conf
  deploy/iso/minikube-iso/package/crio-bin/crio.conf.default
  deploy/iso/minikube-iso/package/crio-bin/crio.service
Labels: approved, cncf-cla: yes, ok-to-test, size/L

#5984 Update Makefile for 1.6.0-beta.1 release
  Makefile
Labels: approved, cncf-cla: yes, ok-to-test, size/XS

#5985 Add release notes for 1.6.0-beta.1
  CHANGELOG.md
Labels: approved, cncf-cla: yes, size/S

#5865 Add test case to test file sync between host and VM.
  test/integration/functional_test.go
  test/integration/testdata/sync.test
Labels: cncf-cla: yes, ok-to-test, size/M

#5992 Fix link to libvirt documentation for openSUSE
  site/content/en/docs/Reference/Drivers/includes/kvm2_usage.inc
Labels: approved, cncf-cla: yes, size/XS
