Repository kubernetes/minikube, pull requests merged in 2019-09, with the labels that each got.

#5247 Fix thrift ref
  go.mod
  go.sum
Labels: cncf-cla: yes, needs-ok-to-test, size/XS

#5241 Moved warning to minikube start command and print it to stderr
  cmd/minikube/cmd/root.go
  cmd/minikube/cmd/start.go
  pkg/minikube/notify/notify.go
Labels: cncf-cla: yes, needs-ok-to-test, size/M

#5249 More logs: exited containers, controller manager, double line count
  cmd/minikube/cmd/logs.go
  pkg/minikube/logs/logs.go
Labels: approved, cncf-cla: yes, size/S

#5250 Upgrade default Kubernetes version to v1.16.0-beta1
  pkg/minikube/bootstrapper/kubeadm/kubeadm_test.go
  pkg/minikube/constants/constants.go
Labels: approved, cncf-cla: yes, size/XS

#5253 Get make builds working on Windows
  Makefile
  go.mod
  site/content/en/docs/Contributing/building.en.md
Labels: approved, cncf-cla: yes, size/S

#5119 Added uninstallation procedures for minikube
  installers/windows/minikube.nsi
  site/content/en/docs/Reference/uninstalling_minikube.md
Labels: cncf-cla: yes, needs-ok-to-test, size/M

#5228 Improve test coverage for proxy package
  pkg/minikube/proxy/proxy.go
  pkg/minikube/proxy/proxy_test.go
Labels: cncf-cla: yes, ok-to-test, size/L

#5262 fix windows pathing in Makefile
  Makefile
Labels: approved, cncf-cla: yes, size/XS

#5261 Update build scripts to handle alpha/beta releases
  hack/jenkins/release_build_and_upload.sh
  hack/jenkins/release_github_page.sh
Labels: approved, cncf-cla: yes, size/L

#5263 skip json and brew update if this is a non-standard release
  hack/jenkins/release_update_brew.sh
  hack/jenkins/release_update_releases_json.sh
Labels: approved, cncf-cla: yes, size/S

#5264 Allow alpha/beta releases to be tagged
  hack/tag_release.sh
Labels: approved, cncf-cla: yes, size/XS

#5272 Add GOPATH back to release script, add diagnostics
  hack/jenkins/release_build_and_upload.sh
Labels: approved, cncf-cla: yes, size/XS

#4759 Exit if --kubernetes-version is older than the oldest supported version
  cmd/minikube/cmd/start.go
Labels: cncf-cla: yes, needs-ok-to-test, size/S

#5086 Minimum CPUs check
  cmd/minikube/cmd/start.go
  pkg/minikube/constants/constants.go
Labels: cncf-cla: yes, needs-ok-to-test, size/S

#5232 improve test coverage for registry package
  pkg/minikube/registry/registry_test.go
Labels: cncf-cla: yes, ok-to-test, size/L

#5244 Change minikube config list to minikube config in documentation
  site/content/en/docs/Reference/Configuration/minikube.md
  site/content/en/docs/Reference/environment_variables.md
Labels: cncf-cla: yes, needs-ok-to-test, size/XS

#5273 Fix indent for linting
  cmd/minikube/cmd/start.go
Labels: approved, cncf-cla: yes, size/XS

#5274 Substitute dashes for tildes when generating Linux packages
  Makefile
  hack/jenkins/release_github_page.sh
Labels: approved, cncf-cla: yes, size/S

#5275 Add - for ~ replacement in release_build_and_upload
  hack/jenkins/release_build_and_upload.sh
Labels: approved, cncf-cla: yes, size/S

#5277 Update CHANGELOG to include the most recent commits
  CHANGELOG.md
Labels: cncf-cla: yes

#5276 Mark alpha/beta releases as a pre-release on GitHub
  hack/jenkins/release_github_page.sh
Labels: approved, cncf-cla: yes, size/XS

#4510 Add 'native-ssh' flag to 'minikube start' and 'minikube ssh'
  cmd/minikube/cmd/config/config.go
  cmd/minikube/cmd/ssh.go
  cmd/minikube/cmd/start.go
  go.sum
Labels: cncf-cla: yes, needs-ok-to-test, size/S

#5296 Add driver usage
  site/content/en/docs/Reference/Drivers/includes/hyperkit_usage.inc
  site/content/en/docs/Reference/Drivers/includes/hyperv_usage.inc
  site/content/en/docs/Reference/Drivers/includes/kvm2_usage.inc
  site/content/en/docs/Reference/Drivers/includes/none_usage.inc
  site/content/en/docs/Reference/Drivers/includes/parallels_usage.inc
  site/content/en/docs/Reference/Drivers/includes/vmware_macos_usage.inc
Labels: approved, cncf-cla: yes, size/M

#5303 Upgrade Docker, from 18.09.8 to 18.09.9
  deploy/iso/minikube-iso/package/docker-bin/docker-bin.hash
  deploy/iso/minikube-iso/package/docker-bin/docker-bin.mk
Labels: approved, cncf-cla: yes, size/XS

#5304 Upgrade crio to 1.15.1
  deploy/iso/minikube-iso/package/crio-bin/crio-bin.hash
  deploy/iso/minikube-iso/package/crio-bin/crio-bin.mk
  deploy/iso/minikube-iso/package/crio-bin/crio-bin.patch
  deploy/iso/minikube-iso/package/crio-bin/crio.conf
  deploy/iso/minikube-iso/package/crio-bin/crio.conf.default
Labels: approved, cncf-cla: yes, size/M

#5292 dashboard: When run as root, show URL instead of opening browser
  cmd/minikube/cmd/dashboard.go
Labels: cncf-cla: yes, needs-ok-to-test, size/XS

#5285 Kill all child processes when cleaning up integration tests
  test/integration/fn_addons.go
  test/integration/fn_cluster_status.go
  test/integration/fn_mount.go
  test/integration/fn_tunnel.go
  test/integration/util/common.go
  test/integration/util/minikube_runner.go
  test/integration/z_proxy_test.go
Labels: approved, cncf-cla: yes, size/M

#5311 forwarding docker/machine to machine-drivers/machine
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, size/XS

#5289 Skip http proxy localhost for docker env
  cmd/minikube/cmd/start.go
  cmd/minikube/cmd/start_test.go
Labels: cncf-cla: yes, needs-ok-to-test, size/M

#5319 Correct docker-machine-parallels brew formula name in the documentation
  site/content/en/docs/Reference/Drivers/includes/parallels_usage.inc
Labels: cncf-cla: yes, needs-ok-to-test, size/XS

#5300 improve problem test coverage
  pkg/minikube/problem/problem_test.go
Labels: cncf-cla: yes, needs-ok-to-test, size/M

#5321 Add error if a non-default profile name is used with the none driver
  cmd/minikube/cmd/start.go
Labels: approved, cncf-cla: yes, size/XS

#5322 version bump to v1.4.0-beta.1
  Makefile
Labels: cncf-cla: yes, size/XS

#5016 Remove "Ignoring --vm-driver" warning
  pkg/minikube/cluster/cluster.go
Labels: approved, cncf-cla: yes, do-not-merge/work-in-progress, size/XS

#5338 Upgrade crio to 1.15.2
  deploy/iso/minikube-iso/package/crio-bin/crio-bin.hash
  deploy/iso/minikube-iso/package/crio-bin/crio-bin.mk
Labels: approved, cncf-cla: yes, size/XS

#5341 integration tests: Arbitrarily extend addon timeouts
  test/integration/addons_test.go
Labels: approved, cncf-cla: yes, size/S

#5343 Bump version to v1.4.0-beta.2
  Makefile
Labels: approved, cncf-cla: yes, size/XS

#5342 Retire Kubernetes v1.10 support, update OldestKubernetesVersion to v1.11
  pkg/minikube/bootstrapper/kubeadm/kubeadm.go
  pkg/minikube/bootstrapper/kubeadm/kubeadm_test.go
  pkg/minikube/bootstrapper/kubeadm/testdata/v1.10/containerd-api-port.yaml
  pkg/minikube/bootstrapper/kubeadm/testdata/v1.10/containerd-pod-network-cidr.yaml
  pkg/minikube/bootstrapper/kubeadm/testdata/v1.10/containerd.yaml
  pkg/minikube/bootstrapper/kubeadm/testdata/v1.10/crio-options-gates.yaml
  pkg/minikube/bootstrapper/kubeadm/testdata/v1.10/crio.yaml
  pkg/minikube/bootstrapper/kubeadm/testdata/v1.10/default.yaml
  pkg/minikube/bootstrapper/kubeadm/testdata/v1.10/image-repository.yaml
  pkg/minikube/bootstrapper/kubeadm/testdata/v1.10/options.yaml
  pkg/minikube/bootstrapper/kubeadm/util.go
  pkg/minikube/bootstrapper/kubeadm/versions.go
  pkg/minikube/constants/constants.go
  site/content/en/docs/Reference/Configuration/kubernetes.md
Labels: approved, cncf-cla: yes, size/L

#5335 Fine-tune integration test logging
  pkg/minikube/assets/vm_assets.go
  pkg/minikube/cluster/cluster.go
  pkg/minikube/command/ssh_runner.go
  test/integration/addons_test.go
  test/integration/docker_test.go
  test/integration/helpers.go
  test/integration/main.go
  test/integration/start_stop_delete_test.go
  test/integration/version_upgrade_test.go
Labels: approved, cncf-cla: yes, size/M

#5344 Move update notification out of PersistentPreRun, improve update UI
  cmd/minikube/cmd/start.go
  pkg/minikube/notify/notify.go
Labels: approved, cncf-cla: yes, size/M

#5348 Integration de-flake: expand lock scopes, sync clock at creation
  pkg/minikube/bootstrapper/certs.go
  pkg/minikube/bootstrapper/kubeadm/kubeadm.go
  pkg/minikube/bootstrapper/kubeadm/util.go
  pkg/minikube/cluster/cluster.go
  pkg/minikube/cluster/cluster_test.go
  pkg/minikube/config/profile.go
  pkg/minikube/kubeconfig/settings.go
Labels: approved, cncf-cla: yes, size/L

#5362 Wrap shell command in backquotes
  site/content/en/docs/Contributing/addons.en.md
Labels: cncf-cla: yes, needs-ok-to-test, size/XS

#5361 Fix addon config
  site/content/en/docs/Contributing/addons.en.md
Labels: cncf-cla: yes, lgtm, needs-ok-to-test, size/S

#5369 Add more logging for integration test failures
  pkg/minikube/logs/logs.go
  test/integration/helpers.go
  test/integration/start_stop_delete_test.go
Labels: approved, cncf-cla: yes, size/XS

#5354 Automatically install docker-machine-driver-hyperkit if missing or incompatible
  cmd/minikube/cmd/root.go
  cmd/minikube/cmd/start.go
  pkg/drivers/drivers.go
  pkg/minikube/constants/constants.go
Labels: cncf-cla: yes, size/L

#5372 Use existing driver by default, improve driver conflict message
  cmd/minikube/cmd/start.go
  cmd/minikube/cmd/start_test.go
  pkg/minikube/out/style.go
  pkg/minikube/out/style_enum.go
Labels: approved, cncf-cla: yes, size/L

#5371 Minor improvement to driver download display
  pkg/drivers/drivers.go
Labels: approved, cncf-cla: yes, size/XS

#5373 Download version appropriate driver, add sha256 checksum check
  cmd/minikube/cmd/root.go
  pkg/drivers/drivers.go
  test/integration/driver_install_or_update_test.go
Labels: approved, cncf-cla: yes, size/M

#5351 Update golangci-lint to v1.18.0
  Makefile
Labels: approved, cncf-cla: yes, size/S

#5378 Revise leftover VM cleanup in integration tests
  hack/jenkins/common.sh
Labels: approved, cncf-cla: yes, size/L

#5381 Offset integration tests which start clusters by 5s
  test/integration/addons_test.go
  test/integration/docker_test.go
  test/integration/guest_env_test.go
  test/integration/gvisor_addon_test.go
  test/integration/helpers.go
  test/integration/start_stop_delete_test.go
  test/integration/version_upgrade_test.go
Labels: approved, cncf-cla: yes, size/M

#5382 Redirect machine driver logs to glog, reduce log spam elsewhere
  cmd/minikube/cmd/root.go
  cmd/minikube/main.go
  pkg/minikube/command/ssh_runner.go
  test/integration/docker_test.go
Labels: approved, cncf-cla: yes, size/M

#5290 Include port names in the 'minikube service' cmd's output
  pkg/minikube/service/service.go
  pkg/minikube/service/service_test.go
Labels: cncf-cla: yes, needs-ok-to-test, size/M

#5386 typo fixes: capitalize "CPU", remove duplicate "the"
  cmd/minikube/cmd/start.go
  pkg/minikube/cluster/cluster.go
  site/content/en/docs/Reference/Configuration/kubernetes.md
Labels: cncf-cla: yes, needs-ok-to-test, size/XS

#5385 UI: Indent driver download and sudo command display
  pkg/drivers/drivers.go
  pkg/util/progressbar.go
Labels: approved, cncf-cla: yes, size/XS

#5383 Provide actionable feedback when running an incompatible driver with root
  cmd/minikube/cmd/start.go
Labels: approved, cncf-cla: yes, size/XS

#5387 Fix markdown typo on release page
  hack/jenkins/release_github_page.sh
Labels: approved, cncf-cla: yes, size/XS

#5390 Retry StartHost only 3 times: 5 is excessive
  cmd/minikube/cmd/start.go
Labels: approved, cncf-cla: yes, size/XS

#5384 Update solutions, add HideCreateLink option
  pkg/minikube/exit/exit.go
  pkg/minikube/logs/logs.go
  pkg/minikube/logs/logs_test.go
  pkg/minikube/problem/err_map.go
  pkg/minikube/problem/problem.go
  pkg/minikube/problem/problem_test.go
Labels: approved, cncf-cla: yes, size/L

#5388 Include ISO files as part of a GitHub release
  hack/jenkins/release_github_page.sh
Labels: approved, cncf-cla: yes, size/S

#5395 Update default Kubernetes version to v1.16.0
  pkg/minikube/bootstrapper/kubeadm/kubeadm_test.go
  pkg/minikube/constants/constants.go
Labels: approved, cncf-cla: yes, size/S

#5389 Bump Makefile VERSION to v1.4.0
  Makefile
Labels: approved, cncf-cla: yes, size/XS

#5399 Fix RAW_VERSION/ISO_VERSION typo
  Makefile
Labels: approved, cncf-cla: yes, size/XS

#5397 Add --interactive flag to prevent stdin prompts
  cmd/minikube/cmd/start.go
  pkg/drivers/drivers.go
  pkg/drivers/drivers_test.go
  pkg/minikube/out/style.go
  test/integration/driver_install_or_update_test.go
Labels: approved, cncf-cla: yes, size/L

#5404 Address start lint error
  cmd/minikube/cmd/start.go
Labels: approved, cncf-cla: yes, size/XS

#5408 Add survey links to popular overview / getting started doc
  site/content/en/docs/Overview/_index.md
  site/content/en/docs/Start/includes/post_install.inc
Labels: approved, cncf-cla: yes, size/XS

#5403 Upgrade dashboard to 2.0.0b4
  cmd/minikube/cmd/dashboard.go
  deploy/addons/dashboard/dashboard-clusterrole.yaml
  deploy/addons/dashboard/dashboard-clusterrolebinding.yaml
  deploy/addons/dashboard/dashboard-configmap.yaml
  deploy/addons/dashboard/dashboard-dp.yaml
  deploy/addons/dashboard/dashboard-dp.yaml.tmpl
  deploy/addons/dashboard/dashboard-ns.yaml
  deploy/addons/dashboard/dashboard-role.yaml
  deploy/addons/dashboard/dashboard-rolebinding.yaml
  deploy/addons/dashboard/dashboard-sa.yaml
  deploy/addons/dashboard/dashboard-secret.yaml
  deploy/addons/dashboard/dashboard-svc.yaml
  pkg/minikube/assets/addons.go
  pkg/minikube/constants/constants.go
Labels: approved, cncf-cla: yes, size/XL

#5401 Remove duplicate handling of driver conflict, handle driver not-found…
  cmd/minikube/cmd/start.go
  pkg/minikube/cluster/cluster.go
Labels: approved, cncf-cla: yes, size/S

#5407 Delete host before retrying creation
  cmd/minikube/cmd/start.go
Labels: approved, cncf-cla: yes, size/XS

#5405 Update addon-manager to v9.0.2, improve startup & reconcile latency
  deploy/addons/addon-manager.yaml.tmpl
  pkg/minikube/constants/constants.go
Labels: approved, cncf-cla: yes, size/S

#5410 Update CHANGELOG for v1.4.0
  CHANGELOG.md
Labels: approved, cncf-cla: yes, size/M

#5411 Fix RELEASE_FLAGS undefined bug, add survey callout
  hack/jenkins/release_github_page.sh
Labels: cncf-cla: yes, size/XS

#5352 docs: Simplify kvm2, hyperkit, and hyperv usage
  site/content/en/docs/Reference/Drivers/includes/hyperkit_usage.inc
  site/content/en/docs/Reference/Drivers/includes/hyperv_usage.inc
  site/content/en/docs/Reference/Drivers/includes/kvm2_usage.inc
Labels: approved, cncf-cla: yes, do-not-merge/hold, size/M

#5413 Update docs to reflect v1.4.0 release
  site/config.toml
Labels: cncf-cla: yes, size/XS

#5258 improve test coverage in service pkg
  pkg/minikube/service/service.go
  pkg/minikube/service/service_test.go
Labels: cncf-cla: yes, needs-ok-to-test, size/L

#5414 Re-order hypervisor tabs on install page based on best user experience
  site/content/en/docs/Start/linux.md
  site/content/en/docs/Start/macos.md
  site/content/en/docs/Start/windows.md
Labels: approved, cncf-cla: yes, size/S

#5283 improve test coverage for sshutil package
  pkg/minikube/sshutil/sshutil_test.go
Labels: cncf-cla: yes, ok-to-test, size/M

#5421 Mention permanently pinning versions
  site/content/en/docs/Reference/Configuration/kubernetes.md
Labels: approved, cncf-cla: yes, size/S

#5409 Remove all functions from constants.go
  cmd/minikube/cmd/delete.go
  cmd/minikube/cmd/env_test.go
  cmd/minikube/cmd/root.go
  cmd/minikube/cmd/ssh-key.go
  cmd/minikube/cmd/start.go
  pkg/minikube/assets/addons.go
  pkg/minikube/assets/addons_test.go
  pkg/minikube/bootstrapper/bootstrapper.go
  pkg/minikube/bootstrapper/certs.go
  pkg/minikube/bootstrapper/certs_test.go
  pkg/minikube/bootstrapper/images/images.go
  pkg/minikube/bootstrapper/kubeadm/kubeadm.go
  pkg/minikube/cluster/cluster.go
  pkg/minikube/config/profile.go
  pkg/minikube/constants/constants.go
  pkg/minikube/drivers/hyperkit/driver.go
  pkg/minikube/drivers/hyperv/driver.go
  pkg/minikube/drivers/kvm2/driver.go
  pkg/minikube/drivers/none/driver.go
  pkg/minikube/drivers/parallels/driver.go
  pkg/minikube/drivers/virtualbox/driver.go
  pkg/minikube/drivers/vmware/driver.go
  pkg/minikube/drivers/vmwarefusion/driver.go
  pkg/minikube/localpath/localpath.go
  pkg/minikube/machine/cache_binaries.go
  pkg/minikube/machine/client.go
  pkg/minikube/machine/client_test.go
  pkg/minikube/notify/notify.go
  pkg/minikube/tests/dir_utils.go
  pkg/minikube/tunnel/tunnel_manager.go
  pkg/util/downloader.go
  pkg/util/downloader_test.go
  site/content/en/docs/Contributing/drivers.en.md
  test/integration/a_download_only_test.go
  test/integration/none_test.go
Labels: cncf-cla: yes, needs-ok-to-test, size/XL

#5356 Improve storageclass test coverage
  cmd/minikube/cmd/config/util.go
  pkg/minikube/storageclass/storageclass.go
  pkg/minikube/storageclass/storageclass_test.go
Labels: cncf-cla: yes, ok-to-test, size/L

#5428 fix-up typos in .travis.yml and check_install_golang.sh
  .travis.yml
  hack/jenkins/installers/check_install_golang.sh
Labels: cncf-cla: yes, needs-ok-to-test, size/XS

#5438 Wait longer for TestVersionUpgrade as old versions may need to retry
  test/integration/version_upgrade_test.go
Labels: approved, cncf-cla: yes, size/XS

#4980 Fix crash when deleting the cluster but it doesn't exist
  cmd/minikube/cmd/delete.go
  pkg/minikube/cluster/cluster.go
  site/content/en/docs/Contributing/building.en.md
Labels: cncf-cla: yes, needs-ok-to-test, size/S

#5427 Fix node InternalIP not matching host-only address
  pkg/minikube/bootstrapper/kubeadm/kubeadm.go
  pkg/minikube/bootstrapper/kubeadm/kubeadm_test.go
Labels: cncf-cla: yes, ok-to-test, size/M

#5445 Improve out test coverage
  pkg/minikube/out/style_test.go
Labels: cncf-cla: yes, needs-ok-to-test, size/L

#5441 Fix a variety of spelling mistakes and typos
  cmd/minikube/cmd/config/set_test.go
  cmd/minikube/cmd/config/util_test.go
  pkg/minikube/bootstrapper/kubeadm/kubeadm.go
  pkg/minikube/bootstrapper/kubeadm/versions_test.go
  pkg/minikube/config/config_test.go
  pkg/minikube/config/extra_options.go
  pkg/minikube/kubeconfig/kubeconfig_test.go
  pkg/minikube/problem/problem_test.go
  pkg/minikube/proxy/proxy_test.go
Labels: cncf-cla: yes, size/S

#5459 Run travis tests in parallel VMs
  .codecov.yml
  .travis.yml
  test.sh
Labels: approved, cncf-cla: yes, size/L

#5422 Improve reportcard
  cmd/minikube/cmd/delete.go
  cmd/minikube/cmd/start.go
  pkg/drivers/hyperkit/driver.go
  pkg/minikube/bootstrapper/certs.go
  pkg/minikube/config/profile.go
  pkg/minikube/constants/constants.go
  pkg/minikube/kubeconfig/kubeconfig.go
  pkg/minikube/kubeconfig/settings.go
  pkg/minikube/registry/registry_test.go
  pkg/minikube/storageclass/storageclass.go
  pkg/util/progressbar.go
Labels: approved, cncf-cla: yes, size/L

#5468 fix-up typo
  CHANGELOG.md
  cmd/minikube/cmd/config/prompt.go
Labels: cncf-cla: yes, ok-to-test, size/XS

#5465 Re-enable gvisor tests now that #5305 is resolved
  test/integration/gvisor_addon_test.go
Labels: approved, cncf-cla: yes, size/XS

#5466 Initial translations for fr, es, de, ja, and zh-CN
  pkg/minikube/extract/extract.go
  translations/de.json
  translations/es.json
  translations/fr-FR.json
  translations/fr.json
  translations/ja.json
Labels: approved, cncf-cla: yes, size/XXL

#5475 Setting travis-ci notification settings explicitly
  .travis.yml
Labels: approved, cncf-cla: yes, size/XS

#5460 Add solution for VERR_VMX_MSR_ALL_VMX_DISABLED
  pkg/minikube/problem/err_map.go
Labels: approved, cncf-cla: yes, size/XS

#5464 Add initial gvisor contrib doc
  site/content/en/docs/Contributing/gvisor.md
Labels: approved, cncf-cla: yes, size/M

#5430 Remove single-package constants from constants package
  cmd/minikube/cmd/cache.go
  cmd/minikube/cmd/cache_list.go
  cmd/minikube/cmd/config/addons_list.go
  cmd/minikube/cmd/config/config.go
  cmd/minikube/cmd/config/open.go
  cmd/minikube/cmd/config/set.go
  cmd/minikube/cmd/config/unset.go
  cmd/minikube/cmd/config/util.go
  cmd/minikube/cmd/config/view.go
  cmd/minikube/cmd/mount.go
  cmd/minikube/cmd/root.go
  cmd/minikube/cmd/root_test.go
  cmd/minikube/cmd/service.go
  cmd/minikube/cmd/start.go
  cmd/minikube/cmd/start_test.go
  cmd/minikube/cmd/status.go
  cmd/minikube/cmd/update-check.go
  deploy/minikube/release_sanity_test.go
  pkg/drivers/none/none.go
  pkg/gvisor/disable.go
  pkg/gvisor/enable.go
  pkg/minikube/assets/addons.go
  pkg/minikube/assets/addons_test.go
  pkg/minikube/bootstrapper/certs.go
  pkg/minikube/bootstrapper/kubeadm/kubeadm.go
  pkg/minikube/bootstrapper/kubeadm/templates.go
  pkg/minikube/bootstrapper/kubeadm/versions.go
  pkg/minikube/config/config.go
  pkg/minikube/constants/constants.go
  pkg/minikube/localpath/localpath.go
  pkg/minikube/machine/cache_images.go
  pkg/minikube/notify/constants.go
  pkg/minikube/notify/notify.go
  pkg/minikube/service/service.go
  pkg/minikube/vmpath/constants.go
  site/content/en/docs/Contributing/addons.en.md
Labels: cncf-cla: yes, ok-to-test, size/XL

#5483 fr: fix translations of environment & existent
  translations/fr.json
Labels: cncf-cla: yes, needs-ok-to-test, size/S

#5439 Fix order of parameters to CurrentContext funcs
  cmd/minikube/cmd/config/profile.go
  cmd/minikube/cmd/stop.go
Labels: approved, cncf-cla: yes, size/XS

#5491 PL translation
  translations/pl.json
Labels: cncf-cla: yes, needs-ok-to-test, size/XL
