Repository kubernetes/minikube, pull requests merged in 2019-12, with the labels that each got.

#5942 Add performance analysis packages to minikube ISO
  deploy/iso/minikube-iso/configs/minikube_defconfig
Labels: approved, cncf-cla: yes, ok-to-test, size/XS

#5739 Adds dm-crypt support
  deploy/iso/minikube-iso/board/coreos/minikube/linux_defconfig
Labels: cncf-cla: yes, ok-to-test, size/M

#6000 Use newer gvisor version
  pkg/gvisor/enable.go
Labels: cncf-cla: yes, ok-to-test, size/XS

#6031 Fix ingress-dns example manifest URL
  deploy/addons/ingress-dns/README.md
Labels: cncf-cla: yes, needs-ok-to-test, size/XS

#6010 typo: Fix typo in err_map key
  pkg/minikube/problem/err_map.go
Labels: cncf-cla: yes, needs-ok-to-test, size/XS

#6005 Explicitly find last release version for release script
  hack/release_notes.sh
Labels: approved, cncf-cla: yes, size/XS

#5988 show status in profile list
  cmd/minikube/cmd/config/profile_list.go
  go.mod
  pkg/minikube/config/types.go
Labels: approved, cncf-cla: yes, ok-to-test, size/M

#5957 Add tutorial for audit policy
  site/content/en/docs/Tutorials/audit-policy.md
Labels: cncf-cla: yes, ok-to-test, size/M

#5954 Remove depreacted annotation storageclass.beta.kubernetes.io
  deploy/addons/storage-provisioner-gluster/storage-provisioner-glusterfile.yaml.tmpl
  pkg/minikube/storageclass/storageclass.go
Labels: cncf-cla: yes, ok-to-test, size/XS

#5912 Make lock names uid and path specific to avoid conflicts
  cmd/minikube/cmd/config/util_test.go
  pkg/minikube/bootstrapper/certs.go
  pkg/minikube/config/profile.go
  pkg/minikube/kubeconfig/settings.go
  pkg/util/lock/lock.go
  pkg/util/lock/lock_test.go
Labels: approved, cncf-cla: yes, ok-to-test, size/L

#5862 delete boilerplate site page
  site/content/en/docs/Concepts/_index.md
Labels: approved, cncf-cla: yes, size/S

#5818 Don't use bash as the entrypoint for docker
  Makefile
Labels: approved, cncf-cla: yes, ok-to-test, size/XS

#5798 Make Kubernetes version sticky for a cluster instead of auto-upgrading
  cmd/minikube/cmd/start.go
  cmd/minikube/cmd/start_test.go
  test/integration/version_upgrade_test.go
Labels: cncf-cla: yes, ok-to-test, size/L

#6039 Update dashboard to 2.0.0b8 and pre-cache it again
  deploy/addons/dashboard/dashboard-dp.yaml
  pkg/minikube/bootstrapper/images/images.go
Labels: approved, cncf-cla: yes, ok-to-test, size/XS

#5773 Add skeleton for performance analysis service
  Makefile
  cmd/performance/mkcmp/cmd/mkcmp.go
  cmd/performance/mkcmp/main.go
  cmd/performance/pr-bot/bot.go
Labels: approved, cncf-cla: yes, size/M

#6038 Add sch_netem kernel module for network emulation
  deploy/iso/minikube-iso/board/coreos/minikube/linux_defconfig
Labels: cncf-cla: yes, ok-to-test, size/XS

#6042 Update default k8s version to v1.17.0
  pkg/minikube/bootstrapper/kubeadm/kubeadm_test.go
  pkg/minikube/constants/constants.go
Labels: cncf-cla: yes, ok-to-test, size/S

#5935 Pre-cache the latest kube-addon-manager
  pkg/minikube/bootstrapper/images/images.go
Labels: approved, cncf-cla: yes, ok-to-test, size/XS

#6043 Sync cached image list for Kubernetes v1.17
  cmd/minikube/cmd/start.go
  pkg/minikube/bootstrapper/bootstrapper.go
  pkg/minikube/bootstrapper/images/images.go
  pkg/minikube/bootstrapper/images/images_test.go
  pkg/minikube/bootstrapper/images/kubeadm.go
  pkg/minikube/bootstrapper/images/kubeadm_test.go
  pkg/minikube/bootstrapper/images/repo.go
  pkg/minikube/bootstrapper/kubeadm/kubeadm.go
  pkg/minikube/cruntime/containerd.go
  pkg/minikube/cruntime/cri.go
  pkg/minikube/cruntime/crio.go
  pkg/minikube/machine/cache_images.go
  test/integration/a_serial_test.go
  test/integration/docker_test.go
  test/integration/start_stop_delete_test.go
Labels: approved, cncf-cla: yes, ok-to-test, size/XL

#6047 CI: adding time to to commit description
  hack/jenkins/common.sh
Labels: approved, cncf-cla: yes, ok-to-test, size/S

#6049 Version bump to v1.6.0
  CHANGELOG.md
  Makefile
Labels: approved, cncf-cla: yes, ok-to-test, size/M

#6053 Version bump doc to v1.6.0
  site/config.toml
Labels: cncf-cla: yes

#6050 Don't check image versions with the none driver (no crictl)
  test/integration/start_stop_delete_test.go
Labels: approved, cncf-cla: yes, ok-to-test, size/M

#6059 lock names: Remove uid suffix & hash entire path
  pkg/minikube/bootstrapper/certs.go
  pkg/minikube/kubeconfig/settings.go
  pkg/util/lock/lock.go
  pkg/util/lock/lock_test.go
Labels: approved, cncf-cla: yes, ok-to-test, size/M

#6066 Version bump to v1.6.1
  CHANGELOG.md
  Makefile
Labels: approved, cncf-cla: yes, ok-to-test, size/XS

#6067 Version bump config.toml to v1.6.1
  site/config.toml
Labels: approved, cncf-cla: yes, size/XS

#6096 jenkins: delete all clusters
  hack/jenkins/common.sh
Labels: approved, cncf-cla: yes, ok-to-test, size/XS

#6118 exclude generated files from linting
  Makefile
Labels: approved, cncf-cla: yes, ok-to-test, size/XS

#6090 Fix update-context to use KUBECONFIG when the env is set
  cmd/minikube/cmd/update-context.go
  test/integration/functional_test.go
Labels: cncf-cla: yes, kind/bug, ok-to-test, size/S

#6125 add unit test for CalculateSizeInMB
  pkg/util/utils_test.go
Labels: cncf-cla: yes, needs-ok-to-test, size/S

#5833 Add hyperkit version check whether user's hyperkit is newer
  pkg/minikube/registry/drvs/hyperkit/hyperkit.go
  pkg/minikube/registry/drvs/hyperkit/hyperkit_test.go
Labels: cncf-cla: yes, kind/bug, ok-to-test, size/L

#6091 Update ingress-dns addon
  deploy/addons/ingress-dns/ingress-dns-pod.yaml
Labels: cncf-cla: yes, ok-to-test, size/XS

#6110 Fixed IPv6 format for SSH
  cmd/minikube/cmd/start.go
Labels: cncf-cla: yes, ok-to-test, size/XS

#6111 Offline: always transfer image if lookup fails, always download drivers
  cmd/minikube/cmd/start.go
  pkg/minikube/machine/cache_images.go
  test/integration/aaa_download_only_test.go
  test/integration/aab_offline_test.go
Labels: approved, cncf-cla: yes, ok-to-test, size/L

#6048 Minor release doc update
  site/content/en/docs/Contributing/releasing.en.md
Labels: approved, cncf-cla: yes, size/M

#6127 Add build tags so that the test only runs on Darwin
  pkg/minikube/registry/drvs/hyperkit/hyperkit_test.go
Labels: approved, cncf-cla: yes, size/XS

#6121 Change error text to encourage better issue reports
  pkg/minikube/exit/exit.go
Labels: approved, cncf-cla: yes, ok-to-test, size/XS

#6129 start: Remove create/delete retry loop
  cmd/minikube/cmd/start.go
Labels: approved, cncf-cla: yes, ok-to-test, size/S

#6128 problem: Refresh advice, flip hide vs show default for links
  pkg/minikube/exit/exit.go
  pkg/minikube/problem/err_map.go
  pkg/minikube/problem/problem.go
  pkg/minikube/problem/problem_test.go
Labels: approved, cncf-cla: yes, ok-to-test, size/XL

#6130 Bump up version to v1.6.2
  CHANGELOG.md
  Makefile
Labels: approved, cncf-cla: yes, ok-to-test, size/S

#6136 Update CHANGELOG.md
  CHANGELOG.md
Labels: approved, cncf-cla: yes, size/XS

#6081 Generate prettier logs for integration tests
  hack/jenkins/common.sh
  hack/jenkins/linux_integration_tests_kvm.sh
  hack/jenkins/linux_integration_tests_none.sh
  hack/jenkins/linux_integration_tests_virtualbox.sh
  hack/jenkins/minikube_set_pending.sh
  hack/jenkins/osx_integration_tests_hyperkit.sh
  hack/jenkins/osx_integration_tests_virtualbox.sh
  hack/jenkins/windows_integration_test_hyperv.ps1
  hack/jenkins/windows_integration_test_virtualbox.ps1
Labels: approved, cncf-cla: yes, ok-to-test, size/M

#6139 update site docs with latest release version
  site/config.toml
Labels: approved, cncf-cla: yes, size/XS

#6138 count of test failures in commit status description
  hack/jenkins/common.sh
Labels: approved, cncf-cla: yes, ok-to-test, size/S

#6051 adding feature to reload cache
  cmd/minikube/cmd/cache.go
  cmd/minikube/cmd/start.go
  go.mod
  pkg/minikube/image/cache.go
  pkg/minikube/image/image.go
  pkg/minikube/localpath/localpath.go
  pkg/minikube/localpath/localpath_test.go
  pkg/minikube/machine/cache_binaries.go
  pkg/minikube/machine/cache_images.go
  test/integration/functional_test.go
Labels: approved, cncf-cla: yes, ok-to-test, size/XL

#6137 Add constants_test
  pkg/util/constants_test.go
Labels: cncf-cla: yes, ok-to-test, size/M

#6144 implemented options command, fixes #5036
  cmd/minikube/cmd/options.go
  cmd/minikube/cmd/root.go
Labels: cncf-cla: yes, ok-to-test, size/M

#6154 Add istio addon for minikube
  cmd/minikube/cmd/config/config.go
  cmd/minikube/cmd/config/util.go
  deploy/addons/addon-manager.yaml.tmpl
  deploy/addons/istio-provisioner/istio-operator.yaml.tmpl
  deploy/addons/istio/README.md
  deploy/addons/istio/istio-default-profile.yaml.tmpl
  deploy/addons/layouts/istio/single.html
  pkg/minikube/assets/addons.go
  site/config.toml
  site/content/en/docs/Tasks/addons.md
Labels: cncf-cla: yes, ok-to-test, size/L

#6164 fix podman build documentation link
  site/content/en/docs/Tasks/building.md
Labels: cncf-cla: yes, needs-ok-to-test, size/XS

#6169 fix nvidia GPU docs
  site/content/en/docs/Tutorials/nvidia_gpu.md
Labels: cncf-cla: yes, needs-ok-to-test, size/XS

#6174 fix kic status comments
  pkg/drivers/kic/oci/oci.go
Labels: cncf-cla: yes, ok-to-test, size/XS

#6179 pkg/drivers/kic: fix wrong command in Unpause
  pkg/drivers/kic/kic.go
Labels: cncf-cla: yes, needs-ok-to-test, size/XS
