Repository kubernetes/minikube, pull requests merged in 2019-04, with the labels that each got.

#4040 Add conformance test script
  hack/conformance_tests.sh
Labels: cncf-cla: yes, size/M

#3997 Escape systemd special chars in docker-env
  pkg/provision/buildroot.go
  pkg/util/utils.go
  pkg/util/utils_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#4048 Fixed url for issues.
  pkg/minikube/problem/problem.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#4022 Upgrade Docker, from 18.06.2-ce to 18.06.3-ce
  deploy/iso/minikube-iso/package/docker-bin/docker-bin.hash
  deploy/iso/minikube-iso/package/docker-bin/docker-bin.mk
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4058 Fixed status checking with non-default apiserver-port.
  cmd/minikube/cmd/start.go
  cmd/minikube/cmd/status.go
  pkg/minikube/bootstrapper/bootstrapper.go
  pkg/minikube/bootstrapper/kubeadm/kubeadm.go
  pkg/util/kubeconfig.go
  test/integration/start_stop_delete_test.go
Labels: cncf-cla: yes, needs-ok-to-test, size/M

#4011 Add port name to service struct used in minikube service
  pkg/minikube/service/service.go
  pkg/minikube/service/service_test.go
Labels: cncf-cla: yes, size/L

#4059 Don't cache images when --vmdriver=none
  cmd/minikube/cmd/start.go
Labels: cncf-cla: yes, needs-ok-to-test, size/XS

#4030 Update Hyper-V daemons
  deploy/iso/minikube-iso/package/Config.in
  deploy/iso/minikube-iso/package/hv-kvp-daemon/Config.in
  deploy/iso/minikube-iso/package/hv-kvp-daemon/hv_kvp_daemon.mk
  deploy/iso/minikube-iso/package/hv-kvp-daemon/hv_kvp_daemon.service
  deploy/iso/minikube-iso/package/hyperv-daemons/70-hv_fcopy.rules
  deploy/iso/minikube-iso/package/hyperv-daemons/70-hv_kvp.rules
  deploy/iso/minikube-iso/package/hyperv-daemons/70-hv_vss.rules
  deploy/iso/minikube-iso/package/hyperv-daemons/Config.in
  deploy/iso/minikube-iso/package/hyperv-daemons/hv_fcopy_daemon.service
  deploy/iso/minikube-iso/package/hyperv-daemons/hv_kvp_daemon.service
  deploy/iso/minikube-iso/package/hyperv-daemons/hv_vss_daemon.service
  deploy/iso/minikube-iso/package/hyperv-daemons/hyperv-daemons.mk
Labels: cncf-cla: yes, size/L

#4076 Avoid surfacing "error: no objects passed to apply" non-error from addon-manager
  pkg/minikube/logs/logs.go
  pkg/minikube/logs/logs_test.go
Labels: cncf-cla: yes, needs-ok-to-test, size/XS

#4026 Escape ‘%’ in console.OutStyle arguments
  pkg/minikube/console/console.go
  pkg/minikube/console/console_test.go
Labels: cncf-cla: yes, size/M

#4052 more vm-driver=none documentation on resolve.conf
  docs/vmdriver-none.md
Labels: cncf-cla: yes, needs-ok-to-test, size/XS

#3737 Add --download-only option to start command
  cmd/minikube/cmd/cache.go
  cmd/minikube/cmd/start.go
  pkg/minikube/bootstrapper/bootstrapper.go
  pkg/minikube/bootstrapper/kubeadm/kubeadm.go
  pkg/minikube/cluster/cluster.go
  pkg/minikube/console/style.go
  pkg/minikube/constants/constants.go
  pkg/minikube/machine/cache_binaries.go
Labels: approved, cncf-cla: yes, needs-rebase, size/L

#4082 Fix broken build due to bad merge: restore waitCacheImages function.
  cmd/minikube/cmd/start.go
Labels: cncf-cla: yes, needs-ok-to-test, size/S

#4080 Added REGISTRY_STORAGE_DELETE_ENABLED environment variable for Registry addon
  deploy/addons/registry/registry-rc.yaml
Labels: cncf-cla: yes, needs-ok-to-test, size/XS

#3899 Use Reference, allow caching images with both Tag and Digest
  Gopkg.lock
  pkg/minikube/machine/cache_images.go
  vendor/github.com/google/go-containerregistry/pkg/authn/helper.go
  vendor/github.com/google/go-containerregistry/pkg/name/digest.go
  vendor/github.com/google/go-containerregistry/pkg/name/registry.go
  vendor/github.com/google/go-containerregistry/pkg/v1/config.go
  vendor/github.com/google/go-containerregistry/pkg/v1/doc.go
  vendor/github.com/google/go-containerregistry/pkg/v1/hash.go
  vendor/github.com/google/go-containerregistry/pkg/v1/image.go
  vendor/github.com/google/go-containerregistry/pkg/v1/index.go
  vendor/github.com/google/go-containerregistry/pkg/v1/manifest.go
  vendor/github.com/google/go-containerregistry/pkg/v1/partial/compressed.go
  vendor/github.com/google/go-containerregistry/pkg/v1/partial/uncompressed.go
  vendor/github.com/google/go-containerregistry/pkg/v1/partial/with.go
  vendor/github.com/google/go-containerregistry/pkg/v1/remote/delete.go
  vendor/github.com/google/go-containerregistry/pkg/v1/remote/image.go
  vendor/github.com/google/go-containerregistry/pkg/v1/remote/index.go
  vendor/github.com/google/go-containerregistry/pkg/v1/remote/list.go
  vendor/github.com/google/go-containerregistry/pkg/v1/remote/mount.go
  vendor/github.com/google/go-containerregistry/pkg/v1/remote/options.go
  vendor/github.com/google/go-containerregistry/pkg/v1/remote/transport/basic.go
  vendor/github.com/google/go-containerregistry/pkg/v1/remote/transport/bearer.go
  vendor/github.com/google/go-containerregistry/pkg/v1/remote/transport/error.go
  vendor/github.com/google/go-containerregistry/pkg/v1/remote/transport/ping.go
  vendor/github.com/google/go-containerregistry/pkg/v1/remote/transport/transport.go
  vendor/github.com/google/go-containerregistry/pkg/v1/remote/write.go
  vendor/github.com/google/go-containerregistry/pkg/v1/stream/layer.go
  vendor/github.com/google/go-containerregistry/pkg/v1/tarball/image.go
  vendor/github.com/google/go-containerregistry/pkg/v1/tarball/layer.go
  vendor/github.com/google/go-containerregistry/pkg/v1/tarball/write.go
  vendor/github.com/google/go-containerregistry/pkg/v1/v1util/nop.go
  vendor/github.com/google/go-containerregistry/pkg/v1/v1util/verify.go
  vendor/github.com/google/go-containerregistry/pkg/v1/v1util/zip.go
Labels: approved, cncf-cla: yes, size/XXL

#3886 Decrease cyclomatic complexity
  cmd/minikube/cmd/config/util.go
  cmd/minikube/cmd/start.go
  pkg/minikube/bootstrapper/kubeadm/kubeadm.go
  pkg/minikube/cluster/cluster.go
  pkg/minikube/tunnel/tunnel.go
  pkg/minikube/tunnel/tunnel_manager_test.go
  pkg/minikube/tunnel/tunnel_test.go
  pkg/provision/buildroot.go
  pkg/util/config.go
  pkg/util/kubeconfig_test.go
  test/integration/mount_test.go
  test/integration/tunnel_test.go
Labels: approved, cncf-cla: yes, size/XXL

#4086 Fixed ignored error, noticed by ineffassign
  pkg/minikube/service/service.go
Labels: approved, cncf-cla: yes, size/XS

#4112 VirtualBox won't boot a 64bits VM when Hyper-V is activated
  pkg/minikube/problem/err_map.go
Labels: cncf-cla: yes, size/XS

#4095 Systemd returns error on inactive, so allow that
  cmd/minikube/cmd/env.go
Labels: approved, cncf-cla: yes, size/S

#4133 Update default Kubernetes version to 1.14.1
  pkg/minikube/bootstrapper/kubeadm/kubeadm_test.go
  pkg/minikube/bootstrapper/kubeadm/testdata/containerd-api-port__default.yaml
  pkg/minikube/bootstrapper/kubeadm/testdata/containerd__default.yaml
  pkg/minikube/bootstrapper/kubeadm/testdata/crio-options-gates__default.yaml
  pkg/minikube/bootstrapper/kubeadm/testdata/crio__default.yaml
  pkg/minikube/bootstrapper/kubeadm/testdata/default__default.yaml
  pkg/minikube/bootstrapper/kubeadm/testdata/image-repository__default.yaml
  pkg/minikube/bootstrapper/kubeadm/testdata/options__default.yaml
  pkg/minikube/constants/constants.go
Labels: cncf-cla: yes, needs-ok-to-test, size/S

#4123 Fix the Data Loss section of vmdriver-none.md: kubectl -> kubelet
  docs/vmdriver-none.md
Labels: cncf-cla: yes, needs-ok-to-test, size/XS

#4115 Reroute logs printed directly to stdout
  pkg/minikube/machine/cache_images.go
Labels: cncf-cla: yes, ok-to-test, size/S

#4141 Download ISO image before Docker images, as it's required first
  cmd/minikube/cmd/start.go
  pkg/minikube/cluster/cluster.go
Labels: approved, cncf-cla: yes, size/S

#4142 Add user-friendly error messages for known issues.
  pkg/minikube/problem/err_map.go
Labels: cncf-cla: yes, do-not-merge/work-in-progress, needs-ok-to-test, size/S

#4149 Revert "Add user-friendly error messages for known issues."
  pkg/minikube/problem/err_map.go
Labels: cncf-cla: yes

#4105 fix tunnel integration tests for driver None
  test/integration/tunnel_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#4009 Accessing minikube Dashboard UI
  README.md
Labels: cncf-cla: yes, size/XS

#4116 Assert that docker has started rather than explicitly restarting it
  pkg/minikube/cruntime/cruntime_test.go
  pkg/minikube/cruntime/docker.go
Labels: cncf-cla: yes, needs-ok-to-test, size/XS

#4110 Don't load Minikube on boot
  pkg/minikube/bootstrapper/kubeadm/kubeadm.go
Labels: cncf-cla: yes, needs-ok-to-test, size/XS

#4152 Add user-friendly error messages for VBOX_THIRD_PARTY & HYPERV_NO_VSWITCH
  pkg/minikube/problem/err_map.go
Labels: cncf-cla: yes, size/S

#4139 BugFix: ExecRunner.Copy now parses permissions strings as octal
  pkg/minikube/bootstrapper/exec_runner.go
  pkg/minikube/machine/cache_binaries.go
Labels: cncf-cla: yes, needs-ok-to-test, size/XS

#4049 update-context is confusing with profiles
  cmd/minikube/cmd/update-context.go
Labels: cncf-cla: yes, size/XS

#4156 Update release documentation
  docs/contributors/releasing_minikube.md
Labels: cncf-cla: yes, size/XS

#4159 Add sharifelgamal@ to MAINTAINERS
  MAINTAINERS
Labels: approved, cncf-cla: yes, size/XS

#4158 Add 1.0.1 release notes to CHANGELOG
  CHANGELOG.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#4160 Update more release documentation
  docs/contributors/releasing_minikube.md
Labels: approved, cncf-cla: yes, size/XS

#4155 Update Makefile for 1.0.1 release
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4174 Remove unused ArchLinux releaser, raise errors if Brew push fails.
  hack/jenkins/release_update_brew.sh
  hack/jenkins/release_update_installers.sh
Labels: approved, cncf-cla: yes, size/L

#4178 Fixing arch linux package url
  docs/contributors/releasing_minikube.md
Labels: cncf-cla: yes

#4091 Adding support for s390x
  .gitignore
  Makefile
  deploy/addons/addon-manager.template
  deploy/addons/dashboard/dashboard-dp.template
  deploy/addons/heapster/heapster-rc.template
  deploy/addons/heapster/influx-grafana-rc.template
  deploy/addons/ingress/ingress-dp.template
  deploy/addons/metrics-server/metrics-server-deployment.template
  deploy/addons/storage-provisioner/storage-provisioner.template
  deploy/storage-provisioner/Dockerfile-s390x
  pkg/minikube/constants/constants.go
Labels: cncf-cla: yes, size/L

#4153 storageclass no longer beta #4148
  deploy/addons/storageclass/storageclass.yaml
Labels: cncf-cla: yes, needs-ok-to-test, size/XS
