Repository kubernetes/minikube, pull requests merged in 2019-08, with the labels that each got.

#4898 hyperv: Powershell was not found in the path
  pkg/minikube/problem/err_map.go
Labels: approved, cncf-cla: yes, size/XS

#4950 Improve driver none stop to work on older systems
  pkg/drivers/none/none.go
Labels: approved, cncf-cla: yes, size/XS

#4948 parallel integration tests 4
  .gitignore
  go.mod
  go.sum
  hack/jenkins/common.sh
  hack/jenkins/linux_integration_tests_kvm.sh
  hack/jenkins/linux_integration_tests_none.sh
  hack/jenkins/linux_integration_tests_virtualbox.sh
  hack/jenkins/osx_integration_tests_hyperkit.sh
  hack/jenkins/osx_integration_tests_virtualbox.sh
  pkg/util/kubernetes.go
  test/integration/a_download_only_test.go
  test/integration/containerd_test.go
  test/integration/docker_test.go
  test/integration/flags.go
  test/integration/fn_addons.go
  test/integration/fn_cluster_dns.go
  test/integration/fn_cluster_env.go
  test/integration/fn_cluster_logs.go
  test/integration/fn_cluster_ssh.go
  test/integration/fn_cluster_status.go
  test/integration/fn_mount.go
  test/integration/fn_profile.go
  test/integration/fn_pv.go
  test/integration/fn_tunnel.go
  test/integration/functional_test.go
  test/integration/iso_test.go
  test/integration/persistence_test.go
  test/integration/start_stop_delete_test.go
  test/integration/util/common.go
  test/integration/util/kubectl_runner.go
  test/integration/util/minikube_runner.go
  test/integration/util/util.go
  test/integration/version_upgrade_test.go
  test/integration/z_proxy_test.go
Labels: approved, cncf-cla: yes, size/XXL

#4961 Decrease ReasonableStartTime from 10 minutes to 5 minutes
  pkg/util/kubernetes.go
Labels: approved, cncf-cla: yes, size/XS

#4958 Log the underlying template error
  pkg/minikube/out/style.go
Labels: approved, cncf-cla: yes, size/XS

#4959 UI: Add profile name & distro version to intro, clarify other messages
  cmd/minikube/cmd/start.go
  pkg/minikube/bootstrapper/kubeadm/kubeadm.go
  pkg/minikube/cluster/cluster.go
  pkg/minikube/logs/logs.go
Labels: approved, cncf-cla: yes, size/M

#4960 logs: Add container status & cruntime logs
  cmd/minikube/cmd/logs.go
  pkg/minikube/cruntime/containerd.go
  pkg/minikube/cruntime/crio.go
  pkg/minikube/cruntime/cruntime.go
  pkg/minikube/cruntime/docker.go
  pkg/minikube/logs/logs.go
Labels: approved, cncf-cla: yes, size/M

#4607 Automatically set flags for MINIKUBE_ prefixed env vars
  cmd/minikube/cmd/start.go
Labels: cncf-cla: yes, needs-ok-to-test, size/S

#4934 Docs-site: Front-page beautification
  site/assets/icons/logo.svg
  site/assets/scss/_variables_project.scss
  site/config.toml
  site/content/en/_index.html
  site/layouts/partials/hooks/body-end.html
Labels: approved, cncf-cla: yes, size/L

#4966 logs container status: fallback to docker if crictl fails (none)
  pkg/minikube/logs/logs.go
Labels: approved, cncf-cla: yes, size/XS

#4971 Fix the new site installation instructions
  site/content/en/docs/Getting started/linux.md
Labels: approved, cncf-cla: yes, size/XS

#4962 Bump version to v1.3.0
  CHANGELOG.md
  Makefile
Labels: approved, cncf-cla: yes, size/M

#4972 Turn gopsutil errors into warnings
  cmd/minikube/cmd/start.go
Labels: approved, cncf-cla: yes, size/XS

#4944 Refactor extract writeconfig
  cmd/minikube/cmd/config/config.go
  cmd/minikube/cmd/config/config_test.go
  cmd/minikube/cmd/config/set.go
  cmd/minikube/cmd/config/unset.go
  pkg/minikube/config/config.go
  pkg/minikube/config/config_test.go
Labels: cncf-cla: yes, lgtm, size/L

#4984 Switch ISO download impl from go-download to go-getter
  go.mod
  go.sum
  pkg/util/downloader.go
  pkg/util/progressbar.go
Labels: approved, cncf-cla: yes, size/L

#4986 Update latest kubernetes version to v1.15.2
  pkg/minikube/constants/constants.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4988 Fix docs merge breakage: Call initTabs() to activate tabs UI
  site/layouts/partials/hooks/body-end.html
  site/layouts/partials/hooks/head-end.html
Labels: approved, cncf-cla: yes, size/XS

#4941 wip: Improve coverage: add kubeconfig tests
  pkg/util/kubeconfig_test.go
  pkg/util/testdata/kubeconfig/config1
  pkg/util/testdata/kubeconfig/config2
Labels: cncf-cla: yes, do-not-merge/work-in-progress, size/L

#5000 Use a temp dest to atomically download the iso
  pkg/util/downloader.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5004 Fixed the template for dashboard output
  cmd/minikube/cmd/dashboard.go
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/XS

#5001 Consistently name test targets <driver>_<os>
  hack/jenkins/linux_integration_tests_kvm.sh
  hack/jenkins/linux_integration_tests_none.sh
  hack/jenkins/linux_integration_tests_virtualbox.sh
  hack/jenkins/minikube_set_pending.sh
  hack/jenkins/minishift_linux_integration_tests_kvm.sh
  hack/jenkins/osx_integration_tests_hyperkit.sh
  hack/jenkins/osx_integration_tests_virtualbox.sh
  hack/jenkins/windows_integration_test_hyperv.ps1
  hack/jenkins/windows_integration_test_virtualbox.ps1
  hack/jenkins/windows_integration_test_virtualbox_kubeadm_crio.ps1
Labels: approved, cncf-cla: yes, size/L

#5023 Fix prepareNone and add integration test for it
  cmd/minikube/cmd/start.go
  pkg/minikube/out/style.go
  pkg/util/kubeconfig.go
  test/integration/none_test.go
Labels: approved, cncf-cla: yes, size/L

#5026 Restore --disable-driver-mounts flag
  cmd/minikube/cmd/start.go
  test/integration/start_stop_delete_test.go
Labels: approved, cncf-cla: yes, size/S

#5018 Adding GOPROXY to Travis
  .travis.yml
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, size/XS

#4964 [2/3] Copy documentation into Hugo
  docs/persistent_volumes.md
  site/assets/scss/_variables_project.scss
  site/content/en/docs/Contributing/building.en.md
  site/content/en/docs/Contributing/guide.en.md
  site/content/en/docs/Contributing/iso.md
  site/content/en/docs/Contributing/testing.en.md
  site/content/en/docs/Reference/Commands/_index.md
  site/content/en/docs/Reference/Commands/addons.md
  site/content/en/docs/Reference/Commands/cache.md
  site/content/en/docs/Reference/Commands/completion.md
  site/content/en/docs/Reference/Commands/config.md
  site/content/en/docs/Reference/Commands/dashboard.md
  site/content/en/docs/Reference/Commands/delete.md
  site/content/en/docs/Reference/Commands/docker-env.md
  site/content/en/docs/Reference/Commands/ip.md
  site/content/en/docs/Reference/Commands/kubectl.md
  site/content/en/docs/Reference/Commands/logs.md
  site/content/en/docs/Reference/Commands/mount.md
  site/content/en/docs/Reference/Commands/profile.md
  site/content/en/docs/Reference/Commands/service.md
  site/content/en/docs/Reference/Commands/ssh-key.md
  site/content/en/docs/Reference/Commands/ssh.md
  site/content/en/docs/Reference/Commands/start.md
  site/content/en/docs/Reference/Commands/status.md
  site/content/en/docs/Reference/Commands/stop.md
  site/content/en/docs/Reference/Commands/tunnel.md
  site/content/en/docs/Reference/Commands/update-check.md
  site/content/en/docs/Reference/Commands/update-context.md
  site/content/en/docs/Reference/Commands/version.md
  site/content/en/docs/Reference/Configuration/_index.md
  site/content/en/docs/Reference/Configuration/kubernetes.md
  site/content/en/docs/Reference/Configuration/minikube.md
  site/content/en/docs/Reference/Networking/_index.md
  site/content/en/docs/Reference/Networking/proxy.md
  site/content/en/docs/Reference/Networking/vpn.md
  site/content/en/docs/Reference/_index.md
  site/content/en/docs/Reference/cache.md
  site/content/en/docs/Reference/persistent_volumes.md
  site/content/en/docs/Reference/runtimes.md
  site/content/en/docs/Tasks/Registry/_index.md
  site/content/en/docs/Tasks/Registry/insecure.md
  site/content/en/docs/Tasks/Registry/private.md
  site/content/en/docs/Tasks/_index.md
  site/content/en/docs/Tasks/debug.md
  site/content/en/docs/Tasks/sync.md
Labels: approved, cncf-cla: yes, size/XXL

#5035 Minor improvements to doc styling
  site/assets/scss/_variables_project.scss
  site/content/en/docs/Reference/Commands/addons.md
  site/content/en/docs/Reference/Commands/cache.md
  site/content/en/docs/Reference/Commands/completion.md
  site/content/en/docs/Reference/Commands/config.md
  site/content/en/docs/Reference/Commands/dashboard.md
  site/content/en/docs/Reference/Commands/delete.md
  site/content/en/docs/Reference/Commands/ip.md
  site/content/en/docs/Reference/Commands/kubectl.md
  site/content/en/docs/Reference/Commands/profile.md
  site/content/en/docs/Reference/Commands/service.md
  site/content/en/docs/Reference/Commands/status.md
  site/content/en/docs/Reference/Commands/stop.md
  site/content/en/docs/Reference/Commands/tunnel.md
  site/content/en/docs/Reference/Commands/update-context.md
  site/content/en/docs/Reference/Commands/version.md
  site/content/en/docs/Tasks/dashboard.md
  site/static/css/tabs.css
Labels: approved, cncf-cla: yes, size/L

#5034 Remove obsolete MAINTAINERS file
  MAINTAINERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5025 Upgrade cheggaaa/pb from v1.0.27 to v3.0.1
  go.mod
  go.sum
  pkg/util/progressbar.go
Labels: cncf-cla: yes, needs-ok-to-test, size/M

#4814 Localization support for help text
  cmd/minikube/cmd/config/profile_list.go
  cmd/minikube/cmd/dashboard.go
  cmd/minikube/cmd/logs.go
  cmd/minikube/cmd/root.go
  cmd/minikube/cmd/start.go
  cmd/minikube/main.go
  hack/jenkins/minikube_cross_build_and_upload.sh
  hack/jenkins/minikube_set_pending.sh
  pkg/minikube/extract/extract.go
  translations/fr-FR.json
  translations/zh-CN.json
Labels: approved, cncf-cla: yes, size/XL

#5050 none_test: Make sure minikube is up before checkout .minikube directory
  test/integration/none_test.go
Labels: approved, cncf-cla: yes, size/M

#5049 Add caching & env var docs, redirect old pages to Hugo
  CONTRIBUTING.md
  docs/accessing_etcd.md
  docs/addons.md
  docs/alternative_runtimes.md
  docs/building_images_within_the_vm.md
  docs/cache.md
  docs/cli_commands.md
  docs/configuring_kubernetes.md
  docs/contributors/README.md
  docs/contributors/adding_an_addon.md
  docs/contributors/adding_driver.md
  docs/contributors/build_guide.md
  docs/contributors/ci_builds.md
  docs/contributors/minikube_iso.md
  docs/contributors/principles.md
  docs/contributors/releasing_minikube.md
  docs/contributors/roadmap.md
  docs/dashboard.md
  docs/debugging.md
  docs/drivers.md
  docs/env_vars.md
  docs/gpu.md
  docs/host_folder_mount.md
  docs/http_proxy.md
  docs/insecure_registry.md
  docs/networking.md
  docs/offline.md
  docs/openid_connect_auth.md
  docs/persistent_volumes.md
  docs/reusing_the_docker_daemon.md
  docs/syncing-files.md
  docs/tunnel.md
  docs/vmdriver-none.md
  site/content/en/docs/Reference/Networking/proxy.md
  site/content/en/docs/Reference/Networking/vpn.md
  site/content/en/docs/Reference/disk_cache.md
  site/content/en/docs/Reference/environment_variables.md
  site/content/en/docs/Start/_index.md
  site/content/en/docs/Start/includes/post_install.inc
  site/content/en/docs/Start/linux.md
  site/content/en/docs/Start/macos.md
  site/content/en/docs/Start/windows.md
  site/content/en/docs/Tasks/building.md
  site/content/en/docs/Tasks/caching.md
Labels: approved, cncf-cla: yes, size/XXL

#4933 Remove all minikube dependencies from drivers
  Makefile
  pkg/drivers/hyperkit/driver.go
  pkg/drivers/kvm/kvm.go
Labels: approved, cncf-cla: yes, size/M

#5051 Typo in okteto's name
  site/content/en/docs/Tasks/sync.md
Labels: cncf-cla: yes, needs-ok-to-test, size/XS

#5052 Update code references to new documentation URL's
  CHANGELOG.md
  cmd/minikube/cmd/start.go
  hack/conformance_tests.sh
  pkg/drivers/kvm/gpu.go
  pkg/drivers/none/none.go
  pkg/minikube/cluster/cluster.go
  pkg/minikube/constants/constants.go
  pkg/minikube/problem/err_map.go
  site/content/en/_index.html
  site/content/en/docs/Overview/_index.md
  site/content/en/docs/Tasks/docker_registry.md
  site/content/en/docs/Tutorials/openid_connect_auth.md
  translations/fr-FR.json
  translations/zh-CN.json
Labels: approved, cncf-cla: yes, size/M

#5053 Fix rough edges in documentation presentation
  site/config.toml
  site/content/en/docs/Overview/_index.md
  site/content/en/docs/Reference/_index.md
  site/content/en/docs/Tasks/_index.md
  site/content/en/docs/Tutorials/_index.md
Labels: approved, cncf-cla: yes, size/S

#5055 Update Makefile and CHANGELOG for v1.3.1
  CHANGELOG.md
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/S

#5058 Update docs to v1.3.1, fix start URL, checkoff roadmap item
  site/content/en/_index.html
  site/content/en/blog/news/first-post/featured-sunset-get.png
  site/content/en/blog/news/first-post/index.md
  site/content/en/blog/news/new-website.md
  site/content/en/blog/news/second-post.md
  site/content/en/blog/releases/in-depth-monoliths-detailed-spec.md
  site/content/en/blog/releases/v1.13.1.md
  site/content/en/docs/Contributing/roadmap.en.md
Labels: approved, cncf-cla: yes, size/XL

#5060 docs: Mark v1.3.1 as latest, fix hyperkit install doc
  site/config.toml
  site/content/en/docs/Reference/Drivers/includes/hyperkit_usage.inc
  site/static/css/tabs.css
Labels: approved, cncf-cla: yes, size/S

#5066 Fix typo: /docs/contribute -> /docs/contributing
  site/content/en/_index.html
Labels: approved, cncf-cla: yes, size/XS

#5067 Use https for slack.kubernetes.io link
  site/content/en/_index.html
Labels: approved, cncf-cla: yes, size/XS

#5064 Fix site documentation links to docker_daemon.md
  site/content/en/docs/Tasks/building.md
  site/content/en/docs/Tasks/docker_registry.md
Labels: approved, cncf-cla: yes, size/XS

#5003 Refactor Kubeconfig
  cmd/minikube/cmd/config/profile.go
  cmd/minikube/cmd/delete.go
  cmd/minikube/cmd/mount.go
  cmd/minikube/cmd/start.go
  cmd/minikube/cmd/status.go
  cmd/minikube/cmd/stop.go
  cmd/minikube/cmd/update-context.go
  cmd/util/util.go
  cmd/util/util_test.go
  pkg/minikube/bootstrapper/certs.go
  pkg/minikube/bootstrapper/kubeadm/kubeadm.go
  pkg/minikube/config/types.go
  pkg/minikube/constants/constants.go
  pkg/minikube/kubeconfig/context.go
  pkg/minikube/kubeconfig/context_test.go
  pkg/minikube/kubeconfig/kubeconfig.go
  pkg/minikube/kubeconfig/kubeconfig_test.go
  pkg/minikube/kubeconfig/settings.go
  pkg/minikube/kubeconfig/testdata/kubeconfig/config1
  pkg/minikube/kubeconfig/testdata/kubeconfig/config2
  pkg/util/constants.go
  pkg/util/kubeconfig.go
  test/integration/functional_test.go
  test/integration/start_stop_delete_test.go
  test/integration/z_proxy_test.go
Labels: approved, cncf-cla: yes, size/XXL

#5045 fix typo of vmdriver-none.md
  site/content/en/docs/Reference/Drivers/none.md
Labels: approved, cncf-cla: yes, ok-to-test, size/XS

#5071 Restore most of the README.md text
  README.md
Labels: approved, cncf-cla: yes, size/M

#5068 Create empty profile if profile is set to a not-existing profile
  cmd/minikube/cmd/config/profile.go
  cmd/minikube/cmd/delete.go
  cmd/minikube/cmd/start.go
  pkg/minikube/config/config.go
  pkg/minikube/config/profile.go
  pkg/minikube/config/profile_test.go
  pkg/minikube/config/testdata/.minikube2/profiles/p1/config.json
  pkg/minikube/config/testdata/.minikube2/profiles/p2/config.json
  pkg/minikube/config/testdata/.minikube2/profiles/p3_empty/config.json
  pkg/minikube/config/testdata/.minikube2/profiles/p4_invalid_file/config.json
  pkg/minikube/config/testdata/.minikube2/profiles/p5_partial_config/config.json
  pkg/minikube/constants/constants.go
Labels: approved, cncf-cla: yes, size/L

#5073 Site top bar: rename "Blog" to "News", add "GitHub" link.
  site/config.toml
  site/content/en/blog/_index.md
Labels: approved, cncf-cla: yes, size/XS

#5074 Update screenshot, remove help wanted image
  README.md
  images/help_wanted.jpg
  images/start.jpg
  site/content/en/_index.html
  site/content/en/start.jpg
  site/content/en/start.png
Labels: approved, cncf-cla: yes, size/XS

#4993 start.go: logging message typo correction
  cmd/minikube/cmd/start.go
Labels: cncf-cla: yes, needs-ok-to-test, size/XS

#4991 Re-Added time synchronization between host/VM
  deploy/iso/minikube-iso/board/coreos/minikube/rootfs-overlay/etc/systemd/system/systemd-timesyncd.service.d/disable-virtualbox.conf
  deploy/iso/minikube-iso/configs/minikube_defconfig
Labels: cncf-cla: yes, needs-ok-to-test, size/XS

#5070 Add documentation & make targets for starting a local doc site
  .gitignore
  Makefile
  site/content/en/docs/Contributing/documentation.en.md
  test.sh
Labels: approved, cncf-cla: yes, size/M

#5079 Update screenshot to use Droid Sans Mono 18pt
  README.md
  site/content/en/start.png
Labels: approved, cncf-cla: yes, size/XS

#5056 Improve handling KUBECONFIG environment variable with invalid entries
  pkg/minikube/kubeconfig/kubeconfig.go
  pkg/minikube/kubeconfig/kubeconfig_test.go
Labels: cncf-cla: yes, needs-ok-to-test, size/S

#4751 Improve the release tarballs with compression and checksum
  Makefile
Labels: approved, cncf-cla: yes, size/S

#5075 Improve parallel run reliability by putting lock on files before writing
  cmd/minikube/cmd/dashboard.go
  cmd/minikube/cmd/service.go
  cmd/minikube/cmd/start.go
  cmd/minikube/cmd/stop.go
  go.mod
  go.sum
  pkg/drivers/none/none.go
  pkg/minikube/bootstrapper/kubeadm/kubeadm.go
  pkg/minikube/bootstrapper/kubeadm/util.go
  pkg/minikube/cluster/cluster.go
  pkg/minikube/config/profile.go
  pkg/minikube/extract/extract.go
  pkg/minikube/kubeconfig/kubeconfig.go
  pkg/minikube/kubeconfig/kubeconfig_test.go
  pkg/minikube/notify/notify.go
  pkg/minikube/service/service.go
  pkg/provision/buildroot.go
  pkg/util/config.go
  pkg/util/crypto.go
  pkg/util/kubernetes.go
  pkg/util/lock/lock.go
  pkg/util/retry/retry.go
  pkg/util/retry/retry_test.go
  pkg/util/utils.go
  pkg/util/utils_test.go
  test/integration/a_download_only_test.go
  test/integration/fn_addons.go
  test/integration/fn_cluster_dns.go
  test/integration/fn_cluster_env.go
  test/integration/fn_cluster_status.go
  test/integration/fn_mount.go
  test/integration/fn_pv.go
  test/integration/fn_tunnel.go
  test/integration/start_stop_delete_test.go
  test/integration/util/common.go
  test/integration/util/kubectl_runner.go
  test/integration/util/minikube_runner.go
  test/integration/version_upgrade_test.go
Labels: approved, cncf-cla: yes, size/XL

#5082 Fix TestVersionUpgrade for Windows
  test/integration/version_upgrade_test.go
Labels: approved, cncf-cla: yes, size/XS

#4834 [FEATURE] allow to set container-runtime via config
  cmd/minikube/cmd/config/config.go
Labels: approved, cncf-cla: yes, size/XS

#4844 [FEATURE] insecure-registry via minikube config set
  cmd/minikube/cmd/config/config.go
Labels: approved, cncf-cla: yes, size/XS

#4896 Advice user does command ssh on non existing profile
  pkg/minikube/problem/err_map.go
Labels: approved, cncf-cla: yes, do-not-merge/work-in-progress, size/XS

#5089 docs: brew install should be brew cask install
  site/content/en/docs/Start/macos.md
Labels: cncf-cla: yes, needs-ok-to-test, size/XS

#5092 cleanup: fix words in logging message
  pkg/drivers/kvm/gpu.go
Labels: cncf-cla: yes, needs-ok-to-test, size/XS

#5015 Support adding untrusted root CA certificates (corp certs)
  deploy/iso/minikube-iso/configs/minikube_defconfig
  pkg/minikube/bootstrapper/certs.go
  pkg/minikube/bootstrapper/certs_test.go
  site/content/en/docs/Tutorials/untrusted_root_certificate.md
Labels: cncf-cla: yes, needs-ok-to-test, size/L

#5094 Updated docs to add how to develop addons link
  site/content/en/docs/Tasks/addons.md
Labels: cncf-cla: yes, needs-ok-to-test, size/XS

#5102 cleanup: fix error message in crypto.go
  pkg/util/crypto.go
Labels: cncf-cla: yes, needs-ok-to-test, size/XS

#4717 Rebuild gvisor image for integration tests
  Makefile
  deploy/addons/gvisor/gvisor-pod.yaml.tmpl
  go.mod
  go.sum
  hack/jenkins/common.sh
  pkg/minikube/cruntime/containerd.go
  pkg/minikube/machine/cache_images.go
  test/integration/containerd_test.go
  test/integration/testdata/gvisor-addon-Dockerfile
Labels: cncf-cla: yes, size/M

#5106 delete: Clean up machine directory if DeleteHost fails to
  cmd/minikube/cmd/delete.go
  pkg/minikube/machine/client.go
Labels: approved, cncf-cla: yes, size/S

#5109 Update URL should be concatenated without a /
  pkg/minikube/notify/notify.go
Labels: approved, cncf-cla: yes, size/XS

#5115 Adding upgrade minikube docs for mac
  site/content/en/docs/Start/macos.md
Labels: cncf-cla: yes, needs-ok-to-test, size/S

#5112 cleanup: lock.go error message typo fix
  pkg/util/lock/lock.go
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/XS

#5095 Ensure specific golang version everywhere in CI based on Makefile
  Makefile
  hack/jenkins/installers/check_install_golang.sh
  hack/jenkins/minikube_cross_build_and_upload.sh
  hack/jenkins/release_build_and_upload.sh
Labels: approved, cncf-cla: yes, size/M

#5124 fix mis-spelling in README.md
  deploy/addons/storage-provisioner-gluster/README.md
Labels: cncf-cla: yes, needs-ok-to-test, size/XS

#5104 Provide default InstallURL in EngineOptions for libmachine
  pkg/minikube/cluster/cluster.go
Labels: approved, cncf-cla: yes, size/XS

#5131 fix wrong spells in flags.go
  test/integration/flags.go
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/XS

#5130 Update Skaffold link
  site/content/en/docs/Tasks/sync.md
Labels: cncf-cla: yes, needs-ok-to-test, size/XS

#5128 bump to go1.12.9
  .travis.yml
  Makefile
Labels: cncf-cla: yes, size/XS

#5135 clean up zombie procs before starting integration tests
  hack/jenkins/common.sh
Labels: approved, cncf-cla: yes, size/S

#5121 Add wait-timeout flag to start command and refactor util/kubernetes
  cmd/minikube/cmd/start.go
  hack/jenkins/common.sh
  pkg/kapi/kapi.go
  pkg/minikube/bootstrapper/bootstrapper.go
  pkg/minikube/bootstrapper/kubeadm/kubeadm.go
  pkg/minikube/bootstrapper/kubeadm/kubeadm_test.go
  pkg/minikube/bootstrapper/kubeadm/versions.go
  pkg/minikube/bootstrapper/kubeadm/versions_test.go
  pkg/minikube/config/extra_options.go
  pkg/minikube/config/extra_options_test.go
  pkg/minikube/config/types.go
  pkg/util/utils.go
  test/integration/containerd_test.go
  test/integration/flags.go
  test/integration/fn_addons.go
  test/integration/fn_cluster_dns.go
  test/integration/fn_mount.go
  test/integration/fn_pv.go
  test/integration/fn_tunnel.go
  test/integration/util/common.go
  test/integration/util/minikube_runner.go
  test/integration/version_upgrade_test.go
Labels: approved, cncf-cla: yes, size/L

#5136 skip gvisor test setup on mac
  hack/jenkins/common.sh
Labels: approved, cncf-cla: yes, size/S

#5143 fix wrong spells in containerd.go
  pkg/minikube/cruntime/containerd.go
Labels: cncf-cla: yes, needs-ok-to-test, size/XS

#5129 Provide example of using minikube with kvm
  site/content/en/docs/Reference/Drivers/includes/kvm2_usage.inc
Labels: cncf-cla: yes, needs-ok-to-test, size/S

#5148 remove duplicate import
  cmd/minikube/cmd/start.go
  pkg/minikube/translate/translate.go
Labels: approved, cncf-cla: yes, size/XS

#5151 fix none perm flake test
  test/integration/none_test.go
Labels: approved, cncf-cla: yes, size/XS

#5160 fix wrong spells in kapi.go
  pkg/kapi/kapi.go
Labels: cncf-cla: yes, needs-ok-to-test, size/XS

#5158 Add missing tab closing tag to fix tabs on macOS getting started guide
  site/content/en/docs/Start/macos.md
Labels: cncf-cla: yes, needs-ok-to-test, size/XS

#5159 Fixes broken Overview: links as per #5156
  site/content/en/docs/Overview/_index.md
Labels: cncf-cla: yes, needs-ok-to-test, size/XS

#5116 Refactor config.ReadConfig to accept a file
  cmd/minikube/cmd/cache.go
  cmd/minikube/cmd/config/config.go
  cmd/minikube/cmd/config/set.go
  cmd/minikube/cmd/config/unset.go
  cmd/minikube/cmd/config/view.go
  pkg/minikube/config/config.go
  pkg/minikube/config/config_test.go
  test/integration/config_test.go
  test/integration/util/minikube_runner.go
Labels: cncf-cla: yes, size/L

#5103 Only provision buildroot with BuildrootProvisioner
  pkg/minikube/cluster/cluster.go
  pkg/provision/buildroot.go
Labels: approved, cncf-cla: yes, size/XS

#4931 Clean up the make targets
  Makefile
Labels: approved, cncf-cla: yes, size/M

#4840 Added command to generate the documentation
  cmd/minikube/cmd/generate-docs.go
Labels: cncf-cla: yes, needs-ok-to-test, size/M

#5162 Run gofmt -w -s
  cmd/minikube/cmd/generate-docs.go
  pkg/minikube/out/style.go
Labels: approved, cncf-cla: yes, size/XS

#5069 Set NewestKubernetesVersion to v1.16.0-beta.1
  pkg/minikube/bootstrapper/kubeadm/kubeadm_test.go
  pkg/minikube/bootstrapper/kubeadm/testdata/v1.16/containerd-api-port.yaml
  pkg/minikube/bootstrapper/kubeadm/testdata/v1.16/containerd-pod-network-cidr.yaml
  pkg/minikube/bootstrapper/kubeadm/testdata/v1.16/containerd.yaml
  pkg/minikube/bootstrapper/kubeadm/testdata/v1.16/crio-options-gates.yaml
  pkg/minikube/bootstrapper/kubeadm/testdata/v1.16/crio.yaml
  pkg/minikube/bootstrapper/kubeadm/testdata/v1.16/default.yaml
  pkg/minikube/bootstrapper/kubeadm/testdata/v1.16/image-repository.yaml
  pkg/minikube/bootstrapper/kubeadm/testdata/v1.16/options.yaml
  pkg/minikube/constants/constants.go
Labels: approved, cncf-cla: yes, size/L

#5164 adding travisbuddy bot for lint error comment
  .travis.yml
Labels: approved, cncf-cla: yes, size/XS

#5171 fix mis-spelling in ssh_runner.go
  pkg/minikube/command/ssh_runner.go
Labels: cncf-cla: yes, needs-ok-to-test, size/XS

#5150 remove retry start from integeration tests
  pkg/minikube/bootstrapper/kubeadm/kubeadm.go
  pkg/minikube/bootstrapper/kubeadm/util.go
  test/integration/a_download_only_test.go
  test/integration/config_test.go
  test/integration/containerd_test.go
  test/integration/docker_test.go
  test/integration/fn_addons.go
  test/integration/fn_cluster_env.go
  test/integration/fn_cluster_logs.go
  test/integration/fn_cluster_ssh.go
  test/integration/fn_profile.go
  test/integration/fn_tunnel.go
  test/integration/functional_test.go
  test/integration/iso_test.go
  test/integration/none_test.go
  test/integration/persistence_test.go
  test/integration/start_stop_delete_test.go
  test/integration/util/minikube_runner.go
  test/integration/version_upgrade_test.go
  test/integration/z_proxy_test.go
Labels: approved, cncf-cla: yes, size/L

#5175 docs: Fix grammar in continuous_integration.md
  site/content/en/docs/Tutorials/continuous_integration.md
Labels: cncf-cla: yes, needs-ok-to-test, size/XS

#5177 Fix broken TestDownloadOnly test, remove broken Test_defaultDiskSize test.
  pkg/drivers/hyperkit/driver_test.go
  test/integration/a_download_only_test.go
Labels: approved, cncf-cla: yes, size/S

#5179 Exit if uid=0, add --force flag to override
  cmd/minikube/cmd/start.go
Labels: approved, cncf-cla: yes, size/M

#5155 Fix downgrade warning is unhelpful and confusing
  cmd/minikube/cmd/start.go
Labels: cncf-cla: yes, needs-ok-to-test, size/S

#5220 Update driver install URL, adjust upgrade text
  cmd/minikube/cmd/start.go
Labels: approved, cncf-cla: yes, size/S

#5229 cleanup: fix mis-spelling in kapi.go
  pkg/kapi/kapi.go
Labels: cncf-cla: yes, needs-ok-to-test, size/XS

#5224 Windows: Use path.Join for VM paths, fall-back to anon image downloads
  pkg/minikube/assets/vm_assets.go
  pkg/minikube/bootstrapper/kubeadm/kubeadm.go
  pkg/minikube/command/command_runner.go
  pkg/minikube/command/exec_runner.go
  pkg/minikube/command/ssh_runner.go
  pkg/minikube/machine/cache_binaries.go
  pkg/minikube/machine/cache_images.go
  test/integration/util/minikube_runner.go
Labels: approved, cncf-cla: yes, size/M
