Repository kubernetes/minikube, pull requests merged in 2019-02, with the labels that each got.

#3619 Upgrade libmachine to version 0.16.1
  Gopkg.lock
  Gopkg.toml
  vendor/github.com/docker/machine/drivers/virtualbox/virtualbox_darwin.go
  vendor/github.com/docker/machine/drivers/virtualbox/virtualbox_freebsd.go
  vendor/github.com/docker/machine/drivers/virtualbox/virtualbox_linux.go
  vendor/github.com/docker/machine/drivers/virtualbox/virtualbox_openbsd.go
  vendor/github.com/docker/machine/drivers/virtualbox/virtualbox_windows.go
  vendor/github.com/docker/machine/drivers/virtualbox/vtx_intel.go
  vendor/github.com/docker/machine/drivers/virtualbox/vtx_other.go
  vendor/github.com/docker/machine/libmachine/drivers/plugin/localbinary/plugin.go
  vendor/github.com/docker/machine/libmachine/libmachine.go
  vendor/github.com/docker/machine/libmachine/provision/boot2docker.go
  vendor/github.com/docker/machine/libmachine/provision/debian.go
  vendor/github.com/docker/machine/libmachine/provision/redhat.go
  vendor/github.com/docker/machine/libmachine/provision/suse.go
  vendor/github.com/docker/machine/libmachine/provision/ubuntu_systemd.go
  vendor/github.com/docker/machine/libmachine/provision/ubuntu_upstart.go
  vendor/github.com/docker/machine/libmachine/provision/utils.go
  vendor/github.com/docker/machine/libmachine/ssh/client.go
  vendor/github.com/intel-go/cpuid/LICENSE
  vendor/github.com/intel-go/cpuid/cpuid.go
  vendor/github.com/intel-go/cpuid/cpuid_amd64.go
  vendor/github.com/intel-go/cpuid/cpuidlow_amd64.s
Labels: approved, cncf-cla: yes, size/XXL

#3616 Update crictl to v1.13.0
  deploy/iso/minikube-iso/package/crictl-bin/crictl-bin.hash
  deploy/iso/minikube-iso/package/crictl-bin/crictl-bin.mk
Labels: approved, cncf-cla: yes, size/XS

#3625 Updated the default kubernetes version
  pkg/minikube/constants/constants.go
Labels: cncf-cla: yes, size/XS

#3580 Use minikube-bin AUR instead of minikube
  hack/jenkins/release_update_installers.sh
Labels: approved, cncf-cla: yes, size/XS

#3630 Use a shallow git clone for buildroot
  Makefile
Labels: approved, cncf-cla: yes, size/XS

#3621 Updated OWNERS file to include link to docs
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3635 Make date regexp more flexible so that we don't have to update it yearly
  hack/boilerplate/boilerplate.py
Labels: approved, cncf-cla: yes, size/XS

#3633 Refactor and centralize container runtime code into a cruntime package
  Gopkg.lock
  Gopkg.toml
  cmd/minikube/cmd/config/util.go
  cmd/minikube/cmd/config/validations.go
  cmd/minikube/cmd/start.go
  cmd/util/util.go
  pkg/drivers/none/none.go
  pkg/minikube/bootstrapper/bootstrapper.go
  pkg/minikube/bootstrapper/kubeadm/kubeadm.go
  pkg/minikube/bootstrapper/kubeadm/kubeadm_test.go
  pkg/minikube/constants/constants.go
  pkg/minikube/cruntime/containerd.go
  pkg/minikube/cruntime/cri.go
  pkg/minikube/cruntime/crio.go
  pkg/minikube/cruntime/cruntime.go
  pkg/minikube/cruntime/cruntime_test.go
  pkg/minikube/cruntime/docker.go
  pkg/minikube/drivers/none/driver.go
  pkg/minikube/machine/cache_images.go
  pkg/minikube/machine/client.go
  test/integration/functional_test.go
  test/integration/start_stop_delete_test.go
  test/integration/util/util.go
  vendor/github.com/google/go-cmp/LICENSE
  vendor/github.com/google/go-cmp/cmp/compare.go
  vendor/github.com/google/go-cmp/cmp/internal/diff/debug_disable.go
  vendor/github.com/google/go-cmp/cmp/internal/diff/debug_enable.go
  vendor/github.com/google/go-cmp/cmp/internal/diff/diff.go
  vendor/github.com/google/go-cmp/cmp/internal/function/func.go
  vendor/github.com/google/go-cmp/cmp/internal/value/format.go
  vendor/github.com/google/go-cmp/cmp/internal/value/sort.go
  vendor/github.com/google/go-cmp/cmp/options.go
  vendor/github.com/google/go-cmp/cmp/path.go
  vendor/github.com/google/go-cmp/cmp/reporter.go
  vendor/github.com/google/go-cmp/cmp/unsafe_panic.go
  vendor/github.com/google/go-cmp/cmp/unsafe_reflect.go
Labels: approved, cncf-cla: yes, size/XXL

#3641 Debugging Issues With Minikube: Add example usage
  docs/debugging.md
Labels: cncf-cla: yes, size/S

#3631 crio: use official kube pause image from gcr
  deploy/iso/minikube-iso/package/crio-bin/crio.conf
Labels: approved, cncf-cla: yes, co/runtime/crio, size/XS

#3602 Document the default storage provider for hostPath
  docs/persistent_volumes.md
Labels: cncf-cla: yes, size/S

#3258 When copying assets from .minikube/files on windows, directories get squashed during transfer. ie /etc/ssl/certs/test.pem becomes ~minikube/etcsslcerts/test.pem. This pull request ensures any window style directories are converted into unix style.
  pkg/minikube/assets/addons.go
Labels: cncf-cla: yes, size/XS

#953 machine: add parallels support
  cmd/minikube/cmd/start.go
  pkg/minikube/constants/constants.go
  pkg/minikube/drivers/parallels/doc.go
  pkg/minikube/drivers/parallels/driver.go
Labels: cncf-cla: yes, size/M

#3617 Enable CNI for alternative runtimes
  cmd/minikube/cmd/config/validations.go
  cmd/minikube/cmd/start.go
  deploy/addons/gvisor/README.md
  docs/alternative_runtimes.md
  docs/contributors/minikube_iso.md
  pkg/minikube/cruntime/containerd.go
  pkg/minikube/cruntime/crio.go
  pkg/minikube/cruntime/cruntime.go
  pkg/minikube/cruntime/docker.go
  test/integration/util/util.go
Labels: approved, cncf-cla: yes, size/M

#3643 Avoid double unlock of image load mutex
  pkg/minikube/machine/cache_images.go
Labels: approved, cncf-cla: yes, size/XS

#3656 Add DeleteCluster to bootstrapper
  cmd/minikube/cmd/delete.go
  pkg/minikube/bootstrapper/bootstrapper.go
  pkg/minikube/bootstrapper/kubeadm/kubeadm.go
  pkg/minikube/console/style.go
Labels: approved, cncf-cla: yes, size/M

#3657 Complete the cruntime implementation for CRI runtimes
  deploy/iso/minikube-iso/package/crio-bin/crio.service
  docs/alternative_runtimes.md
  pkg/minikube/cruntime/containerd.go
  pkg/minikube/cruntime/cri.go
  pkg/minikube/cruntime/crio.go
  pkg/minikube/cruntime/cruntime_test.go
  test/integration/util/util.go
Labels: approved, cncf-cla: yes, size/M

#3663 Fix to not execute clusterBootstrapper.Delete when clusterBootstrappe…
  cmd/minikube/cmd/delete.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3670 Check that a style exists for all runtimes
  pkg/minikube/console/console.go
  pkg/minikube/console/style.go
  pkg/minikube/cruntime/cruntime_test.go
Labels: approved, cncf-cla: yes, size/S

#3667 Seems kubeadm reset doesn't have a --config flag
  pkg/minikube/bootstrapper/kubeadm/kubeadm.go
Labels: approved, cncf-cla: yes, size/XS

#3665 Run poweroff before delete, only call uninstall if driver is None
  cmd/minikube/cmd/delete.go
  cmd/minikube/cmd/stop.go
  pkg/minikube/cluster/cluster.go
  pkg/minikube/console/style.go
Labels: approved, cncf-cla: yes, size/M

#3639 drivers.md: Require Ubuntu >=18.04
  docs/drivers.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3671 Disable kubelet disk eviction by default
  pkg/minikube/bootstrapper/kubeadm/templates.go
Labels: approved, cncf-cla: yes, size/S

#3659 Clearer output when re-using VM's so that users know what they are waiting on
  cmd/minikube/cmd/start.go
  pkg/minikube/cluster/cluster.go
  pkg/minikube/console/style.go
Labels: approved, cncf-cla: yes, size/M

#3661 Consolidate fatal error handling, remove StackDriver integration.
  cmd/minikube/cmd/cache.go
  cmd/minikube/cmd/cache_list.go
  cmd/minikube/cmd/completion.go
  cmd/minikube/cmd/config/addons_list.go
  cmd/minikube/cmd/config/config_view.go
  cmd/minikube/cmd/config/configure.go
  cmd/minikube/cmd/config/disable.go
  cmd/minikube/cmd/config/enable.go
  cmd/minikube/cmd/config/open.go
  cmd/minikube/cmd/config/profile.go
  cmd/minikube/cmd/config/set.go
  cmd/minikube/cmd/config/unset.go
  cmd/minikube/cmd/config/util.go
  cmd/minikube/cmd/dashboard.go
  cmd/minikube/cmd/delete.go
  cmd/minikube/cmd/env.go
  cmd/minikube/cmd/ip.go
  cmd/minikube/cmd/logs.go
  cmd/minikube/cmd/mount.go
  cmd/minikube/cmd/root.go
  cmd/minikube/cmd/service.go
  cmd/minikube/cmd/service_list.go
  cmd/minikube/cmd/ssh.go
  cmd/minikube/cmd/start.go
  cmd/minikube/cmd/status.go
  cmd/minikube/cmd/stop.go
  cmd/minikube/cmd/tunnel.go
  cmd/minikube/cmd/update-check.go
  cmd/minikube/cmd/update-context.go
  cmd/util/util.go
  cmd/util/util_test.go
  pkg/drivers/none/none.go
  pkg/minikube/cluster/cluster.go
  pkg/minikube/console/style.go
  pkg/minikube/exit/exit.go
  pkg/minikube/machine/client.go
Labels: approved, cncf-cla: yes, size/XL

#3669 Upgrade opencontainers/runc to 0a012df
  deploy/iso/minikube-iso/package/runc-master/runc-master.hash
  deploy/iso/minikube-iso/package/runc-master/runc-master.mk
Labels: approved, cncf-cla: yes, size/XS

#3666 Upgrade Docker, from 18.06.1-ce to 18.06.2-ce
  deploy/iso/minikube-iso/package/docker-bin/docker-bin.hash
  deploy/iso/minikube-iso/package/docker-bin/docker-bin.mk
Labels: approved, cncf-cla: yes, size/XS

#3673 Include pod output in 'logs' command & display detected problems during start
  cmd/minikube/cmd/logs.go
  cmd/minikube/cmd/start.go
  pkg/minikube/bootstrapper/bootstrapper.go
  pkg/minikube/bootstrapper/kubeadm/kubeadm.go
  pkg/minikube/console/style.go
  pkg/minikube/cruntime/containerd.go
  pkg/minikube/cruntime/cri.go
  pkg/minikube/cruntime/crio.go
  pkg/minikube/cruntime/cruntime.go
  pkg/minikube/cruntime/docker.go
  pkg/minikube/exit/exit.go
  pkg/minikube/logs/logs.go
  pkg/minikube/logs/logs_test.go
  pkg/util/kubernetes.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#3676 Add docs to use new vmware unified driver
  docs/drivers.md
Labels: cncf-cla: yes, size/XS

#3682 none tests: Cleanup /var/lib/minikube
  hack/jenkins/linux_integration_tests_none.sh
Labels: approved, cncf-cla: yes, size/XS

#3683 Fix TestStartStop so that none tests are executed
  test/integration/start_stop_delete_test.go
Labels: approved, cncf-cla: yes, size/XS

#3684 Adding docs for OpenID Connect Authentication
  docs/README.md
  docs/openid_connect_auth.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#3660 Make hyperkit driver more robust: detect crashing, misinstallation, other process names
  pkg/drivers/hyperkit/driver.go
  pkg/drivers/hyperkit/iso.go
  pkg/drivers/hyperkit/network.go
  pkg/drivers/hyperkit/network_test.go
Labels: approved, cncf-cla: yes, size/L

#3501 addons: Fixes multiple files behavior in files rootfs
  pkg/minikube/assets/addons.go
  pkg/minikube/assets/addons_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#3687 Minor output changes to reduce string size or improve clarity
  cmd/minikube/cmd/delete.go
  cmd/minikube/cmd/start.go
  pkg/minikube/bootstrapper/kubeadm/kubeadm.go
  pkg/minikube/cluster/cluster.go
Labels: approved, cncf-cla: yes, size/S

#3686 Implement 7-bit ASCII prefixes for when MINIKUBE_IN_COLOR=false
  pkg/minikube/console/console_test.go
  pkg/minikube/console/style.go
Labels: approved, cncf-cla: yes, size/L

#3679 cruntime: Fix (List|Stop|Kill)Containers behavior when no containers match
  Gopkg.lock
  pkg/drivers/none/none.go
  pkg/minikube/cruntime/cri.go
  pkg/minikube/cruntime/cruntime_test.go
  pkg/minikube/cruntime/docker.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/equate.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/ignore.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/sort.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/sort_go17.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/sort_go18.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/struct_filter.go
Labels: approved, cncf-cla: yes, size/XL

#3675 Upgrade the list of images for 1.12 and 1.13
  pkg/minikube/constants/constants.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#3678 Add implementation of the deprecated rkt runtime
  pkg/minikube/console/style.go
  pkg/minikube/cruntime/cruntime.go
  pkg/minikube/cruntime/cruntime_test.go
  pkg/minikube/cruntime/rkt.go
Labels: approved, cncf-cla: yes, size/L

#3688 Implement CRI method ContainerLogCmd for rkt
  pkg/minikube/cruntime/rkt.go
Labels: approved, cncf-cla: yes, size/XS

#3680 none UX: Reword warnings and other strings for accuracy
  cmd/minikube/cmd/dashboard.go
  cmd/minikube/cmd/delete.go
  cmd/minikube/cmd/root.go
  cmd/minikube/cmd/start.go
  cmd/util/util.go
  cmd/util/util_test.go
  pkg/minikube/console/style.go
Labels: approved, cncf-cla: yes, size/L

#3690 Added and unified driver usage instructions.
  docs/drivers.md
Labels: cncf-cla: yes, size/S

#3696 Make images subdirectory, add start image
  README.md
  images/logo/LICENSE
  images/logo/logo.eps
  images/logo/logo.png
  images/logo/logo.svg
  images/logo/logo_white.eps
  images/logo/logo_white.png
  images/logo/logo_white.svg
  images/logo/logo_white_with_name.eps
  images/logo/logo_white_with_name.png
  images/logo/logo_white_with_name.svg
  images/logo/logo_with_name.eps
  images/logo/logo_with_name.png
  images/logo/logo_with_name.svg
  images/logo/minikube-logo.png
  images/logo/minikube_logo_name.jpg
  images/start.jpg
Labels: approved, cncf-cla: yes, size/XS

#3699 Use the new ISO version, for features and security
  Makefile
Labels: approved, cncf-cla: yes, size/XS

#3698 Improve reporting when docker host/service is down
  cmd/minikube/cmd/env.go
Labels: approved, cncf-cla: yes, size/S

#3702 Only call trySSHPowerOff if we are using hyperv
  pkg/minikube/cluster/cluster.go
Labels: approved, cncf-cla: yes, size/S

#3703 Make non-zero ssh error codes less dramatic
  cmd/minikube/cmd/ssh.go
Labels: approved, cncf-cla: yes, size/XS

#3705 Bump VERSION_BUILD to 0.34.1, update ISO_VERSION default to major.minor.0
  Makefile
Labels: approved, cncf-cla: yes, size/XS

#3707 v0.34.1 release notes
  CHANGELOG.md
Labels: approved, cncf-cla: yes, size/S

#3716 readme: typo
  README.md
Labels: cncf-cla: yes, size/XS

#3715 Fix code block highlight in README
  README.md
Labels: cncf-cla: yes, size/XS

#3717 Formatting and minor content fixes
  docs/drivers.md
Labels: cncf-cla: yes, size/M

#3712 Add Netfilter `xt_socket` module to complete support for Transparent Proxying (TPROXY)
  deploy/iso/minikube-iso/board/coreos/minikube/linux_defconfig
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3719 chown command should be against user $HOME, not roots home directory.
  cmd/minikube/cmd/start.go
Labels: approved, cncf-cla: yes, size/XS

#3653 Prow results script
  hack/prow/run_tests.py
Labels: cncf-cla: yes, size/L

#3745 Improve building of deb package (versioning and permissions)
  Makefile
  hack/jenkins/release_build_and_upload.sh
  hack/jenkins/release_github_page.sh
Labels: approved, cncf-cla: yes, size/XS

#3742 Add make target for building a rpm file
  Makefile
  hack/jenkins/release_build_and_upload.sh
  hack/jenkins/release_github_page.sh
  installers/linux/rpm/minikube_rpm_template/minikube.spec
Labels: approved, cncf-cla: yes, size/M

#3734 Add flag for disabling the VirtualBox VTX check
  cmd/minikube/cmd/start.go
  pkg/minikube/config/types.go
  pkg/minikube/drivers/virtualbox/driver.go
Labels: approved, cncf-cla: yes, size/XS

#3711 update libvirtd
  docs/drivers.md
Labels: approved, cncf-cla: yes, lgtm, size/S
