Repository kubernetes/minikube, pull requests merged in 2019-10, with the labels that each got.

#5462 Proposal: MEP, the minikube enhancement proposal workflow
  enhancements/README.md
  enhancements/proposed/20190925-minikube-enhancement-process.md
  enhancements/template.md
Labels: approved, cncf-cla: yes, size/L, triage/discuss

#5517 Add TCP/UDP ingress tutorial
  site/content/en/docs/Tutorials/nginx_tcp_udp_ingress.md
Labels: cncf-cla: yes, needs-ok-to-test, size/L

#5521 Productionize MEP: add to PR template and documentation
  .github/pull_request_template.md
  enhancements/implemented/20190925-minikube-enhancement-process.md
  site/content/en/docs/Contributing/guide.en.md
Labels: approved, cncf-cla: yes, size/S

#5519 Fix pods not being scheduled when ingress deployment is patched
  deploy/addons/ingress/ingress-dp.yaml.tmpl
Labels: cncf-cla: yes, needs-ok-to-test, size/XS

#5455 Improve the grammar and annotations
  deploy/addons/helm-tiller/README.md
  site/content/en/docs/Reference/Commands/dashboard.md
  site/content/en/docs/Reference/Commands/delete.md
  site/content/en/docs/Reference/Commands/kubectl.md
  site/content/en/docs/Reference/Commands/service.md
  site/content/en/docs/Reference/Commands/start.md
  site/content/en/docs/Reference/Commands/status.md
  site/content/en/docs/Reference/Commands/stop.md
Labels: cncf-cla: yes, ok-to-test, size/M

#5525 Minor fixes to nginx tcp udp article
  site/content/en/docs/Tutorials/nginx_tcp_udp_ingress.md
Labels: cncf-cla: yes, needs-ok-to-test, size/M

#5523 fix some spelling mistakes in 20190925-minikube-enhancement-process.md file
  enhancements/implemented/20190925-minikube-enhancement-process.md
Labels: cncf-cla: yes, needs-ok-to-test, size/XS

#5447 Fixes image repository flags when using CRI-O and containerd runtime
  cmd/minikube/cmd/start.go
  pkg/minikube/bootstrapper/bootstrapper.go
  pkg/minikube/bootstrapper/images/images.go
  pkg/minikube/bootstrapper/kubeadm/kubeadm.go
  pkg/minikube/cruntime/containerd.go
  pkg/minikube/cruntime/cri.go
  pkg/minikube/cruntime/crio.go
  pkg/minikube/cruntime/cruntime.go
  test/integration/a_download_only_test.go
Labels: cncf-cla: yes, ok-to-test, size/XL

#5314 Update NO_PROXY example for Windows
  site/content/en/docs/Reference/Networking/proxy.md
Labels: cncf-cla: yes, needs-ok-to-test, size/XS

#5507 Add ingress-dns addon
  cmd/minikube/cmd/config/config.go
  deploy/addons/ingress-dns/README.md
  deploy/addons/ingress-dns/example/example.yaml
  deploy/addons/ingress-dns/ingress-dns-configmap.yaml
  deploy/addons/ingress-dns/ingress-dns-dns-server-pod.yaml
  deploy/addons/ingress-dns/ingress-dns-nginx-pod.yaml.tmpl
  deploy/addons/ingress-dns/ingress-dns-svc.yaml
  pkg/minikube/assets/addons.go
  site/content/en/docs/Tasks/addons.md
Labels: cncf-cla: yes, needs-ok-to-test, size/XL

#5536 fix linting for travis.yml
  .travis.yml
Labels: cncf-cla: yes, needs-ok-to-test, size/S

#5556 Adding blueelvis as a minikube reviewer
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5562 Fix Jenkins Cross script to copy testdata properly
  hack/jenkins/minikube_cross_build_and_upload.sh
Labels: approved, cncf-cla: yes, size/XS

#5559 clean up inaccessible virtualbox
  hack/jenkins/common.sh
Labels: approved, cncf-cla: yes, size/XS

#5492 Change systemd unit files perm to 644
  pkg/minikube/bootstrapper/kubeadm/kubeadm.go
Labels: cncf-cla: yes, needs-ok-to-test, size/XS

#5575 Add css to accomodate proper sizing for image
  site/content/en/_index.html
Labels: cncf-cla: yes, needs-ok-to-test, size/S

#5533 Replace BR2_EXTERNAL_MINIKUBE_PATH with PKGDIR.
  deploy/iso/minikube-iso/package/automount/automount.mk
  deploy/iso/minikube-iso/package/containerd-bin/containerd-bin.mk
  deploy/iso/minikube-iso/package/crio-bin/crio-bin.mk
  deploy/iso/minikube-iso/package/docker-bin/docker-bin.mk
  deploy/iso/minikube-iso/package/hyperv-daemons/hyperv-daemons.mk
  deploy/iso/minikube-iso/package/vbox-guest/vbox-guest.mk
Labels: cncf-cla: yes, needs-ok-to-test, size/M

#5508 Adjusted Terminal Style Detection
  pkg/minikube/out/out.go
Labels: cncf-cla: yes, needs-ok-to-test, size/XS

#5566 Use configured DNS domain in bootstrapper kubeadm templates
  pkg/minikube/bootstrapper/kubeadm/kubeadm.go
  pkg/minikube/bootstrapper/kubeadm/kubeadm_test.go
  pkg/minikube/bootstrapper/kubeadm/templates.go
  pkg/minikube/bootstrapper/kubeadm/testdata/v1.12/dns.yaml
  pkg/minikube/bootstrapper/kubeadm/testdata/v1.13/dns.yaml
  pkg/minikube/bootstrapper/kubeadm/testdata/v1.14/dns.yaml
  pkg/minikube/bootstrapper/kubeadm/testdata/v1.15/dns.yaml
  pkg/minikube/bootstrapper/kubeadm/testdata/v1.16/dns.yaml
  site/content/en/docs/Reference/Networking/dns.md
Labels: cncf-cla: yes, do-not-merge/invalid-commit-message, needs-ok-to-test, size/L

#5574 Add libmachine debug logs back
  cmd/minikube/main.go
Labels: approved, cncf-cla: yes, size/XS

#5583 Revert "clean up inaccessible virtualbox"
  hack/jenkins/common.sh
Labels: cncf-cla: yes, size/XS

#5522 Add documentation for adding translations
  site/content/en/docs/Contributing/gvisor.md
  site/content/en/docs/Contributing/translations.md
Labels: approved, cncf-cla: yes, size/S

#5543 Add addons flag to 'minikube start' in order to enable specified addons
  cmd/minikube/cmd/start.go
  site/content/en/docs/Reference/Commands/addons.md
  site/content/en/docs/Reference/Commands/start.md
  site/content/en/docs/Tasks/addons.md
  test/integration/addons_test.go
Labels: cncf-cla: yes, kind/feature, needs-ok-to-test, size/M

#5584 jenkins: Resilient VirtualBox VM and test directory cleanup
  hack/jenkins/common.sh
Labels: approved, cncf-cla: yes, size/M

#5589 Disable interfacer lint check
  Makefile
Labels: approved, cncf-cla: yes, size/XS

#5591 Remove unused enableUpdateNotification variable
  cmd/minikube/cmd/start.go
  cmd/minikube/cmd/update-check.go
  cmd/minikube/cmd/version.go
Labels: approved, cncf-cla: yes, size/S

#4999 Warn when a user tries to set a profile name that is unlikely to be valid
  cmd/minikube/cmd/config/profile.go
  cmd/minikube/cmd/config/util.go
  cmd/minikube/cmd/config/util_test.go
Labels: cncf-cla: yes, ok-to-test, size/M

#5593 Update default Kubernetes version to 1.16.1
  pkg/minikube/bootstrapper/kubeadm/kubeadm_test.go
  pkg/minikube/constants/constants.go
  pkg/minikube/constants/constants_darwin.go
Labels: approved, cncf-cla: yes, size/S

#5602 Update Makefile for version 1.4.1
  Makefile
Labels: approved, cncf-cla: yes, size/XS

#5620 gsutil: Remove trailing slashes, rsync instead of cp
  hack/jenkins/minikube_cross_build_and_upload.sh
Labels: approved, cncf-cla: yes, size/XS

#5609 Upgrade Buildroot to 2019.02 and VirtualBox to 5.2
  Makefile
  deploy/iso/minikube-iso/board/coreos/minikube/rootfs-overlay/var/run/crio.sock
  deploy/iso/minikube-iso/board/coreos/minikube/rootfs-overlay/var/run/crio/.empty
  deploy/iso/minikube-iso/configs/minikube_defconfig
  deploy/iso/minikube-iso/package/hyperv-daemons/hyperv-daemons.mk
  deploy/iso/minikube-iso/package/vbox-guest/vbox-guest.hash
  deploy/iso/minikube-iso/package/vbox-guest/vbox-guest.mk
Labels: approved, cncf-cla: yes, size/S

#5608 Disable go modules for containerd, for newer go
  deploy/iso/minikube-iso/package/containerd-bin/containerd-bin.mk
Labels: approved, cncf-cla: yes, size/XS

#5622 jenkins: rsync needs -R, add version output
  hack/jenkins/common.sh
  hack/jenkins/minikube_cross_build_and_upload.sh
Labels: approved, cncf-cla: yes, size/XS

#5614 Performance and security enhancement for ingress-dns addon
  deploy/addons/ingress-dns/ingress-dns-configmap.yaml
  deploy/addons/ingress-dns/ingress-dns-nginx-pod.yaml.tmpl
  deploy/addons/ingress-dns/ingress-dns-pod.yaml
  deploy/addons/ingress-dns/ingress-dns-svc.yaml
  pkg/minikube/assets/addons.go
Labels: cncf-cla: yes, needs-ok-to-test, size/L

#5586 Replace registry-creds addon ReplicationController with Deployment
  deploy/addons/registry-creds/registry-creds-rc.yaml.tmpl
Labels: cncf-cla: yes, needs-ok-to-test, size/S

#4780 Added option to delete all profiles
  cmd/minikube/cmd/delete.go
  cmd/minikube/cmd/delete_test.go
  hack/jenkins/common.sh
  pkg/minikube/cluster/machine.go
  pkg/minikube/cluster/machine_test.go
  pkg/minikube/cluster/testdata/list-machines/.minikube/machines/p1/config.json
  pkg/minikube/cluster/testdata/list-machines/.minikube/machines/p2/config.json
  pkg/minikube/cluster/testdata/list-machines/.minikube/machines/p3_empty_config/config.json
  pkg/minikube/cluster/testdata/list-machines/.minikube/machines/p4_invalid_machine_config/config.json
  pkg/minikube/cluster/testdata/list-machines/.minikube/machines/p5_partial_config/config.json
  pkg/minikube/config/profile.go
  pkg/minikube/config/profile_test.go
  pkg/minikube/config/testdata/delete-all/.minikube/machines/p1/config.json
  pkg/minikube/config/testdata/delete-all/.minikube/machines/p2_empty_profile_config/config.json
  pkg/minikube/config/testdata/delete-all/.minikube/machines/p3_invalid_profile_config/config.json
  pkg/minikube/config/testdata/delete-all/.minikube/machines/p4_partial_profile_config/config.json
  pkg/minikube/config/testdata/delete-all/.minikube/machines/p6_empty_machine_config/config.json
  pkg/minikube/config/testdata/delete-all/.minikube/machines/p7_invalid_machine_config/config.json
  pkg/minikube/config/testdata/delete-all/.minikube/machines/p8_partial_machine_config/config.json
  pkg/minikube/config/testdata/delete-all/.minikube/profiles/p1/config.json
  pkg/minikube/config/testdata/delete-all/.minikube/profiles/p2_empty_profile_config/config.json
  pkg/minikube/config/testdata/delete-all/.minikube/profiles/p3_invalid_profile_config/config.json
  pkg/minikube/config/testdata/delete-all/.minikube/profiles/p4_partial_profile_config/config.json
  pkg/minikube/config/testdata/delete-all/.minikube/profiles/p5_missing_machine_config/config.json
  pkg/minikube/config/testdata/delete-all/.minikube/profiles/p6_empty_machine_config/config.json
  pkg/minikube/config/testdata/delete-all/.minikube/profiles/p7_invalid_machine_config/config.json
  pkg/minikube/config/testdata/delete-all/.minikube/profiles/p8_partial_machine_config/config.json
  pkg/minikube/config/testdata/delete-single/.minikube/machines/p1/config.json
  pkg/minikube/config/testdata/delete-single/.minikube/machines/p2_empty_profile_config/config.json
  pkg/minikube/config/testdata/delete-single/.minikube/machines/p3_invalid_profile_config/config.json
  pkg/minikube/config/testdata/delete-single/.minikube/machines/p4_partial_profile_config/config.json
  pkg/minikube/config/testdata/delete-single/.minikube/machines/p6_empty_machine_config/config.json
  pkg/minikube/config/testdata/delete-single/.minikube/machines/p7_invalid_machine_config/config.json
  pkg/minikube/config/testdata/delete-single/.minikube/machines/p8_partial_machine_config/config.json
  pkg/minikube/config/testdata/delete-single/.minikube/profiles/p1/config.json
  pkg/minikube/config/testdata/delete-single/.minikube/profiles/p2_empty_profile_config/config.json
  pkg/minikube/config/testdata/delete-single/.minikube/profiles/p3_invalid_profile_config/config.json
  pkg/minikube/config/testdata/delete-single/.minikube/profiles/p4_partial_profile_config/config.json
  pkg/minikube/config/testdata/delete-single/.minikube/profiles/p5_missing_machine_config/config.json
  pkg/minikube/config/testdata/delete-single/.minikube/profiles/p6_empty_machine_config/config.json
  pkg/minikube/config/testdata/delete-single/.minikube/profiles/p7_invalid_machine_config/config.json
  pkg/minikube/config/testdata/delete-single/.minikube/profiles/p8_partial_machine_config/config.json
  pkg/minikube/config/testdata/profile/.minikube/profiles/p1/config.json
  pkg/minikube/config/testdata/profile/.minikube/profiles/p2/config.json
  pkg/minikube/config/testdata/profile/.minikube/profiles/p3_empty/config.json
  pkg/minikube/config/testdata/profile/.minikube/profiles/p4_invalid_file/config.json
  pkg/minikube/config/testdata/profile/.minikube/profiles/p5_partial_config/config.json
  test/integration/start_stop_delete_test.go
  translations/fr.json
  translations/zh-CN.json
Labels: cncf-cla: yes, needs-ok-to-test, size/XXL

#5607 Add docker-init binary to package, bundled tini
  deploy/iso/minikube-iso/package/docker-bin/docker-bin.mk
Labels: approved, cncf-cla: yes, size/XS

#5641 Download gluster from OpenPKG while RH is having issues
  deploy/iso/minikube-iso/package/gluster/gluster.mk
Labels: approved, cncf-cla: yes, size/XS

#5649 Move delete --all test so that it is run in serial
  test/integration/Untitled-1
  test/integration/a_serial_tests.go
  test/integration/start_stop_delete_test.go
Labels: approved, cncf-cla: yes, size/S

#5647 common.sh tune-up: Add load warning, fix profile deletion, fix lint errors and noise
  hack/jenkins/common.sh
Labels: approved, cncf-cla: yes, size/M

#5651 Allow more time for gvisor to complete on slower machines
  test/integration/gvisor_addon_test.go
Labels: approved, cncf-cla: yes, size/XS

#5626 fix "minikube update-context" command fail
  cmd/minikube/cmd/update-context.go
Labels: cncf-cla: yes, kind/bug, needs-ok-to-test, size/XS

#5623 Delegate release notes generation to external tool
  hack/.gitignore
  hack/release_notes.sh
  hack/release_notes/listpullreqs.go
Labels: cncf-cla: yes, ok-to-test, size/L

#5612 Add docs for using registry on macOS
  site/content/en/docs/Tasks/Registry/insecure.md
Labels: cncf-cla: yes, ok-to-test, size/S

#5565 Allow addon enabling and disabling when minikube is not running
  cmd/minikube/cmd/config/disable_test.go
  cmd/minikube/cmd/config/enable_test.go
  cmd/minikube/cmd/config/open.go
  cmd/minikube/cmd/config/util.go
  cmd/minikube/cmd/config/util_test.go
  cmd/minikube/cmd/dashboard.go
  cmd/minikube/cmd/service.go
  go.mod
  pkg/minikube/cluster/cluster.go
Labels: cncf-cla: yes, needs-ok-to-test, size/L

#5555 Fix addons list output format option
  cmd/minikube/cmd/config/addons_list.go
  test/integration/functional_test.go
Labels: cncf-cla: yes, ok-to-test, size/M

#5201 optimizing Chinese translation
  translations/zh-CN.json
Labels: cncf-cla: yes, ok-to-test, size/L

#5425 improve translations test coverage
  pkg/minikube/translate/translate_test.go
Labels: cncf-cla: yes, ok-to-test, size/M

#5512 Improve machine test coverage
  pkg/minikube/machine/cache_binaries_test.go
Labels: cncf-cla: yes, needs-ok-to-test, size/L

#5639 Speed up RNG initialization on new systemd
  deploy/iso/minikube-iso/board/coreos/minikube/isolinux.cfg
  pkg/minikube/drivers/hyperkit/driver.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5471 remove the redundant code in util.go
  pkg/util/utils.go
Labels: cncf-cla: yes, size/S

#5554 Add json output for profile list
  cmd/minikube/cmd/config/profile_list.go
  test/integration/functional_test.go
Labels: cncf-cla: yes, ok-to-test, size/L

#5563 Make error message more human readable
  pkg/minikube/service/service.go
  pkg/minikube/service/service_test.go
  test.sh
Labels: cncf-cla: yes, ok-to-test, size/M

#5596 Warn if incompatible kubectl version is in use
  cmd/minikube/cmd/start.go
Labels: cncf-cla: yes, do-not-merge/invalid-commit-message, needs-ok-to-test, size/M

#5592 Add networking validation to validateNetwork
  cmd/minikube/cmd/start.go
  pkg/minikube/bootstrapper/images/images.go
Labels: approved, cncf-cla: yes, size/M

#5653 Add test to ensure addon state is mutable for stopped clusters
  test/integration/addons_test.go
Labels: approved, cncf-cla: yes, size/S

#5654 Ensure that delete succeeds even if cluster is unavailable
  cmd/minikube/cmd/delete.go
  pkg/minikube/cluster/cluster.go
  test/integration/a_serial_tests.go
Labels: approved, cncf-cla: yes, size/S

#5676 upgrade go version 1.12.9 -> 1.12.12
  .travis.yml
  Makefile
Labels: cncf-cla: yes, kind/bug, ok-to-test, priority/important-soon, size/XS

#5671 Add missing dash before the image arch
  pkg/minikube/assets/addons.go
Labels: approved, cncf-cla: yes, size/XS

#5670 Reduce code smell reported by SonarCloud
  cmd/minikube/cmd/config/prompt.go
  pkg/drivers/kvm/network_test.go
  pkg/minikube/config/config_test.go
Labels: approved, cncf-cla: yes, ok-to-test, size/XS

#5665 Build minikube for arm64 (aarch64) as well
  Makefile
  installers/linux/deb/minikube_deb_template/DEBIAN/control
  installers/linux/rpm/minikube_rpm_template/minikube.spec
Labels: approved, cncf-cla: yes, size/M

#5664 Upgrade toolbox versions, fedora and systemd
  deploy/iso/minikube-iso/board/coreos/minikube/rootfs-overlay/usr/bin/toolbox
Labels: approved, cncf-cla: yes, size/XS

#5663 Pick some lint from the recent master commits
  Makefile
  cmd/minikube/cmd/delete.go
  cmd/minikube/cmd/start.go
  pkg/minikube/bootstrapper/images/images.go
  pkg/minikube/cluster/cluster.go
  pkg/minikube/cluster/machine.go
  pkg/minikube/config/profile.go
Labels: approved, cncf-cla: yes, size/M

#5662 fix test case TestCacheBinary/ok_kubeadm to download linux kubeadm binary
  pkg/minikube/machine/cache_binaries_test.go
Labels: cncf-cla: yes, kind/bug, kind/failing-test, needs-ok-to-test, size/XS

#5659 [performance] add Makefile rule and code skeleton for mkcmp
  Makefile
  cmd/performance/cmd/mkcmp.go
  cmd/performance/main.go
Labels: cncf-cla: yes, size/M

#5656 Rewrite cmd/delete_test to run without side effects
  cmd/minikube/cmd/delete_test.go
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, size/XL

#5640 add ability to override autoupdating drivers
  cmd/minikube/cmd/start.go
  pkg/drivers/drivers.go
  test/integration/driver_install_or_update_test.go
Labels: approved, cncf-cla: yes, size/M

#5624 Add validation checking for minikube profile
  cmd/minikube/cmd/config/profile.go
  pkg/minikube/config/profile.go
  pkg/minikube/config/profile_test.go
Labels: cncf-cla: yes, do-not-merge/invalid-commit-message, ok-to-test, size/M

#5601 Add JSON output for addons list
  cmd/minikube/cmd/config/addons_list.go
  test/integration/functional_test.go
Labels: cncf-cla: yes, ok-to-test, size/M

#5550 Address some go9p issues adressed by SonarCloud
  third_party/go9p/ufs_darwin.go
  third_party/go9p/unpack.go
Labels: approved, cncf-cla: yes, size/XS

#5548 Added flags to purge configuration with minikube delete
  cmd/minikube/cmd/delete.go
  pkg/minikube/cluster/cluster.go
  pkg/minikube/drivers/hyperv/driver.go
  pkg/minikube/tunnel/route_windows.go
  site/content/en/docs/Reference/Commands/delete.md
Labels: cncf-cla: yes, ok-to-test, size/M

#5655 Improve kubectl skew check logic
  cmd/minikube/cmd/start.go
Labels: approved, cncf-cla: yes, size/M

#5658 Consolidate driver handling code in pkg/minikube/driver
  cmd/minikube/cmd/config/util_test.go
  cmd/minikube/cmd/config/validations.go
  cmd/minikube/cmd/delete.go
  cmd/minikube/cmd/env.go
  cmd/minikube/cmd/mount.go
  cmd/minikube/cmd/ssh.go
  cmd/minikube/cmd/start.go
  cmd/minikube/main.go
  go.sum
  pkg/drivers/common.go
  pkg/drivers/common_test.go
  pkg/drivers/drivers.go
  pkg/drivers/none/none.go
  pkg/minikube/cluster/cluster.go
  pkg/minikube/cluster/cluster_linux.go
  pkg/minikube/cluster/cluster_test.go
  pkg/minikube/cluster/machine.go
  pkg/minikube/config/config_test.go
  pkg/minikube/constants/constants.go
  pkg/minikube/constants/constants_darwin.go
  pkg/minikube/constants/constants_gendocs.go
  pkg/minikube/constants/constants_linux.go
  pkg/minikube/constants/constants_windows.go
  pkg/minikube/driver/driver.go
  pkg/minikube/driver/driver_darwin.go
  pkg/minikube/driver/driver_linux.go
  pkg/minikube/driver/driver_windows.go
  pkg/minikube/driver/install.go
  pkg/minikube/machine/client.go
  pkg/minikube/machine/client_test.go
  pkg/minikube/registry/drvs/hyperkit/doc.go
  pkg/minikube/registry/drvs/hyperkit/driver.go
  pkg/minikube/registry/drvs/hyperv/doc.go
  pkg/minikube/registry/drvs/hyperv/driver.go
  pkg/minikube/registry/drvs/init.go
  pkg/minikube/registry/drvs/kvm2/doc.go
  pkg/minikube/registry/drvs/kvm2/driver.go
  pkg/minikube/registry/drvs/none/doc.go
  pkg/minikube/registry/drvs/none/driver.go
  pkg/minikube/registry/drvs/parallels/doc.go
  pkg/minikube/registry/drvs/parallels/driver.go
  pkg/minikube/registry/drvs/virtualbox/doc.go
  pkg/minikube/registry/drvs/virtualbox/driver.go
  pkg/minikube/registry/drvs/vmware/doc.go
  pkg/minikube/registry/drvs/vmware/driver.go
  pkg/minikube/registry/drvs/vmwarefusion/doc.go
  pkg/minikube/registry/drvs/vmwarefusion/driver.go
  pkg/minikube/registry/registry_test.go
  pkg/minikube/tests/api_mock.go
  pkg/minikube/tests/driver_mock.go
  pkg/minikube/tunnel/tunnel.go
  pkg/provision/buildroot.go
  test/integration/driver_install_or_update_test.go
Labels: approved, cncf-cla: yes, size/XXL

#5628 Bump version to 1.5.0-beta.0
  Makefile
Labels: approved, cncf-cla: yes, size/XS

#5630 Update CHANGELOG for 1.5.0-beta.0
  CHANGELOG.md
Labels: approved, cncf-cla: yes, size/M

#5680 Add note for releasing betas in documentation
  site/content/en/docs/Contributing/releasing.en.md
Labels: approved, cncf-cla: yes, size/XS

#5611 Add json output for status
  cmd/minikube/cmd/status.go
  test/integration/functional_test.go
Labels: cncf-cla: yes, ok-to-test, size/L

#5695 Make minikube the default target again
  Makefile
Labels: approved, cncf-cla: yes, size/XS

#5705 Fix comment for go lint
  pkg/minikube/config/profile.go
Labels: cncf-cla: yes, needs-ok-to-test, size/XS

#5646 Added docs for delete --all command
  site/content/en/docs/Examples/_index.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#5520 Remove duplicate setting field in config
  cmd/minikube/cmd/config/config.go
Labels: cncf-cla: yes, do-not-merge/work-in-progress, needs-ok-to-test, size/XS

#5544 Get rid of python scripts in build process
  .travis.yml
  hack/boilerplate/boilerplate.go
  hack/boilerplate/boilerplate.py
  hack/boilerplate/fix.sh
  test.sh
Labels: cncf-cla: yes, ok-to-test, size/L

#5710 pin go version for boilerplate
  .travis.yml
Labels: approved, cncf-cla: yes, size/XS

#5711 Previous boilerplate fix break make test
  test.sh
Labels: cncf-cla: yes, needs-ok-to-test, size/XS

#5712 Upgrade to golangci-lint v1.21, add dogsled check
  Makefile
Labels: approved, cncf-cla: yes, size/XS

#5721 Fix lint error: File is not `goimports` -ed
  pkg/minikube/registry/drvs/hyperkit/driver.go
  pkg/minikube/registry/drvs/vmwarefusion/driver.go
Labels: cncf-cla: yes, kind/bug, kind/failing-test, needs-ok-to-test, size/XS

#5725 CI: Use print preserve whitespace between interface names
  hack/jenkins/common.sh
Labels: approved, cncf-cla: yes, size/XS

#5700 Default to best-available local hypervisor rather than VirtualBox
  cmd/minikube/cmd/start.go
  hack/jenkins/common.sh
  hack/jenkins/linux_integration_tests_kvm.sh
  hack/jenkins/linux_integration_tests_none.sh
  hack/jenkins/linux_integration_tests_virtualbox.sh
  hack/jenkins/osx_integration_tests_hyperkit.sh
  hack/jenkins/osx_integration_tests_virtualbox.sh
  hack/jenkins/windows_integration_test_hyperv.ps1
  hack/jenkins/windows_integration_test_virtualbox.ps1
  pkg/minikube/cluster/cluster.go
  pkg/minikube/cluster/cluster_test.go
  pkg/minikube/config/config_test.go
  pkg/minikube/driver/driver.go
  pkg/minikube/driver/driver_test.go
  pkg/minikube/driver/install_test.go
  pkg/minikube/machine/client.go
  pkg/minikube/out/style.go
  pkg/minikube/out/style_enum.go
  pkg/minikube/registry/drvs/hyperkit/hyperkit.go
  pkg/minikube/registry/drvs/hyperv/hyperv.go
  pkg/minikube/registry/drvs/kvm2/kvm2.go
  pkg/minikube/registry/drvs/none/none.go
  pkg/minikube/registry/drvs/parallels/parallels.go
  pkg/minikube/registry/drvs/virtualbox/doc.go
  pkg/minikube/registry/drvs/virtualbox/virtualbox.go
  pkg/minikube/registry/drvs/vmware/vmware.go
  pkg/minikube/registry/drvs/vmwarefusion/vmwarefusion.go
  pkg/minikube/registry/global.go
  pkg/minikube/registry/global_test.go
  pkg/minikube/registry/registry.go
  pkg/minikube/registry/registry_test.go
  test/integration/Untitled-1
  test/integration/a_serial_test.go
  test/integration/main.go
Labels: approved, cncf-cla: yes, size/XXL

#5731 Update default Kubernetes version to v1.16.2
  pkg/minikube/bootstrapper/kubeadm/kubeadm_test.go
  pkg/minikube/constants/constants.go
Labels: approved, cncf-cla: yes, size/S

#5732 Hide innocuous viper ConfigFileNotFoundError
  cmd/minikube/cmd/root.go
Labels: approved, cncf-cla: yes, size/XS

#5736 Fix typo in integration test readme
  test/integration/README.md
Labels: approved, cncf-cla: yes, size/XS

#5735 gvisor: Use chroot instead of LD_LIBRARY_PATH
  Makefile
  deploy/addons/gvisor/gvisor-pod.yaml.tmpl
  deploy/gvisor/Dockerfile
  hack/jenkins/common.sh
  pkg/gvisor/enable.go
  test/integration/gvisor_addon_test.go
Labels: approved, cncf-cla: yes, size/M

#5741 Set gvisor-addon version, make cache add non-fatal
  test/integration/gvisor_addon_test.go
Labels: approved, cncf-cla: yes, ok-to-test, size/XS

#5737 Update Makefile and CHANGELOG to v1.5.0
  CHANGELOG.md
  Makefile
Labels: approved, cncf-cla: yes, ok-to-test, size/S

#5743 Update documentation for v1.5.0
  site/config.toml
  site/content/en/docs/Reference/Drivers/includes/virtualbox_usage.inc
Labels: approved, cncf-cla: yes, size/XS

#5747 Make sure to look for vmrun, for vmware
  pkg/minikube/registry/drvs/vmware/vmware.go
Labels: approved, cncf-cla: yes, size/XS

#5748 Fix compile error introduced by vmrun fix
  pkg/minikube/registry/drvs/vmware/vmware.go
Labels: approved, cncf-cla: yes, size/XS

#5702 Fix links by using Hugo modules tag
  deploy/addons/layouts/gvisor/single.html
  deploy/addons/layouts/helm-tiller/single.html
  deploy/addons/layouts/ingress-dns/single.html
  deploy/addons/layouts/storage-provisioner-gluster/single.html
  netlify.toml
  site/config.toml
  site/content/en/docs/Tasks/addons.md
Labels: cncf-cla: yes, needs-ok-to-test, size/M

#5758 Do not check sshd for the none driver
  cmd/minikube/cmd/start.go
Labels: approved, cncf-cla: yes, size/XS

#5759 Add josedonizetti as minikube approver
  OWNERS
Labels: approved, cncf-cla: yes, size/XS

#5697 kubelet: Pass --config to use kubeadm generated configuration
  pkg/minikube/bootstrapper/kubeadm/kubeadm_test.go
  pkg/minikube/bootstrapper/kubeadm/versions.go
Labels: cncf-cla: yes, ok-to-test, size/S

#5757 Set --wait=false to default but still wait for apiserver
  cmd/minikube/cmd/start.go
  pkg/minikube/bootstrapper/bootstrapper.go
  pkg/minikube/bootstrapper/kubeadm/kubeadm.go
  pkg/minikube/bootstrapper/kubeadm/kubeadm_test.go
  test/integration/functional_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#5718 Refactor to remove opening browser and just return url(s)
  cmd/minikube/cmd/config/open.go
  cmd/minikube/cmd/service.go
  pkg/minikube/service/service.go
  pkg/minikube/service/service_test.go
Labels: cncf-cla: yes, ok-to-test, size/L

#5771 add generated asset file to gitignore
  .gitignore
Labels: approved, cncf-cla: yes, do-not-test, size/XS

#5767 Used fixed uid/gid for the default user account
  deploy/iso/minikube-iso/board/coreos/minikube/users
Labels: approved, cncf-cla: yes, ok-to-test, size/XS

#5761 Set Docker open-files limit ( 'ulimit -n') to be consistent with other runtimes
  pkg/provision/buildroot.go
  test/integration/functional_test.go
  test/integration/start_stop_delete_test.go
  test/integration/testdata/mysql.yaml
Labels: approved, cncf-cla: yes, ok-to-test, size/M

#5775 Update Makefile and CHANGELOG for v1.5.1
  CHANGELOG.md
  Makefile
Labels: approved, cncf-cla: yes, ok-to-test, size/S

#5750 macOS install docs: Minikube is a normal Homebrew formula now
  site/content/en/docs/Start/macos.md
Labels: cncf-cla: yes, needs-ok-to-test, size/XS

#5778 Set latest_release to v1.5.1
  site/config.toml
Labels: cncf-cla: yes

#5768 CI: Cut down log noise by just showing problems by default
  test/integration/helpers.go
Labels: approved, cncf-cla: yes, ok-to-test, size/XS

#5783 CI experiment: Move gvisor testing behind a flag, double timeout
  hack/jenkins/common.sh
  hack/jenkins/linux_integration_tests_kvm.sh
  test/integration/gvisor_addon_test.go
  test/integration/main.go
Labels: approved, cncf-cla: yes, ok-to-test, size/S

#5530 Refactor command runner interface, allow stdin writes
  Makefile
  cmd/minikube/cmd/start.go
  go.mod
  go.sum
  pkg/drivers/none/none.go
  pkg/minikube/bootstrapper/certs.go
  pkg/minikube/bootstrapper/certs_test.go
  pkg/minikube/bootstrapper/kubeadm/kubeadm.go
  pkg/minikube/cluster/mount.go
  pkg/minikube/cluster/mount_test.go
  pkg/minikube/command/command_runner.go
  pkg/minikube/command/exec_runner.go
  pkg/minikube/command/fake_runner.go
  pkg/minikube/command/ssh_runner.go
  pkg/minikube/command/ssh_runner_test.go
  pkg/minikube/cruntime/containerd.go
  pkg/minikube/cruntime/cri.go
  pkg/minikube/cruntime/crio.go
  pkg/minikube/cruntime/cruntime.go
  pkg/minikube/cruntime/cruntime_test.go
  pkg/minikube/cruntime/docker.go
  pkg/minikube/logs/logs.go
  pkg/minikube/problem/err_map.go
  pkg/minikube/tunnel/route_darwin.go
  pkg/util/utils.go
  pkg/util/utils_test.go
Labels: approved, cncf-cla: yes, ok-to-test, size/XXL

#5786 CI: kill VboxHeadless processes, move load warning until after cleanup
  hack/jenkins/common.sh
Labels: approved, cncf-cla: yes, ok-to-test, size/M

#5784 Improve reliability of TestStartStop with none driver
  hack/jenkins/linux_integration_tests_none.sh
  test/integration/helpers.go
  test/integration/start_stop_delete_test.go
Labels: approved, cncf-cla: yes, ok-to-test, size/S

#5648 Automatically install periodic cleanup script on macOS and Linux
  hack/jenkins/cron/cleanup_and_reboot_Darwin.sh
  hack/jenkins/cron/cleanup_and_reboot_Linux.sh
  hack/jenkins/linux_integration_tests_kvm.sh
  hack/jenkins/linux_integration_tests_none.sh
  hack/jenkins/linux_integration_tests_virtualbox.sh
  hack/jenkins/osx_integration_tests_hyperkit.sh
  hack/jenkins/osx_integration_tests_virtualbox.sh
Labels: approved, cncf-cla: yes, ok-to-test, size/L

#5794 Fix pod list retry, reset start timer
  test/integration/helpers.go
Labels: approved, cncf-cla: yes, ok-to-test, size/XS

#5790 service: fix --url mode, add integration tests
  cmd/minikube/cmd/service.go
  pkg/minikube/service/service.go
  test/integration/functional_test.go
Labels: approved, cncf-cla: yes, ok-to-test, size/L

#5310 Avoid the s3 and gcs protocol handlers in go-getter
  Makefile
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, size/XS

#5802 Make network validation friendlier, especially to corp networks
  cmd/minikube/cmd/start.go
  go.sum
Labels: approved, cncf-cla: yes, ok-to-test, size/M

#5803 Allow CPU count check to be disabled using --force
  cmd/minikube/cmd/start.go
Labels: approved, cncf-cla: yes, ok-to-test, size/XS

#5796 Version bump to v1.5.2
  CHANGELOG.md
  Makefile
Labels: approved, cncf-cla: yes, ok-to-test, size/S

#5804 Disable brew cask updater
  hack/jenkins/release_update_brew.sh
Labels: approved, cncf-cla: yes, size/XS
