Repository kubernetes/minikube, pull requests merged in 2019-06, with the labels that each got.

#4396 dashboard: detect nonexistent profile instead of causing a panic
  cmd/minikube/cmd/dashboard.go
Labels: cncf-cla: yes, lgtm, ok-to-test, size/M

#4383 Fix TestProxy
  test/integration/proxy_test.go
Labels: cncf-cla: yes, ok-to-test, size/M

#4405 Dashboard: add --disable-settings-authorizer to avoid settings 403 forbidden
  deploy/addons/dashboard/dashboard-dp.yaml.tmpl
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#4419 Improve type check for driver none
  cmd/minikube/cmd/delete.go
  cmd/minikube/cmd/env.go
  cmd/minikube/cmd/mount.go
  cmd/minikube/cmd/ssh.go
  pkg/drivers/none/none.go
  pkg/minikube/cluster/cluster.go
  pkg/minikube/drivers/none/driver.go
  pkg/minikube/machine/client.go
Labels: approved, cncf-cla: yes, ok-to-test, size/S

#4432 adding hyperv integration script
  hack/jenkins/windows_integration_test_hyperv.ps1
Labels: cncf-cla: yes, needs-ok-to-test, size/M

#4434 Fixing file path for windows
  test/integration/addons_test.go
  test/integration/mount_test.go
  test/integration/persistence_test.go
  test/integration/tunnel_test.go
Labels: cncf-cla: yes, ok-to-test, size/M

#4443 Add libvirt and qemu-kvm install docs for openSUSE/SLES
  docs/drivers.md
Labels: cncf-cla: yes, needs-ok-to-test, size/XS

#4439 Cache: don't use ssh runner for the none driver
  pkg/minikube/machine/cache_images.go
Labels: approved, cncf-cla: yes, size/XS

#4431 fix ShowDriverDeprecationNotification config setting
  cmd/minikube/cmd/config/config.go
  pkg/minikube/cluster/cluster.go
Labels: cncf-cla: yes, ok-to-test, size/S

#4444 Upgrade to kubernetes 1.14.3
  pkg/minikube/bootstrapper/kubeadm/testdata/containerd-api-port__default.yaml
  pkg/minikube/bootstrapper/kubeadm/testdata/containerd-pod-network-cidr__default.yaml
  pkg/minikube/bootstrapper/kubeadm/testdata/containerd__default.yaml
  pkg/minikube/bootstrapper/kubeadm/testdata/crio-options-gates__default.yaml
  pkg/minikube/bootstrapper/kubeadm/testdata/crio__default.yaml
  pkg/minikube/bootstrapper/kubeadm/testdata/default__default.yaml
  pkg/minikube/bootstrapper/kubeadm/testdata/image-repository__default.yaml
  pkg/minikube/bootstrapper/kubeadm/testdata/options__default.yaml
  pkg/minikube/constants/constants.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#4446 Update Makefile for 1.1.1 release
  Makefile
Labels: approved, cncf-cla: yes, size/XS

#4448 Update CHANGELOG for 1.1.1 release
  CHANGELOG.md
Labels: approved, cncf-cla: yes, size/M

#4408 adding medyagh to approvers
  OWNERS
Labels: cncf-cla: yes, needs-ok-to-test, size/XS

#4465 Automatically add extra options for none driver on ubuntu
  cmd/minikube/cmd/start.go
  pkg/minikube/drivers/none/driver.go
Labels: cncf-cla: yes, ok-to-test, size/S

#4480 Fix busybox version in integration tests
  test/integration/testdata/busybox-mount-test.yaml
  test/integration/testdata/busybox.yaml
Labels: cncf-cla: yes, ok-to-test, size/XS

#4474 adding retriable http get
  deploy/minikube/release_sanity_test.go
  go.mod
  go.sum
  pkg/util/utils.go
  test/integration/addons_test.go
  test/integration/proxy_test.go
  test/integration/version_upgrade_test.go
Labels: approved, cncf-cla: yes, size/M

#4424 Detect status before enable/disable addon
  cmd/minikube/cmd/config/util.go
  cmd/minikube/cmd/config/util_test.go
  cmd/minikube/cmd/dashboard.go
  pkg/minikube/assets/addons.go
Labels: cncf-cla: yes, ok-to-test, size/M

#4410 Upgrade CNI config version to 0.3.0
  pkg/minikube/bootstrapper/kubeadm/default_cni.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4491 Integration Test: increase timeout for watching pod
  pkg/util/kubernetes.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4380 Add kvm network name validation
  pkg/drivers/kvm/network.go
Labels: cncf-cla: yes, ok-to-test, size/XS

#4499 Upgrade buildroot minor version
  Makefile
Labels: approved, cncf-cla: yes, size/XS

#4514 Add some documentation about the dashboard
  README.md
  docs/dashboard.md
Labels: approved, cncf-cla: yes, size/M

#4516 Add netlify config
  netlify.toml
Labels: approved, cncf-cla: yes, size/S

#4521 Fix the release date of minikube v1.1.1
  README.md
Labels: approved, cncf-cla: yes, size/XS

#4504 Switch kubectl current-context on profile change
  cmd/minikube/cmd/config/profile.go
  cmd/minikube/cmd/start.go
  pkg/minikube/config/types.go
  pkg/util/kubeconfig.go
Labels: approved, cncf-cla: yes, size/M

#4469 Update for supporting k8s_v1.15.0-beta.1
  pkg/minikube/bootstrapper/kubeadm/kubeadm_test.go
  pkg/minikube/bootstrapper/kubeadm/versions.go
  pkg/minikube/constants/constants.go
Labels: approved, cncf-cla: yes, ok-to-test, size/S

#4528 Add issue templates for es, pt-BR, and zh-CN
  .github/ISSUE_TEMPLATE/en-US.md
  .github/ISSUE_TEMPLATE/es.md
  .github/ISSUE_TEMPLATE/pt-BR.md
  .github/ISSUE_TEMPLATE/zh-CN.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#4529 Register registry-proxy.yaml.tmpl with registry addons
  pkg/minikube/assets/addons.go
Labels: approved, cncf-cla: yes, needs-ok-to-test, size/XS

#4393 Fix "mount failed: File exists" issue when unmount fails
  pkg/minikube/cluster/mount.go
  pkg/minikube/cluster/mount_test.go
Labels: cncf-cla: yes, ok-to-test, size/S

#4407 Stop updating /etc/rkt/net.d config files
  pkg/minikube/bootstrapper/kubeadm/default_cni.go
  pkg/minikube/bootstrapper/kubeadm/kubeadm.go
  pkg/minikube/constants/constants.go
Labels: approved, cncf-cla: yes, ok-to-test, size/XS

#4535 Remove deprecated reporting api
  pkg/minikube/constants/constants.go
Labels: approved, cncf-cla: yes, size/XS

#4538 jenkins: Increase integration test time limit to 90 minutes
  hack/jenkins/common.sh
Labels: approved, cncf-cla: yes, size/XS

#4537 Update golangci-lint to v1.17.1
  Makefile
Labels: approved, cncf-cla: yes, size/S

#4385 Refactor: improve readability drivers.Restart
  pkg/drivers/drivers.go
Labels: cncf-cla: yes, ok-to-test, size/XS

#4464 Add ability to localize all strings output to console
  cmd/extract/extract.go
  cmd/minikube/cmd/root.go
  cmd/minikube/cmd/start.go
  cmd/minikube/main.go
  go.mod
  go.sum
  pkg/minikube/console/console.go
  pkg/minikube/console/console_test.go
  pkg/minikube/console/style.go
  pkg/minikube/exit/exit.go
  pkg/minikube/extract/extract.go
  pkg/minikube/extract/extract_test.go
  pkg/minikube/extract/testdata/sample_file.go
  pkg/minikube/extract/testdata/test.json
  pkg/minikube/notify/notify.go
  pkg/minikube/notify/notify_test.go
  pkg/minikube/problem/problem.go
  pkg/minikube/tests/dir_utils.go
  pkg/minikube/translate/translate.go
  pkg/minikube/translate/translations/fr-FR.json
  pkg/minikube/translate/translations/zh-CN.json
Labels: approved, cncf-cla: yes, size/XXL

#4550 Add Arabic and Indonesian issue templates
  .github/ISSUE_TEMPLATE/ar.md
  .github/ISSUE_TEMPLATE/id.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#4552 Suppress error message when translation file doesn't exist
  pkg/minikube/translate/translate.go
Labels: approved, cncf-cla: yes, size/XS

#4534 Update Kubernetes default version to v1.15.0
  pkg/minikube/bootstrapper/kubeadm/kubeadm_test.go
  pkg/minikube/bootstrapper/kubeadm/testdata/v1.10/containerd-api-port.yaml
  pkg/minikube/bootstrapper/kubeadm/testdata/v1.10/containerd-pod-network-cidr.yaml
  pkg/minikube/bootstrapper/kubeadm/testdata/v1.10/containerd.yaml
  pkg/minikube/bootstrapper/kubeadm/testdata/v1.10/crio-options-gates.yaml
  pkg/minikube/bootstrapper/kubeadm/testdata/v1.10/crio.yaml
  pkg/minikube/bootstrapper/kubeadm/testdata/v1.10/default.yaml
  pkg/minikube/bootstrapper/kubeadm/testdata/v1.10/image-repository.yaml
  pkg/minikube/bootstrapper/kubeadm/testdata/v1.10/options.yaml
  pkg/minikube/bootstrapper/kubeadm/testdata/v1.11/containerd-api-port.yaml
  pkg/minikube/bootstrapper/kubeadm/testdata/v1.11/containerd-pod-network-cidr.yaml
  pkg/minikube/bootstrapper/kubeadm/testdata/v1.11/containerd.yaml
  pkg/minikube/bootstrapper/kubeadm/testdata/v1.11/crio-options-gates.yaml
  pkg/minikube/bootstrapper/kubeadm/testdata/v1.11/crio.yaml
  pkg/minikube/bootstrapper/kubeadm/testdata/v1.11/default.yaml
  pkg/minikube/bootstrapper/kubeadm/testdata/v1.11/image-repository.yaml
  pkg/minikube/bootstrapper/kubeadm/testdata/v1.11/options.yaml
  pkg/minikube/bootstrapper/kubeadm/testdata/v1.12/containerd-api-port.yaml
  pkg/minikube/bootstrapper/kubeadm/testdata/v1.12/containerd-pod-network-cidr.yaml
  pkg/minikube/bootstrapper/kubeadm/testdata/v1.12/containerd.yaml
  pkg/minikube/bootstrapper/kubeadm/testdata/v1.12/crio-options-gates.yaml
  pkg/minikube/bootstrapper/kubeadm/testdata/v1.12/crio.yaml
  pkg/minikube/bootstrapper/kubeadm/testdata/v1.12/default.yaml
  pkg/minikube/bootstrapper/kubeadm/testdata/v1.12/image-repository.yaml
  pkg/minikube/bootstrapper/kubeadm/testdata/v1.12/options.yaml
  pkg/minikube/bootstrapper/kubeadm/testdata/v1.13/containerd-api-port.yaml
  pkg/minikube/bootstrapper/kubeadm/testdata/v1.13/containerd-pod-network-cidr.yaml
  pkg/minikube/bootstrapper/kubeadm/testdata/v1.13/containerd.yaml
  pkg/minikube/bootstrapper/kubeadm/testdata/v1.13/crio-options-gates.yaml
  pkg/minikube/bootstrapper/kubeadm/testdata/v1.13/crio.yaml
  pkg/minikube/bootstrapper/kubeadm/testdata/v1.13/default.yaml
  pkg/minikube/bootstrapper/kubeadm/testdata/v1.13/image-repository.yaml
  pkg/minikube/bootstrapper/kubeadm/testdata/v1.13/options.yaml
  pkg/minikube/bootstrapper/kubeadm/testdata/v1.14/containerd-api-port.yaml
  pkg/minikube/bootstrapper/kubeadm/testdata/v1.14/containerd-pod-network-cidr.yaml
  pkg/minikube/bootstrapper/kubeadm/testdata/v1.14/containerd.yaml
  pkg/minikube/bootstrapper/kubeadm/testdata/v1.14/crio-options-gates.yaml
  pkg/minikube/bootstrapper/kubeadm/testdata/v1.14/crio.yaml
  pkg/minikube/bootstrapper/kubeadm/testdata/v1.14/default.yaml
  pkg/minikube/bootstrapper/kubeadm/testdata/v1.14/image-repository.yaml
  pkg/minikube/bootstrapper/kubeadm/testdata/v1.14/options.yaml
  pkg/minikube/bootstrapper/kubeadm/testdata/v1.15/containerd-api-port.yaml
  pkg/minikube/bootstrapper/kubeadm/testdata/v1.15/containerd-pod-network-cidr.yaml
  pkg/minikube/bootstrapper/kubeadm/testdata/v1.15/containerd.yaml
  pkg/minikube/bootstrapper/kubeadm/testdata/v1.15/crio-options-gates.yaml
  pkg/minikube/bootstrapper/kubeadm/testdata/v1.15/crio.yaml
  pkg/minikube/bootstrapper/kubeadm/testdata/v1.15/default.yaml
  pkg/minikube/bootstrapper/kubeadm/testdata/v1.15/image-repository.yaml
  pkg/minikube/bootstrapper/kubeadm/testdata/v1.15/options.yaml
  pkg/minikube/constants/constants.go
Labels: approved, cncf-cla: yes, size/L

#4560 zh-CN: Use non-unicode percent signs for proper interpolation
  pkg/minikube/translate/translations/zh-CN.json
Labels: approved, cncf-cla: yes, size/XS

#4566 Use non-list YAML format for issue labels, simplify text
  .github/ISSUE_TEMPLATE/__en-US.md
  .github/ISSUE_TEMPLATE/ar.md
  .github/ISSUE_TEMPLATE/es.md
  .github/ISSUE_TEMPLATE/id.md
  .github/ISSUE_TEMPLATE/pt-BR.md
  .github/ISSUE_TEMPLATE/zh-CN.md
Labels: approved, cncf-cla: yes, size/S

#4421 Enable running containers with Podman
  deploy/iso/minikube-iso/package/Config.in
  deploy/iso/minikube-iso/package/conmon-master/Config.in
  deploy/iso/minikube-iso/package/conmon-master/conmon-master.hash
  deploy/iso/minikube-iso/package/conmon-master/conmon-master.mk
  deploy/iso/minikube-iso/package/podman/Config.in
  deploy/iso/minikube-iso/package/podman/libpod.conf
  deploy/iso/minikube-iso/package/podman/podman.mk
  deploy/iso/minikube-iso/package/runc-master/runc-master.mk
Labels: approved, cncf-cla: yes, size/M

#4567 Adjustment titles of Chinese & English issue template titles
  .github/ISSUE_TEMPLATE/__en-US.md
  .github/ISSUE_TEMPLATE/zh-CN.md
Labels: approved, cncf-cla: yes

#4559 Make markdownlint happy about whitespace
  CHANGELOG.md
  docs/configuring_kubernetes.md
  docs/contributors/releasing_minikube.md
  docs/contributors/roadmap.md
  docs/drivers.md
  docs/http_proxy.md
  docs/networking.md
  docs/offline.md
  docs/syncing-files.md
Labels: approved, cncf-cla: yes, size/M

#4562 Universally redirect stdlog messages to glog
  cmd/minikube/cmd/start.go
  cmd/minikube/main.go
  pkg/minikube/machine/cache_images.go
Labels: approved, cncf-cla: yes, size/M

#4455 Provide warning message for unnecessary sudo
  cmd/minikube/cmd/start.go
Labels: cncf-cla: yes, size/S

#4568 Allow --kubernetes-version to be specified without the leading v
  cmd/minikube/cmd/start.go
  test/integration/version_upgrade_test.go
Labels: approved, cncf-cla: yes, size/S

#4569 Bump Makefile version to v1.2.0 to prepare for a release
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4571 Remove extraneous whitespace from GitHub issue templates
  .github/ISSUE_TEMPLATE/ar.md
  .github/ISSUE_TEMPLATE/es.md
  .github/ISSUE_TEMPLATE/id.md
  .github/ISSUE_TEMPLATE/zh-CN.md
Labels: approved, cncf-cla: yes, size/M

#4557 Add golint and gocyclo smaller make targets
  Makefile
Labels: approved, cncf-cla: yes, size/S

#4573 Add release notes for v1.2.0
  CHANGELOG.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#4576 Update start.jpg to v1.2
  images/start.jpg
Labels: cncf-cla: yes, size/XS

#4572 Delete profile folder instead of just config.json
  cmd/minikube/cmd/delete.go
  pkg/minikube/constants/constants.go
Labels: cncf-cla: yes, needs-ok-to-test, size/XS

#4558 Fix the reportcard: gofmt, golint and gocyclo
  cmd/minikube/cmd/start.go
  pkg/drivers/kvm/network.go
  pkg/minikube/bootstrapper/kubeadm/kubeadm_test.go
  pkg/minikube/console/style_enum.go
  pkg/minikube/cruntime/containerd.go
  pkg/minikube/cruntime/crio.go
  pkg/minikube/cruntime/docker.go
  pkg/minikube/drivers/hyperv/driver.go
  pkg/minikube/extract/extract.go
  pkg/minikube/tests/dir_utils.go
  pkg/minikube/tests/ssh_mock.go
  test/integration/tunnel_test.go
Labels: approved, cncf-cla: yes, size/L

#4539 Add docs for registry proxy addon
  docs/reusing_the_docker_daemon.md
Labels: cncf-cla: yes, needs-ok-to-test, size/M

#4582 Improve typecheck for driver options
  cmd/minikube/cmd/config/config_test.go
  cmd/minikube/cmd/config/util_test.go
  cmd/minikube/cmd/start.go
  pkg/drivers/hyperkit/driver.go
  pkg/drivers/kvm/kvm.go
  pkg/minikube/cluster/cluster.go
  pkg/minikube/config/config_test.go
  pkg/minikube/constants/constants.go
  pkg/minikube/drivers/hyperkit/driver.go
  pkg/minikube/drivers/hyperv/driver.go
  pkg/minikube/drivers/kvm/driver.go
  pkg/minikube/drivers/kvm2/driver.go
  pkg/minikube/drivers/parallels/driver.go
  pkg/minikube/drivers/virtualbox/driver.go
  pkg/minikube/drivers/vmware/driver.go
  pkg/minikube/drivers/vmwarefusion/driver.go
  pkg/minikube/drivers/xhyve/driver.go
  pkg/minikube/machine/client_test.go
  pkg/minikube/tunnel/tunnel.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#4584 improve code readability cmd package
  cmd/minikube/cmd/delete.go
  cmd/minikube/cmd/start.go
  cmd/minikube/cmd/stop.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#4583 Update Ingress-NGINX to 0.24.1 Release
  deploy/addons/ingress/ingress-dp.yaml.tmpl
Labels: cncf-cla: yes, lgtm, ok-to-test, size/XS

#4548 Display commit id along with version
  Makefile
  cmd/minikube/cmd/version.go
  pkg/version/version.go
Labels: cncf-cla: yes, needs-ok-to-test, size/S

#4581 Add translation files into the minikube binary
  .gitignore
  Makefile
  cmd/extract/extract.go
  go.sum
  pkg/minikube/translate/translate.go
  test.sh
  translations/fr-FR.json
  translations/zh-CN.json
Labels: approved, cncf-cla: yes, size/M

#4591 Add kvm2 version documentation
  docs/drivers.md
Labels: cncf-cla: yes, needs-ok-to-test, size/XS

#4544 Unset current-context only if the profile is the current context
  pkg/util/kubeconfig.go
Labels: cncf-cla: yes, needs-ok-to-test, size/S

#4579 Makefile: add platform specific phony targets
  Makefile
  docs/contributors/build_guide.md
Labels: cncf-cla: yes, needs-ok-to-test, size/S

#4586 Make service wait time meaningful
  cmd/minikube/cmd/service.go
  pkg/minikube/service/service.go
Labels: cncf-cla: yes, lgtm, needs-ok-to-test, size/XS

#4601 Added Kurdish and Persian github issues language
  .github/ISSUE_TEMPLATE/fa.md
  .github/ISSUE_TEMPLATE/ku.md
Labels: approved, cncf-cla: yes, size/S

#4284 Added validation for --registry-mirror flag
  cmd/minikube/cmd/start.go
Labels: cncf-cla: yes, do-not-merge/work-in-progress, ok-to-test, size/S

#4602 Proxy: handle lower case proxy env vars
  cmd/minikube/cmd/start.go
  pkg/minikube/proxy/proxy.go
Labels: approved, cncf-cla: yes, size/XS

#4605 Use glog instead of logrus
  go.mod
  hack/release_notes/listpullreqs.go
Labels: cncf-cla: yes, needs-ok-to-test, size/S

#4611 Fix kvm2 remove domain
  pkg/drivers/kvm/kvm.go
Labels: cncf-cla: yes, lgtm, needs-ok-to-test, size/XS

#4603 Added solution message for not found service.
  pkg/minikube/problem/err_map.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4630 Fix version.gitCommitID doc
  pkg/version/version.go
Labels: cncf-cla: yes, needs-ok-to-test, size/XS

#4632 Add hyperkit doc
  pkg/drivers/hyperkit/driver.go
Labels: cncf-cla: yes, needs-ok-to-test, size/XS

#4612 Fix docker-machine-driver-kvm2 version
  Makefile
  cmd/drivers/kvm/main.go
  docs/drivers.md
  pkg/drivers/kvm/version.go
Labels: cncf-cla: yes, needs-ok-to-test, size/S

#4628 removed label selector for registry-proxy daemonset
  deploy/addons/registry/registry-proxy.yaml.tmpl
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/XS

#4401 Add support to custom qemu uri on kvm2 driver
  cmd/minikube/cmd/start.go
  pkg/drivers/kvm/domain.go
  pkg/drivers/kvm/kvm.go
  pkg/drivers/kvm/network.go
  pkg/minikube/config/types.go
  pkg/minikube/drivers/kvm/driver.go
  pkg/minikube/drivers/kvm2/driver.go
  test/integration/start_stop_delete_test.go
Labels: cncf-cla: yes, ok-to-test, size/M

#4631 Send sigkill to hyperkit if sigterm doesn't work
  pkg/drivers/hyperkit/driver.go
Labels: cncf-cla: yes, needs-ok-to-test, size/S

#4619 virtualbox: Make DNS settings configurable
  cmd/minikube/cmd/start.go
  pkg/minikube/config/types.go
  pkg/minikube/drivers/virtualbox/driver.go
Labels: cncf-cla: yes, needs-ok-to-test, size/S

#4638 Removed the adding a dependency from the contributing guide
  docs/contributors/README.md
  docs/contributors/adding_a_dependency.md
Labels: cncf-cla: yes, needs-ok-to-test, size/S

#4642 Fix error naming convention
  pkg/drivers/kvm/domain.go
  pkg/drivers/kvm/kvm.go
Labels: cncf-cla: yes, needs-ok-to-test, size/S

#4641 Improve kvm connection error message
  pkg/drivers/kvm/domain.go
  pkg/minikube/problem/err_map.go
Labels: cncf-cla: yes, needs-ok-to-test, size/S

#4595 Added validation for start memory size
  cmd/minikube/cmd/start.go
  pkg/drivers/hyperkit/driver.go
  pkg/drivers/kvm/kvm.go
  pkg/minikube/constants/constants.go
  pkg/util/utils.go
Labels: cncf-cla: yes, needs-ok-to-test, size/M
