Repository kubernetes/minikube, pull requests merged in 2019-05, with the labels that each got.

#4129 Don't attempt to pull docker images on relaunch
  cmd/minikube/cmd/start.go
Labels: cncf-cla: yes, do-not-merge/work-in-progress, size/S

#4188 Add script to update kubernetes version
  hack/help_text/gen_help_text.go
  hack/kubernetes_version/update_kubernetes_version.go
Labels: approved, cncf-cla: yes, size/M

#3646 Initial implementation of kubectl command
  cmd/minikube/cmd/kubectl.go
  pkg/minikube/bootstrapper/kubeadm/kubeadm.go
  pkg/minikube/constants/constants.go
  pkg/minikube/machine/cache_binaries.go
Labels: approved, cncf-cla: yes, size/L

#4192 Revert "Initial implementation of kubectl command"
  cmd/minikube/cmd/kubectl.go
  pkg/minikube/bootstrapper/kubeadm/kubeadm.go
  pkg/minikube/constants/constants.go
  pkg/minikube/machine/cache_binaries.go
Labels: approved, cncf-cla: yes, size/L

#4194 Fix the deploy targets, restore default target
  Makefile
Labels: approved, cncf-cla: yes, size/S

#4193 Add new kubectl command
  cmd/minikube/cmd/kubectl.go
  pkg/minikube/bootstrapper/kubeadm/kubeadm.go
  pkg/minikube/constants/constants.go
  pkg/minikube/machine/cache_binaries.go
Labels: approved, cncf-cla: yes, size/L

#4191 Make handling of stale mount pid files more robust
  cmd/minikube/cmd/stop.go
  cmd/util/util.go
Labels: approved, cncf-cla: yes, size/M

#4196 Improve the github issue template
  .github/ISSUE_TEMPLATE
Labels: cncf-cla: yes, needs-ok-to-test, size/S

#4198 Add solution text for common kvm2 and VirtualBox problems
  pkg/minikube/exit/exit.go
  pkg/minikube/problem/err_map.go
  pkg/minikube/problem/problem.go
  pkg/minikube/problem/problem_test.go
Labels: approved, cncf-cla: yes, size/L

#4199 Add automatic locale detection
  Gopkg.lock
  Gopkg.toml
  cmd/minikube/main.go
  pkg/minikube/console/console.go
  vendor/github.com/cloudfoundry-attic/jibber_jabber/LICENSE
  vendor/github.com/cloudfoundry-attic/jibber_jabber/jibber_jabber.go
  vendor/github.com/cloudfoundry-attic/jibber_jabber/jibber_jabber_unix.go
  vendor/github.com/cloudfoundry-attic/jibber_jabber/jibber_jabber_windows.go
Labels: approved, cncf-cla: yes, size/L

#4215 Fix stale err_map entry which broke TestFromError/VBOX_BLOCKED
  pkg/minikube/problem/err_map.go
Labels: approved, cncf-cla: yes, size/XS

#4203 Fix Makefile deploy rule dependency and improve error checking for invalid assets
  Makefile
  docs/contributors/adding_an_addon.md
  pkg/gvisor/enable.go
  pkg/minikube/assets/addons.go
  pkg/minikube/assets/vm_assets.go
  pkg/minikube/bootstrapper/ssh_runner.go
Labels: approved, cncf-cla: yes, size/L

#4197 Make default output of 'minikube start' consume fewer lines in the terminal
  cmd/minikube/cmd/start.go
  pkg/minikube/bootstrapper/kubeadm/kubeadm.go
Labels: cncf-cla: yes, needs-ok-to-test, size/M

#3937 Select an accessible image repository for some users
  cmd/minikube/cmd/start.go
  pkg/minikube/constants/constants.go
Labels: cncf-cla: yes, size/M

#4216 Replace ARCH sed macros with Go templates
  .gitignore
  Makefile
  deploy/addons/addon-manager.yaml.tmpl
  deploy/addons/dashboard/dashboard-dp.yaml.tmpl
  deploy/addons/dashboard/dashboard-svc.yaml.tmpl
  deploy/addons/efk/elasticsearch-rc.yaml.tmpl
  deploy/addons/efk/elasticsearch-svc.yaml.tmpl
  deploy/addons/efk/fluentd-es-configmap.yaml.tmpl
  deploy/addons/efk/fluentd-es-rc.yaml.tmpl
  deploy/addons/efk/kibana-rc.yaml.tmpl
  deploy/addons/efk/kibana-svc.yaml.tmpl
  deploy/addons/freshpod/freshpod-rc.yaml.tmpl
  deploy/addons/gpu/nvidia-driver-installer.yaml.tmpl
  deploy/addons/gpu/nvidia-gpu-device-plugin.yaml.tmpl
  deploy/addons/gvisor/gvisor-pod.yaml.tmpl
  deploy/addons/heapster/grafana-svc.yaml.tmpl
  deploy/addons/heapster/heapster-rc.yaml.tmpl
  deploy/addons/heapster/heapster-svc.yaml.tmpl
  deploy/addons/heapster/influx-grafana-rc.yaml.tmpl
  deploy/addons/heapster/influxdb-svc.yaml.tmpl
  deploy/addons/ingress/ingress-configmap.yaml.tmpl
  deploy/addons/ingress/ingress-dp.yaml.tmpl
  deploy/addons/ingress/ingress-rbac.yaml.tmpl
  deploy/addons/ingress/ingress-svc.yaml.tmpl
  deploy/addons/logviewer/logviewer-dp-and-svc.yaml.tmpl
  deploy/addons/logviewer/logviewer-rbac.yaml.tmpl
  deploy/addons/metrics-server/metrics-apiservice.yaml.tmpl
  deploy/addons/metrics-server/metrics-server-deployment.yaml.tmpl
  deploy/addons/metrics-server/metrics-server-service.yaml.tmpl
  deploy/addons/registry-creds/registry-creds-rc.yaml.tmpl
  deploy/addons/registry/registry-rc.yaml.tmpl
  deploy/addons/registry/registry-svc.yaml.tmpl
  deploy/addons/storage-provisioner-gluster/glusterfs-daemonset.yaml.tmpl
  deploy/addons/storage-provisioner-gluster/heketi-deployment.yaml.tmpl
  deploy/addons/storage-provisioner-gluster/storage-gluster-ns.yaml.tmpl
  deploy/addons/storage-provisioner-gluster/storage-provisioner-glusterfile.yaml.tmpl
  deploy/addons/storage-provisioner/storage-provisioner.yaml.tmpl
  deploy/addons/storageclass/storageclass.yaml.tmpl
  pkg/minikube/assets/addons.go
Labels: cncf-cla: yes, size/L

#4162 Standardize ASCII prefix for info, warning, and error messages
  pkg/minikube/console/console_test.go
  pkg/minikube/console/style.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#4220 Fix registry addon ReplicationController template
  deploy/addons/registry/registry-rc.yaml.tmpl
Labels: cncf-cla: yes, needs-ok-to-test, size/XS

#4244 Fix location of Kubernetes binaries in cache directory
  docs/offline.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#4177 Unset the current-context after minikube stop
  cmd/minikube/cmd/stop.go
  pkg/util/kubeconfig.go
  test/integration/start_stop_delete_test.go
Labels: cncf-cla: yes, needs-ok-to-test, size/M

#4257 Add more solutions messages
  pkg/minikube/logs/logs.go
  pkg/minikube/logs/logs_test.go
  pkg/minikube/problem/err_map.go
  pkg/minikube/problem/problem_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#4255 Return host IP when using vmware as vm driver.
  pkg/minikube/cluster/cluster.go
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/S

#4270 Test the upgrade of Kubernetes versions (oldest->newest)
  test/integration/version_upgrade_test.go
Labels: approved, cncf-cla: yes, size/S

#3464 WIP: Resolve service FQDNs from host during 'minikube tunnel' (macOS)
  pkg/minikube/tunnel/cluster_inspector.go
  pkg/minikube/tunnel/cluster_inspector_test.go
  pkg/minikube/tunnel/route_darwin.go
  pkg/minikube/tunnel/route_darwin_test.go
  pkg/minikube/tunnel/route_test.go
  pkg/minikube/tunnel/types.go
Labels: cncf-cla: yes, do-not-merge/work-in-progress, size/L

#4278 Lint cleanup after merging tunnel DNS resolution
  pkg/minikube/tunnel/cluster_inspector.go
  pkg/minikube/tunnel/cluster_inspector_test.go
  pkg/minikube/tunnel/route_test.go
Labels: approved, cncf-cla: yes, size/S

#4276 Restart kube-proxy using kubeadm & add bootstrapper.WaitCluster
  cmd/minikube/cmd/start.go
  pkg/minikube/bootstrapper/bootstrapper.go
  pkg/minikube/bootstrapper/kubeadm/kubeadm.go
  pkg/minikube/bootstrapper/kubeadm/util.go
Labels: approved, cncf-cla: yes, size/L

#4281 log the intended message when errFile/outFile are unset
  pkg/minikube/console/console.go
Labels: approved, cncf-cla: yes, size/XS

#4279 Upgrade default Kubernetes release to v1.14.2
  pkg/minikube/bootstrapper/kubeadm/testdata/containerd-api-port__default.yaml
  pkg/minikube/bootstrapper/kubeadm/testdata/containerd__default.yaml
  pkg/minikube/bootstrapper/kubeadm/testdata/crio-options-gates__default.yaml
  pkg/minikube/bootstrapper/kubeadm/testdata/crio__default.yaml
  pkg/minikube/bootstrapper/kubeadm/testdata/default__default.yaml
  pkg/minikube/bootstrapper/kubeadm/testdata/image-repository__default.yaml
  pkg/minikube/bootstrapper/kubeadm/testdata/options__default.yaml
  pkg/minikube/constants/constants.go
Labels: approved, cncf-cla: yes, size/S

#4204 Upgrade Docker, from 18.06.3-ce to 18.09.5
  deploy/iso/minikube-iso/package/containerd-bin/containerd-bin.hash
  deploy/iso/minikube-iso/package/containerd-bin/containerd-bin.mk
  deploy/iso/minikube-iso/package/docker-bin/docker-bin.hash
  deploy/iso/minikube-iso/package/docker-bin/docker-bin.mk
  deploy/iso/minikube-iso/package/runc-master/runc-master.hash
  deploy/iso/minikube-iso/package/runc-master/runc-master.mk
  pkg/minikube/constants/constants.go
Labels: approved, cncf-cla: yes, size/M

#4282 Set apiserver oom_adj to -10 to avoid OOMing before other pods
  pkg/minikube/bootstrapper/kubeadm/kubeadm.go
Labels: approved, cncf-cla: yes, size/S

#4229 Allow minikube to function with misconfigured NO_PROXY value
  cmd/minikube/cmd/dashboard.go
  cmd/minikube/cmd/start.go
  go.mod
  go.sum
  pkg/minikube/bootstrapper/kubeadm/kubeadm.go
  pkg/minikube/proxy/proxy.go
  pkg/minikube/proxy/proxy_test.go
  pkg/minikube/service/service.go
  pkg/util/kubernetes.go
  test/integration/proxy_test.go
Labels: cncf-cla: yes, size/L

#4298 Add missing testdata update to v1.14.2
  pkg/minikube/bootstrapper/kubeadm/testdata/containerd-pod-network-cidr__default.yaml
Labels: cncf-cla: yes

#4300 Use NewMinikubeRunner in TestVersionUpgrade to get correct VM driver
  test/integration/version_upgrade_test.go
Labels: approved, cncf-cla: yes, size/XS

#4297 Make the minikube binary depend on cmd/ and pkg/ go files
  Makefile
Labels: approved, cncf-cla: yes, size/XS

#4296 Upgrade Docker, from 18.09.5 to 18.09.6
  deploy/iso/minikube-iso/package/docker-bin/docker-bin.hash
  deploy/iso/minikube-iso/package/docker-bin/docker-bin.mk
Labels: approved, cncf-cla: yes, size/XS

#4299 Update to Podman 1.3 & CRIO v1.14.1
  deploy/iso/minikube-iso/board/coreos/minikube/rootfs-overlay/etc/cni/net.d/.keep
  deploy/iso/minikube-iso/package/crio-bin/crio-bin.hash
  deploy/iso/minikube-iso/package/crio-bin/crio-bin.mk
  deploy/iso/minikube-iso/package/podman/podman.hash
  deploy/iso/minikube-iso/package/podman/podman.mk
Labels: approved, cncf-cla: yes, size/S

#4307 Make sure to start Docker, before getting version
  cmd/minikube/cmd/start.go
Labels: approved, cncf-cla: yes, size/S

#4312 Improve driver issue map - KVM2_[START_NO_IP|QEMU_MONITOR], DRIVER_[CRASHED|EXITED]
  pkg/minikube/problem/err_map.go
Labels: approved, cncf-cla: yes, size/S

#4306 Disable SystemVerification preflight on Kubernetes releases <1.13
  pkg/minikube/bootstrapper/kubeadm/kubeadm.go
  pkg/minikube/bootstrapper/kubeadm/templates.go
Labels: approved, cncf-cla: yes, size/M

#4308 Validate kvm network exists
  pkg/drivers/kvm/network.go
Labels: cncf-cla: yes, needs-ok-to-test, size/XS

#4310 Add some CRI-agnostic image build documentation
  docs/README.md
  docs/building_images_within_the_vm.md
Labels: approved, cncf-cla: yes, size/M

#4301 Update Makefile and CHANGELOG for v1.1.0.
  CHANGELOG.md
  Makefile
Labels: approved, cncf-cla: yes, size/M

#4315 Fallback to golangci-lint v1.16.0 if necessary, quiet test.sh output
  Makefile
  test.sh
Labels: approved, cncf-cla: yes, size/S

#4326 Add documentation for file syncing
  docs/README.md
  docs/syncing-files.md
Labels: cncf-cla: yes

#4262 Added test case for minikube config unset
  cmd/minikube/cmd/config/unset_test.go
Labels: cncf-cla: yes, ok-to-test, size/M

#4331 Skip kvm network deletion if private network doesn't exist
  pkg/drivers/kvm/network.go
Labels: cncf-cla: yes, needs-ok-to-test, size/XS

#4335 Get current profile if no arguments given
  cmd/minikube/cmd/config/profile.go
Labels: cncf-cla: yes, needs-ok-to-test, size/S

#4338 Enable GatewayPorts in sshd_config, for proxying in services into minikube
  deploy/iso/minikube-iso/board/coreos/minikube/rootfs-overlay/etc/ssh/sshd_config
Labels: cncf-cla: yes, needs-ok-to-test, size/XS

#4343 Fix kvm remove warn message
  pkg/drivers/kvm/kvm.go
Labels: cncf-cla: yes, ok-to-test, size/XS

#4323 kvm2: Add support for --kvm-network to ensureNetwork
  pkg/drivers/kvm/network.go
  test/integration/start_stop_delete_test.go
Labels: cncf-cla: yes, needs-ok-to-test, size/XS

#4344 Fix kvm remove when domain is not running
  pkg/drivers/kvm/kvm.go
Labels: cncf-cla: yes, needs-ok-to-test, size/S

#4340 kernel: Add config for tc u32 filter and mirred action
  deploy/iso/minikube-iso/board/coreos/minikube/linux_defconfig
Labels: cncf-cla: yes, needs-ok-to-test, size/XS

#4341 Enable registry-proxy
  deploy/addons/registry/registry-proxy.yaml.tmpl
Labels: cncf-cla: yes, needs-ok-to-test, size/S

#4334 Refactor kvm lookupIPFromStatusFile
  pkg/drivers/kvm/network.go
  pkg/drivers/kvm/network_test.go
Labels: cncf-cla: yes, needs-ok-to-test, size/L

#4362 Windows installer: Use PowerShell to update PATH value to avoid 1024 char truncation
  installers/windows/minikube.nsi
  installers/windows/update_path.bat
  installers/windows/update_path.ps1
Labels: cncf-cla: yes, needs-ok-to-test, size/L

#4355 Fix kvm remove when domain is not defined
  pkg/drivers/kvm/kvm.go
Labels: cncf-cla: yes, needs-ok-to-test, size/S

#4354 Pass minikube stdin to the kubectl command
  cmd/minikube/cmd/kubectl.go
Labels: approved, cncf-cla: yes, size/XS

#4321 Make buildah --no-pivot default, using env var
  deploy/iso/minikube-iso/package/podman/buildah.profile
  deploy/iso/minikube-iso/package/podman/podman.mk
Labels: approved, cncf-cla: yes, size/XS

#4356 delete the unnecessary word
  docs/env_vars.md
Labels: cncf-cla: yes, needs-ok-to-test, size/XS

#2797 Disable hyperv dynamic memory for hyperv driver
  pkg/minikube/drivers/hyperv/driver.go
Labels: cncf-cla: yes, size/XS

#4364 docker-env: Remove DOCKER_API_VERSION
  cmd/minikube/cmd/env.go
  cmd/minikube/cmd/env_test.go
  pkg/minikube/constants/constants.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#4283 Sync guest system clock if desynchronized from host
  pkg/minikube/cluster/cluster.go
  pkg/minikube/cluster/cluster_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#4370 fix func name in comment
  pkg/minikube/cluster/cluster.go
Labels: cncf-cla: yes, needs-ok-to-test, size/XS

#4373 OWNERS and MAINTAINERS file cleanup
  MAINTAINERS
  OWNERS
Labels: approved, cncf-cla: yes, size/S

#4372 Increase apiserver wait time from 1 minute to 3 minutes
  pkg/minikube/bootstrapper/kubeadm/kubeadm.go
Labels: approved, cncf-cla: yes, size/XS

#4379 Add kvm default network documentation
  docs/drivers.md
Labels: cncf-cla: yes, needs-ok-to-test, size/S

#4376 Change console style string to enum
  cmd/minikube/cmd/config/open.go
  cmd/minikube/cmd/config/validations.go
  cmd/minikube/cmd/dashboard.go
  cmd/minikube/cmd/delete.go
  cmd/minikube/cmd/mount.go
  cmd/minikube/cmd/service_list.go
  cmd/minikube/cmd/start.go
  cmd/minikube/cmd/stop.go
  cmd/minikube/cmd/update-context.go
  pkg/minikube/bootstrapper/kubeadm/kubeadm.go
  pkg/minikube/cluster/cluster.go
  pkg/minikube/console/console.go
  pkg/minikube/console/console_test.go
  pkg/minikube/console/style.go
  pkg/minikube/console/style_enum.go
  pkg/minikube/cruntime/containerd.go
  pkg/minikube/cruntime/crio.go
  pkg/minikube/cruntime/cruntime.go
  pkg/minikube/cruntime/cruntime_test.go
  pkg/minikube/cruntime/docker.go
  pkg/minikube/exit/exit.go
  pkg/minikube/logs/logs.go
  pkg/minikube/machine/cache_binaries.go
  pkg/minikube/problem/problem.go
  pkg/minikube/service/service.go
  pkg/util/downloader.go
Labels: approved, cncf-cla: yes, size/L

#4381 Fix kvm gpu log
  pkg/drivers/kvm/gpu.go
Labels: cncf-cla: yes, ok-to-test, size/XS

#4382 clean vendor on make clean
  Makefile
Labels: cncf-cla: yes, needs-ok-to-test, size/XS

#4399 Fix kvm trobleshoot documentation
  docs/drivers.md
Labels: cncf-cla: yes, needs-ok-to-test, size/XS

#4386 Fixed addon-manager failing with non-default --apiserver-port
  pkg/minikube/bootstrapper/certs.go
Labels: cncf-cla: yes, needs-ok-to-test, size/XS
