Repository kubernetes/minikube, pull requests merged in 2020-10, with the labels that each got.

#8978 fix: "profile list" shows paused clusters as "Running"
  cmd/minikube/cmd/config/profile_list.go
Labels: cncf-cla: yes, ok-to-test, size/L

#9294 add dedicated network for docker driver
  cmd/minikube/cmd/delete.go
  cmd/minikube/cmd/mount.go
  hack/preload-images/generate.go
  pkg/drivers/kic/kic.go
  pkg/drivers/kic/oci/errors.go
  pkg/drivers/kic/oci/network.go
  pkg/drivers/kic/oci/network_create.go
  pkg/drivers/kic/oci/oci.go
  pkg/drivers/kic/oci/types.go
  pkg/drivers/kic/types.go
  pkg/minikube/cluster/ip.go
  pkg/minikube/driver/driver.go
  pkg/minikube/driver/driver_test.go
  pkg/minikube/node/start.go
  pkg/minikube/registry/drvs/docker/docker.go
  pkg/minikube/registry/drvs/podman/podman.go
  site/content/en/docs/handbook/vpn_and_proxy.md
Labels: approved, cncf-cla: yes, ok-to-test, size/L

#9382 point to newest gcp-auth-webhook version
  deploy/addons/gcp-auth/gcp-auth-webhook.yaml
Labels: approved, cncf-cla: yes, ok-to-test, size/XS

#9388 Run gofmt on pkg/minikube/driver/driver_test.go
  pkg/minikube/driver/driver_test.go
Labels: approved, cncf-cla: yes, size/S

#9389 Do some simple cleanup of the golint complaints
  cmd/minikube/cmd/status.go
  pkg/minikube/cruntime/containerd.go
  pkg/minikube/cruntime/crio.go
  pkg/minikube/cruntime/docker.go
  pkg/minikube/download/json_output.go
  pkg/minikube/driver/driver.go
  pkg/minikube/out/register/cloud_events.go
  pkg/minikube/out/register/log.go
  pkg/minikube/reason/exitcodes.go
  pkg/minikube/reason/reason.go
  pkg/minikube/tests/dir_utils.go
  pkg/perf/monitor/constants.go
  pkg/util/utils.go
Labels: approved, cncf-cla: yes, size/M

#9387 Fixed broken link, and wording.
  site/content/en/docs/drivers/kvm2.md
Labels: cncf-cla: yes, needs-ok-to-test, size/XS

#9386 Update triage/support label references to kind/support
  site/content/en/docs/contrib/triage.md
Labels: cncf-cla: yes, size/XS

#9367 don't allow profile name to be less than 2 characters
  cmd/minikube/cmd/start.go
  pkg/minikube/config/profile.go
  pkg/minikube/config/profile_test.go
Labels: approved, cncf-cla: yes, size/S

#9400 explicitly skip gcp-auth webhook for internally maintained addons
  deploy/addons/dashboard/dashboard-dp.yaml
  deploy/addons/gcp-auth/gcp-auth-webhook.yaml
  deploy/addons/gvisor/gvisor-pod.yaml.tmpl
  deploy/addons/ingress-dns/ingress-dns-pod.yaml
  deploy/addons/ingress/ingress-dp.yaml.tmpl
  deploy/addons/storage-provisioner/storage-provisioner.yaml.tmpl
  site/content/en/docs/contrib/addons.en.md
Labels: approved, cncf-cla: yes, ok-to-test, size/S

#9383 Fix minikube status bug when cluster is paused
  cmd/minikube/cmd/status.go
  test/integration/status_test.go
Labels: approved, cncf-cla: yes, ok-to-test, size/M

#9401 Fixes existing Polish translations
  translations/pl.json
Labels: cncf-cla: yes, needs-ok-to-test, size/S

#9406 add gcp-skip label to gcp-auth cert job pods
  deploy/addons/gcp-auth/gcp-auth-webhook.yaml
Labels: approved, cncf-cla: yes, ok-to-test, size/XS

#9405 Release v1.14.0-beta.0
  CHANGELOG.md
  Makefile
Labels: approved, cncf-cla: yes, ok-to-test, size/M

#9316 preload: print solution message when there is no space left on device
  cmd/minikube/cmd/start.go
  pkg/drivers/kic/kic.go
  pkg/drivers/kic/oci/errors.go
  pkg/minikube/node/start.go
Labels: approved, cncf-cla: yes, ok-to-test, size/S

#9334 Make storage-provisioner available for all arch
  Makefile
  deploy/addons/storage-provisioner/storage-provisioner.yaml.tmpl
  hack/jenkins/release_build_and_upload.sh
Labels: approved, cncf-cla: yes, size/S

#9411 Remove reference to Virtualbox in "stop" help
  cmd/minikube/cmd/stop.go
  site/content/en/docs/commands/stop.md
Labels: approved, cncf-cla: yes, size/XS

#9404 Add new flag "--ports" to expose ports for docker & podman drivers
  cmd/minikube/cmd/start_flags.go
  pkg/drivers/kic/kic.go
  pkg/drivers/kic/types.go
  pkg/minikube/config/types.go
  pkg/minikube/registry/drvs/docker/docker.go
  pkg/minikube/registry/drvs/podman/podman.go
  site/content/en/docs/commands/start.md
Labels: cncf-cla: yes, needs-ok-to-test, size/S

#9412 fix panic when updating mount-string with KiC driver after cluster creation without mount configuration
  cmd/minikube/cmd/start.go
Labels: cncf-cla: yes, needs-ok-to-test, size/XS

#9419 stress test: Minor improvements for running on Cloud Shell
  test/stress/stress.sh
Labels: approved, cncf-cla: yes, size/S

#9414 Delete context when stopped
  cmd/minikube/cmd/stop.go
  pkg/minikube/reason/reason.go
Labels: cncf-cla: yes, needs-ok-to-test, size/S

#9413 fixing the controller name in ingress-nginx-controller patch
  site/content/en/docs/tutorials/nginx_tcp_udp_ingress.md
Labels: cncf-cla: yes, needs-ok-to-test, size/XS

#9421 bump kicbase image tag to stable
  pkg/drivers/kic/types.go
  site/content/en/docs/commands/start.md
Labels: approved, cncf-cla: yes, size/XS

#9423 skip "cache add_local" test on macos gh runner
  test/integration/functional_test.go
Labels: approved, cncf-cla: yes, size/XS

#9426 Add further debugging for DRV_CP_ENDPOINT failure
  pkg/drivers/kic/oci/errors.go
  pkg/drivers/kic/oci/network_create.go
Labels: approved, cncf-cla: yes, size/S

#9432 Release v.1.14.0
  CHANGELOG.md
  Makefile
Labels: approved, cncf-cla: yes, ok-to-test, size/M

#9329 Buildroot 2020.02.6
  .github/workflows/iso.yml
  Makefile
  deploy/iso/minikube-iso/configs/minikube_defconfig
  deploy/iso/minikube-iso/package/cni-plugins/Config.in
  deploy/iso/minikube-iso/package/cni-plugins/cni-plugins.mk
  deploy/iso/minikube-iso/package/cni/Config.in
  deploy/iso/minikube-iso/package/cni/cni.mk
  deploy/iso/minikube-iso/package/conmon/Config.in
  deploy/iso/minikube-iso/package/containerd-bin/Config.in
  deploy/iso/minikube-iso/package/containerd-bin/containerd-bin.mk
  deploy/iso/minikube-iso/package/crio-bin/Config.in
  deploy/iso/minikube-iso/package/crio-bin/crio-bin.mk
  deploy/iso/minikube-iso/package/podman/Config.in
  deploy/iso/minikube-iso/package/podman/podman.mk
  deploy/iso/minikube-iso/package/runc-master/Config.in
  deploy/iso/minikube-iso/package/runc-master/runc-master.mk
Labels: approved, cncf-cla: yes, size/M

#9384 update_kubernetes_version: standalone script v2
  hack/kubernetes_version/update_kubernetes_version.go
Labels: cncf-cla: yes, needs-ok-to-test, size/L

#9408 simplify addon code by fixing gcp-auth failure policy
  deploy/addons/gcp-auth/gcp-auth-webhook.yaml
  deploy/addons/storage-provisioner/storage-provisioner.yaml.tmpl
  pkg/addons/addons.go
  test/integration/addons_test.go
  test/integration/testdata/gcp-creds.json
Labels: approved, cncf-cla: yes, ok-to-test, size/L

#9454 Bump ISO to use latest Buildroot 2020.02.6
  Makefile
  site/content/en/docs/commands/start.md
Labels: approved, cncf-cla: yes, ok-to-test, size/XS

#9462 Fix typo (cointainer -> container)
  pkg/drivers/kic/oci/oci.go
Labels: cncf-cla: yes, needs-ok-to-test, size/XS

#9417 Fix "--native-ssh" flag of "minikube ssh"
  cmd/minikube/cmd/ssh.go
  pkg/minikube/machine/ssh.go
Labels: cncf-cla: yes, ok-to-test, size/XS

#9459 new --wait component "kubelet"
  cmd/minikube/cmd/status.go
  pkg/drivers/none/none.go
  pkg/minikube/bootstrapper/bsutil/kverify/kverify.go
  pkg/minikube/bootstrapper/bsutil/kverify/system_pods.go
  pkg/minikube/bootstrapper/bsutil/kverify/system_svc.go
  pkg/minikube/bootstrapper/kubeadm/kubeadm.go
  pkg/minikube/node/start.go
  site/content/en/docs/commands/start.md
Labels: approved, cncf-cla: yes, ok-to-test, size/L

#9444 bump helm-tiller addon to v2.16.12
  deploy/addons/helm-tiller/helm-tiller-dp.tmpl
Labels: area/addons, cncf-cla: yes, ok-to-test, size/XS

#9466 Combine pause status test into existing pause test
  .github/workflows/pr.yml
  test/integration/pause_test.go
  test/integration/status_test.go
Labels: approved, cncf-cla: yes, ok-to-test, size/M

#9476 make sure worker nodes actually join control plane on restart
  pkg/minikube/bootstrapper/kubeadm/kubeadm.go
  pkg/minikube/node/start.go
  test/integration/multinode_test.go
Labels: approved, cncf-cla: yes, ok-to-test, size/S

#9490 Update warning message for local proxy.
  pkg/minikube/proxy/proxy.go
Labels: approved, cncf-cla: yes, ok-to-test, size/XS

#9477 Upgrade Docker, from 19.03.12 to 19.03.13
  deploy/iso/minikube-iso/package/docker-bin/docker-bin.hash
  deploy/iso/minikube-iso/package/docker-bin/docker-bin.mk
Labels: approved, cncf-cla: yes, size/XS

#9478 Upgrade containerd to the same as docker-ce uses
  deploy/iso/minikube-iso/package/containerd-bin/containerd-bin.hash
  deploy/iso/minikube-iso/package/containerd-bin/containerd-bin.mk
Labels: approved, cncf-cla: yes, size/XS

#9484 Install docker from docker.com instead of distro
  deploy/kicbase/Dockerfile
Labels: approved, cncf-cla: yes, size/S

#9511 Use correct port for echoserver - fixes "Connection reset by peer" LoadBalancer issue
  site/content/en/docs/start/_index.md
Labels: approved, cncf-cla: yes, needs-ok-to-test, size/XS

#9368 Added deprecation warning for --network-plugin=cni
  cmd/minikube/cmd/start_flags.go
Labels: approved, cncf-cla: yes, needs-ok-to-test, size/XS

#9435 Bump version for ingress dns addon
  deploy/addons/ingress-dns/ingress-dns-pod.yaml
Labels: cncf-cla: yes, needs-ok-to-test, size/XS

#9280 Upgrade go version to 1.15.2
  .github/workflows/iso.yml
  .github/workflows/kic_image.yml
  .github/workflows/master.yml
  .github/workflows/pr.yml
  .travis.yml
  Makefile
  go.mod
  hack/jenkins/common.sh
Labels: cncf-cla: yes, ok-to-test, size/M

#9500 Update go-getter to 1.4.2 and add checksum patch
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, size/XS

#9515 Double addon pod wait time to avoid errors on slow pulls
  pkg/addons/addons.go
Labels: approved, cncf-cla: yes, ok-to-test, size/XS

#9393 Update default linux config to support ftrace, for bpf tracing, fixes #8637
  deploy/iso/minikube-iso/board/coreos/minikube/linux_defconfig
Labels: cncf-cla: yes, needs-ok-to-test, size/XS

#9494 Remove Init function from the parallels driver definition
  pkg/minikube/registry/drvs/parallels/parallels.go
Labels: cncf-cla: yes, needs-ok-to-test, size/XS

#9519 Remove old unused build tags from localkube
  Makefile
Labels: approved, cncf-cla: yes, size/XS

#8923 Upgrade crio to 1.18.3 (merge after buildroot2020)
  deploy/iso/minikube-iso/package/crio-bin/crio-bin.hash
  deploy/iso/minikube-iso/package/crio-bin/crio-bin.mk
  deploy/iso/minikube-iso/package/crio-bin/crio.conf
  deploy/iso/minikube-iso/package/crio-bin/crio.conf.default
Labels: approved, cncf-cla: yes, size/L

#9505 Omit error message if 100-crio-bridge.conf has already been disabled
  pkg/minikube/cni/flannel.go
Labels: approved, cncf-cla: yes, ok-to-test, size/XS

#9394 re-synchronize default linux kernel config with buildroot
  deploy/iso/minikube-iso/board/coreos/minikube/linux_defconfig
Labels: approved, cncf-cla: yes, needs-ok-to-test, size/S

#9540 increase logs_test time diff tolerance
  pkg/minikube/perf/logs_test.go
Labels: cncf-cla: yes, needs-ok-to-test, size/XS

#9530 docker: When creating networks, use MTU of built-in bridge network
  pkg/drivers/kic/oci/network.go
  pkg/drivers/kic/oci/network_create.go
Labels: approved, cncf-cla: yes, ok-to-test, size/L

#9543 release 1.14.1
  CHANGELOG.md
  Makefile
Labels: approved, cncf-cla: yes, ok-to-test, size/M

#9557 fix "profile list" timing out when cluster stopped.
  cmd/minikube/cmd/config/profile_list.go
  go.sum
  pkg/minikube/config/profile.go
  pkg/minikube/config/types.go
Labels: approved, cncf-cla: yes, ok-to-test, size/S

#9559 github action test improvements
  .github/workflows/master.yml
  .github/workflows/pr.yml
  test/integration/functional_test.go
Labels: approved, cncf-cla: yes, ok-to-test, size/M

#9569 Release v1.14.2
  CHANGELOG.md
  Makefile
Labels: approved, cncf-cla: yes, size/S

#9537 Enable TCP Path MTU Discovery when an ICMP black hole is detected
  deploy/iso/minikube-iso/board/coreos/minikube/rootfs-overlay/etc/sysctl.d/11-tcp-mtu-probing.conf
  deploy/kicbase/11-tcp-mtu-probing.conf
  deploy/kicbase/Dockerfile
Labels: approved, cncf-cla: yes, size/XS

#9517 Update "parallels" driver library and make this driver built into minikube
  go.mod
  go.sum
  pkg/minikube/registry/drvs/parallels/parallels.go
  site/content/en/docs/drivers/includes/parallels_usage.inc
  site/content/en/docs/drivers/parallels.md
Labels: approved, cncf-cla: yes, needs-ok-to-test, size/M

#9527 Update kicbase base image and sync with kind
  deploy/kicbase/Dockerfile
Labels: approved, cncf-cla: yes, size/S

#9533 Add unit test
  pkg/addons/validations_test.go
Labels: cncf-cla: yes, ok-to-test, size/M

#9464 Add hack/update package to automate PR generation
  go.mod
  go.sum
  hack/update/filesystem.go
  hack/update/github.go
  hack/update/golang_version/update_golang_version.go
  hack/update/kicbase_version/update_kicbase_version.go
  hack/update/kubernetes_version/update_kubernetes_version.go
  hack/update/registry.go
  hack/update/update.go
Labels: cncf-cla: yes, needs-ok-to-test, size/XXL

#9439 automate pushing kicbase image from snapshot to stable after release
  hack/kicbase_version/release_kicbase_version.go
Labels: approved, cncf-cla: yes, needs-ok-to-test, size/L

#9573 site: Update latest version
  site/content/en/docs/_index.md
Labels: approved, cncf-cla: yes, size/XS

#9578 Fix minikube kubectl direct call test by allowing users to specify context
  cmd/minikube/cmd/root.go
  test/integration/functional_test.go
Labels: approved, cncf-cla: yes, ok-to-test, size/S

#9445 Update ingress-nginx image to v0.40.2
  deploy/addons/ingress/ingress-dp.yaml.tmpl
Labels: approved, cncf-cla: yes, ok-to-test, size/S

#9542 replace set-env with Env Files in GitHub Actions
  .github/workflows/iso.yml
  .github/workflows/kic_image.yml
  .github/workflows/master.yml
  .github/workflows/pr.yml
Labels: cncf-cla: yes, needs-ok-to-test, size/L

#9523 Upgrade buildroot and kernel minor version
  Makefile
  deploy/iso/minikube-iso/board/coreos/minikube/linux_defconfig
  deploy/iso/minikube-iso/configs/minikube_defconfig
Labels: approved, cncf-cla: yes, size/XS

#9576 Add JSON output to stop, pause and unpause
  cmd/minikube/cmd/pause.go
  cmd/minikube/cmd/start.go
  cmd/minikube/cmd/start_flags.go
  cmd/minikube/cmd/stop.go
  cmd/minikube/cmd/unpause.go
  pkg/minikube/machine/stop.go
  pkg/minikube/out/register/register.go
  site/content/en/docs/commands/pause.md
  site/content/en/docs/commands/stop.md
  site/content/en/docs/commands/unpause.md
  test/integration/json_output_test.go
Labels: approved, cncf-cla: yes, ok-to-test, size/M

#9531 hack/update: golang version
  hack/update/golang_version/update_golang_version.go
Labels: cncf-cla: yes, needs-ok-to-test, size/S
