Repository kubernetes/minikube, pull requests merged in 2020-11, with the labels that each got.

#9592 implement "--log_file" and "--log_dir" for klog
  cmd/minikube/cmd/root.go
  cmd/minikube/main.go
  pkg/initflag/initflag.go
  pkg/minikube/extract/extract.go
  pkg/minikube/translate/translate.go
Labels: approved, cncf-cla: yes, ok-to-test, size/M

#9508 Remove hard-coded list of valid cgroupfs mountpoints to bind mount
  deploy/kicbase/entrypoint
Labels: approved, cncf-cla: yes, ok-to-test, size/S

#9599 jenkins/common.sh: Fix comment typo
  hack/jenkins/common.sh
Labels: cncf-cla: yes, needs-ok-to-test, size/XS

#9597 update klog version to v2.4.0
  go.mod
  go.sum
  site/content/en/docs/commands/addons.md
  site/content/en/docs/commands/cache.md
  site/content/en/docs/commands/completion.md
  site/content/en/docs/commands/config.md
  site/content/en/docs/commands/dashboard.md
  site/content/en/docs/commands/delete.md
  site/content/en/docs/commands/docker-env.md
  site/content/en/docs/commands/help.md
  site/content/en/docs/commands/ip.md
  site/content/en/docs/commands/kubectl.md
  site/content/en/docs/commands/logs.md
  site/content/en/docs/commands/mount.md
  site/content/en/docs/commands/node.md
  site/content/en/docs/commands/pause.md
  site/content/en/docs/commands/podman-env.md
  site/content/en/docs/commands/profile.md
  site/content/en/docs/commands/service.md
  site/content/en/docs/commands/ssh-key.md
  site/content/en/docs/commands/ssh.md
  site/content/en/docs/commands/start.md
  site/content/en/docs/commands/status.md
  site/content/en/docs/commands/stop.md
  site/content/en/docs/commands/tunnel.md
  site/content/en/docs/commands/unpause.md
  site/content/en/docs/commands/update-check.md
  site/content/en/docs/commands/update-context.md
  site/content/en/docs/commands/version.md
Labels: approved, cncf-cla: yes, ok-to-test, size/M

#9611 improve makefile in building kicbase
  Makefile
Labels: approved, cncf-cla: yes, size/S

#9614 fix help flag 'pflag: help requested' error
  cmd/minikube/main.go
Labels: approved, cncf-cla: yes, ok-to-test, size/XS

#9613 Improving log message when profile not found
  pkg/minikube/mustload/mustload.go
  translations/de.json
  translations/es.json
  translations/fr.json
  translations/ja.json
  translations/ko.json
  translations/pl.json
  translations/strings.txt
  translations/zh-CN.json
Labels: approved, cncf-cla: yes, ok-to-test, size/XL

#9587 MEP for adding OpenTelemetry tracing to minikube
  enhancements/proposed/20201030-tracing/README.md
Labels: approved, cncf-cla: yes, size/M

#9536 Add docker.io repo prefix to the dashboard images
  pkg/minikube/bootstrapper/images/images.go
  pkg/minikube/bootstrapper/images/images_test.go
  pkg/minikube/bootstrapper/images/kubeadm_test.go
Labels: approved, cncf-cla: yes, size/S

#9535 Add support for podman v2 to podman-env command
  cmd/minikube/cmd/podman-env.go
  cmd/minikube/cmd/podman-env_test.go
  pkg/minikube/constants/constants.go
Labels: approved, cncf-cla: yes, size/L

#9506 new flag --namespace
  cmd/minikube/cmd/start.go
  cmd/minikube/cmd/start_flags.go
  pkg/minikube/config/types.go
  pkg/minikube/kubeconfig/settings.go
  pkg/minikube/node/start.go
  site/content/en/docs/commands/start.md
Labels: cncf-cla: yes, ok-to-test, size/S

#9604 Bump kicbase on head
  pkg/drivers/kic/types.go
  site/content/en/docs/commands/start.md
Labels: approved, cncf-cla: yes, ok-to-test, size/XS

#9622 Update docs to include --help flag
  site/content/en/docs/commands/addons.md
  site/content/en/docs/commands/cache.md
  site/content/en/docs/commands/completion.md
  site/content/en/docs/commands/config.md
  site/content/en/docs/commands/dashboard.md
  site/content/en/docs/commands/delete.md
  site/content/en/docs/commands/docker-env.md
  site/content/en/docs/commands/help.md
  site/content/en/docs/commands/ip.md
  site/content/en/docs/commands/kubectl.md
  site/content/en/docs/commands/logs.md
  site/content/en/docs/commands/mount.md
  site/content/en/docs/commands/node.md
  site/content/en/docs/commands/pause.md
  site/content/en/docs/commands/podman-env.md
  site/content/en/docs/commands/profile.md
  site/content/en/docs/commands/service.md
  site/content/en/docs/commands/ssh-key.md
  site/content/en/docs/commands/ssh.md
  site/content/en/docs/commands/start.md
  site/content/en/docs/commands/status.md
  site/content/en/docs/commands/stop.md
  site/content/en/docs/commands/tunnel.md
  site/content/en/docs/commands/unpause.md
  site/content/en/docs/commands/update-check.md
  site/content/en/docs/commands/update-context.md
  site/content/en/docs/commands/version.md
Labels: approved, cncf-cla: yes, ok-to-test, size/L

#9632 Update generate-docs test to include --help flag
  cmd/minikube/cmd/generate-docs_test.go
Labels: approved, cncf-cla: yes, ok-to-test, size/XS

#9627 bump iso on head
  Makefile
  site/content/en/docs/commands/start.md
Labels: approved, cncf-cla: yes, ok-to-test, size/XS

#9629 Upgrade cri-o in kicbase to version 1.18.4
  deploy/kicbase/Dockerfile
Labels: approved, cncf-cla: yes, size/S

#9624 Add script to automatically install docker on jenkins machines
  hack/jenkins/common.sh
  hack/jenkins/installers/check_install_docker.sh
  hack/jenkins/installers/check_install_golang.sh
Labels: approved, cncf-cla: yes, ok-to-test, size/M

#9655 bump kic base image to include crio 18 changes
  pkg/drivers/kic/types.go
  site/content/en/docs/commands/start.md
Labels: approved, cncf-cla: yes, ok-to-test, size/XS

#9532 hack/update: kicbase version
  hack/update/kicbase_version/update_kicbase_version.go
Labels: cncf-cla: yes, needs-ok-to-test, size/S

#9534 stop: removed setEventLogPath for stop process
  cmd/minikube/cmd/stop.go
Labels: cncf-cla: yes, ok-to-test, size/XS

#9551 add ImageRepository to addons templates
  deploy/addons/dashboard/dashboard-dp.yaml.tmpl
  deploy/addons/efk/elasticsearch-rc.yaml.tmpl
  deploy/addons/efk/kibana-rc.yaml.tmpl
  deploy/addons/gcp-auth/gcp-auth-webhook.yaml.tmpl
  deploy/addons/gpu/nvidia-driver-installer.yaml.tmpl
  deploy/addons/gpu/nvidia-gpu-device-plugin.yaml.tmpl
  deploy/addons/helm-tiller/helm-tiller-dp.tmpl
  deploy/addons/ingress-dns/ingress-dns-pod.yaml.tmpl
  deploy/addons/ingress/ingress-dp.yaml.tmpl
  deploy/addons/logviewer/logviewer-dp-and-svc.yaml.tmpl
  deploy/addons/metallb/metallb.yaml.tmpl
  deploy/addons/registry-aliases/node-etc-hosts-update.tmpl
  deploy/addons/registry-aliases/patch-coredns-job.tmpl
  deploy/addons/registry-aliases/registry-aliases-config.tmpl
  deploy/addons/registry-creds/registry-creds-rc.yaml.tmpl
  deploy/addons/registry/registry-proxy.yaml.tmpl
  deploy/addons/registry/registry-rc.yaml.tmpl
  deploy/addons/storage-provisioner-gluster/glusterfs-daemonset.yaml.tmpl
  deploy/addons/storage-provisioner-gluster/heketi-deployment.yaml.tmpl
  deploy/addons/volumesnapshots/volume-snapshot-controller-deployment.yaml.tmpl
  pkg/minikube/assets/addons.go
Labels: cncf-cla: yes, needs-ok-to-test, size/M

#9619 remove travis yaml
  .travis.yml
  README.md
Labels: approved, cncf-cla: yes, size/M

#9390 reword error message when cluster state exit code is not found
  cmd/minikube/cmd/status.go
Labels: approved, cncf-cla: yes, ok-to-test, size/XS

#9628 Upgrade crio to 1.18.4
  deploy/iso/minikube-iso/package/crio-bin/crio-bin.hash
  deploy/iso/minikube-iso/package/crio-bin/crio-bin.mk
Labels: approved, cncf-cla: yes, size/XS

#9641 Fix minikube-net network failures for KVM driver
  pkg/drivers/kvm/kvm.go
  pkg/drivers/kvm/network.go
Labels: approved, cncf-cla: yes, ok-to-test, size/L

#9529 hack/update: kubernetes version
  go.mod
  go.sum
  hack/kubernetes_version/update_kubernetes_version.go
  hack/update/filesystem.go
  hack/update/github.go
  hack/update/kubernetes_version/update_kubernetes_version.go
  hack/update/registry.go
  hack/update/update.go
Labels: cncf-cla: yes, needs-ok-to-test, size/XL

#9660 jenkins: docker install script
  hack/jenkins/common.sh
Labels: approved, cncf-cla: yes, ok-to-test, size/XS

#9385 Improve parsing of start flag apiserver-names
  cmd/minikube/cmd/start_flags.go
  site/content/en/docs/commands/start.md
Labels: approved, cncf-cla: yes, ok-to-test, size/XS

#9487 add --watch flag for minikube status with optional interval duration
  cmd/minikube/cmd/status.go
  go.mod
  go.sum
  site/content/en/docs/commands/status.md
Labels: approved, cncf-cla: yes, ok-to-test, size/M

#9665 icrease gh action timeout for macos
  .github/workflows/master.yml
  .github/workflows/pr.yml
Labels: approved, cncf-cla: yes, size/S

#9621 Fix failing TestJSONOutput/start test
  cmd/minikube/cmd/start.go
  pkg/minikube/node/cache.go
  pkg/minikube/out/register/register.go
Labels: approved, cncf-cla: yes, ok-to-test, size/XS

#9676 Don't check for docker.io prefix in docker preload
  pkg/minikube/cruntime/docker.go
  test/integration/pause_test.go
Labels: approved, cncf-cla: yes, ok-to-test, size/S

#9674 Use special credential file location for cloud shell
  pkg/addons/gcpauth/enable.go
Labels: approved, cncf-cla: yes, ok-to-test, size/S

#9675 automatically try install kvm for kvm2 tests
  hack/jenkins/linux_integration_tests_kvm.sh
Labels: approved, cncf-cla: yes, ok-to-test, size/XS

#9503 Implement schedule stop for unix
  cmd/minikube/cmd/stop.go
  go.mod
  go.sum
  pkg/minikube/config/types.go
  pkg/minikube/localpath/localpath.go
  pkg/minikube/reason/reason.go
  pkg/minikube/schedule/daemonize_unix.go
  pkg/minikube/schedule/daemonize_windows.go
  pkg/minikube/schedule/schedule.go
  test/integration/scheduled_stop_test.go
Labels: approved, cncf-cla: yes, ok-to-test, size/L

#9681 fix Test flakes TestAddons/parallel/Registry
  test/integration/addons_test.go
Labels: approved, cncf-cla: yes, size/XS

#9671 Rename `out.T` to `out.Step`
  cmd/minikube/cmd/config/addons_list.go
  cmd/minikube/cmd/config/disable.go
  cmd/minikube/cmd/config/enable.go
  cmd/minikube/cmd/config/open.go
  cmd/minikube/cmd/config/profile.go
  cmd/minikube/cmd/dashboard.go
  cmd/minikube/cmd/delete.go
  cmd/minikube/cmd/generate-docs.go
  cmd/minikube/cmd/mount.go
  cmd/minikube/cmd/node_add.go
  cmd/minikube/cmd/node_delete.go
  cmd/minikube/cmd/node_start.go
  cmd/minikube/cmd/node_stop.go
  cmd/minikube/cmd/pause.go
  cmd/minikube/cmd/service.go
  cmd/minikube/cmd/start.go
  cmd/minikube/cmd/start_flags.go
  cmd/minikube/cmd/stop.go
  cmd/minikube/cmd/unpause.go
  cmd/minikube/cmd/update-context.go
  pkg/addons/addons.go
  pkg/addons/gcpauth/enable.go
  pkg/minikube/bootstrapper/kubeadm/kubeadm.go
  pkg/minikube/browser/browser.go
  pkg/minikube/download/driver.go
  pkg/minikube/download/iso.go
  pkg/minikube/download/preload.go
  pkg/minikube/driver/install.go
  pkg/minikube/logs/logs.go
  pkg/minikube/machine/advice.go
  pkg/minikube/machine/delete.go
  pkg/minikube/machine/fix.go
  pkg/minikube/machine/info.go
  pkg/minikube/machine/start.go
  pkg/minikube/machine/stop.go
  pkg/minikube/mustload/mustload.go
  pkg/minikube/node/cache.go
  pkg/minikube/node/config.go
  pkg/minikube/node/start.go
  pkg/minikube/notify/notify.go
  pkg/minikube/out/out.go
  pkg/minikube/out/out_test.go
  pkg/minikube/service/service.go
  pkg/minikube/tunnel/kic/ssh_conn.go
  site/content/en/docs/contrib/json_output.en.md
Labels: approved, cncf-cla: yes, ok-to-test, size/L

#9679 release latest snapshot image/iso
  Makefile
  pkg/drivers/kic/types.go
  site/content/en/docs/commands/start.md
Labels: approved, cncf-cla: yes, ok-to-test, size/XS

#9693 update kubernetes version
  pkg/minikube/bootstrapper/bsutil/kubeadm_test.go
  pkg/minikube/bootstrapper/bsutil/testdata/v1.20.0-beta.1/containerd-api-port.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.20.0-beta.1/containerd-pod-network-cidr.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.20.0-beta.1/containerd.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.20.0-beta.1/crio-options-gates.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.20.0-beta.1/crio.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.20.0-beta.1/default.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.20.0-beta.1/dns.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.20.0-beta.1/image-repository.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.20.0-beta.1/options.yaml
  pkg/minikube/constants/constants.go
  site/content/en/docs/commands/start.md
Labels: approved, cncf-cla: yes, ok-to-test, size/XL

#9698 release v1.15.0
  CHANGELOG.md
  Makefile
  site/content/en/docs/_index.md
Labels: approved, cncf-cla: yes, ok-to-test, size/M

#9672 Add Support for driver name alias
  cmd/minikube/cmd/start.go
  pkg/minikube/driver/driver.go
  pkg/minikube/registry/drvs/kvm2/kvm2.go
  pkg/minikube/registry/registry.go
  pkg/minikube/registry/registry_test.go
Labels: cncf-cla: yes, ok-to-test, size/M

#9296 Add MEP for dedicated docker driver
  enhancements/proposed/20200921-dedicated-network-kic/dedicated-network-kic.md
Labels: approved, cncf-cla: yes, size/M

#9648 Bug #9607 - Document no support for userns-remap and rootless in Docker driver
  site/content/en/docs/drivers/docker.md
Labels: approved, cncf-cla: yes, needs-ok-to-test, size/XS

#9699 Fix TestScheduledStop flake on KVM
  test/integration/scheduled_stop_test.go
Labels: approved, cncf-cla: yes, ok-to-test, size/XS

#9715 less verbose language selector
  pkg/minikube/out/out_test.go
  pkg/minikube/translate/translate.go
  pkg/minikube/translate/translate_test.go
Labels: cncf-cla: yes, ok-to-test, size/M

#9719 Update Makefile and release notes for 1.15.1 release
  CHANGELOG.md
  Makefile
Labels: approved, cncf-cla: yes, ok-to-test, size/S

#9510 Support non-default docker endpoints
  cmd/minikube/cmd/docker-env.go
  cmd/minikube/cmd/docker-env_test.go
  cmd/minikube/cmd/podman-env_test.go
  pkg/drivers/kic/kic.go
  pkg/drivers/kic/oci/cli_runner.go
  pkg/drivers/kic/oci/env.go
  pkg/drivers/kic/oci/network.go
  pkg/drivers/kic/oci/oci.go
  pkg/drivers/kic/oci/oci_test.go
  pkg/drivers/kic/oci/test
  pkg/minikube/bootstrapper/certs.go
  pkg/minikube/constants/constants.go
  pkg/minikube/driver/driver.go
  pkg/minikube/driver/endpoint.go
  pkg/minikube/shell/shell.go
  pkg/minikube/shell/shell_test.go
  pkg/provision/provision.go
Labels: cncf-cla: yes, ok-to-test, size/L

#9708 hack update: generate unit tests for new k8rs version
  hack/update/filesystem.go
  hack/update/github.go
  hack/update/kubernetes_version/templates/v1beta2/containerd-api-port.yaml
  hack/update/kubernetes_version/templates/v1beta2/containerd-pod-network-cidr.yaml
  hack/update/kubernetes_version/templates/v1beta2/containerd.yaml
  hack/update/kubernetes_version/templates/v1beta2/crio-options-gates.yaml
  hack/update/kubernetes_version/templates/v1beta2/crio.yaml
  hack/update/kubernetes_version/templates/v1beta2/default.yaml
  hack/update/kubernetes_version/templates/v1beta2/dns.yaml
  hack/update/kubernetes_version/templates/v1beta2/image-repository.yaml
  hack/update/kubernetes_version/templates/v1beta2/options.yaml
  hack/update/kubernetes_version/update_kubernetes_version.go
  hack/update/update.go
Labels: approved, cncf-cla: yes, needs-ok-to-test, size/XL

#9713 fix bsutil (kubeadm) unit tests (testdata)
  pkg/minikube/bootstrapper/bsutil/kubeadm_test.go
  pkg/minikube/bootstrapper/bsutil/testdata/v1.20/containerd-api-port.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.20/containerd-pod-network-cidr.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.20/containerd.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.20/crio-options-gates.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.20/crio.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.20/default.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.20/dns.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.20/image-repository.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.20/options.yaml
Labels: cncf-cla: yes, needs-ok-to-test, size/M

#9728 add tag to nvidia-driver-installer addon docker image
  deploy/addons/gpu/nvidia-driver-installer.yaml.tmpl
Labels: cncf-cla: yes, needs-ok-to-test, size/XS

#9689 Implement scheduled stop on windows
  cmd/minikube/cmd/stop.go
  deploy/iso/minikube-iso/package/Config.in
  deploy/iso/minikube-iso/package/scheduled-stop/Config.in
  deploy/iso/minikube-iso/package/scheduled-stop/minikube-scheduled-stop
  deploy/iso/minikube-iso/package/scheduled-stop/minikube-scheduled-stop.service
  deploy/iso/minikube-iso/package/scheduled-stop/scheduled-stop.mk
  deploy/kicbase/Dockerfile
  deploy/kicbase/scheduled-stop/minikube-scheduled-stop
  deploy/kicbase/scheduled-stop/minikube-scheduled-stop.service
  pkg/minikube/constants/constants.go
  pkg/minikube/schedule/daemonize_windows.go
  pkg/minikube/schedule/schedule.go
  test/integration/scheduled_stop_test.go
Labels: approved, cncf-cla: yes, ok-to-test, size/L

#9733 Fix registry-creds addon failure with ImageRepository
  pkg/minikube/assets/addons.go
Labels: cncf-cla: yes, ok-to-test, size/XS

#9742 improve test failure logs for service command
  test/integration/functional_test.go
Labels: approved, cncf-cla: yes, ok-to-test, size/XS

#9746 Updating link to main_test
  site/content/en/docs/contrib/testing.en.md
Labels: cncf-cla: yes, needs-ok-to-test, size/XS

#9751 remove unused tests from pending
  hack/jenkins/minikube_set_pending.sh
Labels: approved, cncf-cla: yes, ok-to-test, size/XS

#9750 make docker installer more extensible
  hack/jenkins/common.sh
  hack/jenkins/installers/check_install_docker.sh
Labels: approved, cncf-cla: yes, ok-to-test, size/S

#9710 convert dockerNetworkInspect to a struct
  pkg/drivers/kic/oci/network_create.go
Labels: cncf-cla: yes, ok-to-test, size/M

#9747 Fix invalid DOCKER_HOST handling in integration tests
  test/integration/aab_offline_test.go
Labels: cncf-cla: yes, ok-to-test, size/XS

#9752 Abbreviate too long filenames to show progress
  pkg/minikube/download/progressbar.go
Labels: approved, cncf-cla: yes, ok-to-test, size/XS

#9755 integration test: fail service test early if can't deploy example svc
  test/integration/functional_test.go
  test/integration/scheduled_stop_test.go
  test/integration/status_test.go
Labels: approved, cncf-cla: yes, ok-to-test, size/XS

#9748 Remove template dependency in addons
  deploy/addons/ambassador/ambassador-operator-crds.yaml.tmpl
  deploy/addons/ambassador/ambassador-operator.yaml.tmpl
  deploy/addons/ambassador/ambassadorinstallation.yaml
  deploy/addons/ambassador/ambassadorinstallation.yaml.tmpl
  deploy/addons/csi-hostpath-driver/deploy/csi-hostpath-attacher.yaml.tmpl
  deploy/addons/csi-hostpath-driver/deploy/csi-hostpath-driverinfo.yaml
  deploy/addons/csi-hostpath-driver/deploy/csi-hostpath-driverinfo.yaml.tmpl
  deploy/addons/csi-hostpath-driver/deploy/csi-hostpath-plugin.yaml.tmpl
  deploy/addons/csi-hostpath-driver/deploy/csi-hostpath-provisioner.yaml.tmpl
  deploy/addons/csi-hostpath-driver/deploy/csi-hostpath-resizer.yaml.tmpl
  deploy/addons/csi-hostpath-driver/deploy/csi-hostpath-snapshotter.yaml.tmpl
  deploy/addons/csi-hostpath-driver/deploy/csi-hostpath-storageclass.yaml
  deploy/addons/csi-hostpath-driver/deploy/csi-hostpath-storageclass.yaml.tmpl
  deploy/addons/csi-hostpath-driver/rbac/rbac-external-attacher.yaml.tmpl
  deploy/addons/csi-hostpath-driver/rbac/rbac-external-provisioner.yaml.tmpl
  deploy/addons/csi-hostpath-driver/rbac/rbac-external-resizer.yaml.tmpl
  deploy/addons/csi-hostpath-driver/rbac/rbac-external-snapshotter.yaml.tmpl
  deploy/addons/gcp-auth/gcp-auth-ns.yaml.tmpl
  deploy/addons/gcp-auth/gcp-auth-service.yaml
  deploy/addons/gcp-auth/gcp-auth-service.yaml.tmpl
  deploy/addons/gcp-auth/gcp-auth-webhook.yaml.tmpl.tmpl
  deploy/addons/gvisor/gvisor-runtimeclass.yaml.tmpl
  deploy/addons/olm/crds.yaml.tmpl
  deploy/addons/olm/olm.yaml.tmpl
  deploy/addons/storage-provisioner-gluster/storage-provisioner-glusterfile.yaml.tmpl
  deploy/addons/volumesnapshots/rbac-volume-snapshot-controller.yaml.tmpl
  deploy/addons/volumesnapshots/snapshot.storage.k8s.io_volumesnapshotclasses.yaml.tmpl
  deploy/addons/volumesnapshots/snapshot.storage.k8s.io_volumesnapshotcontents.yaml.tmpl
  deploy/addons/volumesnapshots/snapshot.storage.k8s.io_volumesnapshots.yaml.tmpl
  pkg/minikube/assets/addons.go
  pkg/minikube/assets/vm_assets.go
Labels: approved, cncf-cla: yes, size/XL

#9764 Remove duplicated if statement in `(p *Profile) IsValid()`.
  pkg/minikube/config/profile.go
Labels: cncf-cla: yes, needs-ok-to-test, size/XS

#9588 Do not auto-select Hyper-V driver if session has no privilege
  pkg/minikube/reason/reason.go
  pkg/minikube/registry/drvs/hyperv/hyperv.go
Labels: cncf-cla: yes, size/M

#9768 remove restart hack for crio now that iso is fixed
  cmd/minikube/cmd/start.go
Labels: approved, cncf-cla: yes, ok-to-test, size/S

#9702 Add number of nodes for cluster in `minikube profile list`
  cmd/minikube/cmd/config/profile_list.go
Labels: cncf-cla: yes, ok-to-test, size/XS

#9756 docker-env: "reload" dockerd service first before "restart" to avoid restarting apiserver container
  cmd/minikube/cmd/docker-env.go
  pkg/minikube/sysinit/openrc.go
  pkg/minikube/sysinit/sysinit.go
  pkg/minikube/sysinit/systemd.go
Labels: approved, cncf-cla: yes, ok-to-test, size/M

#9734 Update ISO and kicbase to include scheduled stop
  Makefile
  pkg/drivers/kic/types.go
  site/content/en/docs/commands/start.md
Labels: approved, cncf-cla: yes, ok-to-test, size/S

#9657 Document minikube kubectl autocompletion
  site/content/en/docs/handbook/kubectl.md
Labels: cncf-cla: yes, needs-ok-to-test, size/XS

#9723 Add OpenTelemetry tracing to minikube
  cmd/minikube/cmd/start.go
  cmd/minikube/cmd/start_flags.go
  go.mod
  go.sum
  pkg/minikube/out/register/register.go
  pkg/trace/gcp.go
  pkg/trace/trace.go
  site/content/en/docs/commands/start.md
  site/content/en/docs/tutorials/telemetry.md
Labels: approved, cncf-cla: yes, ok-to-test, size/L

#9645 ISO: Add buildkit binaries to the ISO installation
  deploy/iso/minikube-iso/package/Config.in
  deploy/iso/minikube-iso/package/buildkit-bin/Config.in
  deploy/iso/minikube-iso/package/buildkit-bin/buildkit-bin.hash
  deploy/iso/minikube-iso/package/buildkit-bin/buildkit-bin.mk
Labels: approved, cncf-cla: yes, ok-to-test, size/S

#9646 KIC: Install buildkit package for use with containerd
  deploy/kicbase/Dockerfile
Labels: approved, cncf-cla: yes, size/S

#9781 fix TestStartStop crio VerifyKubernetesImages serial test
  pkg/minikube/bootstrapper/images/images.go
  test/integration/start_stop_delete_test.go
Labels: cncf-cla: yes, ok-to-test, size/S

#9782 update kicbase and iso images on head
  Makefile
  pkg/drivers/kic/types.go
  site/content/en/docs/commands/start.md
Labels: approved, cncf-cla: yes, ok-to-test, size/S

#9784 reintroduce crio hack for testing
  cmd/minikube/cmd/start.go
Labels: approved, cncf-cla: yes, ok-to-test, size/S

#9775 restart inner docker daemon using systemd
  pkg/provision/buildroot.go
  pkg/provision/ubuntu.go
Labels: approved, cncf-cla: yes, ok-to-test, size/XS

#9783 Update conformance tests for multinode testing
  hack/conformance_tests.sh
Labels: approved, cncf-cla: yes, size/S

#9774 Add --cancel-scheduled flag to cancel all existing scheduled stops
  cmd/minikube/cmd/stop.go
  site/content/en/docs/commands/stop.md
  test/integration/scheduled_stop_test.go
Labels: approved, cncf-cla: yes, ok-to-test, size/M

#9659 Change back to the version-pinned cri-o channel
  deploy/kicbase/Dockerfile
Labels: approved, cncf-cla: yes, size/XS

#9814 Site: Auto detect user OS and default tabs to it
  site/content/en/docs/drivers/vmware.md
  site/content/en/docs/handbook/pushing.md
  site/content/en/docs/start/_index.md
  site/layouts/shortcodes/linuxtab.html
  site/layouts/shortcodes/mactab.html
  site/layouts/shortcodes/windowstab.html
  site/static/js/tabs.js
Labels: approved, cncf-cla: yes, needs-ok-to-test, size/M
