Repository kubernetes/minikube, pull requests merged in 2020-05, with the labels that each got.

#7934 add experimental warning for multinode clusters
  cmd/minikube/cmd/completion.go
  cmd/minikube/cmd/node_add.go
  cmd/minikube/cmd/start.go
Labels: approved, cncf-cla: yes, ok-to-test, size/S

#7927 Very minor grammar corrections to aid readability
  site/content/en/docs/handbook/pushing.md
Labels: cncf-cla: yes, needs-ok-to-test, size/S

#7968 Don't show any podman hint about restarting sudo
  pkg/drivers/kic/oci/cli_runner.go
Labels: approved, cncf-cla: yes, size/XS

#7985 Add kic base image to the cluster config
  cmd/minikube/cmd/start_flags.go
  pkg/minikube/config/types.go
  pkg/minikube/node/cache.go
  pkg/minikube/node/start.go
  pkg/minikube/registry/drvs/docker/docker.go
  pkg/minikube/registry/drvs/podman/podman.go
Labels: approved, cncf-cla: yes, ok-to-test, size/S

#7984 Detect windows container and exit with instructions
  cmd/minikube/cmd/start.go
  pkg/drivers/kic/oci/errors.go
  pkg/drivers/kic/oci/info.go
  pkg/drivers/kic/oci/oci.go
  pkg/minikube/node/start.go
  pkg/minikube/registry/drvs/docker/docker.go
  site/content/en/docs/drivers/docker.md
Labels: approved, cncf-cla: yes, ok-to-test, size/M

#7961 Use the correct binary for unpacking the preload
  pkg/drivers/kic/kic.go
  pkg/drivers/kic/oci/oci.go
  pkg/drivers/kic/oci/volumes.go
Labels: approved, cncf-cla: yes, ok-to-test, size/S

#7962 Get the gateway by inspecting container network
  pkg/drivers/kic/oci/network.go
Labels: approved, cncf-cla: yes, size/S

#7991 Upload cross tars to google storage for release
  Makefile
Labels: approved, cncf-cla: yes, size/XS

#8000 error spam: add raw stdout/stderr if failed
  test/integration/error_spam_test.go
Labels: approved, cncf-cla: yes, size/S

#7999 addons: fix initial retry delay, double maximum limit
  pkg/addons/addons.go
Labels: approved, cncf-cla: yes, size/XS

#7998 Remove sshutil_test - it offers no value
  pkg/minikube/sshutil/sshutil_test.go
Labels: approved, cncf-cla: yes, size/L

#8002 add docker logs to postmortem
  test/integration/helpers.go
  test/integration/pause_test.go
Labels: approved, cncf-cla: yes, ok-to-test, size/S

#7943 docker/podman: add alternative image repo for base image to fallback
  pkg/drivers/kic/types.go
  pkg/minikube/node/cache.go
  pkg/minikube/node/start.go
Labels: approved, cncf-cla: yes, ok-to-test, size/S

#8005 validateIngressAddon: cleanup output, particularly stderr warnings
  test/integration/addons_test.go
Labels: approved, cncf-cla: yes, size/S

#7971 Add unversioned package paths to avoid updating upstream docs each release
  hack/jenkins/release_build_and_upload.sh
Labels: approved, cncf-cla: yes, size/XS

#8010 Add env variable to configure force-systemd
  pkg/minikube/constants/constants.go
  pkg/minikube/node/start.go
  test/integration/docker_test.go
Labels: approved, cncf-cla: yes, ok-to-test, size/M

#7956 TestFunctional/parallel/TunnelCmd into serial subtest
  site/content/en/docs/handbook/accessing.md
  test/integration/fn_tunnel_cmd.go
Labels: area/testing, cncf-cla: yes, kind/cleanup, kind/failing-test, ok-to-test, size/L

#8018 assign proper internal IPs for nodes
  pkg/minikube/bootstrapper/bsutil/kubelet.go
Labels: approved, cncf-cla: yes, ok-to-test, size/XS

#8023 Fix missing node name in minikube stop output
  cmd/minikube/cmd/stop.go
Labels: approved, cncf-cla: yes, ok-to-test, size/XS

#8030 Fix a typo in roadmap document
  site/content/en/docs/contrib/roadmap.en.md
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/XS

#7997 Update ingress-nginx addon
  deploy/addons/ingress-dns/README.md
  deploy/addons/ingress-dns/example/example.yaml
  deploy/addons/ingress/ingress-configmap.yaml.tmpl
  deploy/addons/ingress/ingress-dp.yaml.tmpl
  deploy/addons/ingress/ingress-rbac.yaml.tmpl
  test/integration/addons_test.go
Labels: cncf-cla: yes, ok-to-test, size/XL

#7860 site: add instructions to upgrade hyperkit
  site/content/en/docs/drivers/hyperkit.md
Labels: approved, cncf-cla: yes, size/S

#8022 restart: validate configs with new hostname, add logging
  pkg/minikube/bootstrapper/bsutil/kverify/api_server.go
  pkg/minikube/bootstrapper/kubeadm/kubeadm.go
  test/integration/pause_test.go
Labels: approved, cncf-cla: yes, ok-to-test, size/M

#8027 virtualbox: Quiet initial ssh timeout warning
  pkg/minikube/node/start.go
  test/integration/error_spam_test.go
Labels: approved, cncf-cla: yes, size/XS

#8038 Use the appropriate OCI for deletePossibleKicLeftOver when known
  cmd/minikube/cmd/delete.go
Labels: approved, cncf-cla: yes, ok-to-test, size/M

#8039 Update golangci-lint to v1.26.0 (low priority)
  Makefile
Labels: approved, cncf-cla: yes, size/XS

#8041 TestFunctional/parallel/ServiceCmd: Add logging
  test/integration/functional_test.go
Labels: approved, cncf-cla: yes, ok-to-test, size/M

#8049 Document that minikube with kubeadm needs 2 CPUs
  site/content/en/docs/start/_index.md
Labels: approved, cncf-cla: yes, size/XS

#8035 Wait to add aliases to /etc/hosts before starting kubelet
  pkg/drivers/kic/kic.go
  pkg/minikube/bootstrapper/kubeadm/kubeadm.go
  pkg/minikube/cluster/pause.go
  pkg/minikube/sysinit/systemd.go
  pkg/minikube/sysinit/systemd_test.go
Labels: approved, cncf-cla: yes, ok-to-test, size/L

#8017 Podman: disable selinux labels when extracting the tarball (permissions error)
  pkg/drivers/kic/oci/volumes.go
Labels: cncf-cla: yes, ok-to-test, size/S

#8064 Docs: podman-remote is also called podman
  site/content/en/docs/handbook/pushing.md
Labels: approved, cncf-cla: yes, size/M

#8051 Run 'minikube logs' when sub-tests fail, remove some extraneous logging
  test/integration/aaa_download_only_test.go
  test/integration/addons_test.go
  test/integration/fn_pvc.go
  test/integration/functional_test.go
  test/integration/helpers.go
  test/integration/pause_test.go
  test/integration/preload_test.go
  test/integration/start_stop_delete_test.go
  test/integration/version_upgrade_test.go
Labels: approved, cncf-cla: yes, ok-to-test, size/L

#8062 Add a PointToHost function for podman as well
  cmd/minikube/cmd/podman-env.go
  cmd/minikube/cmd/podman-env_test.go
  cmd/minikube/cmd/root.go
  pkg/drivers/kic/oci/oci.go
  pkg/minikube/constants/constants.go
  pkg/minikube/machine/fix.go
  site/content/en/docs/commands/podman-env.md
Labels: approved, cncf-cla: yes, ok-to-test, size/M

#8060 The podman cp command is not in podman-remote
  pkg/minikube/command/kic_runner.go
Labels: approved, cncf-cla: yes, ok-to-test, size/S

#8001 podman: Wrap the start command with cgroup manager too
  pkg/drivers/kic/kic.go
  pkg/drivers/kic/oci/oci.go
Labels: approved, cncf-cla: yes, ok-to-test, size/S

#8057 Don't run the extraction tar container for podman
  pkg/drivers/kic/kic.go
Labels: approved, cncf-cla: yes, ok-to-test, size/M

#8053 docker/podman solution message for non-amd64 archs
  pkg/minikube/registry/drvs/docker/docker.go
  pkg/minikube/registry/drvs/podman/podman.go
  site/content/en/docs/drivers/docker.md
  site/content/en/docs/drivers/includes/docker_usage.inc
  site/content/en/docs/drivers/podman.md
Labels: approved, cncf-cla: yes, ok-to-test, size/S

#8073 Missing period character in the error template
  pkg/minikube/node/start.go
Labels: approved, cncf-cla: yes, size/XS

#7959 Use noninteractive sudo when running podman
  cmd/minikube/cmd/delete.go
  pkg/drivers/kic/oci/cli_runner.go
  pkg/minikube/registry/drvs/podman/podman.go
Labels: approved, cncf-cla: yes, ok-to-test, size/M

#8076 fix broken docs link
  site/content/en/docs/drivers/docker.md
  site/content/en/docs/drivers/podman.md
Labels: approved, cncf-cla: yes, size/S

#8075 Release v1.10.0
  CHANGELOG.md
  Makefile
  site/content/en/docs/commands/start.md
Labels: approved, cncf-cla: yes, ok-to-test, size/M

#8071 test: add cache failed load to spam error whitelist
  test/integration/error_spam_test.go
Labels: approved, cncf-cla: yes, size/XS

#8085 release scripts: use dash instead of underscore for latest RPM filename
  hack/jenkins/release_build_and_upload.sh
Labels: approved, cncf-cla: yes, size/XS

#8084 docs: Update screenshot for v1.10.0
  README.md
  site/static/images/screenshot.png
Labels: approved, cncf-cla: yes, size/XS

#8086 Simplify docs redirect page to avoid content flashing
  site/content/en/_index.html
Labels: approved, cncf-cla: yes, size/S

#8094 ControlPaneEndpoint -> ControlPlaneEndpoint
  cmd/minikube/cmd/status.go
  pkg/minikube/bootstrapper/kubeadm/kubeadm.go
  pkg/minikube/driver/endpoint.go
  pkg/minikube/mustload/mustload.go
  pkg/minikube/node/start.go
Labels: approved, cncf-cla: yes, size/S

#8090 Update addons docs to be accurate post addon-manager removal
  site/content/en/docs/contrib/addons.en.md
Labels: approved, cncf-cla: yes, size/L

#8087 docs: Use "_latest" package filenames instead of < latest > tag
  site/config.toml
  site/content/en/docs/contrib/releasing/binaries.md
  site/content/en/docs/start/_index.md
  site/layouts/shortcodes/latest.html
Labels: approved, cncf-cla: yes, size/S

#8103 retrieve virtual switch name from driver object directly
  pkg/minikube/cluster/ip.go
Labels: approved, cncf-cla: yes, ok-to-test, size/S

#8104 make deleting orphaned kics optional
  pkg/minikube/machine/cluster_test.go
  pkg/minikube/machine/delete.go
Labels: approved, cncf-cla: yes, ok-to-test, size/S

#8106 fix virtualbox IP address retrieval
  pkg/minikube/cluster/ip.go
Labels: approved, cncf-cla: yes, ok-to-test, size/XS

#8108 release v1.10.1 for windows regressions
  CHANGELOG.md
  Makefile
  site/content/en/docs/commands/start.md
Labels: approved, cncf-cla: yes, ok-to-test, size/S

#8099 update Kubernetes version to v1.18.2
  pkg/minikube/bootstrapper/bsutil/kubelet_test.go
  pkg/minikube/constants/constants.go
  site/content/en/docs/commands/start.md
Labels: approved, cncf-cla: yes, ok-to-test, size/S

#8109 Release v1.10.1 changelog
  CHANGELOG.md
  Makefile
  pkg/minikube/constants/constants.go
  pkg/minikube/machine/delete.go
  site/content/en/docs/commands/start.md
Labels: approved, cncf-cla: yes, ok-to-test, size/XS

#8111 fix raw version
  Makefile
Labels: approved, cncf-cla: yes, size/XS

#8110 add default versions to preload generation
  hack/preload-images/preload_images.go
Labels: approved, cncf-cla: yes, size/XS

#8140 do not delete generated certs for functional test
  test/integration/functional_test.go
Labels: approved, cncf-cla: yes, ok-to-test, size/XS

#8145 Fix some minor gofmt and golint issues
  cmd/minikube/cmd/start_flags.go
  pkg/generate/rewrite.go
  pkg/minikube/bootstrapper/bsutil/kverify/kverify.go
  pkg/minikube/constants/constants.go
  pkg/minikube/perf/binary.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#8118 Improve handling of VersionPrefix in output
  cmd/minikube/cmd/start.go
Labels: approved, cncf-cla: yes, ok-to-test, size/S

#8024 integration test: break-down TestStartStop to sub-tests
  test/integration/start_stop_delete_test.go
Labels: approved, cncf-cla: yes, ok-to-test, size/L

#8155 do not modify existing config
  cmd/minikube/cmd/start_flags.go
Labels: approved, cncf-cla: yes, ok-to-test, size/M

#8148 docs: Update contributors guide for addons
  site/content/en/docs/contrib/addons.en.md
Labels: cncf-cla: yes, needs-ok-to-test, size/XS

#8032 site: add to FAQ page how to ignore system verification.
  site/content/en/docs/faq/_index.md
Labels: approved, cncf-cla: yes, size/XS

#8117 Don't have to copy environment for podman build
  site/content/en/docs/handbook/pushing.md
Labels: approved, cncf-cla: yes, size/XS

#8174 Bump helm-tiller 2.16.7 and promote tiller ClusterRoleBinding to v1
  deploy/addons/helm-tiller/helm-tiller-dp.tmpl
  deploy/addons/helm-tiller/helm-tiller-rbac.tmpl
Labels: area/addons, cncf-cla: yes, ok-to-test, size/XS

#8092 only copy apiserver certs to control plane
  pkg/minikube/bootstrapper/certs.go
Labels: approved, cncf-cla: yes, ok-to-test, size/XS

#8143 Add defaults subcommand to `minikube config`
  cmd/minikube/cmd/config/config.go
  cmd/minikube/cmd/config/defaults.go
  cmd/minikube/cmd/config/defaults_test.go
  go.sum
  site/content/en/docs/commands/config.md
Labels: approved, cncf-cla: yes, ok-to-test, size/L

#8095 recreate existing control plane node correctly
  cmd/minikube/cmd/start.go
  cmd/minikube/cmd/start_flags.go
  pkg/minikube/download/preload.go
  test/integration/aaa_download_only_test.go
  test/integration/helpers.go
Labels: approved, cncf-cla: yes, ok-to-test, size/M

#8194 add windows tests to github actions
  .github/workflows/master.yml
  .github/workflows/pr.yml
Labels: approved, cncf-cla: yes, size/L

#8169 Check machine name for node restart
  cmd/minikube/cmd/node_start.go
  cmd/minikube/cmd/node_stop.go
Labels: approved, cncf-cla: yes, ok-to-test, size/S

#8197 Switch to hangouts for triage meeting
  site/content/en/docs/contrib/triage.md
Labels: approved, cncf-cla: yes, size/XS

#8208 Avoid image builders to hang on registry port 443
  deploy/addons/registry/registry-svc.yaml.tmpl
Labels: cncf-cla: yes, needs-ok-to-test, size/XS

#8213 Update OWNERS
  OWNERS
Labels: approved, cncf-cla: yes, size/XS

#8201 Improve version output of the runc command
  deploy/iso/minikube-iso/package/runc-master/runc-master.mk
Labels: approved, cncf-cla: yes, size/XS

#8199 Wait for kubernetes components on soft start
  pkg/minikube/node/start.go
Labels: approved, cncf-cla: yes, ok-to-test, size/XS

#8200 site: Update multi node tutorial instructions
  site/content/en/docs/tutorials/multi_node.md
Labels: approved, cncf-cla: yes, size/M

#8198 fix proxy env not being passed to docker engine
  cmd/minikube/cmd/start.go
  cmd/minikube/cmd/start_flags.go
  pkg/minikube/machine/cluster_test.go
  pkg/minikube/machine/start.go
  pkg/minikube/node/start.go
  pkg/minikube/proxy/proxy.go
Labels: approved, cncf-cla: yes, ok-to-test, size/M

#8216 multinode: delete worker volumes for docker driver
  cmd/minikube/cmd/delete.go
  cmd/minikube/cmd/start.go
  pkg/minikube/machine/delete.go
Labels: approved, cncf-cla: yes, ok-to-test, size/S

#8196 Improve documentation for minikube installation via brew
  site/content/en/docs/start/_index.md
Labels: approved, cncf-cla: yes, size/XS

#8168 move node ip save farther down stack
  pkg/minikube/machine/cluster_test.go
  pkg/minikube/machine/fix.go
  pkg/minikube/machine/machine.go
  pkg/minikube/machine/start.go
  pkg/minikube/node/start.go
Labels: approved, cncf-cla: yes, ok-to-test, size/M

#8224 delete docker volumes when deleting a single node
  cmd/minikube/cmd/node_delete.go
  pkg/minikube/node/node.go
  test/integration/multinode_test.go
Labels: approved, cncf-cla: yes, size/M

#8225 exit with usage when need login to image registry
  pkg/minikube/image/image.go
  pkg/minikube/image/types.go
  pkg/minikube/node/cache.go
Labels: approved, cncf-cla: yes, ok-to-test, size/M

#8230 Fixed error parsing old version "latest" or "stable"
  cmd/minikube/cmd/start_flags.go
Labels: cncf-cla: yes, do-not-merge/invalid-commit-message, needs-ok-to-test, size/XS

#8238 allow minikube status to display for one node
  .travis.yml
  cmd/minikube/cmd/node_start.go
  cmd/minikube/cmd/node_stop.go
  cmd/minikube/cmd/ssh.go
  cmd/minikube/cmd/status.go
  pkg/minikube/node/node.go
  site/content/en/docs/commands/status.md
  test/integration/helpers.go
  test/integration/main.go
  test/integration/multinode_test.go
  test/integration/start_stop_delete_test.go
Labels: approved, cncf-cla: yes, ok-to-test, size/L

#8229 kic: explicitly provide the type in inspect commands
  Makefile
  pkg/drivers/kic/oci/network.go
  pkg/drivers/kic/oci/oci.go
  pkg/minikube/cruntime/crio.go
  pkg/minikube/cruntime/cruntime_test.go
  pkg/minikube/cruntime/docker.go
Labels: approved, cncf-cla: yes, ok-to-test, size/M

#8259 Add HostIP implementation for parallels driver
  pkg/minikube/cluster/ip.go
  pkg/minikube/driver/driver_linux.go
Labels: cncf-cla: yes, ok-to-test, size/S

#8129 Addons: add OLM support
  deploy/addons/olm/crds.yaml
  deploy/addons/olm/olm.yaml
  pkg/addons/config.go
  pkg/minikube/assets/addons.go
  test/integration/addons_test.go
Labels: cncf-cla: yes, ok-to-test, size/XXL

#8239 docker-env: restart dockerd inside minikube on failure
  cmd/minikube/cmd/docker-env.go
Labels: approved, cncf-cla: yes, ok-to-test, size/M

#8279 fix parsing kubernetes version flag on an existing minikube
  cmd/minikube/cmd/start_flags.go
Labels: approved, cncf-cla: yes, ok-to-test, size/XS

#8280 Merge TestOlmAddon into TestAddons
  test/integration/addons_test.go
Labels: approved, cncf-cla: yes, ok-to-test, size/M

#8265 integration tests: fix docker-env test in powershell
  test/integration/functional_test.go
Labels: approved, cncf-cla: yes, size/M

#8290 respect native-ssh param properly
  cmd/minikube/cmd/ssh.go
  cmd/minikube/cmd/start.go
  pkg/minikube/machine/cluster_test.go
  pkg/minikube/machine/ssh.go
  test/integration/functional_test.go
Labels: approved, cncf-cla: yes, ok-to-test, size/M

#7973 Make sure multinode clusters can survive restarts
  cmd/minikube/cmd/start.go
  cmd/minikube/cmd/status.go
  pkg/minikube/bootstrapper/bsutil/kverify/api_server.go
  pkg/minikube/bootstrapper/kubeadm/kubeadm.go
  pkg/minikube/cruntime/cruntime.go
  pkg/minikube/machine/cache_images.go
  pkg/minikube/machine/fix.go
  pkg/minikube/machine/start.go
  pkg/minikube/node/start.go
  test/integration/multinode_test.go
Labels: approved, cncf-cla: yes, ok-to-test, size/L

#8161 Add Ambassador Ingress controller as an addon
  deploy/addons/ambassador/ambassador-operator-crds.yaml
  deploy/addons/ambassador/ambassador-operator.yaml
  deploy/addons/ambassador/ambassadorinstallation.yaml
  pkg/addons/config.go
  pkg/minikube/assets/addons.go
  site/content/en/docs/tutorials/ambassador_ingress_controller.md
Labels: cncf-cla: yes, needs-ok-to-test, size/XL

#8305 skip two always failing test on windows and create issue
  .github/workflows/master.yml
  .github/workflows/pr.yml
  test/integration/fn_mount_cmd.go
  test/integration/fn_tunnel_cmd.go
Labels: approved, cncf-cla: yes, size/S

#8307 bump default kubernetes version to 1.18.3
  pkg/minikube/constants/constants.go
  site/content/en/docs/commands/start.md
Labels: approved, cncf-cla: yes, ok-to-test, size/XS

#8154 Upgrade oldest k8s version supported to 1.13
  cmd/minikube/cmd/start.go
  pkg/minikube/constants/constants.go
Labels: approved, cncf-cla: yes, ok-to-test, size/XS

#8308 exit out of the soft start test if we can't find old config
  test/integration/functional_test.go
Labels: approved, cncf-cla: yes, size/XS

#8310 add clean up before running windows test
  .github/workflows/pr.yml
Labels: approved, cncf-cla: yes, size/S

#8311 github actions: add clean up to master too
  .github/workflows/master.yml
  .github/workflows/pr.yml
Labels: approved, cncf-cla: yes, size/M

#8320 docker driver: add fall back image in docker hub
  pkg/drivers/kic/kic.go
  pkg/drivers/kic/types.go
  pkg/minikube/node/cache.go
  test/integration/fn_mount_cmd.go
Labels: approved, cncf-cla: yes, size/S

#8317 Update manual instructions for Parallels driver
  site/content/en/docs/drivers/includes/parallels_usage.inc
Labels: approved, cncf-cla: yes, size/XS

#8249 honor --image-repository even if --image-mirror-country is set
  cmd/minikube/cmd/start_flags.go
  cmd/minikube/cmd/start_test.go
Labels: cncf-cla: yes, ok-to-test, size/S

#8297 #8296 Remove old python scripts
  hack/get_k8s_version.py
  hack/prow/run_tests.py
Labels: cncf-cla: yes, needs-ok-to-test, size/L

#8214 add --kvm-qemu-uri option into docs form kvm driver
  site/content/en/docs/drivers/kvm2.md
Labels: cncf-cla: yes, needs-ok-to-test, size/XS

#8091 Add support for timing per log and printing out timings per log to mkcmp
  cmd/performance/mkcmp/cmd/mkcmp.go
  pkg/minikube/perf/logs.go
  pkg/minikube/perf/logs_test.go
  pkg/minikube/perf/result.go
  pkg/minikube/perf/result_manager.go
  pkg/minikube/perf/start.go
  pkg/minikube/perf/start_test.go
Labels: approved, cncf-cla: yes, size/L

#8309 release v1.11.0
  CHANGELOG.md
  Makefile
  site/content/en/docs/commands/start.md
Labels: approved, cncf-cla: yes, ok-to-test, size/M

#8323 Add support for docker driver to mkcmp
  pkg/minikube/perf/result_manager.go
  pkg/minikube/perf/start.go
Labels: approved, cncf-cla: yes, size/S

#8326 Round floats to one decimal point for mkcmp
  pkg/minikube/perf/result_manager.go
  pkg/minikube/perf/start.go
Labels: approved, cncf-cla: yes, size/S
