Repository kubernetes/minikube, pull requests merged in 2020-07, with the labels that each got.

#8621 Disable containerd from starting up at boot
  deploy/iso/minikube-iso/package/containerd-bin/50-minikube.preset
  deploy/iso/minikube-iso/package/containerd-bin/containerd-bin.mk
Labels: approved, cncf-cla: yes, size/XS

#8624 add unit test for docker-env with none shell
  cmd/minikube/cmd/docker-env_test.go
Labels: approved, cncf-cla: yes, size/S

#8623 make docker driver highly preferred
  pkg/minikube/registry/drvs/docker/docker.go
  pkg/minikube/registry/registry.go
Labels: approved, size/S

#8628 ensure deleting failed hosts if --delete-on-failure is specified
  cmd/minikube/cmd/node_add.go
  cmd/minikube/cmd/node_start.go
  cmd/minikube/cmd/start.go
  pkg/minikube/node/node.go
  pkg/minikube/node/start.go
Labels: approved, cncf-cla: yes, ok-to-test, size/M

#8629 add solution message when container create is stuck
  pkg/minikube/problem/err_map.go
Labels: approved, cncf-cla: yes, size/XS

#8630 release v1.12.0-beta1
  CHANGELOG.md
  Makefile
Labels: approved, cncf-cla: yes, ok-to-test, size/M

#8616 Update troubleshooting docs for kvm2
  site/content/en/docs/drivers/kvm2.md
Labels: approved, cncf-cla: yes, size/XS

#8645 Upgrade crio to 1.18.2
  deploy/iso/minikube-iso/board/coreos/minikube/patches/crio-bin/v1.18.1/version.patch
  deploy/iso/minikube-iso/package/crio-bin/crio-bin.hash
  deploy/iso/minikube-iso/package/crio-bin/crio-bin.mk
Labels: approved, cncf-cla: yes, size/M

#8644 Revert "Upgrade podman to 2.0.0"
  deploy/iso/minikube-iso/package/podman/podman.hash
  deploy/iso/minikube-iso/package/podman/podman.mk
Labels: approved, cncf-cla: yes, size/XS

#8643 Upgrade Docker, from 19.03.11 to 19.03.12
  deploy/iso/minikube-iso/package/docker-bin/docker-bin.hash
  deploy/iso/minikube-iso/package/docker-bin/docker-bin.mk
Labels: approved, cncf-cla: yes, size/XS

#8649 WIP: Revert Buildroot version from 2020.02 to 2019.02
  Makefile
  deploy/iso/minikube-iso/configs/minikube_defconfig
  deploy/iso/minikube-iso/package/hyperv-daemons/hyperv-daemons.mk
Labels: approved, cncf-cla: yes, do-not-merge/work-in-progress, size/S

#8653 Revert "The config flag for go packages were both changed"
  deploy/iso/minikube-iso/package/cni-plugins/Config.in
  deploy/iso/minikube-iso/package/cni/Config.in
  deploy/iso/minikube-iso/package/conmon/Config.in
  deploy/iso/minikube-iso/package/containerd-bin/Config.in
  deploy/iso/minikube-iso/package/crio-bin/Config.in
  deploy/iso/minikube-iso/package/crio-bin/conmon-config.h
  deploy/iso/minikube-iso/package/crio-bin/crio-bin.hash
  deploy/iso/minikube-iso/package/crio-bin/crio-bin.mk
  deploy/iso/minikube-iso/package/crio-bin/crio.conf
  deploy/iso/minikube-iso/package/crio-bin/crio.conf.default
  deploy/iso/minikube-iso/package/podman/Config.in
  deploy/iso/minikube-iso/package/runc-master/Config.in
Labels: approved, cncf-cla: yes, size/L

#8147 add new --extra-config option "scheduler"
  cmd/minikube/cmd/start.go
  pkg/minikube/bootstrapper/bsutil/extraconfig.go
  pkg/minikube/bootstrapper/bsutil/extraconfig_test.go
  pkg/minikube/bootstrapper/bsutil/kubeadm.go
Labels: cncf-cla: yes, ok-to-test, size/L

#8608 Docs: Clarify steps to get podman running as a driver
  site/content/en/docs/drivers/includes/podman_usage.inc
  site/content/en/docs/drivers/podman.md
Labels: cncf-cla: yes, size/M

#8617 Update docs kvm2 for nested virtualization
  site/content/en/docs/drivers/kvm2.md
Labels: approved, cncf-cla: yes, size/XS

#8678 fixed the unterminated quoted string
  site/content/en/docs/drivers/podman.md
Labels: cncf-cla: yes, ok-to-test, size/XS

#7743 docs: fix link to kubernetes 'pull-image-private-registry'
  site/content/en/docs/handbook/registry.md
Labels: cncf-cla: yes, kind/documentation, needs-ok-to-test, size/XS

#8490 A few cleanup
  Makefile
  cmd/minikube/cmd/root_test.go
  pkg/drivers/common_test.go
  pkg/drivers/hyperkit/network_test.go
  pkg/minikube/bootstrapper/certs_test.go
  pkg/minikube/machine/client_test.go
  pkg/minikube/machine/filesync_test.go
  pkg/minikube/notify/notify_test.go
  pkg/minikube/tests/dir_utils.go
Labels: cncf-cla: yes, ok-to-test, size/M

#8505 Cleanup tempfiles
  pkg/minikube/kubeconfig/context_test.go
  pkg/minikube/kubeconfig/kubeconfig_test.go
  test.sh
Labels: cncf-cla: yes, ok-to-test, size/XS

#8683 github action test: add info to virtualbox test
  .github/workflows/master.yml
  .github/workflows/pr.yml
Labels: approved, cncf-cla: yes, size/M

#8650 bump iso to v1.12.0
  .github/workflows/master.yml
  .github/workflows/pr.yml
  Makefile
  site/content/en/docs/commands/start.md
Labels: approved, cncf-cla: yes, ok-to-test, size/M

#8687 restrict apparmor security opt to docker
  pkg/drivers/kic/oci/oci.go
Labels: approved, cncf-cla: yes, ok-to-test, size/XS

#8686 update changelog for v1.12.0
  CHANGELOG.md
  Makefile
Labels: approved, cncf-cla: yes, ok-to-test, size/M

#8664 none: Fix 'minikube delete' issues when the apiserver is down
  pkg/minikube/bootstrapper/bsutil/kverify/api_server.go
  pkg/util/retry/retry.go
Labels: approved, cncf-cla: yes, ok-to-test, size/XS

#8648 disallow setting profile names with underscore
  cmd/minikube/cmd/config/profile.go
  cmd/minikube/cmd/start.go
  pkg/minikube/config/profile.go
  pkg/minikube/config/profile_test.go
Labels: cncf-cla: yes, needs-ok-to-test, size/M

#8660 Upgrade go version to 1.14.4
  .travis.yml
  Makefile
  hack/jenkins/common.sh
Labels: cncf-cla: yes, ok-to-test, size/S

#8591 Prevent start cmd from logging multiple k8s upgrade messages
  cmd/minikube/cmd/start.go
Labels: cncf-cla: yes, needs-ok-to-test, size/M

#8695 add timeout for kubeadm init
  pkg/drivers/hyperkit/network_test.go
  pkg/minikube/bootstrapper/kubeadm/errors.go
  pkg/minikube/bootstrapper/kubeadm/kubeadm.go
Labels: approved, cncf-cla: yes, size/M

#8684 none CNI: error if portmap plug-in is required but unavailable
  pkg/minikube/cni/flannel.go
  pkg/minikube/cni/kindnet.go
  test/integration/net_test.go
Labels: approved, cncf-cla: yes, size/S

#8585 Do not auto-set extra config that user wishes to override
  cmd/minikube/cmd/start.go
  pkg/minikube/config/extra_options.go
  pkg/minikube/config/extra_options_test.go
Labels: cncf-cla: yes, ok-to-test, size/M

#8676 Add Infof function to out package
  cmd/minikube/cmd/mount.go
  cmd/minikube/cmd/start.go
  pkg/minikube/node/config.go
  pkg/minikube/node/start.go
  pkg/minikube/out/out.go
Labels: approved, cncf-cla: yes, size/M

#8663 Create "Step" and "Info" type for JSON output for minikube start
  cmd/minikube/cmd/start.go
  cmd/minikube/cmd/start_flags.go
  go.mod
  go.sum
  pkg/addons/addons.go
  pkg/minikube/bootstrapper/kubeadm/kubeadm.go
  pkg/minikube/machine/start.go
  pkg/minikube/node/config.go
  pkg/minikube/node/start.go
  pkg/minikube/out/out.go
  pkg/minikube/out/register/cloud_events.go
  pkg/minikube/out/register/json.go
  pkg/minikube/out/register/log.go
  pkg/minikube/out/register/register.go
  pkg/minikube/out/style.go
  site/content/en/docs/commands/start.md
  test/integration/json_output_test.go
Labels: approved, cncf-cla: yes, ok-to-test, size/L

#8710 Add unit tests for register package
  pkg/minikube/out/register/cloud_events.go
  pkg/minikube/out/register/json_test.go
  pkg/minikube/out/register/register_test.go
Labels: approved, cncf-cla: yes, ok-to-test, size/L

#8652 docs: update multi_node.md to specify profile name
  site/content/en/docs/tutorials/multi_node.md
Labels: approved, cncf-cla: yes, needs-ok-to-test, size/XS

#8715 improve advice when driver was auto-selected
  cmd/minikube/cmd/start.go
Labels: approved, cncf-cla: yes, ok-to-test, size/XS

#8721 The podman github project was renamed to podman
  deploy/iso/minikube-iso/package/podman/podman.hash
  deploy/iso/minikube-iso/package/podman/podman.mk
Labels: approved, cncf-cla: yes, size/S

#8705 Update ingress images
  deploy/addons/ingress/ingress-dp.yaml.tmpl
Labels: cncf-cla: yes, needs-ok-to-test, size/XS

#8709 Implement Download and DownloadProgress types for JSON output
  pkg/minikube/download/download.go
  pkg/minikube/download/json_output.go
  pkg/minikube/out/register/json.go
  pkg/minikube/out/register/log.go
Labels: approved, cncf-cla: yes, ok-to-test, size/L

#8576 cache: Only use docker client for docker runtime
  pkg/minikube/machine/cache_images.go
Labels: approved, cncf-cla: yes, ok-to-test, size/S

#8727 gomod: Use tag version for dockerclient
  go.mod
  go.sum
Labels: cncf-cla: yes, ok-to-test, size/XS

#8698 multinode: fix control plane not ready on restart
  pkg/minikube/bootstrapper/kubeadm/kubeadm.go
  pkg/minikube/node/node.go
  pkg/minikube/node/start.go
  test/integration/multinode_test.go
Labels: approved, cncf-cla: yes, ok-to-test, size/L

#8573 Add support for Cilium CNI (--cni=cilium)
  cmd/minikube/cmd/start_flags.go
  pkg/minikube/cni/cilium.go
  pkg/minikube/cni/cni.go
  site/content/en/docs/commands/start.md
  test/integration/net_test.go
Labels: approved, cncf-cla: yes, ok-to-test, size/XL

#8742 TestNetworkPlugins/DNS: Wait longer for DNS to become available
  test/integration/net_test.go
Labels: approved, cncf-cla: yes, ok-to-test, size/XS

#8571 Add support for Calico CNI (--cni=calico)
  cmd/minikube/cmd/start_flags.go
  pkg/minikube/cni/calico.go
  pkg/minikube/cni/cni.go
  site/content/en/docs/commands/start.md
  test/integration/net_test.go
Labels: approved, cncf-cla: yes, ok-to-test, size/XL

#8751 Add 'Start Docker' guidance for /pipe/docker_engine errors
  pkg/minikube/registry/drvs/docker/docker.go
Labels: approved, cncf-cla: yes, size/XS

#8747 add required quote to alias kubectl
  site/content/en/docs/handbook/kubectl.md
Labels: cncf-cla: yes, needs-ok-to-test, size/XS

#8738 Add KicBaseImage to existing config if missing (fixes v1.9.x upgrade)
  cmd/minikube/cmd/start_flags.go
  test/integration/version_upgrade_test.go
Labels: approved, cncf-cla: yes, ok-to-test, size/M

#8741 Fix bugs which prevented upgrades from v1.0+ to v1.12
  cmd/minikube/cmd/start.go
  cmd/minikube/cmd/start_flags.go
  pkg/minikube/config/types.go
  pkg/minikube/localpath/localpath.go
  pkg/minikube/machine/start.go
  test/integration/version_upgrade_test.go
Labels: approved, cncf-cla: yes, ok-to-test, size/L

#8753 Release v1.12.1
  CHANGELOG.md
  Makefile
Labels: approved, cncf-cla: yes, ok-to-test, size/M

#8763 Fix documentation typo
  pkg/drivers/kic/kic.go
Labels: approved, cncf-cla: yes, size/XS

#8776 update roadmap 2020
  go.mod
  site/content/en/docs/contrib/roadmap.en.md
Labels: approved, cncf-cla: yes, size/S

#8777 Make sure to prepare the kic volume after creation
  pkg/drivers/kic/kic.go
  pkg/drivers/kic/oci/oci.go
  pkg/drivers/kic/oci/volumes.go
Labels: approved, cncf-cla: yes, ok-to-test, size/M

#8718 docker/podman: warn if allocated memory is below limit
  .github/workflows/pr.yml
  cmd/minikube/cmd/start.go
  cmd/minikube/cmd/start_flags.go
  pkg/drivers/kic/oci/info.go
  pkg/minikube/driver/driver.go
  pkg/minikube/node/advice.go
Labels: approved, cncf-cla: yes, ok-to-test, size/L

#8581 Generate cri-o container runtime preload tarball
  hack/preload-images/generate.go
  hack/preload-images/preload_images.go
  pkg/minikube/cruntime/containerd.go
  pkg/minikube/cruntime/cri.go
  pkg/minikube/cruntime/crio.go
  pkg/minikube/download/preload.go
Labels: approved, cncf-cla: yes, size/L

#8781 update golang version
  .github/workflows/master.yml
  .github/workflows/pr.yml
  .travis.yml
  Makefile
  hack/jenkins/common.sh
Labels: approved, cncf-cla: yes, ok-to-test, size/S

#8610 Update external-provisioner for storage provisioner for Kubernetes 1.18
  deploy/addons/storage-provisioner/storage-provisioner.yaml.tmpl
  go.mod
  go.sum
  pkg/storage/storage_provisioner.go
Labels: cncf-cla: yes, ok-to-test, size/M

#8794 fix typo
  cmd/minikube/cmd/start_flags.go
Labels: approved, cncf-cla: yes, size/XS

#8786 update gopogh to have sorted test duration
  .github/workflows/master.yml
  .github/workflows/pr.yml
  hack/jenkins/common.sh
Labels: approved, cncf-cla: yes, ok-to-test, size/L

#8586 Support more error messages for container inspect
  pkg/drivers/kic/oci/oci.go
Labels: approved, cncf-cla: yes, size/XS

#8782 regenerate config on retry
  cmd/minikube/cmd/node_add.go
  cmd/minikube/cmd/node_start.go
  cmd/minikube/cmd/start.go
  cmd/minikube/cmd/start_flags.go
Labels: approved, cncf-cla: yes, ok-to-test, size/S

#8588 Use preloaded tarball for cri-o container runtime
  pkg/minikube/cruntime/containerd.go
  pkg/minikube/cruntime/crio.go
Labels: approved, cncf-cla: yes, ok-to-test, size/S

#8682 Automated GCP Credentials Addon Prototype
  deploy/addons/gcp-auth/gcp-auth-ns.yaml
  deploy/addons/gcp-auth/gcp-auth-service.yaml
  deploy/addons/gcp-auth/gcp-auth-webhook.yaml
  go.mod
  go.sum
  pkg/addons/addons.go
  pkg/addons/config.go
  pkg/addons/gcpauth/enable.go
  pkg/kapi/kapi.go
  pkg/minikube/assets/addons.go
  site/content/en/docs/handbook/addons/_index.md
  site/content/en/docs/handbook/addons/gcp-auth.md
Labels: approved, cncf-cla: yes, ok-to-test, size/XL

#8792 (Addons) Create a new command in every retry
  pkg/addons/addons.go
Labels: cncf-cla: yes, ok-to-test, size/XS

#8793 Implement Warning type for JSON output
  pkg/minikube/out/out.go
  pkg/minikube/out/register/json.go
  pkg/minikube/out/register/json_test.go
  pkg/minikube/out/register/log.go
Labels: approved, cncf-cla: yes, ok-to-test, size/M

#8780 Add minimal minikube-automount to the kic image
  Makefile
  hack/images/automount/minikube-automount
  hack/images/automount/minikube-automount.service
  hack/images/kicbase.Dockerfile
Labels: approved, cncf-cla: yes, size/M

#8795 ci: Ensure docker desktop is running in windows
  .github/workflows/master.yml
  .github/workflows/pr.yml
Labels: approved, cncf-cla: yes, size/M

#8778 allow for prefixed interface names for hyperv
  pkg/minikube/cluster/ip.go
Labels: approved, cncf-cla: yes, size/M

#8697 improve applying default service account
  pkg/minikube/bootstrapper/kubeadm/kubeadm.go
Labels: approved, cncf-cla: yes, ok-to-test, size/XS

#8796 Add support for Error type to JSON output
  pkg/minikube/exit/exit.go
  pkg/minikube/out/out.go
  pkg/minikube/out/register/cloud_events.go
  pkg/minikube/out/register/json.go
  pkg/minikube/out/register/json_test.go
  pkg/minikube/out/register/log.go
  pkg/minikube/out/register/register_test.go
  pkg/minikube/problem/problem.go
  pkg/minikube/problem/problem_test.go
  test/integration/json_output_test.go
Labels: approved, cncf-cla: yes, ok-to-test, size/L

#8806 update how to add translations page.
  site/content/en/docs/contrib/translations.md
Labels: cncf-cla: yes, size/XS

#8809 Update OIDC documentation.
  site/content/en/docs/tutorials/openid_connect_auth.md
Labels: cncf-cla: yes, needs-ok-to-test, size/XS

#8737 Use RWMutex instead of Mutex
  pkg/minikube/registry/registry.go
  third_party/go9p/srv_file.go
Labels: cncf-cla: yes, ok-to-test, size/S

#8670 Add SCH_PRIO, SCH_SFQ and CLS_BASIC kernel module to add filter on traffic control
  deploy/iso/minikube-iso/board/coreos/minikube/linux_defconfig
Labels: cncf-cla: yes, ok-to-test, size/XS

#8744 TestErrorSpam: Add overlayfs/docker perf issue to stderrAllow
  test/integration/error_spam_test.go
Labels: approved, cncf-cla: yes, ok-to-test, size/S

#8804 Stop kube-system containers before applying configuration updates
  pkg/minikube/bootstrapper/kubeadm/kubeadm.go
Labels: approved, cncf-cla: yes, ok-to-test, size/S

#8800 Improve json integration test
  cmd/minikube/cmd/start.go
  pkg/minikube/machine/info.go
  pkg/minikube/machine/start.go
  pkg/minikube/node/start.go
  pkg/minikube/out/register/register.go
  site/content/en/docs/contrib/json_output.en.md
  test/integration/json_output_test.go
Labels: approved, cncf-cla: yes, ok-to-test, size/L

#8818 ci: docker check github action continue-on-err
  .github/workflows/master.yml
  .github/workflows/pr.yml
Labels: approved, cncf-cla: yes, size/XS

#8825 Avoid panic: runtime error: invalid memory address or nil pointer der…
  pkg/minikube/exit/exit.go
Labels: approved, cncf-cla: yes, size/S

#8827 Increase maximum container startup wait from 13 seconds to 25 seconds
  pkg/drivers/kic/oci/oci.go
Labels: approved, cncf-cla: yes, size/XS

#8819 ci: test kic image changes in github action
  .github/workflows/kic_image.yml
  .github/workflows/master.yml
  .github/workflows/pr.yml
  Makefile
Labels: approved, cncf-cla: yes, size/L

#8828 kic: Show log excerpt for ErrExitedUnexpectedly, check state within prepareSSH
  pkg/drivers/kic/kic.go
  pkg/drivers/kic/oci/errors.go
  pkg/drivers/kic/oci/oci.go
Labels: approved, cncf-cla: yes, size/M

#8833 ci: don't fail when checking if docker is running
  .github/workflows/master.yml
  .github/workflows/pr.yml
Labels: approved, cncf-cla: yes, size/XS

#8816 Add stress test script
  test/stress/stress.sh
Labels: approved, cncf-cla: yes, size/L

#8779 Add integration test to test against latest skaffold release
  .github/workflows/master.yml
  .github/workflows/pr.yml
  hack/boilerplate/boilerplate.go
  test/integration/skaffold_test.go
  test/integration/testdata/skaffold/README.md
  test/integration/testdata/skaffold/leeroy-app/Dockerfile
  test/integration/testdata/skaffold/leeroy-app/app.go
  test/integration/testdata/skaffold/leeroy-app/kubernetes/deployment.yaml
  test/integration/testdata/skaffold/leeroy-web/Dockerfile
  test/integration/testdata/skaffold/leeroy-web/kubernetes/deployment.yaml
  test/integration/testdata/skaffold/leeroy-web/web.go
  test/integration/testdata/skaffold/skaffold.yaml
Labels: approved, cncf-cla: yes, ok-to-test, size/L

#8745 Add error handling for os.RemoveAll
  pkg/minikube/kubeconfig/kubeconfig_test.go
  test/integration/driver_install_or_update_test.go
Labels: cncf-cla: yes, needs-ok-to-test, size/S

#8784 Warn user for podman2 version
  pkg/minikube/registry/drvs/podman/podman.go
  site/content/en/docs/drivers/podman.md
Labels: cncf-cla: yes, needs-ok-to-test, size/S

#8835 ci: update golang lint version
  Makefile
  hack/preload-images/generate.go
  pkg/drivers/hyperkit/driver.go
  pkg/minikube/bootstrapper/bsutil/ops.go
  test/stress/stress.sh
Labels: approved, cncf-cla: yes, size/S

#8817 restart kubelet if config changes
  pkg/minikube/bootstrapper/kubeadm/kubeadm.go
  pkg/minikube/exit/exit.go
Labels: approved, cncf-cla: yes, ok-to-test, size/XS

#8842 Enabling metrics addon when someone enables dashboard
  cmd/minikube/cmd/config/enable.go
Labels: cncf-cla: yes, needs-ok-to-test, size/XS

#8838 fix doc typo
  cmd/minikube/cmd/config/profile.go
  site/content/en/docs/commands/profile.md
Labels: cncf-cla: yes, needs-ok-to-test, size/XS

#8852 Increase integration target timeout from 60m to 90m
  Makefile
Labels: approved, cncf-cla: yes, size/XS

#8853 don't test gh aciton for ISO changes in PR test
  .github/workflows/master.yml
  .github/workflows/pr.yml
Labels: approved, cncf-cla: yes, size/XS

#8855 Skip irrelevent upgrade-tests when --base-image is passed
  test/integration/version_upgrade_test.go
Labels: approved, cncf-cla: yes, ok-to-test, size/S

#8856 Add repo SECURITY.md
  SECURITY.md
Labels: cncf-cla: yes, size/S

#8854 move dockerfile to a different folder
  .github/workflows/kic_image.yml
  .github/workflows/master.yml
  .github/workflows/pr.yml
  Makefile
  deploy/kicbase/Dockerfile
  deploy/kicbase/automount/minikube-automount
  deploy/kicbase/automount/minikube-automount.service
  deploy/kicbase/entrypoint
  test/integration/aab_offline_test.go
  test/integration/main_test.go
  test/integration/version_upgrade_test.go
Labels: approved, cncf-cla: yes, size/L

#8863 UI: suggest to enable `metric-server` for full feature dashboard addon.
  cmd/minikube/cmd/config/enable.go
Labels: approved, cncf-cla: yes, size/S

#8864 kic entrypoint: retryable update-alternatives, move earlier into execution
  .github/workflows/kic_image.yml
  deploy/kicbase/Dockerfile
  deploy/kicbase/entrypoint
Labels: approved, cncf-cla: yes, size/L

#8871 point to newly released v0.0.1 of gcp-auth-webhook
  deploy/addons/gcp-auth/gcp-auth-webhook.yaml
Labels: approved, cncf-cla: yes, size/XS

#8589 add new method to clean
  cmd/minikube/cmd/config/set_test.go
  cmd/minikube/cmd/delete_test.go
Labels: cncf-cla: yes, ok-to-test, size/S

#8868 status: Add experimental cluster JSON status with state transition support
  cmd/minikube/cmd/delete.go
  cmd/minikube/cmd/pause.go
  cmd/minikube/cmd/start.go
  cmd/minikube/cmd/status.go
  cmd/minikube/cmd/stop.go
  cmd/minikube/cmd/unpause.go
  go.sum
  pkg/minikube/localpath/localpath.go
  pkg/minikube/machine/stop.go
  pkg/minikube/out/out.go
  pkg/minikube/out/register/cloud_events.go
  pkg/minikube/out/register/json.go
  pkg/minikube/out/register/json_test.go
  pkg/minikube/out/register/register.go
  pkg/minikube/out/register/register_test.go
  pkg/minikube/problem/problem_test.go
  site/content/en/docs/commands/status.md
Labels: approved, cncf-cla: yes, ok-to-test, size/XL

#8889 Fix typos in code comments, arguments, and error messages
  hack/boilerplate/boilerplate.go
  pkg/minikube/node/cache.go
  pkg/minikube/out/register/cloud_events.go
Labels: cncf-cla: yes, needs-ok-to-test, size/S

#8880 make base-image respect --image-repository
  pkg/minikube/node/cache.go
Labels: cncf-cla: yes, ok-to-test, size/XS

#8887 virtualbox: improve solution message -> ensure it is in the path #8453
  pkg/minikube/problem/err_map.go
Labels: cncf-cla: yes, needs-ok-to-test, size/XS

#8895 update crio to 1.18.3 and kicbase to ubuntu 20.04
  cmd/minikube/cmd/start.go
  cmd/minikube/cmd/stop.go
  deploy/kicbase/Dockerfile
Labels: approved, cncf-cla: yes, size/M

#8869 Kic base ubuntu2020
  deploy/kicbase/Dockerfile
Labels: approved, cncf-cla: yes, size/S

#8896 Add stopping as a possible state in deleting, change errorf to warningf
  pkg/minikube/out/register/register.go
Labels: approved, cncf-cla: yes, ok-to-test, size/XS

#8899 Upgrade kicbase to v0.0.11
  pkg/drivers/kic/types.go
  site/content/en/docs/commands/start.md
Labels: approved, cncf-cla: yes, ok-to-test, size/XS
