Repository kubernetes/minikube, pull requests merged in 2020-09, with the labels that each got.

#9128 Add namespace to persistent volume path
  pkg/storage/storage_provisioner.go
Labels: approved, cncf-cla: yes, size/XS

#9136 Fix --extra-config for scheduler/controllerManager by removing hardcoded values
  pkg/minikube/bootstrapper/bsutil/ktmpl/v1beta1.go
  pkg/minikube/bootstrapper/bsutil/ktmpl/v1beta2.go
  pkg/minikube/bootstrapper/bsutil/testdata/v1.14/containerd-api-port.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.14/containerd-pod-network-cidr.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.14/containerd.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.14/crio-options-gates.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.14/crio.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.14/default.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.14/dns.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.14/image-repository.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.14/options.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.15/containerd-api-port.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.15/containerd-pod-network-cidr.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.15/containerd.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.15/crio-options-gates.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.15/crio.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.15/default.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.15/dns.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.15/image-repository.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.15/options.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.16/containerd-api-port.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.16/containerd-pod-network-cidr.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.16/containerd.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.16/crio-options-gates.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.16/crio.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.16/default.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.16/dns.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.16/image-repository.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.16/options.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.17/containerd-api-port.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.17/containerd-pod-network-cidr.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.17/containerd.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.17/crio-options-gates.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.17/crio.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.17/default.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.17/dns.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.17/image-repository.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.17/options.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.18/containerd-api-port.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.18/containerd-pod-network-cidr.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.18/containerd.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.18/crio-options-gates.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.18/crio.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.18/default.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.18/dns.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.18/image-repository.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.18/options.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.19/containerd-api-port.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.19/containerd-pod-network-cidr.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.19/containerd.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.19/crio-options-gates.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.19/crio.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.19/default.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.19/dns.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.19/image-repository.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.19/options.yaml
  pkg/minikube/bootstrapper/bsutil/versions.go
Labels: approved, cncf-cla: yes, ok-to-test, size/XL

#9129 Update dashboard to v2.0.3
  deploy/addons/dashboard/dashboard-dp.yaml
  pkg/minikube/bootstrapper/images/images.go
  pkg/minikube/bootstrapper/images/images_test.go
  pkg/minikube/bootstrapper/images/kubeadm_test.go
  pkg/minikube/cruntime/containerd_test.go
Labels: approved, cncf-cla: yes, ok-to-test, size/S

#9148 Improve none usage documentation
  pkg/minikube/reason/known_issues.go
  site/content/en/docs/drivers/includes/none_usage.inc
Labels: approved, cncf-cla: yes, size/M

#9145 Fix incorrect exit code for RsrcInsufficientDarwinDockerMemory
  pkg/minikube/reason/reason.go
Labels: approved, cncf-cla: yes, size/XS

#9109 start: fixed the type value for latest minikube version availability message
  pkg/minikube/notify/notify.go
  pkg/minikube/notify/notify_test.go
Labels: cncf-cla: yes, needs-ok-to-test, size/XS

#8787 fix error usage for the WaitGroup in the pkg addons
  pkg/addons/addons.go
  pkg/addons/addons_test.go
  pkg/minikube/node/start.go
Labels: cncf-cla: yes, needs-ok-to-test, size/XS

#9032 Cleanup tempfiles2
  pkg/addons/addons_test.go
  pkg/minikube/localpath/localpath_test.go
  pkg/minikube/machine/cluster_test.go
Labels: cncf-cla: yes, kind/cleanup, needs-ok-to-test, size/M

#8159 Support for mounting host volumes on start with docker driver
  cmd/minikube/cmd/start_flags.go
  pkg/drivers/kic/kic.go
  pkg/drivers/kic/oci/types.go
  pkg/minikube/config/types.go
  pkg/minikube/node/start.go
  pkg/minikube/registry/drvs/docker/docker.go
  pkg/minikube/registry/drvs/podman/podman.go
Labels: cncf-cla: yes, ok-to-test, size/M

#8839 Bump nginx-ingress-controller
  deploy/addons/ingress/ingress-dp.yaml.tmpl
  pkg/minikube/perf/start.go
Labels: cncf-cla: yes, ok-to-test, size/S

#9062 docker: Choose the appropriate bridge interface when multiple exist
  pkg/drivers/kic/oci/network.go
Labels: cncf-cla: yes, ok-to-test, size/M

#8996 Document prerequisites for testing
  site/content/en/docs/contrib/guide.en.md
  site/content/en/docs/contrib/testing.en.md
Labels: cncf-cla: yes, needs-ok-to-test, size/M

#9139 mkcmp: download artifacts before timing start
  pkg/minikube/perf/start.go
Labels: approved, cncf-cla: yes, size/S

#9019 fix multiple node calico-node not ready
  pkg/minikube/cni/calico.go
Labels: cncf-cla: yes, ok-to-test, size/XS

#8907 respect native-ssh flag
  cmd/minikube/cmd/start.go
  pkg/minikube/machine/ssh.go
Labels: approved, cncf-cla: yes, ok-to-test, size/S

#8872 Running internal kubectl command when minikube is called as 'kubectl'
  cmd/minikube/cmd/root.go
  site/content/en/docs/faq/_index.md
  site/content/en/docs/handbook/kubectl.md
  test/integration/functional_test.go
Labels: cncf-cla: yes, ok-to-test, size/M

#9007 Fix typo in github actions CI tutorial
  site/content/en/docs/tutorials/setup_minikube_in_github_actions.md
Labels: cncf-cla: yes, needs-ok-to-test, size/XS

#9157 start: fixed the type value for kubectl version mismatch to warning
  cmd/minikube/cmd/start.go
Labels: cncf-cla: yes, needs-ok-to-test, size/XS

#9143 Repair kubecontext before checking cluster health
  pkg/minikube/bootstrapper/kubeadm/kubeadm.go
  pkg/minikube/kubeconfig/kubeconfig.go
Labels: approved, cncf-cla: yes, ok-to-test, size/XS

#9160 Cherry-pick docker api fix to go-containerregistry
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, ok-to-test, size/XS

#9151 Bump storage-provisioner version to v3
  Makefile
  pkg/minikube/bootstrapper/images/images_test.go
  pkg/minikube/bootstrapper/images/kubeadm_test.go
  pkg/minikube/cruntime/containerd_test.go
Labels: approved, cncf-cla: yes, ok-to-test, size/S

#9159 Increase preload version to v6
  pkg/minikube/download/preload.go
Labels: approved, cncf-cla: yes, ok-to-test, size/XS

#9162 mkcmp: Better error message if binary does not exist
  pkg/minikube/perf/binary.go
Labels: approved, cncf-cla: yes, size/S

#9164 trim whitespace when setting gcp project id
  pkg/addons/gcpauth/enable.go
Labels: approved, cncf-cla: yes, size/XS

#9144 Remove conflicting & inaccurate Docker Desktop memory warning
  cmd/minikube/cmd/start.go
Labels: approved, cncf-cla: yes, size/XS

#9167 Simplify kubectl advice messaging
  cmd/minikube/cmd/start.go
Labels: approved, cncf-cla: yes, ok-to-test, size/S

#9149 Disable swap in Docker & podman containers
  pkg/drivers/kic/oci/oci.go
Labels: approved, cncf-cla: yes, ok-to-test, size/XS

#9163 docker: Improve overlay module check (behavior & UX)
  cmd/minikube/cmd/start.go
  pkg/minikube/driver/driver.go
  pkg/minikube/registry/drvs/docker/docker.go
Labels: approved, cncf-cla: yes, ok-to-test, size/M

#9166 Revert static IP for docker
  pkg/drivers/kic/kic.go
  pkg/drivers/kic/oci/network.go
  pkg/drivers/kic/oci/oci.go
  pkg/drivers/kic/oci/types.go
Labels: approved, cncf-cla: yes, ok-to-test, size/M

#9168 Fix typos in pl translation
  translations/pl.json
Labels: cncf-cla: yes, needs-ok-to-test, size/M

#9171 release notes: Add v1.13.0
  CHANGELOG.md
Labels: approved, cncf-cla: yes, size/M

#9172 added warning for changing mount configuration with KiC driver on exsting cluster
  cmd/minikube/cmd/start.go
Labels: cncf-cla: yes, needs-ok-to-test, size/S

#9178 exit on existing cluster start with KiC driver mount configuration change
  cmd/minikube/cmd/start.go
  pkg/minikube/reason/reason.go
Labels: cncf-cla: yes, needs-ok-to-test, size/XS

#9177 Refresh known issues map
  pkg/minikube/logs/logs.go
  pkg/minikube/logs/logs_test.go
  pkg/minikube/node/start.go
  pkg/minikube/reason/known_issues.go
  pkg/minikube/reason/match_test.go
Labels: approved, cncf-cla: yes, ok-to-test, size/L

#9170 Update Makefile for 1.13.0 release
  Makefile
  site/content/en/docs/commands/start.md
Labels: approved, cncf-cla: yes, ok-to-test, size/XS

#9182 skip building gvisor and storage provisioner on release for now
  hack/jenkins/release_build_and_upload.sh
Labels: approved, cncf-cla: yes, size/XS

#9185 Update screenshot for v1.13.0 (add 23s timing data too)
  site/static/images/screenshot.png
Labels: approved, cncf-cla: yes, size/XS

#9186 start docs: Mention that pods may initially be !Running
  site/content/en/docs/start/_index.md
Labels: approved, cncf-cla: yes, size/XS

#9180 Update min*Mem constants to use MiB instead of MB
  cmd/minikube/cmd/start_flags.go
Labels: approved, cncf-cla: yes, size/XS

#8904 fixes(#8301): --help: bool flags which default to 'false' yield confusing output
  cmd/minikube/cmd/service.go
  site/content/en/docs/commands/service.md
Labels: cncf-cla: yes, needs-ok-to-test, size/XS

#9121 Add silent rules for less verbose build output
  Makefile
Labels: approved, cncf-cla: yes, size/M

#8858 check kubectl for multinode delete test
  pkg/minikube/bootstrapper/kubeadm/kubeadm.go
  test/integration/multinode_test.go
Labels: approved, cncf-cla: yes, ok-to-test, size/M

#9181 Add Docker Desktop instructions if memory is >minimum but <recommended
  cmd/minikube/cmd/start.go
Labels: approved, cncf-cla: yes, size/S

#9158 Add local image integration test for "cache add"
  test/integration/functional_test.go
Labels: approved, cncf-cla: yes, ok-to-test, size/S

#8922 Upgrade crio to 1.17.3
  deploy/iso/minikube-iso/package/crio-bin/crio-bin.hash
  deploy/iso/minikube-iso/package/crio-bin/crio-bin.mk
Labels: approved, cncf-cla: yes, size/XS

#8831 Set preload=false if not using overlay2 as docker storage driver
  cmd/minikube/cmd/start.go
  pkg/drivers/kic/oci/test
Labels: approved, cncf-cla: yes, ok-to-test, size/S

#9199 point to newest gcp-auth-webhook version
  deploy/addons/gcp-auth/gcp-auth-webhook.yaml
Labels: approved, cncf-cla: yes, size/XS

#9152 fix make extract
  pkg/minikube/extract/extract.go
  translations/de.json
  translations/es.json
  translations/fr.json
  translations/ja.json
  translations/ko.json
  translations/pl.json
  translations/strings.txt
  translations/zh-CN.json
Labels: cncf-cla: yes, do-not-merge/invalid-commit-message, needs-ok-to-test, size/XL

#9220 add HTML report to Makefile and funtional only test
  Makefile
Labels: approved, cncf-cla: yes, size/S

#9211 Docs: update kic base release tagging
  .github/workflows/master.yml
  .github/workflows/pr.yml
  site/content/en/docs/contrib/releasing/binaries.md
Labels: approved, cncf-cla: yes, size/XS

#9256 Avoid setting time for memory assets
  pkg/minikube/command/ssh_runner.go
Labels: approved, cncf-cla: yes, size/XS

#9237 Fix ForwardedPort for podman version 2.0.1 and up
  cmd/minikube/cmd/start.go
  pkg/drivers/kic/oci/network.go
Labels: approved, cncf-cla: yes, size/S

#9233 Fix copy/paste error in virtualbox nic-type help
  cmd/minikube/cmd/start_flags.go
  site/content/en/docs/commands/start.md
  translations/strings.txt
Labels: approved, cncf-cla: yes, size/XS

#9255 Make sure CFS_BANDWIDTH is available for --cpus
  pkg/drivers/kic/oci/oci.go
Labels: approved, cncf-cla: yes, size/S

#9207 Update default Kubernetes release to v1.19.1
  pkg/minikube/bootstrapper/images/images.go
  pkg/minikube/constants/constants.go
  site/content/en/docs/commands/start.md
Labels: approved, cncf-cla: yes, ok-to-test, size/S

#9234 The cri-o repository moved to a separate organization
  site/content/en/docs/handbook/config.md
Labels: approved, cncf-cla: yes, size/XS

#8461 CSI Hostpath Driver & VolumeSnapshots addons
  deploy/addons/csi-hostpath-driver/deploy/csi-hostpath-attacher.yaml
  deploy/addons/csi-hostpath-driver/deploy/csi-hostpath-driverinfo.yaml
  deploy/addons/csi-hostpath-driver/deploy/csi-hostpath-plugin.yaml
  deploy/addons/csi-hostpath-driver/deploy/csi-hostpath-provisioner.yaml
  deploy/addons/csi-hostpath-driver/deploy/csi-hostpath-resizer.yaml
  deploy/addons/csi-hostpath-driver/deploy/csi-hostpath-snapshotter.yaml
  deploy/addons/csi-hostpath-driver/deploy/csi-hostpath-storageclass.yaml
  deploy/addons/csi-hostpath-driver/rbac/rbac-external-attacher.yaml
  deploy/addons/csi-hostpath-driver/rbac/rbac-external-provisioner.yaml
  deploy/addons/csi-hostpath-driver/rbac/rbac-external-resizer.yaml
  deploy/addons/csi-hostpath-driver/rbac/rbac-external-snapshotter.yaml
  deploy/addons/volumesnapshots/rbac-volume-snapshot-controller.yaml
  deploy/addons/volumesnapshots/snapshot.storage.k8s.io_volumesnapshotclasses.yaml
  deploy/addons/volumesnapshots/snapshot.storage.k8s.io_volumesnapshotcontents.yaml
  deploy/addons/volumesnapshots/snapshot.storage.k8s.io_volumesnapshots.yaml
  deploy/addons/volumesnapshots/volume-snapshot-controller-deployment.yaml
  pkg/addons/config.go
  pkg/addons/validations.go
  pkg/minikube/assets/addons.go
  site/content/en/docs/tutorials/volume_snapshots_and_csi.md
  test/integration/addons_test.go
  test/integration/helpers_test.go
  test/integration/testdata/csi-hostpath-driver/pv-pod-restore.yaml
  test/integration/testdata/csi-hostpath-driver/pv-pod.yaml
  test/integration/testdata/csi-hostpath-driver/pvc-restore.yaml
  test/integration/testdata/csi-hostpath-driver/pvc.yaml
  test/integration/testdata/csi-hostpath-driver/snapshot.yaml
  test/integration/testdata/csi-hostpath-driver/snapshotclass.yaml
Labels: cncf-cla: yes, ok-to-test, size/XXL

#9239 Add podman storage warning to match docker
  pkg/minikube/machine/start.go
  pkg/minikube/reason/reason.go
Labels: approved, cncf-cla: yes, size/S

#9218 remove docker hub images from integration tests
  test/integration/functional_test.go
Labels: approved, cncf-cla: yes, size/M

#8918 Add prune docker images instructions
  pkg/minikube/machine/advice.go
Labels: cncf-cla: yes, needs-ok-to-test, size/XS

#9267 Reduce cyclotomic complexity of CreateContainerNode to fix lint
  pkg/drivers/kic/oci/oci.go
Labels: approved, cncf-cla: yes, size/M

#9269 Fix documentation grammar
  site/content/en/docs/contrib/releasing/binaries.md
Labels: approved, cncf-cla: yes, size/XS

#9270 Fix cache functional test
  test/integration/functional_test.go
Labels: approved, cncf-cla: yes, size/XS

#9250 revert native-ssh change for ssh command
  pkg/minikube/machine/ssh.go
Labels: approved, cncf-cla: yes, size/XS

#9263 fix mounting for docker driver in windows
  go.mod
  go.sum
  pkg/drivers/kic/oci/types.go
  pkg/drivers/kic/oci/types_test.go
Labels: approved, cncf-cla: yes, ok-to-test, size/L

#9265 Update DefaultKubernetesVersion to v1.19.2
  pkg/minikube/constants/constants.go
  site/content/en/docs/commands/start.md
Labels: approved, cncf-cla: yes, ok-to-test, size/XS

#9275 Update French translation
  translations/fr.json
Labels: cncf-cla: yes, ok-to-test, size/L

#9276 Update Makefile and release notes for v1.13.1
  CHANGELOG.md
  Makefile
  site/content/en/docs/commands/start.md
Labels: approved, cncf-cla: yes, ok-to-test, size/M

#9281 update-context: Automatically set the context as current/active in ku…
  cmd/minikube/cmd/update-context.go
Labels: cncf-cla: yes, needs-ok-to-test, size/XS

#9291 Add advice for the DRV_CP_ENDPOINT error
  pkg/minikube/node/start.go
  pkg/minikube/reason/reason.go
Labels: approved, cncf-cla: yes, size/S

#9300 Disable base image flag for vm drivers
  cmd/minikube/cmd/start.go
  cmd/minikube/cmd/start_test.go
Labels: cncf-cla: yes, ok-to-test, size/M

#9302 Return ExHostPermission for insufficient config file permissions
  cmd/minikube/cmd/start.go
  pkg/minikube/config/config.go
  pkg/minikube/reason/known_issues.go
  pkg/minikube/reason/reason.go
Labels: cncf-cla: yes, needs-ok-to-test, size/M

#9298 update_kubernetes_version: automate the update of DefaultKubernetesVersion
  go.mod
  go.sum
  hack/kubernetes_version/update_kubernetes_version.go
Labels: cncf-cla: yes, needs-ok-to-test, size/L

#9309 Force dependency on exp to prevent dirty commit release binaries
  cmd/minikube/main.go
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, ok-to-test, size/XS

#9308 Add PR bot code to repo
  Makefile
  cmd/performance/pr-bot/bot.go
  pkg/perf/monitor/constants.go
  pkg/perf/monitor/execute.go
  pkg/perf/monitor/github.go
Labels: approved, cncf-cla: yes, size/L

#8901 Use mebibytes instead of megabytes
  cmd/minikube/cmd/start.go
  pkg/drivers/common.go
  pkg/drivers/common_test.go
  pkg/drivers/kvm/domain.go
  pkg/minikube/machine/info.go
  pkg/util/utils.go
Labels: cncf-cla: yes, ok-to-test, size/M

#9324 give the logs test a little wiggle room
  pkg/minikube/perf/logs_test.go
Labels: approved, cncf-cla: yes, ok-to-test, size/XS

#9321 Remove duplicate command additions
  cmd/minikube/cmd/delete.go
  cmd/minikube/cmd/stop.go
Labels: cncf-cla: yes, kind/bug, ok-to-test, size/XS

#9327 Fix SVG logo file (white/icon)
  images/logo/logo_white.svg
Labels: cncf-cla: yes, needs-ok-to-test, size/XS

#9333 Use newer version of the go-bindata tool
  Makefile
Labels: approved, cncf-cla: yes, size/XS

#9332 Don't trim whitespace while extracting strings
  cmd/minikube/cmd/completion.go
  cmd/minikube/cmd/config/configure.go
  cmd/minikube/cmd/start.go
  pkg/minikube/extract/extract.go
  pkg/minikube/machine/advice.go
  site/content/en/docs/commands/addons.md
  site/content/en/docs/commands/completion.md
  translations/strings.txt
Labels: approved, cncf-cla: yes, size/L

#9345 Fix error in unittest, as pointed out by warning
  pkg/drivers/kic/kic.go
Labels: approved, cncf-cla: yes, size/XS

#9348 Compare fully qualified image names when pulling kic base image
  pkg/minikube/node/cache.go
Labels: approved, cncf-cla: yes, ok-to-test, size/XS

#9346 Run gofmt on code, to avoid modified workspace
  pkg/minikube/out/register/register.go
Labels: approved, cncf-cla: yes, size/S

#9351 Improved file-filter for github-release-assets
  hack/jenkins/release_github_page.sh
Labels: cncf-cla: yes, needs-ok-to-test, size/XS

#9330 Base kicbase directly on ubuntu, without kindbase
  Makefile
  deploy/kicbase/10-network-security.conf
  deploy/kicbase/Dockerfile
  deploy/kicbase/clean-install
Labels: approved, cncf-cla: yes, size/L

#9340 Added target for Windows HTML & switched encoding for Windows Report
  .github/workflows/master.yml
  .github/workflows/pr.yml
  Makefile
Labels: cncf-cla: yes, size/M

#9343 Add 'docker status' check, improve deadline-exceeded error message
  pkg/drivers/kic/oci/cli_runner.go
  pkg/drivers/kic/oci/info.go
  pkg/minikube/registry/drvs/docker/docker.go
Labels: approved, cncf-cla: yes, size/M

#9342 hyperv: Make interface search name match case-insensitive
  pkg/minikube/cluster/ip.go
Labels: approved, cncf-cla: yes, ok-to-test, size/S

#9318 Make sure gcp-auth addon can be enabled on startup
  deploy/addons/gcp-auth/gcp-auth-webhook.yaml
  pkg/addons/addons.go
  pkg/addons/config.go
  pkg/addons/gcpauth/enable.go
  site/content/en/docs/handbook/addons/gcp-auth.md
Labels: approved, cncf-cla: yes, ok-to-test, size/M

#9356 Correct comment typo in delete.go: 'delting'
  pkg/minikube/machine/delete.go
Labels: cncf-cla: yes, needs-ok-to-test, size/XS

#9353 update kicbase image to ubuntu-based
  pkg/drivers/kic/types.go
  site/content/en/docs/commands/start.md
Labels: approved, cncf-cla: yes, ok-to-test, size/XS

#9331 The ISO build doesn't need Go installed on host
  .github/workflows/iso.yml
Labels: approved, cncf-cla: yes, size/XS
