Repository kubernetes/minikube, pull requests merged in 2020-04, with the labels that each got.

#7355 Contributing to the documentation : suggest using latest go version
  site/content/en/docs/Contributing/documentation.en.md
Labels: cncf-cla: yes, needs-ok-to-test, size/XS

#7341 additional documentation context for MINIKUBE env vars vs Kubernetes tools
  site/content/en/docs/Reference/environment_variables.md
Labels: cncf-cla: yes, kind/documentation, needs-ok-to-test, size/XS

#7310 mustload: Replace DriverIP with Forwarded(IP|Port)
  cmd/minikube/cmd/docker-env.go
  cmd/minikube/cmd/ip.go
  cmd/minikube/cmd/logs.go
  cmd/minikube/cmd/mount.go
  cmd/minikube/cmd/podman-env.go
  cmd/minikube/cmd/ssh.go
  cmd/minikube/cmd/update-context.go
  pkg/minikube/mustload/mustload.go
Labels: approved, cncf-cla: yes, ok-to-test, size/L

#7361 Run 'make extract' to update translation samples
  translations/de.json
  translations/es.json
  translations/fr.json
  translations/ja.json
  translations/ko.json
  translations/pl.json
  translations/zh-CN.json
Labels: approved, cncf-cla: yes, size/L

#7356 Use kubectl version --short if --output=json fails
  cmd/minikube/cmd/start.go
Labels: approved, cncf-cla: yes, size/M

#7279 Improve display of host startup errors
  pkg/minikube/exit/exit.go
  pkg/minikube/node/start.go
  pkg/minikube/problem/problem.go
  pkg/minikube/problem/problem_test.go
Labels: approved, cncf-cla: yes, ok-to-test, size/S

#7299 Run dashboard with internal kubectl if not in path
  cmd/minikube/cmd/dashboard.go
  cmd/minikube/cmd/kubectl.go
Labels: approved, cncf-cla: yes, ok-to-test, size/M

#7325 Implement options for the minikube version command
  cmd/minikube/cmd/version.go
Labels: approved, cncf-cla: yes, ok-to-test, size/M

#7363 Extend maximum stop retry from 30s to 120s
  cmd/minikube/cmd/stop.go
Labels: approved, cncf-cla: yes, size/XS

#7294 Improve localpath test coverage
  pkg/minikube/localpath/localpath.go
  pkg/minikube/localpath/localpath_test.go
Labels: cncf-cla: yes, needs-ok-to-test, size/L

#7362 Make live cache pushes non-fatal in case of stop/delete race
  pkg/minikube/machine/cache_images.go
Labels: approved, cncf-cla: yes, ok-to-test, size/M

#7345 add delete-on-failure flag
  cmd/minikube/cmd/node_add.go
  cmd/minikube/cmd/node_start.go
  cmd/minikube/cmd/start.go
  pkg/minikube/node/node.go
  pkg/minikube/node/start.go
Labels: approved, cncf-cla: yes, ok-to-test, size/M

#7384 Run sudo for file display due to umask
  test/integration/functional_test.go
Labels: approved, cncf-cla: yes, ok-to-test, size/XS

#7379 Add rejection reason to 'unable to find driver' error
  cmd/minikube/cmd/start.go
  pkg/minikube/driver/driver.go
  pkg/minikube/driver/driver_test.go
  pkg/minikube/out/style.go
  pkg/minikube/out/style_enum.go
  pkg/minikube/registry/global.go
Labels: approved, cncf-cla: yes, ok-to-test, size/M

#7386 "Point 'none' users toward the more user-friendly 'docker' driver
  pkg/minikube/node/start.go
Labels: approved, cncf-cla: yes, size/XS

#7359 Update some Japanese translations
  translations/de.json
  translations/es.json
  translations/fr.json
  translations/ja.json
  translations/ko.json
  translations/pl.json
  translations/zh-CN.json
Labels: cncf-cla: yes, needs-ok-to-test, size/L

#7360 Correct assumptions for forwarded hostname & IP handling
  cmd/minikube/cmd/docker-env.go
  cmd/minikube/cmd/ip.go
  cmd/minikube/cmd/start.go
  cmd/minikube/cmd/status.go
  cmd/minikube/cmd/update-context.go
  pkg/drivers/none/none.go
  pkg/minikube/bootstrapper/bootstrapper.go
  pkg/minikube/bootstrapper/bsutil/kverify/kverify.go
  pkg/minikube/bootstrapper/kubeadm/kubeadm.go
  pkg/minikube/driver/driver.go
  pkg/minikube/driver/endpoint.go
  pkg/minikube/kubeconfig/context_test.go
  pkg/minikube/kubeconfig/kubeconfig.go
  pkg/minikube/kubeconfig/kubeconfig_test.go
  pkg/minikube/mustload/mustload.go
  pkg/minikube/node/start.go
  test/integration/addons_test.go
  test/integration/cert_options_test.go
  test/integration/functional_test.go
  test/integration/main.go
Labels: approved, cncf-cla: yes, ok-to-test, size/XL

#7382 Move errors and warnings to output to stderr
  cmd/minikube/cmd/config/profile.go
  cmd/minikube/cmd/config/profile_list.go
  cmd/minikube/cmd/config/validations.go
  cmd/minikube/cmd/delete.go
  cmd/minikube/cmd/logs.go
  cmd/minikube/cmd/mount.go
  cmd/minikube/cmd/node_add.go
  cmd/minikube/cmd/service.go
  cmd/minikube/cmd/start.go
  cmd/minikube/cmd/stop.go
  go.mod
  pkg/drivers/kic/oci/oci.go
  pkg/minikube/bootstrapper/kubeadm/kubeadm.go
  pkg/minikube/exit/exit.go
  pkg/minikube/logs/logs.go
  pkg/minikube/machine/fix.go
  pkg/minikube/mustload/mustload.go
  pkg/minikube/node/start.go
  test/integration/functional_test.go
Labels: approved, cncf-cla: yes, ok-to-test, size/M

#7388 none: check for docker and root uid
  pkg/minikube/registry/drvs/none/none.go
Labels: approved, cncf-cla: yes, ok-to-test, size/S

#7390 Update err map for v1.9.x
  pkg/minikube/problem/err_map.go
Labels: approved, cncf-cla: yes, size/L

#7374 fix validate test output for TestFunctional/parallel/NodeLabels
  test/integration/functional_test.go
  test/integration/start_stop_delete_test.go
Labels: approved, cncf-cla: yes, ok-to-test, size/S

#7392 Bump version to v1.9.1
  CHANGELOG.md
  Makefile
Labels: approved, cncf-cla: yes, ok-to-test, size/M

#7393 allow ingress addon for docker/podman drivers only on linux for now
  pkg/addons/addons.go
  site/content/en/docs/Reference/Drivers/docker.md
Labels: approved, cncf-cla: yes, ok-to-test, size/S

#7399 Add example showing how to upgrade k8s version
  site/content/en/docs/Examples/_index.md
Labels: cncf-cla: yes, needs-ok-to-test, size/XS

#7400 v1.9.1: Docs & brew script update
  hack/jenkins/release_update_brew.sh
  site/config.toml
Labels: cncf-cla: yes

#7394 parallelize updating cluster and setting up certs
  pkg/minikube/node/start.go
Labels: approved, cncf-cla: yes, ok-to-test, size/S

#7407 Remove noisy debug statement from logs
  pkg/minikube/driver/driver.go
Labels: approved, cncf-cla: yes, size/XS

#7403 Update Japanese translations
  translations/de.json
  translations/es.json
  translations/fr.json
  translations/ja.json
  translations/ko.json
  translations/pl.json
  translations/zh-CN.json
Labels: cncf-cla: yes, needs-ok-to-test, size/XL

#7375 --wait, wait for more components
  cmd/minikube/cmd/start.go
  pkg/minikube/bootstrapper/bsutil/kverify/api_server.go
  pkg/minikube/bootstrapper/bsutil/kverify/default_sa.go
  pkg/minikube/bootstrapper/bsutil/kverify/kverify.go
  pkg/minikube/bootstrapper/bsutil/kverify/system_pods.go
  pkg/minikube/bootstrapper/kubeadm/kubeadm.go
  pkg/minikube/config/types.go
  pkg/minikube/node/start.go
Labels: approved, cncf-cla: yes, ok-to-test, size/XL

#7398 adjust mysql test on timeout
  .github/workflows/main.yml
  deploy/minikube/release_sanity_test.go
  test/integration/functional_test.go
Labels: approved, cncf-cla: yes, ok-to-test, size/S

#7413 Make node start message easier to translate
  pkg/minikube/node/start.go
  translations/de.json
  translations/es.json
  translations/fr.json
  translations/ja.json
  translations/ko.json
  translations/pl.json
  translations/zh-CN.json
Labels: approved, cncf-cla: yes, size/S

#7410 adjust warn if slow for ps and volume
  pkg/drivers/kic/oci/oci.go
Labels: approved, cncf-cla: yes, ok-to-test, size/S

#7415 Version bump: v1.9.2
  CHANGELOG.md
  Makefile
Labels: approved, cncf-cla: yes, ok-to-test, size/S

#7429 Add some basic documentation string for golint
  pkg/minikube/mustload/mustload.go
Labels: approved, cncf-cla: yes, size/XS

#7430 Update translations files by running extract
  translations/de.json
  translations/es.json
  translations/fr.json
  translations/ja.json
  translations/pl.json
Labels: approved, cncf-cla: yes, size/XS

#7439 Update Japanese translations
  translations/ja.json
Labels: cncf-cla: yes, needs-ok-to-test, size/M

#7443 Docs on how to enable feature gates
  site/content/en/docs/Reference/Configuration/kubernetes.md
Labels: cncf-cla: yes, needs-ok-to-test, size/XS

#7460 add new wait component apps_running
  pkg/minikube/bootstrapper/bsutil/kverify/kverify.go
  pkg/minikube/bootstrapper/bsutil/kverify/system_pods.go
  pkg/minikube/bootstrapper/kubeadm/kubeadm.go
Labels: approved, cncf-cla: yes, ok-to-test, size/L

#7479 docs: Improve Drivers & Docker driver doc
  site/content/en/docs/drivers/_index.md
  site/content/en/docs/drivers/docker.md
Labels: approved, cncf-cla: yes, size/M

#7477 Update Japanese translations
  translations/ja.json
Labels: cncf-cla: yes, needs-ok-to-test, size/M

#7485 docs: Add /docs/contributing compatibility alias
  site/content/en/docs/contrib/_index.md
Labels: approved, cncf-cla: yes, size/XS

#7476 Fix incorrect node name of `minikube status`
  cmd/minikube/cmd/status.go
Labels: cncf-cla: yes, kind/bug, ok-to-test, size/XS

#7471 update push to docker docs
  site/content/en/docs/handbook/pushing.md
Labels: approved, cncf-cla: yes, size/S

#7470 update doc: link to docker-env
  site/content/en/docs/_index.md
Labels: approved, cncf-cla: yes, size/XS

#7484 make post mortem logs easier on the eye
  test/integration/helpers.go
Labels: approved, cncf-cla: yes, ok-to-test, size/S

#7486 CI: change wait for cni
  test/integration/start_stop_delete_test.go
Labels: approved, cncf-cla: yes, ok-to-test, size/XS

#7482 Disable update check for (--interactive|--dry-run), make non-blocking
  cmd/minikube/cmd/start.go
Labels: approved, cncf-cla: yes, ok-to-test, size/S

#7487 github actions: rename podman test to experimental
  .github/workflows/main.yml
Labels: approved, cncf-cla: yes, size/XS

#7425 remove kic overlay network for docker-runtime
  hack/preload-images/generate.go
  hack/preload-images/preload_images.go
  pkg/minikube/bootstrapper/kubeadm/kubeadm.go
Labels: approved, cncf-cla: yes, ok-to-test, size/S

#7489 fix readme link to minikube examples
  README.md
  site/content/en/docs/handbook/controls.md
Labels: cncf-cla: yes, needs-ok-to-test, size/XS

#7449 Behavior change: start with no arguments uses existing cluster config
  cmd/minikube/cmd/flags.go
  cmd/minikube/cmd/start.go
  cmd/minikube/cmd/start_flags.go
  cmd/minikube/cmd/start_test.go
  pkg/minikube/config/config.go
  pkg/minikube/node/start.go
  test/integration/functional_test.go
Labels: approved, cncf-cla: yes, ok-to-test, size/XXL

#7436 Upgrade falco-probe module to version 0.21.0
  deploy/iso/minikube-iso/package/falco-probe/falco-probe.hash
  deploy/iso/minikube-iso/package/falco-probe/falco-probe.mk
Labels: approved, cncf-cla: yes, size/XS

#7495 gopopgh: add copy to clipboard to test results
  .github/workflows/main.yml
  hack/jenkins/common.sh
Labels: approved, cncf-cla: yes, ok-to-test, size/S

#7494 Use SSH runner once SSH is set up in kic
  pkg/minikube/machine/client.go
  pkg/minikube/node/start.go
Labels: approved, cncf-cla: yes, ok-to-test, size/S

#7514 Update Japanese translations
  translations/de.json
  translations/es.json
  translations/fr.json
  translations/ja.json
  translations/ko.json
  translations/pl.json
  translations/zh-CN.json
Labels: cncf-cla: yes, needs-ok-to-test, size/M

#7349 Enable kernel support for transparent huge pages with madvise fixes #5765
  deploy/iso/minikube-iso/board/coreos/minikube/linux_defconfig
Labels: cncf-cla: yes, ok-to-test, size/XS

#7321 MEP: Formalized release schedule
  enhancements/proposed/20200316-release-schedule/schedule-proposal.md
Labels: approved, cncf-cla: yes, size/M, triage/discuss

#7424 do kubeadm post init in parallel
  pkg/minikube/bootstrapper/kubeadm/kubeadm.go
Labels: approved, cncf-cla: yes, ok-to-test, size/M

#7513 Fix typo
  cmd/minikube/cmd/start_flags.go
Labels: cncf-cla: yes, needs-ok-to-test, size/XS

#7528 Update supported k8s versions in docs
  site/content/en/docs/handbook/config.md
Labels: cncf-cla: yes, needs-ok-to-test, size/S

#7508 Fix label for parallels link
  site/content/en/docs/drivers/_index.md
Labels: cncf-cla: yes, needs-ok-to-test, size/XS

#7451 fix validateDriver() to exit() when it detects an error.
  cmd/minikube/cmd/start.go
  translations/de.json
  translations/es.json
  translations/fr.json
  translations/ja.json
  translations/ko.json
  translations/pl.json
  translations/zh-CN.json
Labels: cncf-cla: yes, kind/bug, ok-to-test, size/S

#7532 More updates to the configuration docs
  site/content/en/docs/handbook/config.md
Labels: cncf-cla: yes, needs-ok-to-test, size/S

#7509 Respect driver.FlagDefaults even if --extra-config is set
  cmd/minikube/cmd/start.go
  go.mod
  go.sum
  pkg/minikube/bootstrapper/bsutil/kverify/system_pods.go
Labels: approved, cncf-cla: yes, ok-to-test, size/M

#7527 site: npm audit fix
  site/package-lock.json
Labels: approved, cncf-cla: yes, size/L

#7516 Fix incorrect node name of `minikube start`
  pkg/minikube/node/start.go
Labels: cncf-cla: yes, kind/bug, ok-to-test, size/XS

#7536 site: create comparison table for methods to push img to minikube
  site/content/en/docs/drivers/docker.md
  site/content/en/docs/handbook/pushing.md
Labels: approved, cncf-cla: yes, size/L

#7530 cert sync: ignore 0-byte certs, test for them explicitly
  pkg/minikube/bootstrapper/certs.go
  pkg/minikube/bootstrapper/certs_test.go
  test/integration/functional_test.go
Labels: approved, cncf-cla: yes, ok-to-test, size/L

#7498 improve driver failure message with link to driver docs
  pkg/minikube/registry/drvs/docker/docker.go
Labels: approved, cncf-cla: yes, ok-to-test, size/S

#7490 Extract preloaded tarball as soon as minikube volume is created (2.5s speedup)
  pkg/drivers/kic/kic.go
  pkg/drivers/kic/oci/oci.go
Labels: approved, cncf-cla: yes, ok-to-test, size/M

#7550 Doc fix: use LC_ALL which has priority for system locale instead of LANG
  site/content/en/docs/contrib/translations.md
Labels: cncf-cla: yes, kind/documentation, needs-ok-to-test, size/XS

#6580 Add docker on windows integration tests on github actions
  .github/workflows/main.yml
Labels: cncf-cla: yes, needs-ok-to-test, size/M

#7189 add unit test for pkg/drivers/hyperkit/iso.go
  pkg/drivers/hyperkit/iso_test.go
  pkg/drivers/hyperkit/iso_test.iso
Labels: cncf-cla: yes, needs-ok-to-test, size/M

#7539 none: Add support for OpenRC init (Google CloudShell)
  cmd/minikube/cmd/docker-env.go
  cmd/minikube/cmd/status.go
  hack/preload-images/generate.go
  pkg/drivers/kic/kic.go
  pkg/drivers/none/none.go
  pkg/minikube/bootstrapper/bootstrapper.go
  pkg/minikube/bootstrapper/bsutil/binaries.go
  pkg/minikube/bootstrapper/bsutil/files.go
  pkg/minikube/bootstrapper/bsutil/kverify/system_pods.go
  pkg/minikube/bootstrapper/kubeadm/kubeadm.go
  pkg/minikube/cluster/pause.go
  pkg/minikube/cruntime/containerd.go
  pkg/minikube/cruntime/crio.go
  pkg/minikube/cruntime/cruntime.go
  pkg/minikube/cruntime/cruntime_test.go
  pkg/minikube/cruntime/docker.go
  pkg/minikube/kubelet/kubelet.go
  pkg/minikube/node/start.go
  pkg/minikube/registry/drvs/none/none.go
  pkg/minikube/sysinit/openrc.go
  pkg/minikube/sysinit/sysinit.go
  pkg/minikube/sysinit/systemd.go
Labels: approved, cncf-cla: yes, ok-to-test, size/XL

#7483 Fix broken community links
  README.md
Labels: cncf-cla: yes, needs-ok-to-test, size/XS

#7500 Update error message for the user UI in start.go
  cmd/minikube/cmd/start.go
Labels: cncf-cla: yes, needs-ok-to-test, size/XS

#7523 integration tests: post-mortem disk usage and pod describe
  test/integration/helpers.go
Labels: approved, cncf-cla: yes, ok-to-test, size/S

#7525 start: Parallelize mount, cache push, and addon enablement
  cmd/minikube/cmd/config/addons_list.go
  cmd/minikube/cmd/config/disable.go
  cmd/minikube/cmd/config/enable.go
  cmd/minikube/cmd/config/open.go
  cmd/minikube/cmd/dashboard.go
  pkg/addons/addons.go
  pkg/addons/addons_test.go
  pkg/minikube/assets/addons.go
  pkg/minikube/exit/exit.go
  pkg/minikube/node/config.go
  pkg/minikube/node/start.go
Labels: approved, cncf-cla: yes, ok-to-test, size/L

#7556 Fix spelling
  pkg/drivers/kic/oci/oci.go
Labels: approved, cncf-cla: yes, size/XS

#7557 updating some french translations for minikube start
  site/content/en/docs/contrib/translations.md
  translations/de.json
  translations/es.json
  translations/fr.json
  translations/ja.json
  translations/ko.json
  translations/pl.json
  translations/zh-CN.json
Labels: approved, cncf-cla: yes, size/M

#7502 add experimental multi-node walkthrough to docs
  site/content/en/docs/tutorials/includes/hello-deployment.yaml
  site/content/en/docs/tutorials/includes/hello-svc.yaml
  site/content/en/docs/tutorials/includes/kube-flannel.yaml
  site/content/en/docs/tutorials/multi_node.md
Labels: approved, cncf-cla: yes, size/XL

#7389 fallback to alternate drivers on failure
  cmd/minikube/cmd/node_add.go
  cmd/minikube/cmd/node_start.go
  cmd/minikube/cmd/start.go
  pkg/minikube/exit/exit.go
  pkg/minikube/node/cache.go
  pkg/minikube/node/node.go
  pkg/minikube/node/start.go
  pkg/minikube/out/out.go
Labels: approved, cncf-cla: yes, ok-to-test, size/L

#7553 Fix `minikube delete` output nodename missing with KIC driver
  cmd/minikube/cmd/delete.go
Labels: cncf-cla: yes, kind/bug, kind/cleanup, ok-to-test, size/XS

#7546 Remove obsoleted docs/ directory
  Makefile
  docs/README.md
  docs/accessing_etcd.md
  docs/addons.md
  docs/alternative_runtimes.md
  docs/building_images_within_the_vm.md
  docs/cache.md
  docs/cli_commands.md
  docs/configuring_kubernetes.md
  docs/contributors/README.md
  docs/contributors/adding_an_addon.md
  docs/contributors/adding_driver.md
  docs/contributors/build_guide.md
  docs/contributors/ci_builds.md
  docs/contributors/minikube_iso.md
  docs/contributors/principles.md
  docs/contributors/releasing_minikube.md
  docs/contributors/roadmap.md
  docs/dashboard.md
  docs/debugging.md
  docs/drivers.md
  docs/env_vars.md
  docs/gpu.md
  docs/host_folder_mount.md
  docs/http_proxy.md
  docs/insecure_registry.md
  docs/networking.md
  docs/offline.md
  docs/openid_connect_auth.md
  docs/persistent_volumes.md
  docs/reusing_the_docker_daemon.md
  docs/syncing-files.md
  docs/tunnel.md
  docs/vmdriver-none.md
Labels: cncf-cla: yes, needs-ok-to-test, size/M

#7562 fix broken screenshot link on the README
  README.md
Labels: cncf-cla: yes, size/XS

#7559 make CommandRunner.Copy/Remove consistent across runners
  pkg/addons/addons.go
  pkg/gvisor/enable.go
  pkg/minikube/assets/vm_assets.go
  pkg/minikube/bootstrapper/certs.go
  pkg/minikube/command/command_runner.go
  pkg/minikube/command/exec_runner.go
  pkg/minikube/command/fake_runner.go
  pkg/minikube/command/kic_runner.go
  pkg/minikube/command/ssh_runner.go
  pkg/minikube/machine/filesync_test.go
Labels: approved, cncf-cla: yes, ok-to-test, size/L

#7564 contrib docs: Mention Github's markdown editor
  site/content/en/docs/contrib/documentation.en.md
Labels: cncf-cla: yes, needs-ok-to-test, size/XS

#7551 Double docker driver timeout, use version instead of info
  pkg/minikube/registry/drvs/docker/docker.go
Labels: approved, cncf-cla: yes, ok-to-test, size/M

#7554 Add error to 'Unable to load cached images' message
  pkg/minikube/node/cache.go
  pkg/minikube/node/start.go
Labels: approved, cncf-cla: yes, ok-to-test, size/XS

#7568 binaries: Only stop the kubelet service if it's active
  pkg/minikube/bootstrapper/bsutil/binaries.go
Labels: approved, cncf-cla: yes, ok-to-test, size/XS

#7574 use sudo for du
  test/integration/helpers.go
Labels: approved, cncf-cla: yes, size/XS

#7563 docs: Quick Start v2.0
  site/assets/scss/_variables_project.scss
  site/content/en/docs/handbook/troubleshooting.md
  site/content/en/docs/start/_index.md
  site/content/en/docs/start/includes/post_install.inc
  site/content/en/docs/start/linux.md
  site/content/en/docs/start/macos.md
  site/content/en/docs/start/windows.md
  site/layouts/partials/hooks/head-end.html
  site/static/css/tabs.css
Labels: approved, cncf-cla: yes, size/XL

#7570 improve stop for docker/podman drivers
  pkg/drivers/kic/kic.go
  pkg/minikube/cruntime/cri.go
Labels: approved, cncf-cla: yes, ok-to-test, size/S

#7547 site: add hot tips for pushing images
  site/content/en/docs/handbook/pushing.md
Labels: approved, cncf-cla: yes, size/M

#7572 Make test.sh output non-verbose again
  test.sh
Labels: approved, cncf-cla: yes, size/XS

#7596 fix broken link
  site/content/en/docs/handbook/pushing.md
Labels: cncf-cla: yes, size/XS

#7580 update kicbase image : bump cri-o version
  hack/images/kicbase.Dockerfile
  pkg/drivers/kic/types.go
  test/integration/start_stop_delete_test.go
Labels: approved, cncf-cla: yes, ok-to-test, size/S

#7417 Add test for unexpected stderr or errors
  test/integration/error_spam_test.go
Labels: approved, cncf-cla: yes, ok-to-test, size/M

#7590 cert test flakiness: make write atomic, add log msgs
  pkg/minikube/assets/vm_assets.go
  test/integration/functional_test.go
Labels: approved, cncf-cla: yes, ok-to-test, size/S

#7575 Restart crio after applying the kic overlay (in background)
  pkg/minikube/bootstrapper/kubeadm/kubeadm.go
Labels: approved, cncf-cla: yes, ok-to-test, size/M

#7595 Skip containerd shutdown if Docker is bound to it
  pkg/minikube/cruntime/cruntime.go
  pkg/minikube/cruntime/docker.go
Labels: approved, cncf-cla: yes, ok-to-test, size/S

#7599 Revert "Restart crio after applying the kic overlay (in background)"
  pkg/minikube/bootstrapper/kubeadm/kubeadm.go
Labels: cncf-cla: yes

#7600 Revert "Revert "Restart crio after applying the kic overlay (in background)""
  pkg/minikube/bootstrapper/kubeadm/kubeadm.go
Labels: approved, cncf-cla: yes, ok-to-test, size/M

#7593 Fix broken links on minikube website
  README.md
  site/content/en/docs/_index.md
  site/content/en/docs/faq/_index.md
  site/content/en/docs/handbook/accessing.md
  site/content/en/docs/handbook/config.md
  site/content/en/docs/handbook/deploying.md
  site/content/en/docs/handbook/filesync.md
  site/content/en/docs/handbook/persistent_volumes.md
  site/content/en/docs/tutorials/audit-policy.md
  site/content/en/docs/tutorials/openid_connect_auth.md
Labels: cncf-cla: yes, kind/documentation, needs-ok-to-test, size/M

#7598 Add retry to pause/unpause functions
  pkg/minikube/cluster/pause.go
Labels: approved, cncf-cla: yes, ok-to-test, size/M

#7591 kic: Use SSHRunner by default (20% faster startup)
  cmd/minikube/cmd/delete.go
  cmd/minikube/cmd/logs.go
  pkg/minikube/bootstrapper/kubeadm/kubeadm.go
  pkg/minikube/cluster/cluster.go
  pkg/minikube/command/ssh_runner.go
  pkg/minikube/machine/client.go
  pkg/minikube/machine/start.go
  pkg/minikube/node/start.go
  pkg/minikube/sshutil/sshutil.go
  pkg/provision/provision.go
Labels: approved, cncf-cla: yes, ok-to-test, size/L

#7441 Separate between Docker Desktop and Docker Engine
  site/content/en/docs/drivers/includes/docker_usage.inc
Labels: approved, cncf-cla: yes, size/XS

#7478 Make KIC start message shorter
  pkg/minikube/machine/start.go
Labels: approved, cncf-cla: yes, size/XS

#7615 Add fix for broken link
  site/content/en/docs/contrib/_index.md
Labels: cncf-cla: yes, needs-ok-to-test, size/XS

#7621 [DOCS UPDATE] Update audit-policy.md in pages of tutorial.
  site/content/en/docs/tutorials/audit-policy.md
Labels: cncf-cla: yes, needs-ok-to-test, size/XS

#7629 fix broken link in dashboard doc
  site/content/en/docs/handbook/dashboard.md
Labels: cncf-cla: yes, needs-ok-to-test, size/XS

#7609 Add a note that minikube does not support IPv6 yet
  site/content/en/docs/faq/_index.md
Labels: cncf-cla: yes, kind/documentation, needs-ok-to-test, size/XS

#7649 Add kubeadm requirements to none driver docs page
  site/content/en/docs/drivers/includes/none_usage.inc
Labels: cncf-cla: yes, needs-ok-to-test, size/XS

#7656 clean up logs
  pkg/minikube/machine/fix.go
  pkg/minikube/machine/start.go
  pkg/minikube/machine/stop.go
  pkg/minikube/node/cache.go
  pkg/provision/provision.go
Labels: approved, cncf-cla: yes, ok-to-test, size/S

#7655 test: remove dot from profile names
  test/integration/util.go
Labels: approved, cncf-cla: yes, ok-to-test, size/XS

#7652 github actions: remove some of the not working tests
  .github/workflows/main.yml
Labels: approved, cncf-cla: yes, size/L

#7650 site: SEO large size link to minikube site
  site/content/en/_index.html
Labels: approved, cncf-cla: yes, size/XS

#7668 Make it possible to translate (experimental)
  pkg/minikube/registry/global.go
Labels: approved, cncf-cla: yes, ok-to-test, size/XS

#7635 Validate profile name characters
  cmd/minikube/cmd/config/profile.go
  cmd/minikube/cmd/start.go
  pkg/minikube/config/profile.go
  pkg/minikube/config/profile_test.go
Labels: cncf-cla: yes, needs-ok-to-test, size/M

#7669 clean up temp dir in unit test
  cmd/minikube/cmd/delete_test.go
  pkg/drivers/hyperkit/iso_test.go
  pkg/minikube/download/binary_test.go
  pkg/minikube/extract/extract_test.go
  pkg/minikube/kubeconfig/kubeconfig_test.go
  pkg/minikube/localpath/localpath_test.go
  pkg/minikube/machine/cache_binaries_test.go
  pkg/minikube/machine/client_test.go
  pkg/minikube/machine/filesync_test.go
  pkg/util/crypto_test.go
  test/integration/fn_mount_cmd.go
Labels: approved, cncf-cla: yes, size/L

#7658 unconfine apparmor for kic
  pkg/drivers/kic/oci/oci.go
Labels: approved, cncf-cla: yes, ok-to-test, size/XS

#7619 Add proxy cidr check in order not to access nil address
  pkg/minikube/node/start.go
  pkg/minikube/proxy/proxy.go
  pkg/minikube/proxy/proxy_test.go
Labels: approved, cncf-cla: yes, kind/bug, kind/cleanup, lgtm, ok-to-test, size/M

#7586 Add master node/worker node type to `minikube status`
  cmd/minikube/cmd/status.go
  cmd/minikube/cmd/status_test.go
  site/content/en/docs/commands/status.md
  site/content/en/docs/tutorials/multi_node.md
Labels: cncf-cla: yes, kind/ux, ok-to-test, size/M

#7672 docker/podman: graceful shutdown to avoid stuck containers
  .github/workflows/main.yml
  pkg/drivers/kic/kic.go
  pkg/drivers/kic/oci/oci.go
  pkg/minikube/driver/driver.go
  pkg/minikube/machine/delete.go
  pkg/minikube/machine/stop.go
  test/integration/pause_test.go
Labels: approved, cncf-cla: yes, ok-to-test, size/L

#7687 Fix navbar logo font to match headings
  site/assets/scss/_variables_project.scss
Labels: approved, cncf-cla: yes, size/XS

#7688 Turn stale ClientConfig error into warning
  pkg/minikube/bootstrapper/kubeadm/kubeadm.go
Labels: approved, cncf-cla: yes, size/XS

#7684 Restore the make gotest target for unit tests
  Makefile
Labels: approved, cncf-cla: yes, size/XS

#7686 Add triage meeting info to docs and website
  README.md
  site/content/en/community/_index.md
  site/content/en/docs/contrib/triage.md
Labels: approved, cncf-cla: yes, size/S

#7607 docs: Update formatting on ISO build page
  site/content/en/docs/contrib/building/iso.md
Labels: cncf-cla: yes, needs-ok-to-test, size/XS

#7623 iso build README: fix broken link
  deploy/iso/minikube-iso/README.md
Labels: cncf-cla: yes, needs-ok-to-test, size/XS

#7242 Add digest to image in daemon after pulling it
  pkg/minikube/image/image.go
Labels: approved, cncf-cla: yes, size/S

#7240 fix ci machine for docker on macos
  default.profraw
  hack/jenkins/osx_integration_tests_docker.sh
Labels: approved, cncf-cla: yes, ok-to-test, size/XS

#7694 docker on Linux: Add "Permission Denied" advice
  pkg/minikube/registry/drvs/docker/docker.go
Labels: approved, cncf-cla: yes, size/XS

#7696 Show statistics when extracting the translations
  pkg/minikube/extract/extract.go
Labels: approved, cncf-cla: yes, size/S

#7693 update reference URL for proxies and VPNs
  pkg/minikube/problem/err_map.go
  site/content/en/docs/handbook/vpn_and_proxy.md
Labels: approved, cncf-cla: yes, size/XS

#7690 Log the remote OS also for the KIC drivers
  pkg/minikube/machine/start.go
Labels: approved, cncf-cla: yes, size/XS

#7683 Only show pulling base image when actually pulling
  pkg/minikube/image/image.go
  pkg/minikube/node/cache.go
Labels: approved, cncf-cla: yes, size/S

#7702 fix build error
  pkg/minikube/image/image.go
Labels: cncf-cla: yes, size/XS

#7703 lint
  pkg/minikube/extract/extract.go
Labels: cncf-cla: yes

#7682 Add Windows integration test for Docker
  hack/jenkins/windows_integration_test_docker.ps1
Labels: approved, cncf-cla: yes, ok-to-test, size/M

#7681 Remove hyperv-virtual-switch argument, delete all profiles
  hack/jenkins/windows_integration_test_hyperv.ps1
Labels: approved, cncf-cla: yes, ok-to-test, size/XS

#7705 Improve reliability of cluster role binding creation for containerd/cri-o
  pkg/minikube/bootstrapper/kubeadm/kubeadm.go
Labels: approved, cncf-cla: yes, ok-to-test, size/M

#7722 add test for second start no reset
  pkg/minikube/bootstrapper/kubeadm/kubeadm.go
  test/integration/pause_test.go
Labels: approved, cncf-cla: yes, size/S

#7558 Add support for specifying pr when running mkcmp
  cmd/performance/mkcmp/cmd/mkcmp.go
  pkg/minikube/perf/binary.go
  pkg/minikube/perf/start.go
  pkg/minikube/perf/start_test.go
Labels: approved, cncf-cla: yes, size/L

#7565 Increase host creation timeout
  pkg/minikube/machine/start.go
Labels: approved, cncf-cla: yes, ok-to-test, size/XS

#7717 Fix update-context in order to recover kubeconfig even if it's missing
  pkg/minikube/kubeconfig/kubeconfig.go
Labels: cncf-cla: yes, kind/bug, ok-to-test, size/M

#7726 use wait.poll for waiting on default sa
  cmd/minikube/cmd/dashboard.go
  pkg/addons/addons.go
  pkg/minikube/bootstrapper/bsutil/kverify/default_sa.go
  pkg/minikube/bootstrapper/kubeadm/kubeadm.go
  pkg/provision/buildroot.go
  pkg/provision/ubuntu.go
Labels: approved, cncf-cla: yes, ok-to-test, size/S

#7729 improve kic start and kill
  pkg/drivers/kic/kic.go
  pkg/drivers/kic/oci/oci.go
Labels: approved, cncf-cla: yes, ok-to-test, size/M

#7713 Add Docker for Windows to pending job list
  hack/jenkins/minikube_set_pending.sh
Labels: approved, cncf-cla: yes, ok-to-test, size/XS

#7732 TestErrorSpam: Whitelist docker performance suggestion
  test/integration/error_spam_test.go
Labels: approved, cncf-cla: yes, ok-to-test, size/S
