Repository kubernetes/minikube, pull requests merged in 2020-01, with the labels that each got.

#6188 Update hyperkit.md (fix typo)
  site/content/en/docs/Reference/Drivers/hyperkit.md
Labels: cncf-cla: yes, needs-ok-to-test, size/XS

#6176 update zh translation
  translations/zh-CN.json
Labels: cncf-cla: yes, ok-to-test, size/L

#6183 Add systemd patch for booting on AMD Ryzen
  deploy/iso/minikube-iso/board/coreos/minikube/patches/systemd/240/rdrand-workaround-on-amd.patch
  deploy/iso/minikube-iso/configs/minikube_defconfig
Labels: approved, cncf-cla: yes, ok-to-test, size/M

#6191 Fix a typo 'the the' -> 'the'
  pkg/minikube/command/kic_runner.go
Labels: cncf-cla: yes, ok-to-test, size/XS

#6199 Upgrade buildroot minor version
  Makefile
  deploy/iso/minikube-iso/package/hyperv-daemons/hyperv-daemons.mk
Labels: approved, cncf-cla: yes, ok-to-test, size/XS

#6215 Remove duplicated words
  pkg/minikube/registry/registry.go
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/XS

#6207 Minor: change assignment to declaration
  cmd/minikube/cmd/update-context.go
Labels: approved, cncf-cla: yes, size/XS

#6124 Enable or disable addons per profile
  cmd/minikube/cmd/config/config.go
  cmd/minikube/cmd/config/disable.go
  cmd/minikube/cmd/config/disable_test.go
  cmd/minikube/cmd/config/enable.go
  cmd/minikube/cmd/config/enable_test.go
  cmd/minikube/cmd/config/util.go
  cmd/minikube/cmd/config/util_test.go
  cmd/minikube/cmd/config/validations.go
  cmd/minikube/cmd/dashboard.go
  cmd/minikube/cmd/start.go
  pkg/addons/addons.go
  pkg/addons/addons_test.go
  pkg/addons/config.go
  pkg/addons/validations.go
  pkg/addons/validations_test.go
  pkg/minikube/assets/addons.go
  pkg/minikube/config/config.go
  pkg/minikube/config/types.go
  pkg/minikube/tunnel/test_doubles.go
  test/integration/addons_test.go
  test/integration/gvisor_addon_test.go
Labels: approved, cncf-cla: yes, ok-to-test, size/XXL

#6224 Add unit test for cmd/minikube/cmd/config/set.go
  cmd/minikube/cmd/config/set_test.go
Labels: cncf-cla: yes, needs-ok-to-test, size/S

#6218 Improve reportcard by refactoring and commenting
  cmd/minikube/cmd/start.go
  pkg/minikube/cluster/cluster.go
  pkg/minikube/localpath/localpath.go
Labels: approved, cncf-cla: yes, ok-to-test, size/M

#6214 Fixes IPv6 address handling in kubeadm
  pkg/minikube/bootstrapper/kubeadm/kubeadm.go
Labels: cncf-cla: yes, ok-to-test, size/XS

#6208 Upgrade podman to 1.6.4
  deploy/iso/minikube-iso/package/podman/podman.hash
  deploy/iso/minikube-iso/package/podman/podman.mk
Labels: approved, cncf-cla: yes, ok-to-test, size/XS

#6217 Add unit test for cmd/minikube/cmd/config/get.go
  cmd/minikube/cmd/config/get_test.go
Labels: cncf-cla: yes, needs-ok-to-test, size/M

#6209 Fix the version number output of runc
  deploy/iso/minikube-iso/package/runc-master/runc-master.mk
Labels: approved, cncf-cla: yes, size/S

#6212 Docs: Refer links to ingress-minikube
  README.md
Labels: cncf-cla: yes, size/XS

#6210 Upgrade crio to 1.16.1
  deploy/iso/minikube-iso/package/crio-bin/crio-bin.hash
  deploy/iso/minikube-iso/package/crio-bin/crio-bin.mk
Labels: approved, cncf-cla: yes, ok-to-test, size/XS

#6193 kic/oci: parse all kind of states
  pkg/drivers/kic/oci/oci.go
Labels: cncf-cla: yes, needs-ok-to-test, size/XS

#6230 lint change if to swtich
  pkg/drivers/kic/kic.go
  pkg/drivers/kic/oci/oci.go
Labels: cncf-cla: yes, needs-ok-to-test, size/M

#6175 pkg/drivers/kic/oci: delete TODO info
  pkg/drivers/kic/oci/oci.go
Labels: cncf-cla: yes, ok-to-test, size/XS

#6235 Rebuild docker images for each release
  hack/jenkins/release_build_and_upload.sh
Labels: approved, cncf-cla: yes, size/S

#6234 Fixes busybox nslookup does not support query type
  cmd/minikube/cmd/start.go
Labels: cncf-cla: yes, ok-to-test, size/XS

#6244 Set CGO_ENABLED=0 when building the storage-provisioner
  Makefile
Labels: approved, cncf-cla: yes, size/XS

#6248 proxy_test: improve TestIsValidEnv unit test
  pkg/minikube/proxy/proxy_test.go
Labels: cncf-cla: yes, needs-ok-to-test, size/XS

#6240 Fix inverted logic for showing issue link
  pkg/minikube/exit/exit.go
Labels: approved, cncf-cla: yes, size/XS

#6259 Create explicit var to avoid incorrect loop iterator reference
  test/integration/aab_offline_test.go
Labels: approved, cncf-cla: yes, size/XS

#6119 Address low-hanging integration timeout & image list issues
  test/integration/docker_test.go
  test/integration/fn_tunnel_cmd.go
  test/integration/functional_test.go
  test/integration/main.go
  test/integration/start_stop_delete_test.go
Labels: approved, cncf-cla: yes, ok-to-test, size/M

#6260 De-parallelize GetServiceURL unit tests: the mocks are not thread safe
  pkg/minikube/service/service_test.go
Labels: approved, cncf-cla: yes, size/XS

#6261 ssh_mock: Copy buffer to avoid data race
  pkg/minikube/tests/ssh_mock.go
Labels: approved, cncf-cla: yes, size/XS

#6241 Disable IPv6 in the minikube VM until it can be properly supported
  deploy/iso/minikube-iso/board/coreos/minikube/rootfs-overlay/etc/sysctl.d/disable-ipv6.conf
Labels: approved, cncf-cla: yes, ok-to-test, size/XS

#6242 Only print the virtualization system if it exists
  cmd/minikube/cmd/start.go
Labels: approved, cncf-cla: yes, ok-to-test, size/XS

#6258 Replace integration-test hacks with mutex locks around shared resources
  pkg/minikube/cluster/cluster.go
  pkg/minikube/driver/install.go
  pkg/minikube/image/cache.go
  pkg/util/downloader.go
  test/integration/aab_offline_test.go
  test/integration/addons_test.go
  test/integration/docker_test.go
  test/integration/guest_env_test.go
  test/integration/gvisor_addon_test.go
  test/integration/helpers.go
  test/integration/main.go
  test/integration/start_stop_delete_test.go
  test/integration/version_upgrade_test.go
Labels: approved, cncf-cla: yes, ok-to-test, size/L

#6289 Securing many http links to https links
  site/config.toml
  site/content/en/docs/Contributing/documentation.en.md
  site/content/en/docs/Contributing/guide.en.md
  site/content/en/docs/Tutorials/nvidia_gpu.md
Labels: cncf-cla: yes, size/S

#6276 Pass --kvm-qemu-uri value into kvm2 health check
  cmd/minikube/cmd/start.go
  pkg/minikube/driver/driver.go
  pkg/minikube/registry/drvs/kvm2/kvm2.go
Labels: approved, cncf-cla: yes, ok-to-test, size/S

#6294 Move away from go.mod when installing gopogh tool
  hack/jenkins/common.sh
Labels: approved, cncf-cla: yes, ok-to-test, size/XS

#6295 Fix some minor issues from gofmt and golint
  pkg/addons/addons.go
  pkg/minikube/config/config.go
  test/integration/guest_env_test.go
Labels: approved, cncf-cla: yes, size/XS

#6292 Handle empty k8s version in existing profile
  cmd/minikube/cmd/start.go
Labels: approved, cncf-cla: yes, ok-to-test, size/XS

#6256 Add --dry-run option to start
  cmd/minikube/cmd/start.go
  pkg/minikube/out/style.go
  pkg/minikube/out/style_enum.go
  test/integration/functional_test.go
Labels: approved, cncf-cla: yes, ok-to-test, size/M

#6220 Use absolute path, when calling the crictl command
  pkg/minikube/cruntime/containerd.go
  pkg/minikube/cruntime/cri.go
  pkg/minikube/cruntime/crio.go
  pkg/minikube/cruntime/cruntime.go
  pkg/minikube/cruntime/cruntime_test.go
  pkg/minikube/logs/logs.go
Labels: approved, cncf-cla: yes, ok-to-test, size/M

#6316 Adopt 2020 roadmap, clean out 2019 items
  site/content/en/docs/Contributing/roadmap.en.md
Labels: approved, cncf-cla: yes, size/M

#6315 disable istio provisioner by default
  deploy/addons/istio/README.md
  pkg/minikube/assets/addons.go
Labels: approved, cncf-cla: yes, ok-to-test, size/S

#6317 bumping makefile to 1.17.0-beta.0
  Makefile
Labels: approved, cncf-cla: yes, ok-to-test, size/XS

#6306 Add a clear example of minikube tunnel to the docs
  cmd/minikube/cmd/tunnel.go
  site/content/en/docs/Tasks/loadbalancer.md
Labels: approved, cncf-cla: yes, size/M

#6323 Update kicbase.Dockerfile
  hack/images/kicbase.Dockerfile
Labels: cncf-cla: yes, size/XS

#6287 Use CGroupDriver function from cruntime for kubelet
  pkg/minikube/bootstrapper/bsutil/kubelet.go
  pkg/minikube/bootstrapper/bsutil/kubelet_test.go
  pkg/minikube/bootstrapper/kubeadm/kubeadm.go
  pkg/minikube/cruntime/containerd.go
  pkg/minikube/cruntime/cri.go
  pkg/minikube/cruntime/crio.go
  pkg/minikube/cruntime/cruntime.go
  pkg/minikube/cruntime/cruntime_test.go
  pkg/minikube/cruntime/docker.go
Labels: approved, cncf-cla: yes, ok-to-test, size/L

#6326 add the ability to mark drivers as experimental
  cmd/minikube/cmd/start.go
  pkg/minikube/driver/driver.go
  pkg/minikube/registry/drvs/docker/docker.go
  pkg/minikube/registry/registry.go
Labels: approved, cncf-cla: yes, ok-to-test, size/M

#6327 add release notes for 1.17.0-beta.0
  CHANGELOG.md
Labels: cncf-cla: yes, size/M

#6046 Remove polling from addon manager
  go.mod
  go.sum
  pkg/addons/addons.go
  pkg/addons/reconcile.go
  pkg/addons/reconcile_test.go
  pkg/minikube/assets/addons.go
  pkg/minikube/bootstrapper/bootstrapper.go
  pkg/minikube/bootstrapper/bsutil/binaries.go
  pkg/minikube/constants/constants.go
  test/integration/aaa_download_only_test.go
  test/integration/functional_test.go
Labels: approved, cncf-cla: yes, ok-to-test, size/L

#6337 change github-release calls to verbose
  hack/jenkins/release_github_page.sh
Labels: cncf-cla: yes, size/XS

#6336 patch cgroup pr
  pkg/minikube/bootstrapper/kicbs/kicbs.go
Labels: approved, cncf-cla: yes, ok-to-test, size/XS

#6348 fix grammer and remove extra spaces
  site/content/en/docs/Tasks/loadbalancer.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#6355 Remove stray space from driver selection message
  cmd/minikube/cmd/start.go
Labels: approved, cncf-cla: yes, size/XS

#6325 Stop minikube dashboard from crashing at start
  cmd/minikube/cmd/dashboard.go
Labels: approved, cncf-cla: yes, ok-to-test, size/XS

#6255 Fix syntax of minikube kubectl example command
  cmd/minikube/cmd/kubectl.go
  site/content/en/docs/Reference/Commands/kubectl.md
  translations/de.json
  translations/es.json
  translations/fr.json
  translations/ja.json
  translations/pl.json
  translations/zh-CN.json
Labels: approved, cncf-cla: yes, size/S

#6339 Update Japanese translation
  translations/ja.json
Labels: cncf-cla: yes, size/L

#6219 Update the crio.conf instead of overwriting it
  pkg/minikube/cruntime/cri.go
  pkg/minikube/cruntime/crio.go
Labels: approved, cncf-cla: yes, ok-to-test, size/L

#6341 Change the compression methods used on the iso
  deploy/iso/minikube-iso/configs/minikube_defconfig
Labels: approved, cncf-cla: yes, ok-to-test, size/XS

#6338 unify bootstrappers for both VM and contianer
  cmd/minikube/cmd/root.go
  cmd/minikube/cmd/start.go
  go.mod
  go.sum
  pkg/drivers/kic/kic.go
  pkg/minikube/bootstrapper/bootstrapper.go
  pkg/minikube/bootstrapper/bsutil/kverify/kverify.go
  pkg/minikube/bootstrapper/kicbs/cni.go
  pkg/minikube/bootstrapper/kicbs/kicbs.go
  pkg/minikube/bootstrapper/kubeadm/default_cni.go
  pkg/minikube/bootstrapper/kubeadm/kubeadm.go
  pkg/minikube/driver/driver.go
Labels: approved, cncf-cla: yes, ok-to-test, size/XL

#6362 implement remove file for kic runner
  pkg/minikube/command/kic_runner.go
Labels: approved, cncf-cla: yes, ok-to-test, size/XS

#6236 Check for nil ref and img before passing them into go-containerregistry
  pkg/minikube/image/cache.go
Labels: approved, cncf-cla: yes, ok-to-test, size/S

#6369 Remove unnecessary crio restart to improve start latency
  pkg/provision/buildroot.go
Labels: approved, cncf-cla: yes, ok-to-test, size/M

#6372 v1.7.0-beta.1 Makefile version bump for ISO testing
  Makefile
Labels: approved, cncf-cla: yes, size/XS

#6370 Double dry-run time limit, add logging
  test/integration/functional_test.go
Labels: approved, cncf-cla: yes, ok-to-test, size/S

#6266 Fix typo and improve documents
  pkg/minikube/config/profile.go
  pkg/minikube/config/profile_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#6375 ISO_VERSION should use VERSION_BUILD during beta
  Makefile
Labels: approved, cncf-cla: yes, size/XS

#6376 Fix dashboard by using kubectl apply/delete instead of prune for addons
  pkg/addons/addons.go
  pkg/addons/kubectl.go
  pkg/addons/kubectl_test.go
  pkg/addons/reconcile.go
  pkg/addons/reconcile_test.go
  pkg/minikube/assets/addons.go
Labels: approved, cncf-cla: yes, ok-to-test, size/L

#5962 Add 'pause' command to freeze Kubernetes cluster
  cmd/minikube/cmd/mount.go
  cmd/minikube/cmd/pause.go
  cmd/minikube/cmd/root.go
  cmd/minikube/cmd/status.go
  cmd/minikube/cmd/unpause.go
  go.sum
  pkg/drivers/none/none.go
  pkg/minikube/bootstrapper/kubeadm/kubeadm.go
  pkg/minikube/cluster/pause.go
  pkg/minikube/cruntime/containerd.go
  pkg/minikube/cruntime/cri.go
  pkg/minikube/cruntime/crio.go
  pkg/minikube/cruntime/cruntime.go
  pkg/minikube/cruntime/cruntime_test.go
  pkg/minikube/cruntime/docker.go
  pkg/minikube/kubelet/kubelet.go
  pkg/minikube/logs/logs.go
  pkg/minikube/out/style.go
  pkg/minikube/out/style_enum.go
  test/integration/helpers.go
  test/integration/start_stop_delete_test.go
Labels: approved, cncf-cla: yes, ok-to-test, size/XXL

#6374 Update Kubernetes libraries to v1.17.2
  go.mod
  go.sum
  pkg/drivers/none/none.go
Labels: approved, cncf-cla: yes, ok-to-test, size/XL

#6394 Update CRIO test to v1.15.7 to fix cgroups bug
  test/integration/start_stop_delete_test.go
Labels: approved, cncf-cla: yes, ok-to-test, size/XS

#6390 kic driver: add multiple profiles and ssh
  Makefile
  cmd/minikube/cmd/start.go
  hack/images/kicbase.Dockerfile
  pkg/drivers/kic/kic.go
  pkg/drivers/kic/node/node.go
  pkg/drivers/kic/oci/oci.go
  pkg/minikube/bootstrapper/kubeadm/kubeadm.go
  pkg/minikube/config/types.go
  pkg/minikube/constants/constants.go
  pkg/minikube/registry/drvs/docker/docker.go
Labels: approved, cncf-cla: yes, ok-to-test, size/L

#6392 Update DefaultKubernetesVersion to v1.17.2
  pkg/minikube/bootstrapper/bsutil/kubelet_test.go
  pkg/minikube/constants/constants.go
Labels: approved, cncf-cla: yes, ok-to-test, size/S

#6385 Batch file manipulation calls to reduce number of redundant commands
  pkg/minikube/bootstrapper/bsutil/binaries.go
  pkg/minikube/bootstrapper/certs.go
  pkg/minikube/bootstrapper/certs_test.go
  pkg/minikube/bootstrapper/kubeadm/kubeadm.go
  pkg/minikube/cluster/cluster.go
  pkg/minikube/cluster/cluster_test.go
  pkg/minikube/command/exec_runner.go
  pkg/minikube/command/fake_runner.go
  pkg/minikube/command/kic_runner.go
  pkg/minikube/command/ssh_runner.go
  pkg/minikube/machine/cache_images.go
  pkg/provision/buildroot.go
Labels: approved, cncf-cla: yes, ok-to-test, size/L

#6349 Add varlink program for using with podman-remote
  deploy/iso/minikube-iso/package/Config.in
  deploy/iso/minikube-iso/package/varlink/Config.in
  deploy/iso/minikube-iso/package/varlink/varlink.hash
  deploy/iso/minikube-iso/package/varlink/varlink.mk
Labels: approved, cncf-cla: yes, ok-to-test, size/S

#6285 Switch from MBR to GPT for the ISO partitioning
  deploy/iso/minikube-iso/package/automount/minikube-automount
Labels: approved, cncf-cla: yes, ok-to-test, size/XS

#6318 Add the Node interface
  cmd/minikube/cmd/config/profile_list.go
  cmd/minikube/cmd/dashboard.go
  cmd/minikube/cmd/pause.go
  cmd/minikube/cmd/start.go
  cmd/minikube/cmd/start_test.go
  cmd/minikube/cmd/unpause.go
  pkg/minikube/assets/vm_assets.go
  pkg/minikube/bootstrapper/bootstrapper.go
  pkg/minikube/bootstrapper/bsutil/kubeadm.go
  pkg/minikube/bootstrapper/bsutil/kubeadm_test.go
  pkg/minikube/bootstrapper/bsutil/kubelet.go
  pkg/minikube/bootstrapper/bsutil/kubelet_test.go
  pkg/minikube/bootstrapper/certs.go
  pkg/minikube/bootstrapper/certs_test.go
  pkg/minikube/bootstrapper/kubeadm/kubeadm.go
  pkg/minikube/cluster/cluster.go
  pkg/minikube/config/node.go
  pkg/minikube/config/profile.go
  pkg/minikube/config/profile_test.go
  pkg/minikube/config/types.go
  pkg/minikube/kubeconfig/testdata/kubeconfig/config1
  pkg/minikube/machine/cache_images.go
  pkg/minikube/registry/drvs/docker/docker.go
  pkg/minikube/registry/drvs/none/none.go
  pkg/provision/buildroot.go
  test/integration/aaa_download_only_test.go
Labels: approved, cncf-cla: yes, ok-to-test, size/XL

#6395 Update CHANGELOG for v1.7.0-beta.1
  CHANGELOG.md
Labels: approved, cncf-cla: yes, size/S

#6397 patch node refactor
  pkg/drivers/kic/oci/oci.go
  pkg/minikube/bootstrapper/kubeadm/kubeadm.go
  pkg/minikube/registry/drvs/docker/docker.go
Labels: approved, cncf-cla: yes, ok-to-test, size/M

#6267 Update kvm2.md
  site/content/en/docs/Reference/Drivers/kvm2.md
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/XS

#6407 add integration test script for docker driver
  hack/jenkins/linux_integration_tests_docker.sh
  hack/jenkins/minikube_set_pending.sh
Labels: approved, cncf-cla: yes, ok-to-test, size/M

#6322 Configure etcd and kube-proxy metrics to listen on minikube node IP
  pkg/minikube/bootstrapper/bsutil/ktmpl/v1beta1.go
  pkg/minikube/bootstrapper/bsutil/testdata/v1.14/containerd-api-port.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.14/containerd-pod-network-cidr.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.14/containerd.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.14/crio-options-gates.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.14/crio.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.14/default.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.14/dns.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.14/image-repository.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.14/options.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.15/containerd-api-port.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.15/containerd-pod-network-cidr.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.15/containerd.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.15/crio-options-gates.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.15/crio.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.15/default.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.15/dns.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.15/image-repository.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.15/options.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.16/containerd-api-port.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.16/containerd-pod-network-cidr.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.16/containerd.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.16/crio-options-gates.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.16/crio.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.16/default.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.16/dns.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.16/image-repository.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.16/options.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.17/containerd-api-port.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.17/containerd-pod-network-cidr.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.17/containerd.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.17/crio-options-gates.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.17/crio.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.17/default.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.17/dns.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.17/image-repository.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.17/options.yaml
Labels: cncf-cla: yes, ok-to-test, size/L

#6418 Add github actions integration tests
  .github/workflows/main.yml
Labels: approved, cncf-cla: yes, size/L

#6421 add github actions integration tests
  .github/workflows/main.yml
Labels: cncf-cla: yes, size/L

#6427 improve checking modprob netfilter
  pkg/minikube/command/kic_runner.go
  pkg/minikube/cruntime/cruntime.go
Labels: approved, cncf-cla: yes, ok-to-test, size/S

#6422 Add a 2-second timeout to driver detection commands
  pkg/minikube/registry/drvs/docker/docker.go
  pkg/minikube/registry/drvs/hyperkit/hyperkit.go
  pkg/minikube/registry/drvs/hyperv/hyperv.go
  pkg/minikube/registry/drvs/kvm2/kvm2.go
  pkg/minikube/registry/drvs/virtualbox/virtualbox.go
Labels: approved, cncf-cla: yes, ok-to-test, size/M

#6283 Use the complete filenames for the packages
  hack/jenkins/release_build_and_upload.sh
  hack/jenkins/release_github_page.sh
Labels: approved, cncf-cla: yes, size/S

#6431 Add missing status test
  cmd/minikube/cmd/status_test.go
Labels: approved, cncf-cla: yes, ok-to-test, size/L

#6435 Handle cert symlinks that point to a nonexistent file
  pkg/minikube/bootstrapper/certs.go
  pkg/minikube/bootstrapper/certs_test.go
Labels: approved, cncf-cla: yes, ok-to-test, size/XS

#6380 Prevent registry-creds configure from failing when a secret does not exist.
  pkg/minikube/service/service.go
Labels: cncf-cla: yes, ok-to-test, size/XS

#6257 Allow building storage-provisioner for other arch
  Makefile
  deploy/storage-provisioner/Dockerfile
  deploy/storage-provisioner/Dockerfile-s390x
Labels: approved, cncf-cla: yes, size/M

#6243 Do not use an arch suffix for the coredns name
  pkg/minikube/bootstrapper/images/images.go
Labels: approved, cncf-cla: yes, ok-to-test, size/XS

#6436 Add docker run-time for kic driver
  Makefile
  hack/images/kicbase.Dockerfile
  pkg/drivers/kic/kic.go
  pkg/minikube/cluster/cluster.go
  pkg/minikube/constants/constants.go
  pkg/minikube/driver/driver.go
Labels: approved, cncf-cla: yes, ok-to-test, size/M

#6442 Remove some redundance words
  cmd/minikube/cmd/start.go
  translations/ja.json
Labels: cncf-cla: yes, needs-ok-to-test, size/XS

#6423 add more tests to github actions
  .github/workflows/main.yml
Labels: approved, cncf-cla: yes, ok-to-test, size/M

#6444 Update github actions
  .github/workflows/main.yml
Labels: approved, cncf-cla: yes, size/S

#6441 improve kic engine
  pkg/drivers/kic/kic.go
  pkg/drivers/kic/node/node.go
  pkg/drivers/kic/oci/oci.go
  pkg/drivers/kic/oci/types.go
  pkg/drivers/kic/types.go
  pkg/minikube/bootstrapper/kubeadm/kubeadm.go
  pkg/minikube/cluster/cluster.go
  pkg/minikube/config/profile.go
Labels: approved, cncf-cla: yes, ok-to-test, size/XL

#6273 Only grab post-mortem logs if VM is running
  test/integration/helpers.go
  test/integration/start_stop_delete_test.go
Labels: approved, cncf-cla: yes, ok-to-test, size/M

#6449 Fix spacing in vm driver selection log
  cmd/minikube/cmd/start.go
Labels: approved, cncf-cla: yes, ok-to-test, size/XS

#6409 add container runtime info to profile list
  cmd/minikube/cmd/config/profile_list.go
Labels: approved, cncf-cla: yes, ok-to-test, size/XS

#6438 status: Explicitly state that the cluster does not exist
  cmd/minikube/cmd/status.go
  cmd/minikube/cmd/status_test.go
Labels: approved, cncf-cla: yes, ok-to-test, size/S

#6450 Allow 'profiles list' to work even if a profile has no control plane
  cmd/minikube/cmd/config/profile_list.go
Labels: approved, cncf-cla: yes, ok-to-test, size/S
