Repository kubernetes/minikube, pull requests merged in 2020-06, with the labels that each got.

#8362 add tutorial how to use minikube in github actions as a CI step
  site/content/en/docs/tutorials/setup_minikube_in_github_actions.md
Labels: approved, cncf-cla: yes, size/L

#8341 Add conntrack installation and fix some spacing
  site/content/en/docs/drivers/includes/none_usage.inc
Labels: cncf-cla: yes, needs-ok-to-test, size/XS

#8316 docs: Update host access with new cross-platform host method
  site/content/en/docs/handbook/host-access.md
Labels: approved, cncf-cla: yes, size/M

#8334 Add tests to minikube shell & refactor shell.go
  pkg/minikube/shell/shell.go
  pkg/minikube/shell/shell_test.go
Labels: cncf-cla: yes, ok-to-test, size/L

#8275 Add KubeVirt addon
  deploy/addons/kubevirt/README.md
  deploy/addons/kubevirt/pod.yaml.tmpl
  pkg/addons/config.go
  pkg/minikube/assets/addons.go
  site/content/en/docs/tutorials/kubevirt.md
Labels: cncf-cla: yes, ok-to-test, size/L

#8337 exit when minikube addons configure is called on a nonexistent cluster
  cmd/minikube/cmd/config/configure.go
Labels: cncf-cla: yes, ok-to-test, size/XS

#8355 Add digest to image in daemon after pulling it
  go.mod
  go.sum
  pkg/minikube/image/cache.go
  pkg/minikube/image/image.go
Labels: approved, cncf-cla: yes, ok-to-test, size/M

#8329 Log stacks for slowjam analysis if STACKLOG_PATH is set
  cmd/minikube/main.go
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, ok-to-test, size/S

#8368 add support for microsoft wsl for docker driver
  pkg/minikube/driver/driver.go
  test/integration/main.go
Labels: approved, cncf-cla: yes, ok-to-test, size/S

#8373 Refactor downloading kic base image
  pkg/drivers/kic/types.go
  pkg/minikube/image/image.go
  pkg/minikube/image/image_test.go
  pkg/minikube/node/cache.go
  pkg/minikube/node/start.go
Labels: approved, cncf-cla: yes, ok-to-test, size/L

#8335 added mutex lock over teePrefix()
  pkg/minikube/command/command_runner.go
Labels: cncf-cla: yes, ok-to-test, size/XS

#8377 go mod tidy
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, ok-to-test, size/S

#8385 Fix logviewer addon config. #8382
  pkg/addons/config.go
Labels: cncf-cla: yes, needs-ok-to-test, size/XS

#8378 ci: fix hyperv test in github actions
  .github/workflows/master.yml
  .github/workflows/pr.yml
  hack/jenkins/common.sh
  test/integration/fn_tunnel_cmd.go
Labels: approved, cncf-cla: yes, ok-to-test, size/L

#8390 Addons: Update OLM Addon
  deploy/addons/olm/crds.yaml
  deploy/addons/olm/olm.yaml
Labels: cncf-cla: yes, needs-ok-to-test, size/XXL

#8397 Update go-containerregistry to the rebased commit
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, size/XS

#8403 Upgrade Docker, from 19.03.8 to 19.03.11
  deploy/iso/minikube-iso/package/docker-bin/docker-bin.hash
  deploy/iso/minikube-iso/package/docker-bin/docker-bin.mk
Labels: approved, cncf-cla: yes, size/XS

#8405 Upgrade podman to 1.9.3
  deploy/iso/minikube-iso/package/podman/podman.hash
  deploy/iso/minikube-iso/package/podman/podman.mk
Labels: approved, cncf-cla: yes, size/XS

#8406 Upgrade conmon to 2.0.17
  deploy/iso/minikube-iso/package/conmon/conmon.hash
  deploy/iso/minikube-iso/package/conmon/conmon.mk
Labels: approved, cncf-cla: yes, size/XS

#8416 Add link to the Kanban view to community page
  site/config.toml
Labels: cncf-cla: yes, size/XS

#8404 Upgrade crio and crio.conf to v1.18.1
  deploy/iso/minikube-iso/package/crio-bin/conmon-config.h
  deploy/iso/minikube-iso/package/crio-bin/crio-bin.hash
  deploy/iso/minikube-iso/package/crio-bin/crio-bin.mk
  deploy/iso/minikube-iso/package/crio-bin/crio.conf
  deploy/iso/minikube-iso/package/crio-bin/crio.conf.default
Labels: approved, cncf-cla: yes, size/L

#8285 Added option --all to stop all clusters
  cmd/minikube/cmd/stop.go
  site/content/en/docs/commands/stop.md
Labels: cncf-cla: yes, needs-ok-to-test, size/M

#8417 Enable support for offline kic
  cmd/minikube/cmd/start.go
  go.mod
  go.sum
  pkg/minikube/image/image.go
  pkg/minikube/node/cache.go
  pkg/minikube/node/start.go
Labels: approved, cncf-cla: yes, ok-to-test, size/XL

#8419 add prasadkatti owners file
  OWNERS
Labels: approved, cncf-cla: yes, size/S

#8187 Buildroot 2020.02
  Makefile
  deploy/iso/minikube-iso/board/coreos/minikube/linux_defconfig
  deploy/iso/minikube-iso/board/coreos/minikube/patches/sysdig/0.23.1/driver.patch
  deploy/iso/minikube-iso/board/coreos/minikube/patches/sysdig/0.23.1/luajit.patch
  deploy/iso/minikube-iso/board/coreos/minikube/patches/varlink/19/ctags.patch
  deploy/iso/minikube-iso/configs/minikube_defconfig
  deploy/iso/minikube-iso/package/automount/automount.mk
  deploy/iso/minikube-iso/package/cni-plugins/Config.in
  deploy/iso/minikube-iso/package/cni/Config.in
  deploy/iso/minikube-iso/package/conmon/Config.in
  deploy/iso/minikube-iso/package/containerd-bin/Config.in
  deploy/iso/minikube-iso/package/crio-bin/Config.in
  deploy/iso/minikube-iso/package/hyperv-daemons/hyperv-daemons.mk
  deploy/iso/minikube-iso/package/podman/Config.in
  deploy/iso/minikube-iso/package/runc-master/Config.in
  deploy/iso/minikube-iso/package/vbox-guest/vbox-guest.hash
  deploy/iso/minikube-iso/package/vbox-guest/vbox-guest.mk
Labels: approved, cncf-cla: yes, size/XXL

#8392 Patch the registry-aliases addon missing entrypoint
  deploy/addons/registry-aliases/node-etc-hosts-update.tmpl
Labels: cncf-cla: yes, ok-to-test, size/XS

#8432 add mac os virtualbox test in github actions
  .github/workflows/master.yml
  .github/workflows/pr.yml
  test/integration/fn_tunnel_cmd.go
  test/integration/main.go
Labels: approved, cncf-cla: yes, size/XL

#8448 add sudo -E to none docs
  cmd/minikube/cmd/start.go
  site/content/en/docs/drivers/includes/none_usage.inc
Labels: approved, cncf-cla: yes, size/XS

#8428 Replace whitelist/blacklist with allow/deny
  cmd/minikube/cmd/root.go
  cmd/minikube/cmd/start.go
  cmd/minikube/cmd/start_flags.go
  pkg/minikube/bootstrapper/bsutil/extraconfig.go
  pkg/minikube/extract/extract.go
  test/integration/error_spam_test.go
Labels: approved, cncf-cla: yes, ok-to-test, size/M

#8450 Upgrade falco-probe driver kernel module to 0.23
  deploy/iso/minikube-iso/package/falco-probe/falco-probe.hash
  deploy/iso/minikube-iso/package/falco-probe/falco-probe.mk
Labels: approved, cncf-cla: yes, size/XS

#8451 Fix deployment name in ingress Nginx tutorial
  site/content/en/docs/tutorials/nginx_tcp_udp_ingress.md
Labels: cncf-cla: yes, needs-ok-to-test, size/S

#8463 Make sure to pass make env and flags for driver
  deploy/iso/minikube-iso/package/falco-probe/falco-probe.mk
Labels: approved, cncf-cla: yes, size/XS

#8464 skip olm addon
  .github/workflows/master.yml
  .github/workflows/pr.yml
  test/integration/addons_test.go
Labels: approved, cncf-cla: yes, ok-to-test, size/XS

#8465 Add set -x to kicbase image entrypoint
  hack/images/kicbase.Dockerfile
Labels: approved, cncf-cla: yes, size/XS

#8457 Improve logging for cloud shell
  pkg/drivers/kic/oci/cli_runner.go
  pkg/drivers/kic/oci/oci.go
Labels: approved, cncf-cla: yes, size/S

#8472 Require minikube-automount for /run/minikube/env
  deploy/iso/minikube-iso/package/crio-bin/crio-wipe.service
Labels: approved, cncf-cla: yes, size/XS

#8473 Add patch for restoring crio --version output
  deploy/iso/minikube-iso/board/coreos/minikube/patches/crio-bin/v1.18.1/version.patch
Labels: approved, cncf-cla: yes, size/M

#8471 bump helm-tiller addon to v2.16.8
  deploy/addons/helm-tiller/helm-tiller-dp.tmpl
Labels: area/addons, cncf-cla: yes, needs-ok-to-test, size/XS

#8455 Add heapster alias to metrics-server addon
  cmd/minikube/cmd/config/disable.go
  cmd/minikube/cmd/config/enable.go
  pkg/addons/addons.go
Labels: area/addons, cncf-cla: yes, kind/bug, ok-to-test, size/S

#8485 Point multi-node *-env users to the registry addon
  cmd/minikube/cmd/docker-env.go
  cmd/minikube/cmd/podman-env.go
Labels: approved, cncf-cla: yes, ok-to-test, size/XS

#8487 add solution message and suggestion for docker daemon errors
  pkg/minikube/registry/drvs/docker/docker.go
Labels: approved, cncf-cla: yes, size/S

#8475 Fix host network interface for VBox
  pkg/minikube/cluster/ip.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#8499 docker/podman: add advice for cpu count error
  cmd/minikube/cmd/start.go
  pkg/drivers/kic/oci/errors.go
  pkg/drivers/kic/oci/oci.go
  pkg/minikube/node/start.go
Labels: approved, cncf-cla: yes, ok-to-test, size/M

#8502 fix test err spam skip logic
  test/integration/error_spam_test.go
Labels: approved, cncf-cla: yes, size/XS

#8489 docs: fix broken links
  site/content/en/docs/contrib/drivers.en.md
  site/content/en/docs/contrib/roadmap.en.md
  site/content/en/docs/drivers/includes/podman_usage.inc
  site/content/en/docs/drivers/podman.md
  site/content/en/docs/handbook/pushing.md
  site/content/en/docs/handbook/registry.md
  site/content/en/docs/tutorials/ambassador_ingress_controller.md
  site/content/en/docs/tutorials/audit-policy.md
  site/content/en/docs/tutorials/nginx_tcp_udp_ingress.md
  site/content/en/docs/tutorials/nvidia_gpu.md
Labels: cncf-cla: yes, needs-ok-to-test, size/M

#8501 docker/podman: add solution message when container exits after start/create
  cmd/minikube/cmd/start.go
  pkg/drivers/kic/kic.go
  pkg/drivers/kic/oci/errors.go
  pkg/drivers/kic/oci/oci.go
  pkg/minikube/machine/advice.go
  pkg/minikube/machine/fix.go
Labels: approved, cncf-cla: yes, ok-to-test, size/L

#8506 Adds support for unsetting of env vars
  cmd/minikube/cmd/docker-env.go
  cmd/minikube/cmd/podman-env.go
Labels: cncf-cla: yes, needs-ok-to-test, size/M

#8513 Release v1.12.0-beta.0
  CHANGELOG.md
  Makefile
Labels: approved, cncf-cla: yes, ok-to-test, size/M

#8520 Don't return error when SHELL has not been set
  pkg/minikube/shell/shell.go
  pkg/minikube/shell/shell_test.go
Labels: approved, cncf-cla: yes, ok-to-test, size/S

#8519 Adds better information for using kubectl inside minikube
  cmd/minikube/cmd/start.go
  site/content/en/docs/handbook/kubectl.md
Labels: cncf-cla: yes, ok-to-test, size/M

#8521 The logging of the kubectl path was broken
  cmd/minikube/cmd/kubectl.go
Labels: approved, cncf-cla: yes, ok-to-test, size/XS

#8528 docker-env: Avoid container suicide if Docker is not installed locally
  cmd/minikube/cmd/docker-env.go
Labels: approved, cncf-cla: yes, ok-to-test, size/S

#8529 integration: add delete to cache test
  test/integration/functional_test.go
Labels: approved, cncf-cla: yes, ok-to-test, size/XS

#8536 Remove trailing spaces after leader-elect: false
  pkg/minikube/bootstrapper/bsutil/ktmpl/v1alpha3.go
  pkg/minikube/bootstrapper/bsutil/testdata/v1.11/containerd-api-port.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.11/containerd-pod-network-cidr.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.11/containerd.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.11/crio-options-gates.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.11/crio.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.11/default.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.11/image-repository.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.11/options.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.12/containerd-api-port.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.12/containerd-pod-network-cidr.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.12/containerd.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.12/crio-options-gates.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.12/crio.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.12/default.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.12/dns.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.12/image-repository.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.12/options.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.13/containerd-api-port.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.13/containerd-pod-network-cidr.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.13/containerd.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.13/crio-options-gates.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.13/crio.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.13/default.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.13/dns.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.13/image-repository.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.13/options.yaml
Labels: approved, cncf-cla: yes, ok-to-test, size/M

#8531 Do not output usage hint when shell=none.
  pkg/minikube/shell/shell.go
  pkg/minikube/shell/shell_test.go
Labels: cncf-cla: yes, needs-ok-to-test, size/XS

#8539 Upgrade podman to 2.0.0
  deploy/iso/minikube-iso/package/podman/podman.hash
  deploy/iso/minikube-iso/package/podman/podman.mk
Labels: approved, cncf-cla: yes, size/XS

#8537 Automatically limit integration test parallelism
  test/integration/fn_mount_cmd_test.go
  test/integration/fn_pvc_test.go
  test/integration/fn_tunnel_cmd_test.go
  test/integration/helpers_test.go
  test/integration/main_test.go
  test/integration/util_test.go
Labels: approved, cncf-cla: yes, ok-to-test, size/M

#8518 Make sure to use internal containerd for docker
  pkg/minikube/cruntime/cruntime_test.go
  pkg/minikube/cruntime/docker.go
Labels: approved, cncf-cla: yes, ok-to-test, size/M

#8547 virtualbox: double health check timeout, add better errors
  pkg/minikube/registry/drvs/virtualbox/virtualbox.go
Labels: approved, cncf-cla: yes, size/S

#8544 Skip node pressure check if other checks failed, add retry
  pkg/minikube/bootstrapper/bsutil/kverify/node_conditions.go
  pkg/minikube/bootstrapper/kubeadm/kubeadm.go
Labels: approved, cncf-cla: yes, ok-to-test, size/M

#8294 Bump Dashboard to v2.0.1
  deploy/addons/dashboard/dashboard-dp.yaml
  pkg/minikube/bootstrapper/images/images.go
  pkg/minikube/bootstrapper/images/images_test.go
  pkg/minikube/bootstrapper/images/kubeadm_test.go
  pkg/minikube/cruntime/containerd_test.go
  pkg/minikube/download/preload.go
Labels: cncf-cla: yes, ok-to-test, size/M

#8548 Rename falco-probe package to falco-module instead
  deploy/iso/minikube-iso/package/Config.in
  deploy/iso/minikube-iso/package/falco-module/Config.in
  deploy/iso/minikube-iso/package/falco-module/falco-module.hash
  deploy/iso/minikube-iso/package/falco-module/falco-module.mk
  deploy/iso/minikube-iso/package/falco-probe/falco-probe.mk
Labels: approved, cncf-cla: yes, size/M

#8538 integration: add more MacOS test to github actions
  .github/workflows/master.yml
  .github/workflows/pr.yml
Labels: approved, cncf-cla: yes, size/XL

#8551 Allow passing in extra args to etcd via command line
  pkg/minikube/bootstrapper/bsutil/extraconfig.go
  pkg/minikube/bootstrapper/bsutil/ktmpl/v1beta2.go
  pkg/minikube/bootstrapper/bsutil/kubeadm.go
  pkg/minikube/bootstrapper/bsutil/kubeadm_test.go
Labels: approved, cncf-cla: yes, ok-to-test, size/M

#8552 Reduce coredns replicas from 2 to 1
  pkg/addons/kubectl.go
  pkg/kapi/kapi.go
  pkg/minikube/node/start.go
Labels: approved, cncf-cla: yes, ok-to-test, size/M

#8543 Improve error and logging emitted by WaitForAppsRunning
  pkg/minikube/bootstrapper/bsutil/kverify/system_pods.go
  pkg/util/retry/retry.go
Labels: approved, cncf-cla: yes, ok-to-test, size/M

#8541 docker driver on linux: Give warning if overlay module is not enabled
  cmd/minikube/cmd/start.go
  pkg/minikube/registry/drvs/docker/docker.go
  pkg/minikube/registry/registry.go
Labels: approved, cncf-cla: yes, size/M

#8562 apiserverHealthz: wait up to 8s before declaring failure
  pkg/minikube/bootstrapper/bsutil/kverify/api_server.go
Labels: approved, cncf-cla: yes, ok-to-test, size/S

#8565 Check for iptables file before determining container is running
  pkg/drivers/kic/oci/oci.go
Labels: approved, cncf-cla: yes, ok-to-test, size/S

#8574 Fix bug in FailFastError and add unit test
  pkg/drivers/kic/oci/errors.go
  pkg/drivers/kic/oci/errors_test.go
  pkg/minikube/node/start.go
Labels: approved, cncf-cla: yes, size/M

#8575 Support prerelease versions of podman binary
  pkg/minikube/registry/drvs/podman/podman.go
Labels: approved, cncf-cla: yes, size/XS

#8563 add verification for enabling ingress, registry and gvisor addons
  pkg/addons/addons.go
  pkg/addons/config.go
  pkg/kapi/kapi.go
Labels: approved, cncf-cla: yes, size/M

#8570 CNI: Update CRIO netconfig with matching subnet
  pkg/minikube/bootstrapper/kubeadm/kubeadm.go
  pkg/minikube/cni/bridge.go
  pkg/minikube/cruntime/crio.go
  test/integration/net_test.go
Labels: approved, cncf-cla: yes, ok-to-test, size/M

#8582 Kernel with CONFIG_IKHEADERS for BPF tools on Kubernetes
  deploy/iso/minikube-iso/board/coreos/minikube/linux_defconfig
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#8597 add solution message if kubeadm binary is not executable on linux
  cmd/minikube/cmd/node_start.go
  cmd/minikube/cmd/start.go
  pkg/minikube/bootstrapper/kubeadm/errors.go
  pkg/minikube/bootstrapper/kubeadm/kubeadm.go
  pkg/minikube/node/advice.go
  pkg/minikube/node/node.go
  pkg/minikube/node/start.go
Labels: approved, cncf-cla: yes, size/L

#8598 Don't verify nf_conntrack for br_netfilter
  pkg/minikube/cruntime/cruntime.go
Labels: approved, cncf-cla: yes, ok-to-test, size/XS

#8593 Gracefully exit if container runtime is misspelled
  cmd/minikube/cmd/start.go
  cmd/minikube/cmd/start_flags.go
  pkg/minikube/bootstrapper/kubeadm/kubeadm.go
  pkg/minikube/constants/constants.go
  pkg/minikube/cruntime/cruntime.go
  site/content/en/docs/commands/start.md
Labels: cncf-cla: yes, ok-to-test, size/M

#8590 Upgrade golang version from 1.13.8 to 1.13.9
  .github/workflows/master.yml
  .github/workflows/pr.yml
  .travis.yml
  Makefile
  hack/jenkins/common.sh
Labels: approved, cncf-cla: yes, ok-to-test, size/M

#8602 skip cni test for none driver
  test/integration/net_test.go
Labels: approved, cncf-cla: yes, ok-to-test, size/XS

#8612 Run gofmt on pkg/minikube/shell/shell.go
  pkg/minikube/shell/shell.go
Labels: approved, cncf-cla: yes, size/S
