Repository kubernetes/minikube, pull requests merged in 2020-12, with the labels that each got.

#9791 fix base image when using with custom image repository
  pkg/minikube/node/cache.go
Labels: approved, cncf-cla: yes, ok-to-test, size/XS

#9815 Only rebuild minikube latest binaries if commit has changed
  hack/jenkins/build/minikube_build_upload_latest.sh
Labels: approved, cncf-cla: yes, size/XS

#9821 CI: add test order to gopogh report
  .github/workflows/iso.yml
  .github/workflows/kic_image.yml
  .github/workflows/master.yml
  .github/workflows/pr.yml
  hack/jenkins/common.sh
Labels: approved, cncf-cla: yes, do-not-merge/hold, ok-to-test, size/M

#9808 Add script to collect metrics for minikube start
  go.sum
  hack/metrics/README.md
  hack/metrics/metrics.go
  hack/metrics/minikube.go
  pkg/trace/gcp.go
Labels: approved, cncf-cla: yes, ok-to-test, size/L

#9824 Add --label flag so we can add custom labels to metric collection
  Makefile
  hack/metrics/metrics.go
Labels: approved, cncf-cla: yes, size/M

#9822 bump storage provsioner to multi arch
  Makefile
  go.mod
  go.sum
  pkg/minikube/bootstrapper/images/images_test.go
  pkg/minikube/bootstrapper/images/kubeadm_test.go
  pkg/minikube/cruntime/containerd_test.go
  pkg/minikube/download/preload.go
Labels: approved, cncf-cla: yes, ok-to-test, size/M

#9716 Add private network implementation for podman
  cmd/minikube/cmd/delete.go
  pkg/drivers/kic/kic.go
  pkg/drivers/kic/oci/errors.go
  pkg/drivers/kic/oci/network.go
  pkg/drivers/kic/oci/network_create.go
  pkg/drivers/kic/oci/oci.go
Labels: approved, cncf-cla: yes, ok-to-test, size/L

#9832 Fix missing InitialSetup in `node start`
  cmd/minikube/cmd/node_start.go
Labels: approved, cncf-cla: yes, ok-to-test, size/XS

#9854 Collect metrics for each container runtime
  hack/metrics/metrics.go
Labels: approved, cncf-cla: yes, size/M

#9853 add script to automate gopogh version update
  hack/update/gopogh_version/update_gopogh_version.go
Labels: cncf-cla: yes, needs-ok-to-test, size/L

#9852 fix GHReleases() to use rls tag name instead of rls name for rls version
  hack/update/github.go
  hack/update/update.go
Labels: approved, cncf-cla: yes, needs-ok-to-test, size/XS

#9797 Ability to use a custom TLS certificate with the Ingress
  cmd/minikube/cmd/config/configure.go
  deploy/addons/ingress/ingress-dp.yaml.tmpl
  pkg/minikube/assets/addons.go
  pkg/minikube/config/types.go
  site/content/en/docs/tutorials/custom_cert_ingress.md
Labels: cncf-cla: yes, size/M

#9856 metrics script: don't fail if one container runtime fails
  hack/metrics/metrics.go
Labels: approved, cncf-cla: yes, size/M

#9867 Update crictl to v1.18.0
  deploy/iso/minikube-iso/package/crictl-bin/crictl-bin.hash
  deploy/iso/minikube-iso/package/crictl-bin/crictl-bin.mk
Labels: approved, cncf-cla: yes, size/XS

#9862 Buildroot 2020.02.8
  Makefile
  deploy/iso/minikube-iso/configs/minikube_defconfig
Labels: approved, cncf-cla: yes, size/XS

#9861 Upgrade Docker, from 19.03.13 to 19.03.14
  deploy/iso/minikube-iso/package/containerd-bin/containerd-bin.hash
  deploy/iso/minikube-iso/package/containerd-bin/containerd-bin.mk
  deploy/iso/minikube-iso/package/docker-bin/docker-bin.hash
  deploy/iso/minikube-iso/package/docker-bin/docker-bin.mk
Labels: approved, cncf-cla: yes, size/XS

#9844 Set 'currentstep' for PullingBaseImage json event
  pkg/minikube/out/register/register.go
  test/integration/aaa_download_only_test.go
Labels: approved, cncf-cla: yes, ok-to-test, size/M

#9863 Upgrade kicbase to ubuntu:focal-20201106
  deploy/kicbase/Dockerfile
  deploy/kicbase/entrypoint
Labels: approved, cncf-cla: yes, size/M

#9819 Debian installer: only recommend virtualbox when running on amd64
  Makefile
  installers/linux/deb/minikube_deb_template/DEBIAN/control
Labels: approved, cncf-cla: yes, size/XS

#9859 Add linux packages for the arm64 architecture
  hack/jenkins/release_build_and_upload.sh
  site/content/en/docs/start/_index.md
Labels: approved, cncf-cla: yes, size/M

#9801 Add support for restoring existing podman env
  cmd/minikube/cmd/podman-env.go
  pkg/drivers/kic/oci/env.go
  pkg/minikube/constants/constants.go
Labels: approved, cncf-cla: yes, size/M

#9636 KIC: Upgrade podman to version 2.2.0 and remove varlink
  deploy/kicbase/Dockerfile
Labels: approved, cncf-cla: yes, do-not-merge/hold, size/S

#9789 fix unable to set memory in config
  cmd/minikube/cmd/config/config.go
  cmd/minikube/cmd/config/set_test.go
Labels: approved, cncf-cla: yes, ok-to-test, size/XS

#9635 ISO: Upgrade podman to version 2.2.0 and remove varlink
  deploy/iso/minikube-iso/board/coreos/minikube/users
  deploy/iso/minikube-iso/package/Config.in
  deploy/iso/minikube-iso/package/podman/override.conf
  deploy/iso/minikube-iso/package/podman/podman.conf
  deploy/iso/minikube-iso/package/podman/podman.hash
  deploy/iso/minikube-iso/package/podman/podman.mk
  deploy/iso/minikube-iso/package/varlink/Config.in
  deploy/iso/minikube-iso/package/varlink/varlink.hash
  deploy/iso/minikube-iso/package/varlink/varlink.mk
Labels: approved, cncf-cla: yes, do-not-merge/hold, size/M

#9793 feat(minikube) display scheduledstop status in minikube status
  cmd/minikube/cmd/status.go
  cmd/minikube/cmd/status_test.go
  site/content/en/docs/commands/status.md
  test/integration/scheduled_stop_test.go
Labels: cncf-cla: yes, ok-to-test, size/M

#9886 reduce hyperkit tests to functional
  hack/jenkins/common.sh
  hack/jenkins/linux_integration_tests_none.sh
  hack/jenkins/linux_integration_tests_podman.sh
  hack/jenkins/osx_integration_tests_hyperkit.sh
  hack/jenkins/osx_integration_tests_virtualbox.sh
Labels: approved, cncf-cla: yes, ok-to-test, size/S

#9883 bump kic base on head
  pkg/drivers/kic/types.go
  site/content/en/docs/commands/start.md
Labels: approved, cncf-cla: yes, ok-to-test, size/XS

#9703 Fix whitespace issues in the site content markdown
  site/content/en/docs/contrib/documentation.en.md
  site/content/en/docs/contrib/drivers.en.md
  site/content/en/docs/contrib/json_output.en.md
  site/content/en/docs/contrib/principles.en.md
  site/content/en/docs/contrib/releasing/binaries.md
  site/content/en/docs/contrib/roadmap.en.md
  site/content/en/docs/contrib/testing.en.md
  site/content/en/docs/contrib/translations.md
  site/content/en/docs/contrib/triage.md
  site/content/en/docs/drivers/docker.md
  site/content/en/docs/drivers/hyperkit.md
  site/content/en/docs/drivers/kvm2.md
  site/content/en/docs/drivers/podman.md
  site/content/en/docs/faq/_index.md
  site/content/en/docs/handbook/accessing.md
  site/content/en/docs/handbook/addons/gcp-auth.md
  site/content/en/docs/handbook/controls.md
  site/content/en/docs/handbook/dashboard.md
  site/content/en/docs/handbook/deploying.md
  site/content/en/docs/handbook/filesync.md
  site/content/en/docs/handbook/host-access.md
  site/content/en/docs/handbook/kubectl.md
  site/content/en/docs/handbook/mount.md
  site/content/en/docs/handbook/pushing.md
  site/content/en/docs/handbook/registry.md
  site/content/en/docs/handbook/troubleshooting.md
  site/content/en/docs/handbook/untrusted_certs.md
  site/content/en/docs/start/_index.md
  site/content/en/docs/tutorials/_index.md
  site/content/en/docs/tutorials/ambassador_ingress_controller.md
  site/content/en/docs/tutorials/configuring_creds_for_aws_ecr.md
  site/content/en/docs/tutorials/ebpf_tools_in_minikube.md
  site/content/en/docs/tutorials/kubevirt.md
  site/content/en/docs/tutorials/multi_node.md
  site/content/en/docs/tutorials/nginx_tcp_udp_ingress.md
  site/content/en/docs/tutorials/setup_minikube_in_github_actions.md
  site/content/en/docs/tutorials/telemetry.md
  site/content/en/docs/tutorials/volume_snapshots_and_csi.md
Labels: approved, cncf-cla: yes, size/L

#9407 Add a Makefile variable to run a subset of integration tests files
  Makefile
Labels: approved, cncf-cla: yes, needs-ok-to-test, size/S

#9379 Make none driver work as regular user (use sudo on demand)
  cmd/minikube/cmd/start.go
  pkg/minikube/command/exec_runner.go
  pkg/minikube/driver/driver.go
  pkg/minikube/registry/drvs/none/none.go
Labels: cncf-cla: yes, ok-to-test, size/M

#9887 Bump iso on head
  Makefile
  go.mod
  site/content/en/docs/commands/start.md
Labels: approved, cncf-cla: yes, ok-to-test, size/XS

#9634 Fix --extra-config when starting an existing cluster
  cmd/minikube/cmd/start_flags.go
  test/integration/functional_test.go
Labels: approved, cncf-cla: yes, ok-to-test, size/M

#9548 Optionally use ssh for docker-env instead of tcp
  cmd/minikube/cmd/docker-env.go
  cmd/minikube/cmd/docker-env_test.go
  site/content/en/docs/commands/docker-env.md
Labels: approved, cncf-cla: yes, ok-to-test, size/L

#9895 Upgrade Docker, from 19.03.14 to 20.10.0
  deploy/iso/minikube-iso/package/containerd-bin/containerd-bin.hash
  deploy/iso/minikube-iso/package/containerd-bin/containerd-bin.mk
  deploy/iso/minikube-iso/package/docker-bin/docker-bin.hash
  deploy/iso/minikube-iso/package/docker-bin/docker-bin.mk
  deploy/iso/minikube-iso/package/runc-master/runc-master.hash
  deploy/iso/minikube-iso/package/runc-master/runc-master.mk
Labels: approved, cncf-cla: yes, size/S

#9899 Upgrade go version to 1.15.5
  .github/workflows/iso.yml
  .github/workflows/kic_image.yml
  .github/workflows/master.yml
  .github/workflows/pr.yml
  Makefile
  hack/jenkins/common.sh
Labels: approved, cncf-cla: yes, size/M

#9900 Remove warning for using podman v2 with driver
  pkg/minikube/registry/drvs/podman/podman.go
Labels: approved, cncf-cla: yes, size/XS

#9896 Upgrade Podman, from 2.2.0 to 2.2.1
  deploy/iso/minikube-iso/package/podman/podman.hash
  deploy/iso/minikube-iso/package/podman/podman.mk
Labels: approved, cncf-cla: yes, size/XS

#9901 Update crictl to v1.19.0
  deploy/iso/minikube-iso/package/crictl-bin/crictl-bin.hash
  deploy/iso/minikube-iso/package/crictl-bin/crictl-bin.mk
Labels: approved, cncf-cla: yes, size/XS

#9902 Upgrade CRI-O, from 1.18.4 to 1.19.0
  deploy/iso/minikube-iso/package/crio-bin/crio-bin.hash
  deploy/iso/minikube-iso/package/crio-bin/crio-bin.mk
  deploy/kicbase/Dockerfile
Labels: approved, cncf-cla: yes, size/S

#9833 Fix `node start` master node
  cmd/minikube/cmd/node_start.go
Labels: cncf-cla: yes, ok-to-test, size/XS

#9903 Run gofmt on the code and not just goimports
  pkg/minikube/registry/drvs/hyperv/hyperv.go
Labels: approved, cncf-cla: yes, size/XS

#9802 Some more cleanup of missing code for podman-env
  pkg/drivers/kic/oci/oci.go
  pkg/drivers/kic/oci/oci_test.go
  pkg/minikube/constants/constants.go
Labels: approved, cncf-cla: yes, ok-to-test, size/L

#9897 update default kubernetes version to 1.20.0
  pkg/minikube/bootstrapper/bsutil/testdata/v1.20/containerd-api-port.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.20/containerd-pod-network-cidr.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.20/containerd.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.20/crio-options-gates.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.20/crio.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.20/default.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.20/dns.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.20/image-repository.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.20/options.yaml
  pkg/minikube/constants/constants.go
  site/content/en/docs/commands/start.md
Labels: approved, cncf-cla: yes, ok-to-test, size/S

#9894 fix hyperkit tests
  Makefile
  hack/jenkins/installers/check_install_golang.sh
  hack/jenkins/osx_integration_tests_hyperkit.sh
  test/integration/functional_test.go
Labels: approved, cncf-cla: yes, ok-to-test, size/S

#9915 Update the containerd configuration to v2
  deploy/iso/minikube-iso/package/containerd-bin/config.toml
  deploy/iso/minikube-iso/package/containerd-bin/config.toml.default
Labels: approved, cncf-cla: yes, size/L

#9922 Only use sudo with the none driver when on linux
  pkg/drivers/kic/kic.go
  pkg/drivers/none/none.go
  pkg/minikube/command/exec_runner.go
  pkg/minikube/machine/client.go
  pkg/provision/provision.go
Labels: approved, cncf-cla: yes, size/M

#9618 Modify "example command" in cli reference for "config".
  site/content/en/docs/commands/config.md
Labels: approved, cncf-cla: yes, needs-ok-to-test, size/XS

#9918 Remove verbose options
  hack/preload-images/generate.go
  pkg/drivers/kic/oci/volumes.go
  pkg/minikube/cruntime/containerd.go
  pkg/minikube/cruntime/crio.go
  pkg/minikube/cruntime/docker.go
Labels: approved, cncf-cla: yes, ok-to-test, size/S

#9912 fix: use release tags and add make targets
  Makefile
  hack/update/github.go
Labels: approved, cncf-cla: yes, needs-ok-to-test, size/S

#9726 amend linux cleanup script with full minikube, docker and kvm cleanup
  hack/jenkins/cron/cleanup_and_reboot_Linux.sh
Labels: cncf-cla: yes, ok-to-test, size/M

#9855 Add spinner at preparing Kubernetes...
  go.mod
  go.sum
  pkg/minikube/out/out.go
  pkg/minikube/out/out_style.go
  pkg/minikube/out/out_style_test.go
  pkg/minikube/style/style.go
Labels: approved, cncf-cla: yes, ok-to-test, size/M

#9911 Update kicbase 15 snapshot4 on head
  pkg/drivers/kic/types.go
  site/content/en/docs/commands/start.md
Labels: approved, cncf-cla: yes, ok-to-test, size/XS

#9928 Add missing helper binaries for containerd-shim
  deploy/iso/minikube-iso/package/containerd-bin/containerd-bin.mk
Labels: approved, cncf-cla: yes, size/XS

#9917 Upgrade crio.conf to version v1.19.0
  deploy/iso/minikube-iso/package/crio-bin/crio.conf
  deploy/iso/minikube-iso/package/crio-bin/crio.conf.default
Labels: approved, cncf-cla: yes, size/M

#9888 added statusName for kubeconfig
  cmd/minikube/cmd/status.go
Labels: approved, cncf-cla: yes, needs-ok-to-test, size/XS

#9866 Fix podman network inspect format and error
  pkg/drivers/kic/oci/network_create.go
Labels: approved, cncf-cla: yes, size/S

#9933 bump iso on head for snapshot4
  Makefile
  site/content/en/docs/commands/config.md
  site/content/en/docs/commands/start.md
Labels: approved, cncf-cla: yes, ok-to-test, size/XS

#9934 Remove obsolete mention of kvm driver, fixes generate-docs issue
  cmd/minikube/cmd/config/config.go
Labels: approved, cncf-cla: yes, size/XS

#9935 Fixed output on back to back spinner steps
  pkg/minikube/out/out.go
Labels: approved, cncf-cla: yes, needs-ok-to-test, size/XS

#9932 wsl2: log warning if br_netfilter cannot be enabled rather than fatally exit
  pkg/minikube/cruntime/crio.go
  pkg/minikube/cruntime/cruntime.go
Labels: approved, cncf-cla: yes, size/M

#9941 Run generate-docs again for the driver rename
  site/content/en/docs/commands/config.md
Labels: approved, cncf-cla: yes, size/XS

#9945 Fix minor typo in build of the project name itself
  site/content/en/docs/handbook/pushing.md
Labels: approved, cncf-cla: yes, size/XS

#9943 Add some more docs about building images
  site/content/en/docs/handbook/pushing.md
Labels: approved, cncf-cla: yes, size/M

#9949 Add mention of the Windows Package Manager
  site/content/en/docs/start/_index.md
Labels: cncf-cla: yes, needs-ok-to-test, size/S

#9957 start: Support comma-delimited --addons
  cmd/minikube/cmd/start_flags.go
Labels: approved, cncf-cla: yes, needs-ok-to-test, size/XS

#9948 Add persistent storage for /var/lib/buildkit
  deploy/iso/minikube-iso/package/automount/minikube-automount
  site/content/en/docs/handbook/persistent_volumes.md
Labels: approved, cncf-cla: yes, size/XS

#9940 Upgrade buildkit from 0.7.2 to 0.8.0
  deploy/iso/minikube-iso/package/buildkit-bin/buildkit-bin.hash
  deploy/iso/minikube-iso/package/buildkit-bin/buildkit-bin.mk
  deploy/kicbase/Dockerfile
Labels: approved, cncf-cla: yes, size/S

#9960 release notes: fix whitespace before contributors list
  hack/release_notes.sh
Labels: approved, cncf-cla: yes, size/XS

#9753 Fix minikube tunnel for Docker on Windows
  pkg/drivers/kic/kic.go
  pkg/minikube/tunnel/kic/ssh_conn.go
Labels: cncf-cla: yes, size/M

#9923 make tests more reliable
  hack/jenkins/common.sh
  hack/jenkins/linux_integration_tests_virtualbox.sh
  hack/jenkins/minikube_set_pending.sh
Labels: approved, cncf-cla: yes, ok-to-test, size/S

#9964 Update Makefile and release notes for 1.16.0-beta.0
  CHANGELOG.md
  Makefile
  hack/jenkins/linux_integration_tests_none.sh
  site/content/en/docs/commands/start.md
Labels: approved, cncf-cla: yes, ok-to-test, size/M

#9961 changelog: make headings more consistent, pass mdlint
  CHANGELOG.md
Labels: approved, cncf-cla: yes, size/M

#9967 Upgrade buildkit from 0.8.0 to 0.8.1
  deploy/iso/minikube-iso/package/buildkit-bin/buildkit-bin.hash
  deploy/iso/minikube-iso/package/buildkit-bin/buildkit-bin.mk
  deploy/kicbase/Dockerfile
Labels: approved, cncf-cla: yes, size/XS

#9966 Upgrade Docker, from 20.10.0 to 20.10.1
  deploy/iso/minikube-iso/package/docker-bin/docker-bin.hash
  deploy/iso/minikube-iso/package/docker-bin/docker-bin.mk
Labels: approved, cncf-cla: yes, size/XS

#9873 Add --node option for command `ip` and `ssh-key`
  cmd/minikube/cmd/ip.go
  cmd/minikube/cmd/ssh-key.go
  site/content/en/docs/commands/ip.md
  site/content/en/docs/commands/ssh-key.md
Labels: approved, cncf-cla: yes, ok-to-test, size/M

#9904 Added sub-step logging to adm init step on start
  pkg/minikube/bootstrapper/kubeadm/kubeadm.go
  pkg/minikube/command/command_runner.go
  pkg/minikube/command/exec_runner.go
  pkg/minikube/command/fake_runner.go
  pkg/minikube/command/fake_runner_test.go
  pkg/minikube/command/kic_runner.go
  pkg/minikube/command/ssh_runner.go
  pkg/minikube/cruntime/cruntime.go
  pkg/minikube/cruntime/cruntime_test.go
  pkg/minikube/out/register/register.go
  pkg/minikube/style/style.go
  pkg/minikube/style/style_enum.go
  test/integration/error_spam_test.go
Labels: approved, cncf-cla: yes, needs-ok-to-test, size/L

#9963 Upgrade kubernetes dashboard to v2.1.0 for 1.20
  deploy/addons/dashboard/dashboard-dp.yaml.tmpl
  pkg/minikube/bootstrapper/images/images.go
  pkg/minikube/bootstrapper/images/images_test.go
  pkg/minikube/bootstrapper/images/kubeadm_test.go
  pkg/minikube/cruntime/containerd_test.go
  test/integration/start_stop_delete_test.go
Labels: approved, cncf-cla: yes, size/S

#9630 Add ssh-host command for getting the ssh host keys
  cmd/minikube/cmd/root.go
  cmd/minikube/cmd/ssh-host.go
  pkg/minikube/machine/ssh.go
  pkg/minikube/sshutil/sshutil.go
  site/content/en/docs/commands/ssh-host.md
Labels: approved, cncf-cla: yes, ok-to-test, size/L

#9980 README: Update Google Groups URL's
  README.md
Labels: approved, cncf-cla: yes, needs-ok-to-test, size/XS

#9978 Removed parallel running from test func to prevent ctx timeout
  test/integration/functional_test.go
Labels: cncf-cla: yes, ok-to-test, size/XS

#9984 Bump preload to v8 to include updated dashboard
  pkg/minikube/download/preload.go
Labels: approved, cncf-cla: yes, size/XS

#9761 Enable Ingress Addon for Docker Windows
  pkg/addons/addons.go
Labels: cncf-cla: yes, size/XS

#9987 remove experimental warning for multinode
  cmd/minikube/cmd/node_add.go
  cmd/minikube/cmd/start.go
  site/content/en/docs/tutorials/multi_node.md
Labels: approved, cncf-cla: yes, size/M

#9986 fix ip node retrieve for none driver
  pkg/minikube/node/node.go
Labels: approved, cncf-cla: yes, ok-to-test, size/XS

#9990 Update Makefile and release notes for 1.16.0 release
  CHANGELOG.md
  Makefile
Labels: approved, cncf-cla: yes, ok-to-test, size/S

#9994 site: fix display method for tabs if jQuery fails to load
  site/static/css/tabs.css
  site/static/js/tabs.js
Labels: approved, cncf-cla: yes, needs-ok-to-test, size/S

#9983 RSRC_DOCKER_STORAGE advice: remove typo and improve text
  pkg/minikube/reason/reason.go
Labels: approved, cncf-cla: yes, size/S

#9977 Added validation for --insecure-registry values
  cmd/minikube/cmd/start.go
Labels: approved, cncf-cla: yes, needs-ok-to-test, size/M

#10021 Replace fixed time wait with wait function for docker-env cmd
  cmd/minikube/cmd/docker-env.go
  pkg/minikube/bootstrapper/bsutil/kverify/api_server.go
Labels: cncf-cla: yes, needs-ok-to-test, size/M

#9959 When parsing release notes, parse up to the next version tag
  hack/jenkins/release_github_page.sh
Labels: approved, cncf-cla: yes, size/XS

#9999 iso: add XFS_QUOTA support to guest vm
  deploy/iso/minikube-iso/board/coreos/minikube/linux_defconfig
Labels: cncf-cla: yes, needs-ok-to-test, size/XS

#10024 Add spinner in creating container step
  pkg/minikube/style/style.go
Labels: approved, cncf-cla: yes, ok-to-test, size/XS

#9974 Adding warning for docker windows tunnel
  pkg/minikube/tunnel/kic/ssh_conn.go
  site/content/en/docs/handbook/accessing.md
Labels: approved, cncf-cla: yes, size/S

#10027 Fix docker reload issue in docker-env cmd
  pkg/provision/buildroot.go
  pkg/provision/ubuntu.go
Labels: cncf-cla: yes, ok-to-test, size/XS

#10032 ci: add back clean up
  hack/jenkins/common.sh
Labels: approved, cncf-cla: yes, ok-to-test, size/XS

#10018 The kubeadm bootstrapper now requires 1700M mem
  cmd/minikube/cmd/start_flags.go
  pkg/minikube/bootstrapper/kubeadm/kubeadm.go
Labels: approved, cncf-cla: yes, size/XS

#10034 Fix typo in the csi-hostpath-driver addon name
  site/content/en/docs/tutorials/volume_snapshots_and_csi.md
Labels: approved, cncf-cla: yes, needs-ok-to-test, size/XS

#9958 Remove obsolete 'vmwarefusion' driver, add friendly message
  cmd/minikube/cmd/start.go
  pkg/minikube/driver/driver.go
  pkg/minikube/machine/start.go
  pkg/minikube/registry/drvs/vmwarefusion/vmwarefusion.go
  pkg/minikube/registry/registry.go
Labels: approved, cncf-cla: yes, ok-to-test, size/M

#10037 The kubernetes memory requirement is for the total
  cmd/minikube/cmd/start_flags.go
Labels: approved, cncf-cla: yes, size/XS

#9538 Add --network flag to select docker network to run with docker driver
  cmd/minikube/cmd/start_flags.go
  pkg/drivers/kic/kic.go
  pkg/drivers/kic/oci/network_create.go
  pkg/drivers/kic/types.go
  pkg/minikube/config/types.go
  pkg/minikube/registry/drvs/docker/docker.go
  site/content/en/docs/commands/start.md
  test/integration/kic_custom_network_test.go
Labels: approved, cncf-cla: yes, ok-to-test, size/L

#10028 Change exit to warning if can't restart docker in docker-env cmd
  cmd/minikube/cmd/docker-env.go
Labels: approved, cncf-cla: yes, ok-to-test, size/XS

#10054 Update Korean translation
  translations/ko.json
  translations/strings.txt
Labels: cncf-cla: yes, needs-ok-to-test, ok-to-test, size/L

#9889 Use stable networking api in ingress-dns example
  deploy/addons/ingress-dns/README.md
  deploy/addons/ingress-dns/example/example.yaml
Labels: approved, cncf-cla: yes, needs-ok-to-test, size/S

#10049 Use appropriate ClusterDomain value in kubeadm KubeletConfiguration
  pkg/minikube/bootstrapper/bsutil/ktmpl/v1alpha3.go
  pkg/minikube/bootstrapper/bsutil/ktmpl/v1beta1.go
  pkg/minikube/bootstrapper/bsutil/ktmpl/v1beta2.go
  pkg/minikube/bootstrapper/bsutil/kubeadm_test.go
  pkg/minikube/bootstrapper/bsutil/testdata/v1.12/dns.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.13/dns.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.14/dns.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.15/dns.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.16/dns.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.17/dns.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.18/dns.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.19/dns.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.20/dns.yaml
  pkg/minikube/registry/drvs/vmwarefusion/vmwarefusion.go
Labels: cncf-cla: yes, ok-to-test, size/M

#10042 Fix docker driver cert copy on ubuntu's snap package manager
  pkg/minikube/command/kic_runner.go
Labels: approved, cncf-cla: yes, ok-to-test, size/S

#10058 fix "cache add" command error when not specifying :latest tag
  pkg/minikube/image/cache.go
  pkg/minikube/image/image.go
  pkg/minikube/image/image_test.go
  pkg/minikube/machine/cache_images.go
Labels: approved, cncf-cla: yes, kind/feature, ok-to-test, size/M

#10046 Kic: make sure NO_PROXY contains api endpoint
  deploy/kicbase/entrypoint
Labels: cncf-cla: yes, kind/feature, needs-ok-to-test, size/XS

#10053 Fix docker inspect network go template for network which doesn't have MTU
  pkg/drivers/kic/oci/network_create.go
  pkg/drivers/kic/oci/network_create_test.go
Labels: approved, cncf-cla: yes, ok-to-test, size/M

#10048 Added sch_htb, cls_fw, cls_matchall, act_connmark and ifb kernel modules
  deploy/iso/minikube-iso/board/coreos/minikube/linux_defconfig
Labels: approved, cncf-cla: yes, needs-ok-to-test, size/XS

#9955 Delete subnode's machine directories
  cmd/minikube/cmd/delete.go
Labels: approved, cncf-cla: yes, ok-to-test, size/S
