Repository kubernetes/minikube, pull requests merged in 2021-01, with the labels that each got.

#10077 Update go-containerregistry from 0.1.0 to 0.3.0
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, do-not-merge/hold, ok-to-test, size/XS

#10092 Handle podman installations without default bridge
  pkg/drivers/kic/oci/network_create.go
Labels: approved, cncf-cla: yes, ok-to-test, size/XS

#10094 replace badge on readme for build binaries only
  .github/workflows/build.yml
  README.md
  go.mod
  go.sum
  hack/update/golang_version/update_golang_version.go
Labels: approved, cncf-cla: yes, size/L

#10095 run iso and img test on baremetal instances
  .github/workflows/iso.yml
  .github/workflows/kic_image.yml
Labels: approved, cncf-cla: yes, size/XS

#10072 Fix test code not to create unsued config file
  pkg/minikube/config/profile_test.go
  pkg/minikube/config/testdata/.minikube/profiles/p1/config.json
  pkg/minikube/config/testdata/.minikube/profiles/p2_newformat/config.json
  pkg/minikube/config/testdata/.minikube/profiles/p3_empty/config.json
  pkg/minikube/config/testdata/.minikube/profiles/p4_invalid_file/config.json
  pkg/minikube/config/testdata/.minikube/profiles/p5_partial_config/config.json
Labels: approved, cncf-cla: yes, needs-ok-to-test, size/M

#10074 Update go-getter from 1.4.2 to 1.5.1
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/XS

#9937 Added documentation for Vmware driver on Windows
  site/content/en/docs/drivers/includes/vmware_windows_usage.inc
  site/content/en/docs/drivers/vmware.md
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/S

#9988 Performance bot wait for binary before run
  pkg/minikube/perf/binary.go
Labels: approved, cncf-cla: yes, needs-ok-to-test, size/XS

#10096 Change metrics-server pull policy to IfNotPresent
  deploy/addons/metrics-server/metrics-server-deployment.yaml.tmpl
Labels: cncf-cla: yes, ok-to-test, size/XS

#10084 Delete the existing cluster if guest driver mismatch
  cmd/minikube/cmd/start.go
Labels: cncf-cla: yes, ok-to-test, size/S

#10100 Add support for systemd cgroup to containerd runtime
  cmd/minikube/cmd/start_flags.go
  go.sum
  pkg/minikube/cruntime/containerd.go
  site/content/en/docs/commands/start.md
Labels: approved, cncf-cla: yes, ok-to-test, size/S

#10112 Remove systemd dependency from none driver
  pkg/drivers/none/none.go
Labels: approved, cncf-cla: yes, ok-to-test, size/S

#10114 refactor: migrate MachineName function to config package
  cmd/minikube/cmd/config/profile_list.go
  cmd/minikube/cmd/delete.go
  cmd/minikube/cmd/node_delete.go
  cmd/minikube/cmd/node_list.go
  cmd/minikube/cmd/node_start.go
  cmd/minikube/cmd/node_stop.go
  cmd/minikube/cmd/pause.go
  cmd/minikube/cmd/ssh-key.go
  cmd/minikube/cmd/start.go
  cmd/minikube/cmd/status.go
  cmd/minikube/cmd/stop.go
  cmd/minikube/cmd/unpause.go
  pkg/addons/addons.go
  pkg/minikube/bootstrapper/bsutil/kubelet.go
  pkg/minikube/bootstrapper/kubeadm/kubeadm.go
  pkg/minikube/cluster/cluster.go
  pkg/minikube/config/config_test.go
  pkg/minikube/config/profile.go
  pkg/minikube/driver/driver.go
  pkg/minikube/driver/driver_test.go
  pkg/minikube/machine/cache_images.go
  pkg/minikube/machine/cluster_test.go
  pkg/minikube/machine/delete.go
  pkg/minikube/machine/fix.go
  pkg/minikube/machine/ssh.go
  pkg/minikube/machine/start.go
  pkg/minikube/mustload/mustload.go
  pkg/minikube/node/node.go
  pkg/minikube/node/start.go
  pkg/minikube/registry/drvs/docker/docker.go
  pkg/minikube/registry/drvs/hyperkit/hyperkit.go
  pkg/minikube/registry/drvs/hyperv/hyperv.go
  pkg/minikube/registry/drvs/kvm2/kvm2.go
  pkg/minikube/registry/drvs/none/none.go
  pkg/minikube/registry/drvs/parallels/parallels.go
  pkg/minikube/registry/drvs/podman/podman.go
  pkg/minikube/registry/drvs/virtualbox/virtualbox.go
  pkg/minikube/registry/drvs/vmware/vmware.go
Labels: cncf-cla: yes, ok-to-test, size/L

#10109 Ignore non-socks5 ALL_PROXY env var when checking docker status
  cmd/minikube/cmd/docker-env.go
  cmd/minikube/cmd/docker-env_test.go
Labels: cncf-cla: yes, ok-to-test, size/M

#10131 Add spinner stop in err messages
  pkg/minikube/out/out.go
Labels: cncf-cla: yes, ok-to-test, size/XS

#10134 Add spinner stop in warn messages
  pkg/minikube/out/out.go
Labels: approved, cncf-cla: yes, size/XS

#9969 add multi-arch (arm64) support for docker/podman drivers
  Makefile
  pkg/drivers/kic/types.go
  pkg/minikube/registry/drvs/docker/docker.go
  site/content/en/docs/commands/start.md
Labels: approved, cncf-cla: yes, ok-to-test, size/M

#10118 avoid race condition in bootstrap certs for parallel runs
  go.mod
  go.sum
  pkg/minikube/machine/client.go
Labels: approved, cncf-cla: yes, ok-to-test, size/S

#10141 Removed exec permission from markdown files
  site/content/en/docs/_index.md
  site/content/en/docs/handbook/controls.md
  site/content/en/docs/tutorials/_index.md
Labels: approved, cncf-cla: yes, size/XS

#10137 Increase functional test DockerEnv timeout
  test/integration/functional_test.go
Labels: cncf-cla: yes, needs-ok-to-test, size/XS

#10115 Upgrade gopsutil & docker libs for macOS/arm64 compatibility
  cmd/minikube/cmd/start.go
  deploy/kicbase/entrypoint
  go.mod
  go.sum
  pkg/minikube/machine/info.go
  pkg/minikube/registry/drvs/docker/docker.go
  test/integration/helpers_test.go
Labels: approved, cncf-cla: yes, size/L

#10146 arm64: Fix offline start by removing obsolete arch suffix
  pkg/minikube/bootstrapper/images/images.go
Labels: approved, cncf-cla: yes, ok-to-test, size/M

#9985 Support arm64 in docker driver/integration tests
  pkg/minikube/bootstrapper/images/images.go
  test/integration/aaa_download_only_test.go
  test/integration/aab_offline_test.go
  test/integration/addons_test.go
  test/integration/driver_install_or_update_test.go
  test/integration/functional_test.go
  test/integration/main_test.go
  test/integration/preload_test.go
  test/integration/skaffold_test.go
Labels: approved, cncf-cla: yes, size/M

#10154 Upgrade Docker, from 20.10.1 to 20.10.2
  deploy/iso/minikube-iso/package/docker-bin/docker-bin.hash
  deploy/iso/minikube-iso/package/docker-bin/docker-bin.mk
Labels: approved, cncf-cla: yes, size/XS

#10162 Add some zh-CN translations
  translations/zh-CN.json
Labels: cncf-cla: yes, needs-ok-to-test, size/M

#10161 Remove duplicate json key in translations
  translations/ko.json
  translations/pl.json
  translations/zh-CN.json
Labels: cncf-cla: yes, needs-ok-to-test, size/XS

#10099 Add new driver "SSH" to bootstrap generic minkube clusters over ssh
  cmd/minikube/cmd/delete.go
  cmd/minikube/cmd/start.go
  cmd/minikube/cmd/start_flags.go
  pkg/drivers/ssh/ssh.go
  pkg/minikube/cluster/ip.go
  pkg/minikube/config/types.go
  pkg/minikube/driver/driver.go
  pkg/minikube/driver/driver_darwin.go
  pkg/minikube/driver/driver_linux.go
  pkg/minikube/driver/driver_test.go
  pkg/minikube/driver/driver_windows.go
  pkg/minikube/machine/info.go
  pkg/minikube/machine/machine.go
  pkg/minikube/machine/start.go
  pkg/minikube/out/register/register.go
  pkg/minikube/registry/drvs/init.go
  pkg/minikube/registry/drvs/ssh/ssh.go
  pkg/minikube/style/style.go
  pkg/minikube/style/style_enum.go
  site/content/en/docs/commands/start.md
  site/content/en/docs/drivers/includes/ssh_usage.inc
  site/content/en/docs/drivers/ssh.md
Labels: approved, cncf-cla: yes, ok-to-test, size/XL

#10066 MEP: CRI: Containerd by default
  enhancements/proposed/20201230-containerd-default/container-default.md
Labels: approved, cncf-cla: yes, size/M

#10187 Avoid warning about the suggested memory size
  cmd/minikube/cmd/start_flags.go
Labels: approved, cncf-cla: yes, size/XS

#9979 Add github action to run linux/arm64 integration tests
  .github/workflows/iso.yml
  .github/workflows/kic_image.yml
  .github/workflows/master.yml
  .github/workflows/pr.yml
  Makefile
  hack/jenkins/common.sh
Labels: approved, cncf-cla: yes, size/L

#10195 Release KIC Base and ISO
  Makefile
  pkg/drivers/kic/types.go
Labels: approved, cncf-cla: yes, ok-to-test, size/XS

#10207 Generate docs; unit tests failing at HEAD
  site/content/en/docs/commands/start.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#10211 integration test: improve TestUpgrade to use legacy kubeconfig
  test/integration/version_upgrade_test.go
Labels: approved, cncf-cla: yes, ok-to-test, size/M

#10194 update k8s version to v1.20.3-rc.0
  hack/update/kubernetes_version/templates/v1beta2/containerd-api-port.yaml
  hack/update/kubernetes_version/templates/v1beta2/containerd-pod-network-cidr.yaml
  hack/update/kubernetes_version/templates/v1beta2/containerd.yaml
  hack/update/kubernetes_version/templates/v1beta2/crio-options-gates.yaml
  hack/update/kubernetes_version/templates/v1beta2/crio.yaml
  hack/update/kubernetes_version/templates/v1beta2/default.yaml
  hack/update/kubernetes_version/templates/v1beta2/dns.yaml
  hack/update/kubernetes_version/templates/v1beta2/image-repository.yaml
  hack/update/kubernetes_version/templates/v1beta2/options.yaml
  pkg/minikube/constants/constants.go
  site/content/en/docs/commands/start.md
Labels: cncf-cla: yes, ok-to-test, size/S

#10212 Split PROVIDER_DOCKER_ERROR into more specific reason codes
  cmd/minikube/cmd/start.go
  pkg/minikube/registry/drvs/docker/docker.go
  pkg/minikube/registry/registry.go
Labels: approved, cncf-cla: yes, size/M

#10206 Fix failing TestStartStop/serial/VerifyKubernetesImages test
  test/integration/start_stop_delete_test.go
Labels: approved, cncf-cla: yes, ok-to-test, size/S

#10220 add release notes for v1.17.0
  CHANGELOG.md
  Makefile
Labels: approved, cncf-cla: yes, ok-to-test, size/M

#10223 Fix TestDownloadOnlyKic so it takes container runtime into account
  cmd/minikube/cmd/start_flags.go
  pkg/minikube/constants/constants.go
  test/integration/aaa_download_only_test.go
  test/integration/main_test.go
Labels: approved, cncf-cla: yes, ok-to-test, size/S

#10221 configure the crictl yaml file to avoid the warning
  pkg/minikube/cruntime/docker.go
  test/integration/start_stop_delete_test.go
Labels: approved, cncf-cla: yes, ok-to-test, size/S

#10225 Fix TestForceSystemdFlag tests on containerd
  test/integration/docker_test.go
Labels: approved, cncf-cla: yes, ok-to-test, size/M

#10226 Only run TestDockerFlags with docker container runtime
  test/integration/docker_test.go
Labels: approved, cncf-cla: yes, ok-to-test, size/XS

#10227 Only run integration tests that depend on docker-env with docker container runtime
  test/integration/functional_test.go
  test/integration/skaffold_test.go
Labels: approved, cncf-cla: yes, ok-to-test, size/XS

#9998 fixing debian and arch concurrent multiarch builds
  Makefile
Labels: approved, cncf-cla: yes, needs-ok-to-test, size/M

#10004 Makefile: Make Debian/RedHat package revisions settable
  Makefile
Labels: approved, cncf-cla: yes, size/S

#10235 Add resource requests & limits for mysql test
  test/integration/testdata/mysql.yaml
Labels: cncf-cla: yes, needs-ok-to-test, size/XS

#10196 Only run TestOffline/TestDownloadOnly for specified container runtime
  test/integration/aaa_download_only_test.go
  test/integration/aab_offline_test.go
Labels: approved, cncf-cla: yes, ok-to-test, size/L

#10257 Set DEB_REVISION=2 and update release docs for deb/rpm revisions
  Makefile
  site/content/en/docs/contrib/releasing/binaries.md
Labels: approved, cncf-cla: yes, size/XS

#10230 Fix TestFunctional subtests to run for all three runtimes
  test/integration/functional_test.go
Labels: approved, cncf-cla: yes, ok-to-test, size/S

#10193 Split up TestStartStop by container runtime
  test/integration/main_test.go
  test/integration/start_stop_delete_test.go
Labels: approved, cncf-cla: yes, ok-to-test, size/S

#10232 Add JSON step for CNI to fix failing TestJSONOutput test
  pkg/minikube/bootstrapper/kubeadm/kubeadm.go
  pkg/minikube/out/register/register.go
  test/integration/json_output_test.go
Labels: approved, cncf-cla: yes, ok-to-test, size/XS

#10219 refactor download only test for better visibility
  test/integration/aaa_download_only_test.go
Labels: approved, cncf-cla: yes, ok-to-test, size/L

#10269 Make the ssh driver opt-in and not default
  pkg/minikube/registry/drvs/ssh/ssh.go
Labels: approved, cncf-cla: yes, size/XS

#10261 Run CNI tests on containerd
  test/integration/net_test.go
Labels: approved, cncf-cla: yes, ok-to-test, size/S

#10251 Update addons.md
  site/content/en/docs/commands/addons.md
Labels: cncf-cla: yes, needs-ok-to-test, size/XS

#10270 The gopsutil cpu implementation changed in v3
  cmd/minikube/cmd/start.go
  pkg/minikube/machine/info.go
Labels: approved, cncf-cla: yes, ok-to-test, size/XS

#10273 Run make generate-docs
  site/content/en/docs/commands/addons.md
Labels: approved, cncf-cla: yes, size/XS

#10274 Unhide --schedule flag for scheduled stop
  cmd/minikube/cmd/stop.go
  site/content/en/docs/commands/stop.md
Labels: approved, cncf-cla: yes, size/XS

#10275 Fix small bug in TestStartStop
  test/integration/start_stop_delete_test.go
Labels: approved, cncf-cla: yes, ok-to-test, size/XS

#10145 ci: add full integration tests for Docker on Windows
  hack/jenkins/minikube_set_pending.sh
  hack/jenkins/setup_docker_desktop_windows.ps1
  hack/jenkins/windows_integration_test_docker.ps1
Labels: approved, cncf-cla: yes, ok-to-test, size/M

#10255 install losetup from util-linux in the ISO
  deploy/iso/minikube-iso/configs/minikube_defconfig
Labels: approved, cncf-cla: yes, needs-ok-to-test, size/XS

#10202 Add make targets for darwin/arm64 binaries
  Makefile
  hack/jenkins/minikube_cross_build_and_upload.sh
  hack/jenkins/release_build_and_upload.sh
Labels: approved, cncf-cla: yes, ok-to-test, size/M

#10286 Revert "install losetup from util-linux in the ISO"
  deploy/iso/minikube-iso/configs/minikube_defconfig
Labels: approved, cncf-cla: yes, size/XS

#10284 Add more debug output to the ARM64 GitHub Actions runner
  .github/workflows/master.yml
  .github/workflows/pr.yml
Labels: approved, cncf-cla: yes, size/XS

#10285 Update BUILD_IMAGE version to 1.16-rc
  Makefile
Labels: approved, cncf-cla: yes, ok-to-test, size/XS

#10283 Bump minikube version to 1.17.1
  CHANGELOG.md
  Makefile
Labels: approved, cncf-cla: yes, ok-to-test, size/M

#10305 Fix 1.17.1 Changelog
  CHANGELOG.md
Labels: cncf-cla: yes, size/XS

#10300 fail docker tests immediately of docker doesn't start up
  hack/jenkins/setup_docker_desktop_windows.ps1
  hack/jenkins/windows_integration_test_docker.ps1
Labels: approved, cncf-cla: yes, ok-to-test, size/S

#10304 Fix 'make check-release' in a freshly cloned repo
  Makefile
Labels: approved, cncf-cla: yes, ok-to-test, size/S

#10176 Add go implementation of stress tests
  Makefile
  test/stress/main_test.go
  test/stress/stress_test.go
Labels: approved, cncf-cla: yes, size/L
