Repository kubernetes/minikube, pull requests merged in 2021-06, with the labels that each got.

#11504 Fix delete command for paused kic driver with containerd/crio runtime
  cmd/minikube/cmd/delete.go
Labels: approved, cncf-cla: yes, ok-to-test, size/M

#11564 make generate-docs
  translations/de.json
  translations/es.json
  translations/fr.json
  translations/ja.json
  translations/ko.json
  translations/pl.json
  translations/strings.txt
  translations/zh-CN.json
Labels: approved, cncf-cla: yes, size/XS

#11559 try image without sha before failing
  pkg/drivers/kic/types.go
Labels: approved, cncf-cla: yes, ok-to-test, size/XS

#11482 Run addCoreDNSEntry in Go func
  pkg/minikube/node/start.go
Labels: approved, cncf-cla: yes, ok-to-test, size/S

#11528 Change PreloadExists to report no preload for BareMetal drivers
  cmd/minikube/cmd/start.go
  hack/preload-images/preload_images.go
  pkg/drivers/kic/kic.go
  pkg/minikube/bootstrapper/kubeadm/kubeadm.go
  pkg/minikube/cruntime/containerd.go
  pkg/minikube/cruntime/crio.go
  pkg/minikube/cruntime/cruntime.go
  pkg/minikube/cruntime/docker.go
  pkg/minikube/download/download_test.go
  pkg/minikube/download/preload.go
  pkg/minikube/driver/auxdriver/install.go
  pkg/minikube/driver/auxdriver/install_test.go
  pkg/minikube/driver/auxdriver/version.go
  pkg/minikube/driver/auxdriver/version_test.go
  pkg/minikube/driver/driver.go
  pkg/minikube/node/cache.go
  pkg/minikube/node/start.go
  test/integration/aaa_download_only_test.go
  test/integration/driver_install_or_update_test.go
Labels: approved, cncf-cla: yes, ok-to-test, size/L

#11471 Update registry.md with instructions to avoid common pitfalls
  site/content/en/docs/handbook/registry.md
Labels: cncf-cla: yes, needs-ok-to-test, size/XS

#11454 bug: return error on invalid function name in extract.TranslatableStrings
  pkg/minikube/extract/extract.go
  pkg/minikube/extract/extract_test.go
Labels: approved, cncf-cla: yes, needs-ok-to-test, size/S

#11566 Bump minikube version to v1.21.0-beta.0
  CHANGELOG.md
  Makefile
Labels: approved, cncf-cla: yes, ok-to-test, size/M

#11569 fix makefile typo
  Makefile
Labels: approved, cncf-cla: yes, size/XS

#11575 Add FAQ on how to enable beta notifications
  site/content/en/docs/faq/_index.md
Labels: cncf-cla: yes, size/XS

#11567 bump gopogh to v0.8.0
  .github/workflows/master.yml
  .github/workflows/pr.yml
  .github/workflows/pr_verified.yaml
  hack/jenkins/common.sh
  hack/jenkins/windows_integration_test_docker.ps1
  hack/jenkins/windows_integration_test_hyperv.ps1
  hack/jenkins/windows_integration_test_virtualbox.ps1
  hack/update/gopogh_version/update_gopogh_version.go
Labels: cncf-cla: yes, ok-to-test, size/M

#11584 Modify MetricsServer to use v1 api version (instead of v1beta1).
  deploy/addons/metrics-server/metrics-apiservice.yaml.tmpl
Labels: cncf-cla: yes, ok-to-test, size/XS

#11600 add spowelljr as reviewer/approver
  OWNERS
Labels: approved, cncf-cla: yes, size/XS

#11587 add more polish translations
  translations/pl.json
Labels: approved, cncf-cla: yes, needs-ok-to-test, size/L

#11583 Ensure Windows integration tests are ephemeral
  hack/jenkins/windows_integration_setup.ps1
  hack/jenkins/windows_integration_teardown.ps1
  hack/jenkins/windows_integration_test_docker.ps1
  hack/jenkins/windows_integration_test_hyperv.ps1
  hack/jenkins/windows_integration_test_virtualbox.ps1
Labels: cncf-cla: yes, ok-to-test, size/M

#11561 Restore "containerd: upgrade io.containerd.runtime.v1.linux to io.containerd.runc.v2 (suppot cgroup v2)"
  pkg/minikube/cruntime/containerd.go
  test/integration/docker_test.go
  test/integration/status_test.go
Labels: approved, cncf-cla: yes, ok-to-test, size/S

#11601 Prevent misleading "save to tar file succeeded" message from being logged
  pkg/minikube/image/cache.go
Labels: approved, cncf-cla: yes, ok-to-test, size/XS

#11604 Restructure TestErrorSpam to decrease test duration
  test/integration/error_spam_test.go
Labels: approved, cncf-cla: yes, ok-to-test, size/L

#11613 Update triage.md
  site/content/en/docs/contrib/triage.md
Labels: approved, cncf-cla: yes, size/XS

#11617 Revert "Restore "containerd: upgrade io.containerd.runtime.v1.linux to io.containerd.runc.v2 (suppot cgroup v2)""
  pkg/minikube/cruntime/containerd.go
  test/integration/docker_test.go
  test/integration/status_test.go
Labels: approved, cncf-cla: yes, ok-to-test, size/S

#11616 Delete `minikube-integration` folder in case last test failed to delete it
  hack/jenkins/windows_integration_setup.ps1
  hack/jenkins/windows_integration_teardown.ps1
Labels: approved, cncf-cla: yes, ok-to-test, size/S

#11624 Update FAQ
  site/content/en/docs/faq/_index.md
Labels: approved, cncf-cla: yes, size/XS

#11618 site: add alternative certs dir
  site/content/en/docs/handbook/vpn_and_proxy.md
Labels: cncf-cla: yes, needs-ok-to-test, size/XS

#11637 add contribution leaderboard for v1.21.0
  site/content/en/docs/contrib/leaderboard/v1.21.0.html
Labels: approved, cncf-cla: yes, size/L

#11638 site: Cleanup FAQ formatting and grammar.
  site/content/en/docs/faq/_index.md
Labels: approved, cncf-cla: yes, size/M

#11602 Create a system for generating public flake rate reporting.
  hack/jenkins/common.sh
  hack/jenkins/test-flake-chart/collect_data_manual.sh
  hack/jenkins/test-flake-chart/compute_flake_rate.go
  hack/jenkins/test-flake-chart/compute_flake_rate_test.go
  hack/jenkins/test-flake-chart/flake_chart.html
  hack/jenkins/test-flake-chart/flake_chart.js
  hack/jenkins/test-flake-chart/optimize_data.sh
  hack/jenkins/test-flake-chart/process_data.sh
  hack/jenkins/test-flake-chart/report_flakes.sh
  hack/jenkins/test-flake-chart/upload_tests.sh
  hack/jenkins/upload_integration_report.sh
Labels: cncf-cla: yes, size/XXL

#11629 Add timeout to apiserver health check.
  pkg/minikube/bootstrapper/bsutil/kverify/api_server.go
Labels: cncf-cla: yes, ok-to-test, size/XS

#11656 Remove duplicated translations
  site/content/en/docs/handbook/controls.md
  translations/ko.json
  translations/pl.json
  translations/zh-CN.json
Labels: approved, cncf-cla: yes, needs-ok-to-test, size/S

#11653 Fix a download link to use arm64 instead of amd64
  cmd/minikube/cmd/root.go
Labels: approved, cncf-cla: yes, ok-to-test, size/XS

#11660 run `make generate-docs`
  translations/de.json
  translations/es.json
  translations/fr.json
  translations/ja.json
  translations/ko.json
  translations/pl.json
  translations/strings.txt
  translations/zh-CN.json
Labels: approved, cncf-cla: yes, size/S

#11662 Fix collect_data_manual not being formatted correctly.
  hack/jenkins/test-flake-chart/collect_data_manual.sh
Labels: approved, cncf-cla: yes, size/XS

#11663 add local-kicbase make target
  Makefile
Labels: approved, cncf-cla: yes, size/S

#11675 Stop using sudo for check_install_gh
  hack/jenkins/test-flake-chart/report_flakes.sh
Labels: approved, cncf-cla: yes, ok-to-test, size/XS

#11684 Update flake chart colors
  hack/jenkins/test-flake-chart/flake_chart.js
Labels: cncf-cla: yes, ok-to-test, size/XS

#11423 Added Mock of Minikube Delete Profiles Test portion.
  cmd/minikube/cmd/delete.go
  cmd/minikube/cmd/delete_test.go
Labels: approved, cncf-cla: yes, do-not-merge/work-in-progress, needs-ok-to-test, size/M

#11680 site: how to run minikube on remote network
  site/content/en/docs/faq/_index.md
Labels: approved, cncf-cla: yes, size/S

#11671 Use goembed instead of go-bindata for embedding addon config files
  .gitignore
  Makefile
  deploy/addons/assets.go
  pkg/minikube/assets/addons.go
  pkg/minikube/assets/vm_assets.go
  site/content/en/docs/contrib/addons.en.md
Labels: approved, cncf-cla: yes, ok-to-test, size/XL

#11683 Fix flake rates being commented about when no failed tests are present.
  hack/jenkins/test-flake-chart/report_flakes.sh
Labels: approved, cncf-cla: yes, ok-to-test, size/XS

#11693 Change minimum required Go version to 1.16 in docs
  Makefile
  site/content/en/docs/contrib/building/binaries.md
  site/content/en/docs/contrib/building/iso.md
Labels: approved, cncf-cla: yes, needs-ok-to-test, size/XS

#11691 Use goembed for translation files
  .gitignore
  Makefile
  pkg/minikube/translate/translate.go
  translations/translations.go
Labels: cncf-cla: yes, ok-to-test, size/M

#11677 Automatically run `make generate-docs` after every PR merge
  .github/workflows/docs.yml
  .github/workflows/time-to-k8s.yml
  cmd/minikube/cmd/generate-docs_test.go
  hack/generate_docs.sh
  hack/update/golang_version/update_golang_version.go
Labels: approved, cncf-cla: yes, size/L

#11678 change registery_mirror to registery-mirror
  cmd/minikube/cmd/start.go
Labels: cncf-cla: yes, ok-to-test, size/XS

#11698 Fix translations not looking for correct file.
  pkg/minikube/translate/translate.go
  site/content/en/docs/contrib/tests.en.md
  test/integration/functional_test.go
Labels: approved, cncf-cla: yes, ok-to-test, size/M

#11690 Move daemon cache check before file cache check
  pkg/minikube/node/cache.go
Labels: approved, cncf-cla: yes, ok-to-test, size/S

#11704 ISO: Upgrade podman to 3.1.2
  deploy/iso/minikube-iso/package/podman/containers.conf
  deploy/iso/minikube-iso/package/podman/podman.hash
  deploy/iso/minikube-iso/package/podman/podman.mk
Labels: approved, cncf-cla: yes, size/M

#11711 Revert "ISO: Upgrade podman to 3.1.2"
  deploy/iso/minikube-iso/package/podman/containers.conf
  deploy/iso/minikube-iso/package/podman/podman.hash
  deploy/iso/minikube-iso/package/podman/podman.mk
Labels: approved, cncf-cla: yes, size/M

#11694 Fix intersected log boxes when running with --alsologtostderr
  pkg/minikube/out/out.go
Labels: approved, cncf-cla: yes, size/XS

#11665 Upgrade gcp-auth-webhook to v0.0.6
  pkg/minikube/assets/addons.go
Labels: approved, cncf-cla: yes, ok-to-test, size/XS

#11668 Remove unused config options
  cmd/minikube/cmd/config/config.go
  cmd/minikube/cmd/root.go
  pkg/minikube/config/config.go
  site/content/en/docs/commands/config.md
Labels: cncf-cla: yes, ok-to-test, size/M

#11576 Fix embed-certs global config
  cmd/minikube/cmd/config/config.go
  cmd/minikube/cmd/root.go
  cmd/minikube/cmd/start.go
  pkg/minikube/config/config.go
  site/content/en/docs/commands/config.md
Labels: approved, cncf-cla: yes, ok-to-test, size/XS

#11696 Proposal for minikube tips
  enhancements/proposed/20210618-tips/tips.md
Labels: cncf-cla: yes, needs-ok-to-test, size/L

#11672 site: Add tutorial for user flag
  site/content/en/docs/tutorials/user_flag.md
Labels: approved, cncf-cla: yes, size/M

#11721 let windows users use the LC_ALL env var to set locale
  pkg/minikube/translate/translate.go
Labels: approved, cncf-cla: yes, size/S

#11728 Improve French locale
  translations/fr.json
Labels: approved, cncf-cla: yes, needs-ok-to-test, size/XXL

#11667 Do not return an error from Systemd.ForceStop(svc) if svc is already stopped
  pkg/minikube/sysinit/systemd.go
Labels: approved, cncf-cla: yes, ok-to-test, size/S

#11726 Upgrade docker go module from 19.03 to 20.10
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, ok-to-test, size/S

#11732 fix french translation
  translations/fr.json
Labels: approved, cncf-cla: yes, size/S

#11723 fix generate_docs bugs
  hack/generate_docs.sh
Labels: approved, cncf-cla: yes, size/XS

#11734 fix french
  translations/fr.json
Labels: approved, cncf-cla: yes, size/XS

#11720 bump k8s lib to v1.21.2
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, ok-to-test, size/L

#11736 fix generate-docs bugs part 2
  hack/generate_docs.sh
Labels: approved, cncf-cla: yes, size/XS

#11744 Fix running a non-existent command in upload_integration_report
  hack/jenkins/upload_integration_report.sh
Labels: approved, cncf-cla: yes, ok-to-test, size/XS

#11746 Add GitHub Action to check if translations are valid
  .github/workflows/docs.yml
  .github/workflows/time-to-k8s.yml
  .github/workflows/translations.yml
  hack/update/golang_version/update_golang_version.go
  pkg/minikube/translate/translate_test.go
  translations/de.json
  translations/es.json
  translations/fr.json
  translations/ja.json
  translations/ko.json
  translations/pl.json
Labels: approved, cncf-cla: yes, size/L

#11731 Move node config deletion out of drainNode and into Delete
  pkg/minikube/node/node.go
  site/content/en/docs/contrib/tests.en.md
  test/integration/multinode_test.go
Labels: approved, cncf-cla: yes, ok-to-test, size/M

#11632 Restore "containerd: upgrade io.containerd.runtime.v1.linux to io.containerd.runc.v2 (suppot cgroup v2)" #2
  Makefile
  deploy/iso/minikube-iso/package/containerd-bin/containerd.service
  pkg/minikube/bootstrapper/bsutil/kverify/api_server.go
  pkg/minikube/bootstrapper/kubeadm/kubeadm.go
  pkg/minikube/cluster/pause.go
  pkg/minikube/cruntime/containerd.go
  pkg/minikube/cruntime/cruntime.go
  pkg/minikube/download/iso.go
  pkg/minikube/node/advice.go
  pkg/minikube/node/start.go
  pkg/minikube/sysinit/openrc.go
  pkg/minikube/sysinit/systemd.go
  site/content/en/docs/commands/start.md
  test/integration/docker_test.go
  test/integration/version_upgrade_test.go
Labels: approved, cncf-cla: yes, ok-to-test, size/L

#11756 Fix French translation
  translations/fr.json
Labels: cncf-cla: yes, needs-ok-to-test, size/S

#11742 Move testCpCmd to helpers_test
  test/integration/functional_test.go
  test/integration/helpers_test.go
Labels: cncf-cla: yes, ok-to-test, size/L

#11761 Make flake rates only report hashes once and add links to the gopogh files
  hack/jenkins/test-flake-chart/flake_chart.js
Labels: approved, cncf-cla: yes, size/S

#11674 Allow running amd64 binary on M1
  cmd/minikube/cmd/root.go
  pkg/minikube/detect/detect.go
  pkg/minikube/download/binary.go
  pkg/minikube/download/preload.go
  pkg/minikube/machine/cache_binaries.go
  pkg/minikube/node/cache.go
Labels: approved, cncf-cla: no, ok-to-test, size/M

#11769 Create loading bar while downloading flake chart data and add better error UI.
  hack/jenkins/test-flake-chart/flake_chart.js
Labels: approved, cncf-cla: yes, size/M

#11755 Improve finding of local network containing the ip address
  pkg/network/network.go
Labels: approved, cncf-cla: yes, ok-to-test, size/M

#11743 Add auto pause on arm64 image
  Makefile
  deploy/kicbase/Dockerfile
  pkg/addons/addons_autopause.go
Labels: approved, cncf-cla: yes, ok-to-test, size/M

#11603 Fix --base-image caching for images specified by name:tag
  pkg/minikube/download/image.go
Labels: approved, cncf-cla: yes, ok-to-test, size/M

#11753 Add maintainer column to addons list
  cmd/minikube/cmd/config/addons_list.go
  pkg/minikube/assets/addons.go
Labels: approved, cncf-cla: yes, ok-to-test, size/M

#11766 Create page with all tests for an environment in flake rate charts
  hack/jenkins/test-flake-chart/flake_chart.html
  hack/jenkins/test-flake-chart/flake_chart.js
Labels: approved, cncf-cla: yes, size/L

#11688 Upgrade Buildroot to 2021.02 LTS with Linux 4.19
  Makefile
  deploy/iso/minikube-iso/board/coreos/minikube/patches/go/1.15.13/dist-generate-stub-go.mod-in-workdir.patch
  deploy/iso/minikube-iso/configs/minikube_defconfig
  deploy/iso/minikube-iso/package/crio-bin/crio-bin.hash
  pkg/minikube/download/iso.go
  site/content/en/docs/commands/start.md
Labels: approved, cncf-cla: yes, ok-to-test, size/L

#11692 Add ability to pass 'max' value to memory and cpus flags
  cmd/minikube/cmd/config/config.go
  cmd/minikube/cmd/config/validations.go
  cmd/minikube/cmd/start.go
  cmd/minikube/cmd/start_flags.go
  pkg/minikube/constants/constants.go
  site/content/en/docs/commands/start.md
  site/content/en/docs/faq/_index.md
  translations/de.json
  translations/es.json
  translations/fr.json
  translations/ja.json
  translations/ko.json
  translations/pl.json
  translations/strings.txt
  translations/zh-CN.json
Labels: approved, cncf-cla: yes, ok-to-test, size/L

#11787 run `make generate-docs`
  translations/de.json
  translations/es.json
  translations/fr.json
  translations/ja.json
  translations/ko.json
  translations/pl.json
  translations/strings.txt
  translations/zh-CN.json
Labels: approved, cncf-cla: yes, size/M

#11784 Add comment to report_flakes.sh to see environment flake charts
  hack/jenkins/test-flake-chart/report_flakes.sh
Labels: approved, cncf-cla: yes, ok-to-test, size/XS

#11795 Add time-to-k8s benchmark for v1.20.0
  site/static/images/benchmarks/timeToK8s/v1.20.0.png
Labels: approved, cncf-cla: yes, size/XS

#11796 Add time-to-k8s benchmark for v1.21.0
  site/content/en/docs/benchmarks/timeToK8s/v1.21.0.md
  site/static/images/benchmarks/timeToK8s/v1.21.0.png
Labels: approved, cncf-cla: yes, size/XS

#11797 Make minor changes to time-to-k8s benchmarking
  .github/workflows/time-to-k8s.yml
  hack/benchmark/time-to-k8s/time-to-k8s.sh
Labels: approved, cncf-cla: yes, size/XS

#11799 Revert ISO changes
  Makefile
  deploy/iso/minikube-iso/board/coreos/minikube/patches/go/1.15.13/dist-generate-stub-go.mod-in-workdir.patch
  deploy/iso/minikube-iso/configs/minikube_defconfig
  deploy/iso/minikube-iso/package/crio-bin/crio-bin.hash
  pkg/minikube/download/iso.go
  site/content/en/docs/commands/start.md
Labels: approved, cncf-cla: yes, ok-to-test, size/L

#11793 Create new page on website containing all integration test chart links.
  site/content/en/docs/contrib/test_flakes.en.md
Labels: cncf-cla: yes, size/S

#11807 fix crio-bin hash
  deploy/iso/minikube-iso/package/crio-bin/crio-bin.hash
Labels: approved, cncf-cla: yes, size/XS

#11809 Update test_flakes.en.md
  site/content/en/docs/contrib/test_flakes.en.md
Labels: approved, cncf-cla: yes, size/XS

#11804 Lower parallelism when testing on Windows
  test/integration/main_test.go
Labels: approved, cncf-cla: yes, ok-to-test, size/XS

#11791 Bump version and update changelog for beta release 1.22.0-beta.0
  CHANGELOG.md
  Makefile
Labels: approved, cncf-cla: yes, ok-to-test, size/M

#11814 fix generate-docs github action
  .github/workflows/docs.yml
  hack/generate_docs.sh
Labels: approved, cncf-cla: yes, size/M

#11822 Fixing previously renamed func from GetAllVersionsFromURL to AllVersionsFromURL
  deploy/minikube/release_sanity_test.go
Labels: approved, cncf-cla: yes, size/XS

#11827 only run gendocs workflow if there are changes
  .github/workflows/docs.yml
Labels: approved, cncf-cla: yes, size/XS

#11828 fix gendocs workflow syntax
  .github/workflows/docs.yml
Labels: approved, cncf-cla: yes, size/XS

#11829 Update vmware driver install instructions for Mac
  site/content/en/docs/drivers/includes/vmware_macos_usage.inc
Labels: approved, cncf-cla: yes, kind/documentation, needs-ok-to-test, size/XS

#11815 Fix "kubelet Default-Start contains no runlevels" error
  pkg/minikube/sysinit/systemd.go
Labels: approved, cncf-cla: yes, ok-to-test, size/XS

#11811 bump go mod libs manually
  cmd/minikube/cmd/start.go
  cmd/minikube/cmd/start_flags.go
  cmd/minikube/cmd/start_test.go
  go.mod
  go.sum
  hack/preload-images/kubernetes.go
  hack/update/github.go
  pkg/drivers/kic/oci/network.go
  pkg/minikube/bootstrapper/bsutil/extraconfig.go
  pkg/minikube/bootstrapper/bsutil/kubeadm.go
  pkg/minikube/bootstrapper/bsutil/versions.go
  pkg/minikube/bootstrapper/bsutil/versions_test.go
  pkg/minikube/bootstrapper/images/images.go
  pkg/minikube/bootstrapper/images/images_test.go
  pkg/minikube/bootstrapper/images/kubeadm.go
  pkg/minikube/bootstrapper/kubeadm/kubeadm.go
  pkg/minikube/config/types.go
  pkg/minikube/cruntime/containerd.go
  pkg/minikube/cruntime/crio.go
  pkg/minikube/cruntime/cruntime.go
  pkg/minikube/cruntime/docker.go
  pkg/minikube/download/binary.go
  pkg/minikube/download/driver.go
  pkg/minikube/driver/auxdriver/install.go
  pkg/minikube/driver/auxdriver/version.go
  pkg/minikube/driver/auxdriver/version_test.go
  pkg/minikube/node/start.go
  pkg/minikube/notify/notify.go
  pkg/minikube/notify/notify_test.go
  pkg/minikube/reason/k8s.go
  pkg/minikube/registry/drvs/podman/podman.go
  pkg/perf/monitor/github.go
  pkg/util/retry/retry.go
  pkg/util/utils.go
  pkg/util/utils_test.go
  pkg/version/version.go
  test/integration/driver_install_or_update_test.go
  test/integration/helpers_test.go
Labels: approved, cncf-cla: yes, ok-to-test, size/L

#11816 Report flakes only after synchronizing all integration tests
  hack/jenkins/common.sh
  hack/jenkins/test-flake-chart/report_flakes.sh
  hack/jenkins/test-flake-chart/sync_tests.sh
  hack/jenkins/test-flake-chart/upload_tests.sh
  hack/jenkins/upload_integration_report.sh
  hack/jenkins/windows_integration_test_docker.ps1
Labels: cncf-cla: yes, ok-to-test, size/L

#11767 Update release scripts to build arm64 version of kvm2 driver
  Makefile
  hack/jenkins/release_build_and_upload.sh
  installers/linux/kvm/Dockerfile.amd64
  installers/linux/kvm/Dockerfile.arm64
Labels: approved, cncf-cla: yes, size/L

#11803 try less parallelization for macOS tests
  hack/jenkins/osx_integration_tests_docker.sh
  test/integration/main_test.go
Labels: approved, cncf-cla: yes, ok-to-test, size/S

#11841 remove ugly error message from kicbase and ISO autobuild
  hack/jenkins/build_iso.sh
  hack/jenkins/kicbase_auto_build.sh
Labels: approved, cncf-cla: yes, size/M

#11844 Fix Makefile 'drivers' target
  Makefile
Labels: approved, cncf-cla: yes, size/XS

#11840 add FAQ how to create clusters
  site/content/en/docs/faq/_index.md
Labels: approved, cncf-cla: yes, size/S

#11846 Fix kvm2-arm64 build error
  installers/linux/kvm/Dockerfile.arm64
Labels: approved, cncf-cla: yes, ok-to-test, size/S

#11847 Improve Docker Windows integration clean slate
  hack/jenkins/windows_integration_test_docker.ps1
Labels: approved, cncf-cla: yes, size/XS
