Repository kubernetes/minikube, pull requests merged in 2021-04, with the labels that each got.

#10973 [Unit Test] Fix unit test failing boilerplate, TestGenerateDocs
  cmd/minikube/cmd/completion.go
  hack/jenkins/cloud_shell_functional_tests_docker.sh
Labels: approved, area/testing, cncf-cla: yes, kind/bug, kind/failing-test, needs-ok-to-test, size/XS

#10886 Added error check for extra quotation for extra-config.
  pkg/minikube/config/extra_options.go
  pkg/minikube/config/extra_options_test.go
Labels: cncf-cla: yes, needs-ok-to-test, size/M

#10968 Avoid logging 'kubeconfig endpoint' error when cluster is 'starting'
  cmd/minikube/cmd/status.go
Labels: approved, cncf-cla: yes, needs-ok-to-test, size/XS

#10974 iso: make sure to capture failures through pipes
  hack/jenkins/build_iso.sh
Labels: approved, cncf-cla: yes, size/XS

#10975 change crio-bin checksum since it changed upstream
  deploy/iso/minikube-iso/package/crio-bin/crio-bin.hash
Labels: approved, cncf-cla: yes, size/XS

#10217 iso: enable Network Block Device support
  Makefile
  deploy/iso/minikube-iso/board/coreos/minikube/linux_defconfig
  pkg/minikube/download/iso.go
  site/content/en/docs/commands/start.md
Labels: cncf-cla: yes, ok-to-test, size/XS

#10979 Fix gcp-auth tests for cloud shell
  pkg/minikube/detect/detect.go
  test/integration/addons_test.go
Labels: approved, cncf-cla: yes, ok-to-test, size/S

#10648 BuildKit 0.8.2
  deploy/iso/minikube-iso/package/buildkit-bin/buildkit-bin.hash
  deploy/iso/minikube-iso/package/buildkit-bin/buildkit-bin.mk
  deploy/kicbase/Dockerfile
Labels: approved, cncf-cla: yes, ok-to-test, size/S

#10985 Fix CNI issue related to picking up wrong CNI
  cmd/minikube/cmd/start_flags.go
  pkg/drivers/kvm/domain.go
  pkg/minikube/cni/cni.go
  pkg/minikube/cni/kindnet.go
  site/content/en/docs/commands/start.md
  site/content/en/docs/tutorials/includes/hello-deployment.yaml
  site/content/en/docs/tutorials/multi_node.md
  test/integration/multinode_test.go
  test/integration/testdata/multinodes/multinode-pod-dns-test.yaml
Labels: cncf-cla: yes, ok-to-test, size/L

#10983 upgrade spinner library
  go.mod
  go.sum
Labels: cncf-cla: yes, ok-to-test, size/XS

#10958 auto-pause: initialize the pause state from the current state
  cmd/auto-pause/auto-pause.go
  pkg/minikube/cluster/pause.go
  pkg/minikube/reason/reason.go
Labels: approved, cncf-cla: yes, ok-to-test, size/M

#10992 Add SSH to doc
  site/content/en/docs/drivers/_index.md
Labels: approved, cncf-cla: yes, size/XS

#10999 catch auto kicbase failures properly
  hack/jenkins/kicbase_auto_build.sh
Labels: approved, cncf-cla: yes, size/XS

#10997 Release 1.19.0-beta.0
  CHANGELOG.md
  Makefile
Labels: approved, cncf-cla: yes, ok-to-test, size/L

#11013 Add 'Update the Kubernetes version' to 'Building' site doc
  site/content/en/docs/contrib/releasing/binaries.md
Labels: approved, cncf-cla: yes, kind/process, sig/docs, size/XS

#11016 skip trying to install docker in CI
  hack/jenkins/common.sh
Labels: approved, cncf-cla: yes, size/XS

#11017 increase mkcmp runs to 5 and fix ingress test
  pkg/minikube/perf/result_manager.go
  pkg/minikube/perf/start.go
Labels: approved, cncf-cla: yes, size/M

#11015 Fix wrong error message on memory validation
  cmd/minikube/cmd/config/config.go
  cmd/minikube/cmd/config/set_test.go
  cmd/minikube/cmd/config/validations.go
Labels: approved, cncf-cla: yes, size/S

#11007 Add ListImages function and image list command
  cmd/minikube/cmd/image.go
  pkg/drivers/kic/kic.go
  pkg/drivers/none/none.go
  pkg/drivers/ssh/ssh.go
  pkg/minikube/bootstrapper/kubeadm/kubeadm.go
  pkg/minikube/cluster/pause.go
  pkg/minikube/cruntime/containerd.go
  pkg/minikube/cruntime/cri.go
  pkg/minikube/cruntime/crio.go
  pkg/minikube/cruntime/cruntime.go
  pkg/minikube/cruntime/cruntime_test.go
  pkg/minikube/cruntime/docker.go
  pkg/minikube/logs/logs.go
  pkg/minikube/machine/cache_images.go
  pkg/minikube/reason/reason.go
  site/content/en/docs/commands/image.md
Labels: approved, cncf-cla: yes, size/L

#11014 Respect memory being set in the minikube config
  cmd/minikube/cmd/start_flags.go
Labels: approved, cncf-cla: yes, ok-to-test, size/L

#11010 Bump newest supported kubernetes version to v1.21.0-rc.0
  pkg/minikube/bootstrapper/bsutil/testdata/v1.21/containerd-api-port.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.21/containerd-pod-network-cidr.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.21/containerd.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.21/crio-options-gates.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.21/crio.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.21/default.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.21/dns.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.21/image-repository.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.21/options.yaml
  pkg/minikube/constants/constants.go
  site/content/en/docs/commands/start.md
Labels: approved, area/kubernetes-versions, cncf-cla: yes, ok-to-test, size/XL

#11006 fix flake TestErrorSpam
  pkg/network/network.go
  test/integration/error_spam_test.go
  test/integration/testdata/multinodes/multinode-pod-dns-test.yaml
Labels: approved, cncf-cla: yes, ok-to-test, size/M

#10976 define a variable instead of duplicating "kube-system"
  cmd/minikube/cmd/config/configure.go
Labels: approved, cncf-cla: yes, ok-to-test, size/XS

#11026 split out minikube start and enable ingress times for mkcmp
  pkg/minikube/perf/binary.go
  pkg/minikube/perf/binary_test.go
  pkg/minikube/perf/result.go
  pkg/minikube/perf/result_manager.go
  pkg/minikube/perf/start.go
Labels: approved, cncf-cla: yes, size/M

#11028 Revert "Bump newest supported kubernetes version to v1.21.0-rc.0"
  pkg/minikube/bootstrapper/bsutil/testdata/v1.21/containerd-api-port.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.21/containerd-pod-network-cidr.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.21/containerd.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.21/crio-options-gates.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.21/crio.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.21/default.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.21/dns.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.21/image-repository.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.21/options.yaml
  pkg/minikube/constants/constants.go
  site/content/en/docs/commands/start.md
Labels: approved, cncf-cla: yes, ok-to-test, size/XL

#11024 Do not allow running darwin/amd64 minikube binary on darwin/arm64 systems
  cmd/minikube/cmd/root.go
  go.mod
  go.sum
  pkg/minikube/detect/detect.go
  pkg/minikube/notify/notify.go
  pkg/minikube/notify/notify_test.go
  pkg/minikube/reason/reason.go
Labels: approved, cncf-cla: yes, ok-to-test, size/M

#11019 Add auto-pause to VMs
  .gitignore
  Makefile
  deploy/addons/auto-pause/auto-pause.service
  deploy/kicbase/Dockerfile
  hack/jenkins/kicbase_auto_build.sh
  pkg/addons/addons_autopause.go
  pkg/drivers/kic/types.go
  pkg/minikube/download/iso.go
  site/content/en/docs/commands/start.md
Labels: approved, cncf-cla: yes, ok-to-test, size/M

#11011 minikube-pr-bot enhancements
  hack/jenkins/installers/check_install_golang.sh
  hack/jenkins/prbot.sh
Labels: approved, cncf-cla: yes, ok-to-test, size/M

#11027 Detect if go.sum changed after running go mod tidy
  .github/workflows/build.yml
  .github/workflows/master.yml
  .github/workflows/pr.yml
  .github/workflows/pr_verified.yaml
  test.sh
Labels: cncf-cla: yes, size/XS

#11046 Revert "change crio-bin checksum since it changed upstream"
  deploy/iso/minikube-iso/package/crio-bin/crio-bin.hash
Labels: approved, cncf-cla: yes, size/XS

#11047 go mod tidy
  go.mod
  go.sum
Labels: cncf-cla: yes, size/XS

#11048 Release 1.19.0
  CHANGELOG.md
  Makefile
  cmd/minikube/cmd/root.go
Labels: approved, cncf-cla: yes, ok-to-test, pr_verified, size/S

#11053 Fix typo in japanese translation
  translations/ja.json
Labels: cncf-cla: yes, needs-ok-to-test, size/XS

#11065 Fix gofmt and add it to the list of linters
  Makefile
  pkg/minikube/perf/result_manager.go
Labels: approved, cncf-cla: yes, size/XS

#11066 Upgrade go version from 1.16.0 to 1.16.1
  .github/workflows/build.yml
  .github/workflows/master.yml
  .github/workflows/pr.yml
  .github/workflows/pr_verified.yaml
  Makefile
Labels: approved, cncf-cla: yes, size/S

#11079 Address concerns highlighted by code scanning
  site/layouts/partials/community_links.html
  site/static/js/tabs.js
Labels: approved, cncf-cla: yes, size/XS

#11087 don't run error spam test in parallel
  test/integration/error_spam_test.go
Labels: approved, cncf-cla: yes, ok-to-test, size/XS

#11093 site: Add Image Build benchmarking page
  site/content/en/docs/benchmarks/_index.md
  site/content/en/docs/benchmarks/imageBuild/_index.md
  site/content/en/docs/benchmarks/imageBuild/containerdRuntime/_index.md
  site/content/en/docs/benchmarks/imageBuild/crioRuntime/_index.md
  site/content/en/docs/benchmarks/imageBuild/dockerRuntime/_index.md
  site/content/en/docs/benchmarks/imageBuild/minikubeVsKind/_index.md
  site/content/en/docs/featured-background.jpg
  site/content/en/docs/logo.png
  site/content/en/docs/start.png
  site/static/images/benchmarks/containerdRuntime/initial.png
  site/static/images/benchmarks/containerdRuntime/initialSummary.png
  site/static/images/benchmarks/containerdRuntime/iterative.png
  site/static/images/benchmarks/containerdRuntime/iterativeSummary.png
  site/static/images/benchmarks/crioRuntime/initial.png
  site/static/images/benchmarks/crioRuntime/initialSummary.png
  site/static/images/benchmarks/crioRuntime/iterative.png
  site/static/images/benchmarks/crioRuntime/iterativeSummary.png
  site/static/images/benchmarks/dockerRuntime/initial.png
  site/static/images/benchmarks/dockerRuntime/initialSummary.png
  site/static/images/benchmarks/dockerRuntime/iterative.png
  site/static/images/benchmarks/dockerRuntime/iterativeSummary.png
  site/static/images/benchmarks/minikubeVsKind/initial.png
  site/static/images/benchmarks/minikubeVsKind/iterative.png
Labels: cncf-cla: yes, size/M

#11082 Address security concerns with the go code
  pkg/drivers/kic/kic.go
  pkg/minikube/bootstrapper/bsutil/kverify/api_server.go
  pkg/minikube/command/exec_runner.go
  pkg/minikube/command/kic_runner.go
  pkg/minikube/reason/known_issues.go
Labels: approved, cncf-cla: yes, ok-to-test, size/S

#11096 ci : overhaul pr bot's mkcmp output
  pkg/minikube/perf/result_manager.go
  pkg/minikube/perf/start.go
Labels: approved, cncf-cla: yes, size/M

#11088 Check if Docker installed via Snap Package Manager
  pkg/minikube/command/kic_runner.go
  pkg/minikube/command/kic_runner_test.go
  pkg/minikube/detect/detect.go
Labels: approved, cncf-cla: yes, ok-to-test, size/M

#11092 Add configuration for sonarqube code scanning
  .gitignore
  Makefile
  sonar-project.properties
Labels: approved, cncf-cla: yes, size/S

#11097 ci: pr-bot add containerd to mkcmp and warn if too slow
  pkg/minikube/perf/result_manager.go
  pkg/minikube/perf/start.go
Labels: approved, cncf-cla: yes, size/M

#11086 avoid network calls for mirror unit tests
  cmd/minikube/cmd/start.go
  cmd/minikube/cmd/start_test.go
  pkg/drivers/kic/oci/network_create.go
  pkg/drivers/kic/oci/network_create_test.go
Labels: approved, cncf-cla: yes, size/M

#11118 ci: mkcmp: skip testing ingress for containerd
  pkg/minikube/perf/start.go
Labels: approved, cncf-cla: yes, size/XS

#11119 site: update FAQ
  site/content/en/docs/faq/_index.md
Labels: approved, cncf-cla: yes, size/M

#11129 site: Add some more definitions of image terminology
  site/content/en/docs/handbook/pushing.md
Labels: approved, cncf-cla: yes, size/XS

#11133 Correct typo in timeout value in comment
  pkg/minikube/registry/drvs/virtualbox/virtualbox.go
Labels: cncf-cla: yes, needs-ok-to-test, size/XS

#11120 site: Automatically generate integration test documentation
  Makefile
  cmd/minikube/cmd/generate-docs.go
  pkg/generate/docs.go
  pkg/generate/testdocs.go
  site/content/en/docs/contrib/tests.en.md
  test/integration/aaa_download_only_test.go
  test/integration/aab_offline_test.go
  test/integration/addons_test.go
  test/integration/cert_options_test.go
  test/integration/docker_test.go
  test/integration/driver_install_or_update_test.go
  test/integration/error_spam_test.go
  test/integration/functional_test.go
  test/integration/functional_test_mount_test.go
  test/integration/functional_test_pvc_test.go
  test/integration/functional_test_tunnel_test.go
  test/integration/gvisor_addon_test.go
  test/integration/json_output_test.go
  test/integration/kic_custom_network_test.go
  test/integration/multinode_test.go
  test/integration/net_test.go
  test/integration/none_test.go
  test/integration/pause_test.go
  test/integration/pkg_install_test.go
  test/integration/preload_test.go
  test/integration/scheduled_stop_test.go
  test/integration/skaffold_test.go
  test/integration/start_stop_delete_test.go
  test/integration/status_test.go
  test/integration/version_upgrade_test.go
Labels: approved, cncf-cla: yes, size/XL

#11111 Upgrade crio to 1.20.2
  Makefile
  deploy/iso/minikube-iso/package/crio-bin/crio-bin.hash
  deploy/iso/minikube-iso/package/crio-bin/crio-bin.mk
  pkg/minikube/download/iso.go
  site/content/en/docs/commands/start.md
Labels: approved, cncf-cla: yes, ok-to-test, size/S

#11143 ci: move non-functional tests to pr verfied
  .github/workflows/master.yml
  .github/workflows/pr.yml
  .github/workflows/pr_verified.yaml
Labels: approved, cncf-cla: yes, size/XXL

#11081 prevent multiple /etc/hosts entries for control-plane.minikube.internal
  pkg/minikube/machine/start.go
  pkg/minikube/machine/start_test.go
Labels: cncf-cla: yes, needs-ok-to-test, size/L

#11050 Check if go mod tidy || make generate-docs create file changes in CI
  test.sh
Labels: cncf-cla: yes, size/S

#11148 skip dry-run on hyperv
  pkg/minikube/machine/start_test.go
  test/integration/functional_test.go
Labels: approved, cncf-cla: yes, size/S

#11127 new command "image pull: allow to load remote images directly without cache
  cmd/minikube/cmd/image.go
  pkg/minikube/cruntime/containerd.go
  pkg/minikube/cruntime/cri.go
  pkg/minikube/cruntime/crio.go
  pkg/minikube/cruntime/cruntime.go
  pkg/minikube/cruntime/docker.go
  pkg/minikube/machine/cache_images.go
  site/content/en/docs/commands/image.md
Labels: approved, cncf-cla: yes, size/L

#11152 fix "index out of range" in integration.validateDeployAppToMultiNode
  test/integration/multinode_test.go
Labels: approved, cncf-cla: yes, size/XS

#11150 bump golangci-lint to latest v1.39.0
  Makefile
  cmd/minikube/cmd/config/config.go
  cmd/minikube/cmd/config/prompt.go
  cmd/minikube/cmd/delete_test.go
  cmd/minikube/cmd/podman-env.go
  cmd/minikube/cmd/root.go
  hack/help_text/gen_help_text.go
  pkg/addons/config.go
  pkg/drivers/hyperkit/driver.go
  pkg/drivers/hyperkit/iso_test.go
  pkg/minikube/assets/addons.go
  pkg/minikube/bootstrapper/kubeadm/kubeadm.go
  pkg/minikube/config/profile_test.go
  pkg/minikube/cruntime/cruntime_test.go
  pkg/minikube/delete/delete.go
  pkg/minikube/extract/extract.go
  pkg/minikube/extract/extract_test.go
  pkg/minikube/kubeconfig/kubeconfig_test.go
  pkg/minikube/localpath/localpath.go
  pkg/minikube/localpath/localpath_test.go
  pkg/minikube/machine/cache_binaries_test.go
  pkg/minikube/node/start.go
  pkg/minikube/notify/notify_test.go
  pkg/minikube/out/out.go
  pkg/minikube/out/register/cloud_events.go
  pkg/minikube/registry/drvs/docker/docker.go
  pkg/util/crypto_test.go
  pkg/util/utils_test.go
  test/integration/functional_test.go
  test/integration/functional_test_mount_test.go
  test/integration/helpers_test.go
  test/integration/version_upgrade_test.go
Labels: approved, cncf-cla: yes, size/M

#11155 Make golint clean again by adding comments
  Makefile
  cmd/auto-pause/auto-pause-hook/main.go
  cmd/minikube/cmd/status.go
  pkg/minikube/cluster/pause.go
  pkg/minikube/reason/exitcodes.go
  pkg/minikube/sysinit/systemd.go
Labels: approved, cncf-cla: yes, size/S

#11030 fix insufficient memory issues
  hack/metrics/metrics.go
  test/integration/aab_offline_test.go
  test/integration/cert_options_test.go
  test/integration/docker_test.go
  test/integration/guest_env_test.go
  test/integration/net_test.go
  test/integration/pause_test.go
  test/integration/scheduled_stop_test.go
  test/integration/status_test.go
Labels: cncf-cla: yes, size/S

#11151 Pre-cleanup for GitHub actions self-hosted machines
  .github/workflows/master.yml
  .github/workflows/pr.yml
Labels: approved, cncf-cla: yes, kind/process, pr_verified, size/S

#11122 Better to use "0777" than "0o777",instead of only in Go
  cmd/minikube/cmd/root.go
Labels: cncf-cla: yes, needs-ok-to-test, size/XS

#11099 Upgrade Docker, from 20.10.4 to 20.10.6
  Makefile
  deploy/iso/minikube-iso/package/containerd-bin/containerd-bin.hash
  deploy/iso/minikube-iso/package/containerd-bin/containerd-bin.mk
  deploy/iso/minikube-iso/package/docker-bin/docker-bin.hash
  deploy/iso/minikube-iso/package/docker-bin/docker-bin.mk
  pkg/minikube/download/iso.go
  site/content/en/docs/commands/start.md
Labels: approved, cncf-cla: yes, size/S

#11160 Mock the docker call when calling it from tests
  cmd/minikube/cmd/delete_test.go
  pkg/minikube/config/profile.go
  pkg/minikube/config/profile_test.go
Labels: approved, cncf-cla: yes, size/S

#11157 test: Add target for the test report as html
  .gitignore
  Makefile
  sonar-project.properties
Labels: approved, cncf-cla: yes, size/S

#11154 ci: bump timeout for github action
  .github/workflows/master.yml
  .github/workflows/pr.yml
  test/integration/functional_test.go
Labels: approved, cncf-cla: yes, size/S

#11114 Increase timeout value in kvm2 driver validation to 6 seconds
  pkg/minikube/registry/drvs/kvm2/kvm2.go
Labels: approved, cncf-cla: yes, ok-to-test, size/S

#11167 Change 'minikube version --short' to only print the version without a prompt.
  cmd/minikube/cmd/version.go
Labels: cncf-cla: yes, ok-to-test, size/S

#11172 Update guide.en.md
  site/content/en/docs/contrib/guide.en.md
Labels: approved, cncf-cla: yes, size/S

#11173 Revert "ci: mkcmp: skip testing ingress for containerd"
  pkg/minikube/perf/start.go
Labels: approved, cncf-cla: yes, size/XS

#11168 Use canonical image name if one exists remotely
  pkg/minikube/image/cache.go
  pkg/minikube/image/image.go
Labels: approved, cncf-cla: yes, ok-to-test, size/M

#11132 Add checksum to the preload tarball download
  pkg/minikube/download/preload.go
Labels: approved, cncf-cla: yes, ok-to-test, size/M

#11080 Check for uint32 overflow in go9p third party
  third_party/go9p/srv_pipe.go
  third_party/go9p/ufs.go
Labels: approved, cncf-cla: yes, ok-to-test, size/XS

#11095 Move preload generation to Jenkins
  Makefile
  hack/preload-images/kubernetes.go
  hack/preload-images/preload_images.go
Labels: approved, cncf-cla: yes, kind/process, size/L

#11176 fix flake integration tests: cleanups and timeouts
  hack/jenkins/common.sh
  hack/jenkins/cron/cleanup_and_reboot_Linux.sh
Labels: cncf-cla: yes, size/M

#11158 Add log file to GitHub issue output
  pkg/addons/addons.go
  pkg/minikube/out/out.go
  pkg/minikube/out/out_reason.go
  pkg/minikube/out/out_test.go
Labels: cncf-cla: yes, size/L

#11164 Add re-implementation of the build command
  cmd/minikube/cmd/image.go
  go.mod
  go.sum
  pkg/minikube/cruntime/containerd.go
  pkg/minikube/cruntime/crio.go
  pkg/minikube/cruntime/cruntime.go
  pkg/minikube/cruntime/docker.go
  pkg/minikube/machine/build_images.go
  pkg/minikube/reason/reason.go
  site/content/en/docs/commands/image.md
  test/integration/functional_test.go
  test/integration/testdata/build/Dockerfile
  test/integration/testdata/build/content.txt
  third_party/go-dockerclient/LICENSE
  third_party/go-dockerclient/tar.go
Labels: approved, cncf-cla: yes, ok-to-test, size/XL

#11055 Update kicbase base image
  deploy/kicbase/Dockerfile
  deploy/kicbase/entrypoint
  pkg/drivers/kic/types.go
  site/content/en/docs/commands/start.md
Labels: approved, cncf-cla: yes, ok-to-test, size/M

#11054 Upgrade buildroot minor version
  Makefile
  deploy/iso/minikube-iso/configs/minikube_defconfig
  pkg/minikube/download/iso.go
  site/content/en/docs/commands/start.md
Labels: approved, cncf-cla: yes, size/S

#11178 bump kindnet to v20210326-1e038dc5
  pkg/minikube/bootstrapper/images/images.go
  pkg/minikube/cni/kindnet.go
Labels: cncf-cla: yes, ok-to-test, size/S

#11189 [Ingress Addon] Fix bug which the networking.k8s.io/v1 ingress is always rejected
  deploy/addons/ingress/ingress-dp.yaml.tmpl
  test/integration/addons_test.go
  test/integration/testdata/nginx-ingv1.yaml
  test/integration/testdata/nginx-ingv1beta.yaml
Labels: approved, cncf-cla: yes, kind/bug, kind/regression, ok-to-test, priority/important-soon, size/M

#10918 Add code for downloading kicbase image to cache
  cmd/minikube/cmd/root.go
  pkg/minikube/constants/constants.go
  pkg/minikube/download/iso.go
  pkg/minikube/image/image.go
  pkg/minikube/node/cache.go
  pkg/minikube/tests/dir_utils.go
Labels: approved, cncf-cla: yes, ok-to-test, size/L

#11003 Use golang.org/x/term
  cmd/minikube/cmd/config/prompt.go
  go.mod
  go.sum
  pkg/minikube/command/kic_runner.go
Labels: cncf-cla: yes, ok-to-test, size/S

#11203 Add some zh-CN translations
  translations/zh-CN.json
Labels: cncf-cla: yes, needs-ok-to-test, size/S

#11208 Make sure to pass the platform for the kicbase
  pkg/minikube/image/image.go
Labels: approved, cncf-cla: yes, ok-to-test, size/XS

#11206 Correct typo in start_flags.go
  cmd/minikube/cmd/start_flags.go
Labels: approved, cncf-cla: yes, needs-ok-to-test, size/XS

#11210 ci: mkcmp: skip ingress for containerd runtime, take 2
  pkg/minikube/perf/result_manager.go
  pkg/minikube/perf/start.go
Labels: approved, cncf-cla: yes, ok-to-test, size/XS

#11212 Make sure to capture errors in auto kicbase builds
  Makefile
  hack/jenkins/kicbase_auto_build.sh
  pkg/drivers/kic/types.go
  site/content/en/docs/commands/start.md
  site/content/en/docs/contrib/tests.en.md
Labels: approved, cncf-cla: yes, ok-to-test, pr_verified, size/S

#11128 Add API for saving an image to a local path
  pkg/minikube/cruntime/containerd.go
  pkg/minikube/cruntime/crio.go
  pkg/minikube/cruntime/cruntime.go
  pkg/minikube/cruntime/docker.go
Labels: approved, cncf-cla: yes, ok-to-test, size/M

#11169 Add opt-in notifications for beta releases
  cmd/minikube/cmd/config/config.go
  cmd/minikube/cmd/update-check.go
  deploy/minikube/releases-beta.json
  hack/jenkins/release_update_releases_json.sh
  pkg/minikube/config/config.go
  pkg/minikube/notify/constants.go
  pkg/minikube/notify/notify.go
  pkg/minikube/notify/notify_test.go
  site/content/en/docs/commands/config.md
Labels: cncf-cla: yes, ok-to-test, size/L

#11185 improve how cni and cruntimes work together
  cmd/minikube/cmd/start_flags.go
  pkg/minikube/bootstrapper/bsutil/kubeadm.go
  pkg/minikube/bootstrapper/kubeadm/kubeadm.go
  pkg/minikube/cni/cni.go
  pkg/minikube/cni/kindnet.go
  pkg/minikube/cruntime/containerd.go
  pkg/minikube/cruntime/crio.go
  pkg/minikube/node/start.go
Labels: approved, cncf-cla: yes, ok-to-test, size/L

#11140 Add cpu usage benchmark command `make cpu-benchmark` and website docs
  Makefile
  go.mod
  go.sum
  hack/benchmark/cpu_usage/auto_pause/README.md
  hack/benchmark/cpu_usage/auto_pause/benchmark_local_k8s.sh
  hack/benchmark/cpu_usage/auto_pause/chart.go
  hack/benchmark/cpu_usage/auto_pause/update_summary.sh
  hack/benchmark/cpu_usage/idle_only/README.md
  hack/benchmark/cpu_usage/idle_only/benchmark_local_k8s.sh
  hack/benchmark/cpu_usage/idle_only/chart.go
  hack/benchmark/cpu_usage/idle_only/update_summary.sh
  site/content/en/docs/benchmarks/cpuUsage/_index.md
  site/content/en/docs/benchmarks/cpuUsage/linux/_index.md
  site/content/en/docs/benchmarks/cpuUsage/macOS/_index.md
  site/static/images/benchmarks/cpuUsage/autoPause/linux.png
  site/static/images/benchmarks/cpuUsage/autoPause/mac.png
  site/static/images/benchmarks/cpuUsage/idleOnly/linux.png
  site/static/images/benchmarks/cpuUsage/idleOnly/mac.png
Labels: cncf-cla: yes, kind/feature, needs-ok-to-test, size/XXL

#11232 Add mask and unmask to the disable and enable
  pkg/minikube/cruntime/cruntime_test.go
  pkg/minikube/cruntime/docker.go
  pkg/minikube/sysinit/openrc.go
  pkg/minikube/sysinit/sysinit.go
  pkg/minikube/sysinit/systemd.go
Labels: approved, cncf-cla: yes, ok-to-test, size/M

#11209 improve how cni and cruntimes work together v2
  cmd/minikube/cmd/start_flags.go
  pkg/minikube/bootstrapper/bsutil/kverify/pod_ready.go
  pkg/minikube/bootstrapper/kubeadm/kubeadm.go
  pkg/minikube/cni/cni.go
Labels: approved, cncf-cla: yes, ok-to-test, size/M

#11238 Updated English GitHub issue template to require minikube logs
  .github/ISSUE_TEMPLATE/__en-US.md
Labels: approved, cncf-cla: yes, size/S

#11190 ci: add functional contained
  .github/workflows/master.yml
  .github/workflows/pr.yml
Labels: approved, cncf-cla: yes, size/L

#11241 Release 1.20.0-beta.0
  CHANGELOG.md
  Makefile
Labels: approved, cncf-cla: yes, ok-to-test, size/M
