Repository kubernetes/minikube, pull requests merged in 2021-09, with the labels that each got.

#12390 Instructions for adding a dns-server on windows
  site/content/en/docs/handbook/addons/ingress-dns.md
Labels: cncf-cla: yes, size/XS, approved, needs-ok-to-test

#12392 Update issue template to ask user to attach log file to issue
  .github/ISSUE_TEMPLATE/__en-US.md
Labels: cncf-cla: yes, size/XS, approved

#12393 make sure to install the same version of golang across scripts
  hack/jenkins/build/minikube_build_upload_latest.sh
  hack/jenkins/common.sh
  hack/jenkins/installers/check_install_golang.sh
  hack/jenkins/kicbase_auto_build.sh
  hack/jenkins/minikube_cross_build_and_upload.sh
  hack/jenkins/prbot.sh
  hack/jenkins/preload_generation.sh
  hack/update/golang_version/update_golang_version.go
Labels: cncf-cla: yes, size/M, approved

#12395 Change GitHub issue output to ask user to upload `minikube logs` file
  pkg/minikube/out/out.go
  pkg/minikube/out/out_test.go
Labels: cncf-cla: yes, size/L, approved

#12398 remove ppc64le/armv7 from kicbase archs
  Makefile
  pkg/drivers/kic/types.go
  site/content/en/docs/commands/start.md
Labels: cncf-cla: yes, size/XS, approved

#12405 Update Makefile and CHANGELOG for 1.23.0 release
  CHANGELOG.md
  Makefile
Labels: cncf-cla: yes, size/L, approved, ok-to-test

#12412 Fix french translation
  translations/fr.json
Labels: cncf-cla: yes, size/XS, needs-ok-to-test

#12427 Add an issue template for Japanese
  .github/ISSUE_TEMPLATE/ja.md
Labels: cncf-cla: yes, size/S

#12430 Remove quotes from fields of Windows Installer
  installers/windows/minikube.nsi
Labels: cncf-cla: yes, size/S, needs-ok-to-test

#12437 metallb addon: Ask user for config values even if already set
  cmd/minikube/cmd/config/configure.go
Labels: cncf-cla: yes, size/XS, approved

#11785 fix images for aliyun registry
  pkg/minikube/assets/addons.go
  pkg/minikube/image/image.go
  pkg/minikube/node/cache.go
Labels: cncf-cla: yes, size/M, ok-to-test

#12381 Updated version.go with crun version
  cmd/minikube/cmd/version.go
  test/integration/functional_test.go
Labels: cncf-cla: yes, size/XS, approved, needs-ok-to-test

#12446 Fix ingress addon role resource's referenced configmap
  deploy/addons/ingress/ingress-deploy.yaml.tmpl
Labels: cncf-cla: yes, size/XS, ok-to-test

#12449 change test names to fix flake reports
  test/integration/pkg_install_test.go
Labels: cncf-cla: yes, size/XS, approved, ok-to-test

#12443 Fix Ingress Addon
  cmd/minikube/cmd/config/enable.go
  deploy/addons/ingress/ingress-deploy.yaml.tmpl
Labels: cncf-cla: yes, size/XS, approved, ok-to-test

#12461 Create GCP auth pull secret even if creds JSON is nil
  pkg/addons/addons_gcpauth.go
Labels: cncf-cla: yes, size/XS, approved, ok-to-test

#12439 filter out arm64, macOS, and crio from flake reports
  hack/jenkins/test-flake-chart/report_flakes.sh
Labels: cncf-cla: yes, size/XS, approved, ok-to-test

#12474 Add warning for ambassador addon
  cmd/minikube/cmd/config/enable.go
Labels: cncf-cla: yes, size/XS, approved

#12473 make sure to delete image pull secrets on gcp auth addon disable
  pkg/addons/addons_gcpauth.go
  test/integration/addons_test.go
Labels: cncf-cla: yes, size/M, approved, ok-to-test

#12425 Update cri-o from v1.20.0 to 1.22.0
  Makefile
  deploy/iso/minikube-iso/go.hash
  deploy/iso/minikube-iso/package/crio-bin/crio-bin.hash
  deploy/iso/minikube-iso/package/crio-bin/crio-bin.mk
  deploy/kicbase/Dockerfile
  hack/jenkins/build_iso.sh
  pkg/drivers/kic/types.go
  pkg/minikube/download/iso.go
  site/content/en/docs/commands/start.md
Labels: cncf-cla: yes, size/M, approved, ok-to-test

#12487 doc: be more specific as to what the gcp-auth does
  site/content/en/docs/handbook/addons/gcp-auth.md
Labels: cncf-cla: yes, size/S, needs-ok-to-test

#12475 Use newer dashboard, to support ingress extensions
  pkg/minikube/assets/addons.go
  pkg/minikube/bootstrapper/images/images.go
  pkg/minikube/bootstrapper/images/images_test.go
  pkg/minikube/bootstrapper/images/kubeadm_test.go
  pkg/minikube/download/preload.go
Labels: cncf-cla: yes, size/M, approved, ok-to-test

#12496 fix sha for metrics-server image in addon config
  pkg/minikube/assets/addons.go
Labels: cncf-cla: yes, size/XS, approved

#12497 fix refreshing gcp-auth pull secret
  deploy/addons/gcp-auth/gcp-auth-webhook.yaml.tmpl
  pkg/addons/addons_gcpauth.go
Labels: cncf-cla: yes, size/M, approved, ok-to-test

#12499 v1.23.1 release
  CHANGELOG.md
  Makefile
  hack/release_notes.sh
Labels: cncf-cla: yes, size/M, approved, ok-to-test

#12503 Add github-release install script
  hack/jenkins/installers/check_install_github_release.sh
  hack/jenkins/release_github_page.sh
Labels: cncf-cla: yes, size/S, approved

#12495 Replace BusyBox image with gcr.io image in functional tests
  site/content/en/docs/contrib/tests.en.md
  test/integration/functional_test.go
Labels: cncf-cla: yes, size/L, approved

#12516 Fix french translation
  translations/fr.json
Labels: cncf-cla: yes, size/XS, needs-ok-to-test

#12510 Update pushing.md
  site/content/en/docs/handbook/pushing.md
Labels: cncf-cla: yes, size/S, needs-ok-to-test

#12532 Fix template typo
  pkg/minikube/bootstrapper/bsutil/ktmpl/kubelet.go
Labels: cncf-cla: yes, size/XS, approved, ok-to-test

#12541 v1.23.2 release
  CHANGELOG.md
  Makefile
Labels: cncf-cla: yes, size/M, approved, ok-to-test

#12540 skip ingress dns test for docker macOS/windows
  test/integration/addons_test.go
Labels: cncf-cla: yes, size/XS, approved, ok-to-test

#12539 Update MacOS ISO build steps
  Makefile
  deploy/iso/minikube-iso/Dockerfile
Labels: cncf-cla: yes, size/XS, needs-ok-to-test

#12554 fix go sum
  go.sum
Labels: cncf-cla: yes, size/XS, approved

#12545 start timing enable ingress for containerd
  hack/jenkins/linux_integration_tests_docker.sh
  hack/jenkins/minikube_cross_build_and_upload.sh
  hack/jenkins/prbot.sh
  pkg/minikube/perf/start.go
Labels: cncf-cla: yes, size/M, approved, ok-to-test

#12563 Fix update-leaderboard GitHub Action
  hack/update_contributions.sh
Labels: cncf-cla: yes, size/S, approved

#12553 Implement --force-systemd into cri-o
  pkg/minikube/cruntime/crio.go
  test/integration/docker_test.go
Labels: cncf-cla: yes, size/M, approved, ok-to-test

#12534 renew minikube certs if expired
  cmd/minikube/cmd/start_flags.go
  pkg/minikube/bootstrapper/bootstrapper.go
  pkg/minikube/bootstrapper/certs.go
  pkg/minikube/bootstrapper/certs_test.go
  pkg/minikube/bootstrapper/kubeadm/kubeadm.go
  pkg/minikube/config/types.go
  pkg/minikube/constants/constants.go
  pkg/minikube/node/start.go
  pkg/util/crypto.go
  pkg/util/crypto_test.go
  test/integration/cert_options_test.go
  test/integration/pkg_install_test.go
Labels: cncf-cla: yes, size/L, approved, ok-to-test

#12586 Fix french translation
  translations/fr.json
Labels: cncf-cla: yes, size/XS, needs-ok-to-test

#12590 remove all windows tests from github actions
  .github/workflows/functional_verified.yml
  .github/workflows/master.yml
  .github/workflows/pr.yml
  .github/workflows/pr_verified.yaml
Labels: cncf-cla: yes, size/XXL, approved, ok-to-test

#12591 change file name for updaters
  hack/update/golang_version/update_golang_version.go
  hack/update/gopogh_version/update_gopogh_version.go
Labels: cncf-cla: yes, size/S, approved

#12579 Allow running podman as experimental driver
  pkg/minikube/driver/driver_darwin.go
  pkg/minikube/driver/driver_windows.go
  site/content/en/docs/drivers/podman.md
Labels: cncf-cla: yes, size/S, approved

#11997 docs: Suggest using alias for minikube kubectl --
  site/content/en/docs/start/_index.md
Labels: cncf-cla: yes, size/XS, needs-ok-to-test

#12514 add better error output for minikube image rm
  pkg/minikube/machine/cache_images.go
Labels: cncf-cla: yes, size/XS, needs-ok-to-test

#12149 Build images on the primary control plane
  cmd/minikube/cmd/image.go
  pkg/minikube/machine/build_images.go
  site/content/en/docs/commands/image.md
Labels: cncf-cla: yes, size/S, approved, ok-to-test

#12592 GitHubActions: Update `ubuntu-18.04` to `ubuntu-20.04`
  .github/workflows/build.yml
  .github/workflows/docs.yml
  .github/workflows/functional_verified.yml
  .github/workflows/leaderboard.yml
  .github/workflows/master.yml
  .github/workflows/pr.yml
  .github/workflows/time-to-k8s-public-chart.yml
  .github/workflows/twitter-bot.yml
  .github/workflows/update-golang-version.yml
  .github/workflows/update-golint-version.yml
Labels: cncf-cla: yes, size/M, approved

#12397 Update Windows Install PowerShell Commands
  site/content/en/docs/start/_index.md
Labels: cncf-cla: yes, size/M, needs-ok-to-test

#12618 `TestScheduledStopWindows`: increase sleep to 1 minute
  test/integration/scheduled_stop_test.go
Labels: cncf-cla: yes, size/XS, approved

#12617 Fix invoking kubeadm failing when spaces in PATH
  pkg/minikube/bootstrapper/bsutil/kubeadm.go
Labels: cncf-cla: yes, size/XS, ok-to-test

#12420 fix issue #11348 zsh completion broken
  cmd/minikube/cmd/completion.go
Labels: cncf-cla: yes, size/XS, approved, needs-ok-to-test

#12627 podman: Fix network not getting deleted
  pkg/drivers/kic/oci/network_create.go
  pkg/minikube/delete/delete.go
  test/integration/pause_test.go
Labels: cncf-cla: yes, size/S, approved, ok-to-test
