Repository kubernetes/minikube, pull requests merged in 2021-11, with the labels that each got.

#12656 Update Japanese translation (Line 2-51)
  translations/ja.json
Labels: cncf-cla: yes, size/M

#12837 `minikube addons list` shows addons if cluster does not exist
  cmd/minikube/cmd/config/addons_list.go
Labels: cncf-cla: yes, size/S, approved, ok-to-test

#12838 Add LA KubeCon Talk to presentations
  site/content/en/docs/presentations/_index.md
Labels: cncf-cla: yes, size/XS, approved

#12663 Update Japanese translation (Line 700-749)
  translations/ja.json
Labels: cncf-cla: yes, size/L, lgtm, needs-ok-to-test

#12841 fix zsh completion
  cmd/minikube/cmd/completion.go
Labels: cncf-cla: yes, size/XS, needs-ok-to-test

#12811 virtualbox: change default `host-only-cidr`
  cmd/minikube/cmd/start_flags.go
  pkg/minikube/config/profile_test.go
  pkg/minikube/config/testdata/.minikube/profiles/p1/config.json
  pkg/minikube/config/testdata/.minikube/profiles/p2_newformat/config.json
  pkg/minikube/config/testdata/.minikube/profiles/p5_partial_config/config.json
  pkg/minikube/config/testdata/delete-all/.minikube/profiles/p1/config.json
  pkg/minikube/config/testdata/delete-all/.minikube/profiles/p4_partial_profile_config/config.json
  pkg/minikube/config/testdata/delete-all/.minikube/profiles/p5_missing_machine_config/config.json
  pkg/minikube/config/testdata/delete-all/.minikube/profiles/p6_empty_machine_config/config.json
  pkg/minikube/config/testdata/delete-all/.minikube/profiles/p7_invalid_machine_config/config.json
  pkg/minikube/config/testdata/delete-all/.minikube/profiles/p8_partial_machine_config/config.json
  pkg/minikube/config/testdata/delete-single/.minikube/profiles/p1/config.json
  pkg/minikube/config/testdata/delete-single/.minikube/profiles/p4_partial_profile_config/config.json
  pkg/minikube/config/testdata/delete-single/.minikube/profiles/p5_missing_machine_config/config.json
  pkg/minikube/config/testdata/delete-single/.minikube/profiles/p6_empty_machine_config/config.json
  pkg/minikube/config/testdata/delete-single/.minikube/profiles/p7_invalid_machine_config/config.json
  pkg/minikube/config/testdata/delete-single/.minikube/profiles/p8_partial_machine_config/config.json
  pkg/minikube/config/testdata/profile/.minikube/profiles/p1/config.json
  pkg/minikube/config/testdata/profile/.minikube/profiles/p2_newformat/config.json
  pkg/minikube/config/testdata/profile/.minikube/profiles/p5_partial_config/config.json
  pkg/minikube/kubeconfig/kubeconfig_test.go
  pkg/minikube/machine/client_test.go
  pkg/minikube/service/service_test.go
  pkg/minikube/tunnel/route_windows_test.go
  pkg/util/crypto_test.go
  site/content/en/docs/commands/start.md
  site/content/en/docs/drivers/virtualbox.md
  site/content/en/docs/handbook/vpn_and_proxy.md
Labels: cncf-cla: yes, size/L, ok-to-test

#12847 propagate ROOT_JOB_ID into cloud shell tests for proper log storage
  hack/jenkins/cloud_shell_functional_tests_docker.sh
Labels: cncf-cla: yes, size/XS, approved, ok-to-test

#12849 stop setting ACLs on preload tarball
  hack/preload-images/upload.go
Labels: cncf-cla: yes, size/S, approved

#12792 fix cert option test and add more internal testing
  test/integration/cert_options_test.go
Labels: cncf-cla: yes, size/M, approved, ok-to-test

#12808 Update Japanese translation (Line 800-850)
  translations/ja.json
Labels: cncf-cla: yes, size/M, lgtm, needs-ok-to-test

#12778 remove deprecated French translations
  translations/fr.json
Labels: cncf-cla: yes, size/M, approved

#12839 `minikube addons list` tests
  cmd/minikube/cmd/config/addons_list.go
  cmd/minikube/cmd/config/addons_list_test.go
Labels: cncf-cla: yes, size/M, approved, ok-to-test

#12848 Add --no-kubernetes flag to start minikube without kubernetes
  cmd/minikube/cmd/config/profile_list.go
  cmd/minikube/cmd/start.go
  cmd/minikube/cmd/start_flags.go
  pkg/minikube/constants/constants.go
  pkg/minikube/node/start.go
  pkg/minikube/out/out.go
  test/integration/no_kubernetes_test.go
Labels: cncf-cla: yes, size/L, approved, ok-to-test

#12861 register node add initial step
  cmd/minikube/cmd/node_add.go
Labels: cncf-cla: yes, size/XS, approved, ok-to-test

#12863 update suggestion for disabling internet sharing on hyperkit
  pkg/minikube/reason/known_issues.go
Labels: cncf-cla: yes, size/XS, approved

#12866 Update Makefile for v1.24.0 release
  CHANGELOG.md
  Makefile
Labels: cncf-cla: yes, size/M, approved, ok-to-test

#12872 update FAQ with no-kubernetes
  site/content/en/docs/faq/_index.md
Labels: cncf-cla: yes, size/S, approved

#12873 Various CI Script Improvements
  .github/workflows/functional_verified.yml
  .github/workflows/time-to-k8s-public-chart.yml
  .github/workflows/twitter-bot.yml
  hack/jenkins/build/minikube_build_upload_latest.sh
  hack/jenkins/common.ps1
  hack/jenkins/common.sh
  hack/jenkins/minikube_cross_build_and_upload.sh
Labels: cncf-cla: yes, size/M, approved

#12888 Minor GitHub Actions fixes
  .github/workflows/time-to-k8s.yml
  .github/workflows/update-golint-version.yml
Labels: cncf-cla: yes, size/S, approved

#12770 Throw error if trying to install jq on arm64 machines
  hack/jenkins/common.sh
Labels: cncf-cla: yes, size/XS, approved

#12883 clean up the `ingress-dns` documentation
  site/content/en/docs/handbook/addons/ingress-dns.md
  site/layouts/shortcodes/quiz_instruction_plain.html
Labels: cncf-cla: yes, size/L, needs-ok-to-test

#12902 Fix running `minikube delete` before `MINIKUBE_HOME` set
  hack/jenkins/common.ps1
  hack/jenkins/windows_integration_setup.ps1
Labels: cncf-cla: yes, size/XS, approved

#12906 Add new build tags to go9p
  third_party/go9p/clnt_stats_http.go
  third_party/go9p/srv_stats_http.go
Labels: cncf-cla: yes, size/XS, approved

#12740 containerd preload: discard unpacked layers to reduce size
  pkg/minikube/cruntime/containerd.go
  pkg/minikube/download/preload.go
Labels: cncf-cla: yes, size/M, approved, ok-to-test

#12907 Add error message for file sharing
  pkg/minikube/reason/known_issues.go
Labels: cncf-cla: yes, size/S, approved

#12910 change chowns in golang install script to `$USER`
  hack/jenkins/installers/check_install_golang.sh
Labels: cncf-cla: yes, size/XS, approved, ok-to-test

#12893 only copy binaries to minikube/latest on non-PR builds
  hack/jenkins/minikube_cross_build_and_upload.sh
Labels: cncf-cla: yes, size/S, approved, ok-to-test

#12870 Fix `docker-env` with new PowerShell versions
  go.mod
  go.sum
Labels: cncf-cla: yes, size/XS, approved, ok-to-test

#12909 start including macOS tests in flake reports
  hack/jenkins/test-flake-chart/report_flakes.sh
Labels: cncf-cla: yes, size/XS, approved

#12913 Improve contributing docs
  site/content/en/docs/contrib/guide.en.md
Labels: cncf-cla: yes, size/S, approved, needs-ok-to-test

#12923 fix scheduled stop test for containerd on docker driver
  cmd/minikube/cmd/start_flags.go
  pkg/minikube/schedule/daemonize_unix.go
  test/integration/scheduled_stop_test.go
Labels: cncf-cla: yes, size/S, approved, ok-to-test

#12932 Fix fail in parent test reporting oddly on flake charts
  test/integration/version_upgrade_test.go
Labels: cncf-cla: yes, size/S, approved

#12900 Support CRI-O runtime with Rootless Docker driver (`--driver=docker --container-runtime=cri-o`)
  cmd/minikube/cmd/start_flags.go
  pkg/minikube/cruntime/crio.go
  site/content/en/docs/drivers/includes/docker_usage.inc
Labels: cncf-cla: yes, size/M, approved, ok-to-test

#12933 update suggestion messaging for --no-kubernetes
  cmd/minikube/cmd/start.go
  pkg/minikube/constants/constants.go
Labels: cncf-cla: yes, size/S, ok-to-test

#12914 Specify VMware application names used in documentation
  site/content/en/docs/drivers/_index.md
  site/content/en/docs/drivers/includes/vmware_windows_usage.inc
  site/content/en/docs/start/_index.md
Labels: cncf-cla: yes, size/XS, needs-ok-to-test

#12921 kubevirt addon: use KubeVirt CR instead of deprecated ConfigMap
  deploy/addons/kubevirt/pod.yaml.tmpl
Labels: cncf-cla: yes, size/M, approved, needs-ok-to-test

#12940 Correcting minor typo in FAQ for --no-kubernetes
  site/content/en/docs/faq/_index.md
Labels: cncf-cla: yes, size/XS, needs-ok-to-test

#12916 fix grammar in `ingress-dns` documentation
  site/content/en/docs/handbook/addons/ingress-dns.md
Labels: cncf-cla: yes, size/XS, needs-ok-to-test

#12948 Fix french translation
  translations/fr.json
Labels: cncf-cla: yes, size/S, needs-ok-to-test

#12941 fix: do not let users run --no-kubernetes on the none driver
  cmd/minikube/cmd/start.go
Labels: cncf-cla: yes, size/XS, approved, needs-ok-to-test

#12935 Update Japanese translation (Line 100-149)
  translations/ja.json
Labels: cncf-cla: yes, size/M, lgtm

#12961 fix string extraction for translations
  pkg/minikube/extract/extract.go
  translations/de.json
  translations/es.json
  translations/fr.json
  translations/ja.json
  translations/ko.json
  translations/pl.json
  translations/strings.txt
  translations/zh-CN.json
Labels: cncf-cla: yes, size/M, approved

#12966 Fix out of bound exceptions
  cmd/minikube/cmd/root.go
  hack/benchmark/cpu_usage/auto_pause/chart.go
  hack/benchmark/cpu_usage/idle_only/chart.go
Labels: cncf-cla: yes, size/S, approved

#12972 Fix typo in help text for minikube docker-env command
  cmd/minikube/cmd/docker-env_test.go
  pkg/minikube/shell/shell.go
  pkg/minikube/shell/shell_test.go
Labels: cncf-cla: yes, size/S, needs-ok-to-test

#11909 Cleanup on ticker allocations.
  cmd/auto-pause/auto-pause.go
Labels: cncf-cla: yes, size/S, needs-ok-to-test, lifecycle/stale

#12975 Skip mount/any-port until mounting issue resolved
  test/integration/functional_test_mount_test.go
Labels: cncf-cla: yes, size/XS, approved

#12958 ensure --memory flag is within syslimit
  cmd/minikube/cmd/start.go
Labels: cncf-cla: yes, size/XS, approved, ok-to-test

#12978 Revert "Bump github.com/google/go-containerregistry from 0.6.0 to 0.7.0"
  go.mod
  go.sum
Labels: cncf-cla: yes, size/L, approved

#12952 Only check privileged ports for WSL
  cmd/minikube/cmd/start.go
  cmd/minikube/cmd/start_test.go
Labels: cncf-cla: yes, size/S, approved

#12976 Output tunnel has started message so users aren't confused if tunnel is running
  cmd/minikube/cmd/tunnel.go
Labels: cncf-cla: yes, size/S, approved

#12977 fix flag name in cache add
  cmd/minikube/cmd/cache.go
Labels: cncf-cla: yes, size/XS, approved

#12877 Added tests around loaded images.
  test/integration/functional_test.go
Labels: cncf-cla: yes, size/M, ok-to-test

#12985 site: tests docs change name
  pkg/generate/testdocs.go
Labels: cncf-cla: yes, size/XS, approved

#12980 Docs add windows versions of commands
  site/content/en/docs/handbook/addons/ingress-dns.md
  site/content/en/docs/handbook/config.md
  site/content/en/docs/handbook/kubectl.md
  site/content/en/docs/handbook/pushing.md
Labels: cncf-cla: yes, size/L, needs-ok-to-test

#12880 Update Japanese translation (Line 900-950)
  translations/ja.json
Labels: cncf-cla: yes, size/M, lgtm, needs-ok-to-test

#12998 Fix french translation
  translations/fr.json
Labels: cncf-cla: yes, size/S, needs-ok-to-test

#12942 Exit if --kubernetes-version and --no-kubernetes are specified.
  cmd/minikube/cmd/start.go
  test/integration/no_kubernetes_test.go
Labels: cncf-cla: yes, size/S, approved, ok-to-test

#13009 add retry check storage for preload generation
  hack/preload-images/generate.go
  hack/preload-images/preload_images.go
Labels: cncf-cla: yes, size/XS, approved

#11598 Support copy file from node to local host or between nodes.
  cmd/minikube/cmd/cp.go
  cmd/minikube/cmd/cp_test.go
  pkg/minikube/assets/vm_assets.go
  pkg/minikube/command/command_runner.go
  pkg/minikube/command/exec_runner.go
  pkg/minikube/command/fake_runner.go
  pkg/minikube/command/kic_runner.go
  pkg/minikube/command/ssh_runner.go
  pkg/minikube/cruntime/cruntime.go
  pkg/minikube/cruntime/cruntime_test.go
  test/integration/functional_test.go
  test/integration/helpers_test.go
  test/integration/multinode_test.go
  translations/de.json
  translations/es.json
  translations/fr.json
  translations/ja.json
  translations/ko.json
  translations/pl.json
  translations/strings.txt
  translations/zh-CN.json
Labels: cncf-cla: yes, size/XL, ok-to-test

#12993 Doc: Add macOS ARM64 Homebrew install option
  site/content/en/docs/start/_index.md
Labels: cncf-cla: yes, size/S, needs-ok-to-test

#13013 mount: fix `Bad file descriptor`
  test/integration/functional_test_mount_test.go
  third_party/go9p/srv_fcall.go
Labels: cncf-cla: yes, size/XS, approved, ok-to-test

#12973 Update OldestKubernetesVersion to v1.16.0
  pkg/minikube/bootstrapper/bsutil/testdata/v1.12/containerd-api-port.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.12/containerd-pod-network-cidr.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.12/containerd.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.12/crio-options-gates.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.12/crio.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.12/default.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.12/dns.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.12/image-repository.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.12/options.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.13/containerd-api-port.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.13/containerd-pod-network-cidr.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.13/containerd.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.13/crio-options-gates.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.13/crio.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.13/default.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.13/dns.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.13/image-repository.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.13/options.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.14/containerd-api-port.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.14/containerd-pod-network-cidr.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.14/containerd.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.14/crio-options-gates.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.14/crio.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.14/default.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.14/dns.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.14/image-repository.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.14/options.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.15/containerd-api-port.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.15/containerd-pod-network-cidr.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.15/containerd.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.15/crio-options-gates.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.15/crio.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.15/default.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.15/dns.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.15/image-repository.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.15/options.yaml
  pkg/minikube/constants/constants.go
Labels: cncf-cla: yes, size/XXL, approved, ok-to-test

#13015 Add support for port validation with ip
  cmd/minikube/cmd/start.go
  cmd/minikube/cmd/start_test.go
Labels: cncf-cla: yes, size/S, approved, ok-to-test

#13027 Update french translation
  translations/fr.json
Labels: cncf-cla: yes, size/XS, needs-ok-to-test

#12994 Update Japanese Translation (Line 960-)
  translations/ja.json
Labels: cncf-cla: yes, size/L, lgtm, needs-ok-to-test

#12992 Update Japanese Translation (Line 865-908)
  translations/ja.json
Labels: cncf-cla: yes, size/M, lgtm, needs-ok-to-test

#12991 Update Japanese translation (LINE 764-812)
  translations/ja.json
Labels: cncf-cla: yes, size/M, lgtm, needs-ok-to-test

#13040 Add some clarification on mounts needed for none
  site/content/en/docs/drivers/none.md
  site/content/en/docs/handbook/persistent_volumes.md
Labels: cncf-cla: yes, size/S, approved

#13052 time-to-k8s: Store chart and JSON files in AWS
  .github/workflows/time-to-k8s-public-chart.yml
  hack/benchmark/time-to-k8s/public-chart/generate-chart.go
  hack/benchmark/time-to-k8s/public-chart/public-chart.sh
  site/content/en/docs/benchmarks/timeToK8s/daily_benchmark.md
Labels: cncf-cla: yes, size/M, approved

#13055 time-to-k8s: Generate weekly average benchmark charts
  hack/benchmark/time-to-k8s/public-chart/generate-chart.go
  hack/benchmark/time-to-k8s/public-chart/public-chart.sh
  site/content/en/docs/benchmarks/timeToK8s/weekly_benchmark.md
Labels: cncf-cla: yes, size/L, approved

#13054 bump k8s lib
  go.mod
  go.sum
  hack/update/k8s-lib/bumpk8slib.sh
  pkg/trace/gcp.go
Labels: cncf-cla: yes, size/XL, approved, ok-to-test

#13056 time-to-k8s: Add table to release page
  hack/benchmark/time-to-k8s/chart.go
  hack/benchmark/time-to-k8s/time-to-k8s.sh
Labels: cncf-cla: yes, size/M, approved

#13018 mount: Fix `--mode` not being respected
  pkg/minikube/cluster/mount.go
Labels: cncf-cla: yes, size/XS, approved, ok-to-test

#13023 Update Japanese translation (Line 200-249)
  translations/ja.json
Labels: cncf-cla: yes, size/M, lgtm

#12981 Update Japanese translation (Line 694-710)
  translations/ja.json
Labels: cncf-cla: yes, size/M, lgtm, needs-ok-to-test
