Repository kubernetes/minikube, pull requests merged in 2021-08, with the labels that each got.

#12078 Allow building kicbase without pushing it
  Makefile
Labels: approved, cncf-cla: yes, size/XS

#12076 Auto start buildkit daemon on `image build` for containerd
  pkg/minikube/cruntime/containerd.go
  test/integration/functional_test.go
Labels: approved, cncf-cla: yes, ok-to-test, size/M

#12092 Fix french translation
  translations/fr.json
Labels: cncf-cla: yes, needs-ok-to-test, size/S

#12090 Add issue French template
  .github/ISSUE_TEMPLATE/fr.md
Labels: approved, cncf-cla: yes, needs-ok-to-test, size/S

#12107 Revert "fix whitespace in test yaml"
  pkg/minikube/bootstrapper/bsutil/testdata/v1.22/containerd-api-port.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.22/containerd-pod-network-cidr.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.22/containerd.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.22/crio.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.22/default.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.22/dns.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.22/image-repository.yaml
Labels: approved, cncf-cla: yes, size/S

#12040 Site: add icon to side bar items
  site/README.md
  site/content/en/docs/benchmarks/cpuUsage/linux.md
  site/content/en/docs/benchmarks/cpuUsage/macos.md
  site/content/en/docs/benchmarks/imageBuild/benchmarkingprocess.md
  site/content/en/docs/benchmarks/imageBuild/linuxbenchmark.md
  site/content/en/docs/benchmarks/imageBuild/macbenchmark.md
  site/content/en/docs/benchmarks/imageBuild/minikubevsothers.md
  site/content/en/docs/tutorials/custom_cert_ingress.md
  site/content/en/docs/tutorials/kubevirt.md
  site/content/en/docs/tutorials/multi_node.md
  site/content/en/docs/tutorials/nginx_tcp_udp_ingress.md
  site/content/en/docs/tutorials/nvidia_gpu.md
  site/content/en/docs/tutorials/setup_minikube_in_github_actions.md
  site/content/en/docs/tutorials/telemetry.md
  site/layouts/partials/sidebar-tree.html
Labels: cncf-cla: yes, needs-ok-to-test, size/L

#12105 Add message at bottom of page saying when the data was collected
  hack/jenkins/test-flake-chart/flake_chart.html
  hack/jenkins/test-flake-chart/flake_chart.js
Labels: cncf-cla: yes, size/S

#12112 Manage caching of HTML/JS/data.csv for public flake rate system
  hack/jenkins/test-flake-chart/flake_chart.html
  hack/jenkins/test-flake-chart/flake_chart.js
Labels: cncf-cla: yes, size/S

#12111 Replace yield iterator with simple await array
  hack/jenkins/test-flake-chart/flake_chart.js
Labels: approved, cncf-cla: yes, size/M

#12127 Fix `TestSkaffold` on Windows
  test/integration/skaffold_test.go
Labels: approved, cncf-cla: yes, ok-to-test, size/XS

#12134 Add documentation explaining the maintainer field for addons
  site/content/en/docs/contrib/addons.en.md
Labels: cncf-cla: yes, size/XS

#12125 Fix ScheduledStop tests
  test/integration/scheduled_stop_test.go
Labels: cncf-cla: yes, size/S, approved, ok-to-test

#12132 Move legacy version selection to its own function so tests are synced
  test/integration/version_upgrade_test.go
Labels: cncf-cla: yes, size/M, ok-to-test

#12131 Add unpause command under pause in docs
  site/content/en/docs/start/_index.md
Labels: cncf-cla: yes, size/XS, approved

#12119 Create tutorial for using a static token file
  site/content/en/docs/tutorials/token-auth-file.md
Labels: cncf-cla: yes, size/M, approved

#12129 ISO: Upgrade crictl (from cri-tools) to v1.21.0
  Makefile
  deploy/iso/minikube-iso/package/crictl-bin/crictl-bin.hash
  deploy/iso/minikube-iso/package/crictl-bin/crictl-bin.mk
  pkg/minikube/download/iso.go
  site/content/en/docs/commands/start.md
Labels: cncf-cla: yes, size/S, approved, ok-to-test

#12085 Fix the error output of minikube version --components command
  cmd/minikube/cmd/version.go
Labels: cncf-cla: yes, size/S, approved

#12141 fix extra line in update kubernetes automation
  hack/update/kubernetes_version/templates/v1beta2/containerd-api-port.yaml
  hack/update/kubernetes_version/templates/v1beta2/containerd-pod-network-cidr.yaml
  hack/update/kubernetes_version/templates/v1beta2/containerd.yaml
  hack/update/kubernetes_version/templates/v1beta2/crio.yaml
  hack/update/kubernetes_version/templates/v1beta2/default.yaml
  hack/update/kubernetes_version/templates/v1beta2/dns.yaml
  hack/update/kubernetes_version/templates/v1beta2/image-repository.yaml
Labels: cncf-cla: yes, size/S, approved

#12124 gcp-auth: always create the pull secret and don't require --force if …
  pkg/addons/addons_gcpauth.go
Labels: cncf-cla: yes, size/S, approved, ok-to-test

#12155 Fix not appending .exe to binary `TestSkaffold`
  test/integration/skaffold_test.go
Labels: cncf-cla: yes, size/S, approved, ok-to-test

#12146 Mark ssh driver and image build as completed in roadmap
  site/content/en/docs/contrib/roadmap.en.md
Labels: cncf-cla: yes, size/XS, approved

#12122 ISO: Upgrade Docker, from 20.10.6 to 20.10.8
  Makefile
  deploy/iso/minikube-iso/package/containerd-bin/containerd-bin.hash
  deploy/iso/minikube-iso/package/containerd-bin/containerd-bin.mk
  deploy/iso/minikube-iso/package/docker-bin/docker-bin.hash
  deploy/iso/minikube-iso/package/docker-bin/docker-bin.mk
  deploy/iso/minikube-iso/package/runc-master/runc-master.hash
  deploy/iso/minikube-iso/package/runc-master/runc-master.mk
  pkg/minikube/download/iso.go
  site/content/en/docs/commands/start.md
Labels: cncf-cla: yes, size/S, approved, ok-to-test

#12135 Make sure to return valid containerd version
  pkg/minikube/cruntime/containerd.go
  pkg/minikube/cruntime/containerd_test.go
Labels: cncf-cla: yes, size/M, approved, ok-to-test

#12106 configure gcp-auth addon pull secret to work with all GCR and AR mirrors
  go.mod
  go.sum
  pkg/addons/addons_gcpauth.go
  test/integration/addons_test.go
  test/integration/testdata/private-image-eu.yaml
Labels: cncf-cla: yes, size/M, approved, ok-to-test

#12143 Fix loading an image from tar failing on existing delete
  pkg/minikube/machine/cache_images.go
  test/integration/functional_test.go
Labels: cncf-cla: yes, size/M, approved, ok-to-test

#12179 Ping `releases.json` file if `WantUpdateNotification` is false
  pkg/minikube/notify/notify.go
Labels: cncf-cla: yes, size/XS, approved

#12180 display the URL to the logs on failed kicbase/iso builds
  hack/jenkins/build_iso.sh
  hack/jenkins/kicbase_auto_build.sh
Labels: cncf-cla: yes, size/S, approved

#12154 Create issues automatically for flaky tests
  hack/jenkins/test-flake-chart/compute_flake_rate.sh
Labels: cncf-cla: yes, size/L

#12187 Ensure gh is installed for compute_flake_rate.sh
  hack/jenkins/test-flake-chart/compute_flake_rate.sh
Labels: cncf-cla: yes, size/XS, approved

#12224 Add priority/backlog label to all newly created issues
  hack/jenkins/test-flake-chart/compute_flake_rate.sh
Labels: cncf-cla: yes, size/XS, approved

#12176 Change date range to be relative to the current day
  hack/jenkins/test-flake-chart/compute_flake_rate.go
  hack/jenkins/test-flake-chart/compute_flake_rate_test.go
  hack/jenkins/test-flake-chart/report_flakes.sh
Labels: cncf-cla: yes, size/L, approved

#12229 Add link to flake charts in auto-created issues
  hack/jenkins/test-flake-chart/compute_flake_rate.sh
Labels: cncf-cla: yes, size/XS

#12184 Go back to upstream google/go-containerregistry
  go.mod
  go.sum
  pkg/minikube/download/image.go
Labels: cncf-cla: yes, size/M, approved, ok-to-test

#12183 Fix typo in addons/ingress-dns
  site/content/en/docs/handbook/addons/ingress-dns.md
Labels: cncf-cla: yes, size/XS, approved, needs-ok-to-test

#12244 Add link directly to test log for gopogh link
  hack/jenkins/test-flake-chart/flake_chart.js
Labels: cncf-cla: yes, size/S

#12239 Add `--volumes` to `docker system prune`
  .github/workflows/pr_verified.yaml
  hack/jenkins/windows_cleanup_and_reboot_docker.ps1
  hack/jenkins/windows_integration_teardown.ps1
Labels: cncf-cla: yes, size/XS, approved

#12245 Skip describing non-running pods if none present
  test/integration/helpers_test.go
Labels: cncf-cla: yes, size/XS, approved

#12248 add automation to update golint version
  .github/workflows/update-golang-version.yml
  .github/workflows/update-golint-version.yml
  Makefile
  hack/update/golang_version/update_golang_version.go
  hack/update/golint_version/update_golint_version.go
Labels: cncf-cla: yes, size/L, approved

#12228 Print profile driver, container runtime, and Kubernetes version on load
  pkg/minikube/config/config.go
  pkg/minikube/config/profile.go
Labels: cncf-cla: yes, size/S, ok-to-test

#12252 Fix lint for gocilint 1.41.1
  Makefile
  cmd/auto-pause/auto-pause-hook/config.go
  cmd/minikube/cmd/delete.go
  cmd/minikube/cmd/delete_test.go
  hack/benchmark/cpu_usage/auto_pause/chart.go
  hack/benchmark/cpu_usage/idle_only/chart.go
  pkg/gvisor/enable.go
  pkg/minikube/bootstrapper/certs.go
  pkg/minikube/cruntime/cri.go
  pkg/minikube/proxy/proxy_test.go
  pkg/minikube/registry/drvs/docker/docker_test.go
  pkg/minikube/tunnel/route_darwin.go
  pkg/minikube/tunnel/route_linux.go
  pkg/provision/provision.go
Labels: cncf-cla: yes, size/M, approved

#12253 change deprecated golint to revive and fix lint issues
  Makefile
  hack/benchmark/time-to-k8s/chart.go
  hack/update/registry.go
  hack/update/update.go
  pkg/addons/addons.go
  pkg/drivers/hyperkit/driver.go
  pkg/drivers/none/none.go
  pkg/drivers/ssh/ssh.go
  pkg/minikube/config/profile.go
  pkg/minikube/download/download.go
  pkg/minikube/download/preload.go
  pkg/minikube/driver/driver_darwin.go
  pkg/minikube/kubeconfig/context.go
  pkg/minikube/kubeconfig/extension.go
  pkg/minikube/node/start.go
  pkg/minikube/shell/shell.go
  test/integration/functional_test_mount_test.go
Labels: cncf-cla: yes, size/M, approved, ok-to-test

#12032 Upgrade buildkit from 0.8.2 to 0.9.0
  Makefile
  deploy/iso/minikube-iso/package/buildkit-bin/buildkit-bin.hash
  deploy/iso/minikube-iso/package/buildkit-bin/buildkit-bin.mk
  deploy/kicbase/Dockerfile
  pkg/drivers/kic/types.go
  pkg/minikube/download/iso.go
  site/content/en/docs/commands/start.md
Labels: cncf-cla: yes, size/S, approved, ok-to-test

#12227 test: Increase time waiting for `minikube stop` to complete
  test/integration/scheduled_stop_test.go
Labels: cncf-cla: yes, size/XS, approved, ok-to-test

#12162 Image save command
  cmd/minikube/cmd/image.go
  pkg/minikube/assets/vm_assets.go
  pkg/minikube/command/command_runner.go
  pkg/minikube/command/exec_runner.go
  pkg/minikube/command/fake_runner.go
  pkg/minikube/command/kic_runner.go
  pkg/minikube/command/ssh_runner.go
  pkg/minikube/cruntime/cruntime.go
  pkg/minikube/cruntime/cruntime_test.go
  pkg/minikube/image/image.go
  pkg/minikube/machine/cache_images.go
  pkg/minikube/reason/reason.go
  site/content/en/docs/commands/image.md
  site/content/en/docs/contrib/errorcodes.en.md
Labels: cncf-cla: yes, size/XL, approved, ok-to-test

#12144 doc: refresh roadmap year date and sort checkboxes
  site/content/en/docs/contrib/roadmap.en.md
Labels: cncf-cla: yes, size/XS, needs-ok-to-test

#11745 Clean up ssh tunnels during exit.
  pkg/minikube/tunnel/kic/ssh_conn.go
  pkg/minikube/tunnel/kic/ssh_tunnel.go
Labels: cncf-cla: yes, size/M, ok-to-test

#12079 Build kicbase image for all architectures
  Makefile
Labels: cncf-cla: yes, size/XS, approved

#12163 Add external package management page under Minikube contribution
  site/content/en/docs/contrib/external-packages.en.md
Labels: cncf-cla: yes, size/S, needs-ok-to-test

#12086 Update custom_cert_ingress.md
  site/content/en/docs/tutorials/custom_cert_ingress.md
Labels: cncf-cla: yes, size/XS, needs-ok-to-test

#11768 KVM2 driver for linux/aarch64
  Makefile
  pkg/drivers/kvm/domain.go
  pkg/drivers/kvm/domain_definition_arm64.go
  pkg/drivers/kvm/domain_definition_x86.go
  pkg/drivers/kvm/kvm.go
  pkg/minikube/download/driver.go
Labels: cncf-cla: yes, size/L, approved, ok-to-test

#12260 Revert "new `image save` command"
  cmd/minikube/cmd/image.go
  pkg/minikube/assets/vm_assets.go
  pkg/minikube/command/command_runner.go
  pkg/minikube/command/exec_runner.go
  pkg/minikube/command/fake_runner.go
  pkg/minikube/command/kic_runner.go
  pkg/minikube/command/ssh_runner.go
  pkg/minikube/cruntime/cruntime.go
  pkg/minikube/cruntime/cruntime_test.go
  pkg/minikube/image/image.go
  pkg/minikube/machine/cache_images.go
  pkg/minikube/reason/reason.go
  site/content/en/docs/commands/image.md
  site/content/en/docs/contrib/errorcodes.en.md
Labels: cncf-cla: yes, size/XL, approved

#12243 Fix test failures occuring in partially-"branching" tests
  test/integration/addons_test.go
  test/integration/functional_test_tunnel_test.go
  test/integration/guest_env_test.go
  test/integration/json_output_test.go
  test/integration/version_upgrade_test.go
Labels: cncf-cla: yes, size/L, do-not-merge/work-in-progress, ok-to-test

#12279 Add solution message for cgroup related issues on nested cloud-shell
  pkg/minikube/reason/known_issues.go
Labels: cncf-cla: yes, size/M, approved

#12281 Replace Math.min with destructuring with custom array min.
  hack/jenkins/test-flake-chart/flake_chart.js
Labels: cncf-cla: yes, size/S

#12230 bump calico to v3.20 and move away from v1beta apis
  deploy/addons/ambassador/ambassador-operator-crds.yaml.tmpl
  deploy/addons/ingress-dns/ingress-dns-pod.yaml.tmpl
  deploy/addons/istio-provisioner/istio-operator.yaml.tmpl
  pkg/minikube/bootstrapper/images/images.go
  pkg/minikube/cni/calico.go
  pkg/minikube/cni/calico.yaml
  pkg/minikube/cni/flannel.go
  site/content/en/docs/tutorials/includes/kube-flannel.yaml
  test/integration/addons_test.go
  test/integration/testdata/nginx-ingv1beta.yaml
Labels: cncf-cla: yes, size/XXL, approved, ok-to-test

#12268 Upgrade Buildroot to 2021.02 LTS with Linux 4.19
  Makefile
  deploy/iso/minikube-iso/board/coreos/minikube/patches/go/1.15.15/dist-generate-stub-go.mod-in-workdir.patch
  deploy/iso/minikube-iso/board/coreos/minikube/rootfs-overlay/etc/sysctl.d/90-cilium-rp_filter.conf
  deploy/iso/minikube-iso/configs/minikube_defconfig
  pkg/minikube/download/iso.go
  site/content/en/docs/commands/start.md
Labels: cncf-cla: yes, size/L, approved, ok-to-test

#12267 fix boilerplate check for time-to-k8s git submodule
  test.sh
Labels: cncf-cla: yes, size/XS, approved

#12263 Add output parameter to the docker-env none shell
  cmd/minikube/cmd/docker-env.go
  cmd/minikube/cmd/docker-env_test.go
  site/content/en/docs/commands/docker-env.md
Labels: cncf-cla: yes, size/L, approved

#12297 Display flake chart date in a better format
  hack/jenkins/test-flake-chart/flake_chart.js
Labels: cncf-cla: yes, size/S

#12314 fix unit tests by comparing JSON structs
  pkg/minikube/out/out_reason_test.go
  pkg/minikube/out/register/json_test.go
  pkg/minikube/out/register/register_test.go
  pkg/minikube/tests/json_utils.go
Labels: cncf-cla: yes, size/L, approved

#12318 pause each container separately
  pkg/minikube/cruntime/cri.go
Labels: cncf-cla: yes, size/XS, approved, ok-to-test

#12089 Support Ingress on MacOS, driver docker
  cmd/minikube/cmd/tunnel.go
  pkg/addons/addons.go
  pkg/minikube/out/out.go
  pkg/minikube/tunnel/kic/ssh_conn.go
  pkg/minikube/tunnel/kic/ssh_tunnel.go
  test/integration/addons_test.go
Labels: cncf-cla: yes, size/M, approved, ok-to-test

#12326 Add `minikube image` commands for pull and tag and push
  cmd/minikube/cmd/image.go
  pkg/minikube/cruntime/containerd.go
  pkg/minikube/cruntime/crio.go
  pkg/minikube/cruntime/cruntime.go
  pkg/minikube/cruntime/docker.go
  pkg/minikube/machine/cache_images.go
  pkg/minikube/reason/reason.go
  site/content/en/docs/commands/image.md
  site/content/en/docs/contrib/errorcodes.en.md
  translations/strings.txt
Labels: cncf-cla: yes, size/L, approved, ok-to-test

#12295 Fix french translation
  translations/fr.json
Labels: cncf-cla: yes, size/S, needs-ok-to-test

#12329 Fix typo in FAQ docs
  site/content/en/docs/faq/_index.md
Labels: cncf-cla: yes, size/XS

#12331 Add kubeadm image versions for kubernetes 1.22
  pkg/minikube/bootstrapper/images/images.go
  pkg/minikube/bootstrapper/images/images_test.go
  pkg/minikube/download/preload.go
Labels: cncf-cla: yes, size/S, approved, ok-to-test

#12337 fix changed files output for github actions
  .github/workflows/docs.yml
  .github/workflows/leaderboard.yml
  .github/workflows/update-k8s-versions.yml
Labels: cncf-cla: yes, size/S, approved

#12237 Fix minikube restart on Cloud Shell
  cmd/minikube/cmd/start_flags.go
  hack/jenkins/cloud_shell_functional_tests_docker.sh
  test/integration/start_stop_delete_test.go
Labels: cncf-cla: yes, size/S, approved, ok-to-test

#12341 bump gcp-auth-webhook to v0.0.7
  pkg/minikube/assets/addons.go
Labels: cncf-cla: yes, size/XS, approved, ok-to-test

#12346 upgrade box-cli-maker to 2.2.2
  go.mod
  go.sum
Labels: cncf-cla: yes, size/S, approved

#12319 Select WSL VM IP when performing mounting
  cmd/minikube/cmd/mount.go
Labels: cncf-cla: yes, size/S

#12350 fix link to iso/kicbase logs on build failure
  hack/jenkins/build_iso.sh
  hack/jenkins/kicbase_auto_build.sh
Labels: cncf-cla: yes, size/XS, approved

#12339 Add minikube-ci/examples to docs
  README.md
  site/content/en/docs/_index.md
  site/content/en/docs/tutorials/continuous_integration.md
Labels: cncf-cla: yes, size/S, approved

#12372 Fix french translation
  translations/fr.json
Labels: cncf-cla: yes, size/M, needs-ok-to-test

#12359 Support Rootless Docker
  cmd/minikube/cmd/start_flags.go
  deploy/kicbase/Dockerfile
  deploy/kicbase/containerd-fuse-overlayfs.service
  deploy/kicbase/entrypoint
  hack/preload-images/generate.go
  pkg/drivers/kic/oci/network.go
  pkg/drivers/kic/oci/oci.go
  pkg/minikube/cruntime/containerd.go
  pkg/minikube/cruntime/crio.go
  pkg/minikube/cruntime/cruntime.go
  pkg/minikube/cruntime/cruntime_test.go
  pkg/minikube/cruntime/docker.go
  pkg/minikube/driver/driver.go
  pkg/minikube/node/start.go
  pkg/minikube/registry/drvs/docker/docker.go
  site/content/en/docs/drivers/docker.md
  site/content/en/docs/drivers/includes/docker_usage.inc
Labels: cncf-cla: yes, size/L, ok-to-test

#12375 Fix go bump automation to adopt Kubernetes new kube-cross image name
  Makefile
  hack/update/golang_version/update_golang_version.go
Labels: cncf-cla: yes, size/S, approved

#12351 Add `--extra-disks` capability to kvm2 driver
  cmd/minikube/cmd/start_flags.go
  pkg/drivers/kvm/disks.go
  pkg/drivers/kvm/domain_definition_arm64.go
  pkg/drivers/kvm/domain_definition_x86.go
  pkg/drivers/kvm/kvm.go
  pkg/minikube/config/types.go
  pkg/minikube/registry/drvs/kvm2/kvm2.go
  site/content/en/docs/commands/start.md
Labels: cncf-cla: yes, size/L, approved, needs-ok-to-test

#12377 fix deprecated image in helm addon
  pkg/minikube/assets/addons.go
Labels: cncf-cla: yes, size/XS, approved, ok-to-test
