Repository kubernetes/minikube, pull requests merged in 2021-07, with the labels that each got.

#11848 Fix French translation
  translations/fr.json
Labels: approved, cncf-cla: yes, needs-ok-to-test, size/XS

#11819 windows: support renaming binary to `kubectl.exe` and running as kubectl
  cmd/minikube/cmd/root.go
  cmd/minikube/main.go
  test/integration/functional_test.go
Labels: approved, cncf-cla: yes, ok-to-test, size/XS

#11856 Add rank and growth columns to flake percentage list
  hack/jenkins/test-flake-chart/flake_chart.js
Labels: cncf-cla: yes, size/S

#11626 add test for proxies with custom certs
  test/integration/functional_test.go
Labels: approved, cncf-cla: yes, ok-to-test, size/L

#11859 site: Add beta releases to website installation instructions
  site/content/en/docs/start/_index.md
  site/layouts/shortcodes/quiz_instruction.html
Labels: cncf-cla: yes, needs-ok-to-test, size/L

#11852 Fix TestDebPackageInstall test
  Makefile
Labels: approved, cncf-cla: yes, ok-to-test, size/XS

#11860 reformat PR description for gendocs
  .github/workflows/docs.yml
Labels: approved, cncf-cla: yes, size/XS

#11863 auto bump kubernetes version using github actions
  .github/workflows/update-k8s-versions.yml
  hack/update/golang_version/update_golang_version.go
Labels: approved, cncf-cla: yes, size/M

#11843 `minikube version`: add `--components` flag to list all included software
  cmd/minikube/cmd/version.go
  test/integration/functional_test.go
Labels: approved, cncf-cla: yes, ok-to-test, size/M

#11773 Adds explanations for all minikube error codes
  cmd/minikube/cmd/root.go
  cmd/minikube/cmd/start.go
  cmd/minikube/cmd/stop.go
  pkg/minikube/reason/reason.go
Labels: cncf-cla: yes, needs-ok-to-test, size/L

#11867 add ok-to-test label automatically to update k8s workflow
  .github/workflows/update-k8s-versions.yml
Labels: approved, cncf-cla: yes, size/XS

#11851 Replace integration test "hooks" with standalone scripts
  hack/jenkins/common.sh
  hack/jenkins/minikube_set_pending.sh
  hack/jenkins/test-flake-chart/sync_tests.sh
  hack/jenkins/test-flake-chart/upload_tests.sh
  hack/jenkins/upload_integration_report.sh
  hack/jenkins/windows_integration_test_docker.ps1
Labels: approved, cncf-cla: yes, ok-to-test, size/M

#11877 update crio-bin hash
  deploy/iso/minikube-iso/package/crio-bin/crio-bin.hash
Labels: approved, cncf-cla: yes, size/XS

#11794 Show GCS report links in integration test logs
  hack/jenkins/common.sh
Labels: approved, cncf-cla: yes, ok-to-test, size/S

#11826 Add a sanity test for beta releases
  Makefile
  deploy/minikube/release_sanity_test.go
  deploy/minikube/releases-beta.json
Labels: approved, cncf-cla: yes, ok-to-test, size/S

#11874 More charts
  hack/jenkins/test-flake-chart/flake_chart.js
Labels: approved, cncf-cla: yes, size/L

#11866 site: add faq for running minikube on different drive
  site/content/en/docs/faq/_index.md
Labels: approved, cncf-cla: yes, size/S

#11857 fix kvm2-arm64 scripts
  .github/workflows/pr_verified.yaml
  hack/jenkins/minikube_cross_build_and_upload.sh
Labels: approved, cncf-cla: yes, ok-to-test, pr_verified, size/XS

#11880 Fix typo in unpause command
  cmd/minikube/cmd/unpause.go
Labels: approved, cncf-cla: yes, kind/bug, needs-ok-to-test, size/XS

#11875 Fix typo in pause command
  cmd/minikube/cmd/pause.go
Labels: approved, cncf-cla: yes, kind/bug, needs-ok-to-test, size/XS

#11779 Fix indentation of JSON Kubernetes manifest in docs
  site/content/en/docs/handbook/mount.md
Labels: approved, cncf-cla: yes, needs-ok-to-test, size/M

#11892 Replace single preload cache with a preload map cache.
  pkg/minikube/download/download_test.go
  pkg/minikube/download/preload.go
Labels: approved, cncf-cla: yes, ok-to-test, size/L

#11895 ci: add bot to announce minikube release on twitter
  .github/workflows/twitter-bot.yml
Labels: approved, cncf-cla: yes, size/S

#11899 Complete French translation
  translations/fr.json
Labels: approved, cncf-cla: yes, needs-ok-to-test, size/XS

#11800 Simplify, and remove all un-used minikube error codes
  cmd/minikube/cmd/config/disable.go
  cmd/minikube/cmd/config/enable.go
  pkg/minikube/reason/reason.go
Labels: approved, cncf-cla: yes, kind/cleanup, needs-ok-to-test, size/M

#11916 Make sync_tests.sh remove any _integration suffix
  hack/jenkins/test-flake-chart/sync_tests.sh
Labels: approved, cncf-cla: yes, size/XS

#11708 Make sure to log errors from DaemonInfo
  pkg/drivers/kic/oci/info.go
Labels: approved, cncf-cla: yes, size/XS

#11919 Move environment start saving up in minikube_set_pending
  hack/jenkins/minikube_set_pending.sh
Labels: approved, cncf-cla: yes, ok-to-test, size/S

#11917 Create Github Action automation of update-leaderboard
  .github/workflows/leaderboard.yml
Labels: cncf-cla: yes, size/M

#11920 Bump Makefile for v1.22.0 release
  CHANGELOG.md
  Makefile
Labels: approved, cncf-cla: yes, ok-to-test, size/M

#11923 brew automation: Update contact to Medya
  hack/jenkins/release_update_brew.sh
Labels: approved, cncf-cla: yes, size/XS

#11927 site: add twitter to site footer
  site/config.toml
Labels: approved, cncf-cla: yes, size/XS

#11928 Fix typos
  README.md
  test/integration/multinode_test.go
Labels: approved, cncf-cla: yes, needs-ok-to-test, size/XS

#11929 Update creating PR for time-to-k8s
  .github/workflows/time-to-k8s.yml
  hack/benchmark/time-to-k8s/time-to-k8s.sh
Labels: approved, cncf-cla: yes, size/M

#11939 Allow manual triggering of GitHub Actions
  .github/workflows/build.yml
  .github/workflows/docs.yml
  .github/workflows/leaderboard.yml
  .github/workflows/master.yml
  .github/workflows/pr.yml
  .github/workflows/pr_verified.yaml
  .github/workflows/time-to-k8s.yml
  .github/workflows/translations.yml
  .github/workflows/twitter-bot.yml
  .github/workflows/update-k8s-versions.yml
Labels: approved, cncf-cla: yes, size/S

#11943 time-to-k8s: Leave committing to GitHub Action
  hack/benchmark/time-to-k8s/time-to-k8s.sh
Labels: approved, cncf-cla: yes, size/S

#11553 Allow to set the dashboard proxyfied port
  cmd/minikube/cmd/dashboard.go
  site/content/en/docs/commands/dashboard.md
  test/integration/functional_test.go
  translations/de.json
  translations/es.json
  translations/fr.json
  translations/ja.json
  translations/ko.json
  translations/pl.json
  translations/strings.txt
  translations/zh-CN.json
Labels: cncf-cla: yes, ok-to-test, size/S

#11585 minikube start --image-repository will now accept URLs with port
  cmd/minikube/cmd/start.go
  cmd/minikube/cmd/start_test.go
Labels: approved, cncf-cla: yes, ok-to-test, size/M

#11924 Use 'gh auth' to get gh token for leaderboard update
  .github/workflows/leaderboard.yml
  hack/update_contributions.sh
Labels: approved, cncf-cla: yes, size/S

#11893 Refactor checkRemotePreloadExists to no longer include caching logic
  pkg/minikube/download/download_test.go
  pkg/minikube/download/preload.go
Labels: approved, cncf-cla: yes, ok-to-test, size/S

#11921 Use THE_COMMIT env var instead of ghprbActualCommit
  hack/jenkins/minikube_set_pending.sh
Labels: approved, cncf-cla: yes, ok-to-test, size/XS

#11948 Retain full container name when passing --image-repository
  pkg/minikube/bootstrapper/images/images.go
  pkg/minikube/bootstrapper/images/images_test.go
  pkg/minikube/bootstrapper/images/kubeadm_test.go
  pkg/minikube/bootstrapper/images/repo.go
  pkg/minikube/node/cache.go
Labels: cncf-cla: yes, ok-to-test, size/M

#11933 Add addon support for portainer
  deploy/addons/assets.go
  deploy/addons/portainer/portainer.yaml.tmpl
  pkg/addons/config.go
  pkg/minikube/assets/addons.go
Labels: cncf-cla: yes, ok-to-test, size/L

#11941 minor fixes in common.sh
  hack/jenkins/common.sh
  hack/jenkins/installers/check_install_golang.sh
Labels: approved, cncf-cla: yes, ok-to-test, size/S

#11950 Create common.ps1 to simplify Windows integration tests
  hack/jenkins/common.ps1
  hack/jenkins/minikube_set_pending.sh
  hack/jenkins/test-flake-chart/report_flakes.sh
  hack/jenkins/test-flake-chart/sync_tests.sh
  hack/jenkins/windows_integration_setup.ps1
  hack/jenkins/windows_integration_teardown.ps1
  hack/jenkins/windows_integration_test_docker.ps1
  hack/jenkins/windows_integration_test_hyperv.ps1
  hack/jenkins/windows_integration_test_virtualbox.ps1
Labels: cncf-cla: yes, ok-to-test, size/L

#11757 Create design doc for public flake rate system
  enhancements/implemented/20210624-flake-rate/flake-rate.md
Labels: approved, cncf-cla: yes, size/M

#11971 Update ISO release instructions
  site/content/en/docs/contrib/releasing/iso.md
Labels: approved, cncf-cla: yes, size/XS

#11969 Add missing language labels to issue templates
  .github/ISSUE_TEMPLATE/fa.md
  .github/ISSUE_TEMPLATE/ku.md
Labels: approved, cncf-cla: yes, size/XS

#11962 Purge all previous minikube data before functional testing in Github Actions.
  .github/workflows/pr.yml
  test/integration/functional_test.go
Labels: approved, cncf-cla: yes, size/S

#11988 Set specific GO_VERSION env for leaderboard workflow
  .github/workflows/leaderboard.yml
  hack/update/golang_version/update_golang_version.go
Labels: cncf-cla: yes, size/XS

#11989 Fix update_contributions using SSH pull url and release_notes using gh_token.txt.
  hack/release_notes.sh
  hack/update_contributions.sh
Labels: approved, cncf-cla: yes, size/S

#11918 Use gotestsum for testing output and json output.
  hack/jenkins/common.ps1
  hack/jenkins/common.sh
  hack/jenkins/installers/check_install_gotestsum.sh
  hack/jenkins/windows_integration_test_docker.ps1
Labels: cncf-cla: yes, ok-to-test, size/M

#11937 Fix kvm2 driver arm64 deb package
  Makefile
Labels: approved, cncf-cla: yes, ok-to-test, size/XS

#11991 Windows: detect Powershell spawned from CMD
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, ok-to-test, size/XS

#11951 time-to-k8s Public Charts
  .github/workflows/time-to-k8s-public-chart.yml
  hack/benchmark/time-to-k8s/public-chart/containerd-benchmark.yaml
  hack/benchmark/time-to-k8s/public-chart/docker-benchmark.yaml
  hack/benchmark/time-to-k8s/public-chart/generate-chart.go
  hack/benchmark/time-to-k8s/public-chart/public-chart.sh
  hack/benchmark/time-to-k8s/time-to-k8s.sh
  hack/update/golang_version/update_golang_version.go
  site/content/en/docs/benchmarks/timeToK8s/daily_benchmark.md
Labels: approved, cncf-cla: yes, size/L

#12016 Order time-to-k8s benchmarks from newest to oldest
  hack/benchmark/time-to-k8s/time-to-k8s.sh
  site/content/en/docs/benchmarks/timeToK8s/v1.20.0.md
  site/content/en/docs/benchmarks/timeToK8s/v1.21.0.md
  site/content/en/docs/benchmarks/timeToK8s/v1.22.0.md
Labels: approved, cncf-cla: yes, size/XS

#11986 Fix flake report script not commenting
  hack/jenkins/test-flake-chart/report_flakes.sh
  hack/jenkins/test-flake-chart/sync_tests.sh
Labels: cncf-cla: yes, ok-to-test, size/S

#12024 OWNERS file cleanup
  OWNERS
Labels: approved, cncf-cla: yes, size/XS

#12020 Change link formatting
  site/content/en/docs/tutorials/telemetry.md
Labels: approved, cncf-cla: yes, needs-ok-to-test, size/XS

#11420 Use fully qualified image name for kicbase image from docker hub
  hack/jenkins/kicbase_auto_build.sh
  pkg/drivers/kic/types.go
Labels: cncf-cla: yes, ok-to-test, size/XS

#11940 Add a suggestion for unhealthy control plane due to control plane not updated.
  pkg/minikube/reason/known_issues.go
Labels: approved, cncf-cla: yes, ok-to-test, size/S

#12028 Updated PingHostFrom2Pods test to actually ping the host from the pod
  test/integration/multinode_test.go
Labels: approved, cncf-cla: yes, ok-to-test, size/S

#12035 make sure to sync certs from all documented locations
  pkg/minikube/bootstrapper/certs.go
  test/integration/functional_test.go
  test/integration/testdata/minikube_test2.pem
Labels: approved, cncf-cla: yes, ok-to-test, size/L

#12044 Make flake rate commenting more useful, and improve flake rate charts
  hack/jenkins/test-flake-chart/flake_chart.html
  hack/jenkins/test-flake-chart/flake_chart.js
  hack/jenkins/test-flake-chart/report_flakes.sh
Labels: cncf-cla: yes, size/L

#12047 Bump gopogh version from v0.8.0 to v0.9.0
  .github/workflows/master.yml
  .github/workflows/pr.yml
  .github/workflows/pr_verified.yaml
  hack/jenkins/common.ps1
  hack/jenkins/common.sh
Labels: cncf-cla: yes, size/M

#11872 site: Add command-line download instructions for windows binary
  site/content/en/docs/start/_index.md
Labels: approved, cncf-cla: yes, kind/documentation, needs-ok-to-test, priority/important-longterm, size/M

#11972 Clean up extra spaces
  deploy/addons/dashboard/dashboard-secret.yaml
Labels: cncf-cla: yes, ok-to-test, size/XS

#11979 Add configurable port for minikube mount
  cmd/minikube/cmd/mount.go
  pkg/minikube/cluster/mount.go
  pkg/minikube/reason/reason.go
  test/integration/functional_test_mount_test.go
Labels: approved, cncf-cla: yes, ok-to-test, size/L

#11981 Add message to discourage the use of the virtualbox driver
  cmd/minikube/cmd/config/config.go
  cmd/minikube/cmd/root.go
  pkg/minikube/config/config.go
  pkg/minikube/node/start.go
  site/content/en/docs/commands/config.md
Labels: approved, cncf-cla: yes, needs-ok-to-test, size/M

#11709 Add method for customized box output
  pkg/minikube/out/out.go
  pkg/minikube/out/out_test.go
Labels: approved, cncf-cla: yes, ok-to-test, size/L

#12060 Replace duration chart with total duration of tests -line
  hack/jenkins/common.ps1
  hack/jenkins/common.sh
  hack/jenkins/test-flake-chart/compute_flake_rate.go
  hack/jenkins/test-flake-chart/flake_chart.js
  hack/jenkins/test-flake-chart/process_data.sh
Labels: approved, cncf-cla: yes, ok-to-test, size/L

#12064 Parse report data correctly in report_flakes
  hack/jenkins/test-flake-chart/report_flakes.sh
Labels: cncf-cla: yes, ok-to-test, size/XS

#11942 Add image cleanup for local image during cache test
  test/integration/functional_test.go
Labels: cncf-cla: yes, ok-to-test, size/S

#12066 Make download.download not use progress bar if not in tty.
  pkg/minikube/download/download.go
Labels: approved, cncf-cla: yes, ok-to-test, size/S

#11968 Added restart command after setting crio options
  pkg/provision/provision.go
Labels: cncf-cla: yes, ok-to-test, size/XS

#11842 kvm: only check libvirt membership if we failed to connect to it
  pkg/minikube/registry/drvs/kvm2/kvm2.go
Labels: cncf-cla: yes, ok-to-test, size/M

#11549 Site: update versionApi for Ingress Kubernetes definition
  site/content/en/docs/tutorials/ambassador_ingress_controller.md
Labels: approved, cncf-cla: no, needs-ok-to-test, size/XS

#12065 Use job id for logs instead of short commit hash
  enhancements/implemented/20210624-flake-rate/flake-rate.md
  hack/jenkins/build_iso.sh
  hack/jenkins/common.ps1
  hack/jenkins/common.sh
  hack/jenkins/kicbase_auto_build.sh
  hack/jenkins/minikube_set_pending.sh
  hack/jenkins/test-flake-chart/flake_chart.js
  hack/jenkins/test-flake-chart/report_flakes.sh
  hack/jenkins/test-flake-chart/sync_tests.sh
  hack/jenkins/upload_integration_report.sh
  hack/jenkins/windows_integration_test_docker.ps1
Labels: cncf-cla: yes, ok-to-test, size/M

#12068 Add brackets around variable name to prevent scoping problems
  hack/jenkins/common.ps1
Labels: approved, cncf-cla: yes, size/XS

#11483 Add ability to create extra disks on hyperkit vms
  Makefile
  cmd/minikube/cmd/start_flags.go
  deploy/iso/minikube-iso/package/automount/minikube-automount
  pkg/drivers/common.go
  pkg/drivers/hyperkit/driver.go
  pkg/minikube/config/types.go
  pkg/minikube/download/iso.go
  pkg/minikube/registry/drvs/hyperkit/hyperkit.go
  site/content/en/docs/commands/start.md
Labels: approved, cncf-cla: yes, ok-to-test, size/M

#11945 don't try to recreate pull secrets for refreshing gcp-auth
  pkg/addons/addons_gcpauth.go
Labels: approved, cncf-cla: yes, ok-to-test, size/M

#12059 Add CI bot to bump golang version to match Kubernetes golang
  .github/workflows/build.yml
  .github/workflows/docs.yml
  .github/workflows/leaderboard.yml
  .github/workflows/master.yml
  .github/workflows/pr.yml
  .github/workflows/pr_verified.yaml
  .github/workflows/time-to-k8s-public-chart.yml
  .github/workflows/time-to-k8s.yml
  .github/workflows/translations.yml
  .github/workflows/update-golang-version.yml
  .github/workflows/update-k8s-versions.yml
  Makefile
  hack/update/golang_version/update_golang_version.go
Labels: approved, cncf-cla: yes, size/L
