Repository kubernetes/minikube, pull requests merged in 2021-10, with the labels that each got.

#12246 Don't error if we can't retrieve logs from a pod during `minikube logs`
  cmd/minikube/cmd/logs.go
Labels: cncf-cla: yes, size/XS, approved, ok-to-test

#12081 buildkit socket: Add systemd unit
  Makefile
  deploy/iso/minikube-iso/board/coreos/minikube/users
  deploy/iso/minikube-iso/package/buildkit-bin/51-buildkit.preset
  deploy/iso/minikube-iso/package/buildkit-bin/buildkit-bin.mk
  deploy/iso/minikube-iso/package/buildkit-bin/buildkit.conf
  deploy/iso/minikube-iso/package/buildkit-bin/buildkit.service
  deploy/iso/minikube-iso/package/buildkit-bin/buildkit.socket
  deploy/iso/minikube-iso/package/buildkit-bin/buildkitd.toml
  deploy/iso/minikube-iso/package/crio-bin/crio-bin.hash
  deploy/kicbase/Dockerfile
  pkg/drivers/kic/types.go
  pkg/minikube/cruntime/containerd.go
  pkg/minikube/download/iso.go
  site/content/en/docs/commands/start.md
  test/integration/functional_test.go
Labels: cncf-cla: yes, size/L, approved, ok-to-test

#12364 Update Japanese translation
  translations/ja.json
Labels: cncf-cla: yes, size/M, lgtm, needs-ok-to-test

#12641 Update Helm Tiller image to v2.17.0
  pkg/minikube/assets/addons.go
Labels: cncf-cla: yes, size/XS, ok-to-test

#12584 Updates E2E test images registry
  test/integration/testdata/multinodes/multinode-pod-dns-test.yaml
  test/integration/testdata/netcat-deployment-nomaster.yaml
  test/integration/testdata/netcat-deployment.yaml
Labels: cncf-cla: yes, size/XS, ok-to-test

#12626 Enable Hyper-V integration tests
  hack/jenkins/common.ps1
  hack/jenkins/minikube_set_pending.sh
  hack/jenkins/setup_docker_desktop_windows.ps1
  hack/jenkins/windows_cleanup_and_reboot.ps1
  hack/jenkins/windows_cleanup_and_reboot_docker.ps1
  hack/jenkins/windows_cleanup_cron.ps1
  hack/jenkins/windows_integration_test_docker.ps1
  hack/jenkins/windows_integration_test_hyperv.ps1
Labels: cncf-cla: yes, size/L, approved, ok-to-test

#12819 Fix starting on Windows with VMware driver on non `C:` drive
  go.mod
  go.sum
Labels: cncf-cla: yes, size/XS, approved, ok-to-test
