Repository kubernetes/minikube, pull requests merged in 2021-02, with the labels that each got.

#10279 wip:test: make componentHealth test not parallel
  test/integration/functional_test.go
Labels: approved, cncf-cla: yes, do-not-merge/work-in-progress, ok-to-test, size/XS

#10271 Turn on TestPause for containerd
  hack/jenkins/common.sh
  test/integration/helpers_test.go
  test/integration/main_test.go
  test/integration/pause_test.go
Labels: approved, cncf-cla: yes, ok-to-test, size/S

#10320 Migrate tunnel/register logs to structured logging
  pkg/minikube/tunnel/registry.go
Labels: approved, cncf-cla: yes, needs-ok-to-test, size/XS

#10111 Allow setting custom images for addons
  cmd/minikube/cmd/config/enable.go
  cmd/minikube/cmd/config/images.go
  deploy/addons/ambassador/ambassador-operator.yaml.tmpl
  deploy/addons/csi-hostpath-driver/deploy/csi-hostpath-attacher.yaml.tmpl
  deploy/addons/csi-hostpath-driver/deploy/csi-hostpath-plugin.yaml.tmpl
  deploy/addons/csi-hostpath-driver/deploy/csi-hostpath-provisioner.yaml.tmpl
  deploy/addons/csi-hostpath-driver/deploy/csi-hostpath-resizer.yaml.tmpl
  deploy/addons/csi-hostpath-driver/deploy/csi-hostpath-snapshotter.yaml.tmpl
  deploy/addons/dashboard/dashboard-dp.yaml.tmpl
  deploy/addons/efk/elasticsearch-rc.yaml.tmpl
  deploy/addons/efk/fluentd-es-rc.yaml.tmpl
  deploy/addons/efk/kibana-rc.yaml.tmpl
  deploy/addons/freshpod/freshpod-rc.yaml.tmpl
  deploy/addons/gcp-auth/gcp-auth-webhook.yaml.tmpl.tmpl
  deploy/addons/gpu/nvidia-driver-installer.yaml.tmpl
  deploy/addons/gpu/nvidia-gpu-device-plugin.yaml.tmpl
  deploy/addons/gvisor/gvisor-pod.yaml.tmpl
  deploy/addons/helm-tiller/helm-tiller-dp.tmpl
  deploy/addons/ingress-dns/ingress-dns-pod.yaml.tmpl
  deploy/addons/ingress/ingress-dp.yaml.tmpl
  deploy/addons/istio-provisioner/istio-operator.yaml.tmpl
  deploy/addons/kubevirt/pod.yaml.tmpl
  deploy/addons/logviewer/logviewer-dp-and-svc.yaml.tmpl
  deploy/addons/metallb/metallb.yaml.tmpl
  deploy/addons/metrics-server/metrics-server-deployment.yaml.tmpl
  deploy/addons/olm/olm.yaml.tmpl
  deploy/addons/registry-aliases/node-etc-hosts-update.tmpl
  deploy/addons/registry-aliases/patch-coredns-job.tmpl
  deploy/addons/registry-creds/registry-creds-rc.yaml.tmpl
  deploy/addons/registry/registry-proxy.yaml.tmpl
  deploy/addons/registry/registry-rc.yaml.tmpl
  deploy/addons/storage-provisioner-gluster/glusterfs-daemonset.yaml.tmpl
  deploy/addons/storage-provisioner-gluster/heketi-deployment.yaml.tmpl
  deploy/addons/storage-provisioner-gluster/storage-provisioner-glusterfile.yaml.tmpl
  deploy/addons/storage-provisioner/storage-provisioner.yaml.tmpl
  deploy/addons/volumesnapshots/volume-snapshot-controller-deployment.yaml.tmpl
  pkg/addons/addons.go
  pkg/minikube/assets/addons.go
  pkg/minikube/config/config.go
  site/content/en/docs/commands/addons.md
  site/content/en/docs/handbook/addons/custom-images.md
Labels: approved, cncf-cla: yes, ok-to-test, size/XL

#10295 Add support for goimports as well as go fmt
  Makefile
Labels: approved, cncf-cla: yes, size/XS

#10329 Add 15 minute timeout to cleanup and reboot cron
  hack/jenkins/cron/cleanup_and_reboot_Linux.sh
Labels: approved, cncf-cla: yes, ok-to-test, size/L

#10314 Remove old makefile targets for single arch kicbase
  Makefile
Labels: approved, cncf-cla: yes, kind/cleanup, ok-to-test, size/M

#10301 Validate minimum docker version
  pkg/drivers/kic/oci/errors.go
  pkg/minikube/registry/drvs/docker/docker.go
  pkg/minikube/registry/drvs/docker/docker_test.go
  site/content/en/docs/drivers/includes/docker_usage.inc
Labels: cncf-cla: yes, ok-to-test, size/L

#10218 typo
  site/content/en/docs/handbook/pushing.md
Labels: approved, cncf-cla: yes, needs-ok-to-test, size/XS

#10345 Old glusterfs releases were moved to a subdir
  deploy/iso/minikube-iso/package/gluster/gluster.mk
Labels: approved, cncf-cla: yes, size/XS

#10132 CI: add TestScheduledStop on windows in github actions
  .github/workflows/master.yml
  .github/workflows/pr.yml
Labels: approved, cncf-cla: yes, ok-to-test, size/L

#10119 Don't allow profile names that conflict with a multi-node name
  cmd/minikube/cmd/start.go
  pkg/minikube/config/profile.go
  pkg/minikube/machine/cluster_test.go
  pkg/minikube/node/node.go
  test/integration/multinode_test.go
Labels: approved, cncf-cla: yes, ok-to-test, size/L

#9996 Fix profile list when there are multi node clusters
  pkg/minikube/config/profile.go
  test/integration/multinode_test.go
Labels: cncf-cla: yes, ok-to-test, size/M

#10346 docker/podman driver: warn only once for slow running commands
  pkg/drivers/kic/oci/cli_runner.go
  pkg/drivers/kic/oci/cli_runner_test.go
Labels: approved, cncf-cla: yes, ok-to-test, size/M

#10309 Make sure that ssh driver gets an ip address
  cmd/minikube/cmd/start.go
Labels: approved, cncf-cla: yes, ok-to-test, size/S

#10337 Update documentation with instructions for darwin/arm64 platform
  site/content/en/docs/contrib/building/binaries.md
  site/content/en/docs/drivers/docker.md
  site/content/en/docs/drivers/includes/docker_usage.inc
  site/content/en/docs/start/_index.md
Labels: cncf-cla: yes, size/S

#10358 add ilya-zuyev as approver
  OWNERS
Labels: approved, cncf-cla: yes, size/XS

#10375 update klog to v2
  go.mod
  pkg/minikube/audit/audit.go
  pkg/trace/gcp.go
Labels: approved, cncf-cla: yes, size/XS

#10372 fixed snap package manager bug
  pkg/minikube/command/kic_runner.go
Labels: approved, cncf-cla: yes, size/XS

#10374 disable dockerd for container runtime
  pkg/minikube/cruntime/cruntime_test.go
  pkg/minikube/cruntime/docker.go
Labels: approved, cncf-cla: yes, ok-to-test, size/XS

#10369 support ancient versions of docker again (template parsing issue)
  pkg/drivers/kic/oci/network_create.go
  pkg/minikube/registry/drvs/docker/docker.go
Labels: approved, cncf-cla: yes, ok-to-test, size/S

#10356 Wait for the CRI socket to be created properly
  pkg/minikube/node/start.go
Labels: approved, cncf-cla: yes, ok-to-test, size/M

#10396 Add missing reference to --embed-certs in the docs
  site/content/en/docs/handbook/untrusted_certs.md
Labels: approved, cncf-cla: yes, needs-ok-to-test, size/XS

#10354 Provide advice when running windows binary (.exe) inside WSL
  cmd/minikube/cmd/root.go
  pkg/minikube/reason/reason.go
Labels: cncf-cla: yes, ok-to-test, size/S

#10400 Remove s3 and gcs patches from go-getter module
  Makefile
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, size/XS

#10395 Fix configuration of the metallb with empty load balancing IP range
  cmd/minikube/cmd/config/configure.go
  pkg/addons/addons.go
  pkg/addons/config.go
  site/content/en/docs/contrib/addons.en.md
Labels: area/addons, cncf-cla: yes, kind/bug, ok-to-test, size/M

#10385 adding insecure registry support to containerd runtime
  pkg/minikube/cruntime/containerd.go
  pkg/minikube/cruntime/cruntime.go
  pkg/minikube/node/start.go
Labels: approved, cncf-cla: yes, needs-ok-to-test, size/S

#10401 Clean up accumulated golint with missing godoc
  pkg/drivers/ssh/ssh.go
  pkg/minikube/bootstrapper/bsutil/kverify/kverify.go
  pkg/minikube/cni/cni.go
  pkg/minikube/constants/constants.go
  pkg/minikube/kubeconfig/extension.go
  pkg/minikube/machine/ssh.go
  pkg/minikube/sshutil/sshutil.go
  pkg/minikube/style/style.go
Labels: approved, cncf-cla: yes, size/S

#10361 upgrade gcp-auth-webhook image to v0.0.4 for multiarch
  deploy/addons/gcp-auth/gcp-auth-webhook.yaml.tmpl.tmpl
  pkg/minikube/assets/addons.go
Labels: approved, cncf-cla: yes, ok-to-test, size/XS

#10399 Upgrade spinner library
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, ok-to-test, size/XS

#10381 Refactor tmp dir detection to improve testability
  pkg/minikube/command/kic_runner.go
  pkg/minikube/command/kic_runner_test.go
Labels: cncf-cla: yes, size/M

#10411 move StartLimitIntervalSec param from [Service] to [Unit] section
  pkg/minikube/bootstrapper/bsutil/ktmpl/kubelet.go
  pkg/provision/buildroot.go
  pkg/provision/ubuntu.go
Labels: cncf-cla: yes, ok-to-test, size/S

#10423 Fix TestPreload on containerd/crio
  test/integration/preload_test.go
Labels: approved, cncf-cla: yes, ok-to-test, size/S

#10419 Correct the filename for the crio apt repository
  deploy/kicbase/Dockerfile
Labels: approved, cncf-cla: yes, size/XS

#10415 Update libmachine module to machine-drivers@master
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, ok-to-test, size/S

#10417 Upgrade Docker, from 20.10.2 to 20.10.3
  deploy/iso/minikube-iso/package/docker-bin/docker-bin.hash
  deploy/iso/minikube-iso/package/docker-bin/docker-bin.mk
Labels: approved, cncf-cla: yes, size/XS

#10421 Remove now unused isoPath link parameter
  Makefile
Labels: approved, cncf-cla: yes, size/XS

#10366 Implement minikube image load command
  cmd/minikube/cmd/cache.go
  cmd/minikube/cmd/image.go
  cmd/minikube/cmd/root.go
  pkg/minikube/machine/cache_images.go
  pkg/minikube/node/cache.go
  pkg/minikube/node/start.go
  pkg/minikube/reason/reason.go
  site/content/en/docs/commands/cache.md
  site/content/en/docs/commands/image.md
  test/integration/functional_test.go
Labels: approved, cncf-cla: yes, ok-to-test, size/L

#10422 Remove duplicate binaries from build internals
  hack/jenkins/release_build_and_upload.sh
Labels: approved, cncf-cla: yes, size/XS

#10428 Fix TestNetworkPlugins/group/auto/KubeletFlags on containerd/crio
  test/integration/net_test.go
Labels: approved, cncf-cla: yes, ok-to-test, size/M

#10332 Add 5 minute timeout to deleting a profile
  cmd/minikube/cmd/delete.go
  cmd/minikube/cmd/node_delete.go
  cmd/minikube/cmd/start.go
  pkg/drivers/kic/kic.go
  pkg/drivers/kic/oci/oci.go
  pkg/drivers/kic/oci/volumes.go
Labels: approved, cncf-cla: yes, ok-to-test, size/M

#10341 (docs) update install instructions for MacOS
  site/content/en/docs/start/_index.md
Labels: cncf-cla: yes, needs-ok-to-test, size/XS

#10298 ssh: support default key path for built-in ssh
  pkg/minikube/sshutil/sshutil.go
Labels: approved, cncf-cla: yes, size/XS

#10347 Changed x86 to amd64 in installation guide to reflect actual architecture name
  site/content/en/docs/start/_index.md
Labels: approved, cncf-cla: yes, needs-ok-to-test, size/XS

#10412 remove crio restart hack
  cmd/minikube/cmd/start.go
Labels: approved, cncf-cla: yes, ok-to-test, size/S

#10380 Add -l/--light option for profile list command.
  cmd/minikube/cmd/config/profile_list.go
  site/content/en/docs/commands/profile.md
  test/integration/functional_test.go
Labels: cncf-cla: yes, ok-to-test, size/L

#10442 add NodeReadyKey to the AllComponents map for waiting for all components
  pkg/minikube/bootstrapper/bsutil/kverify/kverify.go
Labels: approved, cncf-cla: yes, needs-ok-to-test, size/XS

#10435 Explicitly remove podman volume and network
  cmd/minikube/cmd/delete.go
  pkg/drivers/kic/oci/errors.go
  pkg/drivers/kic/oci/volumes.go
Labels: approved, cncf-cla: yes, ok-to-test, size/M

#10433 Add image repository respected for calico
  pkg/minikube/bootstrapper/images/images.go
  pkg/minikube/cni/calico.go
Labels: approved, cncf-cla: yes, ok-to-test, size/M

#10450 skip LoadImage test on darwin/github actions
  test/integration/functional_test.go
Labels: approved, cncf-cla: yes, size/XS

#10293 ssh: validate the ssh-key parameter if given
  pkg/drivers/ssh/ssh.go
Labels: approved, cncf-cla: yes, size/S

#10452 Disable all drivers except "docker" and "ssh" on darwin/arm64
  cmd/drivers/hyperkit/main.go
  cmd/minikube/cmd/start.go
  pkg/minikube/driver/driver_darwin.go
  translations/de.json
  translations/es.json
  translations/fr.json
  translations/ja.json
  translations/ko.json
  translations/pl.json
  translations/strings.txt
  translations/zh-CN.json
Labels: approved, arch/arm64, kind/bug, ok-to-test, os/macos

#10457 [Unit Test] Fix TestCheckDockerVersion Assertion
  pkg/minikube/registry/drvs/docker/docker_test.go
Labels: area/testing, cncf-cla: yes, needs-ok-to-test, size/XS

#10388 Add condition to check --cpus count with available cpu count
  cmd/minikube/cmd/start.go
Labels: approved, cncf-cla: yes, ok-to-test, size/S

#10463 Fix TestErrorJSONOutput test
  test/integration/json_output_test.go
Labels: approved, cncf-cla: yes, ok-to-test, size/XS

#10472 The checksum of the podman source tarball changed
  deploy/iso/minikube-iso/package/podman/podman.hash
Labels: approved, cncf-cla: yes, size/XS

#10488 Reduce time limit on TestStartStop to fix occasional KVM_containerd timeout
  test/integration/start_stop_delete_test.go
Labels: approved, cncf-cla: yes, ok-to-test, size/XS

#10491 Set --interactive=false flag on skaffold test
  test/integration/skaffold_test.go
Labels: approved, cncf-cla: yes, ok-to-test, size/XS

#10424 add new extra component to --wait=all to validate a healthy cluster
  pkg/minikube/bootstrapper/bsutil/kverify/kverify.go
  pkg/minikube/bootstrapper/bsutil/kverify/pod_ready.go
  pkg/minikube/bootstrapper/kubeadm/kubeadm.go
  test/integration/functional_test.go
Labels: approved, cncf-cla: yes, ok-to-test, size/L

#10466 docs: follow convention for dynamic values
  site/content/en/docs/handbook/accessing.md
Labels: approved, cncf-cla: yes, needs-ok-to-test, size/XS

#10462 UI: do not send image repo info to stderr
  pkg/minikube/assets/addons.go
Labels: approved, cncf-cla: yes, ok-to-test, size/XS

#10476 Upgrade crio to 1.20.0
  deploy/iso/minikube-iso/package/crio-bin/crio-bin.hash
  deploy/iso/minikube-iso/package/crio-bin/crio-bin.mk
  deploy/iso/minikube-iso/package/crio-bin/crio.conf
  deploy/iso/minikube-iso/package/crio-bin/crio.conf.default
Labels: approved, cncf-cla: yes, size/M

#10233 Add google group link to triaging doc
  site/content/en/docs/contrib/triage.md
Labels: cncf-cla: yes, needs-ok-to-test, size/XS

#10480 Make sure to use CRI for docker if configured
  pkg/minikube/cruntime/cruntime.go
  pkg/minikube/cruntime/docker.go
  pkg/minikube/node/start.go
Labels: approved, cncf-cla: yes, ok-to-test, size/M

#10503 Makefile: fix buildx builder name
  Makefile
Labels: approved, cncf-cla: yes, size/XS

#10500 changing step to infof
  pkg/minikube/assets/addons.go
Labels: approved, cncf-cla: yes, ok-to-test, size/XS

#10502 Use golang:1.16.0 docker builder image
  Makefile
Labels: approved, cncf-cla: yes, size/XS

#10454 Change prepareVolume func to add container name for preload side car
  pkg/drivers/kic/oci/oci.go
  pkg/drivers/kic/oci/volumes.go
Labels: cncf-cla: yes, kind/bug, needs-ok-to-test, size/XS

#10507 Stop using --memory-swap if it is not available
  pkg/drivers/kic/oci/oci.go
Labels: approved, cncf-cla: yes, size/XS

#10067 MEP: Standard Linux Distribution ("distro")
  enhancements/proposed/20201230-standard-distro/standard-distro.md
Labels: approved, cncf-cla: yes, size/M

#9577 Turn on ingress addon on linux baremetal
  pkg/addons/addons.go
  pkg/minikube/bootstrapper/bsutil/kverify/default_sa.go
  pkg/minikube/machine/start.go
  test/integration/addons_test.go
Labels: approved, cncf-cla: yes, ok-to-test, size/M

#10468 Make sure to show debian warning also for cgroup 2
  pkg/drivers/kic/oci/cgroups_linux.go
  pkg/drivers/kic/oci/cgroups_other.go
  pkg/drivers/kic/oci/oci.go
Labels: approved, cncf-cla: yes, size/M

#10509 Updated dashboard URL detection logic for DashboardCmd test
  test/integration/functional_test.go
  test/integration/util_test.go
Labels: approved, cncf-cla: yes, size/M

#10408 populate kic.txt properly in kicbase
  .github/workflows/kic_image.yml
  deploy/kicbase/Dockerfile
  hack/jenkins/kicbase_auto_build.sh
  pkg/drivers/kic/types.go
  site/content/en/docs/commands/start.md
Labels: approved, cncf-cla: yes, ok-to-build-image, ok-to-test, size/L

#10512 cgroup v2: skip setting --memory limits when not configurable.
  pkg/drivers/kic/oci/oci.go
Labels: approved, cncf-cla: yes, ok-to-test, size/S

#10418 Update kicbase base image and sync with kind
  deploy/kicbase/Dockerfile
  deploy/kicbase/entrypoint
  pkg/drivers/kic/types.go
  site/content/en/docs/commands/start.md
Labels: approved, cncf-cla: yes, ok-to-test, size/M

#10350 Add audit logs to minikube logs output
  pkg/minikube/audit/audit.go
  pkg/minikube/audit/entry.go
  pkg/minikube/audit/logFile.go
  pkg/minikube/audit/logFile_test.go
  pkg/minikube/audit/report.go
  pkg/minikube/audit/report_test.go
  pkg/minikube/audit/row.go
  pkg/minikube/audit/row_test.go
  pkg/minikube/logs/logs.go
  test/integration/functional_test.go
  test/integration/version_upgrade_test.go
Labels: approved, cncf-cla: yes, ok-to-test, size/L

#10518 bump gopogh version v0.6.0
  .github/workflows/iso.yml
  .github/workflows/master.yml
  .github/workflows/pr.yml
  hack/jenkins/common.sh
  hack/jenkins/windows_integration_test_docker.ps1
  hack/jenkins/windows_integration_test_hyperv.ps1
  hack/jenkins/windows_integration_test_virtualbox.ps1
Labels: approved, cncf-cla: yes, ok-to-test, size/L

#10510 docker: Loosen docker_engine pipe error regexp
  pkg/minikube/registry/drvs/docker/docker.go
Labels: approved, cncf-cla: yes, size/XS

#10493 Improved insecure registry validation function
  cmd/minikube/cmd/start.go
Labels: approved, cncf-cla: yes, needs-ok-to-test, size/M

#10439 prevent oci try to create overlapping network
  pkg/drivers/kic/oci/network_create.go
  pkg/drivers/kvm/network.go
  pkg/minikube/cluster/ip.go
  pkg/network/network.go
Labels: cncf-cla: yes, ok-to-test, size/L

#10398 Allow dependabot to check go dependencies
  .github/dependabot.yml
Labels: cncf-cla: yes, needs-ok-to-test, size/XS

#10479 improve kvm network delete/cleanup
  pkg/drivers/kvm/network.go
Labels: approved, cncf-cla: yes, needs-ok-to-test, size/M

#10527 add sha to all addons
  pkg/minikube/assets/addons.go
Labels: approved, cncf-cla: yes, ok-to-test, size/M

#10464 Add integration tests to verify .deb installation
  .github/workflows/pr_verified.yaml
  Makefile
  test/integration/pkg_install_test.go
Labels: approved, cncf-cla: yes, ok-to-test, pr_verified, size/L

#10528 fix crio by hardcoding mountopt
  deploy/kicbase/Dockerfile
  pkg/drivers/kic/types.go
  site/content/en/docs/commands/start.md
Labels: approved, cncf-cla: yes, ok-to-test, size/S

#10537 [BUILD ERROR] Fix build error of go mod. Update opentelemetry-operations-go version and non-existing packages
  go.mod
  go.sum
  pkg/trace/gcp.go
Labels: cncf-cla: yes, kind/bug, needs-ok-to-test, size/M

#10535 Fix minikube kubectl context switching
  cmd/minikube/cmd/kubectl.go
Labels: approved, cncf-cla: yes, needs-ok-to-test, size/XS

#10531 bump oldest kubernetes version to v1.14.0
  go.sum
  pkg/minikube/constants/constants.go
  site/content/en/docs/commands/start.md
Labels: approved, cncf-cla: yes, ok-to-test, size/S

#10426 kic: Make sure to add crun for running on cgroups v2
  deploy/kicbase/Dockerfile
  pkg/drivers/kic/types.go
  site/content/en/docs/commands/start.md
Labels: approved, cncf-cla: yes, ok-to-test, size/XS

#10477 Change from crio-1.19 to crio-1.20 in kicbase
  deploy/kicbase/Dockerfile
  pkg/drivers/kic/types.go
  site/content/en/docs/commands/start.md
Labels: approved, cncf-cla: yes, ok-to-test, size/S

#10550 Upgrade go version from 1.15.5 to 1.15.8
  .github/workflows/build.yml
  .github/workflows/iso.yml
  .github/workflows/master.yml
  .github/workflows/pr.yml
  .github/workflows/pr_verified.yaml
  Makefile
  hack/jenkins/common.sh
Labels: approved, cncf-cla: yes, size/M

#10551 Require go1.16 for building site with hugo
  Makefile
Labels: approved, cncf-cla: yes, size/XS

#10556 The github label wasn't renamed like the driver
  site/content/en/docs/drivers/ssh.md
Labels: approved, cncf-cla: yes, size/XS

#10546 downgrade default kuberentes version back to v1.20.2
  pkg/minikube/constants/constants.go
  site/content/en/docs/commands/start.md
Labels: approved, cncf-cla: yes, ok-to-test, size/XS

#10542 test: use crictl inspecti for verify images in test
  test/integration/functional_test.go
Labels: approved, cncf-cla: yes, ok-to-test, size/S

#10553 Rsrc Insufficient System memory issue
  cmd/minikube/cmd/start.go
Labels: approved, cncf-cla: yes, needs-ok-to-test, size/XS

#10540 Introduce alias native for none driver
  pkg/minikube/driver/driver.go
  pkg/minikube/registry/drvs/none/none.go
Labels: approved, cncf-cla: yes, ok-to-test, size/XS

#10548 disable minikube-scheduled-stop.service until a user schedules a stop
  deploy/iso/minikube-iso/package/scheduled-stop/scheduled-stop.mk
  deploy/kicbase/Dockerfile
  pkg/drivers/kic/types.go
  pkg/minikube/schedule/daemonize_windows.go
  site/content/en/docs/commands/start.md
Labels: cncf-cla: yes, ok-to-test, size/S

#10569 hack update gh releases: replace deprecated semver.Max with semver.Compare
  hack/update/github.go
Labels: cncf-cla: yes, needs-ok-to-test, size/XS

#10567 fix go.sum that got out-of-sync with go.mod after packages' version bump
  go.sum
Labels: cncf-cla: yes, needs-ok-to-test, size/M

#10348 Buildroot 2020.02.10
  Makefile
  deploy/iso/minikube-iso/board/coreos/minikube/linux_defconfig
  deploy/iso/minikube-iso/configs/minikube_defconfig
Labels: approved, cncf-cla: yes, size/M

#10582 drop support for github packages for kicbase
  Makefile
  go.sum
  hack/jenkins/kicbase_auto_build.sh
  pkg/drivers/kic/types.go
Labels: approved, cncf-cla: yes, size/S

#10321 Move DeletePossibleKicLeftOver function to delete pkg
  cmd/minikube/cmd/delete.go
  cmd/minikube/cmd/node_delete.go
  pkg/minikube/delete/delete.go
Labels: approved, cncf-cla: yes, needs-ok-to-test, size/L

#10554 Don't select Discouraged or Obsolete by default
  cmd/minikube/cmd/start.go
  pkg/minikube/driver/driver.go
  pkg/minikube/driver/driver_test.go
  pkg/minikube/registry/drvs/docker/docker.go
  pkg/minikube/registry/drvs/hyperkit/hyperkit.go
  pkg/minikube/registry/drvs/hyperv/hyperv.go
  pkg/minikube/registry/drvs/kvm2/kvm2.go
  pkg/minikube/registry/drvs/none/none.go
  pkg/minikube/registry/drvs/parallels/parallels.go
  pkg/minikube/registry/drvs/podman/podman.go
  pkg/minikube/registry/drvs/ssh/ssh.go
  pkg/minikube/registry/drvs/virtualbox/virtualbox.go
  pkg/minikube/registry/drvs/vmware/vmware.go
  pkg/minikube/registry/drvs/vmwarefusion/vmwarefusion.go
  pkg/minikube/registry/global.go
  pkg/minikube/registry/global_test.go
  pkg/minikube/registry/registry.go
Labels: approved, cncf-cla: yes, ok-to-test, size/M

#10586 Fixed audit.json error when `delete --purge` ran
  go.sum
  pkg/minikube/audit/audit.go
  pkg/minikube/audit/audit_test.go
Labels: approved, cncf-cla: yes, ok-to-test, pr_verified, size/M

#10583 update kindnet version
  pkg/minikube/bootstrapper/images/images.go
  pkg/minikube/download/preload.go
Labels: approved, cncf-cla: yes, ok-to-test, size/XS

#10465 Add last start logs to minikube logs output
  cmd/minikube/main.go
  pkg/minikube/localpath/localpath.go
  pkg/minikube/logs/logs.go
  test/integration/functional_test.go
Labels: approved, cncf-cla: yes, ok-to-test, pr_verified, size/M

#10159 Update docs VMware Fusion mount location.
  site/content/en/docs/handbook/mount.md
Labels: cncf-cla: yes, needs-ok-to-test, size/XS

#10585 Bump ISO version to 1.18.0-beta.0
  Makefile
  site/content/en/docs/commands/start.md
Labels: approved, cncf-cla: yes, ok-to-test, pr_verified, size/XS

#10572 Add support for official kicbase releases in script
  hack/jenkins/installers/check_install_gh.sh
  hack/jenkins/kicbase_auto_build.sh
Labels: approved, cncf-cla: yes, size/L

#10427 auto-pause addon: automatically pause Kubernetes when not in use
  .gitignore
  Makefile
  cmd/auto-pause/auto-pause.go
  cmd/minikube/cmd/status.go
  deploy/addons/auto-pause/auto-pause.service
  deploy/addons/auto-pause/auto-pause.yaml.tmpl
  deploy/addons/auto-pause/haproxy.cfg
  deploy/addons/auto-pause/unpause.lua
  deploy/kicbase/Dockerfile
  pkg/addons/addons.go
  pkg/addons/config.go
  pkg/drivers/kic/kic.go
  pkg/drivers/kic/types.go
  pkg/minikube/assets/addons.go
  pkg/minikube/constants/constants.go
  pkg/minikube/driver/endpoint.go
  pkg/minikube/sysinit/openrc.go
  pkg/minikube/sysinit/sysinit.go
  pkg/minikube/sysinit/systemd.go
  site/content/en/docs/commands/start.md
Labels: approved, cncf-cla: yes, ok-to-test, pr_verified, size/L

#10606 Check for args length to prevent out of bounds panic
  cmd/minikube/main.go
  pkg/minikube/audit/audit.go
  pkg/minikube/audit/audit_test.go
  test/integration/main_test.go
Labels: approved, cncf-cla: yes, size/S

#10615 Migrate kubectl logs to structured logging
  cmd/minikube/cmd/kubectl.go
Labels: cncf-cla: yes, needs-ok-to-test, size/XS

#10621 generate-docs on kicbase release
  hack/jenkins/kicbase_auto_build.sh
Labels: approved, cncf-cla: yes, size/XS

#10420 Make sure to update the package metadata
  Makefile
  installers/linux/deb/minikube_deb_template/DEBIAN/control
  installers/linux/rpm/minikube_rpm_template/minikube.spec
Labels: approved, cncf-cla: yes, size/XS

#10630 Release 1.18.0-beta.0
  CHANGELOG.md
  Makefile
Labels: approved, cncf-cla: yes, ok-to-test, pr_verified, size/M

#10638 test spam: add cgroup warnning to whitelist
  test/integration/error_spam_test.go
Labels: approved, cncf-cla: yes, ok-to-test, size/XS

#10641 Add README for mkcmp
  cmd/performance/mkcmp/cmd/README.md
Labels: approved, cncf-cla: yes, size/S
