Repository kubernetes/minikube, pull requests merged in 2022-11, with the labels that each got.

#15241 revise gcp-auth addon docs
  site/content/en/docs/handbook/addons/gcp-auth.md
Labels: cncf-cla: yes, size/S, approved, needs-ok-to-test

#15261 Site: Update ISO docs, add MacOS and include recent changes to build process
  site/content/en/docs/contrib/building/iso.md
Labels: cncf-cla: yes, size/M, approved, needs-ok-to-test

#15264 Site: reformat documentation sidebar
  site/assets/scss/_styles_project.scss
  site/layouts/partials/hooks/head-end.html
  site/layouts/partials/sidebar-tree.html
Labels: cncf-cla: yes, size/S, needs-ok-to-test

#15279 fix grammar and spelling in messages
  cmd/minikube/cmd/service.go
  cmd/minikube/cmd/start.go
  pkg/drivers/kic/oci/oci.go
  pkg/minikube/reason/known_issues.go
  translations/de.json
  translations/es.json
  translations/fr.json
  translations/ja.json
  translations/ko.json
  translations/pl.json
  translations/ru.json
  translations/strings.txt
  translations/zh-CN.json
Labels: cncf-cla: yes, size/M, approved, needs-ok-to-test

#15281 Prevent enabling `efk` addon due to containing Log4j CVE
  cmd/minikube/cmd/config/enable.go
  cmd/minikube/cmd/config/flags.go
  pkg/addons/addons.go
  translations/de.json
  translations/es.json
  translations/fr.json
  translations/ja.json
  translations/ko.json
  translations/pl.json
  translations/ru.json
  translations/strings.txt
  translations/zh-CN.json
Labels: cncf-cla: yes, size/L, approved

#15266 Auto select network on QEMU
  cmd/minikube/cmd/start_flags.go
  pkg/minikube/detect/detect.go
  pkg/minikube/reason/reason.go
  site/content/en/docs/contrib/errorcodes.en.md
  site/content/en/docs/drivers/qemu.md
  translations/de.json
  translations/es.json
  translations/fr.json
  translations/ja.json
  translations/ko.json
  translations/pl.json
  translations/ru.json
  translations/strings.txt
  translations/zh-CN.json
Labels: cncf-cla: yes, size/L, approved

#15256 Ensure downloading preload images when size is zero
  pkg/minikube/download/download_test.go
  pkg/minikube/download/preload.go
Labels: cncf-cla: yes, size/M, approved, ok-to-test

#15286 Release v1.28.0
  CHANGELOG.md
  Makefile
Labels: cncf-cla: yes, size/M, approved, ok-to-test

#15288 Pin cloud-spanner-emulator/emulator image
  pkg/minikube/assets/addons.go
Labels: cncf-cla: yes, size/XS, approved

#15303 Fix typo and titles for better readability
  site/content/en/docs/drivers/qemu.md
Labels: cncf-cla: yes, size/S, approved, needs-ok-to-test

#15299 Fixed typo uninstll on qemu workaround for /var/db/dhcpd_leases errors
  site/content/en/docs/drivers/qemu.md
Labels: cncf-cla: yes, size/XS, approved

#15317 Add additional memory overhead for VirtualBox when `--memory=max`
  cmd/minikube/cmd/start.go
  cmd/minikube/cmd/start_flags.go
Labels: cncf-cla: yes, size/S, approved

#15293 CI: Fix setting multiline output
  .github/workflows/docs.yml
  .github/workflows/leaderboard.yml
  .github/workflows/update-golang-version.yml
  .github/workflows/update-golint-version.yml
  .github/workflows/update-gopogh-version.yml
  .github/workflows/update-gotestsum-version.yml
  .github/workflows/update-k8s-versions.yml
  .github/workflows/update-kubeadm-constants.yml
  .github/workflows/yearly-leaderboard.yml
Labels: cncf-cla: yes, size/M, approved

#15310 Update Kubevirt addon image
  pkg/minikube/assets/addons.go
Labels: cncf-cla: yes, size/XS, approved, ok-to-test

#15331 Update auto-pause addon image
  Makefile
  pkg/minikube/assets/addons.go
Labels: cncf-cla: yes, size/XS, approved, ok-to-test

#15337 fix the spanner addon
  deploy/addons/cloud-spanner/deployment.yaml
  pkg/minikube/assets/addons.go
Labels: cncf-cla: yes, size/XS, approved, ok-to-test

#15343 Add `npm install` to fix local site build
  Makefile
Labels: cncf-cla: yes, size/XS, approved

#15344 site: update the links for hyperv documenation
  deploy/iso/minikube-iso/arch/x86_64/package/hyperv-daemons/hv_fcopy_daemon.service
  deploy/iso/minikube-iso/arch/x86_64/package/hyperv-daemons/hv_kvp_daemon.service
  deploy/iso/minikube-iso/arch/x86_64/package/hyperv-daemons/hv_vss_daemon.service
Labels: cncf-cla: yes, size/XS, approved, needs-ok-to-test

#15347 site: Tab deploying section on Getting Started
  site/content/en/docs/start/_index.md
Labels: cncf-cla: yes, size/XS, approved

#15341 ISO: Update Docker from 20.10.20 to 20.10.21
  Makefile
  deploy/iso/minikube-iso/arch/aarch64/package/containerd-bin-aarch64/containerd-bin.hash
  deploy/iso/minikube-iso/arch/aarch64/package/containerd-bin-aarch64/containerd-bin.mk
  deploy/iso/minikube-iso/arch/aarch64/package/docker-bin-aarch64/docker-bin.hash
  deploy/iso/minikube-iso/arch/aarch64/package/docker-bin-aarch64/docker-bin.mk
  deploy/iso/minikube-iso/arch/x86_64/package/containerd-bin/containerd-bin.hash
  deploy/iso/minikube-iso/arch/x86_64/package/containerd-bin/containerd-bin.mk
  deploy/iso/minikube-iso/arch/x86_64/package/docker-bin/docker-bin.hash
  deploy/iso/minikube-iso/arch/x86_64/package/docker-bin/docker-bin.mk
  pkg/minikube/download/iso.go
Labels: cncf-cla: yes, size/S, approved, ok-to-test

#15336 fix kubelet localStorageCapacityIsolation option
  cmd/minikube/cmd/start_flags.go
  pkg/minikube/bootstrapper/bsutil/ktmpl/v1beta3.go
  pkg/minikube/bootstrapper/bsutil/kubeadm.go
  pkg/minikube/bootstrapper/bsutil/kubeadm_test.go
  pkg/minikube/bootstrapper/bsutil/kubelet.go
Labels: cncf-cla: yes, size/M, approved, ok-to-test

#15242 Upgrade Cilium to version 1.12.3
  pkg/minikube/cni/cilium.go
Labels: cncf-cla: yes, size/M, ok-to-test

#15363 Update GUI README
  gui/README.md
  site/content/en/docs/tutorials/setup_minikube_gui.md
Labels: cncf-cla: yes, size/S, approved

#15364 site: Add ingress example to getting started
  site/content/en/docs/start/_index.md
Labels: cncf-cla: yes, size/M, approved

#15370 Move license command to other section in help
  cmd/minikube/cmd/root.go
Labels: cncf-cla: yes, size/XS, approved

#15349 site: Fix command name, missing letter in table header and deduplicate
  site/content/en/docs/handbook/accessing.md
Labels: cncf-cla: yes, size/XS, approved, needs-ok-to-test

#15308 test: use `T.Setenv` to set env vars in tests
  cmd/minikube/cmd/config/set_test.go
  cmd/minikube/cmd/delete_test.go
  cmd/minikube/cmd/docker-env_test.go
  cmd/minikube/cmd/start_test.go
  pkg/addons/addons_test.go
  pkg/drivers/kic/oci/oci_test.go
  pkg/minikube/config/profile_test.go
  pkg/minikube/kubeconfig/kubeconfig_test.go
  pkg/minikube/localpath/localpath_test.go
  pkg/minikube/machine/cache_binaries_test.go
  pkg/minikube/machine/client_test.go
  pkg/minikube/out/out_test.go
  pkg/minikube/proxy/proxy_test.go
  pkg/minikube/service/service_test.go
  pkg/minikube/shell/shell_test.go
  pkg/minikube/storageclass/storageclass_test.go
  pkg/util/utils_test.go
  test/integration/skaffold_test.go
Labels: cncf-cla: yes, size/L, ok-to-test, do-not-merge/failing-test

#15235 Added version.json and CHANGELOG to kicbase image and ISO. Added version validation to start.go.
  .gitignore
  Makefile
  cmd/minikube/cmd/start.go
  deploy/iso/minikube-iso/Dockerfile
  deploy/kicbase/Dockerfile
  hack/jenkins/build_changelog.sh
  hack/jenkins/build_iso.sh
  hack/jenkins/installers/check_install_gh.sh
  hack/jenkins/kicbase_auto_build.sh
  pkg/drivers/kic/types.go
  pkg/minikube/download/iso.go
  site/content/en/docs/commands/start.md
  translations/de.json
  translations/es.json
  translations/fr.json
  translations/ja.json
  translations/ko.json
  translations/pl.json
  translations/ru.json
  translations/strings.txt
  translations/zh-CN.json
Labels: cncf-cla: yes, size/L, approved, ok-to-test

#15225 Stop applying the beta.kubernetes.io/os and arch
  deploy/addons/dashboard/dashboard-dp.yaml.tmpl
  deploy/addons/metallb/metallb.yaml.tmpl
  site/content/en/docs/tutorials/includes/kube-flannel.yaml
Labels: cncf-cla: yes, size/S, approved, ok-to-test

#15376 tests: Remove license dir after test
  test/integration/functional_test.go
Labels: cncf-cla: yes, size/XS, approved

#15272 Revert setting snapshotter to fuse-overlayfs
  deploy/kicbase/entrypoint
  pkg/drivers/kic/types.go
  site/content/en/docs/commands/start.md
Labels: cncf-cla: yes, size/S, approved, ok-to-test

#15383 Fix french translation
  translations/fr.json
Labels: cncf-cla: yes, size/XS, needs-ok-to-test

#15366 Update Japanese translation
  translations/ja.json
Labels: cncf-cla: yes, size/S, lgtm

#15390 Create kubeadm constants entry for all versions
  hack/update/kubeadm_constants/update_kubeadm_constants.go
  pkg/minikube/bootstrapper/images/images.go
  pkg/minikube/bootstrapper/images/kubeadm_test.go
  pkg/minikube/constants/constants_kubeadm_images.go
Labels: cncf-cla: yes, size/XXL, approved, ok-to-test

#15245 Use setup-go action to cache dependencies
  .github/workflows/build.yml
  .github/workflows/docs.yml
  .github/workflows/functional_verified.yml
  .github/workflows/leaderboard.yml
  .github/workflows/master.yml
  .github/workflows/pr.yml
  .github/workflows/sync-minikube.yml
  .github/workflows/time-to-k8s-public-chart.yml
  .github/workflows/time-to-k8s.yml
  .github/workflows/translations.yml
  .github/workflows/update-golang-version.yml
  .github/workflows/update-golint-version.yml
  .github/workflows/update-gopogh-version.yml
  .github/workflows/update-gotestsum-version.yml
  .github/workflows/update-k8s-versions.yml
  .github/workflows/update-kubeadm-constants.yml
  .github/workflows/yearly-leaderboard.yml
Labels: cncf-cla: yes, size/M, ok-to-test

#15404 update the links for go documenation
  translations/es.json
  translations/zh-CN.json
Labels: cncf-cla: yes, size/S, needs-ok-to-test

#15427 site: Add QEMU to driver list
  site/content/en/docs/start/_index.md
Labels: cncf-cla: yes, size/XS, approved

#15405 Update Windows installer script to create system-wide shortcut
  installers/windows/minikube.nsi
Labels: cncf-cla: yes, size/XS, approved, ok-to-test

#15411 Addons: Bump metrics-server to v0.6.2
  pkg/minikube/assets/addons.go
Labels: cncf-cla: yes, size/XS, approved, ok-to-test

#15401 Upgrade Headlamp version to 0.14.0
  pkg/minikube/assets/addons.go
Labels: cncf-cla: yes, size/XS, ok-to-test

#15439 site: Update triage time
  site/content/en/docs/contrib/triage.md
Labels: cncf-cla: yes, size/XS, approved
