Repository kubernetes/minikube, pull requests merged in 2022-09, with the labels that each got.

#14892 GitHub Workflows security hardening
  .github/workflows/twitter-bot.yml
Labels: cncf-cla: yes, size/XS, needs-ok-to-test

#14916 Add more update check params
  pkg/minikube/notify/notify.go
Labels: cncf-cla: yes, size/S, approved

#14904 Update kicbase base image
  deploy/kicbase/Dockerfile
  pkg/drivers/kic/types.go
  site/content/en/docs/commands/start.md
Labels: cncf-cla: yes, size/XS, approved, ok-to-test

#14762 Document qemu start and default commands
  site/content/en/docs/drivers/qemu.md
Labels: cncf-cla: yes, size/XS, approved

#14864 Fix wrong use of loop variable in parallel test
  pkg/minikube/bootstrapper/bsutil/versions_test.go
Labels: cncf-cla: yes, size/S, approved, needs-ok-to-test

#14918 Update k8s imports to v0.25.0
  go.mod
  go.sum
Labels: cncf-cla: yes, size/L, approved, ok-to-test

#14919 fix defaultSSHUser and string formats
  pkg/drivers/qemu/qemu.go
Labels: cncf-cla: yes, size/XS, approved

#14103 readability improvements for addons.go
  pkg/minikube/assets/addons.go
Labels: cncf-cla: yes, size/M, approved, lifecycle/rotten

#14765 Site: add documentation for flag: 'qemu-firmware-path'
  site/content/en/docs/drivers/qemu.md
Labels: cncf-cla: yes, size/XS

#14934 Removed unused config value
  pkg/minikube/bootstrapper/bsutil/kubeadm.go
Labels: cncf-cla: yes, size/XS, approved

#14944 site: Update minikube GUI path
  site/content/en/docs/tutorials/setup_minikube_gui.md
Labels: cncf-cla: yes, size/XS, approved

#14660 Add and fix err checks in bsutil and sysinit packages
  pkg/minikube/bootstrapper/bsutil/binaries.go
  pkg/minikube/sysinit/openrc.go
Labels: cncf-cla: yes, size/S

#14935 ISO: Update Docker from 20.10.17 to 20.10.18
  Makefile
  deploy/addons/auto-pause/Dockerfile
  deploy/iso/minikube-iso/arch/aarch64/package/containerd-bin-aarch64/containerd-bin.hash
  deploy/iso/minikube-iso/arch/aarch64/package/containerd-bin-aarch64/containerd-bin.mk
  deploy/iso/minikube-iso/arch/aarch64/package/docker-bin-aarch64/docker-bin.hash
  deploy/iso/minikube-iso/arch/aarch64/package/docker-bin-aarch64/docker-bin.mk
  deploy/iso/minikube-iso/arch/x86_64/package/containerd-bin/containerd-bin.hash
  deploy/iso/minikube-iso/arch/x86_64/package/containerd-bin/containerd-bin.mk
  deploy/iso/minikube-iso/arch/x86_64/package/docker-bin/docker-bin.hash
  deploy/iso/minikube-iso/arch/x86_64/package/docker-bin/docker-bin.mk
  deploy/iso/minikube-iso/go.hash
  deploy/iso/minikube-iso/package/runc-master/runc-master.hash
  deploy/iso/minikube-iso/package/runc-master/runc-master.mk
  hack/jenkins/build_iso.sh
  pkg/minikube/download/iso.go
  site/content/en/docs/commands/start.md
Labels: cncf-cla: yes, size/M, approved, ok-to-test

#14947 CI: fix Golang install on M1 Macs
  hack/jenkins/installers/check_install_golang.sh
Labels: cncf-cla: yes, size/XS, approved

#14950 Fix QEMU delete errors
  pkg/drivers/qemu/qemu.go
Labels: cncf-cla: yes, size/M, approved

#14903 Skip metallb PodSecurityPolicy object for kubernetes 1.25+
  deploy/addons/metallb/metallb.yaml.tmpl
  pkg/minikube/assets/addons.go
Labels: cncf-cla: yes, size/M, ok-to-test

#14955 release v.1.27.0
  CHANGELOG.md
  Makefile
Labels: cncf-cla: yes, size/M, ok-to-test

#14890 enable `socket_vmnet` network driver for qemu Mac M1 ARM64
  cmd/minikube/cmd/start_flags.go
  pkg/drivers/qemu/qemu.go
  pkg/minikube/config/types.go
  pkg/minikube/registry/drvs/qemu2/qemu2.go
  site/content/en/docs/commands/start.md
Labels: cncf-cla: yes, size/M, ok-to-test

#15019 site: Update deployment image
  site/content/en/docs/start/_index.md
Labels: cncf-cla: yes, size/XS, approved

#15029 site: Fix generate-docs on arm64
  pkg/generate/rewrite.go
  site/content/en/docs/commands/start.md
Labels: cncf-cla: yes, size/XS, approved

#15022 Fix french translation
  translations/fr.json
Labels: cncf-cla: yes, size/S, needs-ok-to-test

#15001 Update Korean translation.
  translations/ko.json
Labels: cncf-cla: yes, size/S, needs-ok-to-test

#15012 fix: typo in known issue powershell command tip
  pkg/minikube/reason/known_issues.go
  translations/de.json
  translations/es.json
  translations/fr.json
  translations/ja.json
  translations/ko.json
  translations/pl.json
  translations/ru.json
  translations/strings.txt
  translations/zh-CN.json
Labels: cncf-cla: yes, size/S, needs-ok-to-test

#14997 Fix update check logic
  cmd/minikube/cmd/start.go
  pkg/minikube/notify/notify.go
  pkg/minikube/notify/notify_test.go
Labels: cncf-cla: yes, size/S, approved, ok-to-test

#15000 Upgrade kubernetes dashboard from v2.6.0 to v2.7.0
  pkg/minikube/assets/addons.go
Labels: cncf-cla: yes, size/XS, ok-to-test

#15037 Fix `minikube dashboard` failing on macOS
  cmd/minikube/cmd/dashboard.go
Labels: cncf-cla: yes, size/XS, approved

#15032 Check if context is invalid during update-context
  pkg/minikube/kubeconfig/kubeconfig.go
  pkg/minikube/kubeconfig/kubeconfig_test.go
Labels: cncf-cla: yes, size/L, approved, ok-to-test
