Repository kubernetes/minikube, pull requests merged in 2022-04, with the labels that each got.

#13741 Upgrade kubernetes dashboard from v2.3.1 to v2.5.1
  pkg/minikube/assets/addons.go
  pkg/minikube/bootstrapper/images/images.go
  pkg/minikube/bootstrapper/images/images_test.go
  pkg/minikube/bootstrapper/images/kubeadm_test.go
  pkg/minikube/cruntime/containerd_test.go
  test/integration/start_stop_delete_test.go
Labels: cncf-cla: yes, size/S, approved, ok-to-test

#13896 Remove unnecessary icacls check
  pkg/drivers/kic/kic.go
Labels: cncf-cla: yes, size/XS, approved

#13903 Fix french translation
  translations/fr.json
Labels: cncf-cla: yes, size/XS, needs-ok-to-test

#13916 Fix PR Bot warnings
  pkg/minikube/perf/result_manager.go
Labels: cncf-cla: yes, size/XS, approved

#13885 Remove docker requirement for none driver
  pkg/minikube/registry/drvs/none/none.go
Labels: cncf-cla: yes, size/XS, approved, ok-to-test

#13901 remove uses of ioutil & use t.TempDir for tests
  cmd/minikube/cmd/config/set_test.go
  cmd/minikube/cmd/delete_test.go
  cmd/minikube/cmd/generate-docs_test.go
  cmd/minikube/cmd/root_test.go
  deploy/minikube/schema_check.go
  pkg/addons/addons_test.go
  pkg/drivers/common_test.go
  pkg/drivers/hyperkit/iso_test.go
  pkg/drivers/hyperkit/network_test.go
  pkg/minikube/bootstrapper/certs_test.go
  pkg/minikube/extract/extract_test.go
  pkg/minikube/kubeconfig/kubeconfig_test.go
  pkg/minikube/localpath/localpath_test.go
  pkg/minikube/machine/cache_binaries_test.go
  pkg/minikube/machine/client_test.go
  pkg/minikube/machine/cluster_test.go
  pkg/minikube/machine/filesync_test.go
  pkg/minikube/notify/notify_test.go
  pkg/minikube/tests/dir_utils.go
  pkg/util/crypto_test.go
  pkg/util/utils_test.go
  test/integration/aaa_download_only_test.go
  test/integration/driver_install_or_update_test.go
  test/integration/functional_test.go
  test/integration/functional_test_mount_test.go
  test/integration/helpers_test.go
  test/integration/multinode_test.go
Labels: cncf-cla: yes, size/L, approved, ok-to-test

#13900 improve language detection
  go.mod
  go.sum
  pkg/minikube/out/out_test.go
  pkg/minikube/translate/translate.go
  pkg/minikube/translate/translate_test.go
Labels: cncf-cla: yes, size/M, approved

#13911 Remove dashboard and metrics-scraper from preload
  pkg/minikube/bootstrapper/images/images.go
  pkg/minikube/bootstrapper/images/images_test.go
  pkg/minikube/bootstrapper/images/kubeadm_test.go
  pkg/minikube/cruntime/containerd_test.go
  pkg/minikube/download/preload.go
Labels: cncf-cla: yes, size/M, approved, ok-to-test

#13910 Only skip downloading kic if --download-only=false
  pkg/minikube/node/cache.go
Labels: cncf-cla: yes, size/S, approved

#13933 Update containerd hash
  deploy/iso/minikube-iso/package/containerd-bin/containerd-bin.hash
Labels: cncf-cla: yes, size/XS, approved

#13659 ISO: Upgrade falco-module to version 0.31.0
  Makefile
  deploy/iso/minikube-iso/package/falco-module/falco-module.hash
  deploy/iso/minikube-iso/package/falco-module/falco-module.mk
  pkg/minikube/download/iso.go
  site/content/en/docs/commands/start.md
Labels: cncf-cla: yes, size/S, approved, ok-to-test

#13913 Updated windows kubectl alias documentation
  site/content/en/docs/handbook/kubectl.md
Labels: cncf-cla: yes, size/XS, needs-ok-to-test

#13829 Support rootless Podman driver, take 2 (Usage: `minikube config set rootless true`)
  cmd/minikube/cmd/config/config.go
  cmd/minikube/cmd/root.go
  cmd/minikube/cmd/start_flags.go
  pkg/drivers/kic/oci/cli_runner.go
  pkg/drivers/kic/oci/info.go
  pkg/drivers/kic/oci/oci.go
  pkg/minikube/config/config.go
  pkg/minikube/constants/constants.go
  pkg/minikube/registry/drvs/podman/podman.go
  site/content/en/docs/drivers/docker.md
  site/content/en/docs/drivers/includes/podman_usage.inc
Labels: cncf-cla: yes, size/M, approved, ok-to-test

#13812 Fix port validation error on specifying tcp/udp or range of ports.
  cmd/minikube/cmd/start.go
  cmd/minikube/cmd/start_test.go
Labels: cncf-cla: yes, size/L, approved, ok-to-test

#13957 Advise user of --force option when using root
  cmd/minikube/cmd/start.go
Labels: cncf-cla: yes, size/XS, approved

#13955 Fix logging when JSON output selected
  pkg/minikube/out/out.go
  pkg/minikube/out/out_reason.go
Labels: cncf-cla: yes, size/M, approved

#13963 Tidy up GCP-Auth go code
  pkg/addons/addons_gcpauth.go
Labels: cncf-cla: yes, size/M, approved, ok-to-test

#13965 GUI: Add basic view
  gui/cluster.h
  gui/window.cpp
  gui/window.h
Labels: cncf-cla: yes, size/L, approved

#13399 Site: Add macOS Hyperkit NFS Mounts Documentation
  site/content/en/docs/handbook/mount.md
Labels: cncf-cla: yes, size/XS, do-not-merge/invalid-commit-message

#13856 Improve description for minikube cache command
  cmd/minikube/cmd/cache.go
Labels: cncf-cla: yes, size/XS

#13976 Add `--user` flag to GUI commands
  gui/window.cpp
Labels: cncf-cla: yes, size/XS, approved

#13982 fix display order for error codes documentation
  pkg/generate/docs.go
  pkg/minikube/reason/reason.go
  site/content/en/docs/contrib/errorcodes.en.md
Labels: cncf-cla: yes, size/L, approved

#13983 Update setup_minikube_gui.md
  site/content/en/docs/tutorials/setup_minikube_gui.md
Labels: cncf-cla: yes, size/XS, approved

#13986 Fix french translation
  translations/fr.json
Labels: cncf-cla: yes, size/S, needs-ok-to-test

#13995 Fix pre command flags
  cmd/minikube/main.go
  pkg/minikube/audit/audit.go
  pkg/minikube/audit/audit_test.go
Labels: cncf-cla: yes, size/M, approved, ok-to-test

#14000 GUI: Add `/usr/local/bin` to `PATH` env on Mac
  gui/window.cpp
  gui/window.h
Labels: cncf-cla: yes, size/S, approved

#13979 Add JSON output to `minikube delete`
  cmd/minikube/cmd/delete.go
  pkg/minikube/out/register/register.go
Labels: cncf-cla: yes, size/S, approved, ok-to-test

#14008 GUI: Refresh cluster list when reopening GUI
  gui/window.cpp
  gui/window.h
Labels: cncf-cla: yes, size/XS, approved

#14015 Add Qt files to .gitignore
  .gitignore
Labels: cncf-cla: yes, size/XS, approved

#13988 Don't use kubelet network-plugin or cni-conf-dir with k8s 1.24
  pkg/minikube/bootstrapper/bsutil/kubelet.go
  pkg/minikube/cni/cni.go
  pkg/minikube/cruntime/cruntime.go
  pkg/minikube/cruntime/docker.go
  pkg/minikube/node/start.go
  test/integration/net_test.go
  test/integration/start_stop_delete_test.go
Labels: cncf-cla: yes, size/L, approved, ok-to-test

#14022 Remove setting event log path on delete
  cmd/minikube/cmd/delete.go
Labels: cncf-cla: yes, size/XS, approved

#14025 GUI: Add kubernetes version selector
  gui/window.cpp
  gui/window.h
Labels: cncf-cla: yes, size/S, approved

#14037 Fix french translation
  translations/fr.json
Labels: cncf-cla: yes, size/XS, needs-ok-to-test

#14028 Update nginx image
  pkg/minikube/assets/addons.go
Labels: cncf-cla: yes, size/XS, approved, ok-to-test

#14030 Don't add kubelet network-plugin flag in test
  test/integration/start_stop_delete_test.go
Labels: cncf-cla: yes, size/S, approved, ok-to-test

#14050 GUI: Link to `lastStart.txt` on failed start
  gui/window.cpp
Labels: cncf-cla: yes, size/S, approved

#14026 GUI: Add kubernetes version to cluster table
  gui/cluster.cpp
  gui/cluster.h
  gui/window.cpp
Labels: cncf-cla: yes, size/M, approved

#14048 GUI: Add pause/unpause buttons
  gui/cluster.h
  gui/window.cpp
  gui/window.h
Labels: cncf-cla: yes, size/L, approved

#14055 GUI: Add start, pause/unpause, and stop to tray
  gui/window.cpp
  gui/window.h
Labels: cncf-cla: yes, size/M, approved

#14029 Set short time Format in Audit log
  pkg/minikube/constants/constants.go
Labels: cncf-cla: yes, size/XS, approved, needs-ok-to-test

#14062 GUI: Cleanup & Improvements
  gui/window.cpp
  gui/window.h
Labels: cncf-cla: yes, size/M, approved

#14068 GUI: Add SSH for Mac
  gui/window.cpp
Labels: cncf-cla: yes, size/S, approved

#14065 GUI: Add status to tray menu
  gui/window.cpp
  gui/window.h
Labels: cncf-cla: yes, size/S, approved

#14049 GUI: Clicking the tray icon opens GUI
  gui/window.cpp
  gui/window.h
Labels: cncf-cla: yes, size/M, approved

#14069 GUI: Mark invalid clusters in table list
  gui/window.cpp
Labels: cncf-cla: yes, size/S, approved

#14038 Use GitHub instead of Github in documents and code comments
  README.md
  hack/jenkins/cloud_shell_functional_tests_docker.sh
  hack/jenkins/linux_integration_tests_docker.sh
  hack/jenkins/linux_integration_tests_docker_arm64.sh
  hack/jenkins/linux_integration_tests_docker_containerd.sh
  hack/jenkins/linux_integration_tests_docker_containerd_arm64.sh
  hack/jenkins/linux_integration_tests_docker_crio.sh
  hack/jenkins/linux_integration_tests_docker_crio_arm64.sh
  hack/jenkins/linux_integration_tests_kvm.sh
  hack/jenkins/linux_integration_tests_kvm_containerd.sh
  hack/jenkins/linux_integration_tests_kvm_crio.sh
  hack/jenkins/linux_integration_tests_none.sh
  hack/jenkins/linux_integration_tests_podman.sh
  hack/jenkins/linux_integration_tests_virtualbox.sh
  hack/jenkins/minikube_cross_build_and_upload.sh
  hack/jenkins/minikube_set_pending.sh
  hack/jenkins/osx_integration_tests_docker.sh
  hack/jenkins/osx_integration_tests_hyperkit.sh
  hack/jenkins/osx_integration_tests_virtualbox.sh
  hack/jenkins/release_build_and_upload.sh
  hack/jenkins/release_github_page.sh
  hack/jenkins/release_update_releases_json.sh
  hack/jenkins/test-flake-chart/compute_flake_rate.sh
  hack/jenkins/test-flake-chart/sync_tests.sh
  hack/update/kubernetes_version/update_kubernetes_version.go
  pkg/minikube/notify/constants.go
  pkg/perf/monitor/github.go
  site/content/en/docs/contrib/documentation.en.md
  site/content/en/docs/contrib/external-packages.en.md
  site/content/en/docs/contrib/releasing/binaries.md
  site/content/en/docs/contrib/tests.en.md
  site/content/en/docs/tutorials/continuous_integration.md
  site/content/en/docs/tutorials/setup_minikube_in_github_actions.md
  test/integration/functional_test.go
Labels: cncf-cla: yes, size/M, needs-ok-to-test

#13972 Fix nvidia-gpu with kvm-driver
  deploy/addons/gpu/nvidia-driver-installer.yaml.tmpl
  deploy/addons/gpu/nvidia-gpu-device-plugin.yaml.tmpl
  deploy/iso/minikube-iso/board/coreos/minikube/linux_defconfig
  deploy/iso/minikube-iso/external.mk
  deploy/iso/minikube-iso/linux/install-module-symvers.mk
  pkg/minikube/assets/addons.go
Labels: cncf-cla: yes, size/M, approved, needs-ok-to-test

#14071 site: Remove alpha tab from GUI docs
  site/content/en/docs/tutorials/setup_minikube_gui.md
Labels: cncf-cla: yes, size/M, approved

#14072 GUI: Make error background color dynamic
  gui/window.cpp
Labels: cncf-cla: yes, size/XS, approved
