Repository kubernetes/minikube, pull requests merged in 2022-03, with the labels that each got.

#13735 Skip updating to rc version of Golang
  hack/update/golang_version/update_golang_version.go
Labels: cncf-cla: yes, size/XS, approved

#13599 Update Japanese translation (LINE 301-352)
  translations/ja.json
Labels: cncf-cla: yes, size/M, lgtm, needs-ok-to-test

#13658 Fix command typo in suggestion
  pkg/minikube/reason/known_issues.go
  translations/de.json
  translations/es.json
  translations/fr.json
  translations/ja.json
  translations/ko.json
  translations/pl.json
  translations/ru.json
  translations/strings.txt
  translations/zh-CN.json
Labels: cncf-cla: yes, size/S, approved

#13724 fix minikube release twitter bot message
  .github/workflows/twitter-bot.yml
Labels: cncf-cla: yes, size/XS, approved

#13603 Update Japanese translation (LINE 163-204)
  translations/ja.json
Labels: cncf-cla: yes, size/M, lgtm, needs-ok-to-test

#13723 Added initial GUI
  .clang-format
  gui/LICENSE
  gui/README.md
  gui/cluster.cpp
  gui/cluster.h
  gui/images/minikube.icns
  gui/images/minikube.png
  gui/main.cpp
  gui/systray.pro
  gui/systray.qrc
  gui/window.cpp
  gui/window.h
  site/content/en/docs/tutorials/setup_minikube_gui.md
  site/static/images/gui/mac.png
  site/static/images/gui/windows.png
Labels: cncf-cla: yes, size/XXL, approved

#13752 site: add note about SSH and add link to creating issue
  site/content/en/docs/tutorials/setup_minikube_gui.md
Labels: cncf-cla: yes, size/XS, approved

#13756 ServiceCmd restructuring to repair docker/port-forward issues
  cmd/minikube/cmd/service.go
  cmd/minikube/cmd/service_test.go
  pkg/minikube/tunnel/kic/service_tunnel.go
  pkg/minikube/tunnel/kic/ssh_conn.go
  test/integration/functional_test.go
Labels: cncf-cla: yes, size/L, ok-to-test

#13784 GUI: Notify user on start if minikube not found on path
  gui/window.cpp
  gui/window.h
Labels: cncf-cla: yes, size/M, approved

#13630 Add sanity check to disk space check
  pkg/minikube/constants/constants.go
  pkg/minikube/machine/start.go
  pkg/minikube/machine/start_test.go
  test/integration/status_test.go
Labels: cncf-cla: yes, size/L, approved, ok-to-test, do-not-merge/failing-test

#13790 site: support nested tabs
  site/static/js/tabs.js
Labels: cncf-cla: yes, size/XS, approved

#13793 site: added brew and choco Docker install instructions
  site/content/en/docs/tutorials/docker_desktop_replacement.md
Labels: cncf-cla: yes, size/M, approved

#13803 Improve icacls error logging
  pkg/drivers/kic/kic.go
Labels: cncf-cla: yes, size/XS, approved, ok-to-test

#13792 site: added nightly build download for GUI
  site/content/en/docs/tutorials/setup_minikube_gui.md
Labels: cncf-cla: yes, size/M, approved

#13802 Add `--disable-metrics` flag
  cmd/minikube/cmd/start_flags.go
  pkg/minikube/config/types.go
  site/content/en/docs/commands/start.md
  test/integration/functional_test.go
  test/integration/guest_env_test.go
  translations/de.json
  translations/es.json
  translations/fr.json
  translations/ja.json
  translations/ko.json
  translations/pl.json
  translations/ru.json
  translations/strings.txt
  translations/zh-CN.json
Labels: cncf-cla: yes, size/M, approved, ok-to-test

#13781 Fix french translation
  translations/fr.json
Labels: cncf-cla: yes, size/XS, needs-ok-to-test

#13815 KIC: Update kicbase base image
  deploy/kicbase/Dockerfile
  pkg/drivers/kic/types.go
  site/content/en/docs/commands/start.md
Labels: cncf-cla: yes, size/S, approved, ok-to-test

#13811 bump golangci-lint to v1.45.0
  Makefile
  cmd/minikube/cmd/start.go
  pkg/minikube/driver/driver.go
Labels: cncf-cla: yes, size/S, approved

#13826 report cloud shell failures back to github
  hack/jenkins/cloud_shell_functional_tests_docker.sh
Labels: cncf-cla: yes, size/S, approved, ok-to-test

#13794 Bump metrics-server to v0.6.1
  deploy/addons/metrics-server/metrics-apiservice.yaml.tmpl
  deploy/addons/metrics-server/metrics-server-deployment.yaml.tmpl
  deploy/addons/metrics-server/metrics-server-rbac.yaml.tmpl
  deploy/addons/metrics-server/metrics-server-service.yaml.tmpl
  pkg/minikube/assets/addons.go
Labels: cncf-cla: yes, size/L, approved, ok-to-test

#13126 ISO: Podman 3.4.2
  deploy/iso/minikube-iso/package/podman/podman.hash
  deploy/iso/minikube-iso/package/podman/podman.mk
Labels: cncf-cla: yes, size/XS, approved, ok-to-test

#13771 Pinned actions to SHA and included permissions for actions
  .github/workflows/build.yml
  .github/workflows/docs.yml
  .github/workflows/functional_verified.yml
  .github/workflows/leaderboard.yml
  .github/workflows/master.yml
  .github/workflows/pr.yml
  .github/workflows/sync-minikube.yml
  .github/workflows/time-to-k8s-public-chart.yml
  .github/workflows/time-to-k8s.yml
  .github/workflows/translations.yml
  .github/workflows/twitter-bot.yml
  .github/workflows/update-golang-version.yml
  .github/workflows/update-golint-version.yml
  .github/workflows/update-k8s-versions.yml
  .github/workflows/update-kubadm-constants.yml
Labels: cncf-cla: yes, size/L, approved, needs-ok-to-test

#13843 Update containerd hash
  deploy/iso/minikube-iso/package/containerd-bin/containerd-bin.hash
Labels: cncf-cla: yes, size/XS, approved

#13770 Included githubactions in dependabot config
  .github/dependabot.yml
Labels: cncf-cla: yes, size/XS, needs-ok-to-test

#13844 Fix German translation
  translations/de.json
Labels: cncf-cla: yes, size/XS, approved, needs-ok-to-test

#13842 Implemented minimum and recommended Docker versions
  pkg/minikube/registry/drvs/docker/docker.go
  pkg/minikube/registry/drvs/docker/docker_test.go
  site/content/en/docs/drivers/docker.md
Labels: cncf-cla: yes, size/L, approved, ok-to-test

#13805 Improve autopause error handling
  cmd/auto-pause/auto-pause.go
  pkg/addons/addons_autopause.go
Labels: cncf-cla: yes, size/S, ok-to-test

#13654 [benchmark] add cpu utilization
  hack/benchmark/time-to-k8s/chart.go
  hack/benchmark/time-to-k8s/cpu.go
  hack/benchmark/time-to-k8s/page.go
  hack/benchmark/time-to-k8s/time-to-k8s.sh
Labels: cncf-cla: yes, size/L, needs-ok-to-test

#13800 ISO: Upgrade crio to 1.22.3
  Makefile
  deploy/iso/minikube-iso/package/crio-bin/crio-bin.hash
  deploy/iso/minikube-iso/package/crio-bin/crio-bin.mk
  pkg/minikube/download/iso.go
  site/content/en/docs/commands/start.md
Labels: cncf-cla: yes, size/S, approved, ok-to-test

#13867 Fix french translation
  translations/fr.json
Labels: cncf-cla: yes, size/S, needs-ok-to-test

#13858 Remove outdated comments
  .github/workflows/build.yml
  .github/workflows/docs.yml
  .github/workflows/functional_verified.yml
  .github/workflows/leaderboard.yml
  .github/workflows/master.yml
  .github/workflows/pr.yml
  .github/workflows/sync-minikube.yml
  .github/workflows/time-to-k8s-public-chart.yml
  .github/workflows/time-to-k8s.yml
  .github/workflows/translations.yml
  .github/workflows/twitter-bot.yml
  .github/workflows/update-golang-version.yml
  .github/workflows/update-golint-version.yml
  .github/workflows/update-k8s-versions.yml
  .github/workflows/update-kubadm-constants.yml
Labels: cncf-cla: yes, size/L, approved

#13859 Update GUI link to latest from version
  site/content/en/docs/tutorials/setup_minikube_gui.md
Labels: cncf-cla: yes, size/XS, approved

#11679 ISO: Add packaging for crun
  Makefile
  deploy/iso/minikube-iso/package/Config.in
  deploy/iso/minikube-iso/package/crio-bin/Config.in
  deploy/iso/minikube-iso/package/crun/Config.in
  deploy/iso/minikube-iso/package/crun/crun.hash
  deploy/iso/minikube-iso/package/crun/crun.mk
  deploy/iso/minikube-iso/package/podman/Config.in
  pkg/minikube/download/iso.go
  site/content/en/docs/commands/start.md
Labels: cncf-cla: yes, size/M, approved, ok-to-test

#13873 Silent fail when user trying to generate log file if cluster not running
  cmd/minikube/cmd/logs.go
Labels: cncf-cla: yes, size/M, approved, ok-to-test

#13860 ISO: Upgrade Docker, from 20.10.13 to 20.10.14
  Makefile
  deploy/iso/minikube-iso/package/containerd-bin/containerd-bin.hash
  deploy/iso/minikube-iso/package/containerd-bin/containerd-bin.mk
  deploy/iso/minikube-iso/package/docker-bin/docker-bin.hash
  deploy/iso/minikube-iso/package/docker-bin/docker-bin.mk
  pkg/minikube/download/iso.go
  site/content/en/docs/commands/start.md
Labels: cncf-cla: yes, size/S, approved, ok-to-test

#13879 Replace go get with go install
  hack/release_notes.sh
  hack/update_contributions.sh
Labels: cncf-cla: yes, size/S, approved

#13883 flake charts: Have test table link to matching time period
  hack/jenkins/test-flake-chart/flake_chart.js
Labels: cncf-cla: yes, size/S, approved

#13884 OLM: stop testing OLM and warn users about the addon
  cmd/minikube/cmd/config/enable.go
  test/integration/addons_test.go
Labels: cncf-cla: yes, size/XS, approved

#13887 Add warning to HyperKit users about removing environment variables from logs
  .github/ISSUE_TEMPLATE/__en-US.yaml
Labels: cncf-cla: yes, size/XS, approved

#13888 pr-flake-rate: Default links to last 90 days
  hack/jenkins/test-flake-chart/report_flakes.sh
Labels: cncf-cla: yes, size/XS, approved

#13730 Add 'subnet' flag for docker/podman driver
  cmd/minikube/cmd/start_flags.go
  pkg/drivers/kic/kic.go
  pkg/drivers/kic/oci/network_create.go
  pkg/drivers/kic/types.go
  pkg/minikube/config/types.go
  pkg/minikube/registry/drvs/docker/docker.go
  pkg/minikube/registry/drvs/podman/podman.go
  test/integration/kic_custom_network_test.go
Labels: cncf-cla: yes, size/M, approved, ok-to-test

#13889 Sync guest clock on initial and existing start
  pkg/minikube/machine/fix.go
  pkg/minikube/machine/start.go
Labels: cncf-cla: yes, size/S, approved, ok-to-test

#13881 Podman: fix `minikube delete` for Podman v4
  pkg/drivers/kic/oci/network.go
  pkg/drivers/kic/oci/network_create.go
  pkg/drivers/kic/oci/oci.go
Labels: cncf-cla: yes, size/S, ok-to-test
