Repository kubernetes/minikube, pull requests merged in 2022-10, with the labels that each got.

#15046 Add update check on `minikube status` & `minikube profile list`
  cmd/minikube/cmd/config/profile_list.go
  cmd/minikube/cmd/status.go
  pkg/minikube/notify/notify.go
Labels: cncf-cla: yes, size/S, approved

#15043 site: Add known issue to qemu documentation
  site/content/en/docs/drivers/qemu.md
Labels: cncf-cla: yes, size/S, approved

#14989 Implement socket_vmnet network (QEMU)
  cmd/minikube/cmd/docker-env.go
  cmd/minikube/cmd/service.go
  cmd/minikube/cmd/start_flags.go
  cmd/minikube/cmd/tunnel.go
  pkg/addons/addons.go
  pkg/addons/addons_autopause.go
  pkg/drivers/common.go
  pkg/drivers/common_test.go
  pkg/drivers/hyperkit/driver.go
  pkg/drivers/hyperkit/network.go
  pkg/drivers/hyperkit/network_test.go
  pkg/drivers/qemu/qemu.go
  pkg/minikube/cluster/ip.go
  pkg/minikube/driver/driver.go
  pkg/minikube/driver/endpoint.go
  pkg/minikube/node/start.go
  pkg/minikube/registry/drvs/qemu2/qemu2.go
  pkg/network/network.go
  site/content/en/docs/drivers/qemu.md
  translations/de.json
  translations/es.json
  translations/fr.json
  translations/ja.json
  translations/ko.json
  translations/pl.json
  translations/ru.json
  translations/strings.txt
  translations/zh-CN.json
Labels: cncf-cla: yes, size/XL, approved

#15066 Update entrypoint and kindnetd
  deploy/kicbase/entrypoint
  pkg/drivers/kic/types.go
  pkg/minikube/bootstrapper/images/images.go
  site/content/en/docs/commands/start.md
Labels: cncf-cla: yes, size/M, approved, ok-to-test

#15070 tests: Enable `TestPreload` for arm64
  test/integration/preload_test.go
Labels: cncf-cla: yes, size/S, approved, ok-to-test

#15080 site: change wording for memory change
  site/content/en/docs/start/_index.md
Labels: cncf-cla: yes, size/XS, approved, needs-ok-to-test

#15073 Warn QEMU users of DNS issue
  pkg/minikube/node/start.go
  translations/de.json
  translations/es.json
  translations/fr.json
  translations/ja.json
  translations/ko.json
  translations/pl.json
  translations/ru.json
  translations/strings.txt
  translations/zh-CN.json
Labels: cncf-cla: yes, size/S, approved

#15077 Fix status taking a long time on docker driver
  cmd/minikube/cmd/start.go
  pkg/minikube/bootstrapper/bsutil/kverify/api_server.go
  pkg/minikube/cluster/pause.go
  pkg/minikube/pause/pause.go
Labels: cncf-cla: yes, size/M, approved, ok-to-test

#15085 Allow passing only exposed port to --ports
  cmd/minikube/cmd/start.go
  cmd/minikube/cmd/start_test.go
Labels: cncf-cla: yes, size/L, approved

#15088 Release 1.27.1
  CHANGELOG.md
  Makefile
Labels: cncf-cla: yes, size/M, approved, ok-to-test

#15081 Warn if addon has no associated Github username
  cmd/minikube/cmd/config/enable.go
  translations/de.json
  translations/es.json
  translations/fr.json
  translations/ja.json
  translations/ko.json
  translations/pl.json
  translations/ru.json
  translations/strings.txt
  translations/zh-CN.json
Labels: cncf-cla: yes, size/M

#15075 Update kicbase base image
  deploy/kicbase/Dockerfile
  pkg/drivers/kic/types.go
  site/content/en/docs/commands/start.md
Labels: cncf-cla: yes, size/S, approved, ok-to-test

#15100 CI: Stop killing docker process
  hack/jenkins/common.sh
Labels: cncf-cla: yes, size/S, approved, ok-to-test

#15110 Add 'qemu' to list of issue template drivers
  .github/ISSUE_TEMPLATE/__en-US.yaml
  .github/ISSUE_TEMPLATE/ru.yaml
Labels: cncf-cla: yes, size/XS, approved

#15071 tests: Shorten qmp path
  hack/jenkins/common.sh
  test/integration/start_stop_delete_test.go
  test/integration/util_test.go
Labels: cncf-cla: yes, size/XS, approved, ok-to-test

#15108 Fix mounting on QEMU with socket_vmnet
  cmd/minikube/cmd/mount.go
  pkg/minikube/cluster/ip.go
  translations/de.json
  translations/es.json
  translations/fr.json
  translations/ja.json
  translations/ko.json
  translations/pl.json
  translations/ru.json
  translations/strings.txt
  translations/zh-CN.json
Labels: cncf-cla: yes, size/S, approved

#15145 Update OWNERS file
  OWNERS
Labels: cncf-cla: yes, size/XS, approved

#14784 Add back service to mount VirtualBox host directory into the guest.
  deploy/iso/minikube-iso/arch/x86_64/package/Config.in
  deploy/iso/minikube-iso/arch/x86_64/package/vbox-mount-service/Config.in
  deploy/iso/minikube-iso/arch/x86_64/package/vbox-mount-service/vbox-mount-service.hash
  deploy/iso/minikube-iso/arch/x86_64/package/vbox-mount-service/vbox-mount-service.mk
  deploy/iso/minikube-iso/arch/x86_64/package/vbox-mount-service/vboxservice.service
  deploy/iso/minikube-iso/configs/minikube_x86_64_defconfig
  deploy/iso/minikube-iso/package/automount/minikube-automount
Labels: cncf-cla: yes, size/M, approved, ok-to-test

#15133 Update zh-CN.json
  translations/zh-CN.json
Labels: cncf-cla: yes, size/XS, needs-ok-to-test

#15157 site: update latest release on site
  hack/jenkins/release_update_releases_json.sh
  site/content/en/docs/_index.md
Labels: cncf-cla: yes, size/XS, approved

#15175 site: Add documentation about adding a new namespace with GCP-Auth
  site/content/en/docs/handbook/addons/gcp-auth.md
Labels: cncf-cla: yes, size/XS, approved

#15159 ISO: Update Docker from 20.10.18 to 20.10.20
  Makefile
  deploy/iso/minikube-iso/arch/aarch64/package/docker-bin-aarch64/docker-bin.hash
  deploy/iso/minikube-iso/arch/aarch64/package/docker-bin-aarch64/docker-bin.mk
  deploy/iso/minikube-iso/arch/x86_64/package/docker-bin/docker-bin.hash
  deploy/iso/minikube-iso/arch/x86_64/package/docker-bin/docker-bin.mk
  pkg/minikube/download/iso.go
Labels: cncf-cla: yes, size/S, approved, ok-to-test

#15186 Upgrade Headlamp version to 0.13.0
  pkg/minikube/assets/addons.go
Labels: cncf-cla: yes, size/XS, ok-to-test

#15188 site: Update command to open GUI
  site/content/en/docs/tutorials/setup_minikube_gui.md
Labels: cncf-cla: yes, size/XS, approved

#15203 Fix french translation
  translations/fr.json
Labels: cncf-cla: yes, size/S, needs-ok-to-test

#15158 Add `minikube license` command
  Makefile
  cmd/minikube/cmd/license.go
  cmd/minikube/cmd/root.go
  hack/generate_licenses.sh
  hack/jenkins/release_build_and_upload.sh
  hack/release_notes.sh
  hack/update_contributions.sh
  pkg/minikube/download/licenses.go
  pkg/minikube/reason/reason.go
  site/content/en/docs/commands/license.md
  site/content/en/docs/contrib/errorcodes.en.md
  site/content/en/docs/contrib/releasing/binaries.md
  site/content/en/docs/contrib/tests.en.md
  test/integration/functional_test.go
  translations/de.json
  translations/es.json
  translations/fr.json
  translations/ja.json
  translations/ko.json
  translations/pl.json
  translations/ru.json
  translations/strings.txt
  translations/zh-CN.json
Labels: cncf-cla: yes, size/L, approved, ok-to-test

#15172 Portainer addon version bump to 2.15.1 & HTTPS access enabled
  deploy/addons/portainer/portainer.yaml.tmpl
  pkg/minikube/assets/addons.go
Labels: cncf-cla: yes, size/M, approved, ok-to-test

#14933 Fix minikube tunnel repeated printout of status
  pkg/minikube/tunnel/reporter.go
  pkg/minikube/tunnel/reporter_test.go
Labels: cncf-cla: yes, size/S, approved, needs-ok-to-test

#15126 use port forwarding on Linux with Docker Desktop
  cmd/minikube/cmd/start_flags.go
  pkg/drivers/kic/oci/info.go
  pkg/minikube/driver/driver.go
  translations/de.json
  translations/es.json
  translations/fr.json
  translations/ja.json
  translations/ko.json
  translations/pl.json
  translations/ru.json
  translations/strings.txt
  translations/zh-CN.json
Labels: cncf-cla: yes, size/S, approved, ok-to-test

#15220 Fix licenses test on Windows
  test/integration/functional_test.go
Labels: cncf-cla: yes, size/S, approved, ok-to-test

#15219 Update Ubuntu image
  deploy/kicbase/Dockerfile
  pkg/drivers/kic/types.go
  site/content/en/docs/commands/start.md
Labels: cncf-cla: yes, size/XS, approved, ok-to-test

#14956 fix: trim docker.io to prevent always writing to daemon
  pkg/minikube/cruntime/docker.go
  pkg/minikube/download/image.go
  pkg/minikube/image/image.go
Labels: cncf-cla: yes, size/S, ok-to-test

#15216 Add some translations
  translations/zh-CN.json
Labels: cncf-cla: yes, size/S, needs-ok-to-test

#15230 CI: Remove deprecated set-output
  .github/workflows/docs.yml
  .github/workflows/leaderboard.yml
  .github/workflows/time-to-k8s.yml
  .github/workflows/update-golang-version.yml
  .github/workflows/update-golint-version.yml
  .github/workflows/update-gopogh-version.yml
  .github/workflows/update-gotestsum-version.yml
  .github/workflows/update-k8s-versions.yml
  .github/workflows/update-kubeadm-constants.yml
  .github/workflows/yearly-leaderboard.yml
  hack/update/golang_version/update_golang_version.go
Labels: cncf-cla: yes, size/M, approved

#15160 Added cloud-spanner emulator add-on.
  cmd/minikube/cmd/config/addons_list_test.go
  deploy/addons/assets.go
  deploy/addons/cloud-spanner/deployment.yaml
  pkg/addons/config.go
  pkg/minikube/assets/addons.go
  site/content/en/docs/contrib/tests.en.md
  site/content/en/docs/handbook/addons/cloud-spanner.md
  test/integration/addons_test.go
Labels: cncf-cla: yes, size/L, approved, ok-to-test

#15249 Fix French translation
  translations/fr.json
Labels: cncf-cla: yes, size/XS, approved, needs-ok-to-test

#15238 Add logging if docker images command fails
  pkg/minikube/cruntime/docker.go
Labels: cncf-cla: yes, size/XS, approved
