Repository kubernetes/minikube, pull requests merged in 2022-01, with the labels that each got.

#13000 add BR2_PACKAGE_LIBFUSE addresses #12426
  deploy/iso/minikube-iso/configs/minikube_defconfig
Labels: cncf-cla: yes, size/XS, approved, ok-to-test

#13197 Update Japanese translation (LINE 351-401)
  translations/ja.json
Labels: cncf-cla: yes, size/M, lgtm, needs-ok-to-test

#13263 flake charts: allow toggling between all-time and last 90 day flake charts
  hack/jenkins/test-flake-chart/flake_chart.html
  hack/jenkins/test-flake-chart/flake_chart.js
  hack/jenkins/test-flake-chart/process_last_90/process_last_90.go
  hack/jenkins/test-flake-chart/process_last_90/process_last_90.sh
  hack/jenkins/test-flake-chart/sync_tests.sh
  site/content/en/docs/contrib/test_flakes.en.md
Labels: cncf-cla: yes, size/L, approved, ok-to-test

#13300 Support DOCKER_HOST not being numeric IP
  pkg/minikube/driver/endpoint.go
Labels: cncf-cla: yes, size/S, approved, ok-to-test

#13264 Improved the output in minikube github action
  pkg/minikube/detect/detect.go
  pkg/minikube/download/download.go
  test/integration/functional_test.go
  test/integration/functional_test_tunnel_test.go
  test/integration/main_test.go
Labels: cncf-cla: yes, size/M, approved

#13270 German Translations
  translations/de.json
Labels: cncf-cla: yes, size/XXL, needs-ok-to-test

#13295 Add hint to translation check to documentation
  site/content/en/docs/contrib/translations.md
Labels: cncf-cla: yes, size/XS, needs-ok-to-test

#13309 Make warning for running amd64 binary on M1 more visible
  cmd/minikube/cmd/root.go
Labels: cncf-cla: yes, size/XS, approved

#13316 Add missing `minikube-darwin-arm64.sha265` to checksum generation
  Makefile
Labels: cncf-cla: yes, size/XS, approved

#13310 Add SHA for all archs to releases.json file
  hack/jenkins/release_update_releases_json.go
  hack/jenkins/release_update_releases_json.sh
  hack/jenkins/test-flake-chart/process_last_90/process_last_90.go
Labels: cncf-cla: yes, size/L, approved

#13256 Site: Make the Docker API endpoint docs more generic
  site/content/en/docs/_index.md
Labels: cncf-cla: yes, size/XS, approved

#12102 Use cri-dockerd instead of dockershim where needed
  pkg/minikube/bootstrapper/kubeadm/kubeadm.go
  pkg/minikube/cruntime/cruntime.go
  pkg/minikube/cruntime/cruntime_test.go
  pkg/minikube/cruntime/docker.go
Labels: cncf-cla: yes, size/L, approved, ok-to-test

#13257 site: Need to use docker runtime for docker daemon
  site/content/en/docs/faq/_index.md
Labels: cncf-cla: yes, size/XS, approved

#13327 Add klaases as reviewer
  OWNERS
Labels: cncf-cla: yes, size/XS, approved

#13247 Update Japanese translation (Line 61-110)
  translations/ja.json
Labels: cncf-cla: yes, size/M, lgtm

#13283 Update Japanese translation (LINE 253-299)
  translations/ja.json
Labels: cncf-cla: yes, size/M, lgtm, needs-ok-to-test

#13328 Remove deprecated global-housekeeping-interval flag
  pkg/minikube/driver/driver.go
  pkg/minikube/driver/driver_test.go
Labels: cncf-cla: yes, size/XS, approved

#12804 New flag "--binary-mirror" to override mirror URL downloading (kubectl, kubelet, & kubeadm)
  cmd/minikube/cmd/dashboard.go
  cmd/minikube/cmd/kubectl.go
  cmd/minikube/cmd/start_flags.go
  hack/preload-images/generate.go
  pkg/minikube/bootstrapper/bsutil/binaries.go
  pkg/minikube/bootstrapper/kubeadm/kubeadm.go
  pkg/minikube/config/types.go
  pkg/minikube/download/binary.go
  pkg/minikube/download/download_test.go
  pkg/minikube/machine/cache_binaries.go
  pkg/minikube/machine/cache_binaries_test.go
  pkg/minikube/node/cache.go
  test/integration/aaa_download_only_test.go
Labels: cncf-cla: yes, size/L, ok-to-test

#13341 Add example commands for docker-env FAQ
  site/content/en/docs/faq/_index.md
Labels: cncf-cla: yes, size/S, approved

#13347 fix binary mirror test for none driver
  test/integration/aaa_download_only_test.go
Labels: cncf-cla: yes, size/XS, approved, ok-to-test

#13373 Fix french translation
  translations/fr.json
Labels: cncf-cla: yes, size/XS, needs-ok-to-test

#13390 Revert "Bump k8s.io/client-go from 0.22.4 to 0.23.1"
  go.mod
  go.sum
Labels: cncf-cla: yes, size/M, approved

#13392 Revert docker dep update
  go.mod
  go.sum
Labels: cncf-cla: yes, size/M, approved, ok-to-test

#13391 Release v1.25.0
  CHANGELOG.md
  Makefile
Labels: cncf-cla: yes, size/M, approved, ok-to-test

#13401 fix update leaderboard script
  hack/update_contributions.sh
Labels: cncf-cla: yes, size/XS, approved

#13409 Revert "update releases.json to include v1.25.0"
  deploy/minikube/releases.json
  site/content/en/docs/_index.md
Labels: cncf-cla: yes, size/XXL, approved

#13415 time-to-k8s: Fix long table lines auto wrapping
  hack/benchmark/time-to-k8s/chart.go
  site/content/en/docs/benchmarks/timeToK8s/v1.25.0.md
Labels: cncf-cla: yes, size/S, approved

#13418 remove reference to nonexistent file for hyperkit driver
  pkg/drivers/hyperkit/driver.go
Labels: cncf-cla: yes, size/XS, approved, ok-to-test

#13420 Release 1.25.1
  CHANGELOG.md
  Makefile
Labels: cncf-cla: yes, size/S, approved

#13426 Remove empty checksum objects to pass schema check
  deploy/minikube/releases.json
Labels: cncf-cla: yes, size/XS, approved

#13428 Always backfill all missing leaderboard versions
  hack/update_contributions.sh
Labels: cncf-cla: yes, size/S, approved

#13349 Ignore adding kube images to kubeadm constants file
  hack/update/kubeadm_constants/update_kubeadm_constants.go
  pkg/minikube/constants/constants_kubeadm_images.go
Labels: cncf-cla: yes, size/L, approved

#13393 CI: `ImageList` use image that is available immediately
  test/integration/functional_test.go
Labels: cncf-cla: yes, size/S, approved

#13444 Fix hard coded docker driver in minikube tunnel command
  cmd/minikube/cmd/tunnel.go
Labels: cncf-cla: yes, size/XS, needs-ok-to-test

#13440 upgrade libvirt to "8th gen"
  go.mod
  go.sum
  pkg/drivers/kvm/domain.go
  pkg/drivers/kvm/kvm.go
  pkg/drivers/kvm/network.go
Labels: cncf-cla: yes, size/S, approved, ok-to-test

#13442 configure container runtimes for clusters without Kubernetes too
  pkg/minikube/node/start.go
Labels: cncf-cla: yes, size/XS, approved

#13353 Change file path for preload tar files to be organized by version
  hack/preload-images/preload_images.go
  hack/preload-images/upload.go
  pkg/minikube/download/preload.go
Labels: cncf-cla: yes, size/S, approved, ok-to-test

#13419 Fix bug in AUX Driver Download URL for ARM64
  pkg/minikube/download/driver.go
Labels: cncf-cla: yes, size/XS, approved

#13340 Add `--disable-optimizations` flag
  cmd/minikube/cmd/start_flags.go
  pkg/minikube/config/types.go
  pkg/minikube/driver/driver.go
  pkg/minikube/driver/driver_test.go
  pkg/minikube/node/start.go
  site/content/en/docs/commands/start.md
  test/integration/functional_test.go
  test/integration/guest_env_test.go
  translations/de.json
  translations/es.json
  translations/fr.json
  translations/ja.json
  translations/ko.json
  translations/pl.json
  translations/ru.json
  translations/strings.txt
  translations/zh-CN.json
Labels: cncf-cla: yes, size/M, approved, ok-to-test

#13485 preloads: Add trailing slash to bucket destination to indicate folder
  hack/preload-images/upload.go
Labels: cncf-cla: yes, size/XS, approved

#13321 Update Japanese translation (LINE 400-449)
  translations/ja.json
Labels: cncf-cla: yes, size/L, lgtm, needs-ok-to-test

#13490 update yaml templates to v1beta3 for update k8s version job
  hack/update/kubernetes_version/templates/v1beta3/containerd-api-port.yaml
  hack/update/kubernetes_version/templates/v1beta3/containerd-pod-network-cidr.yaml
  hack/update/kubernetes_version/templates/v1beta3/containerd.yaml
  hack/update/kubernetes_version/templates/v1beta3/crio-options-gates.yaml
  hack/update/kubernetes_version/templates/v1beta3/crio.yaml
  hack/update/kubernetes_version/templates/v1beta3/default.yaml
  hack/update/kubernetes_version/templates/v1beta3/dns.yaml
  hack/update/kubernetes_version/templates/v1beta3/image-repository.yaml
  hack/update/kubernetes_version/templates/v1beta3/options.yaml
  hack/update/kubernetes_version/update_kubernetes_version.go
Labels: cncf-cla: yes, size/M, approved

#13345 Add docs for setting up WSL 2 & Docker
  site/content/en/docs/drivers/docker.md
  site/content/en/docs/drivers/includes/docker_usage.inc
  site/content/en/docs/tutorials/wsl_docker_driver.md
  site/static/js/tabs.js
Labels: cncf-cla: yes, size/L, approved

#13069 site: Add info about gcp-auth to registry handbook page
  site/content/en/docs/handbook/registry.md
Labels: cncf-cla: no, size/XS, needs-ok-to-test

#13499 preloads: Add option to upload arm64 preloads
  hack/preload-images/preload_images.go
  hack/preload-images/upload.go
Labels: cncf-cla: yes, size/M, approved

#12835 Print a message about preserving kicbase image when `minkube delete --purge --all` used
  cmd/minikube/cmd/delete.go
  pkg/drivers/kic/oci/oci.go
Labels: cncf-cla: yes, size/M, approved, ok-to-test

#13518 Fix french translation
  translations/fr.json
Labels: cncf-cla: yes, size/XS, needs-ok-to-test
