Repository kubernetes/minikube, pull requests merged in 2023-02, with the labels that each got.

#15753 Update HyperKit build image from go1.17 to go1.19.5
  Makefile
Labels: cncf-cla: yes, size/XS, approved, ok-to-test

#15744 CI: Skip updating golang hash file if version already exists
  hack/update/golang_version/update_golang_version.go
Labels: cncf-cla: yes, size/S, approved

#15743 Update cloud-spanner SHA
  pkg/minikube/assets/addons.go
Labels: cncf-cla: yes, size/XS, approved, ok-to-test

#15728 Kicbase/ISO: Update buildkit to v0.11.2
  Makefile
  deploy/iso/minikube-iso/arch/aarch64/package/buildkit-bin-aarch64/buildkit-bin.hash
  deploy/iso/minikube-iso/arch/aarch64/package/buildkit-bin-aarch64/buildkit-bin.mk
  deploy/iso/minikube-iso/arch/x86_64/package/buildkit-bin/buildkit-bin.hash
  deploy/iso/minikube-iso/arch/x86_64/package/buildkit-bin/buildkit-bin.mk
  deploy/kicbase/Dockerfile
  pkg/drivers/kic/types.go
  pkg/minikube/download/iso.go
  site/content/en/docs/commands/start.md
Labels: cncf-cla: yes, size/M, approved, ok-to-test

#15767 update owners file and security contacts
  OWNERS
  SECURITY_CONTACTS
Labels: cncf-cla: yes, size/XS, approved

#15763 kic: limit SSH auth to only private key
  Makefile
  deploy/kicbase/Dockerfile
  pkg/drivers/kic/types.go
  site/content/en/docs/commands/start.md
Labels: cncf-cla: yes, size/S, approved, ok-to-test

#15400 docs: add doc for running minikube in China mainland
  site/content/en/docs/faq/_index.md
Labels: cncf-cla: yes, size/S, approved, needs-ok-to-test

#15794 CI: return commit when getting GitHub releases
  hack/update/docsy_version/update_docsy_version.go
  hack/update/gh_version/update_gh_version.go
  hack/update/github.go
  hack/update/golint_version/update_golint_version.go
  hack/update/gopogh_version/update_gopogh_version.go
  hack/update/gotestsum_version/update_gotestsum_version.go
  hack/update/hugo_version/update_hugo_version.go
  hack/update/kubernetes_version/update_kubernetes_version.go
Labels: cncf-cla: yes, size/L, approved

#15798 Bump github.com/containerd/containerd from 1.5.2 to 1.6.16
  go.mod
  go.sum
Labels: cncf-cla: yes, size/L, approved, ok-to-test

#15818 Fix french translation
  translations/fr.json
Labels: cncf-cla: yes, size/XS, needs-ok-to-test

#15770 add new flag --last-start-only to only show last start logs
  cmd/minikube/cmd/logs.go
  pkg/minikube/logs/logs.go
  site/content/en/docs/commands/logs.md
  translations/de.json
  translations/es.json
  translations/fr.json
  translations/ja.json
  translations/ko.json
  translations/pl.json
  translations/ru.json
  translations/strings.txt
  translations/zh-CN.json
Labels: cncf-cla: yes, size/M, approved, ok-to-test

#15820 tests: fix setting bad DOCKER_HOST for TestDownloadOnlyKic
  test/integration/aaa_download_only_test.go
Labels: cncf-cla: yes, size/XS, approved, ok-to-test

#15793 QEMU: Rename `user` network to `builtin` and update documentation
  cmd/minikube/cmd/docker-env.go
  cmd/minikube/cmd/mount.go
  cmd/minikube/cmd/service.go
  cmd/minikube/cmd/start_flags.go
  cmd/minikube/cmd/tunnel.go
  pkg/drivers/qemu/qemu.go
  pkg/minikube/cluster/ip.go
  pkg/minikube/driver/endpoint.go
  pkg/minikube/node/start.go
  pkg/network/network.go
  site/content/en/docs/drivers/qemu.md
Labels: cncf-cla: yes, size/L, approved, ok-to-test

#15775 Add ingress pod to logs output
  pkg/minikube/logs/logs.go
  pkg/minikube/logs/logs_test.go
Labels: cncf-cla: yes, size/M, approved, ok-to-test

#15735 fix: service CLI command not honoring --wait arg
  pkg/minikube/service/service.go
  pkg/minikube/service/service_test.go
Labels: cncf-cla: yes, size/M, ok-to-test

#15837 docs: clarify the current setting logic of MINIKUBE_HOME
  site/content/en/docs/handbook/config.md
Labels: cncf-cla: yes, size/XS, approved, needs-ok-to-test

#15731 Print proper value of mount type using info print statement
  cmd/minikube/cmd/mount.go
Labels: cncf-cla: yes, size/XS, ok-to-test

#15840 Download binaries from dl.k8s.io instead of GCS
  .github/workflows/functional_verified.yml
  .github/workflows/master.yml
  .github/workflows/pr.yml
  .github/workflows/time-to-k8s-public-chart.yml
  deploy/prow/Dockerfile
  hack/jenkins/common.ps1
  hack/jenkins/installers/check_install_docker.sh
  hack/jenkins/linux_integration_tests_none.sh
  hack/update/kubeadm_constants/update_kubeadm_constants.go
  pkg/minikube/download/binary.go
  pkg/minikube/download/download.go
  pkg/minikube/reason/match_test.go
  site/content/en/docs/tutorials/continuous_integration.md
Labels: cncf-cla: yes, size/M, approved, ok-to-test

#15781 Implement experimental QEMU on Windows code
  pkg/drivers/qemu/qemu.go
  pkg/minikube/registry/drvs/qemu2/qemu2.go
Labels: cncf-cla: yes, size/M, approved

#15829 update CSI driver, enable multi-node
  deploy/addons/csi-hostpath-driver/deploy/csi-hostpath-attacher.yaml.tmpl
  deploy/addons/csi-hostpath-driver/deploy/csi-hostpath-driverinfo.yaml.tmpl
  deploy/addons/csi-hostpath-driver/deploy/csi-hostpath-plugin.yaml.tmpl
  deploy/addons/csi-hostpath-driver/deploy/csi-hostpath-provisioner.yaml.tmpl
  deploy/addons/csi-hostpath-driver/deploy/csi-hostpath-resizer.yaml.tmpl
  deploy/addons/csi-hostpath-driver/deploy/csi-hostpath-snapshotter.yaml.tmpl
  deploy/addons/csi-hostpath-driver/rbac/rbac-external-health-monitor-agent.yaml.tmpl
  deploy/addons/csi-hostpath-driver/rbac/rbac-external-health-monitor-controller.yaml.tmpl
  deploy/addons/csi-hostpath-driver/rbac/rbac-external-provisioner.yaml.tmpl
  deploy/addons/csi-hostpath-driver/rbac/rbac-external-resizer.yaml.tmpl
  deploy/addons/csi-hostpath-driver/rbac/rbac-external-snapshotter.yaml.tmpl
  deploy/addons/csi-hostpath-driver/rbac/rbac-hostpath.yaml.tmpl
  deploy/addons/volumesnapshots/rbac-volume-snapshot-controller.yaml.tmpl
  deploy/addons/volumesnapshots/volume-snapshot-controller-deployment.yaml.tmpl
  pkg/minikube/assets/addons.go
  site/content/en/docs/handbook/persistent_volumes.md
  site/content/en/docs/tutorials/multi_node.md
  site/content/en/docs/tutorials/volume_snapshots_and_csi.md
Labels: cncf-cla: yes, size/XL, approved, ok-to-test

#15856 Add shell completion for minikube kubectl subcommand
  cmd/minikube/cmd/kubectl.go
  go.mod
  go.sum
Labels: cncf-cla: yes, size/L, ok-to-test

#15851 Prevent panic if docker version returns exit code 0 with unexpected output
  pkg/minikube/registry/drvs/docker/docker.go
  pkg/minikube/registry/drvs/docker/docker_test.go
Labels: cncf-cla: yes, size/L, approved, ok-to-test

#15850 Fix bash completion for kubectl symlinked to minikube by not adding `--cluster` flag for the `kubectl __complete` subcommand
  cmd/minikube/cmd/kubectl.go
Labels: cncf-cla: yes, size/XS, ok-to-test

#15864 change errorf to warnf for aduit error
  cmd/minikube/cmd/root.go
Labels: cncf-cla: yes, size/XS, approved, ok-to-test

#15752 ISO/Kicbase: Update cri-dockerd from 0.3.0 to 0.3.1
  .github/workflows/master.yml
  .github/workflows/pr.yml
  Makefile
  deploy/iso/minikube-iso/arch/aarch64/package/cri-dockerd-aarch64/cri-dockerd.hash
  deploy/iso/minikube-iso/arch/aarch64/package/cri-dockerd-aarch64/cri-dockerd.mk
  deploy/iso/minikube-iso/arch/x86_64/package/cri-dockerd/cri-dockerd.hash
  deploy/iso/minikube-iso/arch/x86_64/package/cri-dockerd/cri-dockerd.mk
  deploy/kicbase/Dockerfile
  hack/jenkins/linux_integration_tests_none.sh
  hack/update/cri_dockerd_version/update_cri_dockerd_version.go
  hack/update/cri_dockerd_version/update_cri_dockerd_version.sh
  pkg/drivers/kic/types.go
  pkg/minikube/download/iso.go
  site/content/en/docs/commands/start.md
Labels: cncf-cla: yes, size/L, approved, ok-to-test

#15768 Kicbase: Update Ubuntu base image
  deploy/kicbase/Dockerfile
  pkg/drivers/kic/types.go
  site/content/en/docs/commands/start.md
Labels: cncf-cla: yes, size/XS, approved, ok-to-test

#15784 Look for cri-dockerd instead of hardcoding
  pkg/minikube/cruntime/docker.go
Labels: cncf-cla: yes, size/S, approved, ok-to-test

#15849 Disable plain text login for ISO
  Makefile
  deploy/iso/minikube-iso/board/minikube/aarch64/users
  deploy/iso/minikube-iso/board/minikube/x86_64/users
  pkg/minikube/download/iso.go
Labels: cncf-cla: yes, size/XS, approved, ok-to-test

#15872 new flag --skip-audit and skip profile cmd from audit by default
  cmd/minikube/cmd/root.go
  pkg/minikube/audit/audit.go
  pkg/minikube/config/config.go
  site/content/en/docs/commands/addons.md
  site/content/en/docs/commands/cache.md
  site/content/en/docs/commands/completion.md
  site/content/en/docs/commands/config.md
  site/content/en/docs/commands/cp.md
  site/content/en/docs/commands/dashboard.md
  site/content/en/docs/commands/delete.md
  site/content/en/docs/commands/docker-env.md
  site/content/en/docs/commands/help.md
  site/content/en/docs/commands/image.md
  site/content/en/docs/commands/ip.md
  site/content/en/docs/commands/kubectl.md
  site/content/en/docs/commands/license.md
  site/content/en/docs/commands/logs.md
  site/content/en/docs/commands/mount.md
  site/content/en/docs/commands/node.md
  site/content/en/docs/commands/options.md
  site/content/en/docs/commands/pause.md
  site/content/en/docs/commands/podman-env.md
  site/content/en/docs/commands/profile.md
  site/content/en/docs/commands/service.md
  site/content/en/docs/commands/ssh-host.md
  site/content/en/docs/commands/ssh-key.md
  site/content/en/docs/commands/ssh.md
  site/content/en/docs/commands/start.md
  site/content/en/docs/commands/status.md
  site/content/en/docs/commands/stop.md
  site/content/en/docs/commands/tunnel.md
  site/content/en/docs/commands/unpause.md
  site/content/en/docs/commands/update-check.md
  site/content/en/docs/commands/update-context.md
  site/content/en/docs/commands/version.md
Labels: cncf-cla: yes, size/M, approved, ok-to-test

#15884 CI: auto update cloud-spanner-emulator
  .github/workflows/update-cloud-spanner-emulator-version.yml
  Makefile
  hack/update/cloud_spanner_emulator_version/update_cloud_spanner_emulator_version.go
  hack/update/golang_version/update_golang_version.go
  hack/update/image.go
Labels: cncf-cla: yes, size/L, approved

#15762 Fix `minikube addons list` output for default addons
  pkg/addons/addons.go
  pkg/addons/addons_test.go
  pkg/minikube/assets/addons.go
  pkg/minikube/node/start.go
Labels: cncf-cla: yes, size/M, ok-to-test

#15886 CI: Make common func to get stable version
  hack/update/cloud_spanner_emulator_version/update_cloud_spanner_emulator_version.go
  hack/update/docsy_version/update_docsy_version.go
  hack/update/gh_version/update_gh_version.go
  hack/update/github.go
  hack/update/golint_version/update_golint_version.go
  hack/update/gopogh_version/update_gopogh_version.go
  hack/update/gotestsum_version/update_gotestsum_version.go
  hack/update/hugo_version/update_hugo_version.go
Labels: cncf-cla: yes, size/L, approved

#15882 Addons: Update ingress controller from v1.5.1 to v1.6.4
  pkg/minikube/assets/addons.go
Labels: cncf-cla: yes, size/XS, approved, ok-to-test

#15892 translate some fields
  translations/zh-CN.json
Labels: cncf-cla: yes, size/S, needs-ok-to-test

#15906 Rollback ISO Go version and prevent automation from updating it
  Makefile
  deploy/iso/minikube-iso/go.hash
  hack/update/golang_version/update_golang_version.go
Labels: cncf-cla: yes, size/XS, approved

#15866 added detail json for addons
  cmd/minikube/cmd/config/addons_list.go
  pkg/minikube/tunnel/route_windows_test.go
Labels: cncf-cla: yes, size/S, ok-to-test

#15911 minikube service list: fix table format & hide URLs
  cmd/minikube/cmd/service_list.go
Labels: cncf-cla: yes, size/M, approved, ok-to-test

#15916 Fix french translation
  translations/fr.json
Labels: cncf-cla: yes, size/S, needs-ok-to-test

#15909 Add default cni logs to `minikbue logs`
  pkg/minikube/logs/logs.go
  test/integration/multinode_test.go
Labels: cncf-cla: yes, size/XS, approved, ok-to-test

#15933 site: Update GCP-Auth docs regarding new namespaces
  site/content/en/docs/handbook/addons/gcp-auth.md
Labels: cncf-cla: yes, size/XS, approved

#15932 Automate updating containerd, buildkit, and cri-o
  .github/workflows/update-buildkit-version.yml
  .github/workflows/update-containerd-version.yml
  .github/workflows/update-cri-o-version.yml
  Makefile
  hack/update/buildkit_version/update_buildkit_version.go
  hack/update/containerd_version/update_containerd_version.go
  hack/update/cri-o_version/update_cri-o_version.go
  hack/update/golang_version/update_golang_version.go
Labels: cncf-cla: yes, size/XL, approved
