Repository kubernetes/minikube, pull requests merged in 2023-07, with the labels that each got.

#16804 Use minikube-machine repository for drivers
  go.mod
  go.sum
Labels: cncf-cla: yes, size/S, approved, ok-to-test

#16811 Fix french translation
  translations/fr.json
Labels: cncf-cla: yes, size/S, needs-ok-to-test

#16765 ISO: Add nerdctl
  Makefile
  deploy/iso/minikube-iso/arch/aarch64/package/Config.in
  deploy/iso/minikube-iso/arch/aarch64/package/nerdctl-bin-aarch64/Config.in
  deploy/iso/minikube-iso/arch/aarch64/package/nerdctl-bin-aarch64/nerdctl-bin.hash
  deploy/iso/minikube-iso/arch/aarch64/package/nerdctl-bin-aarch64/nerdctl-bin.mk
  deploy/iso/minikube-iso/arch/x86_64/package/Config.in
  deploy/iso/minikube-iso/arch/x86_64/package/nerdctl-bin/Config.in
  deploy/iso/minikube-iso/arch/x86_64/package/nerdctl-bin/nerdctl-bin.hash
  deploy/iso/minikube-iso/arch/x86_64/package/nerdctl-bin/nerdctl-bin.mk
  pkg/minikube/download/iso.go
Labels: cncf-cla: yes, size/M, approved, ok-to-test

#16803 [zh-CN] Add translations of stop, status, delete, dashboard, pause, unpause
  translations/zh-CN.json
Labels: cncf-cla: yes, size/M, needs-ok-to-test

#16775 CI: Auto update nerdctl
  .github/workflows/update-nerdctl-version.yml
  Makefile
  hack/update/get_version/get_version.go
  hack/update/nerdctl_version/update_nerdctl_version.go
Labels: cncf-cla: yes, size/L, approved

#16833 CI: Skip remaining steps if no file changes
  .github/workflows/update-buildkit-version.yml
  .github/workflows/update-cni-plugins-version.yml
  .github/workflows/update-containerd-version.yml
  .github/workflows/update-cri-dockerd-version.yml
  .github/workflows/update-cri-o-version.yml
  .github/workflows/update-docker-buildx-version.yml
  .github/workflows/update-docker-version.yml
  .github/workflows/update-nerdctl-version.yml
  .github/workflows/update-runc-version.yml
  .github/workflows/update-ubuntu-version.yml
Labels: cncf-cla: yes, size/S, approved

#14996 Simplify containerd runtime configuration for gVisor
  Makefile
  deploy/addons/assets.go
  deploy/addons/gvisor/README.md
  deploy/addons/gvisor/gvisor-config.toml
  pkg/gvisor/disable.go
  pkg/gvisor/enable.go
  pkg/minikube/assets/addons.go
  pkg/minikube/constants/constants.go
  test/integration/gvisor_addon_test.go
  test/integration/testdata/nginx-untrusted.yaml
Labels: cncf-cla: yes, size/L, ok-to-test

#16844 CI: Exclude vedantmgoyal2009/winget-releaser from dependabot updates
  .github/dependabot.yml
Labels: cncf-cla: yes, size/XS, approved

#16836 translate some fields to chinese
  translations/zh-CN.json
Labels: cncf-cla: yes, size/S, needs-ok-to-test

#16848 [zh-CN] Add translations of image, ssh
  translations/zh-CN.json
Labels: cncf-cla: yes, size/M, approved, needs-ok-to-test

#16839 tunnel: Allow one tunnel per profile
  cmd/minikube/cmd/tunnel.go
Labels: cncf-cla: yes, size/XS, approved, ok-to-test

#16850 fix group message can't be translated
  cmd/minikube/cmd/root.go
Labels: cncf-cla: yes, size/XS, approved, needs-ok-to-test

#16853 Use the stable path for brew installed qemu firmware in machine config
  pkg/minikube/registry/drvs/qemu2/qemu2.go
Labels: cncf-cla: yes, size/S, approved, ok-to-test

#15452 feat: direct image build on containerd via docker-env
  cmd/minikube/cmd/docker-env.go
  cmd/minikube/cmd/ssh-host.go
  cmd/minikube/cmd/start.go
  deploy/kicbase/Dockerfile
  deploy/kicbase/nerdctld/nerdctld.service
  deploy/kicbase/nerdctld/nerdctld.socket
  pkg/drivers/kic/types.go
  pkg/minikube/reason/reason.go
  site/content/en/docs/commands/start.md
  site/content/en/docs/contrib/errorcodes.en.md
  site/content/en/docs/contrib/tests.en.md
  test/integration/docker_test.go
  test/integration/testdata/docker-env/Dockerfile
  translations/de.json
  translations/es.json
  translations/fr.json
  translations/ja.json
  translations/ko.json
  translations/pl.json
  translations/ru.json
  translations/strings.txt
  translations/zh-CN.json
Labels: cncf-cla: yes, size/L, approved, ok-to-test

#16789 QEMU: Unblock bootpd if start fails to due to blocking
  cmd/minikube/cmd/start.go
  pkg/drivers/qemu/qemu.go
  pkg/minikube/firewall/firewall.go
Labels: cncf-cla: yes, size/L, approved, ok-to-test

#16871 CI: Add id to create PR step
  .github/workflows/update-cri-dockerd-version.yml
Labels: cncf-cla: yes, size/XS, approved

#16862 Add more Chinese translations
  translations/zh-CN.json
Labels: cncf-cla: yes, size/S, needs-ok-to-test

#16796 feat: add VMware driver support for new minikube ISO
  cmd/minikube/cmd/start.go
  go.mod
  go.sum
Labels: cncf-cla: yes, size/S, approved, ok-to-test

#16852 fix subcommand cannot be translated
  cmd/minikube/cmd/root.go
Labels: cncf-cla: yes, size/S, needs-ok-to-test

#15868 Don't allow enabling addon on a paused cluster
  cmd/minikube/cmd/config/disable.go
  cmd/minikube/cmd/config/enable.go
  pkg/addons/addons.go
  pkg/minikube/reason/reason.go
Labels: cncf-cla: yes, size/M, lifecycle/stale, ok-to-test

#15519 `minikube cp` now supports providing directory as a target
  cmd/minikube/cmd/cp.go
  cmd/minikube/cmd/cp_test.go
Labels: cncf-cla: yes, size/M, approved, ok-to-test

#16882 translate some fields to chinese
  translations/zh-CN.json
Labels: cncf-cla: yes, size/S, needs-ok-to-test

#16891 [zh-CN] Add more translations
  translations/zh-CN.json
Labels: cncf-cla: yes, size/L, needs-ok-to-test

#16899 Release v1.31.0
  CHANGELOG.md
  Makefile
Labels: cncf-cla: yes, size/L, approved, ok-to-test

#16902 Fix french translation
  translations/fr.json
Labels: cncf-cla: yes, size/XS, needs-ok-to-test

#16912 cni: Fix regression in auto selection
  pkg/minikube/cni/cni.go
  pkg/minikube/cni/cni_test.go
Labels: cncf-cla: yes, size/M, approved, ok-to-test

#16915 Release v1.31.1
  CHANGELOG.md
  Makefile
  cmd/minikube/cmd/start.go
  cmd/minikube/cmd/start_test.go
Labels: cncf-cla: yes, size/M, approved, ok-to-test

#16932 site: typo
  site/content/en/docs/tutorials/kubernetes_101/module5.md
Labels: cncf-cla: yes, size/XS, approved, needs-ok-to-test

#16927 update zh_CN.json
  translations/zh-CN.json
Labels: cncf-cla: yes, size/S, needs-ok-to-test
