Repository kubernetes/minikube, pull requests merged in 2023-09, with the labels that each got.

#17163 Update Korean translation
  translations/ko.json
Labels: cncf-cla: yes, size/S, needs-ok-to-test

#17166 change terminology for "M1 Mac" to "Apple Silicon Mac" in translation
  pkg/minikube/reason/known_issues.go
  translations/de.json
  translations/es.json
  translations/fr.json
  translations/ja.json
  translations/ko.json
  translations/pl.json
  translations/ru.json
  translations/strings.txt
  translations/zh-CN.json
Labels: cncf-cla: yes, size/S, needs-ok-to-test

#17191 site: Update website deps
  site/package-lock.json
  site/package.json
Labels: cncf-cla: yes, size/XXL, approved

#17070 configure auto-pause-interval addon
  cmd/auto-pause/auto-pause.go
  cmd/minikube/cmd/config/configure.go
  cmd/minikube/cmd/start_flags.go
  pkg/minikube/config/types.go
  site/content/en/docs/commands/start.md
  translations/de.json
  translations/es.json
  translations/fr.json
  translations/ja.json
  translations/ko.json
  translations/pl.json
  translations/ru.json
  translations/strings.txt
  translations/zh-CN.json
Labels: cncf-cla: yes, size/M, approved, ok-to-test

#15585 Fix addon registry doesn't follow Minikube DNS domain name configuration (--dns-domain)
  deploy/addons/registry/registry-proxy.yaml.tmpl
  pkg/minikube/assets/addons.go
Labels: cncf-cla: yes, size/XS, approved, ok-to-test

#16064 registry-creds addon: Clarify when to use imagePullSecrets
  site/content/en/docs/tutorials/configuring_creds_for_aws_ecr.md
Labels: cncf-cla: yes, size/S, approved, needs-ok-to-test, lifecycle/rotten

#17186 Add some zh-CN translations
  translations/zh-CN.json
Labels: cncf-cla: yes, size/S, approved, needs-ok-to-test

#17220 set minimum minikube legacy version to v1.26.0 for containerd cri
  test/integration/version_upgrade_test.go
Labels: cncf-cla: yes, size/XS, approved, ok-to-test

#17214 Fix french translation
  translations/fr.json
Labels: cncf-cla: yes, size/XS, needs-ok-to-test

#16890 feat: allow delete-on-faliure in setupKubeAdm
  pkg/minikube/node/start.go
Labels: cncf-cla: yes, size/M, ok-to-test

#17165 Use minikube-machine repository for vmware driver
  go.mod
  go.sum
Labels: cncf-cla: yes, size/XS, approved

#17217 qemu: better cpu type and IP detection
  pkg/drivers/qemu/qemu.go
  pkg/minikube/registry/drvs/qemu2/qemu2.go
Labels: cncf-cla: yes, size/XS, ok-to-test

#17253 update zh-CN.json
  translations/zh-CN.json
Labels: cncf-cla: yes, size/S, approved, needs-ok-to-test

#17135 Upgrade Headlamp version to 0.19.1
  pkg/minikube/assets/addons.go
Labels: cncf-cla: yes, size/XS, ok-to-test

#17277 site: Update deploy an app
  site/content/en/docs/tutorials/kubernetes_101/module2.md
Labels: cncf-cla: no, size/XS, approved, needs-ok-to-test

#17116 Masking http(s)_proxy password from startup output.
  pkg/minikube/node/config.go
  pkg/minikube/node/config_test.go
  pkg/minikube/node/start.go
Labels: cncf-cla: yes, size/L, ok-to-test

#15927 container-runtime: add nvidia-docker
  pkg/minikube/cruntime/cruntime.go
  pkg/minikube/cruntime/cruntime_test.go
  pkg/minikube/cruntime/docker.go
Labels: cncf-cla: yes, size/M, ok-to-test

#17286 Revert "site: Update deploy an app"
  site/content/en/docs/tutorials/kubernetes_101/module2.md
Labels: cncf-cla: yes, size/XS, approved

#15062 Add `local-path-provisioner` addon
  deploy/addons/assets.go
  deploy/addons/storage-provisioner-rancher/storage-provisioner-rancher.yaml.tmpl
  pkg/addons/addons_storage_classes.go
  pkg/addons/config.go
  pkg/minikube/assets/addons.go
  site/content/en/docs/tutorials/local_path_provisioner.md
  test/integration/addons_test.go
  test/integration/testdata/storage-provisioner-rancher/pod.yaml
  test/integration/testdata/storage-provisioner-rancher/pvc.yaml
Labels: cncf-cla: yes, size/L, approved, ok-to-test

#17303 Update zh-CN.json Chinese translation
  translations/zh-CN.json
Labels: cncf-cla: yes, size/S, needs-ok-to-test
