Repository kubernetes/minikube, pull requests merged in 2023-06, with the labels that each got.

#16613 ISO: flannel cni-plugin removed
  Makefile
  deploy/iso/minikube-iso/arch/aarch64/package/cni-plugins-aarch64/cni-plugins.mk
  deploy/iso/minikube-iso/arch/x86_64/package/cni-plugins/cni-plugins.mk
  pkg/minikube/download/iso.go
Labels: cncf-cla: yes, size/S, approved, ok-to-test

#16579 docs: fix typo in ingress-dns.md
  site/content/en/docs/handbook/addons/ingress-dns.md
Labels: cncf-cla: yes, size/XS, approved, needs-ok-to-test

#16603 chore: io/ioutil deprecated
  third_party/kubeadm/app/constants/constants.go
Labels: cncf-cla: yes, size/XS, approved, ok-to-test

#16636 CI: Fix Ubuntu PR title
  hack/update/get_version/get_version.go
Labels: cncf-cla: yes, size/XS, approved

#16623 CI: Fix file change output
  .github/workflows/update-k8s-versions.yml
  .github/workflows/update-kubeadm-constants.yml
  .github/workflows/update-ubuntu-version.yml
Labels: cncf-cla: yes, size/XS, approved

#16610 CI: Automate updating Kubernetes versions list
  .github/workflows/update-kubernetes-versions-list.yml
  Makefile
  cmd/minikube/cmd/config/kubernetes_version.go
  hack/update/golang_version/update_golang_version.go
  hack/update/kubeadm_constants/update_kubeadm_constants.go
  hack/update/kubernetes_versions_list/update_kubernetes_versions_list.go
Labels: cncf-cla: yes, size/L, approved

#16609 Update addon owners
  cmd/minikube/cmd/config/enable.go
  pkg/minikube/assets/addons.go
Labels: cncf-cla: yes, size/S, approved

#16625 CI: Automate updating ingress images
  .github/workflows/update-ingress-version.yml
  Makefile
  hack/update/get_version/get_version.go
  hack/update/golang_version/update_golang_version.go
  hack/update/ingress_version/update_ingress_version.go
Labels: cncf-cla: yes, size/L, approved

#16637 CI: Remove duplicated golang update & fix newlines
  .github/workflows/docs.yml
  .github/workflows/leaderboard.yml
  .github/workflows/update-kubernetes-versions-list.yml
  hack/update/golang_version/update_golang_version.go
Labels: cncf-cla: yes, size/L, approved

#16641 CI: Automate updating flannel
  .github/workflows/update-flannel-version.yml
  Makefile
  hack/update/flannel_version/update_flannel_version.go
  hack/update/get_version/get_version.go
  hack/update/golang_version/update_golang_version.go
Labels: cncf-cla: yes, size/L, approved

#16640 CI: Automate updating calico
  .github/workflows/update-calico-version.yml
  Makefile
  hack/update/calico_version/update_calico_version.go
  hack/update/get_version/get_version.go
  hack/update/golang_version/update_golang_version.go
Labels: cncf-cla: yes, size/L, approved

#16648 Simplify QEMU socket_vmnet advice command
  pkg/minikube/reason/known_issues.go
  translations/de.json
  translations/es.json
  translations/fr.json
  translations/ja.json
  translations/ko.json
  translations/pl.json
  translations/ru.json
  translations/strings.txt
  translations/zh-CN.json
Labels: cncf-cla: yes, size/S, approved

#16577 addons registry: Use multi-arch kube-registry-proxy image
  pkg/minikube/assets/addons.go
Labels: cncf-cla: yes, size/XS, approved, ok-to-test

#16650 flake rate: Fix links always hardcoded to fail_
  hack/jenkins/test-flake-chart/flake_chart.js
Labels: cncf-cla: yes, size/S, approved

#16019 add ceph rbd kernel driver to arm iso
  Makefile
  deploy/iso/minikube-iso/board/minikube/aarch64/linux_aarch64_defconfig
  pkg/minikube/download/iso.go
Labels: cncf-cla: yes, size/XS, approved, ok-to-test

#16653 CI: Use last 90 days for flake issues
  hack/jenkins/test-flake-chart/compute_flake_rate.sh
Labels: cncf-cla: yes, size/XS, approved

#15887 Add ability to create extra disks on qemu2 vms
  cmd/minikube/cmd/start_flags.go
  pkg/drivers/common.go
  pkg/drivers/kvm/disks.go
  pkg/drivers/kvm/kvm.go
  pkg/drivers/qemu/qemu.go
  pkg/minikube/registry/drvs/qemu2/qemu2.go
  site/content/en/docs/commands/start.md
  translations/de.json
  translations/es.json
  translations/fr.json
  translations/ja.json
  translations/ko.json
  translations/pl.json
  translations/ru.json
  translations/strings.txt
  translations/zh-CN.json
Labels: cncf-cla: yes, size/L, approved, ok-to-test

#16654 TestPreload: Fix image list with cri-o CRI
  test/integration/preload_test.go
Labels: cncf-cla: yes, size/S, approved, ok-to-test

#15079 fix: quit minikube service when there is no available pods
  cmd/minikube/cmd/service.go
  pkg/minikube/reason/reason.go
  pkg/minikube/service/service.go
  site/content/en/docs/contrib/tests.en.md
  test/integration/functional_test.go
  test/integration/testdata/invalidsvc.yaml
  translations/de.json
  translations/es.json
  translations/fr.json
  translations/ja.json
  translations/ko.json
  translations/pl.json
  translations/ru.json
  translations/strings.txt
  translations/zh-CN.json
Labels: cncf-cla: yes, size/L, ok-to-test, do-not-merge/failing-test

#16578 fix: missing tags on images with multiple tags for minikube image list
  pkg/minikube/machine/cache_image_test.go
  pkg/minikube/machine/cache_images.go
Labels: cncf-cla: yes, size/L, ok-to-test

#16419 none driver: check for CNI plugins
  pkg/minikube/cruntime/containerd.go
  pkg/minikube/cruntime/cri.go
  pkg/minikube/cruntime/crio.go
  pkg/minikube/cruntime/docker.go
  pkg/minikube/machine/start.go
  pkg/minikube/reason/reason.go
  site/content/en/docs/contrib/errorcodes.en.md
  translations/de.json
  translations/es.json
  translations/fr.json
  translations/ja.json
  translations/ko.json
  translations/pl.json
  translations/ru.json
  translations/strings.txt
  translations/zh-CN.json
Labels: cncf-cla: yes, size/M, approved, ok-to-test

#16670 Remove the obsolete vmwarefusion driver
  cmd/minikube/cmd/start_test.go
  pkg/minikube/driver/driver.go
  pkg/minikube/driver/driver_darwin.go
  pkg/minikube/driver/driver_linux.go
  pkg/minikube/driver/driver_test.go
  pkg/minikube/driver/driver_windows.go
  pkg/minikube/machine/fix.go
  pkg/minikube/registry/drvs/init.go
  pkg/minikube/registry/drvs/vmwarefusion/doc.go
  pkg/minikube/registry/drvs/vmwarefusion/vmwarefusion.go
  site/content/en/docs/contrib/drivers.en.md
Labels: cncf-cla: yes, size/L, approved

#14689 Enable `CONFIG_PROC_CHILDREN` kernel configuration in Minikube ISO
  Makefile
  deploy/iso/minikube-iso/board/minikube/aarch64/linux_aarch64_defconfig
  deploy/iso/minikube-iso/board/minikube/x86_64/linux_x86_64_defconfig
  pkg/minikube/download/iso.go
Labels: cncf-cla: yes, size/XS, approved, ok-to-test

#16692 CI: Automate updating workflow files
  hack/update/golang_version/update_golang_version.go
Labels: cncf-cla: yes, size/M, approved

#16693 CI: Automate updating cri-dockerd
  .github/workflows/update-cri-dockerd-version.yml
  Makefile
  hack/update/cri_dockerd_version/build_and_upload_cri_dockerd_binaries.sh
  hack/update/cri_dockerd_version/update_cri_dockerd_version.go
  hack/update/get_version/get_version.go
Labels: cncf-cla: yes, size/L, approved

#16695 Skip waiting for kicbase downloads on VM drivers
  pkg/minikube/node/start.go
Labels: cncf-cla: yes, size/XS, approved, ok-to-test

#16694 CI: Automate updating go-github
  .github/workflows/update-go-github-version.yml
  Makefile
  hack/update/get_version/get_version.go
  hack/update/go_github_version/update_go_github_version.go
Labels: cncf-cla: yes, size/L, approved

#16702 CI: Fix cri-dockerd Dockerfile update
  hack/update/cri_dockerd_version/update_cri_dockerd_version.go
Labels: cncf-cla: yes, size/XS, approved

#15164 Add CONFIG_BPF_SYSCALL=y to aarch64 config
  Makefile
  deploy/iso/minikube-iso/board/minikube/aarch64/linux_aarch64_defconfig
  pkg/minikube/download/iso.go
Labels: cncf-cla: yes, size/XS, approved, ok-to-test

#14437 Document .localhost usage
  site/content/en/docs/handbook/addons/ingress-dns.md
Labels: cncf-cla: yes, size/XS, approved, needs-ok-to-test

#14780 Always use cni unless running with dockershim
  pkg/minikube/cni/cni.go
  site/content/en/docs/drivers/includes/none_usage.inc
  site/content/en/docs/drivers/includes/ssh_usage.inc
  test/integration/net_test.go
Labels: cncf-cla: yes, size/M, approved, ok-to-test

#14868 Fix kubectl tab-completion and improve error messages
  cmd/minikube/cmd/kubectl.go
Labels: cncf-cla: yes, size/S, approved, ok-to-test

#15003 Fix to prevent accepting addons flag when no kubernetes
  cmd/minikube/cmd/config/enable.go
  cmd/minikube/cmd/start.go
  translations/de.json
  translations/es.json
  translations/fr.json
  translations/ja.json
  translations/ko.json
  translations/pl.json
  translations/ru.json
  translations/strings.txt
  translations/zh-CN.json
Labels: cncf-cla: yes, size/M, ok-to-test

#16704 CI: Cancel build if ISO changes are out of date
  hack/jenkins/build_iso.sh
Labels: cncf-cla: yes, size/S, approved

#15665 Added geneve as a kernel module in minikube ISO
  Makefile
  deploy/iso/minikube-iso/board/minikube/aarch64/linux_aarch64_defconfig
  deploy/iso/minikube-iso/board/minikube/x86_64/linux_x86_64_defconfig
  pkg/minikube/download/iso.go
Labels: cncf-cla: yes, size/XS, approved, ok-to-test

#16711 fix legacy in test missing container
  test/integration/version_upgrade_test.go
Labels: cncf-cla: yes, size/XS, approved, ok-to-test

#16687 Use a built-in version of the vmware driver
  pkg/minikube/registry/drvs/vmware/vmware.go
Labels: cncf-cla: yes, size/S, approved, ok-to-test

#16611 chore: use log.Printf
  third_party/go9p/clnt_clnt.go
  third_party/go9p/srv_conn.go
Labels: cncf-cla: yes, size/XS, approved, needs-ok-to-test

#16712 Add CONFIG_BINFMT_MISC=y flag
  Makefile
  deploy/iso/minikube-iso/board/minikube/aarch64/linux_aarch64_defconfig
  deploy/iso/minikube-iso/board/minikube/x86_64/linux_x86_64_defconfig
  pkg/minikube/download/iso.go
Labels: cncf-cla: yes, size/XS, approved, ok-to-test

#16724 Add more translations
  translations/zh-CN.json
Labels: cncf-cla: yes, size/M, needs-ok-to-test

#16757 site: Update fix for dhcpd_leases issue
  site/content/en/docs/drivers/qemu.md
Labels: cncf-cla: yes, size/S, approved

#16754 site: Update docs on running macOS minikube-gui
  site/content/en/docs/tutorials/setup_minikube_gui.md
  site/static/images/gui/mac.png
Labels: cncf-cla: yes, size/XS, approved

#16714 qemu on maos :Auto unblock bootpd from firewall for socket_vmnet network driver
  cmd/minikube/cmd/start.go
Labels: cncf-cla: yes, size/M, approved, ok-to-test

#16752 site: Added missing Docker_Linux_containerd_arm64 from flake table
  site/content/en/docs/contrib/test_flakes.en.md
Labels: cncf-cla: yes, size/XS, approved

#16751 fix: missing quotes in german translation
  translations/de.json
Labels: cncf-cla: yes, size/XS, needs-ok-to-test

#16672 Replace machine-drivers with minikube-machine
  go.mod
  go.sum
Labels: cncf-cla: yes, size/XS, approved, ok-to-test

#16774 CI: Fix cri-dockerd adding existing hash
  hack/update/cri_dockerd_version/update_cri_dockerd_version.go
Labels: cncf-cla: yes, size/XS, approved

#16230 Update Japanese translation
  translations/ja.json
Labels: cncf-cla: yes, size/M, lgtm, approved

#16782 fix function name in comment
  cmd/minikube/cmd/docker-env.go
  pkg/drivers/kic/oci/info.go
  pkg/drivers/kic/oci/network_create.go
  pkg/minikube/bootstrapper/kubeadm/kubeadm.go
Labels: cncf-cla: yes, size/XS, needs-ok-to-test

#16791 CI: Small GitHub Workflow fixes
  .github/workflows/update-cri-dockerd-version.yml
  .github/workflows/update-go-github-version.yml
Labels: cncf-cla: yes, size/S, approved

#16794 CI: Auto update docker-buildx
  .github/workflows/update-docker-buildx-version.yml
  Makefile
  hack/update/docker_buildx_version/update_docker_buildx_version.go
Labels: cncf-cla: yes

#16764 Add minikube -h,minikube start -h translations
  translations/zh-CN.json
Labels: cncf-cla: yes, size/L, needs-ok-to-test

#16761 Add ability to start & stop ssh-agent process
  cmd/minikube/cmd/delete.go
  cmd/minikube/cmd/docker-env.go
  cmd/minikube/cmd/docker-env_test.go
  pkg/minikube/config/types.go
  pkg/minikube/constants/constants.go
  pkg/minikube/sshagent/sshagent.go
Labels: cncf-cla: yes, size/L, approved, ok-to-test

#14321 automate publishing to winget
  .github/workflows/winget.yml
Labels: cncf-cla: yes, size/S, needs-ok-to-test, kind/process
