Repository kubernetes/minikube, pull requests merged in 2023-03, with the labels that each got.

#15939 Bump github.com/containerd/containerd from 1.6.16 to 1.6.19
  go.mod
  go.sum
Labels: cncf-cla: yes, size/M, approved, ok-to-test

#15940 Update kindnetd image and entrypoint
  deploy/kicbase/entrypoint
  pkg/minikube/bootstrapper/images/images.go
Labels: cncf-cla: yes, size/S, approved, ok-to-test

#15944 CI: Windows Docker setup fixes
  hack/jenkins/common.ps1
Labels: cncf-cla: yes, size/S, approved, ok-to-test

#15954 CI: Fix Windows Issues
  hack/jenkins/common.ps1
  hack/jenkins/installers/check_install_golang.ps1
  hack/update/golang_version/update_golang_version.go
  hack/update/gopogh_version/update_gopogh_version.go
  hack/update/gotestsum_version/update_gotestsum_version.go
Labels: cncf-cla: yes, size/M, approved

#15955 CI: Install gopogh via go install
  .github/workflows/functional_verified.yml
  .github/workflows/master.yml
  .github/workflows/pr.yml
  hack/jenkins/common.sh
  hack/update/gopogh_version/update_gopogh_version.go
Labels: cncf-cla: yes, size/M, approved

#15957 site: Update minikube-gui docs to use new binaries
  site/content/en/docs/tutorials/setup_minikube_gui.md
  site/static/images/gui/mac.png
Labels: cncf-cla: yes, size/M, approved

#15962 CI: remove old gopogh & gotestsum installs
  hack/jenkins/common.ps1
  hack/jenkins/common.sh
Labels: cncf-cla: yes, size/XS, approved

#15923 ISO/Kicbase: Update containerd from 1.6.15 to 1.6.18
  Makefile
  deploy/iso/minikube-iso/arch/aarch64/package/containerd-bin-aarch64/containerd-bin.hash
  deploy/iso/minikube-iso/arch/aarch64/package/containerd-bin-aarch64/containerd-bin.mk
  deploy/iso/minikube-iso/arch/x86_64/package/containerd-bin/containerd-bin.hash
  deploy/iso/minikube-iso/arch/x86_64/package/containerd-bin/containerd-bin.mk
  pkg/drivers/kic/types.go
  pkg/minikube/download/iso.go
  site/content/en/docs/commands/start.md
Labels: cncf-cla: yes, size/S, approved, ok-to-test

#15961 tests: Split up ServiceCmd test into sub-tests and fix on Windows
  site/content/en/docs/contrib/tests.en.md
  test/integration/functional_test.go
Labels: cncf-cla: yes, size/L, approved, ok-to-test

#15990 CI: stagger update crons
  .github/workflows/update-buildkit-version.yml
  .github/workflows/update-containerd-version.yml
  .github/workflows/update-cri-o-version.yml
Labels: cncf-cla: yes, size/S, approved

#16000 site: update GUI docs for macOS
  site/content/en/docs/tutorials/setup_minikube_gui.md
Labels: cncf-cla: yes, size/XS, approved

#15995 Upgrade Headlamp version to 0.15.1
  pkg/minikube/assets/addons.go
Labels: cncf-cla: yes, size/XS, ok-to-test

#16012 Addons: Update GCP-Auth from v0.0.13 to v0.0.14
  pkg/minikube/assets/addons.go
Labels: cncf-cla: yes, size/XS, approved, ok-to-test

#16010 test: Fix having to change test byte size on new addon
  cmd/minikube/cmd/config/addons_list_test.go
Labels: cncf-cla: yes, size/XS, approved

#15989 CI: update cri-o automation to update Dockerfile version
  hack/update/cri-o_version/update_cri-o_version.go
Labels: cncf-cla: yes, size/S, approved

#15984 Fix image related bugs when enabling addons
  cmd/minikube/cmd/config/enable.go
  pkg/minikube/assets/addons.go
  pkg/minikube/assets/addons_test.go
Labels: cncf-cla: yes, size/L, approved, ok-to-test

#16025 Addons: Update auto-pause from v0.0.3 to v0.0.4
  Makefile
  pkg/minikube/assets/addons.go
Labels: cncf-cla: yes, size/XS, approved

#16024 CI: remove ok-to-test labels
  .github/dependabot.yml
  .github/workflows/update-docsy-version.yml
  .github/workflows/update-gh-version.yml
  .github/workflows/update-golint-version.yml
  .github/workflows/update-gopogh-version.yml
  .github/workflows/update-gotestsum-version.yml
  .github/workflows/update-hugo-version.yml
  .github/workflows/update-kubeadm-constants.yml
Labels: cncf-cla: yes, size/S, approved

#15985 GCP-Auth: Add fixes and timeouts
  pkg/addons/addons.go
  pkg/addons/addons_gcpauth.go
  pkg/addons/kubectl.go
  pkg/addons/kubectl_test.go
Labels: cncf-cla: yes, size/M, approved, ok-to-test

#15685 feat: Add kicbase download progress to JSON output
  pkg/minikube/download/image.go
Labels: cncf-cla: yes, size/M, needs-ok-to-test

#15991 kicbase: update Ubuntu base image
  deploy/kicbase/Dockerfile
  pkg/drivers/kic/types.go
  site/content/en/docs/commands/start.md
Labels: cncf-cla: yes, size/XS, approved, ok-to-test

#16046 CI: add workflow to hide past minikube-bot comments
  .github/workflows/hide-minikube-bot-comments.yml
Labels: cncf-cla: yes, size/XS, approved

#16056 metallb addon: fix docker.io dependency and move to quay.io
  pkg/minikube/assets/addons.go
Labels: cncf-cla: yes, size/XS, ok-to-test

#16057 CI: pass token to minikube-bot minimizing action
  .github/workflows/hide-minikube-bot-comments.yml
Labels: cncf-cla: yes, size/XS, approved

#16065 Upgrade Headlamp version to 0.16.0
  pkg/minikube/assets/addons.go
Labels: cncf-cla: yes, size/XS, ok-to-test

#16070 CI: Fix force pushing
  .github/workflows/docs.yml
  .github/workflows/master.yml
  .github/workflows/pr.yml
  .github/workflows/sync-minikube.yml
  .github/workflows/time-to-k8s.yml
  .github/workflows/update-buildkit-version.yml
  .github/workflows/update-containerd-version.yml
  .github/workflows/update-cri-o-version.yml
  .github/workflows/update-golang-version.yml
  .github/workflows/yearly-leaderboard.yml
Labels: cncf-cla: yes, size/L, approved

#16072 Translate some fields
  translations/zh-CN.json
Labels: cncf-cla: yes, size/S, approved, needs-ok-to-test

#16068 kicbase: Update Ubuntu base image
  deploy/kicbase/Dockerfile
  pkg/drivers/kic/types.go
  site/content/en/docs/commands/start.md
Labels: cncf-cla: yes, size/XS, approved, ok-to-test

#16081 Add solution message for cpu controller delegation
  pkg/minikube/reason/known_issues.go
Labels: cncf-cla: yes, size/S, approved, ok-to-test

#16109 tests: Fix unit test failing if docker not running
  pkg/drivers/kic/oci/info.go
  pkg/minikube/registry/drvs/docker/docker_test.go
Labels: cncf-cla: yes, size/XS, approved

#16107 CI: remove setup-go cache true lines
  .github/workflows/build.yml
  .github/workflows/docs.yml
  .github/workflows/functional_verified.yml
  .github/workflows/leaderboard.yml
  .github/workflows/master.yml
  .github/workflows/pr.yml
  .github/workflows/sync-minikube.yml
  .github/workflows/time-to-k8s-public-chart.yml
  .github/workflows/time-to-k8s.yml
  .github/workflows/translations.yml
  .github/workflows/update-buildkit-version.yml
  .github/workflows/update-cloud-spanner-emulator-version.yml
  .github/workflows/update-containerd-version.yml
  .github/workflows/update-cri-o-version.yml
  .github/workflows/update-docsy-version.yml
  .github/workflows/update-gh-version.yml
  .github/workflows/update-golang-version.yml
  .github/workflows/update-golint-version.yml
  .github/workflows/update-gopogh-version.yml
  .github/workflows/update-gotestsum-version.yml
  .github/workflows/update-hugo-version.yml
  .github/workflows/update-k8s-versions.yml
  .github/workflows/update-kubeadm-constants.yml
  .github/workflows/yearly-leaderboard.yml
Labels: cncf-cla: yes, size/M, approved

#14703 Handle CRI config of NetworkPlugin and PauseImage
  pkg/minikube/bootstrapper/bsutil/kubelet.go
  pkg/minikube/cruntime/cruntime.go
  pkg/minikube/cruntime/docker.go
  pkg/minikube/node/start.go
Labels: cncf-cla: yes, size/M, approved, ok-to-test

#16127 Fix Typo in German translation
  translations/de.json
Labels: cncf-cla: yes, size/XS, needs-ok-to-test

#16001 wait for pods to get IPs
  test/integration/multinode_test.go
Labels: cncf-cla: yes, size/M, approved, ok-to-test

#16124 Remove container-runtime flag from later versions
  pkg/minikube/cruntime/containerd.go
  pkg/minikube/cruntime/cri.go
  pkg/minikube/cruntime/crio.go
  pkg/minikube/cruntime/cruntime_test.go
  pkg/minikube/cruntime/docker.go
Labels: cncf-cla: yes, size/M, approved, ok-to-test

#16132 CI: Auto update metrics-server addon
  .github/workflows/update-metrics-server-version.yml
  Makefile
  hack/update/golang_version/update_golang_version.go
  hack/update/metrics_server_version/update_metrics_server_version.go
Labels: cncf-cla: yes, size/L, approved

#16135 Revert "Add shell completion for minikube kubectl subcommand"
  cmd/minikube/cmd/kubectl.go
  go.mod
  go.sum
Labels: cncf-cla: yes, size/L, approved, ok-to-test

#16091 fix(sec): upgrade golang.org/x/image to 0.5.0
  go.mod
  go.sum
Labels: cncf-cla: yes, size/XS, approved, needs-ok-to-test

#15834 Ensure only one instance of tunnel process runs
  cmd/minikube/cmd/tunnel.go
  pkg/minikube/reason/reason.go
  site/content/en/docs/contrib/errorcodes.en.md
  site/content/en/docs/contrib/tests.en.md
  test/integration/functional_test_tunnel_test.go
  translations/de.json
  translations/es.json
  translations/fr.json
  translations/ja.json
  translations/ko.json
  translations/pl.json
  translations/ru.json
  translations/strings.txt
  translations/zh-CN.json
Labels: cncf-cla: yes, size/L, ok-to-test

#16150 CI: fix restarting Docker macOS
  hack/jenkins/setup_docker_desktop_macos.sh
Labels: cncf-cla: yes, size/XS, approved

#16152 CI: only setup docker if using docker driver
  hack/jenkins/common.sh
Labels: cncf-cla: yes, size/XS, approved

#16170 CI: remove test_summary.json
  hack/jenkins/common.sh
Labels: cncf-cla: yes, size/XS, approved

#16151 CI: update GitHub Actions runners
  .github/workflows/functional_verified.yml
Labels: cncf-cla: yes, size/XS, approved

#16139 Fix: check if addon is enabled before doing validation
  cmd/minikube/cmd/config/disable.go
  test/integration/addons_test.go
  translations/de.json
  translations/es.json
  translations/fr.json
  translations/ja.json
  translations/ko.json
  translations/pl.json
  translations/ru.json
  translations/strings.txt
  translations/zh-CN.json
Labels: cncf-cla: yes, size/M, ok-to-test

#16174 none driver: don't check for kicbase/ISO version
  cmd/minikube/cmd/start.go
Labels: cncf-cla: yes, size/XS, approved

#16171 CI: restart Windows if Docker fails to start
  hack/jenkins/common.ps1
Labels: cncf-cla: yes, size/S, approved

#16120 Add provided message to output
  pkg/minikube/exit/exit.go
Labels: cncf-cla: yes, size/XS, approved, ok-to-test

#16186 CI: Always require Docker to be running
  hack/jenkins/common.ps1
  hack/jenkins/common.sh
Labels: cncf-cla: yes, size/M, approved

#16179 addons: Update ingress addon images
  pkg/minikube/assets/addons.go
Labels: cncf-cla: yes, size/S, approved, ok-to-test

#16190 CI: cron to auto update runc
  .github/workflows/update-runc-version.yml
  Makefile
  deploy/iso/minikube-iso/package/runc-master/runc-master.mk
  hack/update/golang_version/update_golang_version.go
  hack/update/runc_version/update_runc_version.go
Labels: cncf-cla: yes, size/L, approved

#16193 CI: add cron to kicbase & ISO build machines
  hack/jenkins/build_iso.sh
  hack/jenkins/installers/check_install_linux_crons.sh
  hack/jenkins/kicbase_auto_build.sh
Labels: cncf-cla: yes, size/XS, approved

#16192 site: update triage hours
  site/content/en/docs/contrib/triage.md
Labels: cncf-cla: yes, size/XS, approved

#16029 Always use the new registry.k8s.io repository
  pkg/minikube/bootstrapper/images/images.go
  pkg/minikube/bootstrapper/images/images_test.go
  pkg/minikube/bootstrapper/images/kubeadm_test.go
  pkg/minikube/bootstrapper/images/repo.go
  pkg/minikube/bootstrapper/images/repo_test.go
  pkg/minikube/node/start.go
  test/integration/start_stop_delete_test.go
Labels: cncf-cla: yes, size/L, approved, ok-to-test

#16199 GCP-Auth: update kube-webhook-certgen image
  pkg/minikube/assets/addons.go
Labels: cncf-cla: yes, size/XS, approved, ok-to-test
