Repository kubernetes/minikube, pull requests merged in 2023-11, with the labels that each got.

#17530 Fix no-limit option for config validation
  cmd/minikube/cmd/config/validations.go
  cmd/minikube/cmd/config/validations_test.go
Labels: cncf-cla: yes, size/M, approved, ok-to-test

#17516 Kicbase: Install NVIDIA container toolkit during image build
  cmd/minikube/cmd/start.go
  deploy/kicbase/Dockerfile
  pkg/drivers/kic/types.go
  pkg/minikube/cruntime/docker.go
  site/content/en/docs/commands/start.md
  translations/de.json
  translations/es.json
  translations/ja.json
  translations/ko.json
  translations/pl.json
  translations/ru.json
  translations/strings.txt
  translations/zh-CN.json
Labels: cncf-cla: yes, size/M, approved, ok-to-test

#17296 Fix orthographic mistake in de.json
  translations/de.json
Labels: cncf-cla: yes, size/XS, needs-ok-to-test

#17566 Fix french translation
  translations/fr.json
Labels: cncf-cla: yes, size/XS, needs-ok-to-test

#17585 Release v1.32.0
  CHANGELOG.md
  Makefile
Labels: cncf-cla: yes, size/M, approved, ok-to-test

#17575 Minor Spelling Correction in module2.md
  site/content/en/docs/tutorials/kubernetes_101/module2.md
Labels: cncf-cla: yes, size/XS, needs-ok-to-test

#17558 Update benchmarkingprocess.md
  site/content/en/docs/benchmarks/imageBuild/benchmarkingprocess.md
Labels: cncf-cla: yes, size/XS, approved, needs-ok-to-test

#17586 Upgrade Headlamp version to 0.21.0
  pkg/minikube/assets/addons.go
Labels: cncf-cla: yes, size/XS, approved, ok-to-test

#17598 Fix no-limit not being respected on restart
  cmd/minikube/cmd/start_flags.go
Labels: cncf-cla: yes, size/XS, approved, ok-to-test

#17497 Add more Chinese translations
  translations/zh-CN.json
Labels: cncf-cla: yes, size/S, needs-ok-to-test

#17656 CI: Fix HyperKit failing to start
  hack/jenkins/common.sh
Labels: cncf-cla: yes, size/XS, approved, ok-to-test

#17601 Fix ingress-dns.md instructions
  site/content/en/docs/handbook/addons/ingress-dns.md
Labels: cncf-cla: yes, size/XS, ok-to-test

#17671 fix containerd ImageExists to look for image name and image id sha
  pkg/minikube/cruntime/containerd.go
Labels: cncf-cla: yes, size/S, approved, ok-to-test

#17659 Add journalctl logs to failed systemctl commands
  pkg/minikube/sysinit/systemd.go
Labels: cncf-cla: yes, size/S, approved, ok-to-test

#17660 Update zh-CN.json Chinese translation
  translations/zh-CN.json
Labels: cncf-cla: yes, size/S, needs-ok-to-test

#17553 fix: add 20s timeout to driver status check
  pkg/minikube/driver/driver.go
  pkg/minikube/registry/global.go
Labels: cncf-cla: yes, size/M, ok-to-test

#17688 Add link to podman for macos and windows
  site/content/en/docs/drivers/_index.md
Labels: cncf-cla: yes, size/XS, approved

#17690 Fix TestEnable unit test
  pkg/minikube/cruntime/cruntime_test.go
Labels: cncf-cla: yes, size/S, approved
