Repository kubernetes/minikube, pull requests merged in 2023-05, with the labels that each got.

#16249 Renew expired kubeadm certs
  pkg/minikube/bootstrapper/bsutil/files.go
  pkg/minikube/bootstrapper/certs.go
  pkg/minikube/bootstrapper/certs_test.go
  pkg/minikube/bootstrapper/kubeadm/kubeadm.go
  pkg/minikube/constants/constants.go
  translations/de.json
  translations/es.json
  translations/fr.json
  translations/ja.json
  translations/ko.json
  translations/pl.json
  translations/ru.json
  translations/strings.txt
  translations/zh-CN.json
Labels: cncf-cla: yes, size/M, approved, ok-to-test

#16409 CI: Automate ubuntu version update #15772
  .github/workflows/update-ubuntu-version.yml
  Makefile
  deploy/kicbase/Dockerfile
  hack/update/golang_version/update_golang_version.go
  hack/update/ubuntu_version/update_ubuntu_version.go
Labels: cncf-cla: yes, size/L, needs-ok-to-test

#16074 CNI: Update flannel from v0.20.2 to v0.21.4 and change repository
  pkg/minikube/cni/flannel.yaml
Labels: cncf-cla: yes, size/S, approved, ok-to-test

#16395 Fix csi hostpath custom registry error
  deploy/addons/csi-hostpath-driver/deploy/csi-hostpath-plugin.yaml.tmpl
Labels: cncf-cla: yes, size/XS, approved, needs-ok-to-test

#16424 [Addon] Update Kong Ingress Controller Addon to 2.9.x/Kong 3.2.x
  deploy/addons/kong/kong-ingress-controller.yaml.tmpl
  pkg/minikube/assets/addons.go
  site/content/en/docs/handbook/addons/kong-ingress.md
Labels: cncf-cla: yes, size/XL, approved, ok-to-test

#16452 Cache command deprecation notification
  site/content/en/docs/commands/cache.md
Labels: cncf-cla: yes, size/XS, needs-ok-to-test

#16429 site: add latest talk
  site/content/en/docs/presentations/_index.md
Labels: cncf-cla: yes, size/XS, approved

#16413 addons: Fix file permissions
  pkg/minikube/assets/addons.go
Labels: cncf-cla: yes, size/S, approved

#16408 Fix `minikube start` not working without `sudo` on none driver
  .github/workflows/master.yml
  .github/workflows/pr.yml
  Makefile
  hack/jenkins/common.sh
  hack/jenkins/linux_integration_tests_none.sh
  pkg/minikube/command/command_runner.go
  pkg/minikube/command/exec_runner.go
  site/content/en/docs/drivers/includes/none_usage.inc
  site/content/en/docs/drivers/none.md
  test/integration/none_test.go
  test/integration/version_upgrade_test.go
Labels: cncf-cla: yes, size/M, approved, ok-to-test

#16386 none driver: fix image build
  cmd/minikube/cmd/start.go
  cmd/minikube/cmd/start_flags.go
  pkg/minikube/node/node.go
Labels: cncf-cla: yes, size/S, approved, do-not-merge/hold, ok-to-test

#16317 site: Kubernetes 101 tutorial
  site/content/en/docs/tutorials/kubernetes_101/_index.md
  site/content/en/docs/tutorials/kubernetes_101/module1.md
  site/content/en/docs/tutorials/kubernetes_101/module2.md
  site/content/en/docs/tutorials/kubernetes_101/module3.md
  site/content/en/docs/tutorials/kubernetes_101/module4.md
  site/content/en/docs/tutorials/kubernetes_101/module5.md
  site/content/en/docs/tutorials/kubernetes_101/module6.md
  site/layouts/partials/hooks/head-end.html
  site/layouts/shortcodes/button.html
  site/static/css/button.css
Labels: cncf-cla: yes, size/XL, approved

#16462 Add old and new version to 'update-ubuntu-version' automation
  .github/workflows/update-ubuntu-version.yml
  hack/update/get_version/get_version.go
Labels: cncf-cla: yes, size/XS, approved, needs-ok-to-test

#16470 Revert "Update go from 1.20.3 to 1.20.4"
  .github/workflows/build.yml
  .github/workflows/docs.yml
  .github/workflows/functional_verified.yml
  .github/workflows/leaderboard.yml
  .github/workflows/master.yml
  .github/workflows/pr.yml
  .github/workflows/sync-minikube.yml
  .github/workflows/time-to-k8s-public-chart.yml
  .github/workflows/time-to-k8s.yml
  .github/workflows/translations.yml
  .github/workflows/update-buildkit-version.yml
  .github/workflows/update-cloud-spanner-emulator-version.yml
  .github/workflows/update-containerd-version.yml
  .github/workflows/update-cri-o-version.yml
  .github/workflows/update-docker-version.yml
  .github/workflows/update-docsy-version.yml
  .github/workflows/update-gh-version.yml
  .github/workflows/update-golang-version.yml
  .github/workflows/update-golint-version.yml
  .github/workflows/update-gopogh-version.yml
  .github/workflows/update-gotestsum-version.yml
  .github/workflows/update-hugo-version.yml
  .github/workflows/update-k8s-versions.yml
  .github/workflows/update-kubeadm-constants.yml
  .github/workflows/update-metrics-server-version.yml
  .github/workflows/update-runc-version.yml
  .github/workflows/update-ubuntu-version.yml
  .github/workflows/yearly-leaderboard.yml
  Makefile
  deploy/addons/auto-pause/Dockerfile
  deploy/iso/minikube-iso/go.hash
  deploy/kicbase/Dockerfile
  hack/jenkins/installers/check_install_golang.ps1
  hack/jenkins/installers/check_install_golang.sh
Labels: cncf-cla: yes, size/M, approved

#16471 site: improve none docs
  site/content/en/docs/drivers/includes/none_usage.inc
  site/content/en/docs/faq/_index.md
Labels: cncf-cla: yes, size/S, approved

#16473 Update CHANGELOG.md
  CHANGELOG.md
Labels: cncf-cla: yes, size/XS, approved, needs-ok-to-test

#16180 ISO: Bump Go from 1.19.6 to 1.19.9
  Makefile
  deploy/iso/minikube-iso/go.hash
  pkg/minikube/download/iso.go
Labels: cncf-cla: yes, size/S, approved, ok-to-test

#16479 CI: fix kube-cross registry
  Makefile
Labels: cncf-cla: yes, size/XS, approved

#16482 CI: include all environments in flake comments
  hack/jenkins/test-flake-chart/compute_flake_rate.go
  hack/jenkins/test-flake-chart/report_flakes.sh
Labels: cncf-cla: yes, size/S, approved

#16453 Fix not prepending `unix://` to CRI socket
  hack/update/kubernetes_version/templates/v1beta3/containerd-api-port.yaml
  hack/update/kubernetes_version/templates/v1beta3/containerd-pod-network-cidr.yaml
  hack/update/kubernetes_version/templates/v1beta3/containerd.yaml
  hack/update/kubernetes_version/templates/v1beta3/crio-options-gates.yaml
  hack/update/kubernetes_version/templates/v1beta3/crio.yaml
  hack/update/kubernetes_version/templates/v1beta3/default.yaml
  hack/update/kubernetes_version/templates/v1beta3/dns.yaml
  hack/update/kubernetes_version/templates/v1beta3/image-repository.yaml
  hack/update/kubernetes_version/templates/v1beta3/options.yaml
  pkg/minikube/bootstrapper/bsutil/ktmpl/v1beta3.go
  pkg/minikube/bootstrapper/bsutil/kubeadm.go
  pkg/minikube/bootstrapper/bsutil/testdata/v1.24/containerd-api-port.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.24/containerd-pod-network-cidr.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.24/containerd.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.24/crio-options-gates.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.24/crio.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.24/default.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.24/dns.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.24/image-repository.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.24/options.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.25/containerd-api-port.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.25/containerd-pod-network-cidr.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.25/containerd.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.25/crio-options-gates.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.25/crio.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.25/default.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.25/dns.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.25/image-repository.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.25/options.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.26/containerd-api-port.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.26/containerd-pod-network-cidr.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.26/containerd.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.26/crio-options-gates.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.26/crio.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.26/default.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.26/dns.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.26/image-repository.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.26/options.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.27/containerd-api-port.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.27/containerd-pod-network-cidr.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.27/containerd.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.27/crio-options-gates.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.27/crio.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.27/default.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.27/dns.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.27/image-repository.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.27/options.yaml
Labels: cncf-cla: yes, size/M, approved, ok-to-test

#16435 flannel CNI: Update from v0.21.4 to v0.21.5
  pkg/minikube/cni/flannel.yaml
Labels: cncf-cla: yes, size/S, approved, ok-to-test

#16487 use dl.k8s.io, not kubernetes-release bucket
  hack/jenkins/installers/check_install_docker.sh
Labels: cncf-cla: yes, size/XS, approved, kind/cleanup, ok-to-test, kind/deprecation

#15869 Addon: add inspektor-gadget
  deploy/addons/assets.go
  deploy/addons/inspektor-gadget/ig-clusterrole.yaml
  deploy/addons/inspektor-gadget/ig-clusterrolebinding.yaml
  deploy/addons/inspektor-gadget/ig-crd.yaml
  deploy/addons/inspektor-gadget/ig-daemonset.yaml.tmpl
  deploy/addons/inspektor-gadget/ig-namespace.yaml
  deploy/addons/inspektor-gadget/ig-role.yaml
  deploy/addons/inspektor-gadget/ig-rolebinding.yaml
  deploy/addons/inspektor-gadget/ig-serviceaccount.yaml
  pkg/addons/config.go
  pkg/minikube/assets/addons.go
  site/content/en/docs/contrib/tests.en.md
  site/content/en/docs/handbook/addons/inspektor-gadget.md
  test/integration/addons_test.go
Labels: cncf-cla: yes, size/L, approved, ok-to-test

#16491 test: Updated skaffold test to help prevent Docker Hub pull limit
  test/integration/testdata/skaffold/base/Dockerfile
  test/integration/testdata/skaffold/leeroy-app/Dockerfile
  test/integration/testdata/skaffold/leeroy-app/go.mod
  test/integration/testdata/skaffold/leeroy-app/kubernetes/deployment.yaml
  test/integration/testdata/skaffold/leeroy-web/Dockerfile
  test/integration/testdata/skaffold/leeroy-web/go.mod
  test/integration/testdata/skaffold/skaffold.yaml
Labels: cncf-cla: yes, size/M, approved, ok-to-test

#16509 Update CHANGELOG.md
  CHANGELOG.md
Labels: cncf-cla: yes, size/XS, needs-ok-to-test

#16492 testing: added Setup subtest for ImageBuild
  site/content/en/docs/contrib/tests.en.md
  test/integration/image_test.go
Labels: cncf-cla: yes, size/S, approved, ok-to-test

#16489 testing: Use GCR image to prevent Docker Hub rate limits
  test/integration/testdata/image-build/test-arg/Dockerfile
  test/integration/testdata/image-build/test-env/Dockerfile
  test/integration/testdata/image-build/test-f/inner/Dockerfile
  test/integration/testdata/image-build/test-ignore/Dockerfile
  test/integration/testdata/image-build/test-normal/Dockerfile
Labels: cncf-cla: yes, size/S, approved, ok-to-test

#16488 CNI kindnet: Update from v20230330-48f316cd to v20230511-dc714da8
  pkg/minikube/bootstrapper/images/images.go
Labels: cncf-cla: yes, size/XS, approved, ok-to-test

#16069 Kicbase: Update base image to Ubuntu 22.04
  .github/workflows/update-ubuntu-version.yml
  deploy/kicbase/Dockerfile
  hack/update/ubuntu_version/update_ubuntu_version.go
  pkg/drivers/kic/types.go
  pkg/minikube/bootstrapper/images/images.go
  pkg/minikube/cruntime/crio.go
  site/content/en/docs/commands/start.md
  test/integration/addons_test.go
  test/integration/functional_test.go
  test/integration/testdata/csi-hostpath-driver/pv-pod-restore.yaml
  test/integration/testdata/csi-hostpath-driver/pv-pod.yaml
  test/integration/testdata/inaccel.yaml
  test/integration/testdata/mysql.yaml
  test/integration/testdata/nginx-gvisor.yaml
  test/integration/testdata/nginx-pod-svc.yaml
  test/integration/testdata/nginx-untrusted.yaml
  test/integration/testdata/storage-provisioner/pod.yaml
  test/integration/testdata/testsvc.yaml
Labels: cncf-cla: yes, size/L, approved, ok-to-test

#16506 Kicbase/ISO: Update cri-dockerd from v0.3.1 to v0.3.2
  .github/workflows/master.yml
  .github/workflows/pr.yml
  Makefile
  deploy/iso/minikube-iso/arch/aarch64/package/cri-dockerd-aarch64/cri-dockerd.hash
  deploy/iso/minikube-iso/arch/aarch64/package/cri-dockerd-aarch64/cri-dockerd.mk
  deploy/iso/minikube-iso/arch/x86_64/package/cri-dockerd/cri-dockerd.hash
  deploy/iso/minikube-iso/arch/x86_64/package/cri-dockerd/cri-dockerd.mk
  deploy/kicbase/Dockerfile
  hack/jenkins/linux_integration_tests_none.sh
  pkg/drivers/kic/types.go
  pkg/minikube/download/iso.go
  site/content/en/docs/commands/start.md
Labels: cncf-cla: yes, size/M, lgtm, approved, ok-to-test

#16534 Bump github.com/docker/docker from 23.0.6+incompatible to 24.0.0+incompatible
  go.mod
  go.sum
  third_party/go-dockerclient/tar.go
Labels: cncf-cla: yes, size/S, approved, ok-to-test

#16533 squash kick layers
  deploy/kicbase/Dockerfile
  pkg/drivers/kic/types.go
  site/content/en/docs/commands/start.md
Labels: cncf-cla: yes, size/S, approved, ok-to-test

#16540 Upgrade Headlamp version to 0.17.1
  pkg/minikube/assets/addons.go
Labels: cncf-cla: yes, size/XS, ok-to-test

#16527 Update docker url in README
  site/content/en/docs/drivers/docker.md
Labels: cncf-cla: yes, size/XS, needs-ok-to-test

#16543 audit log: set default max size
  pkg/minikube/audit/audit.go
Labels: cncf-cla: yes, size/XS, approved, ok-to-test

#16563 Add list of Kubernetes versions
  pkg/minikube/constants/constants_kubernetes_versions.go
Labels: cncf-cla: yes, size/L, approved

#16555 CI: Automate updating CNI plugins in kicbase
  hack/update/cni_plugins_version/update_cni_plugins_version.go
Labels: cncf-cla: yes, size/XS, approved

#16574 Add more Chinese translations
  translations/zh-CN.json
Labels: cncf-cla: yes, size/S, needs-ok-to-test

#16573 addons GCP-Auth: Update gcp-auth-webhook image from v0.0.14 to v0.1.0
  pkg/minikube/assets/addons.go
Labels: cncf-cla: yes, size/XS, approved, ok-to-test

#16434 CI: Build arm64 kvm image on actual arm64
  Makefile
  installers/linux/kvm/Dockerfile.arm64
Labels: cncf-cla: yes, size/M, approved, ok-to-test

#16588 CI: Automate updating gcp-auth-webhook image
  .github/workflows/update-gcp-auth-version.yml
  Makefile
  hack/update/gcp_auth_version/update_gcp_auth_version.go
  hack/update/get_version/get_version.go
  hack/update/golang_version/update_golang_version.go
  pkg/minikube/assets/addons.go
Labels: cncf-cla: yes, size/L, approved

#16596 CNI Calico: Update from v3.25.1 to v3.26.0
  pkg/minikube/bootstrapper/images/images.go
  pkg/minikube/cni/calico.yaml
Labels: cncf-cla: yes, size/L, approved, ok-to-test

#16597 CNI Flannel: Update from v0.21.5 to v0.22.0
  pkg/minikube/cni/flannel.yaml
Labels: cncf-cla: yes, size/XS, approved, ok-to-test

#16601 ingress addon: Update controller & kube-webhook-certgen images
  pkg/minikube/assets/addons.go
Labels: cncf-cla: yes, size/S, approved, ok-to-test
