Repository kubernetes/minikube, pull requests merged in 2023-01, with the labels that each got.

#15528 Don't redownload kicbase when already loaded
  pkg/minikube/download/download_test.go
  pkg/minikube/download/image.go
  pkg/minikube/node/cache.go
Labels: cncf-cla: yes, size/L, approved, ok-to-test

#15560 Fix Docker tunnel failing
  pkg/minikube/tunnel/kic/ssh_conn.go
Labels: cncf-cla: yes, size/S, approved, ok-to-test

#15558 site: fix tabs CSS, echo-server images, added ingress Docker Desktop step
  site/content/en/docs/handbook/accessing.md
  site/content/en/docs/handbook/deploying.md
  site/content/en/docs/handbook/kubectl.md
  site/content/en/docs/start/_index.md
  site/content/en/docs/tutorials/ambassador_ingress_controller.md
  site/static/css/tabs.css
Labels: cncf-cla: yes, size/M, approved

#15530 Added `--subnet` validation
  cmd/minikube/cmd/start.go
  cmd/minikube/cmd/start_test.go
  pkg/network/network.go
  pkg/network/network_test.go
Labels: cncf-cla: yes, size/L, approved, needs-ok-to-test

#15591 site: Fix YAML in multi-node page
  site/content/en/docs/tutorials/includes/hello-deployment.yaml
  site/content/en/docs/tutorials/includes/hello-svc.yaml
  site/content/en/docs/tutorials/includes/kube-flannel.yaml
  site/content/en/docs/tutorials/multi_node.md
Labels: cncf-cla: yes, size/XL, approved

#15571 refactor: avoiding repetitive code
  pkg/minikube/registry/global.go
Labels: cncf-cla: yes, size/S, approved, needs-ok-to-test

#15422 Update Japanese translation
  translations/ja.json
Labels: cncf-cla: yes, size/S, lgtm, approved

#15553 Implement --static-ip flag
  cmd/minikube/cmd/start.go
  cmd/minikube/cmd/start_flags.go
  cmd/minikube/cmd/start_test.go
  pkg/drivers/kic/kic.go
  pkg/drivers/kic/oci/network_create.go
  pkg/drivers/kic/types.go
  pkg/minikube/config/types.go
  pkg/minikube/reason/reason.go
  pkg/minikube/registry/drvs/docker/docker.go
  site/content/en/docs/commands/start.md
  site/content/en/docs/contrib/errorcodes.en.md
  site/content/en/docs/contrib/tests.en.md
  site/content/en/docs/faq/_index.md
  site/content/en/docs/tutorials/static_ip.md
  test/integration/kic_custom_network_test.go
  translations/de.json
  translations/es.json
  translations/fr.json
  translations/ja.json
  translations/ko.json
  translations/pl.json
  translations/ru.json
  translations/strings.txt
  translations/zh-CN.json
Labels: cncf-cla: yes, size/L, approved, ok-to-test

#15622 Use `IsPrivate` function provided by `net` pkg
  pkg/network/network.go
  pkg/network/network_test.go
Labels: cncf-cla: yes, size/M, approved, needs-ok-to-test

#15625 Adding a note for the default profile name to use for the Docker Desktop Replacement examples
  site/content/en/docs/tutorials/docker_desktop_replacement.md
Labels: cncf-cla: yes, size/XS, needs-ok-to-test

#15482 Remove progress bar for kic download when JSON output
  pkg/minikube/download/image.go
Labels: cncf-cla: yes, size/XS, approved

#15628 Update kvm docker machine base image
  Makefile
  hack/jenkins/minikube_cross_build_and_upload.sh
  installers/linux/kvm/Dockerfile.amd64
Labels: cncf-cla: yes, size/S, approved, ok-to-test

#15627 Use the correct port number
  site/content/en/docs/start/_index.md
Labels: cncf-cla: yes, size/XS, needs-ok-to-test

#15658 Fix french translation
  translations/fr.json
Labels: cncf-cla: yes, size/XS, needs-ok-to-test

#15450 CI: add functional_docker_rootless_containerd_ubuntu
  .github/workflows/pr.yml
  cmd/minikube/main.go
  go.mod
  go.sum
  pkg/minikube/image/cache.go
  test/integration/functional_test_mount_test.go
  test/integration/main_test.go
Labels: cncf-cla: yes, size/L, ok-to-test

#15630 Update buildkit to v0.11.0
  deploy/kicbase/Dockerfile
  pkg/drivers/kic/types.go
  site/content/en/docs/commands/start.md
Labels: cncf-cla: yes, size/S, approved, ok-to-test

#15556 Remove experimental markings from QEMU driver
  pkg/minikube/registry/drvs/qemu2/qemu2.go
  site/content/en/docs/drivers/_index.md
  site/content/en/docs/drivers/qemu.md
Labels: cncf-cla: yes, size/S, approved

#15610 Allow running none driver with force on 1 CPU
  pkg/minikube/bootstrapper/kubeadm/kubeadm.go
Labels: cncf-cla: yes, size/XS, approved

#15611 Allow running docker driver with force on 1 CPU
  cmd/minikube/cmd/node_start.go
  cmd/minikube/cmd/start.go
  pkg/minikube/node/advice.go
  pkg/minikube/node/start.go
Labels: cncf-cla: yes, size/S, approved

#15661 site: Add "--extra-config=kubeadm.skip-phases=preflight" to FAQ
  site/content/en/docs/faq/_index.md
Labels: cncf-cla: yes, size/XS, approved

#15666 Add gcp-auth to logs output if enabled
  pkg/minikube/logs/logs.go
Labels: cncf-cla: yes, size/XS, approved

#15646 Add check for Docker Desktop 4.16.0
  pkg/minikube/registry/drvs/docker/docker.go
  pkg/minikube/registry/drvs/docker/docker_test.go
Labels: cncf-cla: yes, size/M, approved, ok-to-test

#15642 Use absolute path when calling crictl version
  pkg/minikube/node/start.go
Labels: cncf-cla: yes, size/XS, approved, ok-to-test

#15667 Update cloud-spanner-emulator from 1.4.8 to 1.4.9
  pkg/minikube/assets/addons.go
Labels: cncf-cla: yes, size/XS, approved, ok-to-test

#15668 Updates knative minimum resource requirements
  site/content/en/docs/faq/_index.md
Labels: cncf-cla: yes, size/XS

#15692 Revert "Special case port mapping publish on macOS"
  pkg/drivers/kic/oci/oci.go
Labels: cncf-cla: yes, size/XS, approved

#15541 ISO: Update docker, containerd, and cri-dockerd
  .github/workflows/master.yml
  .github/workflows/pr.yml
  Makefile
  deploy/iso/minikube-iso/arch/aarch64/package/containerd-bin-aarch64/containerd-bin.hash
  deploy/iso/minikube-iso/arch/aarch64/package/containerd-bin-aarch64/containerd-bin.mk
  deploy/iso/minikube-iso/arch/aarch64/package/cri-dockerd-aarch64/cri-dockerd.hash
  deploy/iso/minikube-iso/arch/aarch64/package/cri-dockerd-aarch64/cri-dockerd.mk
  deploy/iso/minikube-iso/arch/aarch64/package/docker-bin-aarch64/docker-bin.hash
  deploy/iso/minikube-iso/arch/aarch64/package/docker-bin-aarch64/docker-bin.mk
  deploy/iso/minikube-iso/arch/x86_64/package/containerd-bin/containerd-bin.hash
  deploy/iso/minikube-iso/arch/x86_64/package/containerd-bin/containerd-bin.mk
  deploy/iso/minikube-iso/arch/x86_64/package/cri-dockerd/cri-dockerd.hash
  deploy/iso/minikube-iso/arch/x86_64/package/cri-dockerd/cri-dockerd.mk
  deploy/iso/minikube-iso/arch/x86_64/package/docker-bin/docker-bin.hash
  deploy/iso/minikube-iso/arch/x86_64/package/docker-bin/docker-bin.mk
  deploy/kicbase/Dockerfile
  hack/jenkins/linux_integration_tests_none.sh
  hack/update/cri_dockerd_version/update_cri_dockerd_version.go
  hack/update/cri_dockerd_version/update_cri_dockerd_version.sh
  pkg/drivers/kic/oci/network_create.go
  pkg/drivers/kic/types.go
  pkg/minikube/bootstrapper/bsutil/kubeadm.go
  pkg/minikube/cruntime/containerd.go
  pkg/minikube/cruntime/cruntime.go
  pkg/minikube/cruntime/docker.go
  pkg/minikube/download/iso.go
  site/content/en/docs/commands/start.md
Labels: cncf-cla: yes, size/L, approved, ok-to-test

#15624 Warn users if using VirtualBox on macOS 13+
  cmd/minikube/cmd/start.go
  pkg/minikube/detect/detect.go
  translations/de.json
  translations/es.json
  translations/fr.json
  translations/ja.json
  translations/ko.json
  translations/pl.json
  translations/ru.json
  translations/strings.txt
  translations/zh-CN.json
Labels: cncf-cla: yes, size/M, approved

#15695 Fix unit test yamls for kubernetes 1.26
  hack/update/kubernetes_version/templates/v1beta3/containerd-api-port.yaml
  hack/update/kubernetes_version/templates/v1beta3/containerd-pod-network-cidr.yaml
  hack/update/kubernetes_version/templates/v1beta3/containerd.yaml
  hack/update/kubernetes_version/templates/v1beta3/crio-options-gates.yaml
  hack/update/kubernetes_version/templates/v1beta3/crio.yaml
  hack/update/kubernetes_version/templates/v1beta3/default.yaml
  hack/update/kubernetes_version/templates/v1beta3/dns.yaml
  hack/update/kubernetes_version/templates/v1beta3/image-repository.yaml
  hack/update/kubernetes_version/templates/v1beta3/options.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.19/containerd-api-port.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.19/containerd-pod-network-cidr.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.19/containerd.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.20/containerd-api-port.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.20/containerd-pod-network-cidr.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.20/containerd.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.21/containerd-api-port.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.21/containerd-pod-network-cidr.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.21/containerd.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.22/containerd-api-port.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.22/containerd-pod-network-cidr.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.22/containerd.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.23/containerd-api-port.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.23/containerd-pod-network-cidr.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.23/containerd.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.24/containerd-api-port.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.24/containerd-pod-network-cidr.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.24/containerd.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.25/containerd-api-port.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.25/containerd-pod-network-cidr.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.25/containerd.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.26/containerd-api-port.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.26/containerd-pod-network-cidr.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.26/containerd.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.26/crio-options-gates.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.26/crio.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.26/default.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.26/dns.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.26/image-repository.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.26/options.yaml
Labels: cncf-cla: yes, size/M, approved, ok-to-test

#15702 CI: Improve automated golang version updating
  .github/workflows/update-docsy-version.yml
  .github/workflows/update-hugo-version.yml
  Makefile
  deploy/addons/auto-pause/Dockerfile
  deploy/iso/minikube-iso/go.hash
  deploy/kicbase/Dockerfile
  hack/update/golang_version/update_golang_version.go
Labels: cncf-cla: yes, size/M, approved

#15701 Check brew install paths for socket_vmnet
  cmd/minikube/cmd/start_flags.go
  pkg/drivers/qemu/qemu.go
  pkg/minikube/detect/detect.go
  pkg/minikube/registry/drvs/qemu2/qemu2.go
  site/content/en/docs/commands/start.md
  translations/de.json
  translations/es.json
  translations/fr.json
  translations/ja.json
  translations/ko.json
  translations/pl.json
  translations/ru.json
  translations/strings.txt
  translations/zh-CN.json
Labels: cncf-cla: yes, size/L, approved

#15706 fix addons map race condition
  pkg/addons/addons.go
  pkg/addons/addons_test.go
  pkg/minikube/node/start.go
Labels: cncf-cla: yes, size/L, approved, ok-to-test

#15703 ISO: update Docker from 20.10.22 to 20.10.23
  Makefile
  deploy/iso/minikube-iso/arch/aarch64/package/docker-bin-aarch64/docker-bin.hash
  deploy/iso/minikube-iso/arch/aarch64/package/docker-bin-aarch64/docker-bin.mk
  deploy/iso/minikube-iso/arch/x86_64/package/docker-bin/docker-bin.hash
  deploy/iso/minikube-iso/arch/x86_64/package/docker-bin/docker-bin.mk
  pkg/drivers/kic/types.go
  pkg/minikube/download/iso.go
  site/content/en/docs/commands/start.md
Labels: cncf-cla: yes, size/S, approved, ok-to-test

#15707 Update cloud-spanner-emulator from 1.4.9 to 1.5.0
  pkg/minikube/assets/addons.go
Labels: cncf-cla: yes, size/XS, approved, ok-to-test

#15686 Add solution message for socket_vmnet permission denied
  pkg/drivers/qemu/qemu.go
  pkg/minikube/reason/known_issues.go
Labels: cncf-cla: yes, size/S, approved

#15716 Release v1.29.0
  CHANGELOG.md
  Makefile
  hack/jenkins/build_iso.sh
  hack/jenkins/kicbase_auto_build.sh
Labels: cncf-cla: yes, size/L, approved, ok-to-test

#15565 ISO: Upgrade podman to 3.4.7
  Makefile
  deploy/iso/minikube-iso/package/podman/podman.hash
  deploy/iso/minikube-iso/package/podman/podman.mk
  pkg/minikube/download/iso.go
Labels: cncf-cla: yes, size/XS, approved, ok-to-test

#15729 Update machine-drivers/machine
  go.mod
  go.sum
Labels: cncf-cla: yes, size/M, approved, ok-to-test
