Repository kubernetes/minikube, pull requests merged in 2024-12, with the labels that each got.

#19985 remove arm64 kvm
  Makefile
  hack/jenkins/minikube_cross_build_and_upload.sh
  hack/jenkins/release_build_and_upload.sh
  pkg/minikube/registry/drvs/kvm2/kvm2.go
Labels: cncf-cla: yes, size/M, approved, ok-to-test

#20043 remove containerd and buildx form build all iso
  .github/workflows/update-iso-image-versions.yml
Labels: cncf-cla: yes, size/XS, approved

#20049 Update _index.md
  site/content/en/docs/contrib/leaderboard/_index.md
Labels: cncf-cla: yes, size/XS, needs-ok-to-test

#20048 Update roadmap.en.md
  site/content/en/docs/contrib/roadmap.en.md
Labels: cncf-cla: yes, size/XS, needs-ok-to-test

#20077 rm nerdctl from iso all build
  .github/workflows/update-iso-image-versions.yml
Labels: cncf-cla: yes, size/XS, approved

#20081 Makefile, fix update-nerdctld-version spelling
  Makefile
Labels: cncf-cla: yes, size/XS, needs-ok-to-test

#20062 fix make by skipping kvm2-arm64 till 19959 is resolved
  Makefile
Labels: cncf-cla: yes, size/S, approved, ok-to-test

#20057 chore: fix some function names in comment
  pkg/addons/addons.go
  pkg/minikube/logs/logs.go
  test/integration/main_test.go
Labels: cncf-cla: yes, size/XS, needs-ok-to-test

#20045 Revert "Change MINIKUBE_HOME logic"
  pkg/minikube/kubeconfig/kubeconfig_test.go
  pkg/minikube/localpath/localpath.go
  pkg/minikube/localpath/localpath_test.go
Labels: cncf-cla: yes, size/S, approved, ok-to-test

#19900 auto-pause: restart service after configuration
  cmd/minikube/cmd/config/configure.go
  cmd/minikube/cmd/config/profile_list.go
Labels: cncf-cla: yes, size/M, approved

#20088 fix newest-cni tests: remove deprecated flag and removed feature gate
  test/integration/start_stop_delete_test.go
Labels: cncf-cla: yes, size/XS, approved, ok-to-test

#19758 fix timeout when stopping KVM machine with CRI-O container runtime
  pkg/drivers/kvm/domain.go
  pkg/drivers/kvm/kvm.go
  pkg/drivers/kvm/network.go
Labels: cncf-cla: yes, size/L, lgtm, approved, ok-to-test

#20116 Fix french translation
  translations/fr.json
Labels: cncf-cla: yes, size/XS, lgtm, approved, needs-ok-to-test

#20126 docs: Fix outdated Github Actions URL
  site/content/en/docs/tutorials/setup_minikube_in_github_actions.md
Labels: cncf-cla: yes, size/XS, needs-ok-to-test

#19545 Merge nvidia-gpu-device-plugin and nvidia-device-plugin.
  pkg/addons/addons.go
  pkg/addons/config.go
  site/content/en/docs/tutorials/nvidia.md
Labels: cncf-cla: yes, size/XS, approved, ok-to-test
