Repository kubernetes/minikube, pull requests merged in 2024-01, with the labels that each got.

#17905 docs: fixed broken nvidia link in Readme
  README.md
Labels: cncf-cla: yes, size/XS, needs-ok-to-test

#17869 CI: Build auto-pause-hook for all architectures
  Makefile
  deploy/addons/auto-pause/Dockerfile
  hack/update/golang_version/update_golang_version.go
Labels: cncf-cla: yes, size/S, approved

#17865 Build(deps): Update semver to v4
  go.mod
  go.sum
  pkg/minikube/machine/start.go
  pkg/minikube/registry/drvs/qemu2/qemu2.go
Labels: cncf-cla: yes, size/XS, approved

#17902 site: Build improvements to the site
  Makefile
  netlify.toml
  site/config.toml
Labels: cncf-cla: yes, size/S, approved

#17830 Kicbase: Fix modifying Docker binfmt config
  deploy/kicbase/Dockerfile
  pkg/drivers/kic/types.go
  site/content/en/docs/commands/start.md
Labels: cncf-cla: yes, size/XS, approved, ok-to-test

#17658 Fix KVM not detecting containerd preload
  pkg/minikube/cruntime/containerd.go
Labels: cncf-cla: yes, size/S, approved, ok-to-test

#17866 addons: Fix auto-pause addon
  Makefile
  cmd/auto-pause/auto-pause.go
  cmd/minikube/cmd/config/configure.go
  cmd/minikube/cmd/start_flags.go
  pkg/drivers/kic/types.go
  pkg/minikube/assets/addons.go
  pkg/minikube/config/types.go
  pkg/minikube/download/iso.go
  site/content/en/docs/commands/start.md
  translations/es.json
  translations/ja.json
  translations/ko.json
  translations/pl.json
  translations/ru.json
  translations/strings.txt
Labels: cncf-cla: yes, size/M, approved, ok-to-test

#17907 fix "Failed to enable container runtime: sudo systemctl restart cri-docker"
  pkg/minikube/cruntime/docker.go
Labels: cncf-cla: yes, size/S, approved, ok-to-test

#17903 CI: Automate updating node version (for website)
  .github/workflows/update-site-node-version.yml
  Makefile
  hack/update/get_version/get_version.go
  hack/update/go_github_version/update_go_github_version.go
  hack/update/site_node_version/update_site_node_version.go
Labels: cncf-cla: yes, size/L, approved

#17929 CI: Build new prow image
  Makefile
Labels: cncf-cla: yes, size/XS, approved

#17937 Fix broken doc url
  enhancements/implemented/20190925-minikube-enhancement-process/README.md
Labels: cncf-cla: yes, size/XS, lgtm

#17935 isolate k8s version testruns and fix images cache path
  test/integration/aaa_download_only_test.go
Labels: cncf-cla: yes, size/M, approved, ok-to-test

#17944 bump legacyVersion to v1.26.0 from 2022-06-23
  test/integration/version_upgrade_test.go
Labels: cncf-cla: yes, size/S, approved, ok-to-test

#17969 fix PingHostFrom2Pods integration test by adding NET_RAW capabilities
  test/integration/testdata/multinodes/multinode-pod-dns-test.yaml
Labels: cncf-cla: yes, size/XS, approved, ok-to-test

#17967 kvm with containerd needs more time to stop
  pkg/drivers/kvm/kvm.go
Labels: cncf-cla: yes, size/M, approved, ok-to-test

#17973 CI: Fix Go auto update PR title
  hack/update/get_version/get_version.go
Labels: cncf-cla: yes, size/XS, approved

#17989 Fix misleading error messages in TestCopyBinary
  pkg/minikube/machine/cache_binaries_test.go
Labels: cncf-cla: yes, size/XS, approved, needs-ok-to-test

#18019 Fix french translation
  translations/fr.json
Labels: cncf-cla: yes, size/XS, approved, needs-ok-to-test

#18007 Move errors getting logs into log output itself
  cmd/minikube/cmd/logs.go
  pkg/minikube/logs/logs.go
  test/integration/functional_test.go
Labels: cncf-cla: yes, size/S, approved, ok-to-test

#17814 Add SECURITY-INSIGHTS.yml
  SECURITY-INSIGHTS.yml
  site/content/en/docs/contrib/releasing/binaries.md
Labels: cncf-cla: yes, size/M

#18060 Nit fixes
  SECURITY-INSIGHTS.yml
  site/content/en/docs/handbook/network_policy.md
Labels: cncf-cla: yes, size/S

#17965 out.FatalT should be followed by non-zero exit
  cmd/minikube/cmd/delete.go
  cmd/minikube/cmd/node_stop.go
  cmd/minikube/cmd/service.go
  cmd/minikube/cmd/service_list.go
  pkg/minikube/out/out.go
Labels: cncf-cla: yes, size/S, approved, ok-to-test
