Repository kubernetes/minikube, pull requests merged in 2024-05, with the labels that each got.

#18779 ISO: enable CONFIG_EXT4_FS_SECURITY in arm64
  Makefile
  deploy/iso/minikube-iso/board/minikube/aarch64/linux_aarch64_defconfig
  pkg/minikube/download/iso.go
Labels: cncf-cla: yes, size/XS, approved, ok-to-test

#18785 Addons: Only template `.tmpl` files
  pkg/minikube/assets/vm_assets.go
Labels: cncf-cla: yes, size/S, approved, ok-to-test

#18793 Addon headlamp: Update headlamp-k8s/headlamp image from v0.23.1 to v0.23.2
  pkg/minikube/assets/addons.go
Labels: cncf-cla: yes, size/XS, ok-to-test

#18774 bump kube-vip to v0.8.0
  pkg/minikube/cluster/ha/kube-vip/kube-vip.go
Labels: cncf-cla: yes, size/XS, approved, ok-to-test

#18832 ISO: Add 50-fs-inotify.conf to increase limits
  Makefile
  deploy/iso/minikube-iso/board/minikube/aarch64/rootfs-overlay/etc/sysctl.d/50-fs-inotify.conf
  deploy/iso/minikube-iso/board/minikube/x86_64/rootfs-overlay/etc/sysctl.d/50-fs-inotify.conf
  pkg/minikube/download/iso.go
Labels: cncf-cla: yes, size/S, approved, ok-to-test

#18830 ISO: Add 50-dnssec.conf to fix DNSSEC issue
  deploy/iso/minikube-iso/board/minikube/aarch64/rootfs-overlay/etc/systemd/resolved.conf.d/50-dnssec.conf
  deploy/iso/minikube-iso/board/minikube/x86_64/rootfs-overlay/etc/systemd/resolved.conf.d/50-dnssec.conf
Labels: cncf-cla: yes, size/XS, approved

#18853 site: Fix broken link to Kong documentation
  site/content/en/docs/handbook/addons/kong-ingress.md
Labels: cncf-cla: yes, size/XS, needs-ok-to-test

#18846 CNI cilium: Fix and update to v1.15.3
  .github/workflows/update-cilium-version.yml
  Makefile
  hack/update/cilium_version/update_cilium_version.go
  hack/update/get_version/get_version.go
  pkg/minikube/cni/cilium.go
  pkg/minikube/cni/cilium.yaml
Labels: cncf-cla: yes, size/XXL, approved, ok-to-test

#18840 Release v1.33.1
  CHANGELOG.md
  Makefile
Labels: cncf-cla: yes, size/M, approved, ok-to-test

#18879 CI: Fix RPM build failing when stripping cross compiled binary
  installers/linux/rpm/minikube_rpm_template/minikube.spec
Labels: cncf-cla: yes, size/XS, approved

#18886 CI: Fix golang auto update not building kicbase image
  .github/workflows/update-golang-version.yml
Labels: cncf-cla: yes, size/XS, approved

#18896 ISO: Update cni-plugins v1.4.1 SHAs
  Makefile
  deploy/iso/minikube-iso/arch/aarch64/package/cni-plugins-latest-aarch64/cni-plugins-latest.hash
  deploy/iso/minikube-iso/arch/x86_64/package/cni-plugins-latest/cni-plugins-latest.hash
  pkg/minikube/download/iso.go
Labels: cncf-cla: yes, size/XS, approved, ok-to-test

#18920 kvm2 driver: Don't delete the "default" libvirt network
  pkg/drivers/kvm/network.go
Labels: cncf-cla: yes, size/XS, approved, ok-to-test

#18942 Site: Corrected minor typo. (issue #18941)
  site/content/en/docs/contrib/testing.en.md
Labels: cncf-cla: yes, size/S, approved, needs-ok-to-test

#18948 CI: Build RPM builds concurrently
  hack/jenkins/release_build_and_upload.sh
Labels: cncf-cla: yes, size/XS, approved

#18916 update translations/zh-CN.json
  translations/zh-CN.json
Labels: cncf-cla: yes, size/S, lgtm, approved, needs-ok-to-test

#18728 site: Add instructions for Linux OS systemd-resolved to ingress-dns documentation
  site/content/en/docs/handbook/addons/ingress-dns.md
Labels: cncf-cla: yes, size/M, needs-ok-to-test

#18977 site: made tabs view linkable #18956
  site/layouts/shortcodes/quiz_button.html
  site/layouts/shortcodes/quiz_instruction.html
  site/layouts/shortcodes/quiz_row.html
  site/static/js/quiz.js
  site/static/js/tabs.js
Labels: cncf-cla: yes, size/L, lgtm, approved, needs-ok-to-test

#18958 skip boilerplate check for minikube-image-benchmark submodule
  test.sh
Labels: cncf-cla: yes, size/XS, approved

#18982 Fix for linkable tabs ui breaking
  site/layouts/shortcodes/quiz_button.html
  site/layouts/shortcodes/quiz_instruction.html
  site/layouts/shortcodes/quiz_row.html
  site/static/js/quiz.js
  site/static/js/tabs.js
Labels: cncf-cla: yes, size/L, needs-ok-to-test

#18981 changed exit codes ExHostUnsupported from 38 to 36 as per code review.
  pkg/minikube/reason/exitcodes.go
Labels: cncf-cla: yes, size/XS, approved, ok-to-test
