Repository kubernetes/minikube, pull requests merged in 2024-09, with the labels that each got.

#19423 Add new macOS vfkit driver, like hyperkit and qemu
  cmd/minikube/cmd/start_flags.go
  hack/jenkins/common.sh
  hack/jenkins/minikube_set_pending.sh
  hack/jenkins/osx_integration_tests_vfkit.sh
  pkg/drivers/vfkit/vfkit.go
  pkg/minikube/cluster/ip.go
  pkg/minikube/driver/driver.go
  pkg/minikube/driver/driver_darwin.go
  pkg/minikube/registry/drvs/init.go
  pkg/minikube/registry/drvs/vfkit/doc.go
  pkg/minikube/registry/drvs/vfkit/vfkit.go
  site/content/en/docs/drivers/_index.md
  site/content/en/docs/drivers/vfkit.md
Labels: cncf-cla: yes, size/XL, approved, ok-to-test

#19574 CI: Remove VFKit from integration list until job is actually setup
  hack/jenkins/minikube_set_pending.sh
Labels: cncf-cla: yes, size/XS, approved

#19575 Release v1.34.0
  CHANGELOG.md
  Makefile
Labels: cncf-cla: yes, size/L, approved, ok-to-test

#19576 Disallow using Docker Desktop 4.34.0 on macos
  CHANGELOG.md
  pkg/minikube/registry/drvs/docker/docker.go
Labels: cncf-cla: yes, size/S, approved, ok-to-test

#19596 Fix wrong version in changelog
  CHANGELOG.md
Labels: cncf-cla: yes, size/XS, approved

#19602 CI: Fix yearly leaderboard updates failures
  .github/workflows/yearly-leaderboard.yml
Labels: cncf-cla: yes, size/XS, approved

#19603 site: Backfill yearly leaderboard updates
  site/content/en/docs/contrib/leaderboard/2024.html
Labels: cncf-cla: yes, size/L, approved

#19581 Update nginx_tcp_udp_ingress.md
  site/content/en/docs/tutorials/nginx_tcp_udp_ingress.md
Labels: cncf-cla: yes, size/XS, needs-ok-to-test

#19641 site: Update that containerd CRI supports docker-env
  site/content/en/docs/handbook/pushing.md
Labels: cncf-cla: yes, size/XS, approved

#19570 Addon headlamp: Update headlamp-k8s/headlamp image from v0.25.0 to v0.25.1
  pkg/minikube/assets/addons.go
Labels: cncf-cla: yes, size/XS, approved, ok-to-test

#19654 Fix french translation
  translations/fr.json
Labels: cncf-cla: yes, size/S, needs-ok-to-test

#19659 remove deadlink
  site/content/en/docs/tutorials/continuous_integration.md
Labels: cncf-cla: yes, size/XS, approved

#19642 CI: Generate package list after building kicbase
  hack/jenkins/kicbase_auto_build.sh
  hack/kicbase_version/os-package-list.txt
Labels: cncf-cla: yes, size/L, approved

#18998 unified minikube cluster status query
  cmd/minikube/cmd/config/profile_list.go
  cmd/minikube/cmd/status.go
  cmd/minikube/cmd/status_test.go
  pkg/minikube/cluster/status.go
  test/integration/ha_test.go
  test/integration/multinode_test.go
  test/integration/pause_test.go
  test/integration/status_test.go
Labels: cncf-cla: yes, size/XXL, lgtm, ok-to-test

#19669 CI: Remove brew upgrade script
  hack/jenkins/release_update_brew.sh
Labels: cncf-cla: yes, size/M, needs-ok-to-test

#19636 remove helm-tiller addon
  deploy/addons/aliyun_mirror.json
  deploy/addons/assets.go
  deploy/addons/helm-tiller/README.md
  deploy/addons/helm-tiller/helm-tiller-dp.yaml.tmpl
  deploy/addons/helm-tiller/helm-tiller-rbac.yaml
  deploy/addons/helm-tiller/helm-tiller-svc.yaml
  pkg/addons/config.go
  pkg/minikube/assets/addons.go
  site/content/en/docs/contrib/tests.en.md
  site/content/en/docs/handbook/addons/helm-tiller.md
  test/integration/addons_test.go
Labels: cncf-cla: yes, size/L, approved, ok-to-test

#19677 Update "Using NVIDIA GPUs with minikube" docs
  site/content/en/docs/tutorials/nvidia.md
Labels: cncf-cla: yes, size/S, needs-ok-to-test

#19664 Fix wrongly detecting kicbase arch as incorrect
  pkg/minikube/download/image.go
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#19711 Addons registry: Update kube-registry-proxy from 0.0.6 to 0.0.7
  pkg/minikube/assets/addons.go
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#19508 Add more Chinese translations
  translations/zh-CN.json
Labels: cncf-cla: yes, size/S, needs-ok-to-test

#19490 Add more Chinese translations
  translations/zh-CN.json
Labels: cncf-cla: yes, size/S, lgtm, needs-ok-to-test

#19712 addons: Use configmap for inspektor-gadget
  deploy/addons/inspektor-gadget/ig-configmap.yaml
  deploy/addons/inspektor-gadget/ig-daemonset.yaml.tmpl
  pkg/minikube/assets/addons.go
Labels: cncf-cla: yes, size/M, approved, ok-to-test

#19709 CI: Update hide-minikube-bot-comments action
  .github/workflows/hide-minikube-bot-comments.yml
Labels: cncf-cla: yes, size/XS, approved

#19718 translations: Fix translation on wrong line
  translations/zh-CN.json
Labels: cncf-cla: yes, size/XS, approved

#19731 Add missing quotes around podman_ubuntu e2e test
  .github/workflows/pr.yml
Labels: cncf-cla: yes, size/XS, lgtm, approved

#19722 HA (multi-control plane) docs: use installed kubectl version in examples
  site/content/en/docs/tutorials/multi_control_plane_ha_clusters.md
Labels: cncf-cla: yes, size/XS, approved

#19728 don't pollute minikube profile list with errors if exitcode is absent
  pkg/minikube/cluster/status.go
Labels: cncf-cla: yes, size/S, approved

#19727 fix cluster status check in TestMultiControlPlane
  pkg/minikube/cluster/status.go
  test/integration/ha_test.go
Labels: cncf-cla: yes, size/S, approved, ok-to-test

#19724 HA (multi-control plane): Automate kube-vip version update
  .github/workflows/update-kube-vip-version.yml
  Makefile
  hack/update/get_version/get_version.go
  hack/update/kube_vip_version/update_kube_vip_version.go
  pkg/minikube/cluster/ha/kube-vip/kube-vip.go
Labels: cncf-cla: yes, size/L, approved
