Repository kubernetes/minikube, pull requests merged in 2024-08, with the labels that each got.

#19356 add -d shorthand for --driver
  cmd/minikube/cmd/start_flags.go
Labels: cncf-cla: yes, size/XS, approved, ok-to-test

#19349 Addon headlamp: Update headlamp-k8s/headlamp image from v0.24.1 to v0.25.0
  pkg/minikube/assets/addons.go
Labels: cncf-cla: yes, size/XS, approved, ok-to-test

#19386 fix lint
  cmd/minikube/cmd/config/images.go
Labels: cncf-cla: yes, size/XS, approved

#19373 Add Parallels driver support for darwin/arm64
  go.mod
  go.sum
  pkg/minikube/driver/driver_darwin.go
Labels: cncf-cla: yes, size/XS, ok-to-test

#19312 fix: fix empty tarball when generating image save
  pkg/minikube/cruntime/containerd.go
  pkg/minikube/cruntime/cri.go
  pkg/minikube/cruntime/docker.go
  pkg/minikube/image/image.go
  pkg/minikube/machine/cache_images.go
  test/integration/functional_test.go
Labels: cncf-cla: yes, size/M, ok-to-test

#19404 Correct link title of Storage Provisioner Gluster addon markdown document
  site/content/en/docs/handbook/addons/storage-provisioner-gluster.md
Labels: cncf-cla: yes, size/XS, needs-ok-to-test

#19420 Fix lint
  pkg/minikube/cruntime/docker.go
Labels: cncf-cla: yes, size/XS, approved

#19399 Update roadmap for 2023-2024
  site/content/en/docs/contrib/roadmap.en.md
Labels: cncf-cla: yes, size/S, approved

#19459 CI: Check if sed is GNU or BSD version.
  Makefile
Labels: cncf-cla: yes, size/S, approved, needs-ok-to-test

#19454 Upgrade minikube-machine for dependencies
  go.mod
  go.sum
Labels: cncf-cla: yes, size/S, approved, ok-to-test

#19468 Move ExtractFile from hyperkit to drivers
  pkg/drivers/hyperkit/driver.go
  pkg/drivers/iso.go
  pkg/drivers/iso_test.go
  pkg/drivers/iso_test.iso
Labels: cncf-cla: yes, size/XS, approved, ok-to-test

#19345 Set `NVIDIA_DRIVER_CAPABILITIES` to `all` when GPU is enabled
  pkg/drivers/kic/oci/oci.go
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#19402 Updated tutorial steps
  site/content/en/docs/tutorials/kubernetes_101/module5.md
Labels: cncf-cla: yes, size/S, approved, needs-ok-to-test

#19462 Debug Cloud Shell tests not uploading results
  hack/jenkins/common.sh
Labels: cncf-cla: yes, size/S, approved, ok-to-test

#19511 Remove crio-wipe service that is not required
  Makefile
  deploy/iso/minikube-iso/package/crio-bin/crio-bin.mk
  deploy/iso/minikube-iso/package/crio-bin/crio-wipe.service
  deploy/iso/minikube-iso/package/crio-bin/crio.service
  pkg/drivers/kic/types.go
  pkg/minikube/download/iso.go
  site/content/en/docs/commands/start.md
Labels: cncf-cla: yes, size/M, ok-to-test

#19523 CI: Fix Cloud Shell not writing results to DB
  hack/jenkins/cloud_shell_functional_tests_docker.sh
Labels: cncf-cla: yes, size/XS, approved

#19524 CI: Fix Cloud Shell not saving to DB
  hack/jenkins/cloud_shell_functional_tests_docker.sh
Labels: cncf-cla: yes, size/S, approved

#19531 Use `sudo -n` if `--interactive=false`
  pkg/minikube/firewall/firewall.go
Labels: cncf-cla: yes, size/XS, approved, ok-to-test
