Repository kubernetes/minikube, pull requests merged in 2024-07, with the labels that each got.

#19157 update translations/zh-CN.json
  translations/zh-CN.json
Labels: cncf-cla: yes, size/S, needs-ok-to-test

#19159 feat: update volcano addon to 1.9
  deploy/addons/volcano/volcano-development.yaml.tmpl
  pkg/minikube/assets/addons.go
  test/integration/addons_test.go
  test/integration/testdata/vcjob.yaml
Labels: cncf-cla: yes, size/XXL, ok-to-test

#19181 Remove deprecated RSS feed from repo security tab
  SECURITY.md
Labels: cncf-cla: yes, size/XS, lgtm, approved

#19180 CI: Auto update volcano addon YAML
  hack/update/volcano_version/update_volcano_version.go
Labels: cncf-cla: yes, size/S, lgtm, approved

#19192 abort virtual box macos test if not x86 arch
  .github/workflows/master.yml
  .github/workflows/pr.yml
Labels: cncf-cla: yes, size/S, approved

#19198 addons ingress-dns: Update image to support multi-arch
  pkg/minikube/assets/addons.go
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#19193 Output error for `Unable to load the current Docker config from`
  cmd/minikube/main.go
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#19182 testing: Use multi-arch example app image
  deploy/addons/ingress-dns/example/example.yaml
  test/integration/testdata/ingress-dns-example-v1.yaml
  test/integration/testdata/ingress-dns-example-v1beta1.yaml
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#19191 Fixed not creating API server tunnel
  pkg/minikube/bootstrapper/kubeadm/kubeadm.go
Labels: cncf-cla: yes, size/XS, approved, ok-to-test

#19195 addons: Fail when enabling KVM addons on non-KVM cluster
  pkg/addons/config.go
  pkg/addons/validations.go
  pkg/addons/validations_test.go
Labels: cncf-cla: yes, size/M, approved, ok-to-test

#19217 add -c shorthand for --container-runtime
  cmd/minikube/cmd/start_flags.go
Labels: cncf-cla: yes, size/XS, approved, ok-to-test

#19231 bump all github action runners to ubuntu 22.04 LTS
  .github/workflows/build.yml
  .github/workflows/docs.yml
  .github/workflows/functional_verified.yml
  .github/workflows/hide-minikube-bot-comments.yml
  .github/workflows/leaderboard.yml
  .github/workflows/master.yml
  .github/workflows/minikube-image-benchmark.yml
  .github/workflows/pr.yml
  .github/workflows/time-to-k8s-public-chart.yml
  .github/workflows/time-to-k8s.yml
  .github/workflows/translations.yml
  .github/workflows/twitter-bot.yml
  .github/workflows/update-buildkit-version.yml
  .github/workflows/update-calico-version.yml
  .github/workflows/update-cilium-version.yml
  .github/workflows/update-cloud-spanner-emulator-version.yml
  .github/workflows/update-cni-plugins-version.yml
  .github/workflows/update-containerd-version.yml
  .github/workflows/update-cri-dockerd-version.yml
  .github/workflows/update-cri-o-version.yml
  .github/workflows/update-crictl-version.yml
  .github/workflows/update-crun-version.yml
  .github/workflows/update-docker-buildx-version.yml
  .github/workflows/update-docker-version.yml
  .github/workflows/update-docsy-version.yml
  .github/workflows/update-flannel-version.yml
  .github/workflows/update-gcp-auth-version.yml
  .github/workflows/update-gh-version.yml
  .github/workflows/update-go-github-version.yml
  .github/workflows/update-golang-version.yml
  .github/workflows/update-golint-version.yml
  .github/workflows/update-gopogh-version.yml
  .github/workflows/update-gotestsum-version.yml
  .github/workflows/update-hugo-version.yml
  .github/workflows/update-ingress-version.yml
  .github/workflows/update-inspektor-gadget-version.yml
  .github/workflows/update-iso-image-versions.yml
  .github/workflows/update-istio-operator.yml
  .github/workflows/update-k8s-versions.yml
  .github/workflows/update-kindnetd-version.yml
  .github/workflows/update-kong-ingress-controller-version.yml
  .github/workflows/update-kong-version.yml
  .github/workflows/update-kubeadm-constants.yml
  .github/workflows/update-kubectl-version.yml
  .github/workflows/update-kubernetes-versions-list.yml
  .github/workflows/update-metrics-server-version.yml
  .github/workflows/update-nerdctl-version.yml
  .github/workflows/update-nerdctld-version.yml
  .github/workflows/update-nvidia-device-plugin-version.yml
  .github/workflows/update-registry-version.yml
  .github/workflows/update-runc-version.yml
  .github/workflows/update-site-node-version.yml
  .github/workflows/update-ubuntu-version.yml
  .github/workflows/update-volcano-version.yml
  .github/workflows/update-yakd-version.yml
  .github/workflows/vex.yml
  .github/workflows/yearly-leaderboard.yml
Labels: cncf-cla: yes, size/L, approved

#19240 fix: fix missing go.mod for comment bot
  hack/jenkins/test-flake-chart/report_flakes.sh
  hack/jenkins/test-flake-chart/report_flakes/go.mod
  hack/jenkins/test-flake-chart/report_flakes/go.sum
Labels: cncf-cla: yes, size/L, approved

#19243 Auto detect OS Architecture in Installation doc
  site/static/js/quiz.js
Labels: cncf-cla: yes, size/S, approved, needs-ok-to-test

#19255 remove virtualbox tests from github actions
  .github/workflows/master.yml
  .github/workflows/pr.yml
Labels: cncf-cla: yes, size/L, approved

#18062 Revamp minikube website footer
  site/config.toml
  site/layouts/partials/footer.html
Labels: cncf-cla: yes, size/M, lifecycle/stale

#18859 feat: check connectivity outside minikube once it fails
  pkg/minikube/node/start.go
Labels: cncf-cla: yes, size/M, approved, ok-to-test

#19267 CI: Remove extra bracket from script
  hack/jenkins/test-flake-chart/sync_tests.sh
Labels: cncf-cla: yes, size/XS, approved

#19270 CI: Fix flake rate commenting
  hack/jenkins/test-flake-chart/sync_tests.sh
Labels: cncf-cla: yes, size/XS, approved

#19268 CI: Fix golang install
  hack/jenkins/test-flake-chart/process_last_90/process_last_90.sh
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#19205 Improvements for using x86 binary on arm64 machine
  pkg/minikube/detect/detect.go
  pkg/minikube/download/binary.go
  pkg/minikube/download/image.go
  pkg/minikube/download/preload.go
  pkg/minikube/machine/cache_binaries.go
  pkg/minikube/node/cache.go
  pkg/minikube/registry/drvs/docker/docker.go
Labels: cncf-cla: yes, size/M, approved, ok-to-test

#19228 Support running x86 QEMU on arm64
  pkg/drivers/qemu/qemu.go
  pkg/minikube/registry/drvs/qemu2/qemu2.go
Labels: cncf-cla: yes, size/M, approved

#19254 Replace ReplicationController with Deployment in addons
  deploy/addons/efk/elasticsearch-rc.yaml.tmpl
  deploy/addons/efk/fluentd-es-rc.yaml.tmpl
  deploy/addons/efk/kibana-rc.yaml.tmpl
  deploy/addons/freshpod/freshpod-rc.yaml.tmpl
  deploy/addons/registry/registry-rc.yaml.tmpl
  pkg/kapi/kapi.go
  test/integration/addons_test.go
Labels: cncf-cla: yes, size/M, approved, ok-to-test

#19289 site: Fix typo
  site/content/en/docs/tutorials/kubernetes_101/module3.md
Labels: cncf-cla: yes, size/XS, lgtm, approved

#18648 Update MINIKUBE_HOME usage
  pkg/minikube/kubeconfig/kubeconfig_test.go
  pkg/minikube/localpath/localpath.go
  pkg/minikube/localpath/localpath_test.go
Labels: cncf-cla: yes, size/S, approved, ok-to-test

#19301 CI: Update macOS deps via cron
  hack/jenkins/cron/cleanup_and_reboot_Darwin.sh
Labels: cncf-cla: yes, size/XS, approved

#19304 Fix typo: s/Virtulization/Virtualization/g
  site/content/en/docs/drivers/kvm2.md
Labels: cncf-cla: yes, size/XS, needs-ok-to-test

#19310 Update required Go version in building docs
  site/content/en/docs/contrib/building/binaries.md
  site/content/en/docs/contrib/building/iso.md
Labels: cncf-cla: yes, size/XS, needs-ok-to-test

#18487 ISO: Add docker-buildx
  .github/workflows/update-iso-image-versions.yml
  Makefile
  deploy/iso/minikube-iso/arch/aarch64/package/Config.in
  deploy/iso/minikube-iso/arch/aarch64/package/docker-buildx-aarch64/Config.in
  deploy/iso/minikube-iso/arch/aarch64/package/docker-buildx-aarch64/docker-buildx.hash
  deploy/iso/minikube-iso/arch/aarch64/package/docker-buildx-aarch64/docker-buildx.mk
  deploy/iso/minikube-iso/arch/x86_64/package/Config.in
  deploy/iso/minikube-iso/arch/x86_64/package/docker-buildx/Config.in
  deploy/iso/minikube-iso/arch/x86_64/package/docker-buildx/docker-buildx.hash
  deploy/iso/minikube-iso/arch/x86_64/package/docker-buildx/docker-buildx.mk
  hack/update/get_version/get_version.go
  pkg/minikube/download/iso.go
Labels: cncf-cla: yes, size/L, approved, ok-to-test

#19316 Remove unnecessary dependency for build on Fedora
  site/content/en/docs/contrib/building/binaries.md
  site/content/en/docs/contrib/building/iso.md
Labels: cncf-cla: yes, size/S, needs-ok-to-test

#19287 testing: Fix volcano addon failing other addons
  test/integration/addons_test.go
Labels: cncf-cla: yes, size/M, lgtm, approved, ok-to-test

#16900 config: transform os.ENOENT error into config.ErrNotExist
  pkg/minikube/config/profile.go
Labels: cncf-cla: yes, size/XS, lifecycle/stale, ok-to-test
