Repository kubernetes/minikube, pull requests merged in 2025-07, with the labels that each got.

#20991 iso: Improve build and clean up configuration
  Makefile
  deploy/iso/minikube-iso/board/minikube/aarch64/linux_aarch64_defconfig
  deploy/iso/minikube-iso/board/minikube/x86_64/linux_x86_64_defconfig
  deploy/iso/minikube-iso/configs/minikube_aarch64_defconfig
  deploy/iso/minikube-iso/configs/minikube_x86_64_defconfig
  pkg/minikube/download/iso.go
  site/content/en/docs/commands/start.md
Labels: cncf-cla: yes, size/XL, ok-to-test

#21016 Update OWNERS: adding nirs to reviewers
  OWNERS
Labels: cncf-cla: yes, size/XS, approved, do-not-merge/invalid-owners-file

#21019 build: Update xcgo image to v2
  Makefile
Labels: cncf-cla: yes, size/XS, approved, ok-to-test

#21027 ci: login to docker during build process
  hack/jenkins/minikube_cross_build_and_upload.sh
Labels: cncf-cla: yes, size/XS, approved, ok-to-test

#20372 CI: Auto update Headlamp image
  .github/workflows/update-headlamp-version.yml
  Makefile
  hack/update/headlamp_version/update_headlamp_version.go
Labels: cncf-cla: yes, size/L, approved, needs-ok-to-test

#21042 ci: login to docker in downstream jobs
  hack/jenkins/common.sh
Labels: cncf-cla: yes, size/XS, approved, ok-to-test

#20995 iso: Update to longterm kernel to 6.6.95
  Makefile
  deploy/iso/minikube-iso/arch/x86_64/package/hyperv-daemons/hyperv-daemons.mk
  deploy/iso/minikube-iso/board/minikube/aarch64/linux_aarch64_defconfig
  deploy/iso/minikube-iso/board/minikube/x86_64/linux_x86_64_defconfig
  deploy/iso/minikube-iso/configs/minikube_aarch64_defconfig
  deploy/iso/minikube-iso/configs/minikube_x86_64_defconfig
  pkg/minikube/download/iso.go
Labels: cncf-cla: yes, size/L, ok-to-test

#20820 Suppress progress bar for Kubernetes version retrieval
  hack/jenkins/common.ps1
Labels: cncf-cla: yes, size/XS, approved, ok-to-test

#21061 add go.work to separate hack folder
  Makefile
  go.work
  go.work.sum
  hack/go.mod
  hack/go.sum
Labels: cncf-cla: yes, size/L, approved

#21062 fix dirty commit version
  .gitignore
  hack/jenkins/release_build_and_upload.sh
Labels: cncf-cla: yes, size/S, approved

#21059 test: use alpine for gvsior image in testdata
  test/integration/testdata/gvisor-addon-Dockerfile
Labels: cncf-cla: yes, size/XS, approved, ok-to-test

#21024 Deprecate HyperKit driver with warning
  cmd/minikube/cmd/start.go
  pkg/minikube/driver/driver.go
  pkg/minikube/registry/drvs/hyperkit/hyperkit.go
Labels: cncf-cla: yes, size/M, lgtm, approved, ok-to-test

#21077 Fix mount to same folder causing Input/output error
  go.work.sum
  pkg/minikube/cluster/mount.go
Labels: cncf-cla: yes, size/S, approved, ok-to-test

#21085 docs: Update vment-helper installation
  site/content/en/docs/drivers/vfkit.md
Labels: cncf-cla: yes, size/XS, approved, needs-ok-to-test

#21095 ci: add smoke test to github action
  .github/workflows/smoke-test.yml
  pkg/drivers/hyperkit/driver.go
  pkg/drivers/qemu/qemu.go
  pkg/drivers/vfkit/vfkit.go
  pkg/minikube/detect/detect.go
Labels: cncf-cla: yes, size/L, approved

#21096 vfkit: Add vfkit.log
  pkg/drivers/vfkit/vfkit.go
Labels: cncf-cla: yes, size/S, approved, ok-to-test

#21089 iso: Fix `minikube stop` with vfkit and krunkit drivers
  Makefile
  deploy/iso/minikube-iso/board/minikube/aarch64/linux_aarch64_defconfig
  pkg/minikube/download/iso.go
Labels: cncf-cla: yes, size/L, ok-to-test

#21083 Manually bump runc version to v1.3.0
  go.mod
  go.sum
  go.work.sum
  pkg/drivers/kic/oci/cgroups_linux.go
Labels: cncf-cla: yes, size/M, lgtm, approved, ok-to-test

#21100 vfkit: Restore compatibility with x86_64
  pkg/drivers/vfkit/vfkit.go
Labels: cncf-cla: yes, size/M, ok-to-test

#21102 ci: Add vfkit smoke test
  .github/workflows/smoke-test.yml
Labels: cncf-cla: yes, size/M, approved, needs-ok-to-test

#21119 bump winget gihtub action
  .github/workflows/winget.yml
Labels: cncf-cla: yes, size/XS, approved

#20893 Refactor table rendering
  cmd/minikube/cmd/config/addons_list.go
  cmd/minikube/cmd/config/addons_list_test.go
  cmd/minikube/cmd/config/images.go
  cmd/minikube/cmd/config/profile_list.go
  go.mod
  go.sum
  go.work.sum
  hack/benchmark/time-to-k8s/chart.go
  hack/benchmark/time-to-k8s/cpu.go
  hack/go.mod
  hack/go.sum
  pkg/drivers/hyperkit/driver.go
  pkg/drivers/vfkit/vfkit.go
  pkg/minikube/audit/row.go
  pkg/minikube/machine/cache_images.go
  pkg/minikube/perf/result_manager.go
  pkg/minikube/service/service.go
  pkg/minikube/service/service_test.go
  test/integration/functional_test.go
Labels: cncf-cla: yes, size/L, lgtm, approved, ok-to-test

#21115 replace spinner lib to upstream
  go.mod
  go.sum
  go.work.sum
  hack/go.mod
  hack/go.sum
Labels: cncf-cla: yes, size/L, approved, ok-to-test

#21103 optimize memory usage in image load with Docker client integration
  pkg/minikube/image/cache.go
  pkg/minikube/image/image.go
Labels: cncf-cla: yes, size/M, lgtm, approved, ok-to-test

#21146 Revert "optimize memory usage in image load with Docker client integration"
  pkg/minikube/image/cache.go
  pkg/minikube/image/image.go
Labels: cncf-cla: yes, size/M, approved

#21176 CI: fix PR update titles missing version
  Makefile
Labels: cncf-cla: yes, size/XS, approved

#21147 iso: Enable VirtioFS for x86_64 and aarch64
  Makefile
  deploy/iso/minikube-iso/board/minikube/aarch64/linux_aarch64_defconfig
  deploy/iso/minikube-iso/board/minikube/x86_64/linux_x86_64_defconfig
  pkg/minikube/download/iso.go
Labels: cncf-cla: yes, size/XS, ok-to-test

#21111 vfkit: Extract isoPath() helper
  pkg/drivers/vfkit/vfkit.go
Labels: cncf-cla: yes, size/S, approved, ok-to-test

#21182 ci: get dep version fix
  hack/update/get_version/get_version.go
Labels: cncf-cla: yes, size/XS, approved

#21187 gomod: remove replace for k8s.io/cluster-bootstrap
  go.mod
  go.sum
  hack/go.mod
  hack/go.sum
Labels: cncf-cla: yes, size/M, approved, ok-to-test

#21141 Rename hack module
  hack/go.mod
  hack/update/amd_device_plugin_version/update_amd_device_plugin_version.go
  hack/update/buildkit_version/update_buildkit_version.go
  hack/update/calico_version/update_calico_version.go
  hack/update/cilium_version/update_cilium_version.go
  hack/update/cloud_spanner_emulator_version/update_cloud_spanner_emulator_version.go
  hack/update/cni_plugins_version/update_cni_plugins_version.go
  hack/update/containerd_version/update_containerd_version.go
  hack/update/cri-o_version/update_cri-o_version.go
  hack/update/cri_dockerd_version/update_cri_dockerd_version.go
  hack/update/crictl_version/update_crictl_version.go
  hack/update/crun_version/update_crun_version.go
  hack/update/docker_buildx_version/update_docker_buildx_version.go
  hack/update/docker_version/update_docker_version.go
  hack/update/docsy_version/update_docsy_version.go
  hack/update/flannel_version/update_flannel_version.go
  hack/update/gcp_auth_version/update_gcp_auth_version.go
  hack/update/gh_version/update_gh_version.go
  hack/update/go_github_version/update_go_github_version.go
  hack/update/golang_version/update_golang_version.go
  hack/update/golint_version/update_golint_version.go
  hack/update/gopogh_version/update_gopogh_version.go
  hack/update/gotestsum_version/update_gotestsum_version.go
  hack/update/headlamp_version/update_headlamp_version.go
  hack/update/hugo_version/update_hugo_version.go
  hack/update/ingress_version/update_ingress_version.go
  hack/update/inspektor_gadget_version/update_inspektor_gadget_version.go
  hack/update/istio_operator_version/update_istio_operator_version.go
  hack/update/kicbase_version/update_kicbase_version.go
  hack/update/kindnetd_version/update_kindnetd_version.go
  hack/update/kong_ingress_controller_version/update_kong_ingress_controller_version.go
  hack/update/kong_version/update_kong_version.go
  hack/update/kube_registry_proxy_version/update_kube_registry_proxy_version.go
  hack/update/kube_vip_version/update_kube_vip_version.go
  hack/update/kubeadm_constants/update_kubeadm_constants.go
  hack/update/kubectl_version/update_kubectl_version.go
  hack/update/kubernetes_version/update_kubernetes_version.go
  hack/update/kubernetes_versions_list/update_kubernetes_versions_list.go
  hack/update/metrics_server_version/update_metrics_server_version.go
  hack/update/nerdctl_version/update_nerdctl_version.go
  hack/update/nerdctld_version/update_nerdctld_version.go
  hack/update/nvidia_device_plugin_version/update_nvidia_device_plugin_version.go
  hack/update/preload_version/update_preload_version.go
  hack/update/registry_version/update_registry_version.go
  hack/update/runc_version/update_runc_version.go
  hack/update/site_node_version/update_site_node_version.go
  hack/update/ubuntu_version/update_ubuntu_version.go
  hack/update/volcano_version/update_volcano_version.go
  hack/update/yakd_version/update_yakd_version.go
Labels: cncf-cla: yes, size/M, approved, needs-ok-to-test

#21189 ci: use authenticated github when possible
  hack/preload-images/kubernetes.go
  hack/update/github.go
  hack/update/go_github_version/update_go_github_version.go
  hack/update/ingress_version/update_ingress_version.go
  hack/update/kubeadm_constants/update_kubeadm_constants.go
  hack/update/kubernetes_versions_list/update_kubernetes_versions_list.go
  hack/update/site_node_version/update_site_node_version.go
Labels: cncf-cla: yes, size/M, approved

#20992 Add `--disable-coredns-log` flag
  cmd/minikube/cmd/start_flags.go
  pkg/minikube/config/types.go
  pkg/minikube/node/start.go
Labels: cncf-cla: yes, size/S, approved, ok-to-test

#21203 chore: add site public to gitignore
  .gitignore
Labels: cncf-cla: yes, size/XS, approved

#21209 Updated site/readme.md outdated documentation
  site/README.md
Labels: cncf-cla: yes, size/M, approved, needs-ok-to-test
