Repository kubernetes/minikube, pull requests merged in 2025-05, with the labels that each got.

#20501 Shared network for vfkit driver using vmnet-helper
  cmd/minikube/cmd/start_flags.go
  pkg/drivers/vfkit/vfkit.go
  pkg/drivers/vmnet/vmnet.go
  pkg/drivers/vmnet/vmnet_stub.go
  pkg/minikube/driver/driver.go
  pkg/minikube/reason/reason.go
  pkg/minikube/registry/drvs/vfkit/vfkit.go
  site/content/en/docs/drivers/vfkit.md
Labels: cncf-cla: yes, size/XL, lgtm, approved, ok-to-test

#20658 migrate golangci lint to v2
  .golangci.yaml
  Makefile
Labels: cncf-cla: yes, size/L, approved, ok-to-test

#20720 Kicbase/ISO: Update buildroot from 2023.02.9 to 2025.2
  Makefile
  deploy/iso/minikube-iso/arch/aarch64/package/cri-dockerd-aarch64/cri-dockerd.mk
  deploy/iso/minikube-iso/arch/aarch64/package/docker-buildx-aarch64/docker-buildx.mk
  deploy/iso/minikube-iso/arch/x86_64/package/cri-dockerd/cri-dockerd.mk
  deploy/iso/minikube-iso/arch/x86_64/package/docker-buildx/docker-buildx.mk
  deploy/iso/minikube-iso/go.hash
  deploy/iso/minikube-iso/package/Config.in
  deploy/iso/minikube-iso/package/conmon/Config.in
  deploy/iso/minikube-iso/package/conmon/conmon.hash
  deploy/iso/minikube-iso/package/conmon/conmon.mk
  deploy/iso/minikube-iso/package/crio-bin/crio.conf
  deploy/iso/minikube-iso/package/falco-module/Config.in
  deploy/iso/minikube-iso/package/falco-module/falco-module.hash
  deploy/iso/minikube-iso/package/falco-module/falco-module.mk
  deploy/iso/minikube-iso/package/podman/podman.mk
  pkg/minikube/cruntime/cruntime_test.go
  pkg/minikube/cruntime/docker.go
  pkg/minikube/download/iso.go
  pkg/minikube/sysinit/openrc.go
  pkg/minikube/sysinit/sysinit.go
  pkg/minikube/sysinit/systemd.go
Labels: cncf-cla: yes, size/L, lgtm, approved, ok-to-test

#20255 New flag to allow option for passing a config file for addon configure command.
  cmd/minikube/cmd/config/configure.go
  cmd/minikube/cmd/config/configure_registry_creds.go
  site/content/en/docs/commands/addons.md
  site/content/en/docs/contrib/tests.en.md
  test/integration/addons_test.go
  test/integration/testdata/addons_testconfig.json
  translations/de.json
  translations/es.json
  translations/fr.json
  translations/id.json
  translations/ja.json
  translations/ko.json
  translations/pl.json
  translations/ru.json
  translations/strings.txt
  translations/zh-CN.json
Labels: cncf-cla: yes, size/XL, lgtm, approved, ok-to-test, do-not-merge/invalid-commit-message

#20746 build: Use jammy based xcgo image for hyperkit
  Makefile
Labels: cncf-cla: yes, size/S, lgtm, approved, ok-to-test

#20648 fix bug in parsing proxies with dashes
  pkg/minikube/node/config.go
  pkg/minikube/node/start.go
  pkg/minikube/proxy/proxy.go
  pkg/minikube/proxy/proxy_test.go
  pkg/util/utils.go
  pkg/util/utils_test.go
Labels: cncf-cla: yes, size/L, lgtm, approved, ok-to-test

#20761 fix: reference missing files in schema (Closes #20752)
  hack/update/cni_plugins_version/update_cni_plugins_version.go
Labels: cncf-cla: yes, size/S, lgtm, approved, needs-ok-to-test, do-not-merge/invalid-commit-message

#20685 Update qemu.md docs for homebrew/services decommission
  site/content/en/docs/drivers/qemu.md
Labels: cncf-cla: yes, size/XS, approved, needs-ok-to-test

#20679 Update service tests to use discoveryv1.EndpointSlice instead of deprecated core.Endpoints
  pkg/minikube/service/service_test.go
Labels: cncf-cla: yes, size/L, lgtm, ok-to-test, do-not-merge/invalid-commit-message

#20769 CI: Fix cni escaping
  hack/update/cni_plugins_version/update_cni_plugins_version.go
Labels: cncf-cla: yes, size/XS, approved, needs-ok-to-test

#20760 CI: make "bump all ISO/image workflow" configurable
  .github/workflows/update-iso-image-versions.yml
Labels: cncf-cla: yes, size/S, lgtm, approved

#20781 Prevent Unnecessary Version Bumps in `go.mod` During Go Version Updates
  hack/update/golang_version/update_golang_version.go
Labels: cncf-cla: yes, size/S, approved, needs-ok-to-test, do-not-merge/invalid-commit-message

#20574 docs: improved Invoke-WebRequest command
  site/content/en/docs/start/_index.md
Labels: cncf-cla: yes, size/XS, approved, ok-to-test

#20808 vfkit: Bump to Preferred driver on macOs
  pkg/minikube/registry/drvs/vfkit/vfkit.go
Labels: cncf-cla: yes, size/XS, lgtm, approved, ok-to-test

#20814 site: Add example to ingress tutorial
  site/content/en/docs/tutorials/nginx_tcp_udp_ingress.md
Labels: cncf-cla: yes, size/S, lgtm, approved, needs-ok-to-test

#20815 vfkit: Minor docs, test, and help fixes
  cmd/minikube/cmd/start_flags.go
  hack/jenkins/osx_integration_tests_vfkit.sh
  site/content/en/docs/drivers/_index.md
Labels: cncf-cla: yes, size/XS, approved, needs-ok-to-test

#20821 add changelog for minikube 1.36.0
  CHANGELOG.md
  Makefile
Labels: cncf-cla: yes, size/M, approved, ok-to-test

#20830 docs: Fix instructions for building iso
  site/content/en/docs/contrib/building/iso.md
Labels: cncf-cla: yes, size/M, approved, needs-ok-to-test
