Repository kubernetes/minikube, pull requests merged in 2025-08, with the labels that each got.

#21214 ci: skip boilerplate for git submodules
  hack/boilerplate/boilerplate.go
Labels: cncf-cla: yes, size/XS, approved

#21213 ci: update all with go
  .github/workflows/update-all.yml
  .github/workflows/update-amd-gpu-device-plugin-version.yml
  .github/workflows/update-cloud-spanner-emulator-version.yml
  .github/workflows/update-golang-version.yml
  Makefile
  hack/update/amd_device_gpu_plugin_version/amd_device_gpu_plugin_version.go
  hack/update/buildkit_version/buildkit_version.go
  hack/update/calico_version/calico_version.go
  hack/update/cilium_version/cilium_version.go
  hack/update/cloud_spanner_emulator_version/cloud_spanner_emulator_version.go
  hack/update/cni_plugins_version/cni_plugins_version.go
  hack/update/containerd_version/containerd_version.go
  hack/update/cri_dockerd_version/cri_dockerd_version.go
  hack/update/cri_o_version/cri_o_version.go
  hack/update/crictl_version/crictl_version.go
  hack/update/crun_version/crun_version.go
  hack/update/docker_buildx_version/docker_buildx_version.go
  hack/update/docker_version/docker_version.go
  hack/update/docsy_version/docsy_version.go
  hack/update/flannel_version/flannel_version.go
  hack/update/gcp_auth_version/gcp_auth_version.go
  hack/update/get_version/get_version.go
  hack/update/gh_version/gh_version.go
  hack/update/go_github_version/go_github_version.go
  hack/update/golang_version/golang_version.go
  hack/update/golint_version/golint_version.go
  hack/update/gopogh_version/gopogh_version.go
  hack/update/gotestsum_version/gotestsum_version.go
  hack/update/headlamp_version/headlamp_version.go
  hack/update/hugo_version/hugo_version.go
  hack/update/ingress_version/ingress_version.go
  hack/update/inspektor_gadget_version/inspektor_gadget_version.go
  hack/update/istio_operator_version/istio_operator_version.go
  hack/update/kicbase_version/kicbase_version.go
  hack/update/kindnetd_version/kindnetd_version.go
  hack/update/kong_ingress_controller_version/kong_ingress_controller_version.go
  hack/update/kong_version/kong_version.go
  hack/update/kube_registry_proxy_version/kube_registry_proxy_version.go
  hack/update/kube_vip_version/kube_vip_version.go
  hack/update/kubeadm_constants/kubeadm_constants.go
  hack/update/kubectl_version/kubectl_version.go
  hack/update/kubernetes_version/kubernetes_version.go
  hack/update/kubernetes_versions_list/kubernetes_versions_list.go
  hack/update/metrics_server_version/metrics_server_version.go
  hack/update/nerdctl_version/nerdctl_version.go
  hack/update/nerdctld_version/nerdctld_version.go
  hack/update/nvidia_device_plugin_version/nvidia_device_plugin_version.go
  hack/update/preload_version/preload_version.go
  hack/update/registry_version/registry_version.go
  hack/update/runc_version/runc_version.go
  hack/update/site_node_version/site_node_version.go
  hack/update/ubuntu_version/ubuntu_version.go
  hack/update/update.go
  hack/update/update_all/update_all.go
  hack/update/volcano_version/volcano_version.go
  hack/update/yakd_version/yakd_version.go
Labels: cncf-cla: yes, size/L, approved

#21212 CI: remove not needed replaces in gomod and add automation
  .github/workflows/go-mod-tidy.yml
  Makefile
  go.mod
  hack/go.mod
  hack/go.sum
  site/content/en/docs/contrib/building/binaries.md
Labels: cncf-cla: yes, size/L, approved, ok-to-test

#21247 CI: updater add site_node_version to not supported before after version
  hack/update/update_all/update_all.go
Labels: cncf-cla: yes, size/XS, approved

#21215 Refactor spinner library & hide sub steps after spinning
  pkg/minikube/out/out.go
  pkg/minikube/out/out_reason.go
  pkg/minikube/out/out_style.go
  pkg/minikube/out/out_style_test.go
  pkg/minikube/out/out_test.go
  pkg/minikube/registry/drvs/krunkit/krunkit.go
  pkg/minikube/style/style.go
  test/integration/error_spam_test.go
Labels: cncf-cla: yes, size/L, approved, ok-to-test

#20959 Add support to docker runtime for OCI access to NVIDIA GPUs
  cmd/minikube/cmd/start.go
  cmd/minikube/cmd/start_test.go
  pkg/drivers/kic/oci/oci.go
  pkg/minikube/cruntime/docker.go
  site/content/en/docs/commands/start.md
  site/content/en/docs/tutorials/nvidia.md
Labels: cncf-cla: yes, size/S, approved, ok-to-test

#21266 drivers: Extract drivers/common package
  cmd/minikube/cmd/start_flags.go
  pkg/drivers/common/common.go
  pkg/drivers/common/common_test.go
  pkg/drivers/common/iso.go
  pkg/drivers/common/iso_test.go
  pkg/drivers/common/testdata/test.iso
  pkg/drivers/common/vmnet/vmnet.go
  pkg/drivers/common/vmnet/vmnet_error.go
  pkg/drivers/common/vmnet/vmnet_stub.go
  pkg/drivers/hyperkit/driver.go
  pkg/drivers/kic/kic.go
  pkg/drivers/krunkit/krunkit.go
  pkg/drivers/kvm/kvm.go
  pkg/drivers/none/none.go
  pkg/drivers/qemu/qemu.go
  pkg/drivers/ssh/ssh.go
  pkg/drivers/vfkit/vfkit.go
  pkg/minikube/registry/drvs/krunkit/krunkit.go
  pkg/minikube/registry/drvs/vfkit/vfkit.go
Labels: cncf-cla: yes, size/L, ok-to-test

#21265 feat: Add version checking for all components in noVersionCheck
  hack/update/get_version/get_version.go
  hack/update/update_all/update_all.go
Labels: cncf-cla: yes, size/L, approved, needs-ok-to-test

#21174 improve docker service reliability, update docker systemd files
  pkg/minikube/cruntime/cruntime_test.go
  pkg/minikube/cruntime/docker.go
  pkg/provision/buildroot.go
  pkg/provision/ubuntu.go
Labels: cncf-cla: yes, size/M, approved, ok-to-test

#21274 ci: add qemu functional test to github action on macos13
  .github/workflows/master.yml
  .github/workflows/pr.yml
  test/integration/functional_test_pvc_test.go
Labels: cncf-cla: yes, size/L, approved

#21277 Fix update kubeadm constants
  hack/update/kubeadm_constants/kubeadm_constants.go
Labels: cncf-cla: yes, size/XS, approved

#21278 remove deprecated proxy-refresh-interval v2 etcd flag
  hack/update/kubernetes_version/templates/v1beta4/containerd-api-port.yaml
  hack/update/kubernetes_version/templates/v1beta4/containerd-pod-network-cidr.yaml
  hack/update/kubernetes_version/templates/v1beta4/containerd.yaml
  hack/update/kubernetes_version/templates/v1beta4/crio-options-gates.yaml
  hack/update/kubernetes_version/templates/v1beta4/crio.yaml
  hack/update/kubernetes_version/templates/v1beta4/default.yaml
  hack/update/kubernetes_version/templates/v1beta4/dns.yaml
  hack/update/kubernetes_version/templates/v1beta4/image-repository.yaml
  hack/update/kubernetes_version/templates/v1beta4/options.yaml
  pkg/minikube/bootstrapper/bsutil/ktmpl/v1beta4.go
  pkg/minikube/bootstrapper/bsutil/testdata/v1.31/containerd-api-port.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.31/containerd-pod-network-cidr.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.31/containerd.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.31/crio-options-gates.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.31/crio.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.31/default.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.31/dns.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.31/image-repository.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.31/options.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.32/containerd-api-port.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.32/containerd-pod-network-cidr.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.32/containerd.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.32/crio-options-gates.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.32/crio.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.32/default.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.32/dns.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.32/image-repository.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.32/options.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.33/containerd-api-port.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.33/containerd-pod-network-cidr.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.33/containerd.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.33/crio-options-gates.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.33/crio.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.33/default.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.33/dns.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.33/image-repository.yaml
  pkg/minikube/bootstrapper/bsutil/testdata/v1.33/options.yaml
Labels: cncf-cla: yes, size/L, approved, ok-to-test

#21304 ci: fix auto go mod tidy
  .github/workflows/go-mod-tidy.yml
Labels: cncf-cla: yes, size/XS, approved

#21244 Upgrade kubetail addon to version 0.13.3
  deploy/addons/kubetail/kubetail-cli.yaml
  deploy/addons/kubetail/kubetail-cluster-agent.yaml.tmpl
  deploy/addons/kubetail/kubetail-cluster-api.yaml.tmpl
  deploy/addons/kubetail/kubetail-dashboard.yaml.tmpl
  pkg/minikube/assets/addons.go
Labels: cncf-cla: yes, size/M, approved, needs-ok-to-test

#21322 github action: dont define both path and path-ignore
  .github/workflows/functional_test.yml
  .github/workflows/smoke-test.yml
  .github/workflows/unit-test.yml
Labels: cncf-cla: yes, size/M, approved

#21337 fix k8s v1.33.3 etcd image version
  pkg/minikube/constants/constants_kubeadm_images.go
Labels: cncf-cla: yes, size/XS, approved

#21372 UI: Improve french translations
  translations/fr.json
Labels: cncf-cla: yes, size/XS, needs-ok-to-test

#21395 avoid conflict with the update package flags
  hack/preload-images/kubernetes.go
Labels: cncf-cla: yes, size/S, approved

#21399 lint: Improve go mod tidy lint step
  .github/workflows/lint.yml
Labels: cncf-cla: yes, size/S, approved

#21430 refactor: change to slices.Collect instead of append loops
  cmd/minikube/cmd/config/addons_list.go
  cmd/minikube/cmd/version.go
  hack/changelog/changelog.go
  pkg/minikube/node/cache.go
  pkg/minikube/registry/registry.go
Labels: cncf-cla: yes, size/M, approved, ok-to-test
